Voxel: Voxel::MainConfigurationFile Class Reference
Voxel::MainConfigurationFile Class Reference
#include <Configuration.h>
Classes
struct ConfigSerialNumberType
Public Types
typedef Function< bool(ConfigSerialNumberType
&, TimeStampType
&, SerializedObject &)> HardwareSerializer
Public Types inherited from Voxel::ConfigurationFile
enum Location { IN_HOST = 0, IN_CAMERA = 1 }
typedef Map< String, ConfigSet > ConfigSetMap
Public Member Functions
MainConfigurationFile (const String &name, const String &hardwareID, HardwareSerializer hardwareReader=nullptr, HardwareSerializer hardwareWriter=nullptr)
virtual bool read (const String &configFile)
bool readFromHardware ()
bool writeToHardware ()
void setHardwareReader (HardwareSerializer hardwareReader)
void setHardwareWriter (HardwareSerializer hardwareWriter)
virtual String get (const String &section, const String &name) const
virtual bool isPresent (const String &section, const String &name, bool includeParent=true) const
int addCameraProfile (const String &profileName, const int parentID)
bool setCurrentCameraProfile (const int id)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (const int id)
ConfigurationFile * getDefaultCameraProfile ()
ConfigurationFile * getCameraProfile (const int id)
template<typename T >
bool getFile (const String &section, const String &name, String &fileName, Vector< T > &data)
int getDefaultCameraProfileID ()
bool setDefaultCameraProfile (const int id)
void setHardwareID (const String &hwID)
int getCurrentProfileID ()
bool getCameraProfileName (const int id, String &cameraProfileName)
const Map< int, String > & getCameraProfileNames ()
virtual ~MainConfigurationFile ()
Public Member Functions inherited from Voxel::ConfigurationFile
Location getLocation () const
void setID (const int id)
template<typename T >
bool getFile (const String &section, const String &name, String &fileName, Vector< T > &data)
int getInteger (const String &section, const String &name) const
float getFloat (const String &section, const String &name) const
bool getBoolean (const String &section, const String &name) const
virtual bool set (const String &section, const String &name, const String &value)
template<typename T >
bool setFile (const String &section, const String &name, const String &fileName, const Vector< T > &data)
bool setInteger (const String &section, const String &name, int value)
bool setFloat (const String &section, const String &name, float value)
bool setBoolean (const String &section, const String &name, bool value)
bool remove (const String &section, const String &name)
virtual bool getConfigSet (const String &section, const ConfigSet *&configSet) const
virtual bool read (InputStream &in)
virtual bool write (const String &configFile="")
virtual bool write (OutputStream &out)
bool isValidCameraProfile ()
virtual bool removeFile ()
void clear ()
const String & getConfigFileName ()
ConfigurationFile ()
ConfigurationFile (MainConfigurationFile *mainConfigurationFile)
ConfigurationFile (const ConfigurationFile &other)
ConfigurationFile & operator= (const ConfigurationFile &other)
bool mergeParentConfiguration ()
ConfigurationFile & copy (const ConfigurationFile &other)
virtual ~ConfigurationFile ()
Protected Member Functions
bool _updateCameraProfileList ()
int _getNewCameraProfileID (bool inHost=true)
Protected Member Functions inherited from Voxel::ConfigurationFile
bool _get (const String &section, const String &name, String &value) const
bool _set (const String &section, const String &name, const String &value)
bool _serializeAllDataFiles (OutputStream &out)
template<typename T >
bool _getData (const String &fileName, Vector< T > &data)
template<typename T >
bool _setData (const String &fileName, const Vector< T > &data)
bool _copyFromParentIfNotPresent (ConfigurationFile *other, bool recurse=true)
Protected Attributes
Map< int, ConfigurationFile > _cameraProfiles
Map< int, String > _cameraProfileNames
int _defaultCameraProfileID
int _defaultCameraProfileIDInHardware
int _currentCameraProfileID
ConfigurationFile * _currentCameraProfile
String _mainConfigName
String _hardwareID
HardwareSerializer _hardwareReader
HardwareSerializer _hardwareWriter
Protected Attributes inherited from Voxel::ConfigurationFile
String _fileName
Map< String, Vector< ByteType > > _dataFiles
MainConfigurationFile * _mainConfigurationFile
int _id
int _parentID
String _profileName
Mutex _mutex
Location _location
Additional Inherited Members
Public Attributes inherited from Voxel::ConfigurationFile
ConfigSetMap configs
Detailed Description
Definition at line 334 of file Configuration.h.
Member Typedef Documentation
typedef Function<bool(ConfigSerialNumberType &, TimeStampType &, SerializedObject &)> Voxel::MainConfigurationFile::HardwareSerializer
Definition at line 351 of file Configuration.h.
Constructor & Destructor Documentation
Voxel::MainConfigurationFile::MainConfigurationFile (const String & name, const String & hardwareID, HardwareSerializer hardwareReader = nullptr, HardwareSerializer hardwareWriter = nullptr) inline
Definition at line 357 of file Configuration.h.
                                                                                                                                                                :
   _currentCameraProfile(nullptr), _defaultCameraProfileID(-1), _defaultCameraProfileIDInHardware(-1), _mainConfigName(name), _hardwareReader(hardwareReader), _hardwareWriter(hardwareWriter) {}
virtual Voxel::MainConfigurationFile::~MainConfigurationFile () inline virtual
Definition at line 400 of file Configuration.h.
 {}
Member Function Documentation
int Voxel::MainConfigurationFile::_getNewCameraProfileID (bool inHost = true) protected
Definition at line 920 of file Configuration.cpp.
References _cameraProfiles, Voxel::ConfigurationFile::IN_CAMERA, and Voxel::ConfigurationFile::IN_HOST.
Referenced by addCameraProfile(), and saveCameraProfileToHardware().
 {
   int maxID = 0;
   for(auto c = _cameraProfiles.begin(); c != _cameraProfiles.end(); c++)
   {
     if((inHost && c->second.getLocation() == ConfigurationFile::IN_CAMERA) || (!inHost && c->second.getLocation() == ConfigurationFile::IN_HOST))
       continue;
     maxID = std::max(maxID, c->first);
   }
   if(inHost && maxID == 0)
     maxID = 128;
   return maxID + 1;
 }
bool Voxel::MainConfigurationFile::_updateCameraProfileList () protected
Definition at line 970 of file Configuration.cpp.
References _cameraProfiles, Voxel::basename(), Voxel::ConfigurationFile::IN_CAMERA, Voxel::ConfigurationFile::set(), and Voxel::ConfigurationFile::write().
Referenced by addCameraProfile(), and removeCameraProfile().
 {
   String n;
   bool first = true;
   for(auto c = _cameraProfiles.begin(); c != _cameraProfiles.end(); c++)
   {
     if(c->second.getLocation() == ConfigurationFile::IN_CAMERA)
       continue;
     if(!first)
       n += ", ";
     first = false;
     n += basename(c->second.getConfigFileName());
   }
   if(!set("core", "camera_profiles", n))
     return false;
   if(!write())
     return false;
   return true;
 }
int Voxel::MainConfigurationFile::addCameraProfile (const String & profileName, const int parentID)
Definition at line 938 of file Configuration.cpp.
References _cameraProfileNames, _cameraProfiles, Voxel::ConfigurationFile::_fileName, _getNewCameraProfileID(), _mainConfigName, _updateCameraProfileList(), Voxel::ConfigurationFile::ConfigurationFile(), Voxel::LOG_WARNING, Voxel::logger, and Voxel::ConfigurationFile::write().
Referenced by Voxel::DepthCamera::addCameraProfile().
 {
   if(_cameraProfiles.find(parentID) == _cameraProfiles.end())
     return -1;
   int id = _getNewCameraProfileID();
   _cameraProfiles[id] = ConfigurationFile(this);
   _cameraProfiles[id].setInteger("global", "id", id);
   _cameraProfiles[id].setInteger("global", "parent", parentID);
   _cameraProfiles[id].set("global", "name", profileName);
   _cameraProfileNames[id] = profileName;
   String fileName = profileName;
   fileName.erase(std::remove(fileName.begin(), fileName.end(), ' '), fileName.end());
   fileName = _mainConfigName + fileName + ".conf";
   if(!_cameraProfiles[id].write(fileName))
   {
     logger(LOG_WARNING) << "MainConfigurationFile: Could not write configuration file for '" << profileName << "' to '" << fileName << "'." << std::endl;
   }
   if(!_updateCameraProfileList())
   {
     logger(LOG_WARNING) << "MainConfigurationFile: Could not update profile list in main configuration file '" << _fileName << "'." << std::endl;
   }
   return id;
 }
String Voxel::MainConfigurationFile::get (const String & section, const String & name) const virtual
Reimplemented from Voxel::ConfigurationFile.
Definition at line 1094 of file Configuration.cpp.
References _currentCameraProfile, and Voxel::ConfigurationFile::_get().
Referenced by Voxel::TI::ToFTintinCamera::_applyCalibrationParams(), Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), Voxel::TI::ToFTintinCamera::_init(), and Voxel::TI::ToFCamera::_initStartParams().
 {
   String value;
   if(_currentCameraProfile && _currentCameraProfile->_get(section, name, value))
   {
     return value;
   }
   if(ConfigurationFile::_get(section, name, value))
     return value;
   return "";
 }
ConfigurationFile * Voxel::MainConfigurationFile::getCameraProfile (const int id)
Definition at line 894 of file Configuration.cpp.
References _cameraProfiles.
Referenced by Voxel::ConfigurationFile::_copyFromParentIfNotPresent(), Voxel::ConfigurationFile::_get(), Voxel::ConfigurationFile::getConfigSet(), getDefaultCameraProfile(), Voxel::ConfigurationFile::isPresent(), Voxel::ConfigurationFile::isValidCameraProfile(), readFromHardware(), saveCameraProfileToHardware(), Voxel::DepthCamera::setCameraProfile(), and setDefaultCameraProfile().
 {
   if(_cameraProfiles.find(id) != _cameraProfiles.end())
   {
     return &_cameraProfiles.at(id);
   }
   return 0;
 }
bool Voxel::MainConfigurationFile::getCameraProfileName (const int id, String & cameraProfileName)
Definition at line 1120 of file Configuration.cpp.
References _cameraProfileNames.
Referenced by Voxel::DepthCamera::setCameraProfile().
 {
   if(_cameraProfileNames.find(id) != _cameraProfileNames.end())
   {
     cameraProfileName = _cameraProfileNames.at(id);
     return true;
   }
   return false;
 }
const Map<int, String>& Voxel::MainConfigurationFile::getCameraProfileNames () inline
Definition at line 398 of file Configuration.h.
 { return _cameraProfileNames; }
int Voxel::MainConfigurationFile::getCurrentProfileID () inline
Definition at line 394 of file Configuration.h.
 { return _currentCameraProfileID; }
ConfigurationFile * Voxel::MainConfigurationFile::getDefaultCameraProfile ()
Definition at line 903 of file Configuration.cpp.
References _defaultCameraProfileID, and getCameraProfile().
 {
   return getCameraProfile(_defaultCameraProfileID);
 }
int Voxel::MainConfigurationFile::getDefaultCameraProfileID () inline
Definition at line 382 of file Configuration.h.
Referenced by Voxel::DepthCamera::_init().
   {
     if(_defaultCameraProfileIDInHardware >= 0)
       return _defaultCameraProfileIDInHardware;
     else
       return _defaultCameraProfileID;
   }
template<typename T > bool Voxel::MainConfigurationFile::getFile (const String & section, const String & name, String & fileName, Vector< T > & data)
Definition at line 404 of file Configuration.h.
References _currentCameraProfile, and Voxel::ConfigurationFile::getFile().
Referenced by Voxel::TI::ToFCamera::_initStartParams().
 {
   if(!_currentCameraProfile || !_currentCameraProfile->getFile(section, name, fileName, data))
     return ConfigurationFile::getFile(section, name, fileName, data);
   else
     return true;
 }
bool Voxel::MainConfigurationFile::isPresent (const String & section, const String & name, bool includeParent = true) const virtual
Reimplemented from Voxel::ConfigurationFile.
Definition at line 1109 of file Configuration.cpp.
References _currentCameraProfile, and Voxel::ConfigurationFile::isPresent().
Referenced by Voxel::TI::ToFHaddockCamera::_applyCalibrationParams(), Voxel::TI::ToFTintinCamera::_applyCalibrationParams(), Voxel::TI::ToFCamera::_getDepthScalingFactor(), Voxel::TI::ToFCamera::_initStartParams(), and read().
 {
   if(_currentCameraProfile && _currentCameraProfile->isPresent(section, name, includeParent))
     return true;
   if(ConfigurationFile::isPresent(section, name, includeParent))
     return true;
   return false;
 }
bool Voxel::MainConfigurationFile::read (const String & configFile) virtual
Reimplemented from Voxel::ConfigurationFile.
Definition at line 821 of file Configuration.cpp.
References _cameraProfileNames, _cameraProfiles, _currentCameraProfile, _currentCameraProfileID, _defaultCameraProfileID, CAMERA_PROFILES, Voxel::ConfigurationFile::get(), Voxel::ConfigurationFile::getInteger(), isPresent(), Voxel::ConfigurationFile::isValidCameraProfile(), Voxel::LOG_ERROR, Voxel::logger, Voxel::ConfigurationFile::read(), setCurrentCameraProfile(), Voxel::split(), and Voxel::trim().
Referenced by Voxel::DepthCamera::DepthCamera().
 {
   if(!ConfigurationFile::read(configFile))
     return false;
   _cameraProfiles.clear();
   _cameraProfileNames.clear();
   _currentCameraProfile = 0;
   _currentCameraProfileID = -1;
   String cameraProfiles;
   if(!isPresent("core", CAMERA_PROFILES))
   {
     logger(LOG_ERROR) << "Could not find 'camera_profiles' in " << configFile << std::endl;
     return false;
   }
   cameraProfiles = get("core", CAMERA_PROFILES);
   Vector<String> cp;
   split(cameraProfiles, ',', cp);
   for(auto i = 0; i < cp.size(); i++)
   {
     const String &profileConfigFile = trim(cp[i]);
     ConfigurationFile cf(this);
     int id;
     if(!cf.read(profileConfigFile))
     {
       logger(LOG_ERROR) << "MainConfigurationFile: Could not read " << profileConfigFile << std::endl;
       return false;
     }
     if(!cf.isValidCameraProfile())
     {
       logger(LOG_ERROR) << "MainConfigurationFile: '" << profileConfigFile << "' is not a valid camera profile." << std::endl;
       return false;
     }
     id = cf.getInteger("global", "id");
     String cameraProfileName = cf.get("global", "name");
     _cameraProfiles[id] = cf;
     _cameraProfileNames[id] = cameraProfileName;
   }
   if(!isPresent("core", "default_profile"))
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Default profile not defined in " << configFile << std::endl;
     return false;
   }
   _defaultCameraProfileID = getInteger("core", "default_profile");
   if(_cameraProfiles.find(_defaultCameraProfileID) == _cameraProfiles.end())
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Default profile not valid in " << configFile << std::endl;
     return false;
   }
   if(!setCurrentCameraProfile(_defaultCameraProfileID))
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Default profile is defined but not found in " << configFile << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::MainConfigurationFile::readFromHardware ()
Definition at line 1131 of file Configuration.cpp.
References _cameraProfileNames, _cameraProfiles, Voxel::ConfigurationFile::_dataFiles, _defaultCameraProfileIDInHardware, Voxel::ConfigurationFile::_fileName, _hardwareID, _hardwareReader, Voxel::ConfigurationFile::_location, Voxel::ConfigurationFile::_profileName, Voxel::SerializedObject::currentGetOffset(), Voxel::Data2DCodec::decompress(), FILE_PREFIX, Voxel::SerializedObject::get(), Voxel::ConfigurationFile::get(), Voxel::SerializedObject::getBytes(), getCameraProfile(), Voxel::Configuration::getConfFile(), Voxel::ConfigurationFile::getInteger(), Voxel::ConfigurationFile::IN_CAMERA, Voxel::ConfigurationFile::isPresent(), Voxel::ConfigurationFile::isValidCameraProfile(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::DataPacket::object, Voxel::ConfigDataPacket::PACKET_2D_DATA_FILE, Voxel::ConfigDataPacket::PACKET_CONFIG, Voxel::DataPacket::read(), Voxel::SerializableString::read(), Voxel::ConfigurationFile::read(), Voxel::SerializedObject::resize(), Voxel::SerializedObject::size(), and Voxel::DataPacket::type.
Referenced by Voxel::DepthCamera::_init().
 {
   SerializedObject so;
   ConfigSerialNumberType serialNumber;
   TimeStampType timestamp = 0;
   Configuration c;
   String f = _hardwareID + ".bin";
   if(!c.getConfFile(f))
     return false;
   InputFileStream fs(f, std::ios::in | std::ios::binary);
   if(fs.good())
   {
     fs.read((char *)&serialNumber, sizeof(serialNumber));
     fs.read((char *)&timestamp, sizeof(timestamp));
   }
   bool ret = false;
   if(!_hardwareReader || !(ret = _hardwareReader(serialNumber, timestamp, so)) || so.size() == 0)
     // Last condition is when the data in hardware and backup file in host are the same...
   {
     if(!ret)
       logger(LOG_ERROR) << "MainConfigurationFile: Failed to read configuration from hardware." << std::endl;
     else if(_hardwareReader && so.size() == 0)
       logger(LOG_INFO) << "MainConfigurationFile: Reading from local copy of hardware configuration data" << std::endl;
     if(!fs.good())
     {
       logger(LOG_ERROR) << "MainConfigurationFile: Could not open file '" << f << "'" << std::endl;
       return false;
     }
     fs.seekg(0, std::ios::end);
     int size = (int)fs.tellg() - sizeof(timestamp) - sizeof(serialNumber);
     if(size == 0)
     {
       logger(LOG_ERROR) << "MainConfigurationFile: Null config data '" << f << "'" << std::endl;
       return false;
     }
     so.resize(size);
     fs.seekg(sizeof(timestamp) + sizeof(serialNumber), std::ios::beg);
     fs.clear();
     fs.read((char *)so.getBytes().data(), size);
   }
   uint8_t defaultProfileID;
   if(so.get((char *)&defaultProfileID, sizeof(defaultProfileID)) != sizeof(defaultProfileID))
     return false;
   while(so.size() > so.currentGetOffset())
   {
     ConfigDataPacket p;
     if(!p.read(so))
     {
       logger(LOG_ERROR) << "MainConfigurationFile: Failed to read configuration packet." << std::endl;
       return false;
     }
     if(p.type == ConfigDataPacket::PACKET_CONFIG)
     {
       ConfigurationFile cf(this);
       int id;
       InputStringStream ss(String(p.object.getBytes().data(), p.object.size()));
       if(!cf.read(ss))
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Could not read profile from hardware" << std::endl;
         return false;
       }
       cf._fileName = _hardwareID + "-" + cf._profileName + ".conf";
       if(!cf.isValidCameraProfile())
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Profile read from hardware, is not a valid camera profile." << std::endl;
         return false;
       }
       cf._location = ConfigurationFile::IN_CAMERA;
       id = cf.getInteger("global", "id");
       String cameraProfileName = cf.get("global", "name");
       _cameraProfiles[id] = cf;
       _cameraProfileNames[id] = cameraProfileName;
     }
     else if(p.type == ConfigDataPacket::PACKET_2D_DATA_FILE)
     {
       uint8_t id;
       if(p.object.get((char *)&id, sizeof(id)) != sizeof(id))
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Could not read 2D data file from hardware" << std::endl;
         return false;
       }
       ConfigurationFile *config = getCameraProfile(id);
       if(!config)
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Invalid camera profile with id = '" << (uint)id << "' found for 2D data file from hardware" << std::endl;
         return false;
       }
       SerializableString s;
       if(!s.read(p.object))
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Could not read section name for 2D data file from hardware" << std::endl;
         return false;
       }
       String section = s;
       if(!s.read(p.object))
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Could not read field name for 2D data file from hardware" << std::endl;
         return false;
       }
       String field = s;
       if(!config->isPresent(section, field))
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Configuration with id = " << id
           << ", does not contain section = " << section << ", field = " << field << std::endl;
         return false;
       }
       String name = config->get(section, field);
       if(name.compare(0, sizeof(FILE_PREFIX) - 1, FILE_PREFIX) != 0)
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Value at section = " << section << ", field = " << field
           << ", in configuration with id = " << id << ", is invalid. Value = " << name << std::endl;
         return false;
       }
       name = name.substr(sizeof(FILE_PREFIX) - 1);
       Data2DCodec codec;
       Data2DCodec::ByteArray in;
       Data2DCodec::Array2D out;
       in.resize(p.object.size() - p.object.currentGetOffset());
       p.object.get((char *)in.data(), in.size());
       if(!codec.decompress(in, out))
       {
         logger(LOG_ERROR) << "MainConfigurationFile: Could not decompress data at section = " << section << ", field = " << field
           << ", in configuration with id = " << id << std::endl;
         return false;
       }
       config->_dataFiles[name].resize(out.size()*sizeof(out[0]));
       memcpy(config->_dataFiles[name].data(), out.data(), out.size()*sizeof(out[0]));
     }
   }
   if(getCameraProfile(defaultProfileID) != 0)
     _defaultCameraProfileIDInHardware = defaultProfileID;
   return true;
 }
bool Voxel::MainConfigurationFile::removeCameraProfile (const int id)
Definition at line 999 of file Configuration.cpp.
References _cameraProfileNames, _cameraProfiles, _currentCameraProfileID, _defaultCameraProfileID, _defaultCameraProfileIDInHardware, Voxel::ConfigurationFile::_fileName, Voxel::ConfigurationFile::_parentID, _updateCameraProfileList(), Voxel::ConfigurationFile::getLocation(), Voxel::ConfigurationFile::IN_CAMERA, Voxel::ConfigurationFile::IN_HOST, Voxel::LOG_ERROR, Voxel::LOG_WARNING, Voxel::logger, Voxel::ConfigurationFile::removeFile(), setCurrentCameraProfile(), setDefaultCameraProfile(), and writeToHardware().
Referenced by Voxel::DepthCamera::removeCameraProfile().
 {
   if(_cameraProfiles.find(id) == _cameraProfiles.end())
     return false;
   ConfigurationFile *c = &_cameraProfiles.at(id);
   ConfigurationFile *parent = 0;
   if(_cameraProfiles.find(c->_parentID) != _cameraProfiles.end())
     parent = &_cameraProfiles.at(c->_parentID);
   bool refreshHardware = false;
   if(c->getLocation() == IN_HOST)
   {
     if(!c->removeFile())
       return false;
   }
   else
     refreshHardware = true;
   // Update all those profiles which have this profile as its parent.
   for(auto config = _cameraProfiles.begin(); config != _cameraProfiles.end(); config++)
   {
     if(config->second._parentID == id)
     {
       if(!config->second._copyFromParentIfNotPresent(&config->second, false))
       {
         return false;
       }
       if(parent)
       {
         config->second.setInteger("global", "parent", c->_parentID);
         config->second._parentID = c->_parentID;
       }
       if(config->second.getLocation() == IN_HOST)
       {
         if(!config->second.write())
         {
           return false;
         }
       }
       else
       {
         refreshHardware = true;
       }
     }
   }
   _cameraProfiles.erase(_cameraProfiles.find(id));
   if(_cameraProfileNames.find(id) != _cameraProfileNames.end())
     _cameraProfileNames.erase(_cameraProfileNames.find(id));
   if(refreshHardware && id != _defaultCameraProfileIDInHardware && !writeToHardware())
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Failed to update hardware data after removing profile with id = " << id << std::endl;
     return false;
   }
   if(!_updateCameraProfileList())
   {
     logger(LOG_WARNING) << "MainConfigurationFile: Could not update profile list in main configuration file '" << _fileName << "'." << std::endl;
   }
   if(id == _defaultCameraProfileID)
   {
     for(auto config = _cameraProfiles.begin(); config != _cameraProfiles.end(); config++)
       if(config->second.getLocation() == IN_HOST)
         if(!setDefaultCameraProfile(_cameraProfiles.begin()->first))
           return false;
   }
   else if(id == _defaultCameraProfileIDInHardware)
   {
     for(auto config = _cameraProfiles.begin(); config != _cameraProfiles.end(); config++)
       if(config->second.getLocation() == IN_CAMERA)
         if(!setDefaultCameraProfile(_cameraProfiles.begin()->first))
           return false;
   }
   if(id == _currentCameraProfileID)
   {
     if(id != _defaultCameraProfileID)
       return setCurrentCameraProfile(_defaultCameraProfileID);
     else if(_cameraProfiles.size() > 0)
       return setCurrentCameraProfile(_cameraProfiles.begin()->first);
   }
   return true;
 }
bool Voxel::MainConfigurationFile::saveCameraProfileToHardware (const int id)
Definition at line 1389 of file Configuration.cpp.
References _cameraProfileNames, _cameraProfiles, _currentCameraProfileID, _getNewCameraProfileID(), Voxel::ConfigurationFile::_location, Voxel::ConfigurationFile::_parentID, Voxel::ConfigurationFile::_profileName, getCameraProfile(), Voxel::ConfigurationFile::getLocation(), Voxel::ConfigurationFile::IN_CAMERA, Voxel::ConfigurationFile::IN_HOST, Voxel::LOG_ERROR, Voxel::logger, Voxel::ConfigurationFile::mergeParentConfiguration(), setCurrentCameraProfile(), Voxel::ConfigurationFile::setID(), and writeToHardware().
 {
   ConfigurationFile *config = getCameraProfile(id);
   if(!config)
     return false;
   ConfigurationFile oldconfig(*config);
   ConfigurationFile newconfig(*config);
   int newid = id;
   if(config->getLocation() == ConfigurationFile::IN_HOST) // Was it in camera earlier?
   {
     newid = _getNewCameraProfileID(false); // Get new ID for camera
     newconfig.setID(newid);
     newconfig._location = ConfigurationFile::IN_CAMERA;
   }
   ConfigurationFile *parent = getCameraProfile(newconfig._parentID);
   if(parent && parent->getLocation() == ConfigurationFile::IN_HOST)
     if(!newconfig.mergeParentConfiguration())
     {
       logger(LOG_ERROR) << "MainConfigurationFile: Failed to merge data from parents" << std::endl;
       return false;
     }
   _cameraProfiles[newid] = newconfig;
   _cameraProfileNames[newid] = newconfig._profileName;
   if(writeToHardware())
   {
     if(_currentCameraProfileID == id)
       return setCurrentCameraProfile(newid);
     return true;
   }
   else
   {
     if(newid == id)
     {
       _cameraProfiles[newid] = oldconfig;
       _cameraProfileNames[newid] = oldconfig._profileName;
     }
     else
     {
       _cameraProfileNames.erase(newid);
       _cameraProfiles.erase(newid);
     }
     return false;
   }
 }
bool Voxel::MainConfigurationFile::setCurrentCameraProfile (const int id)
Definition at line 908 of file Configuration.cpp.
References _cameraProfiles, _currentCameraProfile, and _currentCameraProfileID.
Referenced by read(), removeCameraProfile(), saveCameraProfileToHardware(), and Voxel::DepthCamera::setCameraProfile().
 {
   if(_cameraProfiles.find(id) != _cameraProfiles.end())
   {
     _currentCameraProfileID = id;
     _currentCameraProfile = &_cameraProfiles.at(id);
     return true;
   }
   return false;
 }
bool Voxel::MainConfigurationFile::setDefaultCameraProfile (const int id)
Definition at line 1442 of file Configuration.cpp.
References _defaultCameraProfileID, _defaultCameraProfileIDInHardware, getCameraProfile(), Voxel::ConfigurationFile::getLocation(), Voxel::ConfigurationFile::IN_CAMERA, Voxel::LOG_INFO, Voxel::logger, Voxel::ConfigurationFile::setInteger(), Voxel::ConfigurationFile::write(), and writeToHardware().
Referenced by removeCameraProfile().
 {
   ConfigurationFile *config = getCameraProfile(id);
   if(!config)
     return false;
   logger(LOG_INFO) << "MainConfigurationFile: Setting id = " << id << ", as default camera profile." << std::endl;
   if(config->getLocation() == ConfigurationFile::IN_CAMERA)
   {
     _defaultCameraProfileIDInHardware = id;
     return writeToHardware();
   }
   else
   {
     _defaultCameraProfileID = id;
     if(!setInteger("core", "default_profile", id))
       return false;
     return write();
   }
 }
void Voxel::MainConfigurationFile::setHardwareID (const String & hwID) inline
Definition at line 392 of file Configuration.h.
Referenced by Voxel::DepthCamera::_init().
 { _hardwareID = hwID; }
void Voxel::MainConfigurationFile::setHardwareReader (HardwareSerializer hardwareReader) inline
Definition at line 365 of file Configuration.h.
Referenced by Voxel::TI::TintinCDKCamera::_init().
 { _hardwareReader = hardwareReader; }
void Voxel::MainConfigurationFile::setHardwareWriter (HardwareSerializer hardwareWriter) inline
Definition at line 366 of file Configuration.h.
Referenced by Voxel::TI::TintinCDKCamera::_init().
 { _hardwareWriter = hardwareWriter; }
bool Voxel::MainConfigurationFile::writeToHardware ()
Definition at line 1309 of file Configuration.cpp.
References _cameraProfiles, _defaultCameraProfileIDInHardware, _hardwareID, _hardwareWriter, CONFIG_VERSION_MAJOR, CONFIG_VERSION_MINOR, Voxel::SerializedObject::getBytes(), Voxel::Timer::getCurentRealTime(), Voxel::Configuration::getLocalConfPath(), Voxel::ConfigurationFile::IN_HOST, Voxel::LOG_ERROR, Voxel::logger, Voxel::MainConfigurationFile::ConfigSerialNumberType::major, Voxel::DataPacket::object, Voxel::ConfigDataPacket::PACKET_CONFIG, Voxel::SerializedObject::put(), Voxel::SerializedObject::resize(), Voxel::DataPacket::size, Voxel::SerializedObject::size(), Voxel::DataPacket::type, and Voxel::DataPacket::write().
Referenced by removeCameraProfile(), saveCameraProfileToHardware(), and setDefaultCameraProfile().
 {
   OutputStringStream ss;
   uint8_t defaultProfileID = _defaultCameraProfileIDInHardware;
   ss.write((char *)&defaultProfileID, sizeof(defaultProfileID));
   for(auto c = _cameraProfiles.begin(); c != _cameraProfiles.end(); c++)
   {
     if(c->second.getLocation() == ConfigurationFile::IN_HOST)
       continue;
     ConfigDataPacket cp;
     cp.type = ConfigDataPacket::PACKET_CONFIG;
     OutputStringStream oss;
     if(!c->second.write(oss))
       return false;
     String s = oss.str();
     cp.size = s.size();
     cp.object.resize(s.size());
     cp.object.put((const char *)&s[0], s.size());
     if(!cp.write(ss))
       return false;
     if(!c->second._serializeAllDataFiles(ss))
       return false;
   }
   SerializedObject so;
   String out = ss.str();
   so.resize(out.size());
   memcpy(so.getBytes().data(), &out[0], so.size());
   ConfigSerialNumberType serialNumber;
   serialNumber.major = CONFIG_VERSION_MAJOR;
   serialNumber.minor = CONFIG_VERSION_MINOR;
   Timer t;
   TimeStampType timestamp = t.getCurentRealTime();
   if(_hardwareWriter && !_hardwareWriter(serialNumber, timestamp, so))
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Failed to write configuration from hardware." << std::endl;
     return false;
   }
   Configuration c;
   String f = _hardwareID + ".bin", path;
   if(!c.getLocalConfPath(path))
     return false;
   f = path + DIR_SEP + f;
   OutputFileStream fs(f, std::ios::out | std::ios::binary);
   if(!fs.good())
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Could not open file '" << f << "'" << std::endl;
     return false;
   }
   fs.write((const char *)&serialNumber, sizeof(serialNumber));
   fs.write((const char *)&timestamp, sizeof(timestamp));
   fs.write((const char *)so.getBytes().data(), so.size());
   fs.close();
   return true;
 }
Member Data Documentation
Map<int, String> Voxel::MainConfigurationFile::_cameraProfileNames protected
Definition at line 338 of file Configuration.h.
Referenced by addCameraProfile(), getCameraProfileName(), read(), readFromHardware(), removeCameraProfile(), and saveCameraProfileToHardware().
Map<int, ConfigurationFile> Voxel::MainConfigurationFile::_cameraProfiles protected
Definition at line 337 of file Configuration.h.
Referenced by _getNewCameraProfileID(), _updateCameraProfileList(), addCameraProfile(), getCameraProfile(), read(), readFromHardware(), removeCameraProfile(), saveCameraProfileToHardware(), setCurrentCameraProfile(), and writeToHardware().
ConfigurationFile* Voxel::MainConfigurationFile::_currentCameraProfile protected
Definition at line 341 of file Configuration.h.
Referenced by get(), getFile(), isPresent(), read(), and setCurrentCameraProfile().
int Voxel::MainConfigurationFile::_currentCameraProfileID protected
Definition at line 340 of file Configuration.h.
Referenced by read(), removeCameraProfile(), saveCameraProfileToHardware(), and setCurrentCameraProfile().
int Voxel::MainConfigurationFile::_defaultCameraProfileID protected
Definition at line 339 of file Configuration.h.
Referenced by getDefaultCameraProfile(), read(), removeCameraProfile(), and setDefaultCameraProfile().
int Voxel::MainConfigurationFile::_defaultCameraProfileIDInHardware protected
Definition at line 339 of file Configuration.h.
Referenced by readFromHardware(), removeCameraProfile(), setDefaultCameraProfile(), and writeToHardware().
String Voxel::MainConfigurationFile::_hardwareID protected
Definition at line 345 of file Configuration.h.
Referenced by readFromHardware(), and writeToHardware().
HardwareSerializer Voxel::MainConfigurationFile::_hardwareReader protected
Definition at line 354 of file Configuration.h.
Referenced by readFromHardware().
HardwareSerializer Voxel::MainConfigurationFile::_hardwareWriter protected
Definition at line 354 of file Configuration.h.
Referenced by writeToHardware().
String Voxel::MainConfigurationFile::_mainConfigName protected
Definition at line 345 of file Configuration.h.
Referenced by addCameraProfile().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp