Voxel: Voxel::BilateralFilter Class Reference
Voxel::BilateralFilter Class Reference
Filter related classes
#include <BilateralFilter.h>
Public Member Functions
BilateralFilter (float sigma=0.5)
virtual ~BilateralFilter ()
virtual void reset ()
Public Member Functions inherited from Voxel::Filter
Filter (const String &name, const String &description="", const String &nameScope="")
void setDepthCamera (const DepthCameraPtr &d)
const Map< String,
FilterParameterPtr > & parameters ()
const String & name ()
const String & description ()
void setNameScope (const String &scope)
bool filter (const FramePtr &in, FramePtr &out)
FilterParameterConstPtr getParam (const String &name) const
template<typename T >
bool get (const String &name, T &value)
template<typename T >
bool set (const String &name, const T &value)
virtual ~Filter ()
Protected Member Functions
virtual void _onSet (const FilterParameterPtr &f)
template<typename T , typename T2 >
bool _filter (const T *in, const T2 *ref, T *out)
virtual bool _filter (const FramePtr &in, FramePtr &out)
Protected Member Functions inherited from Voxel::Filter
void _makeID ()
virtual bool _addParameters (const Vector< FilterParameterPtr > &params)
virtual bool _prepareOutput (const FramePtr &in, FramePtr &out)
template<typename T >
bool _get (const String &name, T &value)
template<typename T >
bool _set (const String &name, const T &value)
Protected Attributes
DiscreteGaussian _discreteGuassian
FrameSize _size
Protected Attributes inherited from Voxel::Filter
String _name
String _nameScope
String _description
String _id
Mutex _accessMutex
DepthCameraPtr _depthCamera
Map< String, FilterParameterPtr > _parameters
Detailed Description
Definition at line 22 of file BilateralFilter.h.
Constructor & Destructor Documentation
Voxel::BilateralFilter::BilateralFilter (float sigma = 0.5)
Definition at line 14 of file BilateralFilter.cpp.
References Voxel::Filter::_addParameters().
                                            : Filter("BilateralFilter"), _discreteGuassian(sigma)
 {
   _addParameters({
     FilterParameterPtr(new FloatFilterParameter("sigma", "Sigma", "Standard deviation", sigma, "", 0, 100)),
   });
 }
virtual Voxel::BilateralFilter::~BilateralFilter () inline virtual
Definition at line 38 of file BilateralFilter.h.
 {}
Member Function Documentation
template<typename T , typename T2 > bool Voxel::BilateralFilter::_filter (const T * in, const T2 * ref, T * out) protected
Definition at line 37 of file BilateralFilter.cpp.
References _discreteGuassian, _size, Voxel::FrameSize::height, Voxel::DiscreteGaussian::valueAt(), and Voxel::FrameSize::width.
 {
   uint s = _size.width*_size.height;
   #pragma omp parallel for
   for (int j = 0; j < _size.height; j++)
   {
     for (int i = 0; i < _size.width; i++)
     {
       int p = j*_size.width + i;
       float weight_sum = 0;
       float sum = 0;
       for (int k = -2; k <= 2; k++)
       {
         for (int m = -2; m <= 2; m++)
         {
           int i2 = i+m;
           int j2 = j+k;
           if ((j2 >= 0 && j2 < _size.height) && (i2 >= 0 && i2 < _size.width))
           {
             int q = j2*_size.width + i2;
             float weight = _discreteGuassian.valueAt(k)*_discreteGuassian.valueAt(m)*_discreteGuassian.valueAt(ref[p]-ref[q]);
             weight_sum += weight;
             sum += weight * in[q];
           }
         }
       }
       out[p] = (T)(sum / weight_sum);
     }
   }
   return true;
 }
bool Voxel::BilateralFilter::_filter (const FramePtr & in, FramePtr & out) protected virtual
Implements Voxel::Filter.
Definition at line 73 of file BilateralFilter.cpp.
References Voxel::Filter::_prepareOutput(), _size, Voxel::ToFRawFrame::ambient(), Voxel::ToFRawFrame::ambientWordWidth(), Voxel::DepthFrame::amplitude, Voxel::ToFRawFrame::amplitude(), Voxel::ToFRawFrame::amplitudeWordWidth(), Voxel::DepthFrame::depth, Voxel::ToFRawFrame::flags(), Voxel::ToFRawFrame::flagsWordWidth(), Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::ToFRawFrame::phase(), Voxel::ToFRawFrame::phaseWordWidth(), Voxel::DepthFrame::size, Voxel::ToFRawFrame::size, CameraSystemIQFrameTest::tofFrame, and Voxel::FrameSize::width.
 {
   ToFRawFrame *tofFrame = dynamic_cast<ToFRawFrame *>(in.get());
   DepthFrame *depthFrame = dynamic_cast<DepthFrame *>(in.get());
   if((!tofFrame && !depthFrame) || !_prepareOutput(in, out))
   {
     logger(LOG_ERROR) << "IIRFilter: Input frame type is not ToFRawFrame or DepthFrame or failed get the output ready" << std::endl;
     return false;
   }
   if(tofFrame)
   {
     _size = tofFrame->size;
     ToFRawFrame *o = dynamic_cast<ToFRawFrame *>(out.get());
     if(!o)
     {
       logger(LOG_ERROR) << "IIRFilter: Invalid frame type. Expecting ToFRawFrame." << std::endl;
       return false;
     }
     //logger(LOG_INFO) << "IIRFilter: Applying filter with gain = " << _gain << " to ToFRawFrame id = " << tofFrame->id << std::endl;
     uint s = _size.width*_size.height;
     memcpy(o->ambient(), tofFrame->ambient(), s*tofFrame->ambientWordWidth());
     memcpy(o->amplitude(), tofFrame->amplitude(), s*tofFrame->amplitudeWordWidth());
     memcpy(o->flags(), tofFrame->flags(), s*tofFrame->flagsWordWidth());
     if(tofFrame->phaseWordWidth() == 2)
     {
       if(tofFrame->amplitudeWordWidth() == 1)
         return _filter<uint16_t, uint8_t>((uint16_t *)tofFrame->phase(), (uint8_t *)tofFrame->amplitude(), (uint16_t *)o->phase());
       else if(tofFrame->amplitudeWordWidth() == 2)
         return _filter<uint16_t, uint16_t>((uint16_t *)tofFrame->phase(), (uint16_t *)tofFrame->amplitude(), (uint16_t *)o->phase());
       else if(tofFrame->amplitudeWordWidth() == 4)
         return _filter<uint16_t, uint32_t>((uint16_t *)tofFrame->phase(), (uint32_t *)tofFrame->amplitude(), (uint16_t *)o->phase());
     }
     else if(tofFrame->phaseWordWidth() == 1)
     {
       if(tofFrame->amplitudeWordWidth() == 1)
         return _filter<uint8_t, uint8_t>((uint8_t *)tofFrame->phase(), (uint8_t *)tofFrame->amplitude(), (uint8_t *)o->phase());
       else if(tofFrame->amplitudeWordWidth() == 2)
         return _filter<uint8_t, uint16_t>((uint8_t *)tofFrame->phase(), (uint16_t *)tofFrame->amplitude(), (uint8_t *)o->phase());
       else if(tofFrame->amplitudeWordWidth() == 4)
         return _filter<uint8_t, uint32_t>((uint8_t *)tofFrame->phase(), (uint32_t *)tofFrame->amplitude(), (uint8_t *)o->phase());
     }
     else if(tofFrame->phaseWordWidth() == 4)
     {
       if(tofFrame->amplitudeWordWidth() == 1)
         return _filter<uint32_t, uint8_t>((uint32_t *)tofFrame->phase(), (uint8_t *)tofFrame->amplitude(), (uint32_t *)o->phase());
       else if(tofFrame->amplitudeWordWidth() == 2)
         return _filter<uint32_t, uint16_t>((uint32_t *)tofFrame->phase(), (uint16_t *)tofFrame->amplitude(), (uint32_t *)o->phase());
       else if(tofFrame->amplitudeWordWidth() == 4)
         return _filter<uint32_t, uint32_t>((uint32_t *)tofFrame->phase(), (uint32_t *)tofFrame->amplitude(), (uint32_t *)o->phase());
     }
     return false;
   }
   else if(depthFrame)
   {
     _size = depthFrame->size;
     DepthFrame *o = dynamic_cast<DepthFrame *>(out.get());
     if(!o)
     {
       logger(LOG_ERROR) << "IIRFilter: Invalid frame type. Expecting DepthFrame." << std::endl;
       return false;
     }
     o->amplitude = depthFrame->amplitude;
     return _filter<float, float>(depthFrame->depth.data(), depthFrame->amplitude.data(), o->depth.data());
   }
   else
     return false;
 }
void Voxel::BilateralFilter::_onSet (const FilterParameterPtr & f) protected virtual
Implements Voxel::Filter.
Definition at line 23 of file BilateralFilter.cpp.
References _discreteGuassian, Voxel::Filter::_get(), Voxel::LOG_WARNING, Voxel::logger, and Voxel::DiscreteGaussian::setStandardDeviation().
 {
   if(f->name() == "sigma")
   {
     float s;
     if(!_get(f->name(), s))
     {
       logger(LOG_WARNING) << "BilateralFilter: Could not get the recently updated 'sigma' parameter" << std::endl;
     }
     _discreteGuassian.setStandardDeviation(s);
   }
 }
void Voxel::BilateralFilter::reset () virtual
Implements Voxel::Filter.
Definition at line 21 of file BilateralFilter.cpp.
 {}
Member Data Documentation
DiscreteGaussian Voxel::BilateralFilter::_discreteGuassian protected
Definition at line 25 of file BilateralFilter.h.
Referenced by _filter(), and _onSet().
FrameSize Voxel::BilateralFilter::_size protected
Definition at line 27 of file BilateralFilter.h.
Referenced by _filter().
The documentation for this class was generated from the following files:
BilateralFilter.h
BilateralFilter.cpp