Voxel: Voxel::FrameStreamWriter Class Reference
Voxel::FrameStreamWriter Class Reference
#include <FrameStream.h>
Public Member Functions
FrameStreamWriter (const String &filename, GeneratorIDType processedRawFrameGeneratorID, GeneratorIDType depthFrameGeneratorID, GeneratorIDType pointCloudFrameGeneratorID)
FrameStreamWriter (OutputFileStream &stream, GeneratorIDType processedRawFrameGeneratorID, GeneratorIDType depthFrameGeneratorID, GeneratorIDType pointCloudFrameGeneratorID)
bool isStreamGood ()
bool write (FramePtr rawUnprocessed)
SerializedObject & getConfigObject ()
bool writeGeneratorConfiguration (uint frameType)
bool close ()
virtual ~FrameStreamWriter ()
Private Member Functions
bool _writeHeader ()
bool _init (GeneratorIDType processedRawFrameGeneratorID, GeneratorIDType depthFrameGeneratorID, GeneratorIDType pointCloudFrameGeneratorID)
Private Attributes
OutputFileStream & _stream
OutputFileStream _internalStream
Mutex _mutex
size_t _frameCount
FrameStreamHeader _header
FrameStreamPacket _rawpacket
FrameStreamPacket _configPacket
GeneratorConfigurationSubPacket _generatorConfigSubPacket
Detailed Description
Definition at line 47 of file FrameStream.h.
Constructor & Destructor Documentation
Voxel::FrameStreamWriter::FrameStreamWriter (const String & filename, GeneratorIDType processedRawFrameGeneratorID, GeneratorIDType depthFrameGeneratorID, GeneratorIDType pointCloudFrameGeneratorID)
Definition at line 19 of file FrameStream.cpp.
References _init(), and _stream.
   :_stream(_internalStream)
 {
   _stream.open(filename, std::ios::binary | std::ios::out);
   _init(processedRawFrameGeneratorID, depthFrameGeneratorID, pointCloudFrameGeneratorID);
 }
Voxel::FrameStreamWriter::FrameStreamWriter (OutputFileStream & stream, GeneratorIDType processedRawFrameGeneratorID, GeneratorIDType depthFrameGeneratorID, GeneratorIDType pointCloudFrameGeneratorID)
Definition at line 51 of file FrameStream.cpp.
References _init().
 :_stream(stream)
 {
   _init(processedRawFrameGeneratorID, depthFrameGeneratorID, pointCloudFrameGeneratorID);
 }
virtual Voxel::FrameStreamWriter::~FrameStreamWriter () inline virtual
Definition at line 77 of file FrameStream.h.
 { close(); }
Member Function Documentation
bool Voxel::FrameStreamWriter::_init (GeneratorIDType processedRawFrameGeneratorID, GeneratorIDType depthFrameGeneratorID, GeneratorIDType pointCloudFrameGeneratorID) private
Definition at line 28 of file FrameStream.cpp.
References _frameCount, _header, _stream, _writeHeader(), Voxel::FrameStreamHeader::generatorIDs, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by FrameStreamWriter().
 {
   _frameCount = 0;
   if(!_stream.good())
   {
     logger(LOG_ERROR) << "FrameStreamWriter: Failed to open file." << std::endl;
     return false;
   }
   _header.generatorIDs[0] = processedRawFrameGeneratorID;
   _header.generatorIDs[1] = depthFrameGeneratorID;
   _header.generatorIDs[2] = pointCloudFrameGeneratorID;
   if(!_writeHeader())
   {
     logger(LOG_ERROR) << "FrameStreamWriter: Failed to write stream header." << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::FrameStreamWriter::_writeHeader () private
Definition at line 77 of file FrameStream.cpp.
References _header, _stream, Voxel::FrameStreamHeader::generatorIDs, and Voxel::FrameStreamHeader::version.
Referenced by _init().
 {
   _header.version[0] = 0;
   _header.version[1] = 1;
   _stream.write(_header.version, 2);
   _stream.write((const char *)_header.generatorIDs, sizeof(GeneratorIDType)*3);
   return true;
 }
bool Voxel::FrameStreamWriter::close ()
Definition at line 107 of file FrameStream.cpp.
References _mutex, and _stream.
 {
   Lock<Mutex> _(_mutex);
   if(_stream.is_open())
     _stream.close();
   return !_stream.fail();
 }
SerializedObject& Voxel::FrameStreamWriter::getConfigObject () inline
Definition at line 71 of file FrameStream.h.
 { return _generatorConfigSubPacket.config; }
bool Voxel::FrameStreamWriter::isStreamGood () inline
Definition at line 67 of file FrameStream.h.
Referenced by write(), and writeGeneratorConfiguration().
 { return _stream.good(); }
bool Voxel::FrameStreamWriter::write (Voxel::FramePtr rawUnprocessed)
Definition at line 58 of file FrameStream.cpp.
References _mutex, _rawpacket, _stream, isStreamGood(), Voxel::LOG_ERROR, Voxel::logger, Voxel::DataPacket::object, Voxel::FrameStreamPacket::PACKET_DATA, Voxel::DataPacket::size, Voxel::SerializedObject::size(), Voxel::DataPacket::type, and Voxel::DataPacket::write().
 {
   Lock<Mutex> _(_mutex);
   if(!isStreamGood())
     return false;
   if((rawUnprocessed && !rawUnprocessed->serialize(_rawpacket.object)))
   {
     logger(LOG_ERROR) << "FrameStreamWriter: Failed to serialize frame." << std::endl;
     return false;
   }
   _rawpacket.type = FrameStreamPacket::PACKET_DATA;
   _rawpacket.size = _rawpacket.object.size();
   return _rawpacket.write(_stream);
 }
bool Voxel::FrameStreamWriter::writeGeneratorConfiguration (uint frameType)
Definition at line 90 of file FrameStream.cpp.
References _configPacket, _generatorConfigSubPacket, _mutex, _stream, Voxel::GeneratorConfigurationSubPacket::config, Voxel::GeneratorConfigurationSubPacket::frameType, isStreamGood(), Voxel::DataPacket::object, Voxel::FrameStreamPacket::PACKET_GENERATOR_CONFIG, Voxel::DataPacket::size, Voxel::GeneratorConfigurationSubPacket::size, Voxel::SerializedObject::size(), Voxel::DataPacket::type, Voxel::DataPacket::write(), and Voxel::GeneratorConfigurationSubPacket::write().
 {
   Lock<Mutex> _(_mutex);
   if(!isStreamGood())
     return false;
   _generatorConfigSubPacket.frameType = frameType;
   _generatorConfigSubPacket.size = _generatorConfigSubPacket.config.size();
   _configPacket.type = FrameStreamPacket::PACKET_GENERATOR_CONFIG;
   _generatorConfigSubPacket.write(_configPacket.object);
   _configPacket.size = _configPacket.object.size();
   return _configPacket.write(_stream);
 }
Member Data Documentation
FrameStreamPacket Voxel::FrameStreamWriter::_configPacket private
Definition at line 56 of file FrameStream.h.
Referenced by writeGeneratorConfiguration().
size_t Voxel::FrameStreamWriter::_frameCount private
Definition at line 54 of file FrameStream.h.
Referenced by _init().
GeneratorConfigurationSubPacket Voxel::FrameStreamWriter::_generatorConfigSubPacket private
Definition at line 57 of file FrameStream.h.
Referenced by writeGeneratorConfiguration().
FrameStreamHeader Voxel::FrameStreamWriter::_header private
Definition at line 55 of file FrameStream.h.
Referenced by _init(), and _writeHeader().
OutputFileStream Voxel::FrameStreamWriter::_internalStream private
Definition at line 50 of file FrameStream.h.
Mutex Voxel::FrameStreamWriter::_mutex private
Definition at line 52 of file FrameStream.h.
Referenced by close(), write(), and writeGeneratorConfiguration().
FrameStreamPacket Voxel::FrameStreamWriter::_rawpacket private
Definition at line 56 of file FrameStream.h.
Referenced by write().
OutputFileStream& Voxel::FrameStreamWriter::_stream private
Definition at line 49 of file FrameStream.h.
Referenced by _init(), _writeHeader(), close(), FrameStreamWriter(), write(), and writeGeneratorConfiguration().
The documentation for this class was generated from the following files:
FrameStream.h
FrameStream.cpp