Voxel: Voxel::DFT Class Reference
Voxel::DFT Class Reference
Filter related classes
#include <DFT.h>
Public Types
enum Direction { FORWARD = 1, REVERSE = -1 }
Public Member Functions
bool DFT2D (Complex2D &data, Direction dir)
bool DFT1D (const Complex1D &in, Complex1D &out, Direction dir)
Protected Member Functions
void _computeExpTable (SizeType size, Direction dir)
Protected Attributes
Complex2D _internal
Map< SizeType, Complex2D > _expTable
Detailed Description
Definition at line 29 of file DFT.h.
Member Enumeration Documentation
enum Voxel::DFT::Direction
Enumerator
FORWARD
REVERSE
Definition at line 32 of file DFT.h.
   {
     FORWARD = 1,
     REVERSE = -1
   };
Member Function Documentation
void Voxel::DFT::_computeExpTable (SizeType size, Direction dir) protected
Definition at line 312 of file DFT.cpp.
References _expTable.
Referenced by DFT1D().
 {
   Complex2D &expTable = _expTable[size];
   expTable.resize(size);
   for(int i = 0; i < size; i++)
   {
     expTable[i].resize(size);
     ComplexDouble arg = ComplexDouble(0, -((dir*2.0*M_PI*i)/size));
     for(int k = 0; k < size; k++)
       expTable[i][k] = exp(((double)k)*arg);
   }
 }
bool Voxel::DFT::DFT1D (const Complex1D & in, Complex1D & out, Direction dir)
This computes an in-place complex-to-complex DFT x and y are the real and imaginary arrays of 2^m points. dir = 1 gives forward transform dir = -1 gives reverse transform
Formula: forward
N-1
1 \ - j k 2 pi n / N X(n) = — > x(k) e = forward transform
N / n=0..N-1
k=0
Formula: reverse
N-1
\ j k 2 pi n / N X(n) = > x(k) e = forward transform
/ n=0..N-1
k=0
Definition at line 277 of file DFT.cpp.
References _computeExpTable(), and _expTable.
Referenced by DFT2D().
 {
   if(out.size() != in.size())
     out.resize(in.size());
   if(_expTable.find(in.size()) == _expTable.end())
   {
     _computeExpTable(in.size(), dir);
   }
   Complex2D &expTable = _expTable[in.size()];
   int i, k;
   int m = in.size();
   for(i = 0; i < m; i++)
   {
     out[i] = 0;
     for(k = 0; k < m; k++)
       out[i] += in[k]*expTable[i][k];
 //     {
 //       cosarg = cos(k*arg);
 //       sinarg = sin(k*arg);
 //       out[i].real(out[i].real() + (in[k].real() * cosarg - in[k].imag() * sinarg));
 //       out[i].imag(out[i].imag() + (in[k].real() * sinarg + in[k].imag() * cosarg));
 //     }
   }
   double msq = sqrt(m);
   for(i = 0; i < m; i++)
     out[i] /= msq;
   return true;
 }
bool Voxel::DFT::DFT2D (Complex2D & data, Direction dir)
Perform a 2D FFT inplace given a complex 2D array The direction dir, 1 for forward, -1 for reverse The size of the array (nx,ny) Return false if there are memory problems or the dimensions are not powers of 2
Definition at line 230 of file DFT.cpp.
References _expTable, _internal, DFT1D(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by main().
 {
   if(data.size() == 0 || data[0].size() == 0)
   {
     logger(LOG_ERROR) << "DFT: Number of rows is zero in input data?" << std::endl;
     return false;
   }
   _expTable.clear();
   SizeType rows = data.size(), columns = data[0].size();
   _internal.resize(rows);
   for(auto i = 0; i < rows; i++)
   {
     _internal[i].resize(columns);
     if(!DFT1D(data[i], _internal[i], dir))
     {
       logger(LOG_ERROR) << "Failed to perform 1D DFT for row '" << i << "'" << std::endl;
       return false;
     }
   }
   Complex1D in, out;
   in.resize(rows);
   out.resize(rows);
   for(auto i = 0; i < columns; i++)
   {
     for(auto j = 0; j < rows; j++)
       in[j] = _internal[j][i];
     if(!DFT1D(in, out, dir))
     {
       logger(LOG_ERROR) << "Failed to perform 1D DFT for row '" << i << "'" << std::endl;
       return false;
     }
     for(auto j = 0; j < rows; j++)
       data[j][i] = out[j];
   }
   return true;
 }
Member Data Documentation
Map<SizeType, Complex2D> Voxel::DFT::_expTable protected
Definition at line 41 of file DFT.h.
Referenced by _computeExpTable(), DFT1D(), and DFT2D().
Complex2D Voxel::DFT::_internal protected
Definition at line 39 of file DFT.h.
Referenced by DFT2D().
The documentation for this class was generated from the following files:
DFT.h
DFT.cpp