Voxel: Voxel::LogLevelChanger Class Reference
Voxel::LogLevelChanger Class Reference
Common and Utility classes
#include <Logger.h>
Public Member Functions
LogLevelChanger (LogLevel desired)
~LogLevelChanger ()
Private Attributes
LogLevel _currentLogLevel
LogLevel _desiredLogLevel
Detailed Description
Definition at line 184 of file Logger.h.
Constructor & Destructor Documentation
Voxel::LogLevelChanger::LogLevelChanger (LogLevel desired) inline
Definition at line 189 of file Logger.h.
References Voxel::Logger::getDefaultLogLevel(), Voxel::logger, and Voxel::Logger::setDefaultLogLevel().
                                    : _desiredLogLevel(desired)
   {
     _currentLogLevel = logger.getDefaultLogLevel();
     logger.setDefaultLogLevel(_desiredLogLevel);
   }
Voxel::LogLevelChanger::~LogLevelChanger () inline
Definition at line 195 of file Logger.h.
References Voxel::logger, and Voxel::Logger::setDefaultLogLevel().
   {
     logger.setDefaultLogLevel(_currentLogLevel);
   }
Member Data Documentation
LogLevel Voxel::LogLevelChanger::_currentLogLevel private
Definition at line 186 of file Logger.h.
LogLevel Voxel::LogLevelChanger::_desiredLogLevel private
Definition at line 187 of file Logger.h.
The documentation for this class was generated from the following file:
Logger.h