Voxel: Voxel::TI::CalculusCDKCamera Class Reference
Voxel::TI::CalculusCDKCamera Class Reference
#include <CalculusCDKCamera.h>
Public Member Functions
CalculusCDKCamera (DevicePtr device)
virtual ~CalculusCDKCamera ()
Public Member Functions inherited from Voxel::TI::ToFCalculusCamera
ToFCalculusCamera (const String &name, DevicePtr device)
virtual ~ToFCalculusCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (const int id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _getFieldOfView (float &fovHalfAngle) const
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
virtual bool _setStreamerFrameSize (const FrameSize &s)
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _initStartParams ()
Protected Member Functions inherited from Voxel::TI::ToFCalculusCamera
bool _init ()
virtual bool _getIlluminationFrequency (float &frequency) const
bool _getMaximumFrameSize (FrameSize &s) const
virtual bool _getFrameSize (Voxel::FrameSize &s) const
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
bool _updateEasyConf ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Protected Attributes
Ptr< Downloader > _downloader
USBIOPtr _usbIO
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Detailed Description
Definition at line 25 of file CalculusCDKCamera.h.
Constructor & Destructor Documentation
Voxel::TI::CalculusCDKCamera::CalculusCDKCamera (Voxel::DevicePtr device)
Definition at line 24 of file CalculusCDKCamera.cpp.
References _init().
                                                          : ToFCalculusCamera("CalculusCDKCamera", device)
 {
   _init();
 }
virtual Voxel::TI::CalculusCDKCamera::~CalculusCDKCamera () inline virtual
Definition at line 45 of file CalculusCDKCamera.h.
 {}
Member Function Documentation
bool Voxel::TI::CalculusCDKCamera::_getFieldOfView (float & fovHalfAngle) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 170 of file CalculusCDKCamera.cpp.
 {
   fovHalfAngle = (87/2.0f)*(M_PI/180.0f);
   return true;
 }
bool Voxel::TI::CalculusCDKCamera::_getMaximumFrameRate (FrameRate & frameRate, const FrameSize & forFrameSize) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 214 of file CalculusCDKCamera.cpp.
References Voxel::FrameRate::denominator, and Voxel::FrameRate::numerator.
 {
   frameRate.numerator = 500; // To be later updated to use OP_CLK_FREQ
   frameRate.denominator = 1;
   return true;
 }
bool Voxel::TI::CalculusCDKCamera::_getMaximumVideoMode (VideoMode & videoMode) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 205 of file CalculusCDKCamera.cpp.
References Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, Voxel::FrameRate::numerator, and Voxel::FrameSize::width.
 {
   videoMode.frameSize.width = 80;
   videoMode.frameSize.height = 60;
   videoMode.frameRate.denominator = 1;
   videoMode.frameRate.numerator = 100;
   return true;
 }
bool Voxel::TI::CalculusCDKCamera::_getSupportedVideoModes (Vector< SupportedVideoMode > & supportedVideoModes) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 197 of file CalculusCDKCamera.cpp.
 {
   supportedVideoModes = Vector<SupportedVideoMode> {
     SupportedVideoMode(80,60,30,1,4),
   };
   return true;
 }
bool Voxel::TI::CalculusCDKCamera::_init () protected
Definition at line 87 of file CalculusCDKCamera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::DepthCamera::_device, Voxel::TI::ToFCalculusCamera::_init(), Voxel::DepthCamera::_programmer, _setStreamerFrameSize(), Voxel::DepthCamera::_streamer, _usbIO, Voxel::DepthCamera::getFrameSize(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by CalculusCDKCamera().
 {
   USBDevice &d = (USBDevice &)*_device;
   DevicePtr controlDevice;
   controlDevice = _device;
   _usbIO = USBIOPtr(new USBIO(controlDevice));
   _programmer = Ptr<RegisterProgrammer>(new VoxelUSBProgrammer(
     { {0x58, 3}, {0x2D, 1} },
     {
       {0x58, {0x08, 0x09, 0}},
       {0x2D, {0x04, 0x03, 8}},
     }, _usbIO,
     controlDevice));
   _streamer = Ptr<Streamer>(new USBBulkStreamer(_usbIO, controlDevice, 0x82));
   if(!_programmer->isInitialized() || !_streamer->isInitialized())
     return false;
 #if 0
   if(!_addParameters({
     ParameterPtr(new CalculusCDKMixVoltageParameter(*_pmicProgrammer)),
     ParameterPtr(new CalculusCDKPVDDVoltageParameter(*_pmicProgrammer)),
     }))
   {
     return false;
   }
 #endif
   if(!ToFCalculusCamera::_init())
     return false;
   // PVDD 3.0V
   _programmer->writeRegister(0x2D0E, 0xA8);
   FrameSize s;
   if(!getFrameSize(s))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Unable to get frame size" << std::endl;
     return false;
   }
   if(!_setStreamerFrameSize(s))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Unable to set frame size for USBBulkStreamer" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::CalculusCDKCamera::_initStartParams () protected virtual
Reimplemented from Voxel::TI::ToFCalculusCamera.
Definition at line 143 of file CalculusCDKCamera.cpp.
References Voxel::TI::ToFCalculusCamera::_initStartParams(), Voxel::DepthCamera::_programmer, _usbIO, Voxel::LOG_ERROR, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, and Voxel::USBIO::TO_DEVICE.
 {
   if (!ToFCalculusCamera::_initStartParams())
     return false;
   VoxelUSBProgrammer *programmer = dynamic_cast<VoxelUSBProgrammer *>(&*_programmer);
   if(!programmer)
   {
     logger(LOG_ERROR) << "CalculusCDKCamera: Streamer is not of type VoxelUSBProgrammer" << std::endl;
     return false;
   }
   uint16_t length = 0;
   if(
     // Enable Slave Fifo, reqCode 0x12
     !_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, 0x12, 0x00, 0x00, 0, length) ||
     // Set VD Counter to 1300 for now
     !_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, 0x13, 1300, 0x00, 0, length) ||
     // Enable FSC
     !_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, 0x10, 0x0001, 0x00, 0, length))
     return false;
   return true;
 }
bool Voxel::TI::CalculusCDKCamera::_setStreamerFrameSize (const FrameSize & s) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 176 of file CalculusCDKCamera.cpp.
References Voxel::TI::ToFCalculusCamera::_getBytesPerPixel(), Voxel::DepthCamera::_streamer, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::USBBulkStreamer::setBufferSize(), and Voxel::FrameSize::width.
Referenced by _init().
 {
   USBBulkStreamer *streamer = dynamic_cast<USBBulkStreamer *>(&*_streamer);
   if(!streamer)
   {
     logger(LOG_ERROR) << "CalculusCDKCamera: Streamer is not of type USBBulkStreamer" << std::endl;
     return false;
   }
   uint bytesPerPixel;
   if(!_getBytesPerPixel(bytesPerPixel))
   {
     logger(LOG_ERROR) << "CalculusCDKCamera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   return streamer->setBufferSize(s.width*s.height*bytesPerPixel);
 }
Member Data Documentation
Ptr<Downloader> Voxel::TI::CalculusCDKCamera::_downloader protected
Definition at line 28 of file CalculusCDKCamera.h.
USBIOPtr Voxel::TI::CalculusCDKCamera::_usbIO protected
Definition at line 29 of file CalculusCDKCamera.h.
Referenced by _init(), and _initStartParams().
The documentation for this class was generated from the following files:
CalculusCDKCamera.h
CalculusCDKCamera.cpp