Voxel: Voxel::TI::HaddockCDKCamera Class Reference
Voxel::TI::HaddockCDKCamera Class Reference
#include <HaddockCDKCamera.h>
Public Member Functions
HaddockCDKCamera (DevicePtr device)
virtual ~HaddockCDKCamera ()
Public Member Functions inherited from Voxel::TI::ToFHaddockCamera
ToFHaddockCamera (const String &name, DevicePtr device)
virtual ~ToFHaddockCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (const int id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _getFieldOfView (float &fovHalfAngle) const
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
virtual bool _setStreamerFrameSize (const FrameSize &s)
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _initStartParams ()
Protected Member Functions inherited from Voxel::TI::ToFHaddockCamera
bool _init ()
bool _getMaximumFrameSize (FrameSize &s) const
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _getIlluminationFrequency (float &frequency) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _getFrameSize (FrameSize &s) const
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Protected Attributes
Ptr< Downloader > _downloader
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Friends
class HaddockCDKIlluminationPowerPercentageParameter
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Detailed Description
Definition at line 27 of file HaddockCDKCamera.h.
Constructor & Destructor Documentation
Voxel::TI::HaddockCDKCamera::HaddockCDKCamera (Voxel::DevicePtr device)
Definition at line 22 of file HaddockCDKCamera.cpp.
References _init().
                                                        : ToFHaddockCamera("HaddockCDKCamera", device)
 {
   _init();
 }
virtual Voxel::TI::HaddockCDKCamera::~HaddockCDKCamera () inline virtual
Definition at line 45 of file HaddockCDKCamera.h.
 {}
Member Function Documentation
bool Voxel::TI::HaddockCDKCamera::_getFieldOfView (float & fovHalfAngle) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 182 of file HaddockCDKCamera.cpp.
 {
   fovHalfAngle = (87/2.0f)*(M_PI/180.0f);
   return true;
 }
bool Voxel::TI::HaddockCDKCamera::_getMaximumFrameRate (FrameRate & frameRate, const FrameSize & forFrameSize) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 237 of file HaddockCDKCamera.cpp.
References Voxel::DepthCamera::_get(), Voxel::FrameRate::denominator, Voxel::gcd(), Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameRate::numerator, OP_CLK_FREQ, PIXEL_DATA_SIZE, and Voxel::FrameSize::width.
 {
   int opClockFrequency, bytesPerPixel;
   if(!_get(OP_CLK_FREQ, opClockFrequency) || !_get(PIXEL_DATA_SIZE, bytesPerPixel))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Could not get " << OP_CLK_FREQ << " or " << PIXEL_DATA_SIZE << std::endl;
     return false;
   }
   opClockFrequency = 24/(1 << opClockFrequency);
   uint numerator = opClockFrequency*1000000,
   denominator = bytesPerPixel*forFrameSize.width*forFrameSize.height;
   uint g = gcd(numerator, denominator);
   frameRate.numerator = 0.8*numerator/g; // 90% of maximum
   frameRate.denominator = denominator/g;
   return true;
 }
bool Voxel::TI::HaddockCDKCamera::_getMaximumVideoMode (VideoMode & videoMode) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 228 of file HaddockCDKCamera.cpp.
References Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, Voxel::FrameRate::numerator, and Voxel::FrameSize::width.
 {
   videoMode.frameSize.width = 320;
   videoMode.frameSize.height = 240;
   videoMode.frameRate.denominator = 1;
   videoMode.frameRate.numerator = 30;
   return true;
 }
bool Voxel::TI::HaddockCDKCamera::_getSupportedVideoModes (Vector< SupportedVideoMode > & supportedVideoModes) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 222 of file HaddockCDKCamera.cpp.
 {
   supportedVideoModes.clear();
   return true;
 }
bool Voxel::TI::HaddockCDKCamera::_init () protected
Definition at line 106 of file HaddockCDKCamera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::DepthCamera::_device, Voxel::TI::ToFHaddockCamera::_init(), Voxel::DepthCamera::_programmer, _setStreamerFrameSize(), Voxel::DepthCamera::_streamer, Voxel::DepthCamera::getFrameSize(), HaddockCDKIlluminationPowerPercentageParameter, ILLUM_POWER, ILLUM_POWER2, Voxel::LOG_ERROR, Voxel::logger, and LensCalibrationTest::p1.
Referenced by HaddockCDKCamera().
 {
   USBDevice &d = (USBDevice &)*_device;
   DevicePtr controlDevice;
   controlDevice = _device;
   USBIOPtr usbIO(new USBIO(controlDevice));
   _programmer = Ptr<RegisterProgrammer>(new VoxelUSBProgrammer(
     { {0x58, 3}, {0x5C, 3}, {0x28, 1}, {0x2A, 1}, {0x2B, 1} },
     {
       {0x58, {0xA4, 0xA4, 0}},
       {0x5C, {0xA4, 0xA4, 0}},
       {0x28, {0xA4, 0xA4, 0}},
       {0x2A, {0xA4, 0xA4, 0}},
       {0x2B, {0xA4, 0xA4, 0}}
     }, usbIO,
     controlDevice));
   _streamer = Ptr<Streamer>(new USBBulkStreamer(usbIO, controlDevice, 0x86));
   if(!_programmer->isInitialized() || !_streamer->isInitialized())
     return false;
   auto p1 = Ptr<HaddockCDKIlluminationPowerPercentageParameter>(new HaddockCDKIlluminationPowerPercentageParameter(*this, *_programmer));
   auto p21 = Ptr<HaddockCDKIlluminationPowerParameter>(new HaddockCDKIlluminationPowerParameter(*_programmer, ILLUM_POWER, 0x2A11)),
   p22 = Ptr<HaddockCDKIlluminationPowerParameter>(new HaddockCDKIlluminationPowerParameter(*_programmer, ILLUM_POWER2, 0x2B11));
   p21->setOtherParameter(p22);
   if(!_addParameters({
     ParameterPtr(new HaddockCDKMixVoltageParameter(*_programmer)),
     std::dynamic_pointer_cast<Parameter>(p1),
     std::dynamic_pointer_cast<Parameter>(p21)
     }))
     return false;
   if(!ToFHaddockCamera::_init())
     return false;
   FrameSize s;
   if(!getFrameSize(s))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Unable to get frame size" << std::endl;
     return false;
   }
   if(!_setStreamerFrameSize(s))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Unable to set frame size for USBBulkStreamer" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::HaddockCDKCamera::_initStartParams () protected virtual
Reimplemented from Voxel::TI::ToFHaddockCamera.
Definition at line 165 of file HaddockCDKCamera.cpp.
References Voxel::TI::ToFCamera::_getFrameSize(), Voxel::TI::ToFCamera::_initStartParams(), _setStreamerFrameSize(), CONFIDENCE_THRESHOLD, FB_READY_EN, Voxel::DepthCamera::set(), and TG_EN.
 {
   if(!set(TG_EN, true) ||
      !set(FB_READY_EN, true) ||
      !set(CONFIDENCE_THRESHOLD, 1U))
     return false;
   FrameSize s;
   // Re-calculate stream size everytime on start of stream. This is necessary because stream size
   // depends on parameters which could be changed in between...
   if(!_getFrameSize(s) || !_setStreamerFrameSize(s))
     return false;
   return ToFCamera::_initStartParams(); // skip ToFHaddockCamera::_initStartParams()
 }
bool Voxel::TI::HaddockCDKCamera::_setStreamerFrameSize (const FrameSize & s) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 188 of file HaddockCDKCamera.cpp.
References Voxel::DepthCamera::_get(), Voxel::TI::ToFCamera::_getToFFrameType(), Voxel::DepthCamera::_streamer, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, PIXEL_DATA_SIZE, QUAD_CNT_MAX, Voxel::USBBulkStreamer::setBufferSize(), Voxel::ToF_QUAD, and Voxel::FrameSize::width.
Referenced by _init(), and _initStartParams().
 {
   USBBulkStreamer *streamer = dynamic_cast<USBBulkStreamer *>(&*_streamer);
   if(!streamer)
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Streamer is not of type USBBulkStreamer" << std::endl;
     return false;
   }
   int bytesPerPixel;
   int quadCount;
   ToFFrameType frameType;
   if(!_get(PIXEL_DATA_SIZE, bytesPerPixel) || !_get(QUAD_CNT_MAX, quadCount) || !_getToFFrameType(frameType))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   uint scaleFactor = bytesPerPixel;
   if(frameType == ToF_QUAD)
     scaleFactor = quadCount*2;
   if(!streamer->setBufferSize(s.height*s.width*scaleFactor))
   {
     logger(LOG_ERROR) << "HaddockCDKCamera: Could not set video mode for USBBulkStreamer" << std::endl;
     return false;
   }
   return true;
 }
Friends And Related Function Documentation
friend class HaddockCDKIlluminationPowerPercentageParameter friend
Definition at line 47 of file HaddockCDKCamera.h.
Referenced by _init().
Member Data Documentation
Ptr<Downloader> Voxel::TI::HaddockCDKCamera::_downloader protected
Definition at line 30 of file HaddockCDKCamera.h.
The documentation for this class was generated from the following files:
HaddockCDKCamera.h
HaddockCDKCamera.cpp