Voxel: Voxel::DiscreteGaussian Class Reference
Voxel::DiscreteGaussian Class Reference
#include <DiscreteGaussian.h>
Public Member Functions
DiscreteGaussian (float s)
void setStandardDeviation (float s)
float getStandardDeviation () const
float getSquaredStandardDeviation () const
float valueAt (int x)
Private Member Functions
void _computeValues ()
Private Attributes
float _sigma
float _squaredSigma
Vector< float > _values
Detailed Description
Definition at line 19 of file DiscreteGaussian.h.
Constructor & Destructor Documentation
Voxel::DiscreteGaussian::DiscreteGaussian (float s) inline
Definition at line 28 of file DiscreteGaussian.h.
 { setStandardDeviation(s); }
Member Function Documentation
void Voxel::DiscreteGaussian::_computeValues () inline private
Definition at line 51 of file DiscreteGaussian.h.
References _sigma, _squaredSigma, _values, and Voxel::floatEquals().
 {
   int limit = sqrt(20)*_sigma + 1; // This would correspond to exp(-10)
   _values.resize(limit);
   if(!floatEquals(_sigma, 0))
   {
     float d = _sigma*sqrt(2*M_PI);
     for(auto i = 0; i < limit; i++)
       _values[i] = exp(-i*i/2.0f/_squaredSigma)/d;
   }
   else
     _values[0] = 1;
 }
float Voxel::DiscreteGaussian::getSquaredStandardDeviation () const inline
Definition at line 38 of file DiscreteGaussian.h.
 { return _squaredSigma; }
float Voxel::DiscreteGaussian::getStandardDeviation () const inline
Definition at line 37 of file DiscreteGaussian.h.
 { return _sigma; }
void Voxel::DiscreteGaussian::setStandardDeviation (float s) inline
Definition at line 30 of file DiscreteGaussian.h.
Referenced by Voxel::BilateralFilter::_onSet(), and Voxel::SmoothFilter::_onSet().
   {
     _sigma = s;
     _squaredSigma = _sigma*_sigma;
     _computeValues();
   }
float Voxel::DiscreteGaussian::valueAt (int x) inline
Definition at line 40 of file DiscreteGaussian.h.
References LensCalibrationTest::y.
Referenced by Voxel::BilateralFilter::_filter(), and Voxel::SmoothFilter::_filter().
   {
     int y = (x < 0)?-x:x;
     if(y >= _values.size())
       return 0.0f;
     else
       return _values[y];
   }
Member Data Documentation
float Voxel::DiscreteGaussian::_sigma private
Definition at line 21 of file DiscreteGaussian.h.
Referenced by _computeValues().
float Voxel::DiscreteGaussian::_squaredSigma private
Definition at line 21 of file DiscreteGaussian.h.
Referenced by _computeValues().
Vector<float> Voxel::DiscreteGaussian::_values private
Definition at line 23 of file DiscreteGaussian.h.
Referenced by _computeValues().
The documentation for this class was generated from the following file:
DiscreteGaussian.h