Voxel: Voxel::USBDownloader Class Reference
Voxel::USBDownloader Class Reference
I/O classes
#include <Downloader.h>
Public Member Functions
USBDownloader (DevicePtr device)
virtual bool download (const String &file)
virtual ~USBDownloader ()
Public Member Functions inherited from Voxel::Downloader
Downloader (DevicePtr device)
void setLogCallback (LoggerOutStream::LoggerOutStreamFunctionType f)
void removeLogCallback ()
void setProgressFunction (ProgressFunctionType f)
void removeProgressFunction ()
float getProgress ()
virtual ~Downloader ()
Protected Member Functions
virtual bool _configureForDownload ()
virtual bool _download (InputFileStream &file, long unsigned int filesize)
Protected Member Functions inherited from Voxel::Downloader
virtual bool _locateFile (String &file)
void _setProgress (float progress)
void _setProgressIncrement (float progress)
Protected Attributes
USBIOPtr _usbIO
Protected Attributes inherited from Voxel::Downloader
DevicePtr _device
LoggerOutStream _outStream
ProgressFunctionType _progressFunction
float _progress = 0
Additional Inherited Members
Public Types inherited from Voxel::Downloader
typedef Function< void(float)> ProgressFunctionType
Detailed Description
Definition at line 70 of file Downloader.h.
Constructor & Destructor Documentation
Voxel::USBDownloader::USBDownloader (DevicePtr device)
Definition at line 103 of file Downloader.cpp.
                                             : Downloader(device), _usbIO(new USBIO(device))
 {
 }
virtual Voxel::USBDownloader::~USBDownloader () inline virtual
Definition at line 83 of file Downloader.h.
 {}
Member Function Documentation
bool Voxel::USBDownloader::_configureForDownload () protected virtual
Reimplemented in Voxel::TI::TintinEEPROMDownloader.
Definition at line 33 of file Downloader.cpp.
References Voxel::Downloader::_outStream, Voxel::Downloader::_setProgress(), _usbIO, Voxel::LOG_ERROR, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, and Voxel::USBIO::TO_DEVICE.
Referenced by download().
 {
   if(!_usbIO->isInitialized())
   {
     logger(LOG_ERROR) << "USBDownloader: USBIO not initialized" << std::endl;
     _outStream << "USBDownloader: USBIO not initialized" << std::endl;
     return false;
   }
   uint8_t buffer[4];
   // FIXME: Explain these magic numbers
   buffer[0] = 0x89;
   buffer[1] = 0xCB;
   buffer[2] = 0x07;
   buffer[3] = 0x00;
   uint16_t length = 4;
   bool ret = _usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, 0x05, 0, 0, buffer, length, true, 5000);
   _setProgress(10);
   return ret;
 }
bool Voxel::USBDownloader::_download (InputFileStream & file, long unsigned int filesize) protected virtual
Reimplemented in Voxel::TI::TintinEEPROMDownloader.
Definition at line 56 of file Downloader.cpp.
References Voxel::Downloader::_setProgress(), _usbIO, Voxel::Downloader::getProgress(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by download().
 {
   unsigned char endpointOut = 0x06;
   unsigned char buffer[4096];
   typedef long TransferSizeType;
   TransferSizeType transferSize;
   TransferSizeType bytesToRead = filesize;
   TransferSizeType transferred = 0, t;
   int status;
   float p = getProgress();
   while (bytesToRead > 0) {
     transferSize = bytesToRead > 4096 ? 4096 : bytesToRead;
     file.read((char *)buffer, transferSize);
     status = file.gcount();
     if (status < transferSize)
       logger(LOG_DEBUG) << "USBDownloader: Read less bytes than expected" << std::endl;
     if(!_usbIO->bulkTransfer(endpointOut, buffer, transferSize, transferred))
     {
       logger(LOG_ERROR) << "USBDownloader: Bulk transfer failed." << std::endl;
       return false;
     }
     while(transferred < transferSize)
     {
       if(!_usbIO->bulkTransfer(endpointOut, buffer + transferred, transferSize - transferred, t))
       {
         logger(LOG_ERROR) << "USBDownloader: Bulk transfer failed." << std::endl;
         return false;
       }
       transferred += t;
     }
     bytesToRead -= transferred;
     _setProgress(p + (100 - p)*(1 - bytesToRead*1.0/filesize));
   }
   return true;
 }
bool Voxel::USBDownloader::download (const String & file) virtual
Implements Voxel::Downloader.
Definition at line 108 of file Downloader.cpp.
References _configureForDownload(), _download(), Voxel::Downloader::_locateFile(), Voxel::Downloader::_outStream, Voxel::Downloader::_setProgress(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by main().
 {
   _setProgress(0);
   String fil = file;
   if(!_locateFile(fil))
   {
     logger(LOG_ERROR) << "USBDownloader: Could not locate '" << file << "'." << std::endl;
     _outStream << "USBDownloader: Could not locate '" << file << "'." << std::endl;
     return false;
   }
   std::ifstream f(fil, std::ios::binary | std::ios::ate);
   if(!f.good())
   {
     logger(LOG_ERROR) << "USBDownloader: Could not open '" << fil << "'." << std::endl;
     _outStream << "USBDownloader: Could not open '" << fil << "'." << std::endl;
     return false;
   }
   std::streamoff size = f.tellg();
   f.seekg(std::ios::beg);
   bool ret = _configureForDownload() && _download(f, size);
   _setProgress(100);
   return ret;
 }
Member Data Documentation
USBIOPtr Voxel::USBDownloader::_usbIO protected
Definition at line 73 of file Downloader.h.
Referenced by Voxel::TI::TintinEEPROMDownloader::_configureForDownload(), _configureForDownload(), Voxel::TI::TintinEEPROMDownloader::_download(), _download(), Voxel::TI::TintinEEPROMDownloader::_getEEPROMStatus(), and Voxel::TI::TintinEEPROMDownloader::_printEEPROMFirst64Bytes().
The documentation for this class was generated from the following files:
Downloader.h
Downloader.cpp