Voxel: Voxel::TI::ToFTintinCamera Class Reference
Voxel::TI::ToFTintinCamera Class Reference
#include <ToFTintinCamera.h>
Public Member Functions
ToFTintinCamera (const String &name, DevicePtr device)
virtual bool _getMaximumFrameSize (FrameSize &s) const
virtual ~ToFTintinCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (const int id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _initStartParams ()
virtual bool _getIlluminationFrequency (float &frequency) const
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _getFrameSize (FrameSize &s) const
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _setStreamerFrameSize (const FrameSize &s)=0
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const =0
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const =0
virtual bool _getFieldOfView (float &fovHalfAngle) const =0
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Friends
class TintinVCOFrequency
class TintinModulationFrequencyParameter
class TintinUnambiguousRangeParameter
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Detailed Description
Definition at line 76 of file ToFTintinCamera.h.
Constructor & Destructor Documentation
Voxel::TI::ToFTintinCamera::ToFTintinCamera (const String & name, DevicePtr device)
Definition at line 344 of file ToFTintinCamera.cpp.
                                                                     : ToFCamera(name, device)
 {
 }
virtual Voxel::TI::ToFTintinCamera::~ToFTintinCamera () inline virtual
Definition at line 100 of file ToFTintinCamera.h.
 {}
Member Function Documentation
bool Voxel::TI::ToFTintinCamera::_allowedROI (String & message) protected virtual
Implements Voxel::DepthCamera.
Definition at line 434 of file ToFTintinCamera.cpp.
 {
   message  = "Column start and end must be multiples of 16, both between 0 to 319. ";
   message += "Row start and end must be between 0 to 239.";
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_applyCalibrationParams () protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 541 of file ToFTintinCamera.cpp.
References CALIB_DISABLE, CALIB_PREC, CALIB_SECT_COMMON_PHASE, CALIB_SECT_CROSS_TALK, CALIB_SECT_NON_LINEARITY, CALIB_SECT_TEMPERATURE, COEFF_ILLUM_1, COEFF_SENSOR_1, Voxel::DepthCamera::configFile, CROSS_TALK_EN, CROSS_TALK_FILT_COEFF_X_IM_F1, CROSS_TALK_FILT_COEFF_X_IM_F2, CROSS_TALK_FILT_COEFF_X_RE_F1, CROSS_TALK_FILT_COEFF_X_RE_F2, CROSS_TALK_FILT_COEFF_Y_IM_F1, CROSS_TALK_FILT_COEFF_Y_IM_F2, CROSS_TALK_FILT_COEFF_Y_RE_F1, CROSS_TALK_FILT_COEFF_Y_RE_F2, CROSS_TALK_SCALE, DISABLE_OFFSET_CORR, DISABLE_TEMP_CORR, Voxel::MainConfigurationFile::get(), Voxel::ConfigurationFile::getBoolean(), Voxel::ConfigurationFile::getInteger(), Voxel::MainConfigurationFile::isPresent(), NONLINEARITY_COEFF_F1, NONLINEARITY_COEFF_F2, NONLINEARITY_ENABLE, NONLINEARITY_PHASE_PERIOD, PHASE_CORR_1, PHASE_CORR_2, Voxel::DepthCamera::set(), TILLUM_CALIB, TSENSOR_CALIB, X_CROSS_TALK_COEFF_F1, X_CROSS_TALK_COEFF_F2, Y_CROSS_TALK_COEFF_F1, and Y_CROSS_TALK_COEFF_F2.
 {
   bool commonPhaseCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_COMMON_PHASE) == 0;
   bool temperatureCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_TEMPERATURE) == 0;
   bool crossTalkCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_CROSS_TALK) == 0;
   bool nonlinearityCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_NON_LINEARITY) == 0;
   if(commonPhaseCalibEnable)
   {
     if(!set(PHASE_CORR_1, configFile.getInteger("calib", PHASE_CORR_1)) ||
       !set(PHASE_CORR_2, configFile.getInteger("calib", PHASE_CORR_2)) ||
       !set(TILLUM_CALIB, (uint)configFile.getInteger("calib", TILLUM_CALIB)) ||
       !set(TSENSOR_CALIB, (uint)configFile.getInteger("calib", TSENSOR_CALIB)) ||
       !set(DISABLE_OFFSET_CORR, configFile.getBoolean("calib", DISABLE_OFFSET_CORR)))
       return false;
   }
   else
   {
     if(!set(DISABLE_OFFSET_CORR, true))
       return false;
   }
   if(temperatureCalibEnable)
   {
     if(!set(DISABLE_TEMP_CORR, configFile.getBoolean("calib", DISABLE_TEMP_CORR)) ||
       !set(CALIB_PREC, configFile.getBoolean("calib", CALIB_PREC)) ||
       !set(COEFF_ILLUM_1, configFile.getInteger("calib", COEFF_ILLUM_1)) ||
       !set(COEFF_SENSOR_1, configFile.getInteger("calib", COEFF_SENSOR_1)))
       return false;
   }
   else
   {
     if(!set(DISABLE_TEMP_CORR, true))
       return false;
   }
   if(crossTalkCalibEnable && configFile.isPresent("calib", X_CROSS_TALK_COEFF_F1) && configFile.isPresent("calib", Y_CROSS_TALK_COEFF_F1) &&
     configFile.isPresent("calib", X_CROSS_TALK_COEFF_F2) && configFile.isPresent("calib", Y_CROSS_TALK_COEFF_F2))
   {
     String crossTalk =
       configFile.get("calib", X_CROSS_TALK_COEFF_F1) + " " +
       configFile.get("calib", Y_CROSS_TALK_COEFF_F1) + " " +
       configFile.get("calib", X_CROSS_TALK_COEFF_F2) + " " +
       configFile.get("calib", Y_CROSS_TALK_COEFF_F2);
     Vector<Complex> coefficients;
     coefficients.reserve(4);
     std::istringstream ss(crossTalk);
     std::copy(std::istream_iterator<Complex>(ss),
               std::istream_iterator<Complex>(),
               std::back_inserter(coefficients));
     if(coefficients.size() != 4)
       return false;
     float min = 128, max = 0;
     for(auto i = 0; i < coefficients.size(); i++)
     {
       if(std::fabs(coefficients[i].real()) < min)
         min = std::fabs(coefficients[i].real());
       if(std::fabs(coefficients[i].imag()) < min)
         min = std::fabs(coefficients[i].imag());
       if(std::fabs(coefficients[i].real()) > max)
         max = std::fabs(coefficients[i].real());
       if(std::fabs(coefficients[i].imag()) > max)
         max = std::fabs(coefficients[i].imag());
     }
     uint scale = 3;
     min *= 128*4;
     max *= 128*4;
     while(max*(1 << scale) > 127 && scale > 0)
       scale--;
     uint scale2 = 128*4*(1 << scale);
     if(
       !set(CROSS_TALK_FILT_COEFF_X_RE_F1, (int)(coefficients[0].real()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_X_IM_F1, (int)(coefficients[0].imag()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_Y_RE_F1, (int)(coefficients[1].real()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_Y_IM_F1, (int)(coefficients[1].imag()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_X_RE_F2, (int)(coefficients[2].real()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_X_IM_F2, (int)(coefficients[2].imag()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_Y_RE_F2, (int)(coefficients[3].real()*scale2)) ||
       !set(CROSS_TALK_FILT_COEFF_Y_IM_F2, (int)(coefficients[3].imag()*scale2)) ||
       !set(CROSS_TALK_SCALE, scale) ||
       !set(CROSS_TALK_EN, true))
       return false;
   }
   else
   {
     if(!set(CROSS_TALK_EN, false))
       return false;
   }
   if(nonlinearityCalibEnable && configFile.isPresent("calib", NONLINEARITY_COEFF_F1) && configFile.isPresent("calib", NONLINEARITY_COEFF_F2) &&
     configFile.isPresent("calib", NONLINEARITY_PHASE_PERIOD))
   {
     Vector<uint> nlCoeff1, nlCoeff2;
     nlCoeff1.reserve(16);
     nlCoeff2.reserve(16);
     {
       std::istringstream ss(configFile.get("calib", NONLINEARITY_COEFF_F1));
       std::copy(std::istream_iterator<uint>(ss),
                 std::istream_iterator<uint>(),
                 std::back_inserter(nlCoeff1));
     }
     {
       std::istringstream ss(configFile.get("calib", NONLINEARITY_COEFF_F2));
       std::copy(std::istream_iterator<uint>(ss),
                 std::istream_iterator<uint>(),
                 std::back_inserter(nlCoeff2));
     }
     if(nlCoeff1.size() != 16 || nlCoeff2.size() != 16)
       return false;
     int phasePeriod = configFile.getInteger("calib", NONLINEARITY_PHASE_PERIOD);
     String n1 = NONLINEARITY_COEFF_F1, n2 = NONLINEARITY_COEFF_F2;
     for(auto i = 0; i < 16; i++)
       if(!set(n1 + "_" + std::to_string(i), nlCoeff1[i]) || !set(n2 + "_" + std::to_string(i), nlCoeff2[i]))
         return false;
     if(!set(NONLINEARITY_PHASE_PERIOD, phasePeriod) || !set(NONLINEARITY_ENABLE, true))
       return false;
   }
   else
   {
     if(!set(NONLINEARITY_ENABLE, false))
       return false;
   }
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_getCurrentProfileRegisterName (String & name) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 693 of file ToFTintinCamera.cpp.
References SCRATCH2.
 {
   name = SCRATCH2;
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_getIlluminationFrequency (float & frequency) const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 504 of file ToFTintinCamera.cpp.
References _getSystemClockFrequency(), DEALIAS_EN, Voxel::gcd(), MOD_FREQ1, MOD_M1, MOD_M2, MOD_N1, MOD_N2, MOD_PS1, MOD_PS2, and QUAD_CNT_MAX.
 {
   bool dealiasingEnabled;
   uint modulationPS1, modulationPS2, systemClockFrequency;
   uint modM1, modM2, modN1, modN2;
   int quadCount;
   if(!get(DEALIAS_EN, dealiasingEnabled))
     return false;
   if(dealiasingEnabled)
   {
     if(!_getSystemClockFrequency(systemClockFrequency) || !get(MOD_PS1, modulationPS1) || !get(MOD_PS2, modulationPS2) ||
       !get(QUAD_CNT_MAX, quadCount) ||
       !get(MOD_M1, modM1) || !get(MOD_M2, modM2) ||
       !get(MOD_N1, modN1) || !get(MOD_N2, modN2))
       return false;
     modulationPS1 ++;
     modulationPS2 ++;
     /* TODO: Handle the case for fractional modulation frequencies */
     frequency = systemClockFrequency*gcd(modM1*modN2*modulationPS2, modM2*modN1*modulationPS1)/(modN1*modN2*modulationPS1*modulationPS2*quadCount);
     return true;
   }
   else
   {
     if(!get(MOD_FREQ1, frequency))
       return false;
     return true;
   }
 }
bool Voxel::TI::ToFTintinCamera::_getMaximumFrameSize (FrameSize & s) const virtual
Implements Voxel::DepthCamera.
Definition at line 355 of file ToFTintinCamera.cpp.
References Voxel::FrameSize::height, and Voxel::FrameSize::width.
 {
   s.width = 320;
   s.height = 240;
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_getROI (RegionOfInterest & roi) protected virtual
Implements Voxel::DepthCamera.
Definition at line 441 of file ToFTintinCamera.cpp.
References Voxel::DepthCamera::_get(), COL_END, COL_START, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, ROW_END, ROW_START, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
   uint rowStart, rowEnd, colStart, colEnd;
   if(!_get(ROW_START, rowStart) || !_get(ROW_END, rowEnd) || !_get(COL_START, colStart) || !_get(COL_END, colEnd))
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Could not get necessary parameters for ROI." << std::endl;
     return false;
   }
   colStart = colStart*16;
   colEnd = (colEnd + 1)*16 - 1;
   roi.x = colStart;
   roi.y = rowStart;
   roi.width = colEnd - colStart + 1;
   roi.height = rowEnd - rowStart + 1;
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_getSystemClockFrequency (uint & frequency) const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 348 of file ToFTintinCamera.cpp.
Referenced by _getIlluminationFrequency(), Voxel::TI::TintinVCOFrequency::get(), and Voxel::TI::TintinVCOFrequency::set().
 {
   frequency = 48;
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_init () protected
Definition at line 363 of file ToFTintinCamera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::TI::ToFCamera::_init(), Voxel::DepthCamera::_parameterInit, Voxel::DepthCamera::_programmer, Voxel::DepthCamera::configFile, Voxel::MainConfigurationFile::get(), Voxel::Configuration::getConfFile(), Voxel::ParameterDMLParser::getParameters(), Voxel::LOG_ERROR, Voxel::logger, MOD_FREQ1, MOD_FREQ2, MOD_M1, MOD_M2, MOD_M_FRAC1, MOD_M_FRAC2, MOD_N1, MOD_N2, MOD_PS1, MOD_PS2, Voxel::DepthCamera::name(), TintinModulationFrequencyParameter, TintinUnambiguousRangeParameter, TintinVCOFrequency, VCO_FREQ1, and VCO_FREQ2.
Referenced by Voxel::TI::VoxelDCamera::_init(), and Voxel::TI::TintinCDKCamera::_init().
 {
   Configuration c;
   String name = configFile.get("core", "dml");
   if(!name.size() || !c.getConfFile(name)) // true => name is now a proper path
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Failed to locate/read DML file '" << name << "'" << std::endl;
     return false;
   }
   ParameterDMLParser p(*_programmer, name);
   Vector<ParameterPtr> params;
   if(!p.getParameters(params))
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Could not read parameters from DML file '" << name << "'" << std::endl;
     return _parameterInit = false;
   }
   for(auto &p: params)
   {
     if((p->address() >> 8) == 0) // bankId == 0
       p->setAddress((0x58 << 8) + p->address());
     else if((p->address() >> 8) == 3) // bankId == 3
       p->setAddress((0x5C << 8) + (p->address() & 0xFF));
   }
   if(!_addParameters(params))
     return false;
   if(!_addParameters({
     ParameterPtr(new TintinVCOFrequency(*this, *_programmer, VCO_FREQ1, MOD_M1, MOD_M_FRAC1, MOD_N1)),
     ParameterPtr(new TintinVCOFrequency(*this, *_programmer, VCO_FREQ2, MOD_M2, MOD_M_FRAC2, MOD_N2)),
     ParameterPtr(new TintinModulationFrequencyParameter(*this, *_programmer, MOD_FREQ1, VCO_FREQ1, MOD_PS1)),
     ParameterPtr(new TintinModulationFrequencyParameter(*this, *_programmer, MOD_FREQ2, VCO_FREQ2, MOD_PS2)),
     ParameterPtr(new TintinUnambiguousRangeParameter(*this, *_programmer))
   }))
     return false;
   if(!ToFCamera::_init())
   {
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFTintinCamera::_initStartParams () protected virtual
set(DEBUG_EN, true) || // Uncomment this for sample data
Reimplemented from Voxel::TI::ToFCamera.
Reimplemented in Voxel::TI::TintinCDKCamera, and Voxel::TI::VoxelDCamera.
Definition at line 414 of file ToFTintinCamera.cpp.
References Voxel::TI::ToFCamera::_initStartParams(), Voxel::DepthCamera::_programmer, BLK_HEADER_EN, BLK_SIZE, CONFIDENCE_THRESHOLD, FB_READY_EN, MOD_PLL_UPDATE, OP_CS_POL, Voxel::DepthCamera::set(), and TG_DISABLE.
Referenced by Voxel::TI::VoxelDCamera::_initStartParams(), and Voxel::TI::TintinCDKCamera::_initStartParams().
 {
   if(
     !set(TG_DISABLE, true) ||
     !_programmer->writeRegister(0x583A, 0x008000) ||
     !_programmer->writeRegister(0x583A, 0x004000) ||
     !set(BLK_SIZE, 1024U) ||
     !set(BLK_HEADER_EN, true) ||
     !set(OP_CS_POL, true) ||
     !set(FB_READY_EN, true) ||
     !set(CONFIDENCE_THRESHOLD, 1U) ||
     !set(TG_DISABLE, false) ||
     !set(MOD_PLL_UPDATE, true) ||
     !set(MOD_PLL_UPDATE, false))
       return false;
   return ToFCamera::_initStartParams();
 }
bool Voxel::TI::ToFTintinCamera::_isHistogramEnabled () const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 499 of file ToFTintinCamera.cpp.
 {
   return false;
 }
bool Voxel::TI::ToFTintinCamera::_setROI (const RegionOfInterest & roi) protected virtual
Implements Voxel::DepthCamera.
Definition at line 461 of file ToFTintinCamera.cpp.
References Voxel::TI::ToFCamera::_getFrameSize(), Voxel::DepthCamera::_set(), Voxel::TI::ToFCamera::_setBinning(), Voxel::TI::ToFCamera::_setFrameSize(), COL_END, COL_START, Voxel::FrameSize::height, Voxel::DepthCamera::isRunning(), Voxel::LOG_ERROR, Voxel::logger, ROW_END, ROW_START, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
   if(isRunning())
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Cannot set frame size while the camera is streaming" << std::endl;
     return false;
   }
   uint rowStart, rowEnd, colStart, colEnd;
   colStart = (roi.x/16);
   colEnd = ((roi.x + roi.width)/16) - 1;
   rowStart = roi.y;
   rowEnd = rowStart + roi.height - 1;
   if(!_set(ROW_START, rowStart) || !_set(ROW_END, rowEnd) || !_set(COL_START, colStart) || !_set(COL_END, colEnd))
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Could not get necessary parameters for ROI." << std::endl;
     return false;
   }
   if(!_setBinning(1, 1, roi))
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Could not reset binning while setting ROI." << std::endl;
     return false;
   }
   FrameSize s;
   if(!_getFrameSize(s) || !_setFrameSize(s, false)) // Get and set frame size to closest possible
   {
     logger(LOG_ERROR) << "ToFTintinCamera: Could not update frame size to closest valid frame size" << std::endl;
     return false;
   }
   return true;
 }
Friends And Related Function Documentation
friend class TintinModulationFrequencyParameter friend
Definition at line 103 of file ToFTintinCamera.h.
Referenced by _init().
friend class TintinUnambiguousRangeParameter friend
Definition at line 104 of file ToFTintinCamera.h.
Referenced by _init().
friend class TintinVCOFrequency friend
Definition at line 102 of file ToFTintinCamera.h.
Referenced by _init().
The documentation for this class was generated from the following files:
ToFTintinCamera.h
ToFTintinCamera.cpp