Voxel: Voxel::Timer Class Reference
Voxel::Timer Class Reference
Common and Utility classes
#include <Timer.h>
Public Member Functions
Timer ()
bool isInitialized ()
bool init ()
TimeStampType convertToRealTime (TimeStampType l)
TimeStampType getCurentRealTime ()
Private Attributes
TimeStampType _realTimeStart = 0
TimeStampType _monoticStart = 0
bool _initialized = false
Detailed Description
Definition at line 21 of file Timer.h.
Constructor & Destructor Documentation
Voxel::Timer::Timer () inline
Definition at line 28 of file Timer.h.
   {
     init();
   }
Member Function Documentation
TimeStampType Voxel::Timer::convertToRealTime (TimeStampType l)
Definition at line 93 of file Timer.cpp.
References _monoticStart, and _realTimeStart.
Referenced by Voxel::UVCStreamer::_capture().
 {
   if(l > _realTimeStart) // Is it already real-time?
     return l;
   return (l - _monoticStart) + _realTimeStart;
 }
TimeStampType Voxel::Timer::getCurentRealTime ()
Definition at line 101 of file Timer.cpp.
Referenced by Voxel::UVCStreamer::_capture(), Voxel::TI::TintinCDKCamera::_readConfigFromHardware(), Voxel::TI::TintinCDKCamera::_writeConfigFromHardware(), Voxel::USBBulkStreamer::USBBulkStreamerPrivate::putBuffer(), Voxel::USBBulkStreamer::USBBulkStreamerPrivate::run(), and Voxel::MainConfigurationFile::writeToHardware().
 {
 #ifdef LINUX
   struct timespec tp;
   if(clock_gettime(CLOCK_REALTIME, &tp) == -1)
     return 0;
   else
     return tp.tv_sec*1000000L + tp.tv_nsec/1000;
 #elif defined(WINDOWS)
   TimeStampType t;
   clock_gettime(t);
   return t;
 #endif
 }
bool Voxel::Timer::init ()
Definition at line 68 of file Timer.cpp.
References _initialized, _monoticStart, _realTimeStart, Voxel::LOG_ERROR, Voxel::logger, and LensCalibrationTest::r2.
 {
 #ifdef LINUX
   struct timespec t1, t2;
   int r1, r2;
   r1 = clock_gettime(CLOCK_REALTIME, &t1);
   r2 = clock_gettime(CLOCK_MONOTONIC, &t2);
   if(r1 == -1 || r2 == -1)
   {
     logger(LOG_ERROR) << "Time: Failed to get current time." << std::endl;
     return _initialized = false;
   }
   _realTimeStart = t1.tv_sec*1000000L + t1.tv_nsec/1000;
   _monoticStart = t2.tv_sec*1000000L + t2.tv_nsec/1000;
 #elif defined(WINDOWS)
   clock_gettime(_realTimeStart);
   _monoticStart = _realTimeStart;
 #endif
   return _initialized = true;
 }
bool Voxel::Timer::isInitialized () inline
Definition at line 33 of file Timer.h.
 { return _initialized; }
Member Data Documentation
bool Voxel::Timer::_initialized = false private
Definition at line 25 of file Timer.h.
Referenced by init().
TimeStampType Voxel::Timer::_monoticStart = 0 private
Definition at line 23 of file Timer.h.
Referenced by convertToRealTime(), and init().
TimeStampType Voxel::Timer::_realTimeStart = 0 private
Definition at line 23 of file Timer.h.
Referenced by convertToRealTime(), and init().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp