Voxel: TinyXML2::XMLComment Class Reference
TinyXML2::XMLComment Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual const XMLComment * ToComment () const
virtual bool Accept (XMLVisitor *visitor) const
char * ParseDeep (char *, StrPair *endTag)
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from TinyXML2::XMLNode
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
Protected Member Functions
XMLComment (XMLDocument *doc)
virtual ~XMLComment ()
XMLComment (const XMLComment &)
XMLComment & operator= (const XMLComment &)
Protected Member Functions inherited from TinyXML2::XMLNode
XMLNode (XMLDocument *)
virtual ~XMLNode ()
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Friends
class XMLDocument
Additional Inherited Members
Protected Attributes inherited from TinyXML2::XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Detailed Description
An XML Comment.
Definition at line 963 of file TinyXML2.h.
Constructor & Destructor Documentation
TinyXML2::XMLComment::XMLComment (XMLDocument * doc) protected
Definition at line 970 of file TinyXML2.cpp.
                                          : XMLNode( doc )
 {
 }
TinyXML2::XMLComment::~XMLComment () protected virtual
Definition at line 975 of file TinyXML2.cpp.
 {
 }
TinyXML2::XMLComment::XMLComment (const XMLComment &) protected
Member Function Documentation
bool TinyXML2::XMLComment::Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements TinyXML2::XMLNode.
Definition at line 1010 of file TinyXML2.cpp.
References TIXMLASSERT, and TinyXML2::XMLVisitor::Visit().
 {
     TIXMLASSERT( visitor );
     return visitor->Visit( *this );
 }
XMLComment& TinyXML2::XMLComment::operator= (const XMLComment &) protected
char * TinyXML2::XMLComment::ParseDeep (char * p, StrPair * endTag) virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 980 of file TinyXML2.cpp.
References TinyXML2::XMLNode::_document, TinyXML2::XMLNode::_value, TinyXML2::StrPair::COMMENT, TinyXML2::StrPair::ParseText(), TinyXML2::XMLDocument::SetError(), and TinyXML2::XML_ERROR_PARSING_COMMENT.
 {
     // Comment parses as text.
     const char* start = p;
     p = _value.ParseText( p, "-->", StrPair::COMMENT );
     if ( p == 0 ) {
         _document->SetError( XML_ERROR_PARSING_COMMENT, start, 0 );
     }
     return p;
 }
XMLNode * TinyXML2::XMLComment::ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements TinyXML2::XMLNode.
Definition at line 992 of file TinyXML2.cpp.
References TinyXML2::XMLNode::_document, TinyXML2::XMLDocument::NewComment(), and TinyXML2::XMLNode::Value().
 {
     if ( !doc ) {
         doc = _document;
     }
     XMLComment* comment = doc->NewComment( Value() ); // fixme: this will always allocate memory. Intern?
     return comment;
 }
bool TinyXML2::XMLComment::ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements TinyXML2::XMLNode.
Definition at line 1002 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::StringEqual(), TIXMLASSERT, TinyXML2::XMLNode::ToComment(), and TinyXML2::XMLNode::Value().
 {
     TIXMLASSERT( compare );
     const XMLComment* comment = compare->ToComment();
     return ( comment && XMLUtil::StringEqual( comment->Value(), Value() ));
 }
virtual XMLComment* TinyXML2::XMLComment::ToComment () inline virtual
Safely cast to a Comment, or null.
Reimplemented from TinyXML2::XMLNode.
Definition at line 967 of file TinyXML2.h.
{
         return this;
     }
virtual const XMLComment* TinyXML2::XMLComment::ToComment () const inline virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 970 of file TinyXML2.h.
{
         return this;
     }
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 965 of file TinyXML2.h.
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp