Voxel: Voxel::ParameterTemplate< T > Class Template Reference
Voxel::ParameterTemplate< T > Class Template Reference abstract
Parameter related classes
#include <Parameter.h>
Public Member Functions
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool set (const T &value)
virtual bool validate (const T &value) const =0
virtual bool refresh ()
virtual bool get (T &value, bool refresh=false)
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Static Public Member Functions
static Ptr< ParameterTemplate
< T > > typeCast (const ParameterPtr &other)
Protected Member Functions
virtual uint32_t _toRawValue (T value) const
virtual T _fromRawValue (uint32_t value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes
T _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Detailed Description
template<typename T>
class Voxel::ParameterTemplate< T >
Definition at line 90 of file Parameter.h.
Constructor & Destructor Documentation
template<typename T> Voxel::ParameterTemplate< T >::ParameterTemplate (RegisterProgrammer & programmer, const String & name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T & defaultValue, const String & displayName, const String & description, Parameter::IOType ioType = Parameter::IO_READ_WRITE, const Vector< String > & dependencies = {}) inline
Definition at line 106 of file Parameter.h.
                                                                                                                                                                 {}):
   Parameter(programmer, name, address, registerLength, msb, lsb, displayName, description, ioType, dependencies), _value(defaultValue)
   {
   }
template<typename T> virtual Voxel::ParameterTemplate< T >::~ParameterTemplate () inline virtual
Definition at line 174 of file Parameter.h.
 {}
Member Function Documentation
template<typename T> virtual T Voxel::ParameterTemplate< T >::_fromRawValue (uint32_t value) const inline protected virtual
Reimplemented in Voxel::FloatParameter, Voxel::IntegerParameter, Voxel::TI::TintinCDKMainCurrentParameter, Voxel::BoolParameter, Voxel::TI::TintinCDKIllumCurrentParameter, Voxel::TI::TintinCDKIllumVrefParameter, Voxel::TI::TintinCDKIlluminationPowerParameter, Voxel::TI::TintinCDKPVDDParameterRev2, Voxel::TI::HaddockCDKIlluminationPowerParameter, Voxel::TI::TintinCDKPVDDParameterRev1, Voxel::TI::CalculusCDKPVDDVoltageParameter, Voxel::TI::Voxel14IlluminationVoltageParameter, Voxel::TI::VoxelDIlluminationVoltageParameter, Voxel::TI::TintinCDKMixVoltageParameter, Voxel::TI::CalculusCDKMixVoltageParameter, Voxel::TI::HaddockCDKMixVoltageParameter, Voxel::TI::Voxel14MixVoltageParameter, and Voxel::TI::VoxelDMixVoltageParameter.
Definition at line 100 of file Parameter.h.
Referenced by Voxel::ParameterTemplate< bool >::get().
   {
     return (T)(value);
   }
template<typename T> virtual uint32_t Voxel::ParameterTemplate< T >::_toRawValue (T value) const inline protected virtual
Reimplemented in Voxel::FloatParameter, Voxel::IntegerParameter, and Voxel::BoolParameter.
Definition at line 95 of file Parameter.h.
Referenced by Voxel::ParameterTemplate< bool >::set().
   {
     return (uint32_t)value;
   }
template<typename T> virtual bool Voxel::ParameterTemplate< T >::get (T & value, bool refresh = false) inline virtual
Reimplemented in Voxel::TI::HaddockSensorTemperatureParameter, Voxel::StrobeBoolParameter, Voxel::TI::CalculusModulationFrequencyParameter, Voxel::TI::TintinModulationFrequencyParameter, Voxel::TI::CalculusVCOFrequency, Voxel::TI::HaddockModulationFrequencyParameter, Voxel::TI::TintinVCOFrequency, and Voxel::TI::HaddockVCOFrequency.
Definition at line 142 of file Parameter.h.
Referenced by Voxel::DepthCamera::_get(), Voxel::CLIManager::_getParameter(), Voxel::CLIManager::_showParameterInfo(), Voxel::TI::TintinCDKIlluminationPowerPercentParameter::get(), and Voxel::TI::HaddockUnambiguousRangeParameter::get().
   {
     if(!refresh || _ioType == IO_WRITE_ONLY)
     {
       value = _value;
       return true;
     }
     uint32_t v;
     T val;
     if(!_programmer.getValue(*this, v))
     {
       value = _value;
       return false;
     }
     else
     {
       val = _fromRawValue(v);
       if(validate(val))
       {
         value = val;
         _value = val;
         return true;
       }
       else
       {
         value = _value;
         return false;
       }
     }
   }
template<typename T> virtual bool Voxel::ParameterTemplate< T >::refresh () inline virtual
Implements Voxel::Parameter.
Definition at line 136 of file Parameter.h.
Referenced by Voxel::TI::IntegrationTimeParameter::get(), Voxel::TI::HaddockCDKIlluminationPowerPercentageParameter::get(), Voxel::ParameterTemplate< bool >::get(), Voxel::TI::HaddockUnambiguousRangeParameter::get(), and Voxel::TI::TintinUnambiguousRangeParameter::get().
   {
     T v;
     return get(v, true);
   }
template<typename T> virtual bool Voxel::ParameterTemplate< T >::set (const T & value) inline virtual
Reimplemented in Voxel::TI::HaddockSensorTemperatureParameter, Voxel::TI::CalculusModulationFrequencyParameter, Voxel::TI::TintinModulationFrequencyParameter, Voxel::TI::CalculusVCOFrequency, Voxel::TI::HaddockModulationFrequencyParameter, Voxel::TI::TintinVCOFrequency, and Voxel::TI::HaddockVCOFrequency.
Definition at line 118 of file Parameter.h.
Referenced by Voxel::DepthCamera::_set(), Voxel::CLIManager::_setParameter(), Voxel::TI::TintinCDKIlluminationPowerPercentParameter::set(), Voxel::TI::HaddockUnambiguousRangeParameter::set(), and Voxel::TI::TintinUnambiguousRangeParameter::set().
   {
     if(_ioType == IO_READ_ONLY || !validate(value))
     {
       return false;
     }
     if(_programmer.setValue(*this, _toRawValue(value), _ioType == IO_WRITE_ONLY))
     {
       _value = value;
       return true;
     }
     else
       return false;
   }
template<typename T> static Ptr<ParameterTemplate<T> > Voxel::ParameterTemplate< T >::typeCast (const ParameterPtr & other) inline static
Definition at line 113 of file Parameter.h.
   {
     return std::dynamic_pointer_cast<ParameterTemplate<T>>(other);
   }
template<typename T> virtual bool Voxel::ParameterTemplate< T >::validate (const T & value) const pure virtual
Implemented in Voxel::RangeParameterTemplate< T >, Voxel::RangeParameterTemplate< float >, Voxel::RangeParameterTemplate< int >, Voxel::EnumParameter, and Voxel::BoolParameter.
Referenced by Voxel::ParameterTemplate< bool >::get(), and Voxel::ParameterTemplate< bool >::set().
Member Data Documentation
template<typename T> T Voxel::ParameterTemplate< T >::_value protected
Definition at line 93 of file Parameter.h.
Referenced by Voxel::ParameterTemplate< bool >::get(), Voxel::TI::HaddockUnambiguousRangeParameter::get(), Voxel::TI::TintinUnambiguousRangeParameter::get(), and Voxel::ParameterTemplate< bool >::set().
The documentation for this class was generated from the following file:
Parameter.h