Voxel: Voxel::TI::TintinCDKDownloaderFactory Class Reference
Voxel::TI::TintinCDKDownloaderFactory Class Reference
#include <TintinCDKDownloaderFactory.h>
Public Member Functions
TintinCDKDownloaderFactory (const String &name)
virtual DownloaderPtr getDownloader (DevicePtr device)
virtual ~TintinCDKDownloaderFactory ()
Public Member Functions inherited from Voxel::DownloaderFactory
DownloaderFactory (const String &name)
const String & name () const
const Vector< DevicePtr > & getSupportedDevices () const
virtual ~DownloaderFactory ()
Additional Inherited Members
Protected Member Functions inherited from Voxel::DownloaderFactory
void _addSupportedDevices (const Vector< DevicePtr > &devices)
Protected Attributes inherited from Voxel::DownloaderFactory
Vector< DevicePtr > _supportedDevices
String _name
Detailed Description
Definition at line 18 of file TintinCDKDownloaderFactory.h.
Constructor & Destructor Documentation
Voxel::TI::TintinCDKDownloaderFactory::TintinCDKDownloaderFactory (const String & name)
Definition at line 19 of file TintinCDKDownloaderFactory.cpp.
References Voxel::DownloaderFactory::_addSupportedDevices(), TINTIN_CDK_PRODUCT_BULK, TINTIN_CDK_PRODUCT_UVC, and TINTIN_CDK_VENDOR_ID.
                                                                         : DownloaderFactory(name)
 {
   _addSupportedDevices({
     DevicePtr(new USBDevice(TINTIN_CDK_VENDOR_ID, TINTIN_CDK_PRODUCT_BULK, "")),
     DevicePtr(new USBDevice(TINTIN_CDK_VENDOR_ID, TINTIN_CDK_PRODUCT_UVC, "")),
   });
 }
virtual Voxel::TI::TintinCDKDownloaderFactory::~TintinCDKDownloaderFactory () inline virtual
Definition at line 25 of file TintinCDKDownloaderFactory.h.
 {}
Member Function Documentation
DownloaderPtr Voxel::TI::TintinCDKDownloaderFactory::getDownloader (DevicePtr device) virtual
Implements Voxel::DownloaderFactory.
Definition at line 28 of file TintinCDKDownloaderFactory.cpp.
References Voxel::USBDevice::productID(), TINTIN_CDK_PRODUCT_BULK, TINTIN_CDK_PRODUCT_UVC, TINTIN_CDK_VENDOR_ID, Voxel::Device::USB, and Voxel::USBDevice::vendorID().
 {
   if(device->interfaceID() == Device::USB)
   {
     USBDevice &d = (USBDevice &)*device;
     if(d.vendorID() == TINTIN_CDK_VENDOR_ID &&
       (d.productID() == TINTIN_CDK_PRODUCT_BULK || d.productID() == TINTIN_CDK_PRODUCT_UVC))
     {
       return DownloaderPtr(new TintinEEPROMDownloader(device));
     }
   }
   return 0;
 }
The documentation for this class was generated from the following files:
TintinCDKDownloaderFactory.h
TintinCDKDownloaderFactory.cpp