Voxel: Voxel::TI::VoxelDCameraFactory Class Reference
Voxel::TI::VoxelDCameraFactory Class Reference
#include <VoxelDCameraFactory.h>
Public Member Functions
VoxelDCameraFactory (const String &name)
virtual DepthCameraPtr getDepthCamera (DevicePtr device)
virtual ~VoxelDCameraFactory ()
Public Member Functions inherited from Voxel::TI::ToFCameraFactoryBase
ToFCameraFactoryBase (const String &name)
virtual bool getChannels (Device &device, Vector< int > &channels)
virtual Vector< GeneratorIDType > getSupportedGeneratorTypes ()
virtual bool getFrameGenerator (uint8_t frameType, GeneratorIDType generatorID, FrameGeneratorPtr &frameGenerator)
virtual ~ToFCameraFactoryBase ()
Public Member Functions inherited from Voxel::DepthCameraFactory
DepthCameraFactory (const String &name)
const String & name () const
const Vector< DevicePtr > & getSupportedDevices () const
virtual ~DepthCameraFactory ()
Additional Inherited Members
Protected Member Functions inherited from Voxel::DepthCameraFactory
void _addSupportedDevices (const Vector< DevicePtr > &devices)
Protected Attributes inherited from Voxel::DepthCameraFactory
Vector< DevicePtr > _supportedDevices
String _name
Detailed Description
Definition at line 19 of file VoxelDCameraFactory.h.
Constructor & Destructor Documentation
Voxel::TI::VoxelDCameraFactory::VoxelDCameraFactory (const String & name)
Definition at line 21 of file VoxelDCameraFactory.cpp.
References Voxel::DepthCameraFactory::_addSupportedDevices(), VOXEL_D_PRODUCT_ID1, VOXEL_D_PRODUCT_ID2, and VOXEL_D_VENDOR_ID.
                                                           : ToFCameraFactoryBase(name)
 {
   _addSupportedDevices({
     DevicePtr(new USBDevice(VOXEL_D_VENDOR_ID, VOXEL_D_PRODUCT_ID1, "")),
     DevicePtr(new USBDevice(VOXEL_D_VENDOR_ID, VOXEL_D_PRODUCT_ID2, "")),
   });
 }
virtual Voxel::TI::VoxelDCameraFactory::~VoxelDCameraFactory () inline virtual
Definition at line 26 of file VoxelDCameraFactory.h.
 {}
Member Function Documentation
DepthCameraPtr Voxel::TI::VoxelDCameraFactory::getDepthCamera (DevicePtr device) virtual
Implements Voxel::DepthCameraFactory.
Definition at line 29 of file VoxelDCameraFactory.cpp.
References Voxel::USBDevice::productID(), Voxel::Device::USB, Voxel::USBDevice::vendorID(), VOXEL_D_PRODUCT_ID1, VOXEL_D_PRODUCT_ID2, and VOXEL_D_VENDOR_ID.
 {
   if(device->interfaceID() == Device::USB)
   {
     USBDevice &d = (USBDevice &)*device;
     if(d.vendorID() == VOXEL_D_VENDOR_ID &&
       (d.productID() == VOXEL_D_PRODUCT_ID1 || d.productID() == VOXEL_D_PRODUCT_ID2))
     {
       return DepthCameraPtr(new VoxelDCamera(device));
     }
   }
   return 0;
 }
The documentation for this class was generated from the following files:
VoxelDCameraFactory.h
VoxelDCameraFactory.cpp