Voxel: Voxel::PointCloudFrameTemplate< PointType > Class Template Reference
Voxel::PointCloudFrameTemplate< PointType > Class Template Reference
Frame related classes
#include <Frame.h>
Public Member Functions
virtual SizeType size () const
virtual Point * operator[] (IndexType index)
virtual Ptr< Frame > copy () const
virtual Ptr< Frame > copyTo (Ptr< Frame > &other) const
virtual Ptr< Frame > newFrame () const
virtual bool isSameType (const Frame &other) const
virtual bool isSameSize (const Frame &other) const
virtual bool serialize (SerializedObject &object) const
virtual bool deserialize (SerializedObject &object)
virtual ~PointCloudFrameTemplate ()
Public Member Functions inherited from Voxel::PointCloudFrame
virtual ~PointCloudFrame ()
Public Member Functions inherited from Voxel::Frame
operator String ()
virtual ~Frame ()
Static Public Member Functions
static Ptr
< PointCloudFrameTemplate
< PointType > > typeCast (FramePtr ptr)
Static Public Member Functions inherited from Voxel::PointCloudFrame
static Ptr< PointCloudFrame > typeCast (FramePtr ptr)
Public Attributes
Vector< PointType > points
Public Attributes inherited from Voxel::Frame
TimeStampType timestamp = 0
int id = -1
Detailed Description
template<typename PointType>
class Voxel::PointCloudFrameTemplate< PointType >
Definition at line 662 of file Frame.h.
Constructor & Destructor Documentation
template<typename PointType> virtual Voxel::PointCloudFrameTemplate< PointType >::~PointCloudFrameTemplate () inline virtual
Definition at line 752 of file Frame.h.
 {}
Member Function Documentation
template<typename PointType> virtual Ptr<Frame> Voxel::PointCloudFrameTemplate< PointType >::copy () const inline virtual
Implements Voxel::Frame.
Definition at line 680 of file Frame.h.
References Voxel::PointCloudFrameTemplate< PointType >::copyTo().
   {
     Ptr<Frame> f(new PointCloudFrameTemplate<PointType>());
     return copyTo(f);
   }
template<typename PointType> virtual Ptr<Frame> Voxel::PointCloudFrameTemplate< PointType >::copyTo (Ptr< Frame > & other) const inline virtual
Implements Voxel::Frame.
Definition at line 686 of file Frame.h.
References Voxel::Frame::id, Voxel::PointCloudFrameTemplate< PointType >::isSameType(), Voxel::PointCloudFrameTemplate< PointType >::points, and Voxel::Frame::timestamp.
Referenced by Voxel::PointCloudFrameTemplate< PointType >::copy().
   {
     if(!other || !isSameType(*other))
       other = Ptr<Frame>(new PointCloudFrameTemplate<PointType>());
     auto *p = dynamic_cast<PointCloudFrameTemplate<PointType> *>(other.get());
     p->id = id;
     p->timestamp = timestamp;
     p->points = points;
     return other;
   }
template<typename PointType> virtual bool Voxel::PointCloudFrameTemplate< PointType >::deserialize (SerializedObject & object) inline virtual
Implements Voxel::Frame.
Definition at line 733 of file Frame.h.
References Voxel::PointCloudFrameTemplate< PointType >::points, and Voxel::Frame::timestamp.
   {
     object.get((char *)&id, sizeof(id));
     object.get((char *)&timestamp, sizeof(timestamp));
     size_t s;
     object.get((char *)&s, sizeof(s));
     points.resize(s);
     object.get((char *)points.data(), sizeof(ByteType)*points.size());
     return true;
   }
template<typename PointType> virtual bool Voxel::PointCloudFrameTemplate< PointType >::isSameSize (const Frame & other) const inline virtual
Implements Voxel::Frame.
Definition at line 711 of file Frame.h.
References Voxel::PointCloudFrameTemplate< PointType >::size().
   {
     const PointCloudFrameTemplate<PointType> *f = dynamic_cast<const PointCloudFrameTemplate<PointType> *>(&other);
     return f && f->size() == size();
   }
template<typename PointType> virtual bool Voxel::PointCloudFrameTemplate< PointType >::isSameType (const Frame & other) const inline virtual
Implements Voxel::Frame.
Definition at line 705 of file Frame.h.
Referenced by Voxel::PointCloudFrameTemplate< PointType >::copyTo().
   {
     const PointCloudFrameTemplate<PointType> *f = dynamic_cast<const PointCloudFrameTemplate<PointType> *>(&other);
     return f;
   }
template<typename PointType> virtual Ptr<Frame> Voxel::PointCloudFrameTemplate< PointType >::newFrame () const inline virtual
Implements Voxel::Frame.
Definition at line 698 of file Frame.h.
References Voxel::PointCloudFrameTemplate< PointType >::points.
   {
     PointCloudFrameTemplate<PointType> *p = new PointCloudFrameTemplate<PointType>();
     p->points.resize(points.size());
     return FramePtr(p);
   }
template<typename PointType> virtual Point* Voxel::PointCloudFrameTemplate< PointType >::operator[] (IndexType index) inline virtual
Implements Voxel::PointCloudFrame.
Definition at line 672 of file Frame.h.
References Voxel::PointCloudFrameTemplate< PointType >::points.
   {
     if(index < points.size() && index >= 0)
       return &points[index];
     else
       return 0;
   }
template<typename PointType> virtual bool Voxel::PointCloudFrameTemplate< PointType >::serialize (SerializedObject & object) const inline virtual
Implements Voxel::Frame.
Definition at line 717 of file Frame.h.
References Voxel::Frame::id, Voxel::PointCloudFrameTemplate< PointType >::points, and Voxel::Frame::timestamp.
   {
     size_t s = sizeof(id) + sizeof(timestamp) + points.size()*sizeof(PointType) + sizeof(size_t);
     object.resize(s);
     object.put((const char *)&id, sizeof(id));
     object.put((const char *)&timestamp, sizeof(timestamp));
     s = points.size();
     object.put((const char *)&s, sizeof(s));
     object.put((const char *)points.data(), sizeof(PointType)*points.size());
     return true;
   }
template<typename PointType> virtual SizeType Voxel::PointCloudFrameTemplate< PointType >::size () const inline virtual
Implements Voxel::PointCloudFrame.
Definition at line 667 of file Frame.h.
References Voxel::PointCloudFrameTemplate< PointType >::points.
Referenced by Voxel::PointCloudFrameTemplate< PointType >::isSameSize().
   {
     return points.size();
   }
template<typename PointType> static Ptr<PointCloudFrameTemplate<PointType> > Voxel::PointCloudFrameTemplate< PointType >::typeCast (FramePtr ptr) inline static
Definition at line 747 of file Frame.h.
   {
     return std::dynamic_pointer_cast<PointCloudFrameTemplate<PointType>>(ptr);
   }
Member Data Documentation
template<typename PointType> Vector<PointType> Voxel::PointCloudFrameTemplate< PointType >::points
Definition at line 665 of file Frame.h.
Referenced by Voxel::PCLGrabber::_callback(), Voxel::CLIManager::_save(), Voxel::PointCloudFrameTemplate< PointType >::copyTo(), Voxel::PointCloudFrameTemplate< PointType >::deserialize(), Voxel::PointCloudFrameGenerator::generate(), Voxel::PointCloudFrameTemplate< PointType >::newFrame(), Voxel::PointCloudFrameTemplate< PointType >::operator[](), Voxel::PointCloudFrameTemplate< PointType >::serialize(), and Voxel::PointCloudFrameTemplate< PointType >::size().
The documentation for this class was generated from the following file:
Frame.h