Voxel: TinyXML2::XMLAttribute Class Reference
TinyXML2::XMLAttribute Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
const char * Name () const
The name of the attribute.
const char * Value () const
The value of the attribute.
const XMLAttribute * Next () const
The next attribute in the list.
int IntValue () const
unsigned UnsignedValue () const
Query as an unsigned integer. See IntValue()
bool BoolValue () const
Query as a boolean. See IntValue()
double DoubleValue () const
Query as a double. See IntValue()
float FloatValue () const
Query as a float. See IntValue()
XMLError QueryIntValue (int *value) const
XMLError QueryUnsignedValue (unsigned int *value) const
See QueryIntValue.
XMLError QueryBoolValue (bool *value) const
See QueryIntValue.
XMLError QueryDoubleValue (double *value) const
See QueryIntValue.
XMLError QueryFloatValue (float *value) const
See QueryIntValue.
void SetAttribute (const char *value)
Set the attribute to a string value.
void SetAttribute (int value)
Set the attribute to value.
void SetAttribute (unsigned value)
Set the attribute to value.
void SetAttribute (bool value)
Set the attribute to value.
void SetAttribute (double value)
Set the attribute to value.
void SetAttribute (float value)
Set the attribute to value.
Private Types
enum { BUF_SIZE = 200 }
Private Member Functions
XMLAttribute ()
virtual ~XMLAttribute ()
XMLAttribute (const XMLAttribute &)
void operator= (const XMLAttribute &)
void SetName (const char *name)
char * ParseDeep (char *p, bool processEntities)
Private Attributes
StrPair _name
StrPair _value
XMLAttribute * _next
MemPool * _memPool
Friends
class XMLElement
Detailed Description
An attribute is a name-value pair. Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not XMLNodes. You may only query the Next() attribute in a list.
Definition at line 1065 of file TinyXML2.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
BUF_SIZE
Definition at line 1142 of file TinyXML2.h.
 { BUF_SIZE = 200 };
Constructor & Destructor Documentation
TinyXML2::XMLAttribute::XMLAttribute () inline private
Definition at line 1144 of file TinyXML2.h.
 : _next( 0 ), _memPool( 0 ) {}
virtual TinyXML2::XMLAttribute::~XMLAttribute () inline private virtual
Definition at line 1145 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::DeleteAttribute().
 {}
TinyXML2::XMLAttribute::XMLAttribute (const XMLAttribute &) private
Member Function Documentation
bool TinyXML2::XMLAttribute::BoolValue () const inline
Query as a boolean. See IntValue()
Definition at line 1096 of file TinyXML2.h.
{
         bool b=false;
         QueryBoolValue( &b );
         return b;
     }
double TinyXML2::XMLAttribute::DoubleValue () const inline
Query as a double. See IntValue()
Definition at line 1102 of file TinyXML2.h.
{
         double d=0;
         QueryDoubleValue( &d );
         return d;
     }
float TinyXML2::XMLAttribute::FloatValue () const inline
Query as a float. See IntValue()
Definition at line 1108 of file TinyXML2.h.
{
         float f=0;
         QueryFloatValue( &f );
         return f;
     }
int TinyXML2::XMLAttribute::IntValue () const inline
IntValue interprets the attribute as an integer, and returns the value. If the value isn't an integer, 0 will be returned. There is no error checking; use QueryIntValue() if you need error checking.
Definition at line 1084 of file TinyXML2.h.
{
         int i=0;
         QueryIntValue( &i );
         return i;
     }
const char * TinyXML2::XMLAttribute::Name () const
The name of the attribute.
Definition at line 1118 of file TinyXML2.cpp.
References _name, and TinyXML2::StrPair::GetStr().
Referenced by TinyXML2::XMLElement::ParseAttributes(), and TinyXML2::XMLPrinter::VisitEnter().
 {
     return _name.GetStr();
 }
const XMLAttribute* TinyXML2::XMLAttribute::Next () const inline
The next attribute in the list.
Definition at line 1076 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::ShallowClone(), TinyXML2::XMLElement::ShallowEqual(), and TinyXML2::XMLPrinter::VisitEnter().
{
         return _next;
     }
void TinyXML2::XMLAttribute::operator= (const XMLAttribute &) private
char * TinyXML2::XMLAttribute::ParseDeep (char * p, bool processEntities) private
Definition at line 1128 of file TinyXML2.cpp.
References _name, _value, TinyXML2::StrPair::ATTRIBUTE_VALUE, TinyXML2::StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES, TinyXML2::StrPair::ParseName(), TinyXML2::StrPair::ParseText(), and TinyXML2::XMLUtil::SkipWhiteSpace().
Referenced by TinyXML2::XMLElement::ParseAttributes().
 {
     // Parse using the name rules: bug fix, was using ParseText before
     p = _name.ParseName( p );
     if ( !p || !*p ) {
         return 0;
     }
     // Skip white space before =
     p = XMLUtil::SkipWhiteSpace( p );
     if ( !p || *p != '=' ) {
         return 0;
     }
     ++p;  // move up to opening quote
     p = XMLUtil::SkipWhiteSpace( p );
     if ( *p != '\"' && *p != '\'' ) {
         return 0;
     }
     char endTag[2] = { *p, 0 };
     ++p;  // move past opening quote
     p = _value.ParseText( p, endTag, processEntities ? StrPair::ATTRIBUTE_VALUE : StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES );
     return p;
 }
XMLError TinyXML2::XMLAttribute::QueryBoolValue (bool * value) const
See QueryIntValue.
Definition at line 1180 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::ToBool(), Value(), TinyXML2::XML_NO_ERROR, and TinyXML2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by TinyXML2::XMLElement::QueryBoolAttribute().
 {
     if ( XMLUtil::ToBool( Value(), value )) {
         return XML_NO_ERROR;
     }
     return XML_WRONG_ATTRIBUTE_TYPE;
 }
XMLError TinyXML2::XMLAttribute::QueryDoubleValue (double * value) const
See QueryIntValue.
Definition at line 1198 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::ToDouble(), Value(), TinyXML2::XML_NO_ERROR, and TinyXML2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by TinyXML2::XMLElement::QueryDoubleAttribute().
 {
     if ( XMLUtil::ToDouble( Value(), value )) {
         return XML_NO_ERROR;
     }
     return XML_WRONG_ATTRIBUTE_TYPE;
 }
XMLError TinyXML2::XMLAttribute::QueryFloatValue (float * value) const
See QueryIntValue.
Definition at line 1189 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::ToFloat(), Value(), TinyXML2::XML_NO_ERROR, and TinyXML2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by TinyXML2::XMLElement::QueryFloatAttribute().
 {
     if ( XMLUtil::ToFloat( Value(), value )) {
         return XML_NO_ERROR;
     }
     return XML_WRONG_ATTRIBUTE_TYPE;
 }
XMLError TinyXML2::XMLAttribute::QueryIntValue (int * value) const
QueryIntValue interprets the attribute as an integer, and returns the value in the provided parameter. The function will return XML_NO_ERROR on success, and XML_WRONG_ATTRIBUTE_TYPE if the conversion is not successful.
Definition at line 1162 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::ToInt(), Value(), TinyXML2::XML_NO_ERROR, and TinyXML2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by TinyXML2::XMLElement::QueryIntAttribute().
 {
     if ( XMLUtil::ToInt( Value(), value )) {
         return XML_NO_ERROR;
     }
     return XML_WRONG_ATTRIBUTE_TYPE;
 }
XMLError TinyXML2::XMLAttribute::QueryUnsignedValue (unsigned int * value) const
See QueryIntValue.
Definition at line 1171 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::ToUnsigned(), Value(), TinyXML2::XML_NO_ERROR, and TinyXML2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by TinyXML2::XMLElement::QueryUnsignedAttribute().
 {
     if ( XMLUtil::ToUnsigned( Value(), value )) {
         return XML_NO_ERROR;
     }
     return XML_WRONG_ATTRIBUTE_TYPE;
 }
void TinyXML2::XMLAttribute::SetAttribute (const char * value)
Set the attribute to a string value.
Definition at line 1207 of file TinyXML2.cpp.
References _value, and TinyXML2::StrPair::SetStr().
Referenced by TinyXML2::XMLElement::SetAttribute().
 {
     _value.SetStr( v );
 }
void TinyXML2::XMLAttribute::SetAttribute (int value)
Set the attribute to value.
Definition at line 1213 of file TinyXML2.cpp.
References _value, BUF_SIZE, TinyXML2::StrPair::SetStr(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     _value.SetStr( buf );
 }
void TinyXML2::XMLAttribute::SetAttribute (unsigned value)
Set the attribute to value.
Definition at line 1221 of file TinyXML2.cpp.
References _value, BUF_SIZE, TinyXML2::StrPair::SetStr(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     _value.SetStr( buf );
 }
void TinyXML2::XMLAttribute::SetAttribute (bool value)
Set the attribute to value.
Definition at line 1229 of file TinyXML2.cpp.
References _value, BUF_SIZE, TinyXML2::StrPair::SetStr(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     _value.SetStr( buf );
 }
void TinyXML2::XMLAttribute::SetAttribute (double value)
Set the attribute to value.
Definition at line 1236 of file TinyXML2.cpp.
References _value, BUF_SIZE, TinyXML2::StrPair::SetStr(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     _value.SetStr( buf );
 }
void TinyXML2::XMLAttribute::SetAttribute (float value)
Set the attribute to value.
Definition at line 1243 of file TinyXML2.cpp.
References _value, BUF_SIZE, TinyXML2::StrPair::SetStr(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     _value.SetStr( buf );
 }
void TinyXML2::XMLAttribute::SetName (const char * name) private
Definition at line 1156 of file TinyXML2.cpp.
References _name, and TinyXML2::StrPair::SetStr().
Referenced by TinyXML2::XMLElement::FindOrCreateAttribute().
 {
     _name.SetStr( n );
 }
unsigned TinyXML2::XMLAttribute::UnsignedValue () const inline
Query as an unsigned integer. See IntValue()
Definition at line 1090 of file TinyXML2.h.
{
         unsigned i=0;
         QueryUnsignedValue( &i );
         return i;
     }
const char * TinyXML2::XMLAttribute::Value () const
The value of the attribute.
Definition at line 1123 of file TinyXML2.cpp.
References _value, and TinyXML2::StrPair::GetStr().
Referenced by TinyXML2::XMLElement::Attribute(), QueryBoolValue(), QueryDoubleValue(), QueryFloatValue(), QueryIntValue(), QueryUnsignedValue(), TinyXML2::XMLElement::ShallowEqual(), and TinyXML2::XMLPrinter::VisitEnter().
 {
     return _value.GetStr();
 }
Friends And Related Function Documentation
friend class XMLElement friend
Definition at line 1067 of file TinyXML2.h.
Member Data Documentation
MemPool* TinyXML2::XMLAttribute::_memPool private
Definition at line 1156 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::DeleteAttribute(), TinyXML2::XMLElement::FindOrCreateAttribute(), and TinyXML2::XMLElement::ParseAttributes().
StrPair TinyXML2::XMLAttribute::_name mutable private
Definition at line 1153 of file TinyXML2.h.
Referenced by Name(), ParseDeep(), and SetName().
XMLAttribute* TinyXML2::XMLAttribute::_next private
Definition at line 1155 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::DeleteAttribute(), TinyXML2::XMLElement::FindAttribute(), TinyXML2::XMLElement::FindOrCreateAttribute(), TinyXML2::XMLElement::ParseAttributes(), and TinyXML2::XMLElement::~XMLElement().
StrPair TinyXML2::XMLAttribute::_value mutable private
Definition at line 1154 of file TinyXML2.h.
Referenced by ParseDeep(), SetAttribute(), and Value().
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp