Voxel: TinyXML2::StrPair Class Reference
TinyXML2::StrPair Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Types
enum {
NEEDS_ENTITY_PROCESSING = 0x01, NEEDS_NEWLINE_NORMALIZATION = 0x02, COLLAPSE_WHITESPACE = 0x04, TEXT_ELEMENT = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
TEXT_ELEMENT_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_NAME = 0, ATTRIBUTE_VALUE = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION, ATTRIBUTE_VALUE_LEAVE_ENTITIES = NEEDS_NEWLINE_NORMALIZATION,
COMMENT = NEEDS_NEWLINE_NORMALIZATION
}
Public Member Functions
StrPair ()
~StrPair ()
void Set (char *start, char *end, int flags)
const char * GetStr ()
bool Empty () const
void SetInternedStr (const char *str)
void SetStr (const char *str, int flags=0)
char * ParseText (char *in, const char *endTag, int strFlags)
char * ParseName (char *in)
void TransferTo (StrPair *other)
Private Types
enum { NEEDS_FLUSH = 0x100, NEEDS_DELETE = 0x200 }
Private Member Functions
void Reset ()
void CollapseWhitespace ()
StrPair (const StrPair &other)
void operator= (StrPair &other)
Private Attributes
int _flags
char * _start
char * _end
Detailed Description
Definition at line 162 of file TinyXML2.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NEEDS_ENTITY_PROCESSING
NEEDS_NEWLINE_NORMALIZATION
COLLAPSE_WHITESPACE
TEXT_ELEMENT
TEXT_ELEMENT_LEAVE_ENTITIES
ATTRIBUTE_NAME
ATTRIBUTE_VALUE
ATTRIBUTE_VALUE_LEAVE_ENTITIES
COMMENT
Definition at line 165 of file TinyXML2.h.
          {
         NEEDS_ENTITY_PROCESSING     = 0x01,
         NEEDS_NEWLINE_NORMALIZATION   = 0x02,
         COLLAPSE_WHITESPACE                 = 0x04,
         TEXT_ELEMENT                  = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
         TEXT_ELEMENT_LEAVE_ENTITIES   = NEEDS_NEWLINE_NORMALIZATION,
         ATTRIBUTE_NAME                  = 0,
         ATTRIBUTE_VALUE                 = NEEDS_ENTITY_PROCESSING | NEEDS_NEWLINE_NORMALIZATION,
         ATTRIBUTE_VALUE_LEAVE_ENTITIES    = NEEDS_NEWLINE_NORMALIZATION,
         COMMENT               = NEEDS_NEWLINE_NORMALIZATION
     };
anonymous enum private
Enumerator
NEEDS_FLUSH
NEEDS_DELETE
Definition at line 210 of file TinyXML2.h.
          {
         NEEDS_FLUSH = 0x100,
         NEEDS_DELETE = 0x200
     };
Constructor & Destructor Documentation
TinyXML2::StrPair::StrPair () inline
Definition at line 178 of file TinyXML2.h.
 : _flags( 0 ), _start( 0 ), _end( 0 ) {}
TinyXML2::StrPair::~StrPair ()
Definition at line 72 of file TinyXML2.cpp.
References Reset().
 {
     Reset();
 }
TinyXML2::StrPair::StrPair (const StrPair & other) private
Member Function Documentation
void TinyXML2::StrPair::CollapseWhitespace () private
Definition at line 163 of file TinyXML2.cpp.
References _flags, _start, TinyXML2::XMLUtil::IsWhiteSpace(), NEEDS_DELETE, TinyXML2::XMLUtil::SkipWhiteSpace(), and TIXMLASSERT.
Referenced by GetStr().
 {
     // Adjusting _start would cause undefined behavior on delete[]
     TIXMLASSERT( ( _flags & NEEDS_DELETE ) == 0 );
     // Trim leading space.
     _start = XMLUtil::SkipWhiteSpace( _start );
     if ( _start && *_start ) {
         char* p = _start; // the read pointer
         char* q = _start; // the write pointer
         while( *p ) {
             if ( XMLUtil::IsWhiteSpace( *p )) {
                 p = XMLUtil::SkipWhiteSpace( p );
                 if ( *p == 0 ) {
                     break;    // don't write to q; this trims the trailing space.
                 }
                 *q = ' ';
                 ++q;
             }
             *q = *p;
             ++q;
             ++p;
         }
         *q = 0;
     }
 }
bool TinyXML2::StrPair::Empty () const inline
Definition at line 190 of file TinyXML2.h.
References _end, and _start.
Referenced by TinyXML2::XMLNode::ParseDeep(), and TinyXML2::XMLElement::ParseDeep().
{
         return _start == _end;
     }
const char * TinyXML2::StrPair::GetStr ()
Definition at line 192 of file TinyXML2.cpp.
References _end, _flags, _start, COLLAPSE_WHITESPACE, CollapseWhitespace(), TinyXML2::XMLUtil::GetCharacterRef(), TinyXML2::Entity::length, NEEDS_DELETE, NEEDS_ENTITY_PROCESSING, NEEDS_FLUSH, NEEDS_NEWLINE_NORMALIZATION, TinyXML2::Entity::pattern, TIXMLASSERT, and TinyXML2::Entity::value.
Referenced by TinyXML2::XMLAttribute::Name(), TinyXML2::XMLNode::ParseDeep(), TinyXML2::XMLNode::Value(), and TinyXML2::XMLAttribute::Value().
 {
     if ( _flags & NEEDS_FLUSH ) {
         *_end = 0;
         _flags ^= NEEDS_FLUSH;
         if ( _flags ) {
             char* p = _start; // the read pointer
             char* q = _start; // the write pointer
             while( p < _end ) {
                 if ( (_flags & NEEDS_NEWLINE_NORMALIZATION) && *p == CR ) {
                     // CR-LF pair becomes LF
                     // CR alone becomes LF
                     // LF-CR becomes LF
                     if ( *(p+1) == LF ) {
                         p += 2;
                     }
                     else {
                         ++p;
                     }
                     *q++ = LF;
                 }
                 else if ( (_flags & NEEDS_NEWLINE_NORMALIZATION) && *p == LF ) {
                     if ( *(p+1) == CR ) {
                         p += 2;
                     }
                     else {
                         ++p;
                     }
                     *q++ = LF;
                 }
                 else if ( (_flags & NEEDS_ENTITY_PROCESSING) && *p == '&' ) {
                     // Entities handled by tinyXML2:
                     // - special entities in the entity table [in/out]
                     // - numeric character reference [in]
                     //   &#20013; or &#x4e2d;
                     if ( *(p+1) == '#' ) {
                         const int buflen = 10;
                         char buf[buflen] = { 0 };
                         int len = 0;
                         p = const_cast<char*>( XMLUtil::GetCharacterRef( p, buf, &len ) );
                         TIXMLASSERT( 0 <= len && len <= buflen );
                         TIXMLASSERT( q + len <= p );
                         memcpy( q, buf, len );
                         q += len;
                     }
                     else {
                         int i=0;
                         for(; i<NUM_ENTITIES; ++i ) {
                             const Entity& entity = entities[i];
                             if ( strncmp( p + 1, entity.pattern, entity.length ) == 0
                                     && *( p + entity.length + 1 ) == ';' ) {
                                 // Found an entity - convert.
                                 *q = entity.value;
                                 ++q;
                                 p += entity.length + 2;
                                 break;
                             }
                         }
                         if ( i == NUM_ENTITIES ) {
                             // fixme: treat as error?
                             ++p;
                             ++q;
                         }
                     }
                 }
                 else {
                     *q = *p;
                     ++p;
                     ++q;
                 }
             }
             *q = 0;
         }
         // The loop below has plenty going on, and this
         // is a less useful mode. Break it out.
         if ( _flags & COLLAPSE_WHITESPACE ) {
             CollapseWhitespace();
         }
         _flags = (_flags & NEEDS_DELETE);
     }
     return _start;
 }
void TinyXML2::StrPair::operator= (StrPair & other) private
char * TinyXML2::StrPair::ParseName (char * in)
Definition at line 143 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::IsNameChar(), TinyXML2::XMLUtil::IsNameStartChar(), and Set().
Referenced by TinyXML2::XMLAttribute::ParseDeep(), and TinyXML2::XMLElement::ParseDeep().
 {
     if ( !p || !(*p) ) {
         return 0;
     }
     char* const start = p;
     while( *p && ( p == start ? XMLUtil::IsNameStartChar( *p ) : XMLUtil::IsNameChar( *p ) )) {
         ++p;
     }
     if ( p > start ) {
         Set( start, p, 0 );
         return p;
     }
     return 0;
 }
char * TinyXML2::StrPair::ParseText (char * in, const char * endTag, int strFlags)
Definition at line 123 of file TinyXML2.cpp.
References Set(), and TIXMLASSERT.
Referenced by TinyXML2::XMLText::ParseDeep(), TinyXML2::XMLComment::ParseDeep(), TinyXML2::XMLDeclaration::ParseDeep(), TinyXML2::XMLUnknown::ParseDeep(), and TinyXML2::XMLAttribute::ParseDeep().
 {
     TIXMLASSERT( endTag && *endTag );
     char* start = p;
     char  endChar = *endTag;
     size_t length = strlen( endTag );
     // Inner loop of text parsing.
     while ( *p ) {
         if ( *p == endChar && strncmp( p, endTag, length ) == 0 ) {
             Set( start, p, strFlags );
             return p + length;
         }
         ++p;
     }
     return 0;
 }
void TinyXML2::StrPair::Reset () private
Definition at line 101 of file TinyXML2.cpp.
References _end, _flags, _start, and NEEDS_DELETE.
Referenced by Set(), SetInternedStr(), SetStr(), TransferTo(), and ~StrPair().
 {
     if ( _flags & NEEDS_DELETE ) {
         delete [] _start;
     }
     _flags = 0;
     _start = 0;
     _end = 0;
 }
void TinyXML2::StrPair::Set (char * start, char * end, int flags) inline
Definition at line 181 of file TinyXML2.h.
References _end, _flags, _start, NEEDS_FLUSH, and Reset().
Referenced by ParseName(), and ParseText().
{
         Reset();
         _start  = start;
         _end    = end;
         _flags  = flags | NEEDS_FLUSH;
     }
void TinyXML2::StrPair::SetInternedStr (const char * str) inline
Definition at line 194 of file TinyXML2.h.
References _start, and Reset().
Referenced by TinyXML2::XMLNode::SetValue().
{
         Reset();
         _start = const_cast<char*>(str);
     }
void TinyXML2::StrPair::SetStr (const char * str, int flags = 0)
Definition at line 112 of file TinyXML2.cpp.
References _end, _flags, _start, NEEDS_DELETE, and Reset().
Referenced by TinyXML2::XMLAttribute::SetAttribute(), TinyXML2::XMLAttribute::SetName(), and TinyXML2::XMLNode::SetValue().
 {
     Reset();
     size_t len = strlen( str );
     _start = new char[ len+1 ];
     memcpy( _start, str, len+1 );
     _end = _start + len;
     _flags = flags | NEEDS_DELETE;
 }
void TinyXML2::StrPair::TransferTo (StrPair * other)
Definition at line 78 of file TinyXML2.cpp.
References _end, _flags, _start, Reset(), and TIXMLASSERT.
Referenced by TinyXML2::XMLNode::ParseDeep().
 {
     if ( this == other ) {
         return;
     }
     // This in effect implements the assignment operator by "moving"
     // ownership (as in auto_ptr).
     TIXMLASSERT( other->_flags == 0 );
     TIXMLASSERT( other->_start == 0 );
     TIXMLASSERT( other->_end == 0 );
     other->Reset();
     other->_flags = _flags;
     other->_start = _start;
     other->_end = _end;
     _flags = 0;
     _start = 0;
     _end = 0;
 }
Member Data Documentation
char* TinyXML2::StrPair::_end private
Definition at line 218 of file TinyXML2.h.
Referenced by Empty(), GetStr(), Reset(), Set(), SetStr(), and TransferTo().
int TinyXML2::StrPair::_flags private
Definition at line 216 of file TinyXML2.h.
Referenced by CollapseWhitespace(), GetStr(), Reset(), Set(), SetStr(), and TransferTo().
char* TinyXML2::StrPair::_start private
Definition at line 217 of file TinyXML2.h.
Referenced by CollapseWhitespace(), Empty(), GetStr(), Reset(), Set(), SetInternedStr(), SetStr(), and TransferTo().
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp