Voxel: Voxel::SerializedObject Class Reference
Voxel::SerializedObject Class Reference
#include <SerializedObject.h>
Public Member Functions
SerializedObject (size_t size)
SerializedObject ()
uint currentGetOffset () const
uint currentPutOffset () const
const Vector< char > & getBytes () const
Vector< char > & getBytes ()
void resize (size_t size)
size_t size () const
void rewind ()
size_t get (char *bytes, size_t size)
size_t put (const char *bytes, size_t size)
virtual ~SerializedObject ()
Protected Attributes
Vector< char > _bytes
uint _getOffset
uint _putOffset
Detailed Description
Definition at line 19 of file SerializedObject.h.
Constructor & Destructor Documentation
Voxel::SerializedObject::SerializedObject (size_t size) inline
Definition at line 26 of file SerializedObject.h.
 : _bytes(size), _getOffset(0), _putOffset(0) {}
Voxel::SerializedObject::SerializedObject () inline
Definition at line 27 of file SerializedObject.h.
 : _getOffset(0), _putOffset(0) {}
virtual Voxel::SerializedObject::~SerializedObject () inline virtual
Definition at line 51 of file SerializedObject.h.
 {}
Member Function Documentation
uint Voxel::SerializedObject::currentGetOffset () const inline
Definition at line 29 of file SerializedObject.h.
Referenced by Voxel::Data2DCodec::decompress(), Voxel::DataPacket::read(), Voxel::MainConfigurationFile::readFromHardware(), and Voxel::DataPacket::readHeader().
 { return _getOffset; }
uint Voxel::SerializedObject::currentPutOffset () const inline
Definition at line 30 of file SerializedObject.h.
Referenced by Voxel::Data2DCodec::compress(), and Voxel::DataPacket::write().
 { return _putOffset; }
size_t Voxel::SerializedObject::get (char * bytes, size_t size) inline
Definition at line 54 of file SerializedObject.h.
References _bytes, _getOffset, and size().
Referenced by Voxel::Data2DCodec::decompress(), Voxel::DataPacket::read(), Voxel::MainConfigurationFile::readFromHardware(), and Voxel::DataPacket::readHeader().
 {
   size = std::min(size, _bytes.size() - _getOffset);
   if(size == 0)
     return 0;
   memcpy(bytes, _bytes.data() + _getOffset, size);
   _getOffset += size;
   return size;
 }
const Vector<char>& Voxel::SerializedObject::getBytes () const inline
Definition at line 32 of file SerializedObject.h.
Referenced by Voxel::TI::TintinCDKCamera::_readConfigFromHardware(), Voxel::TI::TintinCDKCamera::_writeConfigFromHardware(), Voxel::Data2DCodec::compress(), Voxel::GeneratorConfigurationSubPacket::read(), Voxel::MainConfigurationFile::readFromHardware(), Voxel::GeneratorConfigurationSubPacket::write(), and Voxel::MainConfigurationFile::writeToHardware().
 { return _bytes; }
Vector<char>& Voxel::SerializedObject::getBytes () inline
Definition at line 33 of file SerializedObject.h.
 { return _bytes; }
size_t Voxel::SerializedObject::put (const char * bytes, size_t size) inline
Definition at line 68 of file SerializedObject.h.
References _bytes, _putOffset, and size().
Referenced by Voxel::ConfigurationFile::_serializeAllDataFiles(), Voxel::Data2DCodec::compress(), Voxel::Data2DCodec::decompress(), Voxel::DataPacket::write(), and Voxel::MainConfigurationFile::writeToHardware().
 {
   size = std::min(size, _bytes.size() - _putOffset);
   if(size == 0)
     return 0;
   memcpy(_bytes.data() + _putOffset, bytes, size);
   _putOffset += size;
   return size;
 }
void Voxel::SerializedObject::resize (size_t size) inline
Definition at line 35 of file SerializedObject.h.
Referenced by Voxel::TI::TintinCDKCamera::_readConfigFromHardware(), Voxel::ConfigurationFile::_serializeAllDataFiles(), Voxel::Data2DCodec::compress(), Voxel::Data2DCodec::decompress(), Voxel::GeneratorConfigurationSubPacket::read(), Voxel::MainConfigurationFile::readFromHardware(), and Voxel::MainConfigurationFile::writeToHardware().
   {
     if(size > 0)
       _bytes.resize(size);
     else
       _bytes.clear();
     rewind();
   }
void Voxel::SerializedObject::rewind () inline
Definition at line 46 of file SerializedObject.h.
 { _getOffset = 0; _putOffset = 0; }
size_t Voxel::SerializedObject::size () const inline
Definition at line 44 of file SerializedObject.h.
Referenced by Voxel::TI::TintinCDKCamera::_readConfigFromHardware(), Voxel::ConfigurationFile::_serializeAllDataFiles(), Voxel::TI::TintinCDKCamera::_writeConfigFromHardware(), get(), put(), Voxel::DataPacket::read(), Voxel::MainConfigurationFile::readFromHardware(), Voxel::DataPacket::readHeader(), Voxel::DataPacket::write(), Voxel::FrameStreamWriter::write(), Voxel::FrameStreamWriter::writeGeneratorConfiguration(), and Voxel::MainConfigurationFile::writeToHardware().
 { return _bytes.size(); }
Member Data Documentation
Vector<char> Voxel::SerializedObject::_bytes protected
Definition at line 22 of file SerializedObject.h.
Referenced by get(), and put().
uint Voxel::SerializedObject::_getOffset protected
Definition at line 23 of file SerializedObject.h.
Referenced by get().
uint Voxel::SerializedObject::_putOffset protected
Definition at line 23 of file SerializedObject.h.
Referenced by put().
The documentation for this class was generated from the following file:
SerializedObject.h