Voxel: Voxel::TI::TintinEEPROMDownloader Class Reference
Voxel::TI::TintinEEPROMDownloader Class Reference
#include <TintinEEPROMDownloader.h>
Public Member Functions
TintinEEPROMDownloader (DevicePtr device)
virtual ~TintinEEPROMDownloader ()
Public Member Functions inherited from Voxel::USBDownloader
USBDownloader (DevicePtr device)
virtual bool download (const String &file)
virtual ~USBDownloader ()
Public Member Functions inherited from Voxel::Downloader
Downloader (DevicePtr device)
void setLogCallback (LoggerOutStream::LoggerOutStreamFunctionType f)
void removeLogCallback ()
void setProgressFunction (ProgressFunctionType f)
void removeProgressFunction ()
float getProgress ()
virtual ~Downloader ()
Protected Member Functions
virtual bool _configureForDownload ()
virtual bool _download (InputFileStream &file, long unsigned int filesize)
bool _printEEPROMFirst64Bytes ()
bool _getEEPROMStatus (uint8_t &eepromStatus)
Protected Member Functions inherited from Voxel::Downloader
virtual bool _locateFile (String &file)
void _setProgress (float progress)
void _setProgressIncrement (float progress)
Additional Inherited Members
Public Types inherited from Voxel::Downloader
typedef Function< void(float)> ProgressFunctionType
Protected Attributes inherited from Voxel::USBDownloader
USBIOPtr _usbIO
Protected Attributes inherited from Voxel::Downloader
DevicePtr _device
LoggerOutStream _outStream
ProgressFunctionType _progressFunction
float _progress = 0
Detailed Description
Definition at line 18 of file TintinEEPROMDownloader.h.
Constructor & Destructor Documentation
Voxel::TI::TintinEEPROMDownloader::TintinEEPROMDownloader (DevicePtr device) inline
Definition at line 29 of file TintinEEPROMDownloader.h.
 : USBDownloader(device) {}
virtual Voxel::TI::TintinEEPROMDownloader::~TintinEEPROMDownloader () inline virtual
Definition at line 30 of file TintinEEPROMDownloader.h.
 {}
Member Function Documentation
bool Voxel::TI::TintinEEPROMDownloader::_configureForDownload () protected virtual
Reimplemented from Voxel::USBDownloader.
Definition at line 37 of file TintinEEPROMDownloader.cpp.
References Voxel::Downloader::_device, _getEEPROMStatus(), Voxel::Downloader::_outStream, _printEEPROMFirst64Bytes(), Voxel::Downloader::_setProgress(), Voxel::USBDownloader::_usbIO, Voxel::USBIO::FROM_DEVICE, Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::USBDevice::productID(), Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, Voxel::TI::VoxelXUProgrammer::reset(), TINTIN_CDK_PRODUCT_BULK, TINTIN_CDK_PRODUCT_UVC, TINTIN_CDK_VENDOR_ID, and Voxel::USBIO::TO_DEVICE.
 {
   // Perform reset
   USBDevice &d = (USBDevice &)*_device;
   DevicePtr controlDevice;
   if (d.productID() == TINTIN_CDK_PRODUCT_UVC)
   {
     logger(LOG_INFO) << "TintinEEPROMDownloader: Reseting device..." << std::endl;
     _outStream << "Reseting device..." << std::endl;
     VoxelXUProgrammer p({}, _device);
     p.reset();
     // Wait for 10 seconds
     logger(LOG_INFO) << "TintinEEPROMDownloader: Waiting for device reenumeration..." << std::endl;
     _outStream << "Waiting for device reenumeration..." << std::endl;
     std::this_thread::sleep_for(std::chrono::seconds(10));
     controlDevice = DevicePtr(new USBDevice(TINTIN_CDK_VENDOR_ID, TINTIN_CDK_PRODUCT_BULK, _device->serialNumber(),
                                             _device->channelID(), _device->description(), _device->serialIndex(), true));
   } else {
     controlDevice = _device;
   }
   _setProgress(10);
   _usbIO.reset(); // Remove reference to USBIO structure
   _usbIO = USBIOPtr(new USBIO(controlDevice));
   if(!_usbIO->isInitialized())
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Could not open device" << std::endl;
     _outStream << "Could not open device" << std::endl;
     return false;
   }
   uint16_t length;
   // Write init
   uint8_t writeInit[] = { 0x06 };
   length = 1;
   if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       0x17, 0x00, 0x00, writeInit, length))
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to init write in EEPROM" << std::endl;
     _outStream << "Failed to init write in EEPROM" << std::endl;
     return false;
   }
   // JEDEC ID
   uint8_t jedecID[3];
   length = 3;
   if(!_usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       0x1D, 0x00, 0x00, jedecID, length))
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to read JEDEC ID" << std::endl;
     _outStream << "Failed to read JEDEC ID" << std::endl;
     return false;
   }
   logger(LOG_INFO) << "TintinEEPROMDownloader: EEPROM JEDEC ID = " << std::hex << "0x" << (uint)jedecID[0] << (uint)jedecID[1] << (uint)jedecID[2] << std::endl;
   _outStream << "EEPROM JEDEC ID = " << std::hex << "0x" << (uint)jedecID[0] << (uint)jedecID[1] << (uint)jedecID[2] << std::endl;;
   uint8_t eepromStatus;
   if(!_getEEPROMStatus(eepromStatus))
     return false;
   logger(LOG_INFO) << "TintinEEPROMDownloader: EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   _outStream << "EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   if(!_printEEPROMFirst64Bytes())
     return false;
   // Write enable
   length = 1;
   if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
     0x1E, 0x00, 0x00, writeInit, length))
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to enable write" << std::endl;
     _outStream << "Failed to enable write" << std::endl;
     return false;
   }
   if(!_getEEPROMStatus(eepromStatus))
     return false;
   logger(LOG_INFO) << "TintinEEPROMDownloader: Write enable, EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   _outStream << "Write enable, EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   // EEPROM Erase
   uint8_t eepromEraseCommand[] = {0xC7};
   length = 1;
   if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
     0x1E, 0x00, 0x00, eepromEraseCommand, length))
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to erase EEPROM" << std::endl;
     _outStream << "Failed to erase EEPROM" << std::endl;
     return false;
   }
   if(!_getEEPROMStatus(eepromStatus))
     return false;
   logger(LOG_INFO) << "TintinEEPROMDownloader: Erase, EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   _outStream << "Erase, EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   _setProgress(15);
   // Wait for 30 seconds
   logger(LOG_INFO) << "TintinEEPROMDownloader: Waiting for erase..." << std::endl;
   _outStream << "Waiting for erase..." << std::endl;
   std::this_thread::sleep_for(std::chrono::seconds(30));
   if(!_getEEPROMStatus(eepromStatus))
     return false;
   logger(LOG_INFO) << "TintinEEPROMDownloader: Erase done, EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   _outStream << "Erase done, EEPROM Status = " << std::hex << "0x" << (uint)eepromStatus << std::endl;
   if(!_printEEPROMFirst64Bytes())
     return false;
   _setProgress(40);
   return true;
 }
bool Voxel::TI::TintinEEPROMDownloader::_download (InputFileStream & file, long unsigned int filesize) protected virtual
Reimplemented from Voxel::USBDownloader.
Definition at line 211 of file TintinEEPROMDownloader.cpp.
References Voxel::Downloader::_outStream, _printEEPROMFirst64Bytes(), Voxel::Downloader::_setProgress(), Voxel::USBDownloader::_usbIO, Voxel::TI::bitReverseTable, Voxel::Downloader::getProgress(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, and Voxel::USBIO::TO_DEVICE.
 {
   logger(LOG_INFO) << "TintinEEPROMDownloader: Starting EEPROM write..." << std::endl;
  _outStream << "Starting EEPROM write..." << std::endl;
   Vector<uint8_t> data(filesize), dataReverse;
   dataReverse.reserve(filesize);
   file.read((char *)data.data(), filesize);
   // bit-reverse all the bytes
   for(auto d: data)
     dataReverse.push_back(bitReverseTable[d]);
   uint32_t stepSize = 64, startAddress = 0, bytesRemaining = filesize, i = 0, bytesToSend;
   float p = getProgress();
   while(bytesRemaining)
   {
     if(bytesRemaining > stepSize)
       bytesToSend = stepSize;
     else
       bytesToSend = bytesRemaining;
     // Write enable
     uint8_t writeInit[] = { 0x06 };
     uint16_t length = 1;
     if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       0x1E, 0x00, 0x00, writeInit, length))
     {
       logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to enable write" << std::endl;
       _outStream << "Failed to enable write" << std::endl;
       return false;
     }
     length = bytesToSend;
     if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       0x18, startAddress & 0xFFFF, (startAddress >> 16) & 0x00FF, dataReverse.data() + startAddress, length))
     {
       logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to write bytes at address 0x" << std::hex << startAddress << std::endl;
       _outStream << "Failed to write bytes at address 0x" << std::hex << startAddress << std::endl;
       return false;
     }
     if(i % 8192 == 0)
     {
       logger(LOG_INFO) << "TintinEEPROMDownloader: Pending " << std::dec << bytesRemaining << " bytes..." << std::endl;
       _outStream << "Pending " << std::dec << bytesRemaining << " bytes..." << std::endl;
     }
     bytesRemaining -= bytesToSend;
     startAddress += bytesToSend;
     i++;
     _setProgress(p + (100 - p)*(startAddress*1.0/filesize));
   }
   logger(LOG_INFO) << "TintinEEPROMDownloader: EEPROM writes finished..." << std::endl;
   _outStream << "EEPROM writes finished..." << std::endl;
   if(!_printEEPROMFirst64Bytes())
     return false;
   logger(LOG_INFO) << "TintinEEPROMDownloader: Done!" << std::dec << std::endl;
   _outStream << "Done!" << std::dec << std::endl;
   return true;
 }
bool Voxel::TI::TintinEEPROMDownloader::_getEEPROMStatus (uint8_t & eepromStatus) protected
Definition at line 164 of file TintinEEPROMDownloader.cpp.
References Voxel::Downloader::_outStream, Voxel::USBDownloader::_usbIO, Voxel::USBIO::FROM_DEVICE, Voxel::LOG_ERROR, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, and Voxel::USBIO::REQUEST_VENDOR.
Referenced by _configureForDownload().
 {
   uint16_t length;
   // EEPROM status
   uint8_t eepromStat[1];
   length = 1;
   if(!_usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
     0x1B, 0x00, 0x00, eepromStat, length))
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to read EEPROM status" << std::endl;
     _outStream << "Failed to read EEPROM status" << std::endl;
     return false;
   }
   eepromStatus = eepromStat[0];
   return true;
 }
bool Voxel::TI::TintinEEPROMDownloader::_printEEPROMFirst64Bytes () protected
Definition at line 183 of file TintinEEPROMDownloader.cpp.
References Voxel::Downloader::_outStream, Voxel::USBDownloader::_usbIO, Voxel::USBIO::FROM_DEVICE, Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, and Voxel::USBIO::REQUEST_VENDOR.
Referenced by _configureForDownload(), and _download().
 {
   uint8_t bytes[64];
   uint16_t length = 64;
   if(!_usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
     0x19, 0x00, 0x00, bytes, length))
   {
     logger(LOG_ERROR) << "TintinEEPROMDownloader: Failed to read EEPROM bytes" << std::endl;
     _outStream << "Failed to read EEPROM bytes" << std::endl;
     return false;
   }
   logger(LOG_INFO) << "First 64 bytes = ";
   _outStream << "First 64 bytes = ";
   for(auto i = 0; i < 64; i++)
   {
     logger << "0x" << std::hex << (uint)bytes[i] << " ";
     _outStream << "0x" << std::hex << (uint)bytes[i] << " ";
   }
   logger << std::endl;
   _outStream << std::endl;
   return true;
 }
The documentation for this class was generated from the following files:
TintinEEPROMDownloader.h
TintinEEPROMDownloader.cpp