Voxel: Voxel::TI::ToFCameraBase Class Reference
Voxel::TI::ToFCameraBase Class Reference abstract
This is a generic ToFCamera which is not strictly dependent on TI's ToF chips.
#include <ToFCameraBase.h>
Public Member Functions
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
virtual bool setSerialNumber (const String &serialNumber)
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (const int id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
virtual bool _initStartParams ()
virtual bool _getAmplitudeNormalizingFactor (float &factor)=0
virtual bool _getDepthScalingFactor (float &factor)=0
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)=0
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
virtual bool _setFrameRate (const FrameRate &r)=0
virtual bool _getFrameRate (FrameRate &r) const =0
virtual bool _setFrameSize (const FrameSize &s)=0
virtual bool _getFrameSize (FrameSize &s) const =0
virtual bool _getMaximumFrameSize (FrameSize &s) const =0
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const =0
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const =0
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const =0
virtual bool _getBytesPerPixel (uint &bpp) const =0
virtual bool _setBytesPerPixel (const uint &bpp)=0
virtual bool _getROI (RegionOfInterest &roi)=0
virtual bool _setROI (const RegionOfInterest &roi)=0
virtual bool _allowedROI (String &message)=0
virtual bool _getFieldOfView (float &fovHalfAngle) const =0
void _makeID ()
virtual bool _reset ()=0
virtual bool _applyConfigParams (const ConfigSet *params)
virtual bool _saveCurrentProfileID (const int id)=0
virtual bool _getCurrentProfileID (int &id)=0
bool _init ()
Protected Attributes
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Detailed Description
This is a generic ToFCamera which is not strictly dependent on TI's ToF chips.
Definition at line 22 of file ToFCameraBase.h.
Constructor & Destructor Documentation
Voxel::TI::ToFCameraBase::ToFCameraBase (const String & name, DevicePtr device) inline
Definition at line 43 of file ToFCameraBase.h.
                                                      : DepthCamera(name, device),
     _tofDepthFrameGenerator(new ToFDepthFrameGenerator())
     {
       _frameGenerators[1] = std::dynamic_pointer_cast<FrameGenerator>(_tofDepthFrameGenerator);
     }
virtual Voxel::TI::ToFCameraBase::~ToFCameraBase () inline virtual
Definition at line 49 of file ToFCameraBase.h.
 {}
Member Function Documentation
bool Voxel::TI::ToFCameraBase::_captureRawUnprocessedFrame (RawFramePtr & rawFrame) protected virtual
Implements Voxel::DepthCamera.
Definition at line 47 of file ToFCameraBase.cpp.
References _rawDataFrame, Voxel::DepthCamera::_streamer, and Voxel::DepthCamera::isInitialized().
 {
   if(!isInitialized() || !_streamer->isRunning())
     return false;
   if(_streamer->capture(_rawDataFrame))
   {
     rawFrame = std::dynamic_pointer_cast<RawFrame>(_rawDataFrame);
     return true;
   }
   return false;
 }
bool Voxel::TI::ToFCameraBase::_convertToDepthFrame (const RawFramePtr & rawFrame, DepthFramePtr & depthFrame) protected virtual
Implements Voxel::DepthCamera.
Definition at line 61 of file ToFCameraBase.cpp.
References _tofDepthFrameGenerator, LensCalibrationTest::p1, and LensCalibrationTest::p2.
 {
   FramePtr p1 = std::dynamic_pointer_cast<Frame>(rawFrame);
   FramePtr p2 = std::dynamic_pointer_cast<Frame>(depthFrame);
   bool ret = _tofDepthFrameGenerator->generate(p1, p2);
   if(ret)
   {
     depthFrame = std::dynamic_pointer_cast<DepthFrame>(p2);
     return true;
   }
   else
     return false;
 }
virtual bool Voxel::TI::ToFCameraBase::_getAmplitudeNormalizingFactor (float & factor) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by _initStartParams().
virtual bool Voxel::TI::ToFCameraBase::_getDepthScalingFactor (float & factor) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by _initStartParams().
bool Voxel::TI::ToFCameraBase::_init () protected
Definition at line 15 of file ToFCameraBase.cpp.
References Voxel::DepthCamera::_init().
Referenced by Voxel::TI::ToFCamera::_init().
 {
   if(!DepthCamera::_init())
     return false;
   return true;
 }
bool Voxel::TI::ToFCameraBase::_initStartParams () protected virtual
Reimplemented in Voxel::TI::ToFCamera, Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, Voxel::TI::TintinCDKCamera, Voxel::TI::HaddockCDKCamera, Voxel::TI::CalculusCDKCamera, Voxel::TI::VoxelDCamera, Voxel::TI::Voxel14Camera, and Voxel::TI::ToFHaddockCamera.
Definition at line 105 of file ToFCameraBase.cpp.
References _getAmplitudeNormalizingFactor(), _getDepthScalingFactor(), _tofDepthFrameGenerator, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::TI::ToFCamera::_initStartParams(), and _start().
 {
   float amplitudeNormalizingFactor, depthScalingFactor;
   if(!_getAmplitudeNormalizingFactor(amplitudeNormalizingFactor) || !_getDepthScalingFactor(depthScalingFactor))
     return false;
   if(!_tofDepthFrameGenerator->setParameters(amplitudeNormalizingFactor, depthScalingFactor))
   {
     logger(LOG_ERROR) << "ToFCameraBase: Could not set parameters to ToFDepthFrameGenerator" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCameraBase::_onReset () protected virtual
Implements Voxel::DepthCamera.
Definition at line 24 of file ToFCameraBase.cpp.
References Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::VideoMode::getFrameRate(), Voxel::DepthCamera::getFrameRate(), Voxel::DepthCamera::getFrameSize(), Voxel::DepthCamera::getMaximumVideoMode(), Voxel::DepthCamera::setFrameRate(), and Voxel::DepthCamera::setFrameSize().
 {
   VideoMode m, m2;
   /* setFrameSize to set the right stream parameters for streamer */
   if(!getMaximumVideoMode(m) || !getFrameSize(m2.frameSize) || !getFrameRate(m2.frameRate) || !setFrameSize(m2.frameSize))
     return false;
   // Just ensure that the frame rate is not out of bounds
   if(m2.getFrameRate() > m.getFrameRate())
   {
     m2.frameRate = m.frameRate;
     if(!setFrameRate(m2.frameRate) || !setFrameSize(m2.frameSize))
       return false;
   }
   return true;
 }
bool Voxel::TI::ToFCameraBase::_start () protected virtual
Implements Voxel::DepthCamera.
Definition at line 78 of file ToFCameraBase.cpp.
References _initStartParams(), Voxel::DepthCamera::_streamer, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::VideoMode::getFrameRate(), Voxel::DepthCamera::getFrameRate(), Voxel::DepthCamera::getFrameSize(), Voxel::FrameSize::height, Voxel::DepthCamera::isInitialized(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, and Voxel::FrameSize::width.
 {
   if(!isInitialized())
     return false;
   VideoMode m;
   if(!getFrameSize(m.frameSize))
   {
     logger(LOG_ERROR) << "ToFCameraBase: Could not get current frame size" << std::endl;
     return false;
   }
   if(!getFrameRate(m.frameRate))
   {
     logger(LOG_ERROR) << "ToFCameraBase: Could not get current frame rate" << std::endl;
   }
   logger(LOG_INFO) << "ToFCameraBase: Starting with " << m.frameSize.width << "x" << m.frameSize.height << "@" << m.getFrameRate() << "fps" << std::endl;
   if(!_initStartParams()) // Initialize parameters to starts streaming
     return false;
   // Start stream
   return _streamer->start();
 }
bool Voxel::TI::ToFCameraBase::_stop () protected virtual
Implements Voxel::DepthCamera.
Definition at line 122 of file ToFCameraBase.cpp.
References Voxel::DepthCamera::_streamer, and Voxel::DepthCamera::isInitialized().
 {
   if(!isInitialized())
     return false;
   return _streamer->stop();
 }
Member Data Documentation
RawDataFramePtr Voxel::TI::ToFCameraBase::_rawDataFrame protected
Definition at line 25 of file ToFCameraBase.h.
Referenced by _captureRawUnprocessedFrame().
Ptr<ToFDepthFrameGenerator> Voxel::TI::ToFCameraBase::_tofDepthFrameGenerator protected
Definition at line 40 of file ToFCameraBase.h.
Referenced by _convertToDepthFrame(), _initStartParams(), and Voxel::TI::ToFCamera::ToFCamera().
The documentation for this class was generated from the following files:
ToFCameraBase.h
ToFCameraBase.cpp