Voxel: Voxel::TI::ToFCamera Class Reference
Voxel::TI::ToFCamera Class Reference abstract
#include <ToFCamera.h>
Public Member Functions
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (const int id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _getFrameSize (FrameSize &s) const
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _setStreamerFrameSize (const FrameSize &s)=0
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getIlluminationFrequency (float &frequency) const =0
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _getSystemClockFrequency (uint &frequency) const =0
virtual bool _isHistogramEnabled () const =0
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _initStartParams ()
virtual bool _applyCalibrationParams ()=0
virtual bool _getCurrentProfileRegisterName (String &name)=0
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
virtual bool _getMaximumFrameSize (FrameSize &s) const =0
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const =0
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const =0
virtual bool _getROI (RegionOfInterest &roi)=0
virtual bool _setROI (const RegionOfInterest &roi)=0
virtual bool _allowedROI (String &message)=0
virtual bool _getFieldOfView (float &fovHalfAngle) const =0
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Protected Attributes
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Friends
class IntegrationTimeParameter
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Detailed Description
Definition at line 99 of file ToFCamera.h.
Constructor & Destructor Documentation
Voxel::TI::ToFCamera::ToFCamera (const String & name, DevicePtr device)
Definition at line 74 of file ToFCamera.cpp.
References Voxel::DepthCamera::_frameGenerators, Voxel::TI::ToFCameraBase::_tofDepthFrameGenerator, and _tofFrameGenerator.
                                                         : ToFCameraBase(name, device),
 _tofFrameGenerator(new ToFFrameGenerator())
 {
   _frameGenerators[0] = std::dynamic_pointer_cast<FrameGenerator>(_tofFrameGenerator);
   _tofDepthFrameGenerator->setProcessedFrameGenerator(_frameGenerators[0]);
 }
virtual Voxel::TI::ToFCamera::~ToFCamera () inline virtual
Definition at line 158 of file ToFCamera.h.
 {}
Member Function Documentation
virtual bool Voxel::TI::ToFCamera::_applyCalibrationParams () protected pure virtual
Implemented in Voxel::TI::ToFCalculusCamera, Voxel::TI::ToFTintinCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by _initStartParams().
bool Voxel::TI::ToFCamera::_getAmplitudeNormalizingFactor (float & factor) protected virtual
Implements Voxel::TI::ToFCameraBase.
Definition at line 340 of file ToFCamera.cpp.
 {
   factor = 1.0/(1 << 12);
   return true;
 }
bool Voxel::TI::ToFCamera::_getBinning (uint & rowsToMerge, uint & columnsToMerge) const protected virtual
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 303 of file ToFCamera.cpp.
References BIN_COLS_TO_MERGE, BIN_ROWS_TO_MERGE, BINNING_EN, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by _initStartParams().
 {
   bool binningEnabled;
   if(!get(BINNING_EN, binningEnabled))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not get binning_en" << std::endl;
     return false;
   }
   if(!binningEnabled)
   {
     rowsToMerge = columnsToMerge = 1;
     return true;
   }
   if(!get(BIN_ROWS_TO_MERGE, rowsToMerge) || !get(BIN_COLS_TO_MERGE, columnsToMerge))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set binning related parameters" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCamera::_getBytesPerPixel (uint & bpp) const protected virtual
Implements Voxel::DepthCamera.
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 261 of file ToFCamera.cpp.
References Voxel::DepthCamera::_get(), Voxel::LOG_ERROR, Voxel::logger, and PIXEL_DATA_SIZE.
Referenced by _getMaximumFrameRate(), _initStartParams(), and _setFrameSize().
 {
   int b;
   if(!_get(PIXEL_DATA_SIZE, b))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   bpp = (uint)b;
   return true;
 }
bool Voxel::TI::ToFCamera::_getCurrentProfileID (int & id) protected virtual
Implements Voxel::DepthCamera.
Definition at line 649 of file ToFCamera.cpp.
References Voxel::DepthCamera::_get(), _getCurrentProfileRegisterName(), and Voxel::DepthCamera::name().
 {
   String name;
   if(!_getCurrentProfileRegisterName(name))
     return false;
   uint i;
   if(_get(name, i, true))
   {
     id = i;
     if(id == 0)
       return false;
     return true;
   }
   return false;
 }
virtual bool Voxel::TI::ToFCamera::_getCurrentProfileRegisterName (String & name) protected pure virtual
Implemented in Voxel::TI::ToFCalculusCamera, Voxel::TI::ToFTintinCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by _getCurrentProfileID(), and _saveCurrentProfileID().
bool Voxel::TI::ToFCamera::_getDepthScalingFactor (float & factor) protected virtual
Implements Voxel::TI::ToFCameraBase.
Definition at line 500 of file ToFCamera.cpp.
References _getIlluminationFrequency(), _is16BitModeEnabled(), CALIB_DISABLE, CALIB_SECT_FREQUENCY, Voxel::DepthCamera::configFile, DEALIAS_EN, DEALIASED_PHASE_MASK, FLOAT_EPSILON, Voxel::ConfigurationFile::getFloat(), Voxel::ConfigurationFile::getInteger(), Voxel::MainConfigurationFile::isPresent(), MA, MB, and SPEED_OF_LIGHT.
 {
   bool dealiasingEnabled;
   if(!get(DEALIAS_EN, dealiasingEnabled))
     return false;
   float illuminationFrequency;
   if(!_getIlluminationFrequency(illuminationFrequency))
     return false;
   bool frequencyCorrectionPresent = false;
   float frequencyCorrection = 1.0f;
   bool frequencyCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_FREQUENCY) == 0;
   if(frequencyCalibEnable && configFile.isPresent("calib", "freq_corr"))
   {
     frequencyCorrection = configFile.getFloat("calib", "freq_corr");
     if(frequencyCorrection < FLOAT_EPSILON)
       frequencyCorrectionPresent = false;
     else
       frequencyCorrectionPresent = true;
   }
   if(dealiasingEnabled)
   {
     bool is16BitMode;
     int dealiasedPhaseMask;
     uint ma, mb;
     if(!_is16BitModeEnabled(is16BitMode) || !get(DEALIASED_PHASE_MASK, dealiasedPhaseMask)
       || !get(MA, ma) || !get(MB, mb))
       return false;
     if(frequencyCorrectionPresent)
       illuminationFrequency *= frequencyCorrection;
     if(is16BitMode)
       factor = SPEED_OF_LIGHT/1E6f/(2*(1 << 16)*illuminationFrequency)*(1 << (5 - dealiasedPhaseMask))*1.0f/ma/mb;
     else
       factor = SPEED_OF_LIGHT/1E6f/(2*(1 << 12)*illuminationFrequency)*(1 << (5 - dealiasedPhaseMask))*1.0f/ma/mb;
     return true;
   }
   else
   {
     if(frequencyCorrectionPresent)
       illuminationFrequency *= frequencyCorrection;
     factor = SPEED_OF_LIGHT/1E6f/2/illuminationFrequency/(1 << 12);
     return true;
   }
 }
bool Voxel::TI::ToFCamera::_getFrameRate (FrameRate & r) const protected virtual
Implements Voxel::DepthCamera.
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 97 of file ToFCamera.cpp.
References Voxel::DepthCamera::_get(), _getSystemClockFrequency(), Voxel::FrameRate::denominator, Voxel::gcd(), Voxel::FrameRate::numerator, PIX_CNT_MAX, PIX_CNT_MAX_SET_FAILED, QUAD_CNT_MAX, and SUBFRAME_CNT_MAX.
Referenced by Voxel::TI::Voxel14Camera::_setStreamerFrameSize(), Voxel::TI::VoxelDCamera::_setStreamerFrameSize(), Voxel::TI::TintinCDKCamera::_setStreamerFrameSize(), Voxel::TI::HaddockUnambiguousRangeParameter::set(), and Voxel::TI::TintinUnambiguousRangeParameter::set().
 {
   bool pixCountSetFailed;
   uint pixCount, sysClkFrequency;
   int quadCount, subFrameCount;
   if(!_get(PIX_CNT_MAX_SET_FAILED, pixCountSetFailed) || pixCountSetFailed)
     return false;
   if(!_get(PIX_CNT_MAX, pixCount) || !_get(QUAD_CNT_MAX, quadCount) || !_get(SUBFRAME_CNT_MAX, subFrameCount) || !_getSystemClockFrequency(sysClkFrequency))
     return false;
   uint numerator = sysClkFrequency*1000000,
   denominator = pixCount*quadCount*subFrameCount;
   uint g = gcd(numerator, denominator);
   r.numerator = numerator/g;
   r.denominator = denominator/g;
   return true;
 }
bool Voxel::TI::ToFCamera::_getFrameSize (Voxel::FrameSize & s) const protected virtual
Implements Voxel::DepthCamera.
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 148 of file ToFCamera.cpp.
References Voxel::DepthCamera::_get(), BIN_COLUMN_COUNT, BIN_ROW_COUNT, Voxel::FrameSize::height, and Voxel::FrameSize::width.
Referenced by Voxel::TI::HaddockCDKCamera::_initStartParams(), Voxel::TI::ToFHaddockCamera::_setROI(), and Voxel::TI::ToFTintinCamera::_setROI().
 {
   uint binRowCount, binColumnCount;
   if(!_get(BIN_ROW_COUNT, binRowCount) || !_get(BIN_COLUMN_COUNT, binColumnCount))
     return false;
   s.width = binColumnCount;
   s.height = binRowCount;
   return true;
 }
virtual bool Voxel::TI::ToFCamera::_getIlluminationFrequency (float & frequency) const protected pure virtual
Implemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by _getDepthScalingFactor().
bool Voxel::TI::ToFCamera::_getMaximumFrameRate (FrameRate & frameRate, const FrameSize & forFrameSize) const protected virtual
Implements Voxel::DepthCamera.
Reimplemented in Voxel::TI::TintinCDKCamera, Voxel::TI::HaddockCDKCamera, and Voxel::TI::CalculusCDKCamera.
Definition at line 452 of file ToFCamera.cpp.
References _getBytesPerPixel(), Voxel::DepthCamera::_getSupportedVideoModes(), Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, and Voxel::FrameSize::width.
 {
   Vector<SupportedVideoMode> supportedVideoModes;
   uint bytesPerPixel;
   if(!_getSupportedVideoModes(supportedVideoModes) || !_getBytesPerPixel(bytesPerPixel))
   {
     logger(LOG_ERROR) << "Could not get supported video modes or current bytes per pixel, to get nearest valid frame size" << std::endl;
     return false;
   }
   int minScore = 0;
   IndexType index = -1;
   int area = forFrameSize.height*forFrameSize.width;
   if(supportedVideoModes.size() > 0)
   {
     for(IndexType i = 0; i < supportedVideoModes.size(); i++)
     {
       auto &a = supportedVideoModes[i];
       int scoreA = a.frameSize.width*a.frameSize.height;
       scoreA = (bytesPerPixel != a.bytesPerPixel || scoreA < area ||
         a.frameSize.width < forFrameSize.width || a.frameSize.height < forFrameSize.height)?0:scoreA;
       if(scoreA < minScore)
       {
         minScore = scoreA;
         index = i;
       }
     }
     if(index < 0)
     {
       logger(LOG_ERROR) << "ToFCamera: No supported frame size exists close to the desired frame size. Could not set frame size." << std::endl;
       return false;
     }
     frameRate = supportedVideoModes[index].frameRate;
     return true;
   }
   else
   {
     logger(LOG_ERROR) << "ToFCamera: No video modes available for this depth camera." << std::endl;
     return false;
   }
 }
bool Voxel::TI::ToFCamera::_getOpDataArrangeMode (int & dataArrangeMode) const protected virtual
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 289 of file ToFCamera.cpp.
References Voxel::LOG_ERROR, Voxel::logger, and OP_DATA_ARRANGE_MODE.
Referenced by _initStartParams().
 {
   int b;
   if(!get(OP_DATA_ARRANGE_MODE, b))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not get data arrange mode" << std::endl;
     return false;
   }
   dataArrangeMode = b;
   return true;
 }
virtual bool Voxel::TI::ToFCamera::_getSystemClockFrequency (uint & frequency) const protected pure virtual
Implemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by _getFrameRate(), and _setFrameRate().
bool Voxel::TI::ToFCamera::_getToFFrameType (ToFFrameType & frameType) const protected virtual
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 558 of file ToFCamera.cpp.
References Voxel::DepthCamera::_get(), CameraSystemIQFrameTest::r, ToF_FRAME_TYPE, Voxel::ToF_I_Q, Voxel::ToF_PHASE_AMPLITUDE, and Voxel::ToF_QUAD.
Referenced by _initStartParams(), and Voxel::TI::HaddockCDKCamera::_setStreamerFrameSize().
 {
   int r;
   if(!_get(ToF_FRAME_TYPE, r))
   {
     frameType = ToF_PHASE_AMPLITUDE;
     return true;
   }
   if(r == 1)
     frameType = ToF_I_Q;
   else if(r == 0)
     frameType = ToF_PHASE_AMPLITUDE;
   else if(r == 15)
     frameType = ToF_QUAD;
   else
     return false; // Unknown frame type
     return true;
 }
bool Voxel::TI::ToFCamera::_init () protected
Definition at line 82 of file ToFCamera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::TI::ToFCameraBase::_init(), Voxel::DepthCamera::_programmer, and IntegrationTimeParameter.
Referenced by Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), and Voxel::TI::ToFTintinCamera::_init().
 {
   if(!_addParameters({
     ParameterPtr(new IntegrationTimeParameter(*this, *_programmer))
   }))
     return false;
   if(!ToFCameraBase::_init())
   {
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCamera::_initStartParams () protected virtual
Reimplemented from Voxel::TI::ToFCameraBase.
Reimplemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, Voxel::TI::TintinCDKCamera, Voxel::TI::HaddockCDKCamera, Voxel::TI::CalculusCDKCamera, Voxel::TI::VoxelDCamera, Voxel::TI::Voxel14Camera, and Voxel::TI::ToFHaddockCamera.
Definition at line 367 of file ToFCamera.cpp.
References _applyCalibrationParams(), _getBinning(), _getBytesPerPixel(), _getOpDataArrangeMode(), _getToFFrameType(), Voxel::TI::ToFCameraBase::_initStartParams(), _is16BitModeEnabled(), _isHistogramEnabled(), Voxel::DepthCamera::_pointCloudFrameGenerator, _tofFrameGenerator, CALIB_DISABLE, CALIB_SECT_CROSS_TALK, CALIB_SECT_LENS, CALIB_SECT_PIXELWISE_OFFSET, Voxel::DepthCamera::configFile, CameraSystemTest::frameSize, Voxel::MainConfigurationFile::get(), Voxel::MainConfigurationFile::getFile(), Voxel::ConfigurationFile::getFloat(), Voxel::DepthCamera::getFrameSize(), Voxel::ConfigurationFile::getInteger(), Voxel::DepthCamera::getMaximumFrameSize(), Voxel::DepthCamera::getROI(), Voxel::FrameSize::height, Voxel::MainConfigurationFile::isPresent(), Voxel::LOG_ERROR, Voxel::logger, OP_DATA_ARRANGE_MODE, PIXEL_DATA_SIZE, QUAD_CNT_MAX, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
Referenced by Voxel::TI::ToFHaddockCamera::_initStartParams(), Voxel::TI::HaddockCDKCamera::_initStartParams(), Voxel::TI::ToFCalculusCamera::_initStartParams(), and Voxel::TI::ToFTintinCamera::_initStartParams().
 {
   RegionOfInterest roi;
   uint rowsToMerge, columnsToMerge;
   if(!_getBinning(rowsToMerge, columnsToMerge) ||
     !getROI(roi))
     return false;
   int lensCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_LENS) == 0;
   if(!_pointCloudFrameGenerator->setParameters(
     roi.x, roi.y, roi.width, roi.height,
     rowsToMerge, columnsToMerge,
     configFile.getFloat("calib", "fx")*lensCalibEnable, // fx
     configFile.getFloat("calib", "fy")*lensCalibEnable, // fy
     configFile.getFloat("calib", "cx")*lensCalibEnable,// cx
     configFile.getFloat("calib", "cy")*lensCalibEnable,// cy
     configFile.getFloat("calib", "k1")*lensCalibEnable,// k1
     configFile.getFloat("calib", "k2")*lensCalibEnable,// k2
     configFile.getFloat("calib", "k3")*lensCalibEnable,// k3
     configFile.getFloat("calib", "p1")*lensCalibEnable,// p1
     configFile.getFloat("calib", "p2")*lensCalibEnable // p2
   ))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set parameters to PointCloudFrameGenerator" << std::endl;
     return false;
   }
   FrameSize maxFrameSize, frameSize;
   if(!getMaximumFrameSize(maxFrameSize) || !getFrameSize(frameSize))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not get frame related parameters. Cannot convert raw data to ToF data" << std::endl;
     return false;
   }
   uint bytesPerPixel;
   int dataArrangeMode;
   int quadCount;
   ToFFrameType type;
   bool dealiased16BitMode;
   if(!_getBytesPerPixel(bytesPerPixel) || !_getOpDataArrangeMode(dataArrangeMode) || !_getToFFrameType(type) ||
     !_is16BitModeEnabled(dealiased16BitMode) || !get(QUAD_CNT_MAX, quadCount))
   {
     logger(LOG_ERROR) << "ToFCamera: Failed to read " << PIXEL_DATA_SIZE << " or "
     << OP_DATA_ARRANGE_MODE << " or " << type << std::endl;
     return false;
   }
   Vector<int16_t> phaseOffsets;
   String phaseOffsetFileName;
   bool pixelwiseCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_PIXELWISE_OFFSET) == 0;
   bool crossTalkCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_CROSS_TALK) == 0;
   std::cout << "pixel-wise phase offset active = " << pixelwiseCalibEnable << std::endl;
   if(pixelwiseCalibEnable && configFile.isPresent("calib", "phasecorrection") && !configFile.getFile<int16_t>("calib", "phasecorrection", phaseOffsetFileName, phaseOffsets))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not read phase offset correction file" << std::endl;
     return false;
   }
   if(!_tofFrameGenerator->setParameters(phaseOffsetFileName, phaseOffsets, bytesPerPixel,
     dataArrangeMode, roi, maxFrameSize, frameSize, rowsToMerge, columnsToMerge, _isHistogramEnabled(),
                                         crossTalkCalibEnable?configFile.get("calib", "cross_talk_coeff"):"",
                                         type, (uint32_t) quadCount, dealiased16BitMode
   ))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set parameters to ToFFrameGenerator" << std::endl;
     return false;
   }
   if(!_applyCalibrationParams() || !ToFCameraBase::_initStartParams())
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set calibration parameters" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCamera::_is16BitModeEnabled (bool & mode16Bit) protected virtual
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 346 of file ToFCamera.cpp.
References DEALIAS_16BIT_OP_ENABLE.
Referenced by _getDepthScalingFactor(), and _initStartParams().
 {
   return get(DEALIAS_16BIT_OP_ENABLE, mode16Bit);
 }
virtual bool Voxel::TI::ToFCamera::_isHistogramEnabled () const protected pure virtual
Implemented in Voxel::TI::ToFCalculusCamera, Voxel::TI::ToFTintinCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by _initStartParams().
bool Voxel::TI::ToFCamera::_processRawFrame (const RawFramePtr & rawFrameInput, RawFramePtr & rawFrameOutput) protected virtual
Implements Voxel::DepthCamera.
Definition at line 351 of file ToFCamera.cpp.
References _tofFrameGenerator, LensCalibrationTest::p1, and LensCalibrationTest::p2.
 {
   FramePtr p1 = std::dynamic_pointer_cast<Frame>(rawFrameInput);
   FramePtr p2 = std::dynamic_pointer_cast<Frame>(rawFrameOutput);
   bool ret = _tofFrameGenerator->generate(p1, p2);
   if(ret)
   {
     rawFrameOutput = std::dynamic_pointer_cast<RawFrame>(p2);
     return true;
   }
   else
     return false;
 }
bool Voxel::TI::ToFCamera::_reset () protected virtual
Implements Voxel::DepthCamera.
Definition at line 581 of file ToFCamera.cpp.
References Voxel::DepthCamera::set(), and SOFTWARE_RESET.
 {
   return set(SOFTWARE_RESET, true); // Reset the chipset
 }
bool Voxel::TI::ToFCamera::_saveCurrentProfileID (const int id) protected virtual
Implements Voxel::DepthCamera.
Definition at line 668 of file ToFCamera.cpp.
References _getCurrentProfileRegisterName(), Voxel::DepthCamera::_set(), Voxel::DepthCamera::id(), and Voxel::DepthCamera::name().
 {
   String name;
   if(!_getCurrentProfileRegisterName(name))
     return false;
   uint i = id;
   return _set(name, i);
 }
bool Voxel::TI::ToFCamera::_setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize & frameSize) protected virtual
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 328 of file ToFCamera.cpp.
References Voxel::DepthCamera::_set(), BIN_COLS_TO_MERGE, BIN_COLUMN_COUNT, BIN_ROW_COUNT, BIN_ROWS_TO_MERGE, BINNING_EN, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, and Voxel::FrameSize::width.
Referenced by _setFrameSize(), Voxel::TI::ToFHaddockCamera::_setROI(), and Voxel::TI::ToFTintinCamera::_setROI().
 {
   if(!_set(BIN_ROWS_TO_MERGE, rowsToMerge) || !_set(BIN_COLS_TO_MERGE, columnsToMerge) ||
     !_set(BIN_ROW_COUNT, (uint)frameSize.height) || !_set(BIN_COLUMN_COUNT, (uint)frameSize.width)
      || !_set(BINNING_EN, true))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set binning related parameters" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCamera::_setBytesPerPixel (const uint & bpp) protected virtual
Implements Voxel::DepthCamera.
Definition at line 275 of file ToFCamera.cpp.
References Voxel::DepthCamera::_set(), Voxel::LOG_ERROR, Voxel::logger, OP_DATA_ARRANGE_MODE, and PIXEL_DATA_SIZE.
 {
   int b = (int)bpp;
   int dataArrangeMode = (b == 4)?2:0;
   if(!_set(PIXEL_DATA_SIZE, b) || !_set(OP_DATA_ARRANGE_MODE, dataArrangeMode))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set bytes per pixel or data arrange mode" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCamera::_setFrameRate (const FrameRate & r) protected virtual
Implements Voxel::DepthCamera.
Reimplemented in Voxel::TI::ToFCalculusCamera.
Definition at line 120 of file ToFCamera.cpp.
References Voxel::DepthCamera::_get(), _getSystemClockFrequency(), Voxel::DepthCamera::_set(), Voxel::FrameRate::denominator, INTG_TIME, Voxel::LOG_DEBUG, Voxel::logger, Voxel::FrameRate::numerator, PIX_CNT_MAX, PIX_CNT_MAX_SET_FAILED, QUAD_CNT_MAX, and SUBFRAME_CNT_MAX.
Referenced by Voxel::TI::HaddockUnambiguousRangeParameter::set(), and Voxel::TI::TintinUnambiguousRangeParameter::set().
 {
   bool pixCountSetFailed;
   uint sysClkFrequency, pixCount;
   int quadCount, subFrameCount;
   if(!_get(QUAD_CNT_MAX, quadCount) || !_get(SUBFRAME_CNT_MAX, subFrameCount) || !_getSystemClockFrequency(sysClkFrequency))
     return false;
   if(r.numerator == 0 || quadCount == 0 || subFrameCount == 0)
     return false;
   pixCount = (uint)((((uint64_t)r.denominator)*sysClkFrequency*1000000L)/(((uint64_t)quadCount)*subFrameCount*r.numerator));
   logger(LOG_DEBUG) << "ToFCamera: Setting " << PIX_CNT_MAX << " = " << pixCount << std::endl;
   if(!_set(PIX_CNT_MAX, pixCount) || !_get(PIX_CNT_MAX_SET_FAILED, pixCountSetFailed) || pixCountSetFailed)
     return false;
   uint integrationTime;
   if(!_get(INTG_TIME, integrationTime) || !_set(INTG_TIME, integrationTime))
     return false;
   return true;
 }
bool Voxel::TI::ToFCamera::_setFrameSize (const FrameSize & s) protected virtual
Implements Voxel::DepthCamera.
Definition at line 160 of file ToFCamera.cpp.
Referenced by Voxel::TI::ToFHaddockCamera::_setROI(), Voxel::TI::ToFTintinCamera::_setROI(), and Voxel::TI::ToFCalculusCamera::_setROI().
 {
   return _setFrameSize(s, true);
 }
bool Voxel::TI::ToFCamera::_setFrameSize (const FrameSize & s, bool resetROI) protected virtual
Definition at line 165 of file ToFCamera.cpp.
References _getBytesPerPixel(), Voxel::DepthCamera::_getMaximumFrameSize(), Voxel::DepthCamera::_getROI(), Voxel::DepthCamera::_getSupportedVideoModes(), _setBinning(), Voxel::DepthCamera::_setROI(), _setStreamerFrameSize(), Voxel::FrameSize::height, Voxel::DepthCamera::isRunning(), Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
   if(isRunning())
   {
     logger(LOG_ERROR) << "ToFCamera: Cannot set frame size while the camera is streaming" << std::endl;
     return false;
   }
   RegionOfInterest roi;
   if(resetROI)
   {
     FrameSize maxFrameSize;
     if(!_getMaximumFrameSize(maxFrameSize))
     {
       logger(LOG_ERROR) << "ToFCamera: Could not get maximum frame size. Need that to reset ROI" << std::endl;
       return false;
     }
     roi.x = roi.y = 0;
     roi.width = maxFrameSize.width;
     roi.height = maxFrameSize.height;
     if(!_setROI(roi))
     {
       logger(LOG_ERROR) << "ToFCamera: Could not reset ROI" << std::endl;
       return false;
     }
   }
   else if(!_getROI(roi))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not get current ROI, to set frame size" << std::endl;
     return false;
   }
   FrameSize toSet;
   toSet.width = (s.width <= roi.width)?s.width:roi.width;
   toSet.height = (s.height <= roi.height)?s.height:roi.height;
   Vector<SupportedVideoMode> supportedVideoModes;
   uint bytesPerPixel;
   if(!_getSupportedVideoModes(supportedVideoModes) || !_getBytesPerPixel(bytesPerPixel))
   {
     logger(LOG_ERROR) << "Could not get supported video modes or current bytes per pixel, to get nearest valid frame size" << std::endl;
     return false;
   }
   int maxScore = 0;
   IndexType index = -1;
   int area = toSet.height*toSet.width;
   if(supportedVideoModes.size() > 0)
   {
     for(IndexType i = 0; i < supportedVideoModes.size(); i++)
     {
       auto &a = supportedVideoModes[i];
       int scoreA = a.frameSize.width*a.frameSize.height;
       scoreA = (bytesPerPixel != a.bytesPerPixel || scoreA > area || a.frameSize.width > toSet.width || a.frameSize.height > toSet.height)?0:scoreA;
       if(scoreA > maxScore)
       {
         maxScore = scoreA;
         index = i;
       }
     }
     if(index < 0)
     {
       logger(LOG_ERROR) << "ToFCamera: No supported frame size exists close to the desired frame size. Could not set frame size." << std::endl;
       return false;
     }
     toSet = supportedVideoModes[index].frameSize;
   }
   uint rowsToMerge = (roi.height + toSet.height - 1)/toSet.height,
   columnsToMerge = (roi.width + toSet.width - 1)/toSet.width;
   if(!_setBinning(rowsToMerge, columnsToMerge, toSet))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not set binning for required frame size" << std::endl;
     return false;
   }
   if(!_setStreamerFrameSize(toSet))
   {
     logger(LOG_ERROR) << "ToFCamera: Could not get streamer's frame size" << std::endl;
     return false;
   }
   return true;
 }
virtual bool Voxel::TI::ToFCamera::_setStreamerFrameSize (const FrameSize & s) protected pure virtual
Implemented in Voxel::TI::TintinCDKCamera, Voxel::TI::HaddockCDKCamera, Voxel::TI::VoxelDCamera, Voxel::TI::CalculusCDKCamera, and Voxel::TI::Voxel14Camera.
Referenced by _setFrameSize().
bool Voxel::TI::ToFCamera::setSerialNumber (const String & serialNumber) virtual
Reimplemented from Voxel::DepthCamera.
Definition at line 617 of file ToFCamera.cpp.
References Voxel::DepthCamera::_device, Voxel::DepthCamera::_programmer, Voxel::TI::VoxelUSBProgrammer::getUSBIO(), Voxel::LOG_ERROR, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, Voxel::DepthCamera::setSerialNumber(), TI_SERIAL_NUMBER_SIZE, TI_USBIO_SERIAL_NUMBER, and Voxel::USBIO::TO_DEVICE.
 {
   if(serialNumber.size() > TI_SERIAL_NUMBER_SIZE)
   {
     logger(LOG_ERROR) << "ToFCamera: Please specify serial number with at most '" << TI_SERIAL_NUMBER_SIZE << "' bytes." << std::endl;
     return false;
   }
   VoxelUSBProgrammer *p = dynamic_cast<VoxelUSBProgrammer *>(&*_programmer);
   if(p)
   {
     USBIOPtr usbIO = p->getUSBIO();
     uint16_t length = serialNumber.size();
     if(!usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, TI_USBIO_SERIAL_NUMBER, 0, 0,
       (uint8_t *)serialNumber.c_str(), length))
     {
       logger(LOG_ERROR) << "ToFCamera: Could not set serial number from depth camera." << std::endl;
       return false;
     }
     else
     {
       _device->setSerialNumber(serialNumber);
       return true;
     }
   }
   return DepthCamera::setSerialNumber(serialNumber);
 }
Friends And Related Function Documentation
friend class IntegrationTimeParameter friend
Definition at line 160 of file ToFCamera.h.
Referenced by _init().
Member Data Documentation
Ptr<ToFFrameGenerator> Voxel::TI::ToFCamera::_tofFrameGenerator protected
Definition at line 148 of file ToFCamera.h.
Referenced by _initStartParams(), _processRawFrame(), and ToFCamera().
The documentation for this class was generated from the following files:
ToFCamera.h
ToFCamera.cpp