Voxel: Voxel::USBSystem Class Reference
Voxel::USBSystem Class Reference
I/O classes
#include <USBSystem.h>
Public Member Functions
USBSystem ()
Vector< DevicePtr > getDevices ()
bool isInitialized ()
USBSystemPrivate & getUSBSystemPrivate ()
String getDeviceNode (const USBDevice &usbd)
virtual ~USBSystem ()
Protected Attributes
Ptr< USBSystemPrivate > _usbPrivate
Detailed Description
Definition at line 25 of file USBSystem.h.
Constructor & Destructor Documentation
Voxel::USBSystem::USBSystem ()
Definition at line 19 of file USBSystem.cpp.
References _usbPrivate, and Voxel::USBSystemPrivate.
 {
   _usbPrivate = Ptr<USBSystemPrivate>(new USBSystemPrivate());
 }
virtual Voxel::USBSystem::~USBSystem () inline virtual
Definition at line 41 of file USBSystem.h.
 {}
Member Function Documentation
String Voxel::USBSystem::getDeviceNode (const USBDevice & usbd)
Definition at line 56 of file USBSystem.cpp.
References _usbPrivate.
Referenced by main(), Voxel::USBIO::USBIOPrivate::USBIOPrivate(), and Voxel::UVCPrivate::UVCPrivate().
 {
   return _usbPrivate->getDeviceNode(usbd);
 }
Vector< DevicePtr > Voxel::USBSystem::getDevices ()
Definition at line 30 of file USBSystem.cpp.
References _usbPrivate, CameraSystemIQFrameTest::count, and CameraSystemTest::devices.
Referenced by Voxel::USBDeviceScanner::_scan().
 {
   Vector<DevicePtr> devices = _usbPrivate->getDevices();
   // Show serial index for all those whose IDs have repeated.
   Map<String, int> count;
   for(auto &d: devices)
   {
     auto f = count.find(d->id());
     if(f != count.end())
       f->second++;
     else
       count[d->id()] = 1;
   }
   for(auto &d: devices)
   {
     if(count[d->id()] > 1)
       d->showSerialIndex();
   }
   return devices;
 }
USBSystemPrivate& Voxel::USBSystem::getUSBSystemPrivate () inline
Definition at line 37 of file USBSystem.h.
Referenced by Voxel::USBIO::USBIOPrivate::USBIOPrivate().
 { return *_usbPrivate; }
bool Voxel::USBSystem::isInitialized ()
Definition at line 24 of file USBSystem.cpp.
References _usbPrivate.
Referenced by Voxel::USBIO::USBIOPrivate::USBIOPrivate().
 {
   return _usbPrivate->isInitialized();
 }
Member Data Documentation
Ptr<USBSystemPrivate> Voxel::USBSystem::_usbPrivate protected
Definition at line 28 of file USBSystem.h.
Referenced by getDeviceNode(), getDevices(), isInitialized(), and USBSystem().
The documentation for this class was generated from the following files:
USBSystem.h
USBSystem.cpp