Voxel: Voxel::Parameter Class Reference
Voxel::Parameter Class Reference abstract
Parameter related classes
#include <Parameter.h>
Public Types
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Public Member Functions
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual bool refresh ()=0
virtual ~Parameter ()
Protected Member Functions
void _computeMask ()
Protected Attributes
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Friends
class ParameterDMLParser
Detailed Description
Definition at line 30 of file Parameter.h.
Member Enumeration Documentation
enum Voxel::Parameter::IOType
Enumerator
IO_READ_ONLY
IO_READ_WRITE
IO_WRITE_ONLY
Definition at line 33 of file Parameter.h.
   {
     IO_READ_ONLY = 0,
     IO_READ_WRITE,
     IO_WRITE_ONLY
   };
Constructor & Destructor Documentation
Voxel::Parameter::Parameter (RegisterProgrammer & programmer, const String & name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String & displayName, const String & description, IOType ioType = IO_READ_WRITE, const Vector< String > & dependencies = {}) inline
Definition at line 58 of file Parameter.h.
                                                                                                                                       {})
   : _programmer(programmer), _name(name), _displayName(displayName), _description(description),
   _address(address), _msb(msb), _registerLength(registerLength), _lsb(lsb), _ioType(ioType), _dependencies(dependencies)
   {
     _computeMask();
   }
virtual Voxel::Parameter::~Parameter () inline virtual
Definition at line 81 of file Parameter.h.
 {}
Member Function Documentation
void Voxel::Parameter::_computeMask () protected
Definition at line 13 of file Parameter.cpp.
References _lsb, _mask, _msb, and _registerLength.
 {
   if(_msb < _lsb)
     _mask = -1; // fictitious register
   _mask = (1 << _registerLength) - 1;
   for (auto i = _lsb; i <= _msb; i++)
   {
     _mask -= (1 << i);
   }
 }
uint32_t Voxel::Parameter::address () const inline
Definition at line 69 of file Parameter.h.
Referenced by Voxel::TI::VoxelProgrammerBase::getValue(), and Voxel::TI::VoxelProgrammerBase::setValue().
 { return _address; }
const String& Voxel::Parameter::description () const inline
Definition at line 68 of file Parameter.h.
 { return _description; }
const String& Voxel::Parameter::displayName () const inline
Definition at line 67 of file Parameter.h.
 { return _displayName; }
IOType Voxel::Parameter::ioType () const inline
Definition at line 74 of file Parameter.h.
 { return _ioType; }
uint8_t Voxel::Parameter::lsb () const inline
Definition at line 72 of file Parameter.h.
Referenced by Voxel::TI::VoxelProgrammerBase::getValue(), and Voxel::TI::VoxelProgrammerBase::setValue().
 { return _lsb; }
uint32_t Voxel::Parameter::mask () const inline
Definition at line 71 of file Parameter.h.
Referenced by Voxel::TI::VoxelProgrammerBase::getValue(), and Voxel::TI::VoxelProgrammerBase::setValue().
 { return _mask; }
uint8_t Voxel::Parameter::msb () const inline
Definition at line 70 of file Parameter.h.
 { return _msb; }
const String& Voxel::Parameter::name () const inline
Definition at line 66 of file Parameter.h.
 { return _name; }
virtual bool Voxel::Parameter::refresh () pure virtual
Implemented in Voxel::ParameterTemplate< T >, Voxel::ParameterTemplate< float >, Voxel::ParameterTemplate< int >, and Voxel::ParameterTemplate< bool >.
void Voxel::Parameter::setAddress (uint32_t a) inline
Definition at line 77 of file Parameter.h.
 { _address = a; }
void Voxel::Parameter::setName (const String & n) inline
Definition at line 76 of file Parameter.h.
 { _name = n; }
Friends And Related Function Documentation
friend class ParameterDMLParser friend
Definition at line 83 of file Parameter.h.
Member Data Documentation
uint32_t Voxel::Parameter::_address protected
Definition at line 41 of file Parameter.h.
Vector<String> Voxel::Parameter::_dependencies protected
Definition at line 51 of file Parameter.h.
String Voxel::Parameter::_description protected
Definition at line 49 of file Parameter.h.
String Voxel::Parameter::_displayName protected
Definition at line 48 of file Parameter.h.
IOType Voxel::Parameter::_ioType protected
Definition at line 45 of file Parameter.h.
Referenced by Voxel::ParameterTemplate< bool >::get(), and Voxel::ParameterTemplate< bool >::set().
uint8_t Voxel::Parameter::_lsb protected
Definition at line 42 of file Parameter.h.
Referenced by _computeMask().
uint32_t Voxel::Parameter::_mask protected
Definition at line 41 of file Parameter.h.
Referenced by _computeMask().
uint8_t Voxel::Parameter::_msb protected
Definition at line 42 of file Parameter.h.
Referenced by _computeMask().
String Voxel::Parameter::_name protected
Definition at line 47 of file Parameter.h.
RegisterProgrammer& Voxel::Parameter::_programmer protected
Definition at line 53 of file Parameter.h.
Referenced by Voxel::ParameterTemplate< bool >::get(), and Voxel::ParameterTemplate< bool >::set().
uint8_t Voxel::Parameter::_registerLength protected
Definition at line 42 of file Parameter.h.
Referenced by _computeMask().
The documentation for this class was generated from the following files:
Parameter.h
Parameter.cpp