Voxel: Voxel::RangeParameterTemplate< T > Class Template Reference
Voxel::RangeParameterTemplate< T > Class Template Reference
Parameter related classes
#include <Parameter.h>
Public Member Functions
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &lowerLimit, const T &upperLimit, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const T lowerLimit () const
virtual const T upperLimit () const
virtual void setLowerLimit (T lowerLimit)
virtual void setUpperLimit (T upperLimit)
virtual bool validate (const T &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< T >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool set (const T &value)
virtual bool refresh ()
virtual bool get (T &value, bool refresh=false)
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Static Public Member Functions
static Ptr
< RangeParameterTemplate< T > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< T >
static Ptr< ParameterTemplate
< T > > typeCast (const ParameterPtr &other)
Protected Attributes
T _lowerLimit
T _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< T >
T _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Protected Member Functions inherited from Voxel::ParameterTemplate< T >
virtual uint32_t _toRawValue (T value) const
virtual T _fromRawValue (uint32_t value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Detailed Description
template<typename T>
class Voxel::RangeParameterTemplate< T >
Definition at line 319 of file Parameter.h.
Constructor & Destructor Documentation
template<typename T> Voxel::RangeParameterTemplate< T >::RangeParameterTemplate (RegisterProgrammer & programmer, const String & name, const String & unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T & lowerLimit, const T & upperLimit, const T & defaultValue, const String & displayName, const String & description, Parameter::IOType ioType = Parameter::IO_READ_WRITE, const Vector< String > & dependencies = {}) inline
Definition at line 327 of file Parameter.h.
                                                                                                                                                                {}):
   ParameterTemplate<T>(programmer, name, address, registerLength, msb, lsb, defaultValue, displayName, description, ioType, dependencies),
   _lowerLimit(lowerLimit), _upperLimit(upperLimit), _unit(unit)
   {
   }
template<typename T> virtual Voxel::RangeParameterTemplate< T >::~RangeParameterTemplate () inline virtual
Definition at line 353 of file Parameter.h.
 {}
Member Function Documentation
template<typename T> virtual const T Voxel::RangeParameterTemplate< T >::lowerLimit () const inline virtual
Reimplemented in Voxel::TI::TintinModulationFrequencyParameter.
Definition at line 342 of file Parameter.h.
Referenced by Voxel::CLIManager::_showParameterInfo(), Voxel::TI::HaddockModulationFrequencyParameter::set(), Voxel::TI::TintinModulationFrequencyParameter::set(), Voxel::TI::HaddockUnambiguousRangeParameter::set(), Voxel::TI::TintinUnambiguousRangeParameter::set(), and Voxel::RangeParameterTemplate< int >::setLowerLimit().
 { return _lowerLimit; }
template<typename T> virtual void Voxel::RangeParameterTemplate< T >::setLowerLimit (T lowerLimit) inline virtual
Definition at line 345 of file Parameter.h.
 { _lowerLimit = lowerLimit; }
template<typename T> virtual void Voxel::RangeParameterTemplate< T >::setUpperLimit (T upperLimit) inline virtual
Definition at line 346 of file Parameter.h.
 { _upperLimit = upperLimit; }
template<typename T> static Ptr<RangeParameterTemplate<T> > Voxel::RangeParameterTemplate< T >::typeCast (const ParameterPtr & other) inline static
Definition at line 335 of file Parameter.h.
   {
     return std::dynamic_pointer_cast<RangeParameterTemplate<T>>(other);
   }
template<typename T> const String& Voxel::RangeParameterTemplate< T >::unit () const inline
Definition at line 340 of file Parameter.h.
Referenced by Voxel::CLIManager::_getParameter(), Voxel::CLIManager::_setParameter(), and Voxel::CLIManager::_showParameterInfo().
 { return _unit; }
template<typename T> virtual const T Voxel::RangeParameterTemplate< T >::upperLimit () const inline virtual
Reimplemented in Voxel::TI::TintinModulationFrequencyParameter.
Definition at line 343 of file Parameter.h.
Referenced by Voxel::CLIManager::_showParameterInfo(), Voxel::TI::TintinCDKIlluminationPowerPercentParameter::get(), Voxel::TI::HaddockModulationFrequencyParameter::set(), Voxel::TI::TintinCDKIlluminationPowerPercentParameter::set(), Voxel::TI::HaddockUnambiguousRangeParameter::set(), Voxel::TI::CalculusModulationFrequencyParameter::set(), Voxel::TI::TintinUnambiguousRangeParameter::set(), and Voxel::RangeParameterTemplate< int >::setUpperLimit().
 { return _upperLimit; }
template<typename T> virtual bool Voxel::RangeParameterTemplate< T >::validate (const T & value) const inline virtual
Implements Voxel::ParameterTemplate< T >.
Definition at line 348 of file Parameter.h.
Referenced by Voxel::TI::IntegrationTimeParameter::set().
   {
     return !(value < _lowerLimit || value > _upperLimit);
   }
Member Data Documentation
template<typename T> T Voxel::RangeParameterTemplate< T >::_lowerLimit protected
Definition at line 322 of file Parameter.h.
Referenced by Voxel::RangeParameterTemplate< int >::lowerLimit(), and Voxel::RangeParameterTemplate< int >::setLowerLimit().
template<typename T> String Voxel::RangeParameterTemplate< T >::_unit protected
Definition at line 324 of file Parameter.h.
Referenced by Voxel::RangeParameterTemplate< int >::unit().
template<typename T> T Voxel::RangeParameterTemplate< T >::_upperLimit protected
Definition at line 322 of file Parameter.h.
Referenced by Voxel::RangeParameterTemplate< int >::setUpperLimit(), Voxel::RangeParameterTemplate< int >::upperLimit(), and Voxel::RangeParameterTemplate< int >::validate().
The documentation for this class was generated from the following file:
Parameter.h