Voxel: Voxel::TI::VoxelXUProgrammer Class Reference
Voxel::TI::VoxelXUProgrammer Class Reference
#include <VoxelXUProgrammer.h>
Public Member Functions
VoxelXUProgrammer (const SlaveAddressToByteMap &map, DevicePtr device)
virtual bool isInitialized () const
void init ()
virtual bool reset ()
virtual ~VoxelXUProgrammer ()
Public Member Functions inherited from Voxel::TI::VoxelProgrammerBase
VoxelProgrammerBase (const SlaveAddressToByteMap &map, DevicePtr device)
virtual bool readRegister (uint32_t address, uint32_t &value) const
virtual bool writeRegister (uint32_t address, uint32_t value)
virtual bool getValue (const Parameter &param, uint32_t &value) const
virtual bool setValue (const Parameter &param, uint32_t value, bool writeOnly=false)
virtual ~VoxelProgrammerBase ()
Public Member Functions inherited from Voxel::RegisterProgrammer
virtual ~RegisterProgrammer ()
Protected Types
enum Control {
CONTROL_WRITE_REGISTER_3 = 1, CONTROL_SET_READ_REGISTER = 2, CONTROL_READ_REGISTER_3 = 3, CONTROL_WRITE_REGISTER_1 = 4,
CONTROL_READ_REGISTER_1 = 5, CONTROL_REBOOT_FW_MODE = 6, CONTROL_GET_VERSION = 7, CONTROL_WRITE_REGISTER_2 = 8,
CONTROL_READ_REGISTER_2 = 9
}
Protected Member Functions
virtual bool _readRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t &value, uint8_t length) const
virtual bool _writeRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t value, uint8_t length)
Protected Attributes
UVCXUPtr _xu
const int _XU_ID = 3
uint8_t _majorVersion
uint8_t _minorVersion
Protected Attributes inherited from Voxel::TI::VoxelProgrammerBase
DevicePtr _device
Mutex _mutex
SlaveAddressToByteMap _slaveAddressToByteMap
Additional Inherited Members
Public Types inherited from Voxel::TI::VoxelProgrammerBase
typedef Map< uint, uint > SlaveAddressToByteMap
Detailed Description
Definition at line 19 of file VoxelXUProgrammer.h.
Member Enumeration Documentation
enum Voxel::TI::VoxelXUProgrammer::Control protected
Enumerator
CONTROL_WRITE_REGISTER_3
CONTROL_SET_READ_REGISTER
CONTROL_READ_REGISTER_3
CONTROL_WRITE_REGISTER_1
CONTROL_READ_REGISTER_1
CONTROL_REBOOT_FW_MODE
CONTROL_GET_VERSION
CONTROL_WRITE_REGISTER_2
CONTROL_READ_REGISTER_2
Definition at line 28 of file VoxelXUProgrammer.h.
   {
     CONTROL_WRITE_REGISTER_3 = 1, // Write 3 bytes
     CONTROL_SET_READ_REGISTER = 2, // Set read register
     CONTROL_READ_REGISTER_3 = 3, // Read 3 bytes
     CONTROL_WRITE_REGISTER_1 = 4, // Write 1 byte
     CONTROL_READ_REGISTER_1 = 5, // Read 1 byte
     CONTROL_REBOOT_FW_MODE = 6, // Reboot to firmware mode
     CONTROL_GET_VERSION = 7, // Get 2 bytes (major.minor) version
     CONTROL_WRITE_REGISTER_2 = 8, // Write 2 bytes
     CONTROL_READ_REGISTER_2 = 9, // Write 2 bytes
   };
Constructor & Destructor Documentation
Voxel::TI::VoxelXUProgrammer::VoxelXUProgrammer (const SlaveAddressToByteMap & map, DevicePtr device)
Definition at line 38 of file VoxelXUProgrammer.cpp.
References init(), Voxel::LOG_ERROR, Voxel::logger, and Voxel::Device::USB.
                                                                                       : VoxelProgrammerBase(map, device)
 {
   if(device->interfaceID() != Device::USB)
   {
     logger(LOG_ERROR) << "VoxelXUProgrammer: Invalid device." << std::endl;
     return;
   }
   init();
 }
virtual Voxel::TI::VoxelXUProgrammer::~VoxelXUProgrammer () inline virtual
Definition at line 53 of file VoxelXUProgrammer.h.
 {}
Member Function Documentation
bool Voxel::TI::VoxelXUProgrammer::_readRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t & value, uint8_t length) const protected virtual
Implements Voxel::TI::VoxelProgrammerBase.
Definition at line 49 of file VoxelXUProgrammer.cpp.
References _xu, Voxel::arraySize(), CONTROL_READ_REGISTER_1, CONTROL_READ_REGISTER_2, CONTROL_READ_REGISTER_3, CONTROL_SET_READ_REGISTER, Voxel::LOG_ERROR, and Voxel::logger.
 {
   uint8_t addr[2];
   addr[0] = slaveAddress;
   addr[1] = registerAddress;
   if(!_xu->setControl(CONTROL_SET_READ_REGISTER, arraySize(addr), addr))
   {
     logger(LOG_ERROR) << "VoxelXUProgrammer: Could not set read register address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
     return false;
   }
   if(length == 1) // TPS -- addr[0] == 0x2D
   {
     uint8_t data[1];
     data[0] = 0x0;
     if(!_xu->getControl(CONTROL_READ_REGISTER_1, arraySize(data), data))
     {
       logger(LOG_ERROR) << "VoxelXUProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
     value = data[0];
   }
   else if(length == 3) // ToF -- 0x58, 0x5C
   {
     uint8_t data[3];
     data[0] = 0x0;
     data[1] = 0x0;
     data[2] = 0x0;
     if(!_xu->getControl(CONTROL_READ_REGISTER_3, arraySize(data), data))
     {
       logger(LOG_ERROR) << "VoxelXUProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
     value = data[0] + (data[1] << 8) + (data[2] << 16);
   }
   else if(length == 2)
   {
     uint8_t data[2];
     data[0] = 0x0;
     data[1] = 0x0;
     if(!_xu->getControl(CONTROL_READ_REGISTER_2, arraySize(data), data))
     {
       logger(LOG_ERROR) << "VoxelXUProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
     value = data[0] + (data[1] << 8);
   }
   else
   {
     logger(LOG_ERROR) << "VoxelXUProgrammer: Don't know how to read '" << std::dec << length << "' bytes. Required for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::VoxelXUProgrammer::_writeRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t value, uint8_t length) protected virtual
Implements Voxel::TI::VoxelProgrammerBase.
Definition at line 111 of file VoxelXUProgrammer.cpp.
References _xu, Voxel::arraySize(), CONTROL_WRITE_REGISTER_1, CONTROL_WRITE_REGISTER_2, CONTROL_WRITE_REGISTER_3, Voxel::LOG_DEBUG, Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(length == 1) // TPS  -- slaveAddress == 0x2D
   {
     uint8_t data[3];
     data[0] = slaveAddress;
     data[1] = registerAddress;
     data[2] = value & 0xFF;
     if(!_xu->setControl(CONTROL_WRITE_REGISTER_1, arraySize(data), data))
     {
       logger(LOG_ERROR) << "VoxelXUProgrammer: Could not write register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
   }
   else if(length == 3) // ToF
   {
     uint8_t data[5];
     data[0] = slaveAddress;
     data[1] = registerAddress;
     data[2] = (value & 0xFF);
     data[3] = (value >> 8) & 0xFF;
     data[4] = (value >> 16) & 0xFF;
     if(!_xu->setControl(CONTROL_WRITE_REGISTER_3, arraySize(data), data))
     {
       logger(LOG_ERROR) << "VoxelXUProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
   }
   else if(length == 2)
   {
     uint8_t data[4];
     data[0] = slaveAddress;
     data[1] = registerAddress;
     data[2] = (value & 0xFF);
     data[3] = (value >> 8) & 0xFF;
     if(!_xu->setControl(CONTROL_WRITE_REGISTER_2, arraySize(data), data))
     {
       logger(LOG_ERROR) << "VoxelXUProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
   }
   else
   {
     logger(LOG_ERROR) << "VoxelXUProgrammer: Don't know how to write '" << std::dec << length << "' bytes. Required for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
     return false;
   }
   logger(LOG_DEBUG) << "VoxelXUProgrammer: register write @0x" << std::hex << slaveAddress << registerAddress << " = " << value << std::endl;
   return true;
 }
void Voxel::TI::VoxelXUProgrammer::init ()
Definition at line 22 of file VoxelXUProgrammer.cpp.
References Voxel::TI::VoxelProgrammerBase::_device, _majorVersion, _minorVersion, _xu, _XU_ID, Voxel::arraySize(), CONTROL_GET_VERSION, Voxel::LOG_INFO, Voxel::LOG_WARNING, and Voxel::logger.
Referenced by VoxelXUProgrammer().
 {
   _xu = UVCXUPtr(new UVCXU(_device, _XU_ID));
   uint8_t data[4];
   if (!_xu->getControl(CONTROL_GET_VERSION, arraySize(data), data))
   {
     logger(LOG_WARNING) << "VoxelXUProgrammer: Could not get XU version." << std::endl;
     return;
   }
   _minorVersion = data[0];
   _majorVersion = data[1];
   logger(LOG_INFO) << "VoxelXUProgrammer: XU controller version " << (int)_majorVersion << "." << (int)_minorVersion << std::endl;
 }
bool Voxel::TI::VoxelXUProgrammer::isInitialized () const virtual
Implements Voxel::RegisterProgrammer.
Definition at line 17 of file VoxelXUProgrammer.cpp.
References _xu.
Referenced by reset().
 {
   return (bool)_xu;
 }
bool Voxel::TI::VoxelXUProgrammer::reset () virtual
Implements Voxel::RegisterProgrammer.
Definition at line 164 of file VoxelXUProgrammer.cpp.
References _xu, Voxel::arraySize(), CONTROL_REBOOT_FW_MODE, isInitialized(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::TI::TintinEEPROMDownloader::_configureForDownload().
 {
   if(!isInitialized())
     return false;
   uint8_t data[1];
   if(!_xu->setControl(CONTROL_REBOOT_FW_MODE, arraySize(data), data))
   {
     logger(LOG_ERROR) << "VoxelXUProgrammer: Could not reset the device." << std::endl;
     return false;
   }
   return true;
 }
Member Data Documentation
uint8_t Voxel::TI::VoxelXUProgrammer::_majorVersion protected
Definition at line 26 of file VoxelXUProgrammer.h.
Referenced by init().
uint8_t Voxel::TI::VoxelXUProgrammer::_minorVersion protected
Definition at line 26 of file VoxelXUProgrammer.h.
Referenced by init().
UVCXUPtr Voxel::TI::VoxelXUProgrammer::_xu protected
Definition at line 22 of file VoxelXUProgrammer.h.
Referenced by _readRegister(), _writeRegister(), init(), isInitialized(), and reset().
const int Voxel::TI::VoxelXUProgrammer::_XU_ID = 3 protected
Definition at line 24 of file VoxelXUProgrammer.h.
Referenced by init().
The documentation for this class was generated from the following files:
VoxelXUProgrammer.h
VoxelXUProgrammer.cpp