Voxel: DeviceTest.cpp File Reference
DeviceTest.cpp File Reference
#include "Device.h"
#include "Logger.h"
#include "USBSystem.h"
Functions
int main ()
Function Documentation
int main ()
Definition at line 13 of file DeviceTest.cpp.
References CameraSystemTest::devices, Voxel::USBSystem::getDeviceNode(), Voxel::LOG_ERROR, Voxel::logger, Voxel::DeviceScanner::scan(), Voxel::Logger::setDefaultLogLevel(), and Voxel::Device::USB.
 {
   logger.setDefaultLogLevel(LOG_ERROR);
   Vector<DevicePtr> devices = DeviceScanner::scan();
   USBSystem usbsys;
   for(auto i = 0; i < devices.size(); i++)
   {
     String devNode;
     if(devices[i]->interfaceID() == Device::USB)
       devNode = usbsys.getDeviceNode((USBDevice &)*devices[i]);
     std::cout << devices[i]->id() << " -- " << devices[i]->description();
     if(devNode.size() > 0)
     {
       std::cout << " (" << devNode << ")";
     }
     std::cout << std::endl;
   }
   return 0;
 }