Voxel: TinyXML2::XMLText Class Reference
TinyXML2::XMLText Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
virtual bool Accept (XMLVisitor *visitor) const
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual const XMLText * ToText () const
void SetCData (bool isCData)
Declare whether this should be CDATA or standard text.
bool CData () const
Returns true if this is a CDATA text element.
char * ParseDeep (char *, StrPair *endTag)
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from TinyXML2::XMLNode
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
Protected Member Functions
XMLText (XMLDocument *doc)
virtual ~XMLText ()
XMLText (const XMLText &)
XMLText & operator= (const XMLText &)
Protected Member Functions inherited from TinyXML2::XMLNode
XMLNode (XMLDocument *)
virtual ~XMLNode ()
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Private Attributes
bool _isCData
Friends
class XMLBase
class XMLDocument
Additional Inherited Members
Protected Attributes inherited from TinyXML2::XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Detailed Description
XML text.
Note that a text node can have child element nodes, for example:
<root>This is <b>bold</b></root>
A text node can have 2 ways to output the next. "normal" output and CDATA. It will default to the mode it was parsed from the XML file and you generally want to leave it alone, but you can change the output mode with SetCData() and query it with CData().
Definition at line 924 of file TinyXML2.h.
Constructor & Destructor Documentation
TinyXML2::XMLText::XMLText (XMLDocument * doc) inline protected
Definition at line 952 of file TinyXML2.h.
 : XMLNode( doc ), _isCData( false ) {}
virtual TinyXML2::XMLText::~XMLText () inline protected virtual
Definition at line 953 of file TinyXML2.h.
 {}
TinyXML2::XMLText::XMLText (const XMLText &) protected
Member Function Documentation
bool TinyXML2::XMLText::Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements TinyXML2::XMLNode.
Definition at line 961 of file TinyXML2.cpp.
References TIXMLASSERT, and TinyXML2::XMLVisitor::Visit().
 {
     TIXMLASSERT( visitor );
     return visitor->Visit( *this );
 }
bool TinyXML2::XMLText::CData () const inline
Returns true if this is a CDATA text element.
Definition at line 943 of file TinyXML2.h.
Referenced by ParseDeep(), ShallowClone(), and TinyXML2::XMLPrinter::Visit().
{
         return _isCData;
     }
XMLText& TinyXML2::XMLText::operator= (const XMLText &) protected
char * TinyXML2::XMLText::ParseDeep (char * p, StrPair * endTag) virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 915 of file TinyXML2.cpp.
References TinyXML2::XMLNode::_document, TinyXML2::XMLNode::_value, CData(), TinyXML2::StrPair::COLLAPSE_WHITESPACE, TinyXML2::COLLAPSE_WHITESPACE, TinyXML2::StrPair::NEEDS_NEWLINE_NORMALIZATION, TinyXML2::StrPair::ParseText(), TinyXML2::XMLDocument::ProcessEntities(), TinyXML2::XMLDocument::SetError(), TinyXML2::StrPair::TEXT_ELEMENT, TinyXML2::StrPair::TEXT_ELEMENT_LEAVE_ENTITIES, TinyXML2::XMLDocument::WhitespaceMode(), TinyXML2::XML_ERROR_PARSING_CDATA, and TinyXML2::XML_ERROR_PARSING_TEXT.
 {
     const char* start = p;
     if ( this->CData() ) {
         p = _value.ParseText( p, "]]>", StrPair::NEEDS_NEWLINE_NORMALIZATION );
         if ( !p ) {
             _document->SetError( XML_ERROR_PARSING_CDATA, start, 0 );
         }
         return p;
     }
     else {
         int flags = _document->ProcessEntities() ? StrPair::TEXT_ELEMENT : StrPair::TEXT_ELEMENT_LEAVE_ENTITIES;
         if ( _document->WhitespaceMode() == COLLAPSE_WHITESPACE ) {
             flags |= StrPair::COLLAPSE_WHITESPACE;
         }
         p = _value.ParseText( p, "<", flags );
         if ( !p ) {
             _document->SetError( XML_ERROR_PARSING_TEXT, start, 0 );
         }
         if ( p && *p ) {
             return p-1;
         }
     }
     return 0;
 }
void TinyXML2::XMLText::SetCData (bool isCData) inline
Declare whether this should be CDATA or standard text.
Definition at line 939 of file TinyXML2.h.
Referenced by TinyXML2::XMLDocument::Identify(), and ShallowClone().
{
         _isCData = isCData;
     }
XMLNode * TinyXML2::XMLText::ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements TinyXML2::XMLNode.
Definition at line 943 of file TinyXML2.cpp.
References TinyXML2::XMLNode::_document, CData(), TinyXML2::XMLDocument::NewText(), SetCData(), and TinyXML2::XMLNode::Value().
 {
     if ( !doc ) {
         doc = _document;
     }
     XMLText* text = doc->NewText( Value() );  // fixme: this will always allocate memory. Intern?
     text->SetCData( this->CData() );
     return text;
 }
bool TinyXML2::XMLText::ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements TinyXML2::XMLNode.
Definition at line 954 of file TinyXML2.cpp.
References TinyXML2::XMLUtil::StringEqual(), TinyXML2::XMLNode::ToText(), and TinyXML2::XMLNode::Value().
 {
     const XMLText* text = compare->ToText();
     return ( text && XMLUtil::StringEqual( text->Value(), Value() ) );
 }
virtual XMLText* TinyXML2::XMLText::ToText () inline virtual
Safely cast to Text, or null.
Reimplemented from TinyXML2::XMLNode.
Definition at line 931 of file TinyXML2.h.
{
         return this;
     }
virtual const XMLText* TinyXML2::XMLText::ToText () const inline virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 934 of file TinyXML2.h.
{
         return this;
     }
Friends And Related Function Documentation
friend class XMLBase friend
Definition at line 926 of file TinyXML2.h.
friend class XMLDocument friend
Definition at line 927 of file TinyXML2.h.
Member Data Documentation
bool TinyXML2::XMLText::_isCData private
Definition at line 958 of file TinyXML2.h.
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp