Voxel: TinyXML2::XMLPrinter Class Reference
TinyXML2::XMLPrinter Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
XMLPrinter (FILE *file=0, bool compact=false, int depth=0)
virtual ~XMLPrinter ()
void PushHeader (bool writeBOM, bool writeDeclaration)
void OpenElement (const char *name, bool compactMode=false)
void PushAttribute (const char *name, const char *value)
If streaming, add an attribute to an open element.
void PushAttribute (const char *name, int value)
void PushAttribute (const char *name, unsigned value)
void PushAttribute (const char *name, bool value)
void PushAttribute (const char *name, double value)
virtual void CloseElement (bool compactMode=false)
If streaming, close the Element.
void PushText (const char *text, bool cdata=false)
Add a text node.
void PushText (int value)
Add a text node from an integer.
void PushText (unsigned value)
Add a text node from an unsigned.
void PushText (bool value)
Add a text node from a bool.
void PushText (float value)
Add a text node from a float.
void PushText (double value)
Add a text node from a double.
void PushComment (const char *comment)
Add a comment.
void PushDeclaration (const char *value)
void PushUnknown (const char *value)
virtual bool VisitEnter (const XMLDocument &)
Visit a document.
virtual bool VisitExit (const XMLDocument &)
Visit a document.
virtual bool VisitEnter (const XMLElement &element, const XMLAttribute *attribute)
Visit an element.
virtual bool VisitExit (const XMLElement &element)
Visit an element.
virtual bool Visit (const XMLText &text)
Visit a text node.
virtual bool Visit (const XMLComment &comment)
Visit a comment node.
virtual bool Visit (const XMLDeclaration &declaration)
Visit a declaration.
virtual bool Visit (const XMLUnknown &unknown)
Visit an unknown node.
const char * CStr () const
int CStrSize () const
void ClearBuffer ()
Public Member Functions inherited from TinyXML2::XMLVisitor
virtual ~XMLVisitor ()
Protected Member Functions
virtual bool CompactMode (const XMLElement &)
virtual void PrintSpace (int depth)
void Print (const char *format,...)
void SealElement ()
Protected Attributes
bool _elementJustOpened
DynArray< const char *, 10 > _stack
Private Types
enum { ENTITY_RANGE = 64, BUF_SIZE = 200 }
Private Member Functions
void PrintString (const char *, bool restrictedEntitySet)
Private Attributes
bool _firstElement
FILE * _fp
int _depth
int _textDepth
bool _processEntities
bool _compactMode
bool _entityFlag [ENTITY_RANGE]
bool _restrictedEntityFlag [ENTITY_RANGE]
DynArray< char, 20 > _buffer
Detailed Description
Printing functionality. The XMLPrinter gives you more options than the XMLDocument::Print() method.
It can:
Print to memory.
Print to a file you provide.
Print XML without a XMLDocument.
Print to Memory
XMLPrinter printer;
doc.Print(&printer);
SomeFunction(printer.CStr());
Print to a File
You provide the file pointer.
XMLPrinter printer(fp);
doc.Print(&printer);
Print without a XMLDocument
When loading, an XML parser is very useful. However, sometimes when saving, it just gets in the way. The code is often set up for streaming, and constructing the DOM is just overhead.
The Printer supports the streaming case. The following code prints out a trivially simple XML file without ever creating an XML document.
XMLPrinter printer(fp);
printer.OpenElement("foo");
printer.PushAttribute("foo", "bar");
printer.CloseElement();
Definition at line 1994 of file TinyXML2.h.
Member Enumeration Documentation
anonymous enum private
Enumerator
ENTITY_RANGE
BUF_SIZE
Definition at line 2100 of file TinyXML2.h.
          {
         ENTITY_RANGE = 64,
         BUF_SIZE = 200
     };
Constructor & Destructor Documentation
TinyXML2::XMLPrinter::XMLPrinter (FILE * file = 0, bool compact = false, int depth = 0)
Construct the printer. If the FILE* is specified, this will print to the FILE. Else it will print to memory, and the result is available in CStr(). If 'compact' is set to true, then output is created with only required whitespace and newlines.
Definition at line 1923 of file TinyXML2.cpp.
References _buffer, _entityFlag, _restrictedEntityFlag, ENTITY_RANGE, TinyXML2::DynArray< T, INIT >::Push(), and TIXMLASSERT.
                                                             :
     _elementJustOpened( false ),
     _firstElement( true ),
     _fp( file ),
     _depth( depth ),
     _textDepth( -1 ),
     _processEntities( true ),
     _compactMode( compact )
 {
     for( int i=0; i<ENTITY_RANGE; ++i ) {
         _entityFlag[i] = false;
         _restrictedEntityFlag[i] = false;
     }
     for( int i=0; i<NUM_ENTITIES; ++i ) {
         TIXMLASSERT( entities[i].value < ENTITY_RANGE );
         if ( entities[i].value < ENTITY_RANGE ) {
             _entityFlag[ (int)entities[i].value ] = true;
         }
     }
     _restrictedEntityFlag[(int)'&'] = true;
     _restrictedEntityFlag[(int)'<'] = true;
     _restrictedEntityFlag[(int)'>'] = true; // not required, but consistency is nice
     _buffer.Push( 0 );
 }
virtual TinyXML2::XMLPrinter::~XMLPrinter () inline virtual
Definition at line 2004 of file TinyXML2.h.
 {}
Member Function Documentation
void TinyXML2::XMLPrinter::ClearBuffer () inline
If in print to memory mode, reset the buffer to the beginning.
Definition at line 2072 of file TinyXML2.h.
{
         _buffer.Clear();
         _buffer.Push(0);
     }
void TinyXML2::XMLPrinter::CloseElement (bool compactMode = false) virtual
If streaming, close the Element.
Definition at line 2111 of file TinyXML2.cpp.
References _depth, _elementJustOpened, _stack, _textDepth, TinyXML2::DynArray< T, INIT >::Pop(), Print(), and PrintSpace().
Referenced by VisitExit().
 {
     --_depth;
     const char* name = _stack.Pop();
     if ( _elementJustOpened ) {
         Print( "/>" );
     }
     else {
         if ( _textDepth < 0 && !compactMode) {
             Print( "\n" );
             PrintSpace( _depth );
         }
         Print( "</%s>", name );
     }
     if ( _textDepth == _depth ) {
         _textDepth = -1;
     }
     if ( _depth == 0 && !compactMode) {
         Print( "\n" );
     }
     _elementJustOpened = false;
 }
virtual bool TinyXML2::XMLPrinter::CompactMode (const XMLElement &) inline protected virtual
Definition at line 2078 of file TinyXML2.h.
Referenced by VisitEnter(), and VisitExit().
 { return _compactMode; }
const char* TinyXML2::XMLPrinter::CStr () const inline
If in print to memory mode, return a pointer to the XML file in memory.
Definition at line 2057 of file TinyXML2.h.
{
         return _buffer.Mem();
     }
int TinyXML2::XMLPrinter::CStrSize () const inline
If in print to memory mode, return the size of the XML file in memory. (Note the size returned includes the terminating null.)
Definition at line 2065 of file TinyXML2.h.
{
         return _buffer.Size();
     }
void TinyXML2::XMLPrinter::OpenElement (const char * name, bool compactMode = false)
If streaming, start writing an element. The element must be closed with CloseElement()
Definition at line 2049 of file TinyXML2.cpp.
References _depth, _elementJustOpened, _firstElement, _stack, _textDepth, Print(), PrintSpace(), TinyXML2::DynArray< T, INIT >::Push(), and SealElement().
Referenced by VisitEnter().
 {
     if ( _elementJustOpened ) {
         SealElement();
     }
     _stack.Push( name );
     if ( _textDepth < 0 && !_firstElement && !compactMode ) {
         Print( "\n" );
     }
     if ( !compactMode ) {
         PrintSpace( _depth );
     }
     Print( "<%s", name );
     _elementJustOpened = true;
     _firstElement = false;
     ++_depth;
 }
void TinyXML2::XMLPrinter::Print (const char * format, ...) protected
Definition at line 1949 of file TinyXML2.cpp.
References _buffer, _fp, and TinyXML2::DynArray< T, INIT >::PushArr().
Referenced by CloseElement(), OpenElement(), PrintSpace(), PrintString(), PushAttribute(), PushComment(), PushDeclaration(), PushHeader(), PushText(), PushUnknown(), and SealElement().
 {
     va_list     va;
     va_start( va, format );
     if ( _fp ) {
         vfprintf( _fp, format, va );
     }
     else {
 #if defined(_MSC_VER) && (_MSC_VER >= 1400 )
     #if defined(WINCE)
     int len = 512;
     do {
         len = len*2;
         char* str = new char[len]();
       len = _vsnprintf(str, len, format, va);
       delete[] str;
     }while (len < 0);
     #else
         int len = _vscprintf( format, va );
     #endif
 #else
         int len = vsnprintf( 0, 0, format, va );
 #endif
         // Close out and re-start the va-args
         va_end( va );
         va_start( va, format );
         char* p = _buffer.PushArr( len ) - 1; // back up over the null terminator.
 #if defined(_MSC_VER) && (_MSC_VER >= 1400 )
     #if defined(WINCE)
     _vsnprintf( p, len+1, format, va );
     #else
     vsnprintf_s( p, len+1, _TRUNCATE, format, va );
     #endif
 #else
     vsnprintf( p, len+1, format, va );
 #endif
     }
     va_end( va );
 }
void TinyXML2::XMLPrinter::PrintSpace (int depth) protected virtual
Prints out the space before an element. You may override to change the space and tabs used. A PrintSpace() override should call Print().
Definition at line 1991 of file TinyXML2.cpp.
References Print().
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
 {
     for( int i=0; i<depth; ++i ) {
         Print( "    " );
     }
 }
void TinyXML2::XMLPrinter::PrintString (const char * p, bool restrictedEntitySet) private
Definition at line 1999 of file TinyXML2.cpp.
References _entityFlag, _processEntities, _restrictedEntityFlag, ENTITY_RANGE, and Print().
Referenced by PushAttribute(), and PushText().
 {
     // Look for runs of bytes between entities to print.
     const char* q = p;
     const bool* flag = restricted ? _restrictedEntityFlag : _entityFlag;
     if ( _processEntities ) {
         while ( *q ) {
             // Remember, char is sometimes signed. (How many times has that bitten me?)
             if ( *q > 0 && *q < ENTITY_RANGE ) {
                 // Check for entities. If one is found, flush
                 // the stream up until the entity, write the
                 // entity, and keep looking.
                 if ( flag[(unsigned)(*q)] ) {
                     while ( p < q ) {
                         Print( "%c", *p );
                         ++p;
                     }
                     for( int i=0; i<NUM_ENTITIES; ++i ) {
                         if ( entities[i].value == *q ) {
                             Print( "&%s;", entities[i].pattern );
                             break;
                         }
                     }
                     ++p;
                 }
             }
             ++q;
         }
     }
     // Flush the remaining string. This will be the entire
     // string if an entity wasn't found.
     if ( !_processEntities || (q-p > 0) ) {
         Print( "%s", p );
     }
 }
void TinyXML2::XMLPrinter::PushAttribute (const char * name, const char * value)
If streaming, add an attribute to an open element.
Definition at line 2070 of file TinyXML2.cpp.
References _elementJustOpened, Print(), PrintString(), and TIXMLASSERT.
Referenced by PushAttribute(), and VisitEnter().
 {
     TIXMLASSERT( _elementJustOpened );
     Print( " %s=\"", name );
     PrintString( value, false );
     Print( "\"" );
 }
void TinyXML2::XMLPrinter::PushAttribute (const char * name, int value)
Definition at line 2079 of file TinyXML2.cpp.
References BUF_SIZE, PushAttribute(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     PushAttribute( name, buf );
 }
void TinyXML2::XMLPrinter::PushAttribute (const char * name, unsigned value)
Definition at line 2087 of file TinyXML2.cpp.
References BUF_SIZE, PushAttribute(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     PushAttribute( name, buf );
 }
void TinyXML2::XMLPrinter::PushAttribute (const char * name, bool value)
Definition at line 2095 of file TinyXML2.cpp.
References BUF_SIZE, PushAttribute(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     PushAttribute( name, buf );
 }
void TinyXML2::XMLPrinter::PushAttribute (const char * name, double value)
Definition at line 2103 of file TinyXML2.cpp.
References BUF_SIZE, PushAttribute(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     PushAttribute( name, buf );
 }
void TinyXML2::XMLPrinter::PushComment (const char * comment)
Add a comment.
Definition at line 2201 of file TinyXML2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _textDepth, Print(), PrintSpace(), and SealElement().
Referenced by Visit().
 {
     if ( _elementJustOpened ) {
         SealElement();
     }
     if ( _textDepth < 0 && !_firstElement && !_compactMode) {
         Print( "\n" );
         PrintSpace( _depth );
     }
     _firstElement = false;
     Print( "<!--%s-->", comment );
 }
void TinyXML2::XMLPrinter::PushDeclaration (const char * value)
Definition at line 2215 of file TinyXML2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _textDepth, Print(), PrintSpace(), and SealElement().
Referenced by PushHeader(), and Visit().
 {
     if ( _elementJustOpened ) {
         SealElement();
     }
     if ( _textDepth < 0 && !_firstElement && !_compactMode) {
         Print( "\n" );
         PrintSpace( _depth );
     }
     _firstElement = false;
     Print( "<?%s?>", value );
 }
void TinyXML2::XMLPrinter::PushHeader (bool writeBOM, bool writeDeclaration)
If streaming, write the BOM and declaration.
Definition at line 2037 of file TinyXML2.cpp.
References Print(), and PushDeclaration().
Referenced by VisitEnter().
 {
     if ( writeBOM ) {
         static const unsigned char bom[] = { TIXML_UTF_LEAD_0, TIXML_UTF_LEAD_1, TIXML_UTF_LEAD_2, 0 };
         Print( "%s", bom );
     }
     if ( writeDec ) {
         PushDeclaration( "xml version=\"1.0\"" );
     }
 }
void TinyXML2::XMLPrinter::PushText (const char * text, bool cdata = false)
Add a text node.
Definition at line 2144 of file TinyXML2.cpp.
References _depth, _elementJustOpened, _textDepth, Print(), PrintString(), and SealElement().
Referenced by PushText(), and Visit().
 {
     _textDepth = _depth-1;
     if ( _elementJustOpened ) {
         SealElement();
     }
     if ( cdata ) {
         Print( "<![CDATA[" );
         Print( "%s", text );
         Print( "]]>" );
     }
     else {
         PrintString( text, true );
     }
 }
void TinyXML2::XMLPrinter::PushText (int value)
Add a text node from an integer.
Definition at line 2161 of file TinyXML2.cpp.
References BUF_SIZE, PushText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( value, buf, BUF_SIZE );
     PushText( buf, false );
 }
void TinyXML2::XMLPrinter::PushText (unsigned value)
Add a text node from an unsigned.
Definition at line 2169 of file TinyXML2.cpp.
References BUF_SIZE, PushText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( value, buf, BUF_SIZE );
     PushText( buf, false );
 }
void TinyXML2::XMLPrinter::PushText (bool value)
Add a text node from a bool.
Definition at line 2177 of file TinyXML2.cpp.
References BUF_SIZE, PushText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( value, buf, BUF_SIZE );
     PushText( buf, false );
 }
void TinyXML2::XMLPrinter::PushText (float value)
Add a text node from a float.
Definition at line 2185 of file TinyXML2.cpp.
References BUF_SIZE, PushText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( value, buf, BUF_SIZE );
     PushText( buf, false );
 }
void TinyXML2::XMLPrinter::PushText (double value)
Add a text node from a double.
Definition at line 2193 of file TinyXML2.cpp.
References BUF_SIZE, PushText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( value, buf, BUF_SIZE );
     PushText( buf, false );
 }
void TinyXML2::XMLPrinter::PushUnknown (const char * value)
Definition at line 2229 of file TinyXML2.cpp.
References _compactMode, _depth, _elementJustOpened, _firstElement, _textDepth, Print(), PrintSpace(), and SealElement().
Referenced by Visit().
 {
     if ( _elementJustOpened ) {
         SealElement();
     }
     if ( _textDepth < 0 && !_firstElement && !_compactMode) {
         Print( "\n" );
         PrintSpace( _depth );
     }
     _firstElement = false;
     Print( "<!%s>", value );
 }
void TinyXML2::XMLPrinter::SealElement () protected
Definition at line 2137 of file TinyXML2.cpp.
References _elementJustOpened, and Print().
Referenced by OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
 {
     _elementJustOpened = false;
     Print( ">" );
 }
bool TinyXML2::XMLPrinter::Visit (const XMLText &) virtual
Visit a text node.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2273 of file TinyXML2.cpp.
References TinyXML2::XMLText::CData(), PushText(), and TinyXML2::XMLNode::Value().
 {
     PushText( text.Value(), text.CData() );
     return true;
 }
bool TinyXML2::XMLPrinter::Visit (const XMLComment &) virtual
Visit a comment node.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2280 of file TinyXML2.cpp.
References PushComment(), and TinyXML2::XMLNode::Value().
 {
     PushComment( comment.Value() );
     return true;
 }
bool TinyXML2::XMLPrinter::Visit (const XMLDeclaration &) virtual
Visit a declaration.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2286 of file TinyXML2.cpp.
References PushDeclaration(), and TinyXML2::XMLNode::Value().
 {
     PushDeclaration( declaration.Value() );
     return true;
 }
bool TinyXML2::XMLPrinter::Visit (const XMLUnknown &) virtual
Visit an unknown node.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2293 of file TinyXML2.cpp.
References PushUnknown(), and TinyXML2::XMLNode::Value().
 {
     PushUnknown( unknown.Value() );
     return true;
 }
bool TinyXML2::XMLPrinter::VisitEnter (const XMLDocument &) virtual
Visit a document.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2243 of file TinyXML2.cpp.
References _processEntities, TinyXML2::XMLDocument::HasBOM(), TinyXML2::XMLDocument::ProcessEntities(), and PushHeader().
 {
     _processEntities = doc.ProcessEntities();
     if ( doc.HasBOM() ) {
         PushHeader( true, false );
     }
     return true;
 }
bool TinyXML2::XMLPrinter::VisitEnter (const XMLElement & , const XMLAttribute *) virtual
Visit an element.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2253 of file TinyXML2.cpp.
References _compactMode, CompactMode(), TinyXML2::XMLAttribute::Name(), TinyXML2::XMLElement::Name(), TinyXML2::XMLAttribute::Next(), OpenElement(), TinyXML2::XMLNode::Parent(), PushAttribute(), TinyXML2::XMLNode::ToElement(), and TinyXML2::XMLAttribute::Value().
 {
   const XMLElement* parentElem = element.Parent()->ToElement();
   bool    compactMode = parentElem ? CompactMode(*parentElem) : _compactMode;
     OpenElement( element.Name(), compactMode );
     while ( attribute ) {
         PushAttribute( attribute->Name(), attribute->Value() );
         attribute = attribute->Next();
     }
     return true;
 }
virtual bool TinyXML2::XMLPrinter::VisitExit (const XMLDocument &) inline virtual
Visit a document.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2041 of file TinyXML2.h.
{
         return true;
     }
bool TinyXML2::XMLPrinter::VisitExit (const XMLElement &) virtual
Visit an element.
Reimplemented from TinyXML2::XMLVisitor.
Definition at line 2266 of file TinyXML2.cpp.
References CloseElement(), and CompactMode().
 {
     CloseElement( CompactMode(element) );
     return true;
 }
Member Data Documentation
DynArray< char, 20 > TinyXML2::XMLPrinter::_buffer private
Definition at line 2107 of file TinyXML2.h.
Referenced by Print(), and XMLPrinter().
bool TinyXML2::XMLPrinter::_compactMode private
Definition at line 2098 of file TinyXML2.h.
Referenced by PushComment(), PushDeclaration(), PushUnknown(), and VisitEnter().
int TinyXML2::XMLPrinter::_depth private
Definition at line 2095 of file TinyXML2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
bool TinyXML2::XMLPrinter::_elementJustOpened protected
Definition at line 2087 of file TinyXML2.h.
Referenced by CloseElement(), OpenElement(), PushAttribute(), PushComment(), PushDeclaration(), PushText(), PushUnknown(), and SealElement().
bool TinyXML2::XMLPrinter::_entityFlag[ENTITY_RANGE] private
Definition at line 2104 of file TinyXML2.h.
Referenced by PrintString(), and XMLPrinter().
bool TinyXML2::XMLPrinter::_firstElement private
Definition at line 2093 of file TinyXML2.h.
Referenced by OpenElement(), PushComment(), PushDeclaration(), and PushUnknown().
FILE* TinyXML2::XMLPrinter::_fp private
Definition at line 2094 of file TinyXML2.h.
Referenced by Print().
bool TinyXML2::XMLPrinter::_processEntities private
Definition at line 2097 of file TinyXML2.h.
Referenced by PrintString(), and VisitEnter().
bool TinyXML2::XMLPrinter::_restrictedEntityFlag[ENTITY_RANGE] private
Definition at line 2105 of file TinyXML2.h.
Referenced by PrintString(), and XMLPrinter().
DynArray< const char*, 10 > TinyXML2::XMLPrinter::_stack protected
Definition at line 2088 of file TinyXML2.h.
Referenced by CloseElement(), and OpenElement().
int TinyXML2::XMLPrinter::_textDepth private
Definition at line 2096 of file TinyXML2.h.
Referenced by CloseElement(), OpenElement(), PushComment(), PushDeclaration(), PushText(), and PushUnknown().
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp