Voxel: TinyXML2::XMLNode Class Reference
TinyXML2::XMLNode Class Reference abstract
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
virtual XMLNode * ShallowClone (XMLDocument *document) const =0
virtual bool ShallowEqual (const XMLNode *compare) const =0
virtual bool Accept (XMLVisitor *visitor) const =0
virtual char * ParseDeep (char *, StrPair *)
Protected Member Functions
XMLNode (XMLDocument *)
virtual ~XMLNode ()
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Protected Attributes
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Private Member Functions
void Unlink (XMLNode *child)
Static Private Member Functions
static void DeleteNode (XMLNode *node)
Private Attributes
MemPool * _memPool
Friends
class XMLDocument
class XMLElement
Detailed Description
XMLNode is a base class for every object that is in the XML Document Object Model (DOM), except XMLAttributes. Nodes have siblings, a parent, and children which can be navigated. A node is always in a XMLDocument. The type of a XMLNode can be queried, and it can be cast to its more defined type.
A XMLDocument allocates memory for all its Nodes. When the XMLDocument gets deleted, all its Nodes will also be deleted.
A Document can contain: Element (container or leaf)
            Comment (leaf)
            Unknown (leaf)
            Declaration( leaf )
An Element can contain: Element (container or leaf)
            Text  (leaf)
            Attributes (not on tree)
            Comment (leaf)
            Unknown (leaf)
Definition at line 646 of file TinyXML2.h.
Constructor & Destructor Documentation
TinyXML2::XMLNode::XMLNode (XMLDocument * doc) protected
Definition at line 594 of file TinyXML2.cpp.
                                    :
     _document( doc ),
     _parent( 0 ),
     _firstChild( 0 ), _lastChild( 0 ),
     _prev( 0 ), _next( 0 ),
     _memPool( 0 )
 {
 }
TinyXML2::XMLNode::~XMLNode () protected virtual
Definition at line 604 of file TinyXML2.cpp.
References _parent, DeleteChildren(), and Unlink().
Referenced by DeleteNode().
 {
     DeleteChildren();
     if ( _parent ) {
         _parent->Unlink( this );
     }
 }
TinyXML2::XMLNode::XMLNode (const XMLNode &) protected
Member Function Documentation
virtual bool TinyXML2::XMLNode::Accept (XMLVisitor * visitor) const pure virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implemented in TinyXML2::XMLDocument, TinyXML2::XMLElement, TinyXML2::XMLUnknown, TinyXML2::XMLDeclaration, TinyXML2::XMLComment, and TinyXML2::XMLText.
void TinyXML2::XMLNode::DeleteChild (XMLNode * node)
Delete a child of this node.
Definition at line 661 of file TinyXML2.cpp.
References _document, _parent, DeleteNode(), and TIXMLASSERT.
Referenced by TinyXML2::XMLDocument::DeleteNode().
 {
     TIXMLASSERT( node->_document == _document );
     TIXMLASSERT( node->_parent == this );
     DeleteNode( node );
 }
void TinyXML2::XMLNode::DeleteChildren ()
Delete all the children of this node.
Definition at line 628 of file TinyXML2.cpp.
References _document, _firstChild, _lastChild, DeleteNode(), TIXMLASSERT, and Unlink().
Referenced by TinyXML2::XMLDocument::Clear(), TinyXML2::XMLDocument::Parse(), and ~XMLNode().
 {
     while( _firstChild ) {
         TIXMLASSERT( _firstChild->_document == _document );
         XMLNode* node = _firstChild;
         Unlink( node );
         DeleteNode( node );
     }
     _firstChild = _lastChild = 0;
 }
void TinyXML2::XMLNode::DeleteNode (XMLNode * node) static private
Definition at line 904 of file TinyXML2.cpp.
References _memPool, TinyXML2::MemPool::Free(), and ~XMLNode().
Referenced by DeleteChild(), DeleteChildren(), and ParseDeep().
 {
     if ( node == 0 ) {
         return;
     }
     MemPool* pool = node->_memPool;
     node->~XMLNode();
     pool->Free( node );
 }
const XMLNode* TinyXML2::XMLNode::FirstChild () const inline
Get the first child node, or null if none exists.
Definition at line 736 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::Accept(), TinyXML2::XMLDocument::Accept(), TinyXML2::XMLElement::GetText(), TinyXML2::XMLElement::QueryBoolText(), TinyXML2::XMLElement::QueryDoubleText(), TinyXML2::XMLElement::QueryFloatText(), TinyXML2::XMLElement::QueryIntText(), TinyXML2::XMLElement::QueryUnsignedText(), and TinyXML2::XMLElement::SetText().
{
         return _firstChild;
     }
XMLNode* TinyXML2::XMLNode::FirstChild () inline
Definition at line 740 of file TinyXML2.h.
{
         return _firstChild;
     }
const XMLElement * TinyXML2::XMLNode::FirstChildElement (const char * value = 0) const
Get the first child element, or optionally the first child element with the specified name.
Definition at line 770 of file TinyXML2.cpp.
References _firstChild, _next, TinyXML2::XMLElement::Name(), TinyXML2::XMLUtil::StringEqual(), and TinyXML2::XMLElement::ToElement().
Referenced by Voxel::ParameterDMLParser::_goTo(), Voxel::ParameterDMLParser::_prepare(), and Voxel::ParameterDMLParser::getParameters().
 {
     for( XMLNode* node=_firstChild; node; node=node->_next ) {
         XMLElement* element = node->ToElement();
         if ( element ) {
             if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                 return element;
             }
         }
     }
     return 0;
 }
XMLElement* TinyXML2::XMLNode::FirstChildElement (const char * value = 0) inline
Definition at line 749 of file TinyXML2.h.
{
         return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->FirstChildElement( value ));
     }
const XMLDocument* TinyXML2::XMLNode::GetDocument () const inline
Get the XMLDocument that owns this XMLNode.
Definition at line 653 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::SetText().
{
         return _document;
     }
XMLDocument* TinyXML2::XMLNode::GetDocument () inline
Get the XMLDocument that owns this XMLNode.
Definition at line 657 of file TinyXML2.h.
{
         return _document;
     }
XMLNode * TinyXML2::XMLNode::InsertAfterChild (XMLNode * afterThis, XMLNode * addThis)
Add a node after the specified child node. If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the afterThis node is not a child of this node, or if the node does not belong to the same document.
Definition at line 736 of file TinyXML2.cpp.
References _document, _memPool, _next, _parent, _prev, InsertEndChild(), TinyXML2::MemPool::SetTracked(), TIXMLASSERT, and Unlink().
 {
     TIXMLASSERT( addThis );
     if ( addThis->_document != _document ) {
         TIXMLASSERT( false );
         return 0;
     }
     TIXMLASSERT( afterThis );
     if ( afterThis->_parent != this ) {
         TIXMLASSERT( false );
         return 0;
     }
     if ( afterThis->_next == 0 ) {
         // The last node or the only node.
         return InsertEndChild( addThis );
     }
   if (addThis->_parent)
     addThis->_parent->Unlink( addThis );
   else
      addThis->_memPool->SetTracked();
     addThis->_prev = afterThis;
     addThis->_next = afterThis->_next;
     afterThis->_next->_prev = addThis;
     afterThis->_next = addThis;
     addThis->_parent = this;
     return addThis;
 }
XMLNode * TinyXML2::XMLNode::InsertEndChild (XMLNode * addThis)
Add a child node as the last (right) child. If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the node does not belong to the same document.
Definition at line 669 of file TinyXML2.cpp.
References _document, _firstChild, _lastChild, _memPool, _next, _parent, _prev, TinyXML2::MemPool::SetTracked(), TIXMLASSERT, and Unlink().
Referenced by InsertAfterChild(), and ParseDeep().
 {
     if ( addThis->_document != _document ) {
         TIXMLASSERT( false );
         return 0;
     }
   if (addThis->_parent)
     addThis->_parent->Unlink( addThis );
   else
      addThis->_memPool->SetTracked();
     if ( _lastChild ) {
         TIXMLASSERT( _firstChild );
         TIXMLASSERT( _lastChild->_next == 0 );
         _lastChild->_next = addThis;
         addThis->_prev = _lastChild;
         _lastChild = addThis;
         addThis->_next = 0;
     }
     else {
         TIXMLASSERT( _firstChild == 0 );
         _firstChild = _lastChild = addThis;
         addThis->_prev = 0;
         addThis->_next = 0;
     }
     addThis->_parent = this;
     return addThis;
 }
XMLNode * TinyXML2::XMLNode::InsertFirstChild (XMLNode * addThis)
Add a child node as the first (left) child. If the child node is already part of the document, it is moved from its old location to the new location. Returns the addThis argument or 0 if the node does not belong to the same document.
Definition at line 702 of file TinyXML2.cpp.
References _document, _firstChild, _lastChild, _memPool, _next, _parent, _prev, TinyXML2::MemPool::SetTracked(), TIXMLASSERT, and Unlink().
Referenced by TinyXML2::XMLElement::SetText().
 {
     if ( addThis->_document != _document ) {
         TIXMLASSERT( false );
         return 0;
     }
   if (addThis->_parent)
     addThis->_parent->Unlink( addThis );
   else
      addThis->_memPool->SetTracked();
     if ( _firstChild ) {
         TIXMLASSERT( _lastChild );
         TIXMLASSERT( _firstChild->_prev == 0 );
         _firstChild->_prev = addThis;
         addThis->_next = _firstChild;
         _firstChild = addThis;
         addThis->_prev = 0;
     }
     else {
         TIXMLASSERT( _lastChild == 0 );
         _firstChild = _lastChild = addThis;
         addThis->_prev = 0;
         addThis->_next = 0;
     }
     addThis->_parent = this;
     return addThis;
 }
const XMLNode* TinyXML2::XMLNode::LastChild () const inline
Get the last child node, or null if none exists.
Definition at line 754 of file TinyXML2.h.
{
         return _lastChild;
     }
XMLNode* TinyXML2::XMLNode::LastChild () inline
Definition at line 758 of file TinyXML2.h.
{
         return const_cast<XMLNode*>(const_cast<const XMLNode*>(this)->LastChild() );
     }
const XMLElement * TinyXML2::XMLNode::LastChildElement (const char * value = 0) const
Get the last child element or optionally the last child element with the specified name.
Definition at line 784 of file TinyXML2.cpp.
References _lastChild, _prev, TinyXML2::XMLElement::Name(), TinyXML2::XMLUtil::StringEqual(), and TinyXML2::XMLElement::ToElement().
 {
     for( XMLNode* node=_lastChild; node; node=node->_prev ) {
         XMLElement* element = node->ToElement();
         if ( element ) {
             if ( !value || XMLUtil::StringEqual( element->Name(), value ) ) {
                 return element;
             }
         }
     }
     return 0;
 }
XMLElement* TinyXML2::XMLNode::LastChildElement (const char * value = 0) inline
Definition at line 767 of file TinyXML2.h.
{
         return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->LastChildElement(value) );
     }
XMLNode* TinyXML2::XMLNode::LinkEndChild (XMLNode * addThis) inline
Definition at line 812 of file TinyXML2.h.
{
         return InsertEndChild( addThis );
     }
const XMLNode* TinyXML2::XMLNode::NextSibling () const inline
Get the next (right) sibling node of this node.
Definition at line 788 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::Accept(), and TinyXML2::XMLDocument::Accept().
{
         return _next;
     }
XMLNode* TinyXML2::XMLNode::NextSibling () inline
Definition at line 792 of file TinyXML2.h.
{
         return _next;
     }
const XMLElement * TinyXML2::XMLNode::NextSiblingElement (const char * value = 0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
Definition at line 798 of file TinyXML2.cpp.
References _next, TinyXML2::XMLUtil::StringEqual(), and TinyXML2::XMLElement::ToElement().
Referenced by Voxel::ParameterDMLParser::_getParameter(), and Voxel::ParameterDMLParser::getParameters().
 {
     for( XMLNode* node=this->_next; node; node = node->_next ) {
         const XMLElement* element = node->ToElement();
         if ( element
                 && (!value || XMLUtil::StringEqual( value, node->Value() ))) {
             return element;
         }
     }
     return 0;
 }
XMLElement* TinyXML2::XMLNode::NextSiblingElement (const char * value = 0) inline
Definition at line 799 of file TinyXML2.h.
{
         return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->NextSiblingElement( value ) );
     }
bool TinyXML2::XMLNode::NoChildren () const inline
Returns true if this node has no children.
Definition at line 731 of file TinyXML2.h.
{
         return !_firstChild;
     }
XMLNode& TinyXML2::XMLNode::operator= (const XMLNode &) protected
const XMLNode* TinyXML2::XMLNode::Parent () const inline
Get the parent of this node on the DOM.
Definition at line 722 of file TinyXML2.h.
Referenced by TinyXML2::XMLPrinter::VisitEnter().
{
         return _parent;
     }
XMLNode* TinyXML2::XMLNode::Parent () inline
Definition at line 726 of file TinyXML2.h.
{
         return _parent;
     }
char * TinyXML2::XMLNode::ParseDeep (char * p, StrPair * parentEnd) virtual
Reimplemented in TinyXML2::XMLElement, TinyXML2::XMLUnknown, TinyXML2::XMLDeclaration, TinyXML2::XMLComment, and TinyXML2::XMLText.
Definition at line 824 of file TinyXML2.cpp.
References _document, _memPool, _value, TinyXML2::XMLElement::CLOSING, TinyXML2::XMLElement::ClosingType(), DeleteNode(), TinyXML2::StrPair::Empty(), TinyXML2::XMLDocument::Error(), TinyXML2::StrPair::GetStr(), TinyXML2::XMLDocument::Identify(), InsertEndChild(), TinyXML2::XMLElement::OPEN, ParseDeep(), TinyXML2::XMLDocument::SetError(), TinyXML2::MemPool::SetTracked(), TinyXML2::XMLUtil::StringEqual(), ToElement(), TinyXML2::StrPair::TransferTo(), Value(), TinyXML2::XML_ERROR_MISMATCHED_ELEMENT, and TinyXML2::XML_ERROR_PARSING.
Referenced by TinyXML2::XMLDocument::LoadFile(), TinyXML2::XMLDocument::Parse(), ParseDeep(), and TinyXML2::XMLElement::ParseDeep().
 {
     // This is a recursive method, but thinking about it "at the current level"
     // it is a pretty simple flat list:
     //    <foo/>
     //    <!-- comment -->
     //
     // With a special case:
     //    <foo>
     //    </foo>
     //    <!-- comment -->
     //
     // Where the closing element (/foo) *must* be the next thing after the opening
     // element, and the names must match. BUT the tricky bit is that the closing
     // element will be read by the child.
     //
     // 'endTag' is the end tag for this node, it is returned by a call to a child.
     // 'parentEnd' is the end tag for the parent, which is filled in and returned.
     while( p && *p ) {
         XMLNode* node = 0;
         p = _document->Identify( p, &node );
         if ( p == 0 || node == 0 ) {
             break;
         }
         StrPair endTag;
         p = node->ParseDeep( p, &endTag );
         if ( !p ) {
             DeleteNode( node );
             node = 0;
             if ( !_document->Error() ) {
                 _document->SetError( XML_ERROR_PARSING, 0, 0 );
             }
             break;
         }
         XMLElement* ele = node->ToElement();
         // We read the end tag. Return it to the parent.
         if ( ele && ele->ClosingType() == XMLElement::CLOSING ) {
             if ( parentEnd ) {
                 ele->_value.TransferTo( parentEnd );
             }
       node->_memPool->SetTracked(); // created and then immediately deleted.
             DeleteNode( node );
             return p;
         }
         // Handle an end tag returned to this level.
         // And handle a bunch of annoying errors.
         if ( ele ) {
             bool mismatch = false;
             if ( endTag.Empty() && ele->ClosingType() == XMLElement::OPEN ) {
                 mismatch = true;
             }
             else if ( !endTag.Empty() && ele->ClosingType() != XMLElement::OPEN ) {
                 mismatch = true;
             }
             else if ( !endTag.Empty() ) {
                 if ( !XMLUtil::StringEqual( endTag.GetStr(), node->Value() )) {
                     mismatch = true;
                 }
             }
             if ( mismatch ) {
                 _document->SetError( XML_ERROR_MISMATCHED_ELEMENT, node->Value(), 0 );
                 p = 0;
             }
         }
         if ( p == 0 ) {
             DeleteNode( node );
             node = 0;
         }
         if ( node ) {
             this->InsertEndChild( node );
         }
     }
     return 0;
 }
const XMLNode* TinyXML2::XMLNode::PreviousSibling () const inline
Get the previous (left) sibling node of this node.
Definition at line 772 of file TinyXML2.h.
{
         return _prev;
     }
XMLNode* TinyXML2::XMLNode::PreviousSibling () inline
Definition at line 776 of file TinyXML2.h.
{
         return _prev;
     }
const XMLElement * TinyXML2::XMLNode::PreviousSiblingElement (const char * value = 0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
Definition at line 811 of file TinyXML2.cpp.
References _prev, TinyXML2::XMLUtil::StringEqual(), and TinyXML2::XMLElement::ToElement().
 {
     for( XMLNode* node=_prev; node; node = node->_prev ) {
         const XMLElement* element = node->ToElement();
         if ( element
                 && (!value || XMLUtil::StringEqual( value, node->Value() ))) {
             return element;
         }
     }
     return 0;
 }
XMLElement* TinyXML2::XMLNode::PreviousSiblingElement (const char * value = 0) inline
Definition at line 783 of file TinyXML2.h.
{
         return const_cast<XMLElement*>(const_cast<const XMLNode*>(this)->PreviousSiblingElement( value ) );
     }
void TinyXML2::XMLNode::SetValue (const char * val, bool staticMem = false)
Set the Value of an XML node.
See Also
Value()
Definition at line 617 of file TinyXML2.cpp.
References _value, TinyXML2::StrPair::SetInternedStr(), and TinyXML2::StrPair::SetStr().
Referenced by TinyXML2::XMLDocument::NewComment(), TinyXML2::XMLDocument::NewDeclaration(), TinyXML2::XMLDocument::NewText(), TinyXML2::XMLDocument::NewUnknown(), and TinyXML2::XMLElement::SetText().
 {
     if ( staticMem ) {
         _value.SetInternedStr( str );
     }
     else {
         _value.SetStr( str );
     }
 }
virtual XMLNode* TinyXML2::XMLNode::ShallowClone (XMLDocument * document) const pure virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implemented in TinyXML2::XMLDocument, TinyXML2::XMLElement, TinyXML2::XMLUnknown, TinyXML2::XMLDeclaration, TinyXML2::XMLComment, and TinyXML2::XMLText.
virtual bool TinyXML2::XMLNode::ShallowEqual (const XMLNode * compare) const pure virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implemented in TinyXML2::XMLDocument, TinyXML2::XMLElement, TinyXML2::XMLUnknown, TinyXML2::XMLDeclaration, TinyXML2::XMLComment, and TinyXML2::XMLText.
virtual XMLComment* TinyXML2::XMLNode::ToComment () inline virtual
Safely cast to a Comment, or null.
Reimplemented in TinyXML2::XMLComment.
Definition at line 670 of file TinyXML2.h.
Referenced by TinyXML2::XMLComment::ShallowEqual().
{
         return 0;
     }
virtual const XMLComment* TinyXML2::XMLNode::ToComment () const inline virtual
Reimplemented in TinyXML2::XMLComment.
Definition at line 692 of file TinyXML2.h.
{
         return 0;
     }
virtual XMLDeclaration* TinyXML2::XMLNode::ToDeclaration () inline virtual
Safely cast to a Declaration, or null.
Reimplemented in TinyXML2::XMLDeclaration.
Definition at line 678 of file TinyXML2.h.
Referenced by TinyXML2::XMLDeclaration::ShallowEqual().
{
         return 0;
     }
virtual const XMLDeclaration* TinyXML2::XMLNode::ToDeclaration () const inline virtual
Reimplemented in TinyXML2::XMLDeclaration.
Definition at line 698 of file TinyXML2.h.
{
         return 0;
     }
virtual XMLDocument* TinyXML2::XMLNode::ToDocument () inline virtual
Safely cast to a Document, or null.
Reimplemented in TinyXML2::XMLDocument.
Definition at line 674 of file TinyXML2.h.
{
         return 0;
     }
virtual const XMLDocument* TinyXML2::XMLNode::ToDocument () const inline virtual
Reimplemented in TinyXML2::XMLDocument.
Definition at line 695 of file TinyXML2.h.
{
         return 0;
     }
virtual XMLElement* TinyXML2::XMLNode::ToElement () inline virtual
Safely cast to an Element, or null.
Reimplemented in TinyXML2::XMLElement.
Definition at line 662 of file TinyXML2.h.
Referenced by ParseDeep(), TinyXML2::XMLElement::ShallowEqual(), and TinyXML2::XMLPrinter::VisitEnter().
{
         return 0;
     }
virtual const XMLElement* TinyXML2::XMLNode::ToElement () const inline virtual
Reimplemented in TinyXML2::XMLElement.
Definition at line 686 of file TinyXML2.h.
{
         return 0;
     }
virtual XMLText* TinyXML2::XMLNode::ToText () inline virtual
Safely cast to Text, or null.
Reimplemented in TinyXML2::XMLText.
Definition at line 666 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::GetText(), TinyXML2::XMLElement::QueryBoolText(), TinyXML2::XMLElement::QueryDoubleText(), TinyXML2::XMLElement::QueryFloatText(), TinyXML2::XMLElement::QueryIntText(), TinyXML2::XMLElement::QueryUnsignedText(), TinyXML2::XMLElement::SetText(), and TinyXML2::XMLText::ShallowEqual().
{
         return 0;
     }
virtual const XMLText* TinyXML2::XMLNode::ToText () const inline virtual
Reimplemented in TinyXML2::XMLText.
Definition at line 689 of file TinyXML2.h.
{
         return 0;
     }
virtual XMLUnknown* TinyXML2::XMLNode::ToUnknown () inline virtual
Safely cast to an Unknown, or null.
Reimplemented in TinyXML2::XMLUnknown.
Definition at line 682 of file TinyXML2.h.
Referenced by TinyXML2::XMLUnknown::ShallowEqual().
{
         return 0;
     }
virtual const XMLUnknown* TinyXML2::XMLNode::ToUnknown () const inline virtual
Reimplemented in TinyXML2::XMLUnknown.
Definition at line 701 of file TinyXML2.h.
{
         return 0;
     }
void TinyXML2::XMLNode::Unlink (XMLNode * child) private
Definition at line 641 of file TinyXML2.cpp.
References _document, _firstChild, _lastChild, _next, _parent, _prev, and TIXMLASSERT.
Referenced by DeleteChildren(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), and ~XMLNode().
 {
     TIXMLASSERT( child->_document == _document );
     if ( child == _firstChild ) {
         _firstChild = _firstChild->_next;
     }
     if ( child == _lastChild ) {
         _lastChild = _lastChild->_prev;
     }
     if ( child->_prev ) {
         child->_prev->_next = child->_next;
     }
     if ( child->_next ) {
         child->_next->_prev = child->_prev;
     }
   child->_parent = 0;
 }
const char * TinyXML2::XMLNode::Value () const
The meaning of 'value' changes for the specific type.
Document: empty
Element:  name of the element
Comment:  the comment text
Unknown:  the tag contents
Text:   the text string
Definition at line 612 of file TinyXML2.cpp.
References _value, and TinyXML2::StrPair::GetStr().
Referenced by TinyXML2::XMLElement::GetText(), ParseDeep(), TinyXML2::XMLElement::QueryBoolText(), TinyXML2::XMLElement::QueryDoubleText(), TinyXML2::XMLElement::QueryFloatText(), TinyXML2::XMLElement::QueryIntText(), TinyXML2::XMLElement::QueryUnsignedText(), TinyXML2::XMLText::ShallowClone(), TinyXML2::XMLComment::ShallowClone(), TinyXML2::XMLDeclaration::ShallowClone(), TinyXML2::XMLUnknown::ShallowClone(), TinyXML2::XMLElement::ShallowClone(), TinyXML2::XMLText::ShallowEqual(), TinyXML2::XMLComment::ShallowEqual(), TinyXML2::XMLDeclaration::ShallowEqual(), TinyXML2::XMLUnknown::ShallowEqual(), TinyXML2::XMLElement::ShallowEqual(), and TinyXML2::XMLPrinter::Visit().
 {
     return _value.GetStr();
 }
Friends And Related Function Documentation
friend class XMLDocument friend
Definition at line 648 of file TinyXML2.h.
friend class XMLElement friend
Definition at line 649 of file TinyXML2.h.
Member Data Documentation
XMLDocument* TinyXML2::XMLNode::_document protected
Definition at line 895 of file TinyXML2.h.
Referenced by DeleteChild(), DeleteChildren(), TinyXML2::XMLElement::FindOrCreateAttribute(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), TinyXML2::XMLElement::ParseAttributes(), ParseDeep(), TinyXML2::XMLText::ParseDeep(), TinyXML2::XMLComment::ParseDeep(), TinyXML2::XMLDeclaration::ParseDeep(), TinyXML2::XMLUnknown::ParseDeep(), TinyXML2::XMLText::ShallowClone(), TinyXML2::XMLComment::ShallowClone(), TinyXML2::XMLDeclaration::ShallowClone(), TinyXML2::XMLUnknown::ShallowClone(), TinyXML2::XMLElement::ShallowClone(), Unlink(), and TinyXML2::XMLDocument::XMLDocument().
XMLNode* TinyXML2::XMLNode::_firstChild protected
Definition at line 899 of file TinyXML2.h.
Referenced by DeleteChildren(), FirstChildElement(), InsertEndChild(), InsertFirstChild(), and Unlink().
XMLNode* TinyXML2::XMLNode::_lastChild protected
Definition at line 900 of file TinyXML2.h.
Referenced by DeleteChildren(), InsertEndChild(), InsertFirstChild(), LastChildElement(), and Unlink().
MemPool* TinyXML2::XMLNode::_memPool private
Definition at line 906 of file TinyXML2.h.
Referenced by DeleteNode(), TinyXML2::XMLDocument::Identify(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), and ParseDeep().
XMLNode* TinyXML2::XMLNode::_next protected
Definition at line 903 of file TinyXML2.h.
Referenced by FirstChildElement(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), NextSiblingElement(), and Unlink().
XMLNode* TinyXML2::XMLNode::_parent protected
Definition at line 896 of file TinyXML2.h.
Referenced by DeleteChild(), TinyXML2::XMLDocument::DeleteNode(), InsertAfterChild(), InsertEndChild(), InsertFirstChild(), Unlink(), and ~XMLNode().
XMLNode* TinyXML2::XMLNode::_prev protected
Definition at line 902 of file TinyXML2.h.
Referenced by InsertAfterChild(), InsertEndChild(), InsertFirstChild(), LastChildElement(), PreviousSiblingElement(), and Unlink().
StrPair TinyXML2::XMLNode::_value mutable protected
Definition at line 897 of file TinyXML2.h.
Referenced by ParseDeep(), TinyXML2::XMLText::ParseDeep(), TinyXML2::XMLComment::ParseDeep(), TinyXML2::XMLDeclaration::ParseDeep(), TinyXML2::XMLUnknown::ParseDeep(), TinyXML2::XMLElement::ParseDeep(), SetValue(), and Value().
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp