Voxel: TinyXML2::XMLVisitor Class Reference
TinyXML2::XMLVisitor Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
virtual ~XMLVisitor ()
virtual bool VisitEnter (const XMLDocument &)
Visit a document.
virtual bool VisitExit (const XMLDocument &)
Visit a document.
virtual bool VisitEnter (const XMLElement &, const XMLAttribute *)
Visit an element.
virtual bool VisitExit (const XMLElement &)
Visit an element.
virtual bool Visit (const XMLDeclaration &)
Visit a declaration.
virtual bool Visit (const XMLText &)
Visit a text node.
virtual bool Visit (const XMLComment &)
Visit a comment node.
virtual bool Visit (const XMLUnknown &)
Visit an unknown node.
Detailed Description
Implements the interface to the "Visitor pattern" (see the Accept() method.) If you call the Accept() method, it requires being passed a XMLVisitor class to handle callbacks. For nodes that contain other nodes (Document, Element) you will get called with a VisitEnter/VisitExit pair. Nodes that are always leafs are simply called with Visit().
If you return 'true' from a Visit method, recursive parsing will continue. If you return false, no children of this node or its siblings will be visited.
All flavors of Visit methods have a default implementation that returns 'true' (continue visiting). You need to only override methods that are interesting to you.
Generally Accept() is called on the XMLDocument, although all nodes support visiting.
You should never change the document from a callback.
See Also
XMLNode::Accept()
Definition at line 475 of file TinyXML2.h.
Constructor & Destructor Documentation
virtual TinyXML2::XMLVisitor::~XMLVisitor () inline virtual
Definition at line 478 of file TinyXML2.h.
 {}
Member Function Documentation
virtual bool TinyXML2::XMLVisitor::Visit (const XMLDeclaration &) inline virtual
Visit a declaration.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 499 of file TinyXML2.h.
Referenced by TinyXML2::XMLText::Accept(), TinyXML2::XMLComment::Accept(), TinyXML2::XMLDeclaration::Accept(), and TinyXML2::XMLUnknown::Accept().
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::Visit (const XMLText &) inline virtual
Visit a text node.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 503 of file TinyXML2.h.
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::Visit (const XMLComment &) inline virtual
Visit a comment node.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 507 of file TinyXML2.h.
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::Visit (const XMLUnknown &) inline virtual
Visit an unknown node.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 511 of file TinyXML2.h.
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::VisitEnter (const XMLDocument &) inline virtual
Visit a document.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 481 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::Accept(), and TinyXML2::XMLDocument::Accept().
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::VisitEnter (const XMLElement & , const XMLAttribute *) inline virtual
Visit an element.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 490 of file TinyXML2.h.
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::VisitExit (const XMLDocument &) inline virtual
Visit a document.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 485 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::Accept(), and TinyXML2::XMLDocument::Accept().
{
         return true;
     }
virtual bool TinyXML2::XMLVisitor::VisitExit (const XMLElement &) inline virtual
Visit an element.
Reimplemented in TinyXML2::XMLPrinter.
Definition at line 494 of file TinyXML2.h.
{
         return true;
     }
The documentation for this class was generated from the following file:
TinyXML2.h