Voxel: Voxel Namespace Reference
Voxel Namespace Reference
Namespaces
TI
Classes
class CLIManager
class PCLViewer
class ToFCrossTalkFilter
class CameraSystem
This class provides ways to instantiate individual cameras and components like filters.
class Configuration
class ConfigSet
struct ConfigDataPacket
class ConfigurationFile
class MainConfigurationFile
class Convolve2D
class BMP
class Data2DCodec
This class is used for compressing and decompressing 16-bit signed data.
struct DataPacket
class DepthCamera
This is primary class which provides API for a depth camera.
class DepthCameraFactory
class DepthCameraLibraryPrivate
class DepthCameraLibrary
class Device
class USBDevice
class DeviceScanner
class USBDeviceScanner
class DFT
class Downloader
class USBDownloader
class DownloaderFactory
class BilateralFilter
class DiscreteGaussian
class Filter
class FilterDescription
class FilterFactory
class FilterParameter
class FilterParameterTemplate
class FilterParameterRangeTemplate
class FilterParameterEnumTemplate
class BoolFilterParameter
class FilterSet
class FilterSetIterator
class IIRFilter
class MedianFilter
class SmoothFilter
class TemporalMedianFilter
class VoxelFilterFactory
class Frame
class DepthFrame
class RawFrame
class ToFRawFrame
class ToFRawFrameTemplate
class ToFRawIQFrame
class ToFRawIQFrameTemplate
class RawDataFrame
class PointCloudFrame
class PointCloudFrameTemplate
class FrameBufferManager
class FrameBuffer
class FrameGenerator
class DepthFrameGenerator
struct FrameStreamHeader
struct FrameStreamPacket
struct GeneratorConfigurationSubPacket
class FrameStreamWriter
class FrameStreamReader
class LoggerOutStream
class Logger
class LogLevelChanger
class Parameter
class ParameterTemplate
class EnumParameterTemplate
class BoolParameter
class StrobeBoolParameter
class EnumParameter
class RangeParameterTemplate
class IntegerParameter
class FloatParameter
class ParameterDMLParser
class Point
class IntensityPoint
class RGBPoint
class Orientation
class PointCloudFrameGenerator
class PointCloudTransform
class Ptr
class RegisterProgrammer
class Serializable
class BasicSerializable
class SerializableString
class SerializableMap
class StringKeySerializableMap
class SerializedObject
class Streamer
class PyDepthCameraCallback
class PyLoggerOutputStream
class PyProgressFunction
class Timer
class USBBulkStreamer
class USBIO
class USBSystem
class USBSystemPrivate
struct DeviceInfo
class UVCRawData
class UVC
class UVCPrivate
class UVCStreamer
class UVCXU
class FrameSize
class RegionOfInterest
class FrameRate
class VideoMode
class SupportedVideoMode
class PCLGrabber
Typedefs
typedef Ptr< ToFCrossTalkFilter > ToFCrossTalkFilterPtr
template<typename T >
using Vector = std::vector< T >
template<typename T >
using List = std::list< T >
template<typename T >
using Set = std::set< T >
template<typename K , typename V >
using Map = std::unordered_map< K, V >
template<typename T >
using Function = std::function< T >
template<typename T >
using Atomic = std::atomic< T >
template<typename T >
using Lock = std::unique_lock< T >
template<typename T >
using shared_ptr = Ptr< T >
typedef std::string String
typedef int IndexType
typedef std::size_t SizeType
typedef uint8_t ByteType
typedef uint64_t TimeStampType
typedef uint32_t GeneratorIDType
typedef uint64_t FileOffsetType
typedef std::complex< float > Complex
typedef std::complex< double > ComplexDouble
typedef std::thread Thread
typedef Ptr< Thread > ThreadPtr
typedef std::mutex Mutex
typedef std::condition_variable ConditionVariable
typedef std::ifstream InputFileStream
typedef std::ofstream OutputFileStream
typedef std::istream InputStream
typedef std::ostream OutputStream
typedef std::ostringstream OutputStringStream
typedef std::istringstream InputStringStream
typedef Ptr< DepthCamera > DepthCameraPtr
typedef Ptr< DepthCameraFactory > DepthCameraFactoryPtr
typedef void(* GetDepthCameraFactory)(DepthCameraFactoryPtr &depthCameraFactory)
typedef int(* GetABIVersion)()
typedef Ptr< DepthCameraLibrary > DepthCameraLibraryPtr
typedef Ptr< Device > DevicePtr
typedef Vector< ComplexDouble > Complex1D
typedef Vector< Vector
< ComplexDouble > > Complex2D
typedef Ptr< Downloader > DownloaderPtr
typedef Ptr< DownloaderFactory > DownloaderFactoryPtr
typedef void(* GetDownloaderFactory)(DownloaderFactoryPtr &downloaderFactory)
typedef Ptr< Filter > FilterPtr
typedef Ptr< FilterFactory > FilterFactoryPtr
typedef void(* GetFilterFactory)(FilterFactoryPtr &filterFactory)
typedef Ptr< FilterParameter > FilterParameterPtr
typedef Ptr< const
FilterParameter > FilterParameterConstPtr
typedef
FilterParameterTemplate< bool > BoolFilterParameterTemplate
typedef
FilterParameterTemplate< int > IntegerFilterParameterTemplate
typedef
FilterParameterTemplate< uint > UnsignedIntegerFilterParameterTemplate
typedef
FilterParameterTemplate< float > FloatFilterParameterTemplate
typedef
FilterParameterRangeTemplate
< uint > UnsignedFilterParameter
typedef
FilterParameterRangeTemplate
< int > SignedFilterParameter
typedef
FilterParameterRangeTemplate
< float > FloatFilterParameter
typedef
FilterParameterEnumTemplate
< int > EnumFilterParameter
typedef
FilterParameterEnumTemplate
< bool > BoolEnumFilterParameterTemplate
typedef BoolFilterParameter StrobeBoolFilterParameter
typedef Ptr< Frame > FramePtr
typedef Ptr< DepthFrame > DepthFramePtr
typedef Ptr< RawFrame > RawFramePtr
typedef Ptr< ToFRawFrame > ToFRawFramePtr
typedef Ptr< ToFRawIQFrame > ToFRawIQFramePtr
typedef Ptr< RawDataFrame > RawDataFramePtr
typedef Ptr< PointCloudFrame > PointCloudFramePtr
typedef
PointCloudFrameTemplate< Point > XYZPointCloudFrame
typedef
PointCloudFrameTemplate
< IntensityPoint > XYZIPointCloudFrame
typedef Ptr< XYZPointCloudFrame > XYZPointCloudFramePtr
typedef Ptr< FrameGenerator > FrameGeneratorPtr
typedef Ptr< DepthFrameGenerator > DepthFrameGeneratorPtr
typedef Ptr< FrameStreamWriter > FrameStreamWriterPtr
typedef Ptr< FrameStreamReader > FrameStreamReaderPtr
typedef OutputStream &(* OStreamManipulator)(OutputStream &)
typedef Ptr< Parameter > ParameterPtr
typedef ParameterTemplate< bool > BoolParameterTemplate
typedef ParameterTemplate< int > IntegerParameterTemplate
typedef ParameterTemplate< uint > UnsignedIntegerParameterTemplate
typedef ParameterTemplate< float > FloatParameterTemplate
typedef EnumParameterTemplate
< bool > BoolEnumParameterTemplate
typedef EnumParameterTemplate
< int > IntegerEnumParameterTemplate
typedef RangeParameterTemplate
< int > IntegerRangeParameterTemplate
typedef RangeParameterTemplate
< float > FloatRangeParameterTemplate
typedef RangeParameterTemplate
< uint > UnsignedIntegerParameter
typedef Ptr< PointCloudTransform > PointCloudTransformPtr
typedef Ptr< Serializable > SerializablePtr
typedef BasicSerializable
< uint32_t > SerializableUnsignedInt
typedef BasicSerializable
< int32_t > SerializableSignedInt
typedef BasicSerializable< float > SerializableFloat
typedef Ptr
< SerializableUnsignedInt > SerializableUnsignedIntPtr
typedef Ptr
< SerializableSignedInt > SerializableSignedIntPtr
typedef Ptr< SerializableFloat > SerializableFloatPtr
typedef Ptr< SerializableString > SerializableStringPtr
typedef Ptr
< StringKeySerializableMap > StringKeySerializableMapPtr
typedef Ptr< USBIO > USBIOPtr
typedef void * HANDLE
typedef void * HDEVINFO
typedef unsigned long DWORD
typedef unsigned long ULONG
typedef unsigned char UCHAR
typedef Ptr< UVCXU > UVCXUPtr
Enumerations
enum ToFFrameType { ToF_PHASE_AMPLITUDE, ToF_I_Q, ToF_QUAD }
enum LogLevel {
LOG_CRITICAL, LOG_ERROR, LOG_WARNING, LOG_INFO,
LOG_DEBUG
}
Functions
String getHex (uint16_t value)
String functions.
void split (const String &str, const char delimiter, Vector< String > &split)
void breakLines (const String &str, std::ostream &out, const uint maxPerLine, const String &newlinePrefix)
int getFiles (const String &dir, const String &matchString, Vector< String > &files)
Filesystem functions – returns the number of files read or else -1 for error. Only those files whose name matches "matchString" partially (sub-string) are returned "files".
uint gcd (uint n, uint m)
unsigned int nearestPowerOf2 (unsigned int value, unsigned int &index)
String dirname (const String &filename)
String basename (const String &filename)
bool isFilePresent (const String &filename)
bool isDirectory (const String &filename)
bool makeDirectory (const String &filename)
template<typename T , int sz>
int arraySize (T(&)[sz])
Array handling template.
template<typename T >
Ptr< T > byteAlloc (unsigned long sizeInBytes)
bool floatEquals (float lhs, float rhs)
String & ltrim (String &s)
Left Trim.
String & rtrim (String &s)
Right Trim.
String & trim (String &s)
Trim.
void getDepthCameraFactory (DepthCameraFactoryPtr &depthCameraFactory)
int getABIVersion ()
String dynamicLoadError ()
void getDownloaderFactory (DownloaderFactoryPtr &downloaderFactory)
void getFilterFactory (FilterFactoryPtr &filterFactory)
template<typename T >
void deleter (T *data)
std::string getDeviceError ()
template<typename T >
boost::shared_ptr< T > make_shared_ptr (std::shared_ptr< T > &ptr)
Support for std::shared_ptr <-> boost::shared_ptr.
template<typename T >
std::shared_ptr< T > make_shared_ptr (boost::shared_ptr< T > &ptr)
Variables
class VOXEL_NO_EXPORT DepthCameraLibraryPrivate
Logger logger (LOG_WARNING)
class VOXEL_EXPORT Parameter
class VOXEL_NO_EXPORT USBSystemPrivate
class VOXEL_NO_EXPORT UVCPrivate
Typedef Documentation
typedef Ptr< DepthCamera > Voxel::DepthCameraPtr
Definition at line 436 of file DepthCamera.h.
typedef Ptr<DepthFrameGenerator> Voxel::DepthFrameGeneratorPtr
Definition at line 159 of file FrameGenerator.h.
typedef Ptr<FrameGenerator> Voxel::FrameGeneratorPtr
Definition at line 63 of file FrameGenerator.h.
typedef Ptr<FrameStreamReader> Voxel::FrameStreamReaderPtr
Definition at line 132 of file FrameStream.h.
typedef Ptr<FrameStreamWriter> Voxel::FrameStreamWriterPtr
Definition at line 82 of file FrameStream.h.
typedef BasicSerializable<float> Voxel::SerializableFloat
Definition at line 56 of file Serializable.h.
typedef Ptr<SerializableFloat> Voxel::SerializableFloatPtr
Definition at line 59 of file Serializable.h.
typedef Ptr<Serializable> Voxel::SerializablePtr
Definition at line 28 of file Serializable.h.
typedef BasicSerializable<int32_t> Voxel::SerializableSignedInt
Definition at line 55 of file Serializable.h.
typedef Ptr<SerializableSignedInt> Voxel::SerializableSignedIntPtr
Definition at line 58 of file Serializable.h.
typedef Ptr<SerializableString> Voxel::SerializableStringPtr
Definition at line 98 of file Serializable.h.
typedef BasicSerializable<uint32_t> Voxel::SerializableUnsignedInt
Definition at line 54 of file Serializable.h.
typedef Ptr<SerializableUnsignedInt> Voxel::SerializableUnsignedIntPtr
Definition at line 57 of file Serializable.h.
typedef Ptr<StringKeySerializableMap> Voxel::StringKeySerializableMapPtr
Definition at line 199 of file Serializable.h.
typedef Ptr<ToFCrossTalkFilter> Voxel::ToFCrossTalkFilterPtr
Definition at line 41 of file ToFCrossTalkFilter.h.
typedef Ptr<USBIO> Voxel::USBIOPtr
Definition at line 62 of file USBIO.h.
Function Documentation
String Voxel::dynamicLoadError ()
Definition at line 29 of file DepthCameraLibrary.cpp.
Referenced by Voxel::DepthCameraLibrary::getABIVersion(), Voxel::DepthCameraLibrary::getDepthCameraFactory(), Voxel::DepthCameraLibrary::getDownloaderFactory(), Voxel::DepthCameraLibrary::getFilterFactory(), and Voxel::DepthCameraLibrary::load().
 {
 #ifdef WINDOWS
   DWORD error = GetLastError();
   if (error)
   {
     LPVOID lpMsgBuf;
     DWORD bufLen = FormatMessage(
       FORMAT_MESSAGE_ALLOCATE_BUFFER |
       FORMAT_MESSAGE_FROM_SYSTEM |
       FORMAT_MESSAGE_IGNORE_INSERTS,
       NULL,
       error,
       MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
       (LPTSTR)&lpMsgBuf,
       0, NULL);
     if (bufLen)
     {
       LPCSTR lpMsgStr = (LPCSTR)lpMsgBuf;
       String result(lpMsgStr, lpMsgStr + bufLen);
       LocalFree(lpMsgBuf);
       return result;
     }
   }
   return String();
 #elif defined(LINUX)
   char *c;
   if(c = dlerror())
     return String(c);
   else
     return String();
 #endif
 }
template<typename T > boost::shared_ptr<T> Voxel::make_shared_ptr (std::shared_ptr< T > & ptr)
Support for std::shared_ptr <-> boost::shared_ptr.
Definition at line 70 of file PCLGrabber.h.
 {
   return boost::shared_ptr<T>(ptr.get(), [ptr](T*) mutable {ptr.reset();});
 }
template<typename T > std::shared_ptr<T> Voxel::make_shared_ptr (boost::shared_ptr< T > & ptr)
Definition at line 76 of file PCLGrabber.h.
 {
   return std::shared_ptr<T>(ptr.get(), [ptr](T*) mutable {ptr.reset();});
 }