Voxel: Frame related classes
Frame related classes
Classes
class Voxel::Frame
class Voxel::DepthFrame
class Voxel::RawFrame
class Voxel::ToFRawFrame
class Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >
class Voxel::ToFRawIQFrame
class Voxel::ToFRawIQFrameTemplate< ByteType >
class Voxel::RawDataFrame
class Voxel::PointCloudFrame
class Voxel::PointCloudFrameTemplate< PointType >
class Voxel::FrameBufferManager< BufferType >
class Voxel::FrameBuffer< BufferType >
class Voxel::Point
class Voxel::IntensityPoint
class Voxel::RGBPoint
class Voxel::Orientation
class Voxel::PointCloudTransform
class Voxel::FrameSize
class Voxel::RegionOfInterest
class Voxel::FrameRate
class Voxel::VideoMode
class Voxel::SupportedVideoMode
Typedefs
typedef Ptr< Frame > Voxel::FramePtr
typedef Ptr< DepthFrame > Voxel::DepthFramePtr
typedef Ptr< RawFrame > Voxel::RawFramePtr
typedef Ptr< ToFRawFrame > Voxel::ToFRawFramePtr
typedef Ptr< ToFRawIQFrame > Voxel::ToFRawIQFramePtr
typedef Ptr< RawDataFrame > Voxel::RawDataFramePtr
typedef Ptr< PointCloudFrame > Voxel::PointCloudFramePtr
typedef
PointCloudFrameTemplate< Point > Voxel::XYZPointCloudFrame
typedef
PointCloudFrameTemplate
< IntensityPoint > Voxel::XYZIPointCloudFrame
typedef Ptr< XYZPointCloudFrame > Voxel::XYZPointCloudFramePtr
typedef Ptr< PointCloudTransform > Voxel::PointCloudTransformPtr
Enumerations
enum Voxel::ToFFrameType { Voxel::ToF_PHASE_AMPLITUDE, Voxel::ToF_I_Q, Voxel::ToF_QUAD }
Functions
float Voxel::Point::dot (const Point &other) const
Point Voxel::Point::cross (const Point &other) const
float Voxel::Point::angle (const Point &other) const
float Voxel::Point::norm () const
Point & Voxel::Point::operator- ()
Point Voxel::Point::operator* (const Point &other) const
Point Voxel::Point::operator* (const float &other) const
Point Voxel::Point::operator+ (const Point &other) const
Detailed Description
Typedef Documentation
typedef Ptr<DepthFrame> Voxel::DepthFramePtr
Definition at line 147 of file Frame.h.
typedef Ptr<Frame> Voxel::FramePtr
Definition at line 53 of file Frame.h.
typedef Ptr<PointCloudFrame> Voxel::PointCloudFramePtr
Definition at line 659 of file Frame.h.
typedef Ptr<PointCloudTransform> Voxel::PointCloudTransformPtr
Definition at line 90 of file PointCloudTransform.h.
typedef Ptr<RawDataFrame> Voxel::RawDataFramePtr
Definition at line 642 of file Frame.h.
typedef Ptr<RawFrame> Voxel::RawFramePtr
Definition at line 160 of file Frame.h.
typedef Ptr<ToFRawFrame> Voxel::ToFRawFramePtr
Definition at line 201 of file Frame.h.
typedef Ptr<ToFRawIQFrame> Voxel::ToFRawIQFramePtr
Definition at line 429 of file Frame.h.
typedef PointCloudFrameTemplate<IntensityPoint> Voxel::XYZIPointCloudFrame
Definition at line 756 of file Frame.h.
typedef PointCloudFrameTemplate<Point> Voxel::XYZPointCloudFrame
Definition at line 755 of file Frame.h.
typedef Ptr<XYZPointCloudFrame> Voxel::XYZPointCloudFramePtr
Definition at line 758 of file Frame.h.
Enumeration Type Documentation
enum Voxel::ToFFrameType
Enumerator
ToF_PHASE_AMPLITUDE
ToF_I_Q
ToF_QUAD
Definition at line 162 of file Frame.h.
                   {
   ToF_PHASE_AMPLITUDE,
   ToF_I_Q,
   ToF_QUAD
 };
Function Documentation
float Voxel::Point::angle (const Point & other) const inline
Definition at line 62 of file Point.h.
References Voxel::Point::dot(), Voxel::floatEquals(), and Voxel::Point::norm().
Referenced by Voxel::PointCloudTransform::calcAperatureAngleRadians().
 {
   float n1 = norm(), n2 = other.norm();
   if(floatEquals(n1, 0) || floatEquals(n2, 0))
     return 0;
   return acos(dot(other)/n1/n2);
 }
Point Voxel::Point::cross (const Point & other) const inline
Definition at line 51 of file Point.h.
References Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
Referenced by Voxel::PointCloudTransform::_computeClippingPlanes().
 {
   Point p;
   p.x = y*other.z - z*other.y;
   p.y = z*other.x - x*other.z;
   p.z = x*other.y - y*other.x;
   return p;
 }
float Voxel::Point::dot (const Point & other) const inline
Definition at line 46 of file Point.h.
References Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
Referenced by Voxel::Point::angle(), and Voxel::PointCloudTransform::worldToImage().
 {
   return (x*other.x + y*other.y + z*other.z);
 }
float Voxel::Point::norm () const inline
Definition at line 72 of file Point.h.
References Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
Referenced by Voxel::Point::angle().
 {
   return sqrt(x*x + y*y + z*z);
 }
Point Voxel::Point::operator* (const Point & other) const inline
Definition at line 85 of file Point.h.
References Voxel::Point::Point(), Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
 {
   return Point(x*other.x, y*other.y, z*other.z);
 }
Point Voxel::Point::operator* (const float & other) const inline
Definition at line 90 of file Point.h.
References Voxel::Point::Point(), Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
 {
   return Point(x*other, y*other, z*other);
 }
Point Voxel::Point::operator+ (const Point & other) const inline
Definition at line 95 of file Point.h.
References Voxel::Point::Point(), Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
 {
   return Point(x + other.x, y + other.y, z + other.z);
 }
Point & Voxel::Point::operator- () inline
Definition at line 77 of file Point.h.
References Voxel::Point::x, Voxel::Point::y, and Voxel::Point::z.
 {
   x = -x;
   y = -y;
   z = -z;
   return *this;
 }