Voxel: Camera System Components
Camera System Components
This group of classes provide the higher level API for cameras.
Classes
class Voxel::CameraSystem
This class provides ways to instantiate individual cameras and components like filters.
class Voxel::DepthCamera
This is primary class which provides API for a depth camera.
class Voxel::DepthCameraFactory
class Voxel::DepthCameraLibrary
class Voxel::Device
class Voxel::USBDevice
class Voxel::DeviceScanner
class Voxel::USBDeviceScanner
class Voxel::DownloaderFactory
Typedefs
typedef Ptr< DepthCameraFactory > Voxel::DepthCameraFactoryPtr
typedef void(* Voxel::GetDepthCameraFactory)(DepthCameraFactoryPtr &depthCameraFactory)
typedef int(* Voxel::GetABIVersion)()
typedef Ptr< DepthCameraLibrary > Voxel::DepthCameraLibraryPtr
typedef Ptr< Device > Voxel::DevicePtr
typedef Ptr< DownloaderFactory > Voxel::DownloaderFactoryPtr
typedef void(* Voxel::GetDownloaderFactory)(DownloaderFactoryPtr &downloaderFactory)
Functions
void Voxel::getDepthCameraFactory (DepthCameraFactoryPtr &depthCameraFactory)
int Voxel::getABIVersion ()
void Voxel::getDownloaderFactory (DownloaderFactoryPtr &downloaderFactory)
void Voxel::DepthCameraFactory::_addSupportedDevices (const Vector< DevicePtr > &devices)
void Voxel::DownloaderFactory::_addSupportedDevices (const Vector< DevicePtr > &devices)
Variables
class VOXEL_NO_EXPORT Voxel::DepthCameraLibraryPrivate
Detailed Description
This group of classes provide the higher level API for cameras.
Typedef Documentation
typedef Ptr<DepthCameraFactory> Voxel::DepthCameraFactoryPtr
Definition at line 58 of file DepthCameraFactory.h.
typedef Ptr<DepthCameraLibrary> Voxel::DepthCameraLibraryPtr
Definition at line 50 of file DepthCameraLibrary.h.
typedef Ptr<Device> Voxel::DevicePtr
Definition at line 79 of file Device.h.
typedef Ptr<DownloaderFactory> Voxel::DownloaderFactoryPtr
Definition at line 53 of file DownloaderFactory.h.
typedef int(* Voxel::GetABIVersion)()
Definition at line 68 of file DepthCameraFactory.h.
typedef void(* Voxel::GetDepthCameraFactory)(DepthCameraFactoryPtr &depthCameraFactory)
Definition at line 66 of file DepthCameraFactory.h.
typedef void(* Voxel::GetDownloaderFactory)(DownloaderFactoryPtr &downloaderFactory)
Definition at line 59 of file DownloaderFactory.h.
Function Documentation
void Voxel::DepthCameraFactory::_addSupportedDevices (const Vector< DevicePtr > & devices) inline protected
Definition at line 49 of file DepthCameraFactory.h.
References Voxel::DepthCameraFactory::_supportedDevices.
Referenced by Voxel::TI::CalculusCDKCameraFactory::CalculusCDKCameraFactory(), Voxel::TI::HaddockCDKCameraFactory::HaddockCDKCameraFactory(), Voxel::TI::TintinCDKCameraFactory::TintinCDKCameraFactory(), Voxel::TI::Voxel14CameraFactory::Voxel14CameraFactory(), and Voxel::TI::VoxelDCameraFactory::VoxelDCameraFactory().
 {
   _supportedDevices.reserve(_supportedDevices.size() + devices.size());
   _supportedDevices.insert(_supportedDevices.end(), devices.begin(), devices.end());
 }
void Voxel::DownloaderFactory::_addSupportedDevices (const Vector< DevicePtr > & devices) inline protected
Definition at line 44 of file DownloaderFactory.h.
References Voxel::DownloaderFactory::_supportedDevices.
Referenced by Voxel::TI::TintinCDKDownloaderFactory::TintinCDKDownloaderFactory().
 {
   _supportedDevices.reserve(_supportedDevices.size() + devices.size());
   _supportedDevices.insert(_supportedDevices.end(), devices.begin(), devices.end());
 }
int Voxel::getABIVersion ()
Definition at line 49 of file CalculusCDKCameraFactory.cpp.
 {
   return VOXEL_ABI_VERSION; // Return the Voxel ABI version which was used to compile this DepthCameraFactory
 }
void Voxel::getDepthCameraFactory (DepthCameraFactoryPtr & depthCameraFactory)
Definition at line 44 of file CalculusCDKCameraFactory.cpp.
 {
   ptr = DepthCameraFactoryPtr(new CalculusCDKCameraFactory("CalculusCDK"));
 }
void Voxel::getDownloaderFactory (DownloaderFactoryPtr & downloaderFactory)
Definition at line 44 of file TintinCDKDownloaderFactory.cpp.
 {
   ptr = DownloaderFactoryPtr(new TintinCDKDownloaderFactory("TintinCDK"));
 }
Variable Documentation
class VOXEL_NO_EXPORT Voxel::DepthCameraLibraryPrivate
Definition at line 23 of file DepthCameraLibrary.h.