Voxel: LineNoise Namespace Reference
LineNoise Namespace Reference
Classes
struct current
struct linenoiseCompletions
Typedefs
typedef std::function< void(const
char *, linenoiseCompletions *)> LinenoiseCompletionCallback
Enumerations
enum {
SPECIAL_NONE, SPECIAL_UP = -20, SPECIAL_DOWN = -21, SPECIAL_LEFT = -22,
SPECIAL_RIGHT = -23, SPECIAL_DELETE = -24, SPECIAL_HOME = -25, SPECIAL_END = -26,
SPECIAL_INSERT = -27, SPECIAL_PAGE_UP = -28, SPECIAL_PAGE_DOWN = -29
}
Functions
void linenoiseHistoryFree (void)
LinenoiseCompletionCallback linenoiseSetCompletionCallback (LinenoiseCompletionCallback fn)
void linenoiseAddCompletion (linenoiseCompletions *lc, const char *str)
int linenoiseColumns (void)
char * linenoise (const char *prompt)
int linenoiseHistoryAdd (const char *line)
int linenoiseHistoryGetMaxLen (void)
int linenoiseHistorySetMaxLen (int len)
int linenoiseHistorySave (const char *filename)
int linenoiseHistoryLoad (const char *filename)
char ** linenoiseHistory (int *len)
Detailed Description
Modified from the following linenoise source.
Copyright (c) 2014 Texas Instruments Inc.
UTF-8 utility functions
(c) 2010 Steve Bennett steve.nosp@m.b@wo.nosp@m.rkwar.nosp@m.e.ne.nosp@m.t.au
See LICENCE for licence details.
Typedef Documentation
typedef std::function<void(const char *, linenoiseCompletions *)> LineNoise::LinenoiseCompletionCallback
Definition at line 61 of file LineNoise.h.
Enumeration Type Documentation
anonymous enum
Enumerator
SPECIAL_NONE
SPECIAL_UP
SPECIAL_DOWN
SPECIAL_LEFT
SPECIAL_RIGHT
SPECIAL_DELETE
SPECIAL_HOME
SPECIAL_END
SPECIAL_INSERT
SPECIAL_PAGE_UP
SPECIAL_PAGE_DOWN
Definition at line 153 of file LineNoise.cpp.
      {
   SPECIAL_NONE,
   SPECIAL_UP = -20,
   SPECIAL_DOWN = -21,
   SPECIAL_LEFT = -22,
   SPECIAL_RIGHT = -23,
   SPECIAL_DELETE = -24,
   SPECIAL_HOME = -25,
   SPECIAL_END = -26,
   SPECIAL_INSERT = -27,
   SPECIAL_PAGE_UP = -28,
   SPECIAL_PAGE_DOWN = -29
 };
Function Documentation
char * LineNoise::linenoise (const char * prompt)
Definition at line 1477 of file LineNoise.cpp.
References LineNoise::current::buf, LineNoise::current::bufmax, LineNoise::current::capture, LineNoise::current::chars, CameraSystemIQFrameTest::count, LineNoise::current::len, LINENOISE_MAX_LINE, LineNoise::current::pos, and LineNoise::current::prompt.
Referenced by Voxel::CLIManager::_commandLoop().
 {
   int count;
   struct current current;
   char buf[LINENOISE_MAX_LINE];
   if (enableRawMode(&current) == -1) {
     printf("%s", prompt);
     fflush(stdout);
     if (fgets(buf, sizeof(buf), stdin) == NULL) {
       return NULL;
     }
     count = strlen(buf);
     if (count && buf[count - 1] == '\n') {
       count--;
       buf[count] = '\0';
     }
   }
   else
   {
     current.buf = buf;
     current.bufmax = sizeof(buf);
     current.len = 0;
     current.chars = 0;
     current.pos = 0;
     current.prompt = prompt;
     current.capture = NULL;
     count = linenoiseEdit(&current);
     disableRawMode(&current);
     printf("\n");
     free(current.capture);
     if (count == -1) {
       return NULL;
     }
   }
   return strdup(buf);
 }
void LineNoise::linenoiseAddCompletion (linenoiseCompletions * lc, const char * str)
Definition at line 1158 of file LineNoise.cpp.
References LineNoise::linenoiseCompletions::cvec, and LineNoise::linenoiseCompletions::len.
Referenced by Voxel::CLIManager::_addFilterCompletion(), Voxel::CLIManager::_completionCallback(), Voxel::CLIManager::_connectCompletion(), Voxel::CLIManager::_paramCompletion(), Voxel::CLIManager::_removeFilterCompletion(), Voxel::CLIManager::_saveCompletion(), and Voxel::CLIManager::_setFilterParamCompletion().
{
   lc->cvec = (char **)realloc(lc->cvec, sizeof(char*)*(lc->len + 1));
   lc->cvec[lc->len++] = strdup(str);
 }
int LineNoise::linenoiseColumns (void)
Definition at line 1468 of file LineNoise.cpp.
References LineNoise::current::cols.
 {
   struct current current;
   enableRawMode(&current);
   getWindowSize(&current);
   disableRawMode(&current);
   return current.cols;
 }
char ** LineNoise::linenoiseHistory (int * len)
Definition at line 1658 of file LineNoise.cpp.
{
   if (len) {
     *len = history_len;
   }
   return history;
 }
int LineNoise::linenoiseHistoryAdd (const char * line)
Definition at line 1519 of file LineNoise.cpp.
Referenced by Voxel::CLIManager::_commandLoop(), and linenoiseHistoryLoad().
{
   char *linecopy;
   if (history_max_len == 0) return 0;
   if (history == NULL) {
     history = (char **)malloc(sizeof(char*)*history_max_len);
     if (history == NULL) return 0;
     memset(history, 0, (sizeof(char*)*history_max_len));
   }
   /* do not insert duplicate lines into history */
   if (history_len > 0 && strcmp(line, history[history_len - 1]) == 0) {
     return 0;
   }
   linecopy = strdup(line);
   if (!linecopy) return 0;
   if (history_len == history_max_len) {
     free(history[0]);
     memmove(history, history + 1, sizeof(char*)*(history_max_len - 1));
     history_len--;
   }
   history[history_len] = linecopy;
   history_len++;
   return 1;
 }
void LineNoise::linenoiseHistoryFree (void)
Definition at line 195 of file LineNoise.cpp.
{
   if (history) {
     int j;
     for (j = 0; j < history_len; j++)
       free(history[j]);
     free(history);
     history = NULL;
     history_len = 0;
   }
 }
int LineNoise::linenoiseHistoryGetMaxLen (void)
Definition at line 1546 of file LineNoise.cpp.
{
   return history_max_len;
 }
int LineNoise::linenoiseHistoryLoad (const char * filename)
Definition at line 1615 of file LineNoise.cpp.
References LINENOISE_MAX_LINE, and linenoiseHistoryAdd().
Referenced by Voxel::CLIManager::_commandLoop().
{
   FILE *fp = fopen(filename, "r");
   char buf[LINENOISE_MAX_LINE];
   if (fp == NULL) return -1;
   while (fgets(buf, LINENOISE_MAX_LINE, fp) != NULL) {
     char *src, *dest;
     /* Decode backslash escaped values */
     for (src = dest = buf; *src; src++) {
       char ch = *src;
       if (ch == '\\') {
         src++;
         if (*src == 'n') {
           ch = '\n';
         }
         else if (*src == 'r') {
           ch = '\r';
         }
         else {
           ch = *src;
         }
       }
       *dest++ = ch;
     }
     /* Remove trailing newline */
     if (dest != buf && (dest[-1] == '\n' || dest[-1] == '\r')) {
       dest--;
     }
     *dest = 0;
     linenoiseHistoryAdd(buf);
   }
   fclose(fp);
   return 0;
 }
int LineNoise::linenoiseHistorySave (const char * filename)
Definition at line 1580 of file LineNoise.cpp.
Referenced by Voxel::CLIManager::_commandLoop().
{
   FILE *fp = fopen(filename, "w");
   int j;
   if (fp == NULL) return -1;
   for (j = 0; j < history_len; j++) {
     const char *str = history[j];
     /* Need to encode backslash, nl and cr */
     while (*str) {
       if (*str == '\\') {
         fputs("\\\\", fp);
       }
       else if (*str == '\n') {
         fputs("\\n", fp);
       }
       else if (*str == '\r') {
         fputs("\\r", fp);
       }
       else {
         fputc(*str, fp);
       }
       str++;
     }
     fputc('\n', fp);
   }
   fclose(fp);
   return 0;
 }
int LineNoise::linenoiseHistorySetMaxLen (int len)
Definition at line 1550 of file LineNoise.cpp.
Referenced by Voxel::CLIManager::_commandLoop().
{
   char **newHistory;
   if (len < 1) return 0;
   if (history) {
     int tocopy = history_len;
     newHistory = (char **)malloc(sizeof(char*)*len);
     if (newHistory == NULL) return 0;
     /* If we can't copy everything, free the elements we'll not use. */
     if (len < tocopy) {
       int j;
       for (j = 0; j < tocopy - len; j++) free(history[j]);
       tocopy = len;
     }
     memset(newHistory, 0, sizeof(char*)*len);
     memcpy(newHistory, history + (history_len - tocopy), sizeof(char*)*tocopy);
     free(history);
     history = newHistory;
   }
   history_max_len = len;
   if (history_len > history_max_len)
     history_len = history_max_len;
   return 1;
 }
LinenoiseCompletionCallback LineNoise::linenoiseSetCompletionCallback (LinenoiseCompletionCallback fn)
Definition at line 1152 of file LineNoise.cpp.
Referenced by Voxel::CLIManager::_commandLoop().
{
   completionCallback = fn;
   return fn;
 }