Voxel: Voxel::TI::TintinVCOFrequency Class Reference
Voxel::TI::TintinVCOFrequency Class Reference
Custom parameters.
Public Member Functions
TintinVCOFrequency (ToFTintinCamera &depthCamera, RegisterProgrammer &programmer, const String &vcoFreq, const String &modM, const String &modMFrac, const String &modN)
_depthCamera (depthCamera)
_vcoFreq (vcoFreq)
_modM (modM)
_modMFrac (modMFrac)
_modN (modN)
virtual bool get (float &value, bool refresh=false)
virtual bool set (const float &value)
virtual ~TintinVCOFrequency ()
Public Member Functions inherited from Voxel::FloatParameter
FloatParameter (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, float lowerLimit, float upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual ~FloatParameter ()
Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &lowerLimit, const float &upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const float lowerLimit () const
virtual const float upperLimit () const
virtual void setLowerLimit (floatlowerLimit)
virtual void setUpperLimit (floatupperLimit)
virtual bool validate (const float &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< float >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool refresh ()
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFTintinCamera & _depthCamera
String _vcoFreq
String _modM
String _modMFrac
String _modN
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::FloatParameter
static Ptr< FloatParameter > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
static Ptr
< RangeParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< float >
static Ptr< ParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::FloatParameter
virtual float _fromRawValue (uint32_t value) const
virtual uint32_t _toRawValue (float value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< float >
float _lowerLimit
float _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< float >
float _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Custom parameters.
Definition at line 21 of file ToFTintinCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::TintinVCOFrequency::TintinVCOFrequency (ToFTintinCamera & depthCamera, RegisterProgrammer & programmer, const String & vcoFreq, const String & modM, const String & modMFrac, const String & modN) inline
Definition at line 26 of file ToFTintinCamera.cpp.
                                                                                                                                                                          :
   FloatParameter(programmer, vcoFreq, "MHz", 0, 0, 0, 1, 300, 600, 384, "VCO frequency",
                  "Frequency of the VCO used for generating modulation frequencies", IOType::IO_READ_WRITE, {modM, modN}), _depthCamera(depthCamera),
virtual Voxel::TI::TintinVCOFrequency::~TintinVCOFrequency () inline virtual
Definition at line 85 of file ToFTintinCamera.cpp.
 {}
Member Function Documentation
Voxel::TI::TintinVCOFrequency::_depthCamera (depthCamera)
Voxel::TI::TintinVCOFrequency::_modM (modM)
Voxel::TI::TintinVCOFrequency::_modMFrac (modMFrac)
Voxel::TI::TintinVCOFrequency::_modN (modN) inline
Definition at line 29 of file ToFTintinCamera.cpp.
 {}
Voxel::TI::TintinVCOFrequency::_vcoFreq (vcoFreq)
virtual bool Voxel::TI::TintinVCOFrequency::get (float & value, bool refresh = false) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 31 of file ToFTintinCamera.cpp.
References _depthCamera, Voxel::DepthCamera::_get(), Voxel::TI::ToFTintinCamera::_getSystemClockFrequency(), _modM, _modMFrac, _modN, Voxel::ParameterTemplate< float >::refresh(), and Voxel::RangeParameterTemplate< float >::validate().
Referenced by Voxel::TI::TintinModulationFrequencyParameter::set().
   {
     uint modM, modMFrac, modN, systemClockFrequency;
     if(!_depthCamera._get(_modM, modM, refresh) || !_depthCamera._get(_modMFrac, modMFrac, refresh)
       || !_depthCamera._get(_modN, modN, refresh) || !_depthCamera._getSystemClockFrequency(systemClockFrequency))
       return false;
     if(modN == 0)
       return false;
     float modMf = modM + ((float)modMFrac)/(1 << 16);
     float v = systemClockFrequency*modMf/modN;
     if(!validate(v))
       return false;
     value = v;
     return true;
   }
virtual bool Voxel::TI::TintinVCOFrequency::set (const float & value) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 52 of file ToFTintinCamera.cpp.
References _depthCamera, Voxel::TI::ToFTintinCamera::_getSystemClockFrequency(), _modM, _modMFrac, _modN, Voxel::DepthCamera::_set(), Voxel::ParameterTemplate< float >::_value, MOD_PLL_UPDATE, and Voxel::RangeParameterTemplate< float >::validate().
Referenced by Voxel::TI::TintinModulationFrequencyParameter::set().
   {
     if(!validate(value))
       return false;
     if(!_depthCamera._set(MOD_PLL_UPDATE, true))
       return false;
     ParameterPtr pllUpdate(nullptr, [this](Parameter *) { _depthCamera._set(MOD_PLL_UPDATE, false); }); // Set PLL update to false when going out of scope of this function
     uint modM, modMFrac, modN, systemClockFrequency;
     if(!_depthCamera._getSystemClockFrequency(systemClockFrequency))
       return false;
     modN = 2;
     if(systemClockFrequency == 0)
       return false;
     float modMf = value*modN/systemClockFrequency;
     modM = (uint)modMf;
     modMFrac = (uint)((modMf - modM)*(1 << 16));
     if(!_depthCamera._set(_modM, modM) || !_depthCamera._set(_modN, modN) || !_depthCamera._set(_modMFrac, modMFrac))
       return false;
     std::this_thread::sleep_for(std::chrono::milliseconds(10));
     _value = value;
     return true;
   }
Member Data Documentation
ToFTintinCamera& Voxel::TI::TintinVCOFrequency::_depthCamera private
Definition at line 23 of file ToFTintinCamera.cpp.
Referenced by get(), and set().
String Voxel::TI::TintinVCOFrequency::_modM private
Definition at line 24 of file ToFTintinCamera.cpp.
Referenced by get(), and set().
String Voxel::TI::TintinVCOFrequency::_modMFrac private
Definition at line 24 of file ToFTintinCamera.cpp.
Referenced by get(), and set().
String Voxel::TI::TintinVCOFrequency::_modN private
Definition at line 24 of file ToFTintinCamera.cpp.
Referenced by get(), and set().
String Voxel::TI::TintinVCOFrequency::_vcoFreq private
Definition at line 24 of file ToFTintinCamera.cpp.
The documentation for this class was generated from the following file:
ToFTintinCamera.cpp