Voxel: Voxel::SerializableMap< Key > Class Template Reference
Voxel::SerializableMap< Key > Class Template Reference
#include <Serializable.h>
Public Member Functions
SerializableMap (Map< Key, SerializablePtr > &other)
SerializableMap (SerializableMap &other)
SerializableMap ()
virtual size_t serializedSize () const
virtual bool write (SerializedObject &object) const
virtual bool read (SerializedObject &object)
virtual ~SerializableMap ()
Additional Inherited Members
Private Member Functions inherited from Voxel::Serializable
virtual ~Serializable ()
Detailed Description
template<typename Key>
class Voxel::SerializableMap< Key >
Definition at line 116 of file Serializable.h.
Constructor & Destructor Documentation
template<typename Key> Voxel::SerializableMap< Key >::SerializableMap (Map< Key, SerializablePtr > & other) inline
Definition at line 119 of file Serializable.h.
 : Map<Key, SerializablePtr>(other) {}
template<typename Key> Voxel::SerializableMap< Key >::SerializableMap (SerializableMap< Key > & other) inline
Definition at line 120 of file Serializable.h.
 : Map<Key, SerializablePtr>(other) {}
template<typename Key> Voxel::SerializableMap< Key >::SerializableMap () inline
Definition at line 121 of file Serializable.h.
 {}
template<typename Key> virtual Voxel::SerializableMap< Key >::~SerializableMap () inline virtual
Definition at line 185 of file Serializable.h.
 {}
Member Function Documentation
template<typename Key> virtual bool Voxel::SerializableMap< Key >::read (SerializedObject & object) inline virtual
Implements Voxel::Serializable.
Definition at line 155 of file Serializable.h.
Referenced by Voxel::FrameGenerator::readConfiguration().
   {
     uint32_t size;
     if(object.get((char *)&size, sizeof(uint32_t)) != sizeof(uint32_t))
       return false;
     uint32_t g = object.currentGetOffset();
     Key k;
     while(object.currentGetOffset() - g < size)
     {
       if(!k.read(object))
         return false;
       auto x = this->find(k);
       if(x == this->end())
       {
         logger(LOG_WARNING) << "SerializableMap: Found unknown key '" << k << "'" << std::endl;
         continue;
       }
       if(!x->second->read(object))
         return false;
     }
     return object.currentGetOffset() == (g + size);
   }
template<typename Key> virtual size_t Voxel::SerializableMap< Key >::serializedSize () const inline virtual
Implements Voxel::Serializable.
Definition at line 123 of file Serializable.h.
Referenced by Voxel::SerializableMap< SerializableString >::write(), and Voxel::FrameGenerator::writeConfiguration().
   {
     uint32_t size = sizeof(uint32_t);
     for(auto &x: *this)
     {
       size += x.first.serializedSize();
       size += x.second->serializedSize();
     }
     return size;
   }
template<typename Key> virtual bool Voxel::SerializableMap< Key >::write (SerializedObject & object) const inline virtual
Implements Voxel::Serializable.
Definition at line 136 of file Serializable.h.
Referenced by Voxel::FrameGenerator::writeConfiguration().
   {
     uint32_t size = serializedSize() - sizeof(uint32_t);
     if(object.size() - object.currentPutOffset() < size)
       return false;
     if(object.put((const char *)&size, sizeof(uint32_t)) != sizeof(uint32_t))
       return false;
     for(auto &x: *this)
     {
       if(!x.first.write(object) || !x.second->write(object))
         return false;
     }
     return true;
   }
The documentation for this class was generated from the following file:
Serializable.h