Voxel: Voxel::TI::HaddockUnambiguousRangeParameter Class Reference
Voxel::TI::HaddockUnambiguousRangeParameter Class Reference
Public Member Functions
HaddockUnambiguousRangeParameter (ToFHaddockCamera &depthCamera, RegisterProgrammer &programmer)
virtual bool get (uint &value, bool refresh=false)
virtual bool set (const uint &value)
Public Member Functions inherited from Voxel::RangeParameterTemplate< T >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &lowerLimit, const T &upperLimit, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const T lowerLimit () const
virtual const T upperLimit () const
virtual void setLowerLimit (T lowerLimit)
virtual void setUpperLimit (T upperLimit)
virtual bool validate (const T &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< T >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool set (const T &value)
virtual bool refresh ()
virtual bool get (T &value, bool refresh=false)
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFHaddockCamera & _depthCamera
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< T >
static Ptr
< RangeParameterTemplate< T > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< T >
static Ptr< ParameterTemplate
< T > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::ParameterTemplate< T >
virtual uint32_t _toRawValue (T value) const
virtual T _fromRawValue (uint32_t value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< T >
T _lowerLimit
T _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< T >
T _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Definition at line 162 of file ToFHaddockCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::HaddockUnambiguousRangeParameter::HaddockUnambiguousRangeParameter (ToFHaddockCamera & depthCamera, RegisterProgrammer & programmer) inline
Definition at line 166 of file ToFHaddockCamera.cpp.
                                                                                                  :
   UnsignedIntegerParameter(programmer, UNAMBIGUOUS_RANGE, "m", 0x5C60, 24, 5, 0, 6, 60,
                            DEFAULT_UNAMBIGUOUS_RANGE, "Unambiguous Range", "Unambiguous range of distance the camera needs to support"),
                            _depthCamera(depthCamera) {}
Member Function Documentation
virtual bool Voxel::TI::HaddockUnambiguousRangeParameter::get (uint & value, bool refresh = false) inline virtual
Definition at line 171 of file ToFHaddockCamera.cpp.
References Voxel::ParameterTemplate< T >::_value, DEFAULT_UNAMBIGUOUS_RANGE, Voxel::ParameterTemplate< T >::get(), Voxel::ParameterTemplate< T >::refresh(), and set().
   {
     if(refresh)
     {
       if(!UnsignedIntegerParameter::get(value, refresh))// Invalid value? Probably register not set yet
       {
         if(!set(DEFAULT_UNAMBIGUOUS_RANGE)) // set range of 3 meters
           return false;
         _value = DEFAULT_UNAMBIGUOUS_RANGE;
         value = DEFAULT_UNAMBIGUOUS_RANGE;
       }
       return true;
     }
     else
       return UnsignedIntegerParameter::get(value, refresh);
   }
virtual bool Voxel::TI::HaddockUnambiguousRangeParameter::set (const uint & value) inline virtual
Definition at line 189 of file ToFHaddockCamera.cpp.
References _depthCamera, Voxel::TI::ToFCamera::_getFrameRate(), Voxel::DepthCamera::_set(), Voxel::TI::ToFCamera::_setFrameRate(), DEALIAS_16BIT_OP_ENABLE, DEALIAS_EN, DEALIASED_PHASE_MASK, Voxel::TI::HaddockModulationFrequencyParameter::getOptimalMaximum(), Voxel::TI::HaddockModulationFrequencyParameter::getOptimalMinimum(), Voxel::DepthCamera::getParam(), K0, Voxel::RangeParameterTemplate< T >::lowerLimit(), MA, MB, MOD_FREQ1, MOD_PLL_UPDATE, MOD_PS1, MOD_PS2, QUAD_CNT_MAX, CameraSystemIQFrameTest::r, Voxel::TI::HaddockModulationFrequencyParameter::set(), Voxel::ParameterTemplate< T >::set(), SPEED_OF_LIGHT, SUBFRAME_CNT_MAX, TG_EN, Voxel::RangeParameterTemplate< T >::upperLimit(), and VCO_FREQ.
Referenced by get().
   {
     ParameterPtr p = _depthCamera.getParam(MOD_FREQ1);
     HaddockModulationFrequencyParameter *mfp = dynamic_cast<HaddockModulationFrequencyParameter *>(p.get());
     HaddockVCOFrequency *vco = dynamic_cast<HaddockVCOFrequency *>(_depthCamera.getParam(VCO_FREQ).get());
     if(!mfp || !vco)
       return false;
     float modulationFrequency1Minimum = mfp->getOptimalMinimum();
     FrameRate r;
     if(!_depthCamera._getFrameRate(r))
       return false;
     // No need of dealiasing?
     if(value <= (uint)(4095*SPEED_OF_LIGHT/1E6f/2/(1 << 12)/modulationFrequency1Minimum))
     {
       if(!_depthCamera._set(TG_EN, false) ||
         !_depthCamera._set(QUAD_CNT_MAX, 4) || !_depthCamera._set(SUBFRAME_CNT_MAX, 4) ||
         !_depthCamera._setFrameRate(r) ||
         !_depthCamera._set(DEALIAS_16BIT_OP_ENABLE, false) ||
         !_depthCamera._set(DEALIASED_PHASE_MASK, 0))
         return false;
       if(!mfp->set(4095*SPEED_OF_LIGHT/1E6f/2/(1 << 12)/value))
         return false;
       if(!_depthCamera._set(DEALIAS_EN, false)) // Disable dealiasing explicitly
         return false;
       if(!UnsignedIntegerParameter::set(value)) // Save the value in a register
         return false;
       if(!_depthCamera._set(TG_EN, true))
         return false;
       return true;
     }
     else
     {
       if(!_depthCamera._set(TG_EN, false) ||
         !_depthCamera._set(QUAD_CNT_MAX, 6) || !_depthCamera._set(SUBFRAME_CNT_MAX, 2))
         return false;
       uint ma = 8, mb = 7, k0 = 1, modPS1 = 14, modPS2 = 16;
       float vcoFreqMinimum = std::max(mfp->getOptimalMinimum()*3*modPS2, vco->lowerLimit()),
       vcoFreqMaximum = std::min(mfp->getOptimalMaximum()*3*modPS2, vco->upperLimit());
       float s = 96*SPEED_OF_LIGHT*1E-6/value; // in MHz
       int phaseMask = 0;
       int sign = 1;
       float vcoFreq;
       if(s > vcoFreqMaximum)
       {
         sign = 1;
         while(s/(1 << phaseMask) > vcoFreqMaximum)
           phaseMask++;
         vcoFreq = s/(1 << phaseMask);
         if(vcoFreq < vcoFreqMinimum)
         {
           phaseMask--;
           vcoFreq = s/(1 << phaseMask);
         }
       }
       else if(s < vcoFreqMinimum)
       {
         sign = -1;
         while(s*(1 << phaseMask) < vcoFreqMinimum)
           phaseMask++;
         vcoFreq = s*(1 << phaseMask);
       }
       else
         vcoFreq = s;
       if(!_depthCamera._set(MOD_PLL_UPDATE, true))
         return false;
       ParameterPtr pllUpdate(nullptr, [this](Parameter *)
       { _depthCamera._set(MOD_PLL_UPDATE, false); }); // Set PLL update to false when going out of scope of this function
       if(!_depthCamera._set(VCO_FREQ, vcoFreq) ||
         !_depthCamera._set(MOD_PS1, modPS1) ||
         !_depthCamera._set(MOD_PS2, modPS2) ||
         !_depthCamera._set(MA, ma) ||
         !_depthCamera._set(MB, mb) ||
         !_depthCamera._set(K0, k0) ||
         !_depthCamera._set(DEALIASED_PHASE_MASK, (int)sign*phaseMask) ||
         !_depthCamera._setFrameRate(r) ||
         !_depthCamera._set(DEALIAS_16BIT_OP_ENABLE, false) ||
         !_depthCamera._set(DEALIAS_EN, true)) // Enable dealiasing explicitly
         return false;
       if(!UnsignedIntegerParameter::set(value)) // Save the value in a register
         return false;
       if(!_depthCamera._set(TG_EN, true))
         return false;
       return true;
     }
   }
Member Data Documentation
ToFHaddockCamera& Voxel::TI::HaddockUnambiguousRangeParameter::_depthCamera private
Definition at line 164 of file ToFHaddockCamera.cpp.
Referenced by set().
The documentation for this class was generated from the following file:
ToFHaddockCamera.cpp