Voxel: Voxel::Logger Class Reference
Voxel::Logger Class Reference
Common and Utility classes
#include <Logger.h>
Public Types
typedef Logger &(* LoggerManipulator)(Logger &)
Public Member Functions
Logger (LogLevel loglevel=LOG_ERROR)
Logger & operator= (const Logger &other)
Logger & operator() (LogLevel loglevel)
LogLevel getDefaultLogLevel ()
LogLevel getCurrentLogLevel ()
void setDefaultLogLevel (LogLevel loglevel)
OutputStream & getStream ()
IndexType addOutputStream (LoggerOutStream::LoggerOutStreamFunctionType f)
bool removeOutputStream (IndexType index)
template<typename T >
Logger & operator<< (const T &value)
Logger & operator<< (LoggerManipulator manip)
Logger & operator<< (OStreamManipulator manip)
virtual ~Logger ()
Protected Attributes
OutputStream & _out = std::cerr
Mutex _mutex
LogLevel _logLevel
LogLevel _currentLogLevel
Map< IndexType, LoggerOutStream > _outputStreams
IndexType _outputStreamCount = 0
Static Protected Attributes
static const String _logLevelNames [5] = { "CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG" }
Detailed Description
Definition at line 73 of file Logger.h.
Member Typedef Documentation
typedef Logger&(* Voxel::Logger::LoggerManipulator)(Logger &)
Definition at line 153 of file Logger.h.
Constructor & Destructor Documentation
Voxel::Logger::Logger (LogLevel loglevel = LOG_ERROR) inline
Definition at line 89 of file Logger.h.
                                        : _logLevel(loglevel), _currentLogLevel(loglevel)
   {}
virtual Voxel::Logger::~Logger () inline virtual
Definition at line 175 of file Logger.h.
   {
   }
Member Function Documentation
IndexType Voxel::Logger::addOutputStream (LoggerOutStream::LoggerOutStreamFunctionType f) inline
Definition at line 120 of file Logger.h.
   {
     IndexType i = _outputStreamCount;
     _outputStreams[i].setOutputFunction(f);
     _outputStreamCount++;
     return i;
   }
LogLevel Voxel::Logger::getCurrentLogLevel () inline
Definition at line 105 of file Logger.h.
   {
     return _currentLogLevel;
   }
LogLevel Voxel::Logger::getDefaultLogLevel () inline
Definition at line 100 of file Logger.h.
Referenced by Voxel::Configuration::_getPaths(), and Voxel::LogLevelChanger::LogLevelChanger().
   {
     return _logLevel;
   }
OutputStream& Voxel::Logger::getStream () inline
Definition at line 115 of file Logger.h.
   {
     return _out;
   }
Logger& Voxel::Logger::operator() (LogLevel loglevel) inline
Definition at line 94 of file Logger.h.
   {
     _currentLogLevel = loglevel;
     return *this << _logLevelNames[loglevel] << ": ";
   }
template<typename T > Logger& Voxel::Logger::operator<< (const T & value) inline
Definition at line 141 of file Logger.h.
References LensCalibrationTest::x.
   {
     if(_currentLogLevel <= _logLevel)
     {
       _out << value;
       for(auto &x: _outputStreams)
         x.second << value;
     }
     return *this;
   }
Logger& Voxel::Logger::operator<< (LoggerManipulator manip) inline
Definition at line 155 of file Logger.h.
   {
     if(_currentLogLevel <= _logLevel)
       return (*manip)(*this);
     else
       return *this;
   }
Logger& Voxel::Logger::operator<< (OStreamManipulator manip) inline
Definition at line 163 of file Logger.h.
References LensCalibrationTest::x.
   {
     if(_currentLogLevel <= _logLevel)
     {
       (*manip)(_out);
       for(auto &x: _outputStreams)
         x.second << manip;
     }
     return *this;
   }
Logger& Voxel::Logger::operator= (const Logger & other) inline
Definition at line 92 of file Logger.h.
References _currentLogLevel, and _logLevel.
 { _logLevel = other._logLevel; _currentLogLevel = other._currentLogLevel; return *this; }
bool Voxel::Logger::removeOutputStream (IndexType index) inline
Definition at line 128 of file Logger.h.
References LensCalibrationTest::x.
   {
     auto x = _outputStreams.find(index);
     if(x != _outputStreams.end())
     {
       _outputStreams.erase(x);
       return true;
     }
     return false;
   }
void Voxel::Logger::setDefaultLogLevel (LogLevel loglevel) inline
Definition at line 110 of file Logger.h.
Referenced by Voxel::LogLevelChanger::LogLevelChanger(), main(), and Voxel::LogLevelChanger::~LogLevelChanger().
   {
     _logLevel = loglevel;
   }
Member Data Documentation
LogLevel Voxel::Logger::_currentLogLevel protected
Definition at line 80 of file Logger.h.
Referenced by operator=().
LogLevel Voxel::Logger::_logLevel protected
Definition at line 80 of file Logger.h.
Referenced by operator=().
const String Voxel::Logger::_logLevelNames = { "CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG" } static protected
Definition at line 83 of file Logger.h.
Mutex Voxel::Logger::_mutex mutable protected
Definition at line 78 of file Logger.h.
OutputStream& Voxel::Logger::_out = std::cerr protected
Definition at line 76 of file Logger.h.
IndexType Voxel::Logger::_outputStreamCount = 0 protected
Definition at line 86 of file Logger.h.
Map<IndexType, LoggerOutStream> Voxel::Logger::_outputStreams protected
Definition at line 85 of file Logger.h.
The documentation for this class was generated from the following files:
Logger.h
Logger.cpp