Voxel: Voxel::TI::TintinUnambiguousRangeParameter Class Reference
Voxel::TI::TintinUnambiguousRangeParameter Class Reference
Public Member Functions
TintinUnambiguousRangeParameter (ToFTintinCamera &depthCamera, RegisterProgrammer &programmer)
virtual bool get (uint &value, bool refresh=false)
virtual bool set (const uint &value)
Public Member Functions inherited from Voxel::RangeParameterTemplate< T >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &lowerLimit, const T &upperLimit, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const T lowerLimit () const
virtual const T upperLimit () const
virtual void setLowerLimit (T lowerLimit)
virtual void setUpperLimit (T upperLimit)
virtual bool validate (const T &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< T >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool set (const T &value)
virtual bool refresh ()
virtual bool get (T &value, bool refresh=false)
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFTintinCamera & _depthCamera
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< T >
static Ptr
< RangeParameterTemplate< T > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< T >
static Ptr< ParameterTemplate
< T > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::ParameterTemplate< T >
virtual uint32_t _toRawValue (T value) const
virtual T _fromRawValue (uint32_t value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< T >
T _lowerLimit
T _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< T >
T _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Definition at line 192 of file ToFTintinCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::TintinUnambiguousRangeParameter::TintinUnambiguousRangeParameter (ToFTintinCamera & depthCamera, RegisterProgrammer & programmer) inline
Definition at line 196 of file ToFTintinCamera.cpp.
                                                                                                :
     UnsignedIntegerParameter(programmer, UNAMBIGUOUS_RANGE, "m", 0, 0, 0, 0, 3, 50,
     DEFAULT_UNAMBIGUOUS_RANGE, "Unambiguous Range", "Unambiguous range of distance the camera needs to support"),
     _depthCamera(depthCamera) {}
Member Function Documentation
virtual bool Voxel::TI::TintinUnambiguousRangeParameter::get (uint & value, bool refresh = false) inline virtual
Definition at line 201 of file ToFTintinCamera.cpp.
References _depthCamera, Voxel::DepthCamera::_get(), Voxel::ParameterTemplate< T >::_value, DEFAULT_UNAMBIGUOUS_RANGE, Voxel::ParameterTemplate< T >::refresh(), SCRATCH1, and set().
   {
     if(refresh)
     {
       if(!_depthCamera._get(SCRATCH1, value, refresh))// Invalid value? Probably register not set yet
       {
         if(!set(DEFAULT_UNAMBIGUOUS_RANGE)) // set range of 3 meters
           return false;
         _value = DEFAULT_UNAMBIGUOUS_RANGE;
         value = DEFAULT_UNAMBIGUOUS_RANGE;
       }
       return true;
     }
     else
       return _depthCamera._get(SCRATCH1, value, refresh);
   }
virtual bool Voxel::TI::TintinUnambiguousRangeParameter::set (const uint & value) inline virtual
Definition at line 219 of file ToFTintinCamera.cpp.
References _depthCamera, Voxel::TI::ToFCamera::_getFrameRate(), Voxel::DepthCamera::_set(), Voxel::TI::ToFCamera::_setFrameRate(), DEALIAS_16BIT_OP_ENABLE, DEALIAS_EN, DEALIASED_PHASE_MASK, DELAY_FB_COEFF1, FREQ_RATIO, Voxel::TI::TintinModulationFrequencyParameter::getOptimalMaximum(), Voxel::TI::TintinModulationFrequencyParameter::getOptimalMinimum(), Voxel::DepthCamera::getParam(), KA, KB, Voxel::RangeParameterTemplate< T >::lowerLimit(), MA, MB, MOD_FREQ1, MOD_PLL_UPDATE, MOD_PS1, MOD_PS2, QUAD_CNT_MAX, CameraSystemIQFrameTest::r, SCRATCH1, Voxel::ParameterTemplate< T >::set(), Voxel::TI::TintinModulationFrequencyParameter::set(), SPEED_OF_LIGHT, SUBFRAME_CNT_MAX, TG_DISABLE, Voxel::RangeParameterTemplate< T >::upperLimit(), VCO_FREQ1, and VCO_FREQ2.
Referenced by get().
   {
     ParameterPtr p = _depthCamera.getParam(MOD_FREQ1);
     TintinModulationFrequencyParameter *mfp = dynamic_cast<TintinModulationFrequencyParameter *>(p.get());
     TintinVCOFrequency *vco = dynamic_cast<TintinVCOFrequency *>(_depthCamera.getParam(VCO_FREQ1).get());
     if(!mfp || !vco)
       return false;
     float modulationFrequency1Minimum = mfp->getOptimalMinimum();
     FrameRate r;
     uint delayFBCoeff1;
     if(!_depthCamera._getFrameRate(r))
       return false;
     // No need of dealiasing?
     if(value <= (uint)(4095*SPEED_OF_LIGHT/1E6f/2/(1 << 12)/modulationFrequency1Minimum))
     {
       float modulationFrequency1 = 4095*SPEED_OF_LIGHT/1E6f/2/(1 << 12)/value;
       delayFBCoeff1 = modulationFrequency1*(1 << 10)/24;
       if(!_depthCamera._set(TG_DISABLE, true) ||
         !_depthCamera._set(QUAD_CNT_MAX, 4) ||
         !_depthCamera._set(SUBFRAME_CNT_MAX, 4) ||
         !_depthCamera._setFrameRate(r) ||
         !_depthCamera._set(DEALIAS_16BIT_OP_ENABLE, false) ||
         !_depthCamera._set(DEALIASED_PHASE_MASK, 0) ||
         !mfp->set(modulationFrequency1) ||
         !_depthCamera._set(DELAY_FB_COEFF1, delayFBCoeff1) ||
         !_depthCamera._set(DEALIAS_EN, false) || // Disable dealiasing explicitly
         !UnsignedIntegerParameter::set(value) || // Save the value in a register
         !_depthCamera._set(TG_DISABLE, false))
         return false;
       return true;
     }
     else
     {
       if(!_depthCamera._set(TG_DISABLE, true) ||
         !_depthCamera._set(QUAD_CNT_MAX, 6) || !_depthCamera._set(SUBFRAME_CNT_MAX, 2))
         return false;
       uint ma = 2, mb = 3, ka = 2, kb = 1, modPS1 = 1, modPS2 = 0;
       uint freqRatio = ma*(1 << 12)/mb;
       float vcoFreqMinimum = std::max(mfp->getOptimalMinimum()*6*(1 + modPS1), vco->lowerLimit()),
       vcoFreqMaximum = std::min((mfp->getOptimalMaximum()*ma)/mb*6*(1 + modPS1), vco->upperLimit());
       float s = (96.0f/ma)*(1 + modPS1)*SPEED_OF_LIGHT*1E-6/value; // in MHz
       int phaseMask = 0;
       int sign = 1;
       float vcoFreq;
       if(s > vcoFreqMaximum)
       {
         sign = 1;
         while(s/(1 << phaseMask) > vcoFreqMaximum)
           phaseMask++;
         vcoFreq = s/(1 << phaseMask);
         if(vcoFreq < vcoFreqMinimum)
         {
           phaseMask--;
           vcoFreq = vcoFreqMaximum;
         }
       }
       else if(s < vcoFreqMinimum)
       {
         sign = -1;
         while(s*(1 << phaseMask) < vcoFreqMinimum)
           phaseMask++;
         vcoFreq = s*(1 << phaseMask);
         if(vcoFreq > vcoFreqMaximum)
           vcoFreq = vcoFreqMaximum;
       }
       else
         vcoFreq = s;
       // delayFBCoeff1 = modFreq1*(1 << 10)/24
       delayFBCoeff1 = (vcoFreq/6/(1 + modPS1))*(1 << 10)/24;
       if(!_depthCamera._set(MOD_PLL_UPDATE, true))
         return false;
       ParameterPtr pllUpdate(nullptr, [this](Parameter *)
       { _depthCamera._set(MOD_PLL_UPDATE, false); }); // Set PLL update to false when going out of scope of this function
       if(!_depthCamera._set(VCO_FREQ1, vcoFreq) ||
         !_depthCamera._set(VCO_FREQ2, vcoFreq*mb/ma*(1+modPS2)/(1+modPS1)) ||
         !_depthCamera._set(MOD_PS1, modPS1) ||
         !_depthCamera._set(MOD_PS2, modPS2) ||
         !_depthCamera._set(MA, ma) ||
         !_depthCamera._set(MB, mb) ||
         !_depthCamera._set(KA, ka) ||
         !_depthCamera._set(KB, kb) ||
         !_depthCamera._set(FREQ_RATIO, freqRatio) ||
         !_depthCamera._set(DELAY_FB_COEFF1, delayFBCoeff1) ||
         !_depthCamera._set(DEALIASED_PHASE_MASK, (int)sign*phaseMask) ||
         !_depthCamera._setFrameRate(r) ||
         !_depthCamera._set(DEALIAS_16BIT_OP_ENABLE, false) ||
         !_depthCamera._set(DEALIAS_EN, true)) // Enable dealiasing explicitly
       return false;
       if(!_depthCamera._set(SCRATCH1, value)) // Save the value in a register
         return false;
       if(!_depthCamera._set(TG_DISABLE, false))
         return false;
       return true;
     }
   }
Member Data Documentation
ToFTintinCamera& Voxel::TI::TintinUnambiguousRangeParameter::_depthCamera private
Definition at line 194 of file ToFTintinCamera.cpp.
Referenced by get(), and set().
The documentation for this class was generated from the following file:
ToFTintinCamera.cpp