Voxel: Voxel::Configuration Class Reference
Voxel::Configuration Class Reference
Common and Utility classes
#include <Configuration.h>
Classes
struct _Path
Public Member Functions
bool getFirmwarePaths (Vector< String > &paths)
bool getConfPaths (Vector< String > &paths)
bool getLibPaths (Vector< String > &paths)
bool getLocalPath (const String &type, String &path)
bool getLocalFirmwarePath (String &path)
bool getLocalConfPath (String &path)
bool getLocalLibPath (String &path)
bool getLocalFile (const String &type, String &fileName)
bool getLocalFirmwareFile (String &fileName)
bool getLocalConfFile (String &fileName)
bool getLocalLibFile (String &fileName)
bool getConfFile (String &fileName)
Updates "name" to full path.
bool getFirmwareFile (String &fileName)
bool geLibFile (String &fileName)
Static Public Member Functions
static bool addFirmwarePath (const String &path)
static bool addConfPath (const String &path)
static bool addLibPath (const String &path)
Protected Member Functions
bool _getPaths (const String &type, Vector< String > &paths)
bool _get (const String &type, String &name)
Static Protected Member Functions
static bool _addPath (const String &type, const String &path)
Static Protected Attributes
static const Map< String, _Path > _pathTypes
Detailed Description
Definition at line 25 of file Configuration.h.
Member Function Documentation
bool Voxel::Configuration::_addPath (const String & type, const String & path) static protected
Definition at line 69 of file Configuration.cpp.
References _pathTypes, and Voxel::Configuration::_Path::environmentVariable.
 {
   auto t = _pathTypes.find(type);
   if(t == _pathTypes.end())
     return false;
   const _Path &pt = t->second;
   char *p = getenv(pt.environmentVariable.c_str());
 #ifdef WINDOWS
   if(p != 0)
     return _putenv_s(pt.environmentVariable.c_str(), (path + PATH_SEP + p).c_str()) == 0;
   else
     return _putenv_s(pt.environmentVariable.c_str(), path.c_str()) == 0;
 #elif defined(LINUX)
   if(p != 0)
     return setenv(pt.environmentVariable.c_str(), (path + PATH_SEP + p).c_str(), 1) == 0;
   else
     return setenv(pt.environmentVariable.c_str(), path.c_str(), 1) == 0;
 #endif
 }
bool Voxel::Configuration::_get (const String & type, String & name) protected
Definition at line 205 of file Configuration.cpp.
References _getPaths().
 {
   Vector<String> paths;
   if(!_getPaths(type, paths))
     return false;
   for(auto &p: paths)
   {
     String n = (p.size() > 0)?(p + DIR_SEP + name):name;
     std::ifstream f(n, std::ios::binary);
     if(f.good())
     {
       name = n;
       return true;
     }
   }
   return false;
 }
bool Voxel::Configuration::_getPaths (const String & type, Vector< String > & paths) protected
Definition at line 157 of file Configuration.cpp.
References _pathTypes, Voxel::Configuration::_Path::environmentVariable, Voxel::Logger::getDefaultLogLevel(), getLocalPath(), Voxel::LOG_DEBUG, Voxel::logger, LensCalibrationTest::p1, Voxel::split(), and Voxel::Configuration::_Path::standardPath.
Referenced by _get().
 {
   auto t = _pathTypes.find(type);
   if(t == _pathTypes.end())
     return false;
   const _Path &pt = t->second;
   paths.clear();
   paths.push_back(pt.standardPath);
   char *p = getenv(pt.environmentVariable.c_str());
   if(p != 0)
   {
     String p1(p);
     Vector<String> splits;
     split(p1, PATH_SEP, splits);
     paths.reserve(paths.size() + splits.size());
     paths.insert(paths.begin(), splits.begin(), splits.end()); // Insert at the beginning to override standard path
   }
   String localPath;
   if(getLocalPath(type, localPath))
     paths.insert(paths.begin(), localPath);
   paths.insert(paths.begin(), ""); // Empty path for absolute file paths and also relative file paths
   if(logger.getDefaultLogLevel() >= LOG_DEBUG)
   {
     for(auto i = 0; i < paths.size(); i++)
     {
       logger(LOG_DEBUG) << paths[i];
       if(i < paths.size() - 1)
         logger(LOG_DEBUG) << PATH_SEP;
     }
     logger(LOG_DEBUG) << std::endl;
   }
   return true;
 }
static bool Voxel::Configuration::addConfPath (const String & path) inline static
Definition at line 48 of file Configuration.h.
 { return _addPath("conf", path); }
static bool Voxel::Configuration::addFirmwarePath (const String & path) inline static
Definition at line 47 of file Configuration.h.
 { return _addPath("fw", path); }
static bool Voxel::Configuration::addLibPath (const String & path) inline static
Definition at line 49 of file Configuration.h.
 { return _addPath("lib", path); }
bool Voxel::Configuration::geLibFile (String & fileName) inline
Definition at line 64 of file Configuration.h.
 { return _get("lib", fileName); }
bool Voxel::Configuration::getConfFile (String & fileName) inline
Updates "name" to full path.
Definition at line 62 of file Configuration.h.
Referenced by Voxel::ConfigurationFile::_getData(), Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), Voxel::TI::ToFTintinCamera::_init(), Voxel::TI::ToFFrameGenerator::_readPhaseOffsetCorrection(), Voxel::ConfigurationFile::read(), and Voxel::MainConfigurationFile::readFromHardware().
 { return _get("conf", fileName); }
bool Voxel::Configuration::getConfPaths (Vector< String > & paths) inline
Definition at line 44 of file Configuration.h.
 { return _getPaths("conf", paths); }
bool Voxel::Configuration::getFirmwareFile (String & fileName) inline
Definition at line 63 of file Configuration.h.
Referenced by Voxel::Downloader::_locateFile().
 { return _get("fw", fileName); }
bool Voxel::Configuration::getFirmwarePaths (Vector< String > & paths) inline
Definition at line 43 of file Configuration.h.
 { return _getPaths("fw", paths); }
bool Voxel::Configuration::getLibPaths (Vector< String > & paths) inline
Definition at line 45 of file Configuration.h.
Referenced by Voxel::CameraSystem::_init().
 { return _getPaths("lib", paths); }
bool Voxel::Configuration::getLocalConfFile (String & fileName) inline
Definition at line 58 of file Configuration.h.
Referenced by Voxel::MainConfigurationFile::_saveHardwareImage(), Voxel::ConfigurationFile::_setData(), and Voxel::ConfigurationFile::write().
 { return getLocalFile("conf", fileName); }
bool Voxel::Configuration::getLocalConfPath (String & path) inline
Definition at line 53 of file Configuration.h.
 { return getLocalPath("conf", path); }
bool Voxel::Configuration::getLocalFile (const String & type, String & fileName)
Definition at line 146 of file Configuration.cpp.
References getLocalPath().
 {
   String path;
   if(!getLocalPath(type, path))
     return false;
   name = path + DIR_SEP + name;
   return true;
 }
bool Voxel::Configuration::getLocalFirmwareFile (String & fileName) inline
Definition at line 57 of file Configuration.h.
 { return getLocalFile("fw", fileName); }
bool Voxel::Configuration::getLocalFirmwarePath (String & path) inline
Definition at line 52 of file Configuration.h.
 { return getLocalPath("fw", path); }
bool Voxel::Configuration::getLocalLibFile (String & fileName) inline
Definition at line 59 of file Configuration.h.
 { return getLocalFile("lib", fileName); }
bool Voxel::Configuration::getLocalLibPath (String & path) inline
Definition at line 54 of file Configuration.h.
 { return getLocalPath("lib", path); }
bool Voxel::Configuration::getLocalPath (const String & type, String & path)
Definition at line 93 of file Configuration.cpp.
References Voxel::isFilePresent(), and Voxel::makeDirectory().
Referenced by _getPaths(), and getLocalFile().
 {
   // Adding local path ~/.Voxel/<type>
   // Works typically for Windows
   char *homeDrive = getenv("HOMEDRIVE");
   char *homePath = getenv("HOMEPATH");
   if(homeDrive != 0 && homePath != 0)
   {
     String s = homeDrive;
     s += homePath;
     s += DIR_SEP;
     s += ".Voxel";
     if(!isFilePresent(s) && !makeDirectory(s))
       return false;
     s += DIR_SEP;
     s += type;
     if(!isFilePresent(s) && !makeDirectory(s))
       return false;
     path = s;
     return true;
   }
   // Adding local path ~/.Voxel/<type>
   // Works typically for Linux
   char *home = getenv("HOME");
   if(home != 0)
   {
     String s = home;
     s += DIR_SEP;
     s += ".Voxel";
     if(!isFilePresent(s) && !makeDirectory(s))
       return false;
     s += DIR_SEP;
     s += type;
     if(!isFilePresent(s) && !makeDirectory(s))
       return false;
     path = s;
     return true;
   }
   return false;
 }
Member Data Documentation
const Map< String, Configuration::_Path > Voxel::Configuration::_pathTypes static protected
Definition at line 34 of file Configuration.h.
Referenced by _addPath(), and _getPaths().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp