Voxel: TinyXML2::XMLUtil Class Reference
TinyXML2::XMLUtil Class Reference
Common and Utility classes
#include <TinyXML2.h>
Static Public Member Functions
static const char * SkipWhiteSpace (const char *p)
static char * SkipWhiteSpace (char *p)
static bool IsWhiteSpace (char p)
static bool IsNameStartChar (unsigned char ch)
static bool IsNameChar (unsigned char ch)
static bool StringEqual (const char *p, const char *q, int nChar=INT_MAX)
static bool IsUTF8Continuation (const char p)
static const char * ReadBOM (const char *p, bool *hasBOM)
static const char * GetCharacterRef (const char *p, char *value, int *length)
static void ConvertUTF32ToUTF8 (unsigned long input, char *output, int *length)
static void ToStr (int v, char *buffer, int bufferSize)
static void ToStr (unsigned v, char *buffer, int bufferSize)
static void ToStr (bool v, char *buffer, int bufferSize)
static void ToStr (float v, char *buffer, int bufferSize)
static void ToStr (double v, char *buffer, int bufferSize)
static bool ToInt (const char *str, int *value)
static bool ToUnsigned (const char *str, unsigned *value)
static bool ToBool (const char *str, bool *value)
static bool ToFloat (const char *str, float *value)
static bool ToDouble (const char *str, double *value)
Detailed Description
Definition at line 547 of file TinyXML2.h.
Member Function Documentation
void TinyXML2::XMLUtil::ConvertUTF32ToUTF8 (unsigned long input, char * output, int * length) static
Definition at line 298 of file TinyXML2.cpp.
Referenced by GetCharacterRef().
 {
     const unsigned long BYTE_MASK = 0xBF;
     const unsigned long BYTE_MARK = 0x80;
     const unsigned long FIRST_BYTE_MARK[7] = { 0x00, 0x00, 0xC0, 0xE0, 0xF0, 0xF8, 0xFC };
     if (input < 0x80) {
         *length = 1;
     }
     else if ( input < 0x800 ) {
         *length = 2;
     }
     else if ( input < 0x10000 ) {
         *length = 3;
     }
     else if ( input < 0x200000 ) {
         *length = 4;
     }
     else {
         *length = 0;    // This code won't covert this correctly anyway.
         return;
     }
     output += *length;
     // Scary scary fall throughs.
     switch (*length) {
         case 4:
             --output;
             *output = (char)((input | BYTE_MARK) & BYTE_MASK);
             input >>= 6;
         case 3:
             --output;
             *output = (char)((input | BYTE_MARK) & BYTE_MASK);
             input >>= 6;
         case 2:
             --output;
             *output = (char)((input | BYTE_MARK) & BYTE_MASK);
             input >>= 6;
         case 1:
             --output;
             *output = (char)(input | FIRST_BYTE_MARK[*length]);
         default:
             break;
     }
 }
const char * TinyXML2::XMLUtil::GetCharacterRef (const char * p, char * value, int * length) static
Definition at line 346 of file TinyXML2.cpp.
References ConvertUTF32ToUTF8().
Referenced by TinyXML2::StrPair::GetStr().
 {
     // Presume an entity, and pull it out.
     *length = 0;
     if ( *(p+1) == '#' && *(p+2) ) {
         unsigned long ucs = 0;
         ptrdiff_t delta = 0;
         unsigned mult = 1;
         if ( *(p+2) == 'x' ) {
             // Hexadecimal.
             if ( !*(p+3) ) {
                 return 0;
             }
             const char* q = p+3;
             q = strchr( q, ';' );
             if ( !q || !*q ) {
                 return 0;
             }
             delta = q-p;
             --q;
             while ( *q != 'x' ) {
                 if ( *q >= '0' && *q <= '9' ) {
                     ucs += mult * (*q - '0');
                 }
                 else if ( *q >= 'a' && *q <= 'f' ) {
                     ucs += mult * (*q - 'a' + 10);
                 }
                 else if ( *q >= 'A' && *q <= 'F' ) {
                     ucs += mult * (*q - 'A' + 10 );
                 }
                 else {
                     return 0;
                 }
                 mult *= 16;
                 --q;
             }
         }
         else {
             // Decimal.
             if ( !*(p+2) ) {
                 return 0;
             }
             const char* q = p+2;
             q = strchr( q, ';' );
             if ( !q || !*q ) {
                 return 0;
             }
             delta = q-p;
             --q;
             while ( *q != '#' ) {
                 if ( *q >= '0' && *q <= '9' ) {
                     ucs += mult * (*q - '0');
                 }
                 else {
                     return 0;
                 }
                 mult *= 10;
                 --q;
             }
         }
         // convert the UCS to UTF-8
         ConvertUTF32ToUTF8( ucs, value, length );
         return p + delta + 1;
     }
     return p+1;
 }
static bool TinyXML2::XMLUtil::IsNameChar (unsigned char ch) inline static
Definition at line 572 of file TinyXML2.h.
Referenced by TinyXML2::StrPair::ParseName().
{
         return IsNameStartChar( ch )
                || isdigit( ch )
                || ch == '.'
                || ch == '-';
     }
static bool TinyXML2::XMLUtil::IsNameStartChar (unsigned char ch) inline static
Definition at line 566 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::ParseAttributes(), and TinyXML2::StrPair::ParseName().
{
         return ( ( ch < 128 ) ? isalpha( ch ) : 1 )
                || ch == ':'
                || ch == '_';
     }
static bool TinyXML2::XMLUtil::IsUTF8Continuation (const char p) inline static
Definition at line 595 of file TinyXML2.h.
{
         return ( p & 0x80 ) != 0;
     }
static bool TinyXML2::XMLUtil::IsWhiteSpace (char p) inline static
Definition at line 562 of file TinyXML2.h.
Referenced by TinyXML2::StrPair::CollapseWhitespace().
{
         return !IsUTF8Continuation(p) && isspace( static_cast<unsigned char>(p) );
     }
const char * TinyXML2::XMLUtil::ReadBOM (const char * p, bool * hasBOM) static
Definition at line 283 of file TinyXML2.cpp.
Referenced by TinyXML2::XMLDocument::LoadFile(), and TinyXML2::XMLDocument::Parse().
 {
     *bom = false;
     const unsigned char* pu = reinterpret_cast<const unsigned char*>(p);
     // Check for BOM:
     if (    *(pu+0) == TIXML_UTF_LEAD_0
             && *(pu+1) == TIXML_UTF_LEAD_1
             && *(pu+2) == TIXML_UTF_LEAD_2 ) {
         *bom = true;
         p += 3;
     }
     return p;
 }
static const char* TinyXML2::XMLUtil::SkipWhiteSpace (const char * p) inline static
Definition at line 550 of file TinyXML2.h.
Referenced by TinyXML2::StrPair::CollapseWhitespace(), TinyXML2::XMLDocument::Identify(), TinyXML2::XMLDocument::LoadFile(), TinyXML2::XMLDocument::Parse(), TinyXML2::XMLElement::ParseAttributes(), TinyXML2::XMLAttribute::ParseDeep(), and TinyXML2::XMLElement::ParseDeep().
{
         while( IsWhiteSpace(*p) ) {
             ++p;
         }
         return p;
     }
static char* TinyXML2::XMLUtil::SkipWhiteSpace (char * p) inline static
Definition at line 556 of file TinyXML2.h.
{
         return const_cast<char*>( SkipWhiteSpace( const_cast<const char*>(p) ) );
     }
static bool TinyXML2::XMLUtil::StringEqual (const char * p, const char * q, int nChar = INT_MAX) inline static
Definition at line 579 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::Attribute(), TinyXML2::XMLElement::DeleteAttribute(), TinyXML2::XMLElement::FindAttribute(), TinyXML2::XMLElement::FindOrCreateAttribute(), TinyXML2::XMLNode::FirstChildElement(), TinyXML2::XMLDocument::Identify(), TinyXML2::XMLNode::LastChildElement(), TinyXML2::XMLNode::NextSiblingElement(), TinyXML2::XMLNode::ParseDeep(), TinyXML2::XMLNode::PreviousSiblingElement(), TinyXML2::XMLText::ShallowEqual(), TinyXML2::XMLComment::ShallowEqual(), TinyXML2::XMLDeclaration::ShallowEqual(), TinyXML2::XMLUnknown::ShallowEqual(), TinyXML2::XMLElement::ShallowEqual(), and ToBool().
{
         int n = 0;
         if ( p == q ) {
             return true;
         }
         while( *p && *q && *p == *q && n<nChar ) {
             ++p;
             ++q;
             ++n;
         }
         if ( (n == nChar) || ( *p == 0 && *q == 0 ) ) {
             return true;
         }
         return false;
     }
bool TinyXML2::XMLUtil::ToBool (const char * str, bool * value) static
Definition at line 473 of file TinyXML2.cpp.
References StringEqual(), and ToInt().
Referenced by TinyXML2::XMLElement::QueryBoolText(), and TinyXML2::XMLAttribute::QueryBoolValue().
 {
     int ival = 0;
     if ( ToInt( str, &ival )) {
         *value = (ival==0) ? false : true;
         return true;
     }
     if ( StringEqual( str, "true" ) ) {
         *value = true;
         return true;
     }
     else if ( StringEqual( str, "false" ) ) {
         *value = false;
         return true;
     }
     return false;
 }
bool TinyXML2::XMLUtil::ToDouble (const char * str, double * value) static
Definition at line 500 of file TinyXML2.cpp.
References TIXML_SSCANF.
Referenced by TinyXML2::XMLElement::QueryDoubleText(), and TinyXML2::XMLAttribute::QueryDoubleValue().
 {
     if ( TIXML_SSCANF( str, "%lf", value ) == 1 ) {
         return true;
     }
     return false;
 }
bool TinyXML2::XMLUtil::ToFloat (const char * str, float * value) static
Definition at line 492 of file TinyXML2.cpp.
References TIXML_SSCANF.
Referenced by TinyXML2::XMLElement::QueryFloatText(), and TinyXML2::XMLAttribute::QueryFloatValue().
 {
     if ( TIXML_SSCANF( str, "%f", value ) == 1 ) {
         return true;
     }
     return false;
 }
bool TinyXML2::XMLUtil::ToInt (const char * str, int * value) static
Definition at line 457 of file TinyXML2.cpp.
References TIXML_SSCANF.
Referenced by TinyXML2::XMLElement::QueryIntText(), TinyXML2::XMLAttribute::QueryIntValue(), and ToBool().
 {
     if ( TIXML_SSCANF( str, "%d", value ) == 1 ) {
         return true;
     }
     return false;
 }
void TinyXML2::XMLUtil::ToStr (int v, char * buffer, int bufferSize) static
Definition at line 424 of file TinyXML2.cpp.
References TIXML_SNPRINTF.
Referenced by TinyXML2::XMLPrinter::PushAttribute(), TinyXML2::XMLPrinter::PushText(), TinyXML2::XMLAttribute::SetAttribute(), and TinyXML2::XMLElement::SetText().
 {
     TIXML_SNPRINTF( buffer, bufferSize, "%d", v );
 }
void TinyXML2::XMLUtil::ToStr (unsigned v, char * buffer, int bufferSize) static
Definition at line 430 of file TinyXML2.cpp.
References TIXML_SNPRINTF.
 {
     TIXML_SNPRINTF( buffer, bufferSize, "%u", v );
 }
void TinyXML2::XMLUtil::ToStr (bool v, char * buffer, int bufferSize) static
Definition at line 436 of file TinyXML2.cpp.
References TIXML_SNPRINTF.
 {
     TIXML_SNPRINTF( buffer, bufferSize, "%d", v ? 1 : 0 );
 }
void TinyXML2::XMLUtil::ToStr (float v, char * buffer, int bufferSize) static
Definition at line 445 of file TinyXML2.cpp.
References TIXML_SNPRINTF.
 {
     TIXML_SNPRINTF( buffer, bufferSize, "%.8g", v );
 }
void TinyXML2::XMLUtil::ToStr (double v, char * buffer, int bufferSize) static
Definition at line 451 of file TinyXML2.cpp.
References TIXML_SNPRINTF.
 {
     TIXML_SNPRINTF( buffer, bufferSize, "%.17g", v );
 }
bool TinyXML2::XMLUtil::ToUnsigned (const char * str, unsigned * value) static
Definition at line 465 of file TinyXML2.cpp.
References TIXML_SSCANF.
Referenced by TinyXML2::XMLElement::QueryUnsignedText(), and TinyXML2::XMLAttribute::QueryUnsignedValue().
 {
     if ( TIXML_SSCANF( str, "%u", value ) == 1 ) {
         return true;
     }
     return false;
 }
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp