Voxel: Voxel::TI::VoxelUSBProgrammer Class Reference
Voxel::TI::VoxelUSBProgrammer Class Reference
#include <VoxelUSBProgrammer.h>
Classes
struct RequestParams
Public Types
typedef Map< uint, RequestParams > SlaveAddressToRequestParamsMap
Public Types inherited from Voxel::TI::VoxelProgrammerBase
typedef Map< uint, uint > SlaveAddressToByteMap
Public Member Functions
VoxelUSBProgrammer (const SlaveAddressToByteMap &map, const SlaveAddressToRequestParamsMap &slaveAddressToRequestParamsMap, USBIOPtr &usbIO, DevicePtr device)
virtual bool isInitialized () const
virtual bool reset ()
USBIOPtr & getUSBIO ()
virtual ~VoxelUSBProgrammer ()
Public Member Functions inherited from Voxel::TI::VoxelProgrammerBase
VoxelProgrammerBase (const SlaveAddressToByteMap &map, DevicePtr device)
virtual bool readRegister (uint32_t address, uint32_t &value) const
virtual bool writeRegister (uint32_t address, uint32_t value)
virtual bool getValue (const Parameter &param, uint32_t &value) const
virtual bool setValue (const Parameter &param, uint32_t value, bool writeOnly=false)
virtual ~VoxelProgrammerBase ()
Public Member Functions inherited from Voxel::RegisterProgrammer
virtual ~RegisterProgrammer ()
Protected Member Functions
virtual bool _readRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t &value, uint8_t length) const
virtual bool _writeRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t value, uint8_t length)
Protected Attributes
USBIOPtr _usbIO
SlaveAddressToRequestParamsMap _slaveAddressToRequestParamsMap
Protected Attributes inherited from Voxel::TI::VoxelProgrammerBase
DevicePtr _device
Mutex _mutex
SlaveAddressToByteMap _slaveAddressToByteMap
Detailed Description
Definition at line 19 of file VoxelUSBProgrammer.h.
Member Typedef Documentation
typedef Map<uint, RequestParams> Voxel::TI::VoxelUSBProgrammer::SlaveAddressToRequestParamsMap
Definition at line 28 of file VoxelUSBProgrammer.h.
Constructor & Destructor Documentation
Voxel::TI::VoxelUSBProgrammer::VoxelUSBProgrammer (const SlaveAddressToByteMap & map, const SlaveAddressToRequestParamsMap & slaveAddressToRequestParamsMap, USBIOPtr & usbIO, DevicePtr device)
Definition at line 23 of file VoxelUSBProgrammer.cpp.
References Voxel::LOG_ERROR, Voxel::logger, and Voxel::Device::USB.
                                                                                                                                                                                : VoxelProgrammerBase(map, device),
   _slaveAddressToRequestParamsMap(slaveAddressToRequestParamsMap), _usbIO(usbIO)
 {
   if(device->interfaceID() != Device::USB)
   {
     logger(LOG_ERROR) << "VoxelUSBProgrammer: Invalid device." << std::endl;
     return;
   }
 }
virtual Voxel::TI::VoxelUSBProgrammer::~VoxelUSBProgrammer () inline virtual
Definition at line 45 of file VoxelUSBProgrammer.h.
 {}
Member Function Documentation
bool Voxel::TI::VoxelUSBProgrammer::_readRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t & value, uint8_t length) const protected virtual
Implements Voxel::TI::VoxelProgrammerBase.
Definition at line 33 of file VoxelUSBProgrammer.cpp.
References _slaveAddressToRequestParamsMap, _usbIO, Voxel::USBIO::FROM_DEVICE, Voxel::TI::VoxelUSBProgrammer::RequestParams::leftShiftBits, Voxel::LOG_ERROR, Voxel::logger, Voxel::TI::VoxelUSBProgrammer::RequestParams::readRequestCode, Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, LensCalibrationTest::x, and LensCalibrationTest::y.
 {
   auto x = _slaveAddressToRequestParamsMap.find(slaveAddress);
   if(x == _slaveAddressToRequestParamsMap.end())
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Unknown slave address 0x" << std::hex << slaveAddress << std::endl;
     return false;
   }
   const RequestParams &y = x->second;
   uint16_t l = length;
   if(length == 1) // TPS -- addr[0] == 0x2D
   {
     uint8_t data[1];
     data[0] = 0x0;
     if(!_usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
         y.readRequestCode, slaveAddress << y.leftShiftBits, registerAddress << y.leftShiftBits, data, l))
     {
       logger(LOG_ERROR) << "VoxelUSBProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
     value = data[0];
   }
   else if(length == 3) // ToF -- 0x58, 0x5C
   {
     uint8_t data[3];
     data[0] = 0x0;
     data[1] = 0x0;
     data[2] = 0x0;
     if(!_usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       y.readRequestCode, slaveAddress << y.leftShiftBits, registerAddress << y.leftShiftBits, data, l))
     {
       logger(LOG_ERROR) << "VoxelUSBProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
     value = data[0] + (data[1] << 8) + (data[2] << 16);
   }
   else if(length == 2)
   {
     uint8_t data[2];
     data[0] = 0x0;
     data[1] = 0x0;
     if(!_usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       y.readRequestCode, slaveAddress << y.leftShiftBits, registerAddress << y.leftShiftBits, data, l))
     {
       logger(LOG_ERROR) << "VoxelUSBProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
     value = data[0] + (data[1] << 8);
   }
   else
   {
     logger(LOG_ERROR) << "VoxelUSBProgrammer: Don't know how to read '" << std::dec << length << "' bytes. Required for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::TI::VoxelUSBProgrammer::_writeRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t value, uint8_t length) protected virtual
Implements Voxel::TI::VoxelProgrammerBase.
Definition at line 101 of file VoxelUSBProgrammer.cpp.
References _slaveAddressToRequestParamsMap, _usbIO, Voxel::TI::VoxelUSBProgrammer::RequestParams::leftShiftBits, Voxel::LOG_ERROR, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, Voxel::USBIO::TO_DEVICE, Voxel::TI::VoxelUSBProgrammer::RequestParams::writeRequestCode, LensCalibrationTest::x, and LensCalibrationTest::y.
 {
   auto x = _slaveAddressToRequestParamsMap.find(slaveAddress);
   if(x == _slaveAddressToRequestParamsMap.end())
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Unknown slave address 0x" << std::hex << slaveAddress << std::endl;
     return false;
   }
   RequestParams &y = x->second;
   uint16_t l = length;
   if(length == 1) // TPS  -- slaveAddress == 0x2D
   {
     uint8_t data[1];
     data[0] = value & 0xFF;
     if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       y.writeRequestCode, slaveAddress << y.leftShiftBits, registerAddress << y.leftShiftBits, data, l))
     {
       logger(LOG_ERROR) << "VoxelUSBProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
   }
   else if(length == 3) // ToF
   {
     uint8_t data[3];
     data[0] = (value & 0xFF);
     data[1] = (value >> 8) & 0xFF;
     data[2] = (value >> 16) & 0xFF;
     if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       y.writeRequestCode, slaveAddress << y.leftShiftBits, registerAddress << y.leftShiftBits, data, l))
     {
       logger(LOG_ERROR) << "VoxelUSBProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
   }
   else if(length == 2)
   {
     uint8_t data[2];
     data[0] = (value & 0xFF);
     data[1] = (value >> 8) & 0xFF;
     if(!_usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       y.writeRequestCode, slaveAddress << y.leftShiftBits, registerAddress << y.leftShiftBits, data, l))
     {
       logger(LOG_ERROR) << "VoxelUSBProgrammer: Could not read register for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
       return false;
     }
   }
   else
   {
     logger(LOG_ERROR) << "VoxelUSBProgrammer: Don't know how to write '" << std::dec << length << "' bytes. Required for address 0x" << std::hex << slaveAddress << registerAddress << std::endl;
     return false;
   }
   return true;
 }
USBIOPtr& Voxel::TI::VoxelUSBProgrammer::getUSBIO () inline
Definition at line 43 of file VoxelUSBProgrammer.h.
Referenced by Voxel::TI::TintinCDKCamera::_getEEPROMSize(), Voxel::TI::TintinCDKCamera::_readConfigFromHardware(), Voxel::TI::TintinCDKCamera::_writeConfigFromHardware(), and Voxel::TI::ToFCamera::setSerialNumber().
 { return _usbIO; }
bool Voxel::TI::VoxelUSBProgrammer::isInitialized () const virtual
Implements Voxel::RegisterProgrammer.
Definition at line 17 of file VoxelUSBProgrammer.cpp.
References _usbIO.
Referenced by reset().
 {
   return _usbIO->isInitialized();
 }
bool Voxel::TI::VoxelUSBProgrammer::reset () virtual
Implements Voxel::RegisterProgrammer.
Definition at line 163 of file VoxelUSBProgrammer.cpp.
References isInitialized(), Voxel::LOG_WARNING, and Voxel::logger.
 {
   if(!isInitialized())
     return false;
   logger(LOG_WARNING) << "VoxelUSBProgrammer: Don't know how to reset the device." << std::endl;
   return true;
 }
Member Data Documentation
SlaveAddressToRequestParamsMap Voxel::TI::VoxelUSBProgrammer::_slaveAddressToRequestParamsMap protected
Definition at line 31 of file VoxelUSBProgrammer.h.
Referenced by _readRegister(), and _writeRegister().
USBIOPtr Voxel::TI::VoxelUSBProgrammer::_usbIO protected
Definition at line 30 of file VoxelUSBProgrammer.h.
Referenced by _readRegister(), _writeRegister(), and isInitialized().
The documentation for this class was generated from the following files:
VoxelUSBProgrammer.h
VoxelUSBProgrammer.cpp