Voxel: Voxel::USBBulkStreamer Class Reference
Voxel::USBBulkStreamer Class Reference
I/O classes
#include <USBBulkStreamer.h>
Classes
class USBBulkStreamerPrivate
Public Member Functions
USBBulkStreamer (USBIOPtr &usbIO, DevicePtr device, uint8_t endpoint)
virtual ~USBBulkStreamer ()
virtual bool isInitialized ()
virtual bool setBufferSize (size_t bufferSize)
virtual bool getSupportedVideoModes (Vector< VideoMode > &videoModes)
virtual bool getCurrentVideoMode (VideoMode &videoMode)
virtual bool setVideoMode (const VideoMode &videoMode)
Public Member Functions inherited from Voxel::Streamer
Streamer (DevicePtr device)
virtual ~Streamer ()
virtual bool isRunning ()
virtual bool start ()
virtual bool capture (RawDataFramePtr &p)
virtual bool stop ()
Protected Member Functions
virtual bool _start ()
virtual bool _capture (RawDataFramePtr &p)
virtual bool _stop ()
Protected Attributes
Ptr< USBBulkStreamerPrivate > _usbBulkStreamerPrivate
Protected Attributes inherited from Voxel::Streamer
DevicePtr _device
Timer _time
int _currentID = -1
TimeStampType _currentTimeStamp = 0
bool _isRunning = false
Detailed Description
Definition at line 21 of file USBBulkStreamer.h.
Constructor & Destructor Documentation
Voxel::USBBulkStreamer::USBBulkStreamer (USBIOPtr & usbIO, DevicePtr device, uint8_t endpoint)
Definition at line 220 of file USBBulkStreamer.cpp.
References _usbBulkStreamerPrivate.
                                                                                    : Streamer(device)
 {
   _usbBulkStreamerPrivate = Ptr<USBBulkStreamerPrivate> (new USBBulkStreamerPrivate(usbIO, device, endpoint));
 }
Voxel::USBBulkStreamer::~USBBulkStreamer () virtual
Definition at line 225 of file USBBulkStreamer.cpp.
 {
 }
Member Function Documentation
bool Voxel::USBBulkStreamer::_capture (RawDataFramePtr & p) protected virtual
Implements Voxel::Streamer.
Definition at line 234 of file USBBulkStreamer.cpp.
References Voxel::Streamer::_currentID, and _usbBulkStreamerPrivate.
 {
   if(_usbBulkStreamerPrivate->getBuffer(2000, p))
   {
     p->id = _currentID++;
     return true;
   }
   return false;
 }
bool Voxel::USBBulkStreamer::_start () protected virtual
Implements Voxel::Streamer.
Definition at line 229 of file USBBulkStreamer.cpp.
References _usbBulkStreamerPrivate.
 {
   return _usbBulkStreamerPrivate->start();
 }
bool Voxel::USBBulkStreamer::_stop () protected virtual
Implements Voxel::Streamer.
Definition at line 244 of file USBBulkStreamer.cpp.
References _usbBulkStreamerPrivate.
 {
   return _usbBulkStreamerPrivate->stop();
 }
bool Voxel::USBBulkStreamer::getCurrentVideoMode (VideoMode & videoMode) virtual
Implements Voxel::Streamer.
Definition at line 260 of file USBBulkStreamer.cpp.
 {
   return false;
 }
bool Voxel::USBBulkStreamer::getSupportedVideoModes (Vector< VideoMode > & videoModes) virtual
Implements Voxel::Streamer.
Definition at line 254 of file USBBulkStreamer.cpp.
 {
   videoModes.clear();
   return true; // No specific video modes
 }
bool Voxel::USBBulkStreamer::isInitialized () virtual
Implements Voxel::Streamer.
Definition at line 249 of file USBBulkStreamer.cpp.
 {
   return true;
 }
bool Voxel::USBBulkStreamer::setBufferSize (size_t bufferSize) virtual
Definition at line 270 of file USBBulkStreamer.cpp.
References _usbBulkStreamerPrivate.
Referenced by Voxel::TI::CalculusCDKCamera::_setStreamerFrameSize(), Voxel::TI::HaddockCDKCamera::_setStreamerFrameSize(), and Voxel::TI::TintinCDKCamera::_setStreamerFrameSize().
 {
   return _usbBulkStreamerPrivate->setBufferSize(bufferSize);
 }
bool Voxel::USBBulkStreamer::setVideoMode (const VideoMode & videoMode) virtual
Implements Voxel::Streamer.
Definition at line 265 of file USBBulkStreamer.cpp.
 {
   return true;
 }
Member Data Documentation
Ptr<USBBulkStreamerPrivate> Voxel::USBBulkStreamer::_usbBulkStreamerPrivate protected
Definition at line 24 of file USBBulkStreamer.h.
Referenced by _capture(), _start(), _stop(), setBufferSize(), and USBBulkStreamer().
The documentation for this class was generated from the following files:
USBBulkStreamer.h
USBBulkStreamer.cpp