Voxel: ELFIO::elfio::Sections Class Reference
ELFIO::elfio::Sections Class Reference
#include <elfio.hpp>
Public Member Functions
Sections (elfio *parent_)
Elf_Half size () const
section * operator[] (unsigned int index) const
section * operator[] (const std::string &name) const
section * add (const std::string &name)
std::vector< section * >::iterator begin ()
std::vector< section * >::iterator end ()
Private Attributes
elfio * parent
Detailed Description
Definition at line 702 of file elfio.hpp.
Constructor & Destructor Documentation
ELFIO::elfio::Sections::Sections (elfio * parent_) inline
Definition at line 705 of file elfio.hpp.
                                    :
             parent( parent_ )
         {
         }
Member Function Documentation
section* ELFIO::elfio::Sections::add (const std::string & name) inline
Definition at line 747 of file elfio.hpp.
References ELFIO::string_section_accessor::add_string(), ELFIO::elfio::create_section(), parent, and ELFIO::elfio::sections_.
Referenced by ELFIO::elfio::create_mandatory_sections().
         {
             section* new_section = parent->create_section();
             new_section->set_name( name );
             Elf_Half str_index = parent->get_section_name_str_index();
             section* string_table( parent->sections_[str_index] );
             string_section_accessor str_writer( string_table );
             Elf_Word pos = str_writer.add_string( name );
             new_section->set_name_string_offset( pos );
             return new_section;
         }
std::vector<section*>::iterator ELFIO::elfio::Sections::begin () inline
Definition at line 762 of file elfio.hpp.
References parent, and ELFIO::elfio::sections_.
{
             return parent->sections_.begin();
         }
std::vector<section*>::iterator ELFIO::elfio::Sections::end () inline
Definition at line 767 of file elfio.hpp.
References parent, and ELFIO::elfio::sections_.
{
             return parent->sections_.end();
         }
section* ELFIO::elfio::Sections::operator[] (unsigned int index) const inline
Definition at line 717 of file elfio.hpp.
References parent, and ELFIO::elfio::sections_.
         {
             section* sec = 0;
             if ( index < parent->sections_.size() ) {
                 sec = parent->sections_[index];
             }
             return sec;
         }
section* ELFIO::elfio::Sections::operator[] (const std::string & name) const inline
Definition at line 729 of file elfio.hpp.
References parent, and ELFIO::elfio::sections_.
         {
             section* sec = 0;
             std::vector<section*>::const_iterator it;
             for ( it = parent->sections_.begin();
                   it != parent->sections_.end();
                   ++it ) {
                 if ( (*it)->get_name() == name ) {
                     sec = *it;
                     break;
                 }
             }
             return sec;
         }
Elf_Half ELFIO::elfio::Sections::size () const inline
Definition at line 711 of file elfio.hpp.
References parent, and ELFIO::elfio::sections_.
Referenced by ELFIO::dump::dynamic_tags(), ELFIO::symbol_section_accessor::find_hash_section(), Voxel::DepthCameraLibrary::getABIVersion(), ELFIO::elfio::layout_segments_and_their_sections(), ELFIO::elfio::load_segments(), ELFIO::dump::notes(), ELFIO::elfio::save(), ELFIO::dump::section_datas(), ELFIO::dump::section_headers(), and ELFIO::dump::symbol_tables().
         {
             return (Elf_Half)parent->sections_.size();
         }
Member Data Documentation
elfio* ELFIO::elfio::Sections::parent private
Definition at line 773 of file elfio.hpp.
Referenced by add(), begin(), end(), operator[](), and size().
The documentation for this class was generated from the following file:
elfio.hpp