Voxel: Voxel::TI::HaddockVCOFrequency Class Reference
Voxel::TI::HaddockVCOFrequency Class Reference
Custom parameters.
Public Member Functions
HaddockVCOFrequency (ToFHaddockCamera &depthCamera, RegisterProgrammer &programmer)
virtual bool get (float &value, bool refresh=false)
virtual bool set (const float &value)
virtual ~HaddockVCOFrequency ()
Public Member Functions inherited from Voxel::FloatParameter
FloatParameter (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, float lowerLimit, float upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual ~FloatParameter ()
Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &lowerLimit, const float &upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const float lowerLimit () const
virtual const float upperLimit () const
virtual void setLowerLimit (floatlowerLimit)
virtual void setUpperLimit (floatupperLimit)
virtual bool validate (const float &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< float >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool refresh ()
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFHaddockCamera & _depthCamera
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::FloatParameter
static Ptr< FloatParameter > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
static Ptr
< RangeParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< float >
static Ptr< ParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::FloatParameter
virtual float _fromRawValue (uint32_t value) const
virtual uint32_t _toRawValue (float value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< float >
float _lowerLimit
float _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< float >
float _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Custom parameters.
Definition at line 21 of file ToFHaddockCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::HaddockVCOFrequency::HaddockVCOFrequency (ToFHaddockCamera & depthCamera, RegisterProgrammer & programmer) inline
Definition at line 25 of file ToFHaddockCamera.cpp.
References MOD_M, and MOD_N.
                                                                                     :
   FloatParameter(programmer, VCO_FREQ, "MHz", 0, 0, 0, 1, 600, 1200, 864, "VCO frequency",
                  "Frequency of the VCO used for generating modulation frequencies", IOType::IO_READ_WRITE, {MOD_M, MOD_N}), _depthCamera(depthCamera) {}
virtual Voxel::TI::HaddockVCOFrequency::~HaddockVCOFrequency () inline virtual
Definition at line 77 of file ToFHaddockCamera.cpp.
 {}
Member Function Documentation
virtual bool Voxel::TI::HaddockVCOFrequency::get (float & value, bool refresh = false) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 29 of file ToFHaddockCamera.cpp.
References _depthCamera, Voxel::DepthCamera::_get(), Voxel::TI::ToFHaddockCamera::_getSystemClockFrequency(), MOD_M, MOD_N, Voxel::ParameterTemplate< float >::refresh(), and Voxel::RangeParameterTemplate< float >::validate().
Referenced by Voxel::TI::HaddockModulationFrequencyParameter::set().
   {
     uint modM, modN, systemClockFrequency;
     if(!_depthCamera._get(MOD_M, modM, refresh) || !_depthCamera._get(MOD_N, modN, refresh) || !_depthCamera._getSystemClockFrequency(systemClockFrequency))
       return false;
     if(modN == 0)
       return false;
     float v = systemClockFrequency*modM/modN;
     if(!validate(v))
       return false;
     value = v;
     return true;
   }
virtual bool Voxel::TI::HaddockVCOFrequency::set (const float & value) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 47 of file ToFHaddockCamera.cpp.
References _depthCamera, Voxel::TI::ToFHaddockCamera::_getSystemClockFrequency(), Voxel::DepthCamera::_set(), Voxel::ParameterTemplate< float >::_value, MOD_M, MOD_N, and Voxel::RangeParameterTemplate< float >::validate().
Referenced by Voxel::TI::HaddockModulationFrequencyParameter::set().
   {
     if(!validate(value))
       return false;
     uint modM, modN, systemClockFrequency;
     if(!_depthCamera._getSystemClockFrequency(systemClockFrequency))
       return false;
     modN = 18;
     if(systemClockFrequency == 0)
       return false;
     modM = value*modN/2/systemClockFrequency;
     modM *= 2;  // mod_m lsbit has no effect and should be set to 0
     if(!_depthCamera._set(MOD_N, modN))
       return false;
     std::this_thread::sleep_for(std::chrono::milliseconds(10));
     if(!_depthCamera._set(MOD_M, modM))
       return false;
     _value = modM*systemClockFrequency/modN;
     return true;
   }
Member Data Documentation
ToFHaddockCamera& Voxel::TI::HaddockVCOFrequency::_depthCamera private
Definition at line 23 of file ToFHaddockCamera.cpp.
Referenced by get(), and set().
The documentation for this class was generated from the following file:
ToFHaddockCamera.cpp