Voxel: Voxel::Data2DCodec Class Reference
Voxel::Data2DCodec Class Reference
Filter related classes
This class is used for compressing and decompressing 16-bit signed data.
#include <Data2DCodec.h>
Classes
struct EightBitOffset
Public Types
typedef Vector< ByteType > ByteArray
typedef Vector< uint8_t > ArrayBool2D
typedef int16_t Array2DElementType
typedef Vector
< Array2DElementType > Array2D
Public Member Functions
Data2DCodec ()
bool compress (const Array2D &in, const ArrayBool2D &invalidPixels, ByteArray &out)
bool decompress (const ByteArray &in, Array2D &out)
bool writeGrayBMPImage (const String &fileName, const Array2D &a, const uint16_t rows, const uint16_t columns)
bool writeGrayBMPImage (const String &fileName, const Complex2D &c)
virtual ~Data2DCodec ()
Detailed Description
This class is used for compressing and decompressing 16-bit signed data.
Primary application of this is for 2D phase offset data compression to store in permanent memory of depth camera
Definition at line 30 of file Data2DCodec.h.
Member Typedef Documentation
typedef Vector<Array2DElementType> Voxel::Data2DCodec::Array2D
Definition at line 46 of file Data2DCodec.h.
typedef int16_t Voxel::Data2DCodec::Array2DElementType
Definition at line 45 of file Data2DCodec.h.
typedef Vector<uint8_t> Voxel::Data2DCodec::ArrayBool2D
Definition at line 44 of file Data2DCodec.h.
typedef Vector<ByteType> Voxel::Data2DCodec::ByteArray
Definition at line 43 of file Data2DCodec.h.
Constructor & Destructor Documentation
Voxel::Data2DCodec::Data2DCodec () inline
Definition at line 49 of file Data2DCodec.h.
 {}
virtual Voxel::Data2DCodec::~Data2DCodec () inline virtual
Definition at line 57 of file Data2DCodec.h.
 {}
Member Function Documentation
bool Voxel::Data2DCodec::compress (const Array2D & in, const ArrayBool2D & invalidPixels, ByteArray & out)
Definition at line 196 of file Data2DCodec.cpp.
References Voxel::Data2DCodec::EightBitOffset::c, Voxel::SerializedObject::currentPutOffset(), Voxel::SerializedObject::getBytes(), Voxel::Data2DCodec::EightBitOffset::index, Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, MAX_OFFSET_COUNT, Voxel::SerializedObject::put(), QUANTIZATION, Voxel::Data2DCodec::EightBitOffset::r, and Voxel::SerializedObject::resize().
Referenced by Voxel::ConfigurationFile::_serializeAllDataFiles(), and main().
 {
   uint16_t rows = *(uint16_t *)&in[0];
   uint16_t columns = *(uint16_t *)&in[1];
   uint16_t dealiasPhaseMask = *(uint16_t *)&in[2];
   const int16_t *inData = &in[3];
   logger(LOG_DEBUG) << "Data2DCodec: rows = " << rows << ", columns = " << columns << std::endl;
   bool noInvalidPixels = (invalidPixels.size() == 0);
   if(in.size() != rows*columns + 3 || (!noInvalidPixels && invalidPixels.size() != rows*columns))
   {
     logger(LOG_ERROR) << "Data2DCodec: Invalid input data size. Expected " << rows*columns*2 + 6
     << " bytes, got " << in.size()*2 << " bytes" << std::endl;
     return false;
   }
   if(rows % 8 != 0 || columns % 8 != 0)
   {
     logger(LOG_ERROR) << "Data2DCodec: Invalid input data. This codec is designed for only rows and columns which are multiples of 8." << std::endl;
     return false;
   }
   SerializedObject so;
   so.resize(rows*columns*sizeof(in[0])*10); // Maximum size needed
   uint16_t version = 0;
   so.put((const char *)&version, sizeof(version));
   so.put((const char *)&rows, sizeof(rows));
   so.put((const char *)&columns, sizeof(columns));
   so.put((const char *)&dealiasPhaseMask, sizeof(dealiasPhaseMask));
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentPutOffset() << std::endl;
   Vector<int32_t> averages(rows/8*columns/8);
   List<EightBitOffset> offsets;
   Vector<int8_t> fourBitOffsets;
   fourBitOffsets.resize(rows*columns);
   for(auto i = 0; i < averages.size(); i++)
     averages[i] = 0;
   for(auto i = 0; i < rows; i++)
     for(auto j = 0; j < columns; j++)
       averages[i/8*columns/8 + j/8] += inData[i*columns + j];
   for(auto i = 0; i < averages.size(); i++)
   {
     averages[i] /= 64;
     int16_t d = averages[i];
     so.put((const char *)&d, sizeof(d));
   }
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentPutOffset() << std::endl;
   uint32_t invalidPixelCount = 0;
   for(auto i = 0; i < rows; i++)
   {
     for(auto j = 0; j < columns; j++)
     {
       int index = i/8*columns/8 + j/8;
       int16_t v = (inData[i*columns + j] - averages[index])/QUANTIZATION;
       if(!noInvalidPixels && invalidPixels[i*columns + j])
       {
         invalidPixelCount++;
         v = 0;
       }
       if(v > 7 || v < -7)
       {
         if(v > 127)
           v = 127;
         else if(v < -128)
           v = -128;
         offsets.push_back(EightBitOffset(i, j, v, offsets.size()));
         fourBitOffsets[i*columns + j] = 8;
       }
       else
         fourBitOffsets[i*columns + j] = v;
     }
   }
   int midRow = rows/2, midColumn = columns/2;
   uint32_t offsetCount = offsets.size();
   if(offsets.size() > MAX_OFFSET_COUNT)
   {
     // Ignore extra offsets near the edges
     offsets.sort([&](const EightBitOffset &a, const EightBitOffset &b) -> bool  {
         return (a.r - midRow)*(a.r - midRow) + (a.c - midColumn)*(a.c - midColumn) <
             (b.r - midRow)*(b.r - midRow) + (b.c - midColumn)*(b.c - midColumn);
       });
     auto o = offsets.begin();
     std::advance(o, MAX_OFFSET_COUNT);
     for(; o != offsets.end(); o++)
     {
       if(o->offset > 0)
         fourBitOffsets[o->r*columns + o->c] = 7;
       else
         fourBitOffsets[o->r*columns + o->c] = -7;
     }
     o = offsets.begin();
     std::advance(o, MAX_OFFSET_COUNT);
     offsets.erase(o, offsets.end());
     // Reorder in index order
     offsets.sort([&](const EightBitOffset &a, const EightBitOffset &b) -> bool  {
       return a.index < b.index;
     });
   }
   for(auto i = 0; i < fourBitOffsets.size(); i += 2)
   {
     uint8_t d = (((uint8_t)fourBitOffsets[i]) & 0xF) + ((((uint8_t)fourBitOffsets[i + 1]) & 0xF) << 4);
     so.put((const char *)&d, 1);
   }
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentPutOffset() << std::endl;
   for(auto o = offsets.begin(); o != offsets.end(); o++)
   {
     so.put((const char *)&o->offset, 1);
   }
   so.put((const char *)&offsetCount, sizeof(offsetCount));
   so.put((const char *)&invalidPixelCount, sizeof(invalidPixelCount));
   logger(LOG_DEBUG) << "Data2DCodec: Number of 8-bit offsets = " << offsetCount << std::endl;
   logger(LOG_DEBUG) << "Data2DCodec: Number of invalid pixels = " << invalidPixelCount << std::endl;
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentPutOffset() << std::endl;
   out.resize(so.currentPutOffset());
   memcpy(out.data(), so.getBytes().data(), out.size());
   return true;
 }
bool Voxel::Data2DCodec::decompress (const ByteArray & in, Array2D & out)
Definition at line 359 of file Data2DCodec.cpp.
References Voxel::SerializedObject::currentGetOffset(), Voxel::SerializedObject::get(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::SerializedObject::put(), QUANTIZATION, and Voxel::SerializedObject::resize().
Referenced by main(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   SerializedObject so;
   so.resize(in.size()); // Maximum size needed
   so.put((const char *)in.data(), in.size()*sizeof(in[0]));
   uint16_t version;
   so.get((char *)&version, sizeof(version));
   uint16_t rows, columns, dealiasPhaseMask;
   so.get((char *)&rows, sizeof(rows));
   so.get((char *)&columns, sizeof(columns));
   so.get((char *)&dealiasPhaseMask, sizeof(dealiasPhaseMask));
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentGetOffset() << std::endl;
   if(rows % 8 != 0 || columns % 8 != 0)
   {
     logger(LOG_ERROR) << "Data2DCodec: Invalid input data. This codec is designed for only rows and columns which are multiples of 8." << std::endl;
     return false;
   }
   logger(LOG_DEBUG) << "Data2DCodec: rows = " << rows << ", columns = " << columns << std::endl;
   Vector<int16_t> averages(rows/8*columns/8);
   so.get((char *)averages.data(), averages.size()*sizeof(averages[0]));
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentGetOffset() << std::endl;
   out.resize(rows*columns + 3);
   *(uint16_t *)&out[0] = rows;
   *(uint16_t *)&out[1] = columns;
   *(uint16_t *)&out[2] = dealiasPhaseMask;
   int16_t *outData = &out[3];
   for(auto i = 0; i < rows; i++)
   {
     for(auto j = 0; j < columns; j++)
     {
       outData[i*columns + j] = averages[i/8*columns/8 + j/8];
     }
   }
   //writeGrayBMPImage("trialI0.bmp", out, rows, columns);
   Vector<uint8_t> fourBitOffsets;
   fourBitOffsets.resize(rows*columns/2);
   so.get((char *)fourBitOffsets.data(), fourBitOffsets.size());
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentGetOffset() << std::endl;
   uint32_t offsetCount = 0;
   for(auto i = 0; i < rows; i++)
   {
     for(auto j = 0; j < columns; j += 2)
     {
       uint8_t d = fourBitOffsets[i*columns/2 + j/2];
       int8_t d1 = d & 0xF;
       if(d1 != 8)
       {
         if(d1 > 8)
           d1 = d1 - 16;
         outData[i*columns + j] += d1*QUANTIZATION;
       }
       else
       {
         int8_t o;
         so.get((char *)&o, sizeof(o));
         outData[i*columns + j] += o;
         offsetCount++;
       }
       int8_t d2 = (d & 0xF0) >> 4;
       if(d2 != 8)
       {
         if(d2 > 8)
           d2 = d2 - 16;
         outData[i*columns + j + 1] += d2*QUANTIZATION;
       }
       else
       {
         int8_t o;
         so.get((char *)&o, sizeof(o));
         outData[i*columns + j + 1] += o*QUANTIZATION;
         offsetCount++;
       }
     }
   }
   logger(LOG_DEBUG) << "Data2DCodec: current number of bytes = " << so.currentGetOffset() << std::endl;
   //writeGrayBMPImage("trialI1.bmp", out, rows, columns);
   uint32_t totalOffsetCount;
   so.get((char *)&totalOffsetCount, sizeof(totalOffsetCount));
   uint32_t invalidPixelCount;
   so.get((char *)&invalidPixelCount, sizeof(invalidPixelCount));
   logger(LOG_INFO) << "Data2DCodec: Original number of 8-bit offsets = " << totalOffsetCount << std::endl;
   logger(LOG_INFO) << "Data2DCodec: Number of invalid pixels in original data = " << invalidPixelCount << std::endl;
   logger(LOG_INFO) << "Data2DCodec: Current number of 8-bit offsets = " << offsetCount << std::endl;
   return true;
 }
bool Voxel::Data2DCodec::writeGrayBMPImage (const String & fileName, const Array2D & a, const uint16_t rows, const uint16_t columns)
Definition at line 350 of file Data2DCodec.cpp.
References Voxel::BMP::writeGrayScale().
 {
   BMP bmp;
   return bmp.writeGrayScale(fileName, a, rows, columns);
 }
bool Voxel::Data2DCodec::writeGrayBMPImage (const String & fileName, const Complex2D & c)
The documentation for this class was generated from the following files:
Data2DCodec.h
Data2DCodec.cpp