Voxel: Voxel::TI::ToFCalculusCamera Class Reference
Voxel::TI::ToFCalculusCamera Class Reference
#include <ToFCalculusCamera.h>
Public Member Functions
ToFCalculusCamera (const String &name, DevicePtr device)
virtual ~ToFCalculusCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, const String &chipset, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, const String &chipset, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, const String &chipset, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
const String & chipset () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
bool isPaused () const
bool pause ()
bool resume ()
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (int &id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _initStartParams ()
virtual bool _getIlluminationFrequency (float &frequency) const
bool _getMaximumFrameSize (FrameSize &s) const
virtual bool _getFrameSize (Voxel::FrameSize &s) const
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
bool _updateEasyConf ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _setStreamerFrameSize (const FrameSize &s)=0
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getDealiasedPhaseMask (int &dealiasedPhaseMask)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const =0
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const =0
virtual bool _getFieldOfView (float &fovHalfAngle) const =0
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Map< String,
CalibrationInformation > & _getCalibrationInformationStructure ()
Friends
class CalculusVCOFrequency
class CalculusModulationFrequencyParameter
class CalculusIntegDutyCycle
class CalculusPixCntMax
class CalculusSubFrameCntMax
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
String _chipset
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
bool _isPaused
Detailed Description
Definition at line 67 of file ToFCalculusCamera.h.
Constructor & Destructor Documentation
Voxel::TI::ToFCalculusCamera::ToFCalculusCamera (const String & name, DevicePtr device)
Definition at line 245 of file ToFCalculusCamera.cpp.
                                                                         : ToFCamera(name, "calculus.ti", device)
 {
 }
virtual Voxel::TI::ToFCalculusCamera::~ToFCalculusCamera () inline virtual
Definition at line 108 of file ToFCalculusCamera.h.
 {}
Member Function Documentation
bool Voxel::TI::ToFCalculusCamera::_allowedROI (String & message) protected virtual
Implements Voxel::DepthCamera.
Definition at line 506 of file ToFCalculusCamera.cpp.
 {
   message  = "Column start and end must be multiples of 16, both between 0 to 319. ";
   message += "Row start and end must be between 0 to 239.";
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_applyCalibrationParams () protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 646 of file ToFCalculusCamera.cpp.
 {
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getBinning (uint & rowsToMerge, uint & columnsToMerge) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 581 of file ToFCalculusCamera.cpp.
 {
   rowsToMerge = columnsToMerge = 1;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getBytesPerPixel (uint & bpp) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 256 of file ToFCalculusCamera.cpp.
Referenced by Voxel::TI::CalculusCDKCamera::_setStreamerFrameSize().
 {
   bpp = (uint) 4;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getCurrentProfileRegisterName (String & name) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 651 of file ToFCalculusCamera.cpp.
 {
   return false;
 }
bool Voxel::TI::ToFCalculusCamera::_getFrameRate (FrameRate & r) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 268 of file ToFCalculusCamera.cpp.
References Voxel::FrameRate::denominator, and Voxel::FrameRate::numerator.
 {
   r.numerator = 30;
   r.denominator = 1;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getFrameSize (Voxel::FrameSize & s) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 249 of file ToFCalculusCamera.cpp.
References Voxel::FrameSize::height, and Voxel::FrameSize::width.
Referenced by _setROI().
 {
   s.width = 80;
   s.height = 60;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getIlluminationFrequency (float & frequency) const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 605 of file ToFCalculusCamera.cpp.
References DEALIAS_EN, Voxel::gcd(), MOD_FREQ1, MOD_FREQ2, MOD_PS1, and MOD_PS2.
 {
   float modulationFrequency1, modulationFrequency2;
   bool dealiasingEnabled;
   uint modulationPS1, modulationPS2;
 #if 0
   if(!get(DEALIAS_EN, dealiasingEnabled))
     return false;
   if(dealiasingEnabled)
   {
     if(!get(MOD_FREQ1, modulationFrequency1) || !get(MOD_FREQ2, modulationFrequency2)) // ensure that these are valid
       return false;
     if(!get(MOD_PS1, modulationPS1) || !get(MOD_PS2, modulationPS2))
       return false;
     frequency = modulationFrequency1*gcd(modulationPS1, modulationPS2)/modulationPS2;
     return true;
   }
   else
   {
     if(!get(MOD_FREQ1, frequency))
       return false;
     return true;
   }
 #endif
   frequency = 19.2;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getMaximumFrameSize (FrameSize & s) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 287 of file ToFCalculusCamera.cpp.
References Voxel::FrameSize::height, and Voxel::FrameSize::width.
 {
   s.width = 80;
   s.height = 60;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getOpDataArrangeMode (int & dataArrangeMode) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 262 of file ToFCalculusCamera.cpp.
 {
   dataArrangeMode = 0;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getROI (RegionOfInterest & roi) protected virtual
Implements Voxel::DepthCamera.
Definition at line 513 of file ToFCalculusCamera.cpp.
References Voxel::DepthCamera::_get(), COL_END, COL_START, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, ROW_END, ROW_START, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
 #if 0
   uint rowStart, rowEnd, colStart, colEnd;
   if(!_get(ROW_START, rowStart) || !_get(ROW_END, rowEnd) || !_get(COL_START, colStart) || !_get(COL_END, colEnd))
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Could not get necessary parameters for ROI." << std::endl;
     return false;
   }
   colStart = colStart*2;
   colEnd = (colEnd + 1)*2 - 1;
   roi.x = colStart;
   roi.y = rowStart;
   roi.width = colEnd - colStart + 1;
   roi.height = rowEnd - rowStart + 1;
 #else
   roi.x = 0;
   roi.y = 0;
   roi.width = 80;
   roi.height = 60;
 #endif
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getSystemClockFrequency (uint & frequency) const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 280 of file ToFCalculusCamera.cpp.
Referenced by Voxel::TI::CalculusVCOFrequency::set().
 {
   frequency = 24;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_getToFFrameType (ToFFrameType & frameType) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 599 of file ToFCalculusCamera.cpp.
References Voxel::ToF_PHASE_AMPLITUDE.
 {
   frameType = ToF_PHASE_AMPLITUDE;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_init () protected
Definition at line 365 of file ToFCalculusCamera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::TI::ToFCamera::_init(), Voxel::DepthCamera::_parameterInit, Voxel::DepthCamera::_programmer, CalculusIntegDutyCycle, CalculusModulationFrequencyParameter, CalculusPixCntMax, CalculusSubFrameCntMax, Voxel::DepthCamera::configFile, Voxel::MainConfigurationFile::get(), Voxel::Configuration::getConfFile(), Voxel::ParameterDMLParser::getParameters(), Voxel::LOG_ERROR, Voxel::logger, MOD_FREQ1, MOD_PS1, and Voxel::DepthCamera::name().
Referenced by Voxel::TI::CalculusCDKCamera::_init().
 {
   Configuration c;
   String name = configFile.get("core", "dml");
   if(!name.size() || !c.getConfFile(name)) // true => name is now a proper path
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Failed to locate/read DML file '" << name << "'" << std::endl;
     return false;
   }
   ParameterDMLParser p(*_programmer, name);
   Vector<ParameterPtr> params;
   if(!p.getParameters(params))
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Could not read parameters from DML file '" << name << "'" << std::endl;
     return _parameterInit = false;
   }
   for(auto &p: params)
   {
     if((p->address() >> 8) == 0) // bankId == 0
       p->setAddress((0x58 << 8) + p->address());
     else if((p->address() >> 8) == 3) // bankId == 3
       p->setAddress((0x5C << 8) + (p->address() & 0xFF));
   }
   if(!_addParameters(params))
     return false;
   if(!_addParameters({
     ParameterPtr(new CalculusModulationFrequencyParameter(*this, *_programmer, MOD_FREQ1, MOD_PS1)),
     ParameterPtr(new CalculusIntegDutyCycle(*this, *_programmer)),
     ParameterPtr(new CalculusPixCntMax(*this, *_programmer)),
     ParameterPtr(new CalculusSubFrameCntMax(*this, *_programmer)),
     ParameterPtr(new CalculusIntegDutyCycleSetFailed(*this, *_programmer)),
   }))
     return false;
   if(!ToFCamera::_init())
   {
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_initStartParams () protected virtual
set(EN_GLOBAL_PDN_REG, true) ||
set(EN_GLOBAL_PDN_REG, false) ||
set(DIS_SDMOD, true) ||
set(ADCK_R, 10U) ||
set(UPDATE_SEL, 2U) ||
set(SYNC_INTEG_PHASE_EN, true) ||
_programmer->writeRegister(0x58AE, 0x40011C) || //!set(TM_INTG_PHASE_PIX1, 284U) || _programmer->writeRegister(0x58DC, 0x5FFA80) || //!set(DVP_BLANK_PIX_PER_LINE, 1023U) ||
set(DISABLE_REARRANGE, true) ||
set(MCKADGEN_R_OFFSET, 10U) ||
_programmer->writeRegister(0x585B, 0xC00001) || //!set(SHUTTER_EN, true) ||
set(TEST_PG1, true) ||
set(FLIP_PHASE, true) ||
Reimplemented from Voxel::TI::ToFCamera.
Reimplemented in Voxel::TI::CalculusCDKCamera.
Definition at line 417 of file ToFCalculusCamera.cpp.
References Voxel::TI::ToFCamera::_initStartParams(), Voxel::DepthCamera::_programmer, ADCK_R, BLK_HEADER_EN, BLK_SIZE, CALIB_PHASE_OFFSET, CLIP_MODE_REG, CONFIDENCE_THRESHOLD, DIS_SDMOD, DISABLE_REARRANGE, DVP_BLANK_PIX_PER_LINE, EN_EASY_CONF_REG, EN_GLOBAL_PDN_REG, FB_READY_EN, FLIP_PHASE, Voxel::DepthCamera::getFrameSize(), Voxel::DepthCamera::getROI(), ILLUM_EN_POL, INTEGRATION_DUTY_CYCLE, LED_DRIVER_CURR_PROG, MCKADGEN_R_OFFSET, MOD_PLL_UPDATE, MOD_PS1, OP_CS_POL, Voxel::DepthCamera::set(), SHUTTER_EN, SYNC_INTEG_PHASE_EN, TEST_PG1, TG_EN, TM_INTG_PHASE_PIX1, TM_PDZ_LED_DRIVER, TM_PIX_CNT_MAX, TM_SPARE3_INIT_REG, TM_SPARE3_PAT1_REG, TM_SPARE3_PIX1_REG, TM_UFRAME_CNT_MAX, and UPDATE_SEL.
Referenced by Voxel::TI::CalculusCDKCamera::_initStartParams().
 {
 #if 0
   if(!set(TG_EN, true) ||
      !set(BLK_SIZE, 1024U) ||
      !set(BLK_HEADER_EN, true) ||
      !set(OP_CS_POL, true) ||
      !set(FB_READY_EN, true) ||
      !set(CONFIDENCE_THRESHOLD, 1U) ||
      !set(ILLUM_EN_POL, false) ||
      !getROI(roi) ||
      !getFrameSize(s))
     // || set(INTG_TIME, 40.0f);
 #endif
 #if 0
   if (!set(EN_GLOBAL_PDN_REG, true) ||
       !set(EN_GLOBAL_PDN_REG, false) ||
       !set(DIS_SDMOD, true) ||
       !set(ADCK_R, 10U) ||
       !set(UPDATE_SEL, 2U) ||
       !set(SYNC_INTEG_PHASE_EN, true) ||
       !set(TM_PIX_CNT_MAX, 50000U) ||
       !set(TM_UFRAME_CNT_MAX, 4U) ||
       !set(INTEGRATION_DUTY_CYCLE, 35U) ||
       !set(TG_EN, true) ||
       !set(TM_INTG_PHASE_PIX1, 284U) ||
       !set(DVP_BLANK_PIX_PER_LINE, 1023U) ||
       !set(DISABLE_REARRANGE, true) ||
       !set(MOD_PS1, 4) ||
       !set(MOD_PLL_UPDATE, true) ||
       !set(MOD_PLL_UPDATE, false) ||
       !set(TM_PDZ_LED_DRIVER, true) ||
       !set(LED_DRIVER_CURR_PROG, 30U) ||
       !set(MCKADGEN_R_OFFSET, 10U) ||
       !set(SHUTTER_EN, true) ||
       !set(TEST_PG1, true) ||
       !set(FLIP_PHASE, true) ||
       !set(CALIB_PHASE_OFFSET, -2884) ||
       !getROI(roi) ||
       !getFrameSize(s)
     )
     return false;
 #else
   if (!_programmer->writeRegister(0x5808, 0x000004) ||
       !_programmer->writeRegister(0x5808, 0x000000) ||
       !_programmer->writeRegister(0x580E, 0x000001) ||
       !_programmer->writeRegister(0x5812, 0x00000A) ||
       !_programmer->writeRegister(0x5881, 0x0000A0) ||
       !_programmer->writeRegister(0x580b, 0x002000) ||
       !_programmer->writeRegister(EN_EASY_CONF_REG, 0x000001) || // Disable Easy Conf
       !_programmer->writeRegister(TM_SPARE3_PIX1_REG, 0x400003) || // SPARE3_POL1 = 1
       !_programmer->writeRegister(TM_SPARE3_PAT1_REG, 0x400000) || // SPARE3_PAT1 = 01
       !_programmer->writeRegister(TM_SPARE3_INIT_REG, 0x000081) || // SPARE3_INIT = 0
       !_programmer->writeRegister(0x585C, 0x8C1000) ||
       !set(MOD_PS1, 4U) ||
       !set(MOD_PLL_UPDATE, true))
       return false;
   std::this_thread::sleep_for(std::chrono::milliseconds(100));
   if (
       !set(MOD_PLL_UPDATE, false) ||
       !set(TM_PDZ_LED_DRIVER, true) ||
       !set(LED_DRIVER_CURR_PROG, 30U) ||
       !_programmer->writeRegister(0x581B, 0x00000A) ||
       !_programmer->writeRegister(0x58D6, 0x400001) ||
       !_programmer->writeRegister(0x58F9, 0x080000) ||
       !set(CALIB_PHASE_OFFSET, -2900) ||
       !_programmer->writeRegister(CLIP_MODE_REG, 0x880000) // !set(CLIP_MODE, true) ||  // Check if we can move this out of the DML and hardcode instead
     )
     return false;
   if (
       !set(TM_PIX_CNT_MAX, 50000U) ||
       !set(TM_UFRAME_CNT_MAX, 4U) ||
       !set(INTEGRATION_DUTY_CYCLE, 55U) ||
       !set(TG_EN, true)
     )
     return false;
 #endif
   return ToFCamera::_initStartParams();
 }
bool Voxel::TI::ToFCalculusCamera::_is16BitModeEnabled (bool & mode16Bit) protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 640 of file ToFCalculusCamera.cpp.
 {
   mode16Bit = false;
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_isHistogramEnabled () const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 592 of file ToFCalculusCamera.cpp.
 {
   //bool histogramEnabled;
   return false;
   //return _get(HISTOGRAM_EN, histogramEnabled) && histogramEnabled;
 }
bool Voxel::TI::ToFCalculusCamera::_setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize & frameSize) protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 587 of file ToFCalculusCamera.cpp.
Referenced by _setROI().
 {
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_setFrameRate (const FrameRate & r) protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 275 of file ToFCalculusCamera.cpp.
 {
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_setROI (const RegionOfInterest & roi) protected virtual
Implements Voxel::DepthCamera.
Definition at line 541 of file ToFCalculusCamera.cpp.
References _getFrameSize(), Voxel::DepthCamera::_set(), _setBinning(), Voxel::TI::ToFCamera::_setFrameSize(), COL_END, COL_START, Voxel::FrameSize::height, Voxel::DepthCamera::isRunning(), Voxel::LOG_ERROR, Voxel::logger, ROW_END, ROW_START, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
 #if 0
   if(isRunning())
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Cannot set frame size while the camera is streaming" << std::endl;
     return false;
   }
   uint rowStart, rowEnd, colStart, colEnd;
   colStart = (roi.x/16)*8;
   colEnd = ((roi.x + roi.width)/16)*8 - 1;
   rowStart = roi.y;
   rowEnd = rowStart + roi.height - 1;
   if(!_set(ROW_START, rowStart) || !_set(ROW_END, rowEnd) || !_set(COL_START, colStart) || !_set(COL_END, colEnd))
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Could not get necessary parameters for ROI." << std::endl;
     return false;
   }
   if(!_setBinning(1, 1, roi))
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Could not reset binning while setting ROI." << std::endl;
     return false;
   }
   FrameSize s;
   if(!_getFrameSize(s) || !_setFrameSize(s, false)) // Get and set frame size to closest possible
   {
     logger(LOG_ERROR) << "ToFCalculusCamera: Could not update frame size to closest valid frame size" << std::endl;
     return false;
   }
 #endif
   return true;
 }
bool Voxel::TI::ToFCalculusCamera::_updateEasyConf () protected
Definition at line 310 of file ToFCalculusCamera.cpp.
References Voxel::DepthCamera::_get(), Voxel::DepthCamera::_programmer, Voxel::DepthCamera::_set(), INTEGRATION_DUTY_CYCLE, INTG_DUTY_CYCLE_SET_FAILED, TG_EN, TM_INTG_PHASE_PIX2_REG, TM_PIX_CNT_MAX, TM_PIX_CNT_MAX_REG, TM_RDOUT_HD_CNT_END_PIX1_REG, TM_RDOUT_HD_CNT_START_PIX1_REG, TM_RDOUT_PHASE_PIX2_REG, TM_RDOUT_VD_PIX1_REG, TM_RDOUT_VD_PIX2_REG, TM_SPARE3_PIX2_REG, TM_UFRAME_CNT_MAX, and TM_UFRAME_CNT_MAX_REG.
Referenced by Voxel::TI::CalculusIntegDutyCycle::set(), Voxel::TI::CalculusPixCntMax::set(), and Voxel::TI::CalculusSubFrameCntMax::set().
 {
   uint intg_duty_cycle, pix_cnt_max, sub_frame_cnt_max;
   // This represents the original value of intg_phase_pix2, and we pull in the register value by 50 cycles
   // other values are pushed out relative to this original value
   uint tm_intg_phase_pix2_int, tm_intg_phase_pix2_limit;
   bool tg_en_value;
   uint total_length_of_rdout_frame = 4950U;
   bool pix_cnt_overflow = false, intg_phase_overflow = false;
   _get(INTEGRATION_DUTY_CYCLE, intg_duty_cycle);
   _get(TM_PIX_CNT_MAX, pix_cnt_max);
   _get(TM_UFRAME_CNT_MAX, sub_frame_cnt_max);
   _get(TG_EN, tg_en_value);
   tm_intg_phase_pix2_int = 722 + ((pix_cnt_max * intg_duty_cycle) >> 6);
   if (pix_cnt_max < (total_length_of_rdout_frame + 922U))
     pix_cnt_overflow = true;
   if (pix_cnt_overflow)
     tm_intg_phase_pix2_limit = 723U;
   else
     tm_intg_phase_pix2_limit = pix_cnt_max - (total_length_of_rdout_frame + 300);
   if (tm_intg_phase_pix2_limit < tm_intg_phase_pix2_int)
     intg_phase_overflow = true;
   else
     intg_phase_overflow = false;
   if (intg_phase_overflow) {
     tm_intg_phase_pix2_int = tm_intg_phase_pix2_limit;
     _set(INTG_DUTY_CYCLE_SET_FAILED, true);
     return true;
   }
   _set(INTG_DUTY_CYCLE_SET_FAILED, false);
   _set(TG_EN, false);
   // Set INTG_PHASE_PIX2 and RDOUT_PHASE_PIX2 to 50 cycles earlier than usual, and gate shutter at the usual point
   _programmer->writeRegister(TM_INTG_PHASE_PIX2_REG, tm_intg_phase_pix2_int - 50);
   _programmer->writeRegister(TM_RDOUT_PHASE_PIX2_REG, tm_intg_phase_pix2_int - 50);
   _programmer->writeRegister(TM_SPARE3_PIX2_REG, tm_intg_phase_pix2_int);
   _programmer->writeRegister(TM_RDOUT_HD_CNT_START_PIX1_REG, tm_intg_phase_pix2_int + 100);
   _programmer->writeRegister(TM_RDOUT_VD_PIX1_REG, 0x400000 + tm_intg_phase_pix2_int + 100);
   _programmer->writeRegister(TM_RDOUT_VD_PIX2_REG, tm_intg_phase_pix2_int + 100 + 8);
   _programmer->writeRegister(TM_RDOUT_HD_CNT_END_PIX1_REG, tm_intg_phase_pix2_int + 100 + 4950);
   _programmer->writeRegister(TM_PIX_CNT_MAX_REG, pix_cnt_max);
   _programmer->writeRegister(TM_UFRAME_CNT_MAX_REG, 4 + (sub_frame_cnt_max << 4));
   _set(TG_EN, tg_en_value);
   return true;
 }
Friends And Related Function Documentation
friend class CalculusIntegDutyCycle friend
Definition at line 112 of file ToFCalculusCamera.h.
Referenced by _init().
friend class CalculusModulationFrequencyParameter friend
Definition at line 111 of file ToFCalculusCamera.h.
Referenced by _init().
friend class CalculusPixCntMax friend
Definition at line 113 of file ToFCalculusCamera.h.
Referenced by _init().
friend class CalculusSubFrameCntMax friend
Definition at line 114 of file ToFCalculusCamera.h.
Referenced by _init().
friend class CalculusVCOFrequency friend
Definition at line 110 of file ToFCalculusCamera.h.
The documentation for this class was generated from the following files:
ToFCalculusCamera.h
ToFCalculusCamera.cpp