Voxel: Voxel::SerializableString Class Reference
Voxel::SerializableString Class Reference
#include <Serializable.h>
Public Member Functions
SerializableString ()
SerializableString (const String &other)
size_t serializedSize () const
bool read (SerializedObject &object)
bool write (SerializedObject &object) const
virtual ~SerializableString ()
Public Member Functions inherited from Voxel::Serializable
virtual ~Serializable ()
Detailed Description
Definition at line 61 of file Serializable.h.
Constructor & Destructor Documentation
Voxel::SerializableString::SerializableString () inline
Definition at line 64 of file Serializable.h.
 {}
Voxel::SerializableString::SerializableString (const String & other) inline
Definition at line 65 of file Serializable.h.
 : String(other) {}
virtual Voxel::SerializableString::~SerializableString () inline virtual
Definition at line 95 of file Serializable.h.
 {}
Member Function Documentation
bool Voxel::SerializableString::read (SerializedObject & object) inline virtual
Implements Voxel::Serializable.
Definition at line 69 of file Serializable.h.
Referenced by Voxel::MainConfigurationFile::readFromHardware().
   {
     uint32_t size;
     if(object.get((char *)&size, sizeof(uint32_t)) != sizeof(uint32_t))
       return false;
     resize(size);
     if(object.get((char *)data(), sizeof(char)*size) != sizeof(char)*size)
       return false;
     return true;
   }
size_t Voxel::SerializableString::serializedSize () const inline virtual
Implements Voxel::Serializable.
Definition at line 67 of file Serializable.h.
Referenced by Voxel::ConfigurationFile::_serializeAllDataFiles().
 { return sizeof(uint32_t) + size(); }
bool Voxel::SerializableString::write (SerializedObject & object) const inline virtual
Implements Voxel::Serializable.
Definition at line 83 of file Serializable.h.
Referenced by Voxel::ConfigurationFile::_serializeAllDataFiles().
   {
     uint32_t size = this->size();
     if(object.put((const char *)&size, sizeof(uint32_t)) != sizeof(uint32_t))
       return false;
     if(object.put((const char *)data(), sizeof(char)*size) != sizeof(char)*size)
       return false;
     return true;
   }
The documentation for this class was generated from the following file:
Serializable.h