Voxel: Voxel::TI::VoxelProgrammerBase Class Reference
Voxel::TI::VoxelProgrammerBase Class Reference abstract
#include <VoxelProgrammerBase.h>
Public Types
typedef Map< uint, uint > SlaveAddressToByteMap
Public Member Functions
VoxelProgrammerBase (const SlaveAddressToByteMap &map, DevicePtr device)
virtual bool readRegister (uint32_t address, uint32_t &value) const
virtual bool writeRegister (uint32_t address, uint32_t value)
virtual bool getValue (const Parameter &param, uint32_t &value) const
virtual bool setValue (const Parameter &param, uint32_t value, bool writeOnly=false)
virtual ~VoxelProgrammerBase ()
Public Member Functions inherited from Voxel::RegisterProgrammer
virtual bool isInitialized () const =0
virtual bool reset ()=0
virtual ~RegisterProgrammer ()
Protected Member Functions
virtual bool _readRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t &value, uint8_t length) const =0
virtual bool _writeRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t value, uint8_t length)=0
Protected Attributes
DevicePtr _device
Mutex _mutex
SlaveAddressToByteMap _slaveAddressToByteMap
Detailed Description
Definition at line 21 of file VoxelProgrammerBase.h.
Member Typedef Documentation
typedef Map<uint, uint> Voxel::TI::VoxelProgrammerBase::SlaveAddressToByteMap
Definition at line 24 of file VoxelProgrammerBase.h.
Constructor & Destructor Documentation
Voxel::TI::VoxelProgrammerBase::VoxelProgrammerBase (const SlaveAddressToByteMap & map, DevicePtr device)
Definition at line 17 of file VoxelProgrammerBase.cpp.
References _device.
                                                                                           : _slaveAddressToByteMap(map)
 {
   _device = device;
 }
virtual Voxel::TI::VoxelProgrammerBase::~VoxelProgrammerBase () inline virtual
Definition at line 46 of file VoxelProgrammerBase.h.
 {}
Member Function Documentation
virtual bool Voxel::TI::VoxelProgrammerBase::_readRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t & value, uint8_t length) const protected pure virtual
Implemented in Voxel::TI::VoxelXUProgrammer, and Voxel::TI::VoxelUSBProgrammer.
Referenced by readRegister().
virtual bool Voxel::TI::VoxelProgrammerBase::_writeRegister (uint16_t slaveAddress, uint16_t registerAddress, uint32_t value, uint8_t length) protected pure virtual
Implemented in Voxel::TI::VoxelXUProgrammer, and Voxel::TI::VoxelUSBProgrammer.
Referenced by writeRegister().
bool Voxel::TI::VoxelProgrammerBase::getValue (const Parameter & param, uint32_t & value) const virtual
Implements Voxel::RegisterProgrammer.
Definition at line 97 of file VoxelProgrammerBase.cpp.
References Voxel::Parameter::address(), Voxel::Parameter::lsb(), Voxel::Parameter::mask(), and readRegister().
 {
   uint32_t registerValue;
   if(param.mask() == -1)
     return false; // No way to read value
   if(!readRegister(param.address(), registerValue))
     return false;
   value = (registerValue & ~param.mask()) >> param.lsb();
   return true;
 }
bool Voxel::TI::VoxelProgrammerBase::readRegister (uint32_t address, uint32_t & value) const virtual
Implements Voxel::RegisterProgrammer.
Definition at line 22 of file VoxelProgrammerBase.cpp.
References _mutex, _readRegister(), _slaveAddressToByteMap, Voxel::RegisterProgrammer::isInitialized(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, and LensCalibrationTest::x.
Referenced by getValue(), and setValue().
 {
   //LogLevelChanger _(LOG_DEBUG);
   Lock<Mutex> _(_mutex);
   if(!isInitialized())
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Not initialized." << std::endl;
     return false;
   }
   uint16_t slaveAddress, registerAddress;
   slaveAddress = (address & 0xFF00) >> 8; // I2C slave address
   registerAddress = (address & 0xFF); // I2C register address
   auto x = _slaveAddressToByteMap.find(slaveAddress);
   if(x == _slaveAddressToByteMap.end())
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Unknown slave address 0x" << std::hex << address << std::endl;
     return false;
   }
   uint byteCount = x->second;
   if(!_readRegister(slaveAddress, registerAddress, value, byteCount))
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Could not read register for address 0x" << std::hex << address  << std::dec << std::endl;
     return false;
   }
   logger(LOG_DEBUG) << "VoxelProgrammerBase: register read @0x" << std::hex << address << " = " << value << std::dec << std::endl;
   return true;
 }
bool Voxel::TI::VoxelProgrammerBase::setValue (const Parameter & param, uint32_t value, bool writeOnly = false) virtual
Implements Voxel::RegisterProgrammer.
Definition at line 111 of file VoxelProgrammerBase.cpp.
References Voxel::Parameter::address(), Voxel::Parameter::lsb(), Voxel::Parameter::mask(), readRegister(), and writeRegister().
 {
   uint32_t registerValue;
   if(param.mask() == -1)
     return true; // Fictitiously accept set
   if(!writeOnly)
   {
     if(!readRegister(param.address(), registerValue))
       return false;
   }
   else
     registerValue = 0; // Start with zero value for write-only registers
   registerValue = ((registerValue & param.mask()) | (value << param.lsb()));
   return writeRegister(param.address(), registerValue);
 }
bool Voxel::TI::VoxelProgrammerBase::writeRegister (uint32_t address, uint32_t value) virtual
Implements Voxel::RegisterProgrammer.
Definition at line 60 of file VoxelProgrammerBase.cpp.
References _mutex, _slaveAddressToByteMap, _writeRegister(), Voxel::RegisterProgrammer::isInitialized(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, and LensCalibrationTest::x.
Referenced by setValue().
 {
   //LogLevelChanger _(LOG_DEBUG);
   Lock<Mutex> _(_mutex);
   if(!isInitialized())
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Not initialized." << std::endl;
     return false;
   }
   uint16_t slaveAddress, registerAddress;
   slaveAddress = (address & 0xFF00) >> 8;
   registerAddress = (address & 0xFF);
   auto x = _slaveAddressToByteMap.find(slaveAddress);
   if(x == _slaveAddressToByteMap.end())
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Unknown slave address 0x" << std::hex << slaveAddress << std::endl;
     return false;
   }
   uint byteCount = x->second;
   if(!_writeRegister(slaveAddress, registerAddress, value, byteCount))
   {
     logger(LOG_ERROR) << "VoxelProgrammerBase: Could not read register for address 0x" << std::hex << address  << std::dec << std::endl;
     return false;
   }
   logger(LOG_DEBUG) << "VoxelProgrammerBase: register write @0x" << std::hex << address << " = " << value  << std::dec << std::endl;
   return true;
 }
Member Data Documentation
DevicePtr Voxel::TI::VoxelProgrammerBase::_device protected
Definition at line 27 of file VoxelProgrammerBase.h.
Referenced by Voxel::TI::VoxelXUProgrammer::init(), and VoxelProgrammerBase().
Mutex Voxel::TI::VoxelProgrammerBase::_mutex mutable protected
Definition at line 29 of file VoxelProgrammerBase.h.
Referenced by readRegister(), and writeRegister().
SlaveAddressToByteMap Voxel::TI::VoxelProgrammerBase::_slaveAddressToByteMap protected
Definition at line 31 of file VoxelProgrammerBase.h.
Referenced by readRegister(), and writeRegister().
The documentation for this class was generated from the following files:
VoxelProgrammerBase.h
VoxelProgrammerBase.cpp