Voxel: ELFIO::string_section_accessor Class Reference
ELFIO::string_section_accessor Class Reference
#include <elfio_strings.hpp>
Public Member Functions
string_section_accessor (section *section_)
const char * get_string (Elf_Word index) const
Elf_Word add_string (const char *str)
Elf_Word add_string (const std::string &str)
Private Attributes
section * string_section
Detailed Description
Definition at line 33 of file elfio_strings.hpp.
Constructor & Destructor Documentation
ELFIO::string_section_accessor::string_section_accessor (section * section_) inline
Definition at line 37 of file elfio_strings.hpp.
                                                  :
                              string_section( section_ )
     {
     }
Member Function Documentation
Elf_Word ELFIO::string_section_accessor::add_string (const char * str) inline
Definition at line 60 of file elfio_strings.hpp.
References ELFIO::section::append_data(), and string_section.
Referenced by ELFIO::elfio::Sections::add(), ELFIO::dynamic_section_accessor::add_entry(), ELFIO::relocation_section_accessor::add_entry(), and ELFIO::symbol_section_accessor::add_symbol().
     {
         // Strings are addeded to the end of the current section data
         Elf_Word current_position = (Elf_Word)string_section->get_size();
         if ( current_position == 0 ) {
             char empty_string[1] = {'\0'};
             string_section->append_data( empty_string, 1 );
             current_position++;
         }
         string_section->append_data( str, (Elf_Word)std::strlen( str ) + 1 );
         return current_position;
     }
Elf_Word ELFIO::string_section_accessor::add_string (const std::string & str) inline
Definition at line 78 of file elfio_strings.hpp.
References ELFIO::section::append_data(), and string_section.
     {
         // Strings are addeded to the end of the current section data
         Elf_Word current_position = (Elf_Word)string_section->get_size();
         char empty_string[1] = {'\0'};
         if ( current_position == 0 ) {
             string_section->append_data( empty_string, 1 );
             current_position++;
         }
         string_section->append_data( str );
         string_section->append_data( empty_string, 1 );
         return current_position;
     }
const char* ELFIO::string_section_accessor::get_string (Elf_Word index) const inline
Definition at line 45 of file elfio_strings.hpp.
References ELFIO::section::get_data(), and string_section.
Referenced by ELFIO::symbol_section_accessor::generic_get_symbol(), ELFIO::dynamic_section_accessor::get_entry(), and ELFIO::elfio::load_sections().
     {
         if ( index < string_section->get_size() ) {
             const char* data = string_section->get_data();
             if ( 0 != data ) {
                 return data + index;
             }
         }
         return 0;
     }
Member Data Documentation
section* ELFIO::string_section_accessor::string_section private
Definition at line 96 of file elfio_strings.hpp.
Referenced by add_string(), and get_string().
The documentation for this class was generated from the following file:
elfio_strings.hpp