Voxel: ELFIO::dynamic_section_accessor Class Reference
ELFIO::dynamic_section_accessor Class Reference
#include <elfio_dynamic.hpp>
Public Member Functions
dynamic_section_accessor (const elfio &elf_file_, section *section_)
Elf_Xword get_entries_num () const
bool get_entry (Elf_Xword index, Elf_Xword &tag, Elf_Xword &value, std::string &str) const
void add_entry (Elf_Xword &tag, Elf_Xword &value)
void add_entry (Elf_Xword &tag, std::string &str)
Private Member Functions
Elf_Half get_string_table_index () const
template<class T >
void generic_get_entry_dyn (Elf_Xword index, Elf_Xword &tag, Elf_Xword &value) const
template<class T >
void generic_add_entry (Elf_Xword tag, Elf_Xword value)
Private Attributes
const elfio & elf_file
section * dynamic_section
Detailed Description
Definition at line 29 of file elfio_dynamic.hpp.
Constructor & Destructor Documentation
ELFIO::dynamic_section_accessor::dynamic_section_accessor (const elfio & elf_file_, section * section_) inline
Definition at line 33 of file elfio_dynamic.hpp.
                                                                           :
                               elf_file( elf_file_ ),
                               dynamic_section( section_ )
     {
     }
Member Function Documentation
void ELFIO::dynamic_section_accessor::add_entry (Elf_Xword & tag, Elf_Xword & value) inline
Definition at line 88 of file elfio_dynamic.hpp.
References elf_file, and ELFCLASS32.
Referenced by add_entry().
     {
         if ( elf_file.get_class() == ELFCLASS32 ) {
             generic_add_entry< Elf32_Dyn >( tag, value );
         }
         else {
             generic_add_entry< Elf64_Dyn >( tag, value );
         }
     }
void ELFIO::dynamic_section_accessor::add_entry (Elf_Xword & tag, std::string & str) inline
Definition at line 101 of file elfio_dynamic.hpp.
References add_entry(), ELFIO::string_section_accessor::add_string(), elf_file, get_string_table_index(), and ELFIO::elfio::sections.
     {
         string_section_accessor strsec =
             elf_file.sections[ get_string_table_index() ];
         Elf_Xword value = strsec.add_string( str );
         add_entry( tag, value );
     }
template<class T > void ELFIO::dynamic_section_accessor::generic_add_entry (Elf_Xword tag, Elf_Xword value) inline private
Definition at line 187 of file elfio_dynamic.hpp.
References ELFIO::section::append_data(), DT_BIND_NOW, DT_DEBUG, DT_FINI, DT_FINI_ARRAY, DT_FINI_ARRAYSZ, DT_FLAGS, DT_HASH, DT_INIT, DT_INIT_ARRAY, DT_INIT_ARRAYSZ, DT_JMPREL, DT_NEEDED, DT_NULL, DT_PLTGOT, DT_PLTREL, DT_PLTRELSZ, DT_PREINIT_ARRAY, DT_PREINIT_ARRAYSZ, DT_REL, DT_RELA, DT_RELAENT, DT_RELASZ, DT_RELENT, DT_RELSZ, DT_RPATH, DT_RUNPATH, DT_SONAME, DT_STRSZ, DT_STRTAB, DT_SYMBOLIC, DT_SYMENT, DT_SYMTAB, DT_TEXTREL, dynamic_section, elf_file, and ELFIO::elfio::get_convertor().
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         T entry;
         switch ( tag ) {
         case DT_NULL:
         case DT_SYMBOLIC:
         case DT_TEXTREL:
         case DT_BIND_NOW:
             value = 0;
         case DT_NEEDED:
         case DT_PLTRELSZ:
         case DT_RELASZ:
         case DT_RELAENT:
         case DT_STRSZ:
         case DT_SYMENT:
         case DT_SONAME:
         case DT_RPATH:
         case DT_RELSZ:
         case DT_RELENT:
         case DT_PLTREL:
         case DT_INIT_ARRAYSZ:
         case DT_FINI_ARRAYSZ:
         case DT_RUNPATH:
         case DT_FLAGS:
         case DT_PREINIT_ARRAYSZ:
             entry.d_un.d_val = convertor( value );
             break;
         case DT_PLTGOT:
         case DT_HASH:
         case DT_STRTAB:
         case DT_SYMTAB:
         case DT_RELA:
         case DT_INIT:
         case DT_FINI:
         case DT_REL:
         case DT_DEBUG:
         case DT_JMPREL:
         case DT_INIT_ARRAY:
         case DT_FINI_ARRAY:
         case DT_PREINIT_ARRAY:
         default:
             entry.d_un.d_ptr = convertor( value );
             break;
         }
         entry.d_tag = convertor( tag );
         dynamic_section->append_data( reinterpret_cast<char*>( &entry ), sizeof( entry ) );
     }
template<class T > void ELFIO::dynamic_section_accessor::generic_get_entry_dyn (Elf_Xword index, Elf_Xword & tag, Elf_Xword & value) const inline private
Definition at line 122 of file elfio_dynamic.hpp.
References DT_BIND_NOW, DT_DEBUG, DT_FINI, DT_FINI_ARRAY, DT_FINI_ARRAYSZ, DT_FLAGS, DT_HASH, DT_INIT, DT_INIT_ARRAY, DT_INIT_ARRAYSZ, DT_JMPREL, DT_NEEDED, DT_NULL, DT_PLTGOT, DT_PLTREL, DT_PLTRELSZ, DT_PREINIT_ARRAY, DT_PREINIT_ARRAYSZ, DT_REL, DT_RELA, DT_RELAENT, DT_RELASZ, DT_RELENT, DT_RELSZ, DT_RPATH, DT_RUNPATH, DT_SONAME, DT_STRSZ, DT_STRTAB, DT_SYMBOLIC, DT_SYMENT, DT_SYMTAB, DT_TEXTREL, dynamic_section, elf_file, ELFIO::elfio::get_convertor(), and ELFIO::section::get_data().
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         // Check unusual case when dynamic section has no data
         if( dynamic_section->get_data() == 0 ||
             ( index + 1 ) * dynamic_section->get_entry_size() > dynamic_section->get_size() ) {
             tag   = DT_NULL;
             value = 0;
             return;
         }
         const T* pEntry = reinterpret_cast<const T*>(
                 dynamic_section->get_data() +
                 index * dynamic_section->get_entry_size() );
         tag = convertor( pEntry->d_tag );
         switch ( tag ) {
         case DT_NULL:
         case DT_SYMBOLIC:
         case DT_TEXTREL:
         case DT_BIND_NOW:
             value = 0;
             break;
         case DT_NEEDED:
         case DT_PLTRELSZ:
         case DT_RELASZ:
         case DT_RELAENT:
         case DT_STRSZ:
         case DT_SYMENT:
         case DT_SONAME:
         case DT_RPATH:
         case DT_RELSZ:
         case DT_RELENT:
         case DT_PLTREL:
         case DT_INIT_ARRAYSZ:
         case DT_FINI_ARRAYSZ:
         case DT_RUNPATH:
         case DT_FLAGS:
         case DT_PREINIT_ARRAYSZ:
             value = convertor( pEntry->d_un.d_val );
             break;
         case DT_PLTGOT:
         case DT_HASH:
         case DT_STRTAB:
         case DT_SYMTAB:
         case DT_RELA:
         case DT_INIT:
         case DT_FINI:
         case DT_REL:
         case DT_DEBUG:
         case DT_JMPREL:
         case DT_INIT_ARRAY:
         case DT_FINI_ARRAY:
         case DT_PREINIT_ARRAY:
         default:
             value = convertor( pEntry->d_un.d_ptr );
             break;
         }
     }
Elf_Xword ELFIO::dynamic_section_accessor::get_entries_num () const inline
Definition at line 41 of file elfio_dynamic.hpp.
References dynamic_section.
Referenced by ELFIO::dump::dynamic_tags(), and get_entry().
     {
         Elf_Xword nRet = 0;
         if ( 0 != dynamic_section->get_entry_size() ) {
             nRet = dynamic_section->get_size() / dynamic_section->get_entry_size();
         }
         return nRet;
     }
bool ELFIO::dynamic_section_accessor::get_entry (Elf_Xword index, Elf_Xword & tag, Elf_Xword & value, std::string & str) const inline
Definition at line 54 of file elfio_dynamic.hpp.
References DT_NEEDED, DT_RPATH, DT_RUNPATH, DT_SONAME, elf_file, ELFCLASS32, get_entries_num(), ELFIO::string_section_accessor::get_string(), get_string_table_index(), and ELFIO::elfio::sections.
Referenced by ELFIO::dump::dynamic_tags(), and Voxel::DepthCameraLibrary::getABIVersion().
     {
         if ( index >= get_entries_num() ) {    // Is index valid
             return false;
         }
         if ( elf_file.get_class() == ELFCLASS32 ) {
             generic_get_entry_dyn< Elf32_Dyn >( index, tag, value );
         }
         else {
             generic_get_entry_dyn< Elf64_Dyn >( index, tag, value );
         }
         // If the tag may have a string table reference, prepare the string
         if ( tag == DT_NEEDED ||
              tag == DT_SONAME ||
              tag == DT_RPATH  ||
              tag == DT_RUNPATH ) {
             string_section_accessor strsec =
                 elf_file.sections[ get_string_table_index() ];
             str = strsec.get_string( value );
         }
         else {
             str.clear();
         }
         return true;
     }
Elf_Half ELFIO::dynamic_section_accessor::get_string_table_index () const inline private
Definition at line 114 of file elfio_dynamic.hpp.
References dynamic_section.
Referenced by add_entry(), and get_entry().
     {
         return (Elf_Half)dynamic_section->get_link();
     }
Member Data Documentation
section* ELFIO::dynamic_section_accessor::dynamic_section private
Definition at line 243 of file elfio_dynamic.hpp.
Referenced by generic_add_entry(), generic_get_entry_dyn(), get_entries_num(), and get_string_table_index().
const elfio& ELFIO::dynamic_section_accessor::elf_file private
Definition at line 242 of file elfio_dynamic.hpp.
Referenced by add_entry(), generic_add_entry(), generic_get_entry_dyn(), and get_entry().
The documentation for this class was generated from the following file:
elfio_dynamic.hpp