Voxel: ELFIO::endianess_convertor Class Reference
ELFIO::endianess_convertor Class Reference
#include <elfio_utils.hpp>
Public Member Functions
endianess_convertor ()
void setup (unsigned char elf_file_encoding)
uint64_t operator() (uint64_t value) const
int64_t operator() (int64_t value) const
uint32_t operator() (uint32_t value) const
int32_t operator() (int32_t value) const
uint16_t operator() (uint16_t value) const
int16_t operator() (int16_t value) const
int8_t operator() (int8_t value) const
uint8_t operator() (uint8_t value) const
Private Member Functions
unsigned char get_host_encoding () const
Private Attributes
bool need_conversion
Detailed Description
Definition at line 61 of file elfio_utils.hpp.
Constructor & Destructor Documentation
ELFIO::endianess_convertor::endianess_convertor () inline
Definition at line 64 of file elfio_utils.hpp.
References need_conversion.
     {
         need_conversion = false;
     }
Member Function Documentation
unsigned char ELFIO::endianess_convertor::get_host_encoding () const inline private
Definition at line 174 of file elfio_utils.hpp.
References ELFDATA2LSB, and ELFDATA2MSB.
Referenced by setup().
     {
         static const int tmp = 1;
         if ( 1 == *(char*)&tmp ) {
             return ELFDATA2LSB;
         }
         else {
             return ELFDATA2MSB;
         }
     }
uint64_t ELFIO::endianess_convertor::operator() (uint64_t value) const inline
Definition at line 78 of file elfio_utils.hpp.
References need_conversion.
     {
         if ( !need_conversion ) {
             return value;
         }
         value =
             ( ( value & 0x00000000000000FFull ) << 56 ) |
             ( ( value & 0x000000000000FF00ull ) << 40 ) |
             ( ( value & 0x0000000000FF0000ull ) << 24 ) |
             ( ( value & 0x00000000FF000000ull ) <<  8 ) |
             ( ( value & 0x000000FF00000000ull ) >>  8 ) |
             ( ( value & 0x0000FF0000000000ull ) >> 24 ) |
             ( ( value & 0x00FF000000000000ull ) >> 40 ) |
             ( ( value & 0xFF00000000000000ull ) >> 56 );
         return value;
     }
int64_t ELFIO::endianess_convertor::operator() (int64_t value) const inline
Definition at line 98 of file elfio_utils.hpp.
References need_conversion.
     {
         if ( !need_conversion ) {
             return value;
         }
         return (int64_t)(*this)( (uint64_t)value );
     }
uint32_t ELFIO::endianess_convertor::operator() (uint32_t value) const inline
Definition at line 108 of file elfio_utils.hpp.
References need_conversion.
     {
         if ( !need_conversion ) {
             return value;
         }
         value =
             ( ( value & 0x000000FF ) << 24 ) |
             ( ( value & 0x0000FF00 ) <<  8 ) |
             ( ( value & 0x00FF0000 ) >>  8 ) |
             ( ( value & 0xFF000000 ) >> 24 );
         return value;
     }
int32_t ELFIO::endianess_convertor::operator() (int32_t value) const inline
Definition at line 124 of file elfio_utils.hpp.
References need_conversion.
     {
         if ( !need_conversion ) {
             return value;
         }
         return (int32_t)(*this)( (uint32_t)value );
     }
uint16_t ELFIO::endianess_convertor::operator() (uint16_t value) const inline
Definition at line 134 of file elfio_utils.hpp.
References need_conversion.
     {
         if ( !need_conversion ) {
             return value;
         }
         value =
             ( ( value & 0x00FF ) <<  8 ) |
             ( ( value & 0xFF00 ) >>  8 );
         return value;
     }
int16_t ELFIO::endianess_convertor::operator() (int16_t value) const inline
Definition at line 148 of file elfio_utils.hpp.
References need_conversion.
     {
         if ( !need_conversion ) {
             return value;
         }
         return (int16_t)(*this)( (uint16_t)value );
     }
int8_t ELFIO::endianess_convertor::operator() (int8_t value) const inline
Definition at line 158 of file elfio_utils.hpp.
     {
         return value;
     }
uint8_t ELFIO::endianess_convertor::operator() (uint8_t value) const inline
Definition at line 165 of file elfio_utils.hpp.
     {
         return value;
     }
void ELFIO::endianess_convertor::setup (unsigned char elf_file_encoding) inline
Definition at line 71 of file elfio_utils.hpp.
References get_host_encoding(), and need_conversion.
Referenced by ELFIO::elfio::create(), and ELFIO::elfio::load().
     {
         need_conversion = ( elf_file_encoding != get_host_encoding() );
     }
Member Data Documentation
bool ELFIO::endianess_convertor::need_conversion private
Definition at line 187 of file elfio_utils.hpp.
Referenced by endianess_convertor(), operator()(), and setup().
The documentation for this class was generated from the following file:
elfio_utils.hpp