Voxel: TinyXML2::XMLDocument Class Reference
TinyXML2::XMLDocument Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
XMLDocument (bool processEntities=true, Whitespace=PRESERVE_WHITESPACE)
constructor
~XMLDocument ()
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual const XMLDocument * ToDocument () const
XMLError Parse (const char *xml, size_t nBytes=(size_t)(-1))
XMLError LoadFile (const char *filename)
XMLError LoadFile (FILE *)
XMLError SaveFile (const char *filename, bool compact=false)
XMLError SaveFile (FILE *fp, bool compact=false)
bool ProcessEntities () const
Whitespace WhitespaceMode () const
bool HasBOM () const
void SetBOM (bool useBOM)
XMLElement * RootElement ()
const XMLElement * RootElement () const
void Print (XMLPrinter *streamer=0) const
virtual bool Accept (XMLVisitor *visitor) const
XMLElement * NewElement (const char *name)
XMLComment * NewComment (const char *comment)
XMLText * NewText (const char *text)
XMLDeclaration * NewDeclaration (const char *text=0)
XMLUnknown * NewUnknown (const char *text)
void DeleteNode (XMLNode *node)
void SetError (XMLError error, const char *str1, const char *str2)
bool Error () const
Return true if there was an error parsing the document.
XMLError ErrorID () const
Return the errorID.
const char * ErrorName () const
const char * GetErrorStr1 () const
Return a possibly helpful diagnostic location or string.
const char * GetErrorStr2 () const
Return a possibly helpful secondary diagnostic location or string.
void PrintError () const
If there is an error, print it to stdout.
void Clear ()
Clear the document, resetting it to the initial state.
char * Identify (char *p, XMLNode **node)
virtual XMLNode * ShallowClone (XMLDocument *) const
virtual bool ShallowEqual (const XMLNode *) const
Public Member Functions inherited from TinyXML2::XMLNode
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLElement * ToElement () const
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
virtual char * ParseDeep (char *, StrPair *)
Private Member Functions
XMLDocument (const XMLDocument &)
void operator= (const XMLDocument &)
Private Attributes
bool _writeBOM
bool _processEntities
XMLError _errorID
Whitespace _whitespace
const char * _errorStr1
const char * _errorStr2
char * _charBuffer
MemPoolT< sizeof(XMLElement) > _elementPool
MemPoolT< sizeof(XMLAttribute) > _attributePool
MemPoolT< sizeof(XMLText) > _textPool
MemPoolT< sizeof(XMLComment) > _commentPool
Static Private Attributes
static const char * _errorNames [XML_ERROR_COUNT]
Friends
class XMLElement
Additional Inherited Members
Protected Member Functions inherited from TinyXML2::XMLNode
XMLNode (XMLDocument *)
virtual ~XMLNode ()
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Protected Attributes inherited from TinyXML2::XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Detailed Description
A Document binds together all the functionality. It can be saved, loaded, and printed to the screen. All Nodes are connected and allocated to a Document. If the Document is deleted, all its Nodes are also deleted.
Definition at line 1539 of file TinyXML2.h.
Constructor & Destructor Documentation
TinyXML2::XMLDocument::XMLDocument (bool processEntities = true, Whitespace whitespace = PRESERVE_WHITESPACE)
constructor
Definition at line 1647 of file TinyXML2.cpp.
References TinyXML2::XMLNode::_document.
                                                                       :
     XMLNode( 0 ),
     _writeBOM( false ),
     _processEntities( processEntities ),
     _errorID( XML_NO_ERROR ),
     _whitespace( whitespace ),
     _errorStr1( 0 ),
     _errorStr2( 0 ),
     _charBuffer( 0 )
 {
     _document = this; // avoid warning about 'this' in initializer list
 }
TinyXML2::XMLDocument::~XMLDocument ()
Definition at line 1661 of file TinyXML2.cpp.
References Clear().
 {
     Clear();
 }
TinyXML2::XMLDocument::XMLDocument (const XMLDocument &) private
Member Function Documentation
bool TinyXML2::XMLDocument::Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements TinyXML2::XMLNode.
Definition at line 579 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLNode::NextSibling(), TinyXML2::XMLVisitor::VisitEnter(), and TinyXML2::XMLVisitor::VisitExit().
Referenced by Print().
 {
     if ( visitor->VisitEnter( *this ) ) {
         for ( const XMLNode* node=FirstChild(); node; node=node->NextSibling() ) {
             if ( !node->Accept( visitor ) ) {
                 break;
             }
         }
     }
     return visitor->VisitExit( *this );
 }
void TinyXML2::XMLDocument::Clear ()
Clear the document, resetting it to the initial state.
Definition at line 1667 of file TinyXML2.cpp.
References _attributePool, _charBuffer, _commentPool, _elementPool, _errorID, _errorStr1, _errorStr2, _textPool, TinyXML2::XMLNode::DeleteChildren(), Error(), TIXMLASSERT, and TinyXML2::XML_NO_ERROR.
Referenced by LoadFile(), Parse(), and ~XMLDocument().
 {
     DeleteChildren();
 #ifdef DEBUG
     const bool hadError = Error();
 #endif
     _errorID = XML_NO_ERROR;
     _errorStr1 = 0;
     _errorStr2 = 0;
     delete [] _charBuffer;
     _charBuffer = 0;
 #if 0
     _textPool.Trace( "text" );
     _elementPool.Trace( "element" );
     _commentPool.Trace( "comment" );
     _attributePool.Trace( "attribute" );
 #endif
 #ifdef DEBUG
     if ( !hadError ) {
         TIXMLASSERT( _elementPool.CurrentAllocs()   == _elementPool.Untracked() );
         TIXMLASSERT( _attributePool.CurrentAllocs() == _attributePool.Untracked() );
         TIXMLASSERT( _textPool.CurrentAllocs()      == _textPool.Untracked() );
         TIXMLASSERT( _commentPool.CurrentAllocs()   == _commentPool.Untracked() );
     }
 #endif
 }
void TinyXML2::XMLDocument::DeleteNode (XMLNode * node) inline
Delete a node associated with this document. It will be unlinked from the DOM.
Definition at line 1685 of file TinyXML2.h.
References TinyXML2::XMLNode::_parent, TinyXML2::XMLNode::DeleteChild(), and TIXMLASSERT.
{
         TIXMLASSERT( node );
         TIXMLASSERT( node->_parent );
         node->_parent->DeleteChild( node );
     }
bool TinyXML2::XMLDocument::Error () const inline
Return true if there was an error parsing the document.
Definition at line 1694 of file TinyXML2.h.
References TinyXML2::XML_NO_ERROR.
Referenced by Clear(), Voxel::ParameterDMLParser::ParameterDMLParser(), Parse(), TinyXML2::XMLNode::ParseDeep(), and PrintError().
{
         return _errorID != XML_NO_ERROR;
     }
XMLError TinyXML2::XMLDocument::ErrorID () const inline
Return the errorID.
Definition at line 1698 of file TinyXML2.h.
{
         return _errorID;
     }
const char * TinyXML2::XMLDocument::ErrorName () const
Definition at line 1897 of file TinyXML2.cpp.
References _errorID, _errorNames, TIXMLASSERT, and TinyXML2::XML_ERROR_COUNT.
Referenced by PrintError().
 {
   TIXMLASSERT( _errorID >= 0 && _errorID < XML_ERROR_COUNT );
   return _errorNames[_errorID];
 }
const char* TinyXML2::XMLDocument::GetErrorStr1 () const inline
Return a possibly helpful diagnostic location or string.
Definition at line 1704 of file TinyXML2.h.
{
         return _errorStr1;
     }
const char* TinyXML2::XMLDocument::GetErrorStr2 () const inline
Return a possibly helpful secondary diagnostic location or string.
Definition at line 1708 of file TinyXML2.h.
{
         return _errorStr2;
     }
bool TinyXML2::XMLDocument::HasBOM () const inline
Returns true if this document has a leading Byte Order Mark of UTF8.
Definition at line 1608 of file TinyXML2.h.
Referenced by TinyXML2::XMLPrinter::VisitEnter().
{
         return _writeBOM;
     }
char * TinyXML2::XMLDocument::Identify (char * p, XMLNode ** node)
Definition at line 509 of file TinyXML2.cpp.
References _commentPool, _elementPool, TinyXML2::XMLNode::_memPool, _textPool, TinyXML2::XMLText::SetCData(), TinyXML2::XMLUtil::SkipWhiteSpace(), TinyXML2::XMLUtil::StringEqual(), TIXMLASSERT, and XMLElement.
Referenced by TinyXML2::XMLNode::ParseDeep().
 {
     char* const start = p;
     p = XMLUtil::SkipWhiteSpace( p );
     if( !p || !*p ) {
         return p;
     }
     // What is this thing?
   // These strings define the matching patters:
     static const char* xmlHeader    = { "<?" };
     static const char* commentHeader  = { "<!--" };
     static const char* dtdHeader    = { "<!" };
     static const char* cdataHeader    = { "<![CDATA[" };
     static const char* elementHeader  = { "<" };  // and a header for everything else; check last.
     static const int xmlHeaderLen   = 2;
     static const int commentHeaderLen = 4;
     static const int dtdHeaderLen   = 2;
     static const int cdataHeaderLen   = 9;
     static const int elementHeaderLen = 1;
 #if defined(_MSC_VER)
 #pragma warning ( push )
 #pragma warning ( disable : 4127 )
 #endif
     TIXMLASSERT( sizeof( XMLComment ) == sizeof( XMLUnknown ) );    // use same memory pool
     TIXMLASSERT( sizeof( XMLComment ) == sizeof( XMLDeclaration ) );  // use same memory pool
 #if defined(_MSC_VER)
 #pragma warning (pop)
 #endif
     XMLNode* returnNode = 0;
     if ( XMLUtil::StringEqual( p, xmlHeader, xmlHeaderLen ) ) {
         returnNode = new (_commentPool.Alloc()) XMLDeclaration( this );
         returnNode->_memPool = &_commentPool;
         p += xmlHeaderLen;
     }
     else if ( XMLUtil::StringEqual( p, commentHeader, commentHeaderLen ) ) {
         returnNode = new (_commentPool.Alloc()) XMLComment( this );
         returnNode->_memPool = &_commentPool;
         p += commentHeaderLen;
     }
     else if ( XMLUtil::StringEqual( p, cdataHeader, cdataHeaderLen ) ) {
         XMLText* text = new (_textPool.Alloc()) XMLText( this );
         returnNode = text;
         returnNode->_memPool = &_textPool;
         p += cdataHeaderLen;
         text->SetCData( true );
     }
     else if ( XMLUtil::StringEqual( p, dtdHeader, dtdHeaderLen ) ) {
         returnNode = new (_commentPool.Alloc()) XMLUnknown( this );
         returnNode->_memPool = &_commentPool;
         p += dtdHeaderLen;
     }
     else if ( XMLUtil::StringEqual( p, elementHeader, elementHeaderLen ) ) {
         returnNode = new (_elementPool.Alloc()) XMLElement( this );
         returnNode->_memPool = &_elementPool;
         p += elementHeaderLen;
     }
     else {
         returnNode = new (_textPool.Alloc()) XMLText( this );
         returnNode->_memPool = &_textPool;
         p = start;  // Back it up, all the text counts.
     }
     *node = returnNode;
     return p;
 }
XMLError TinyXML2::XMLDocument::LoadFile (const char * filename)
Load an XML file from disk. Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1759 of file TinyXML2.cpp.
References _errorID, Clear(), SetError(), and TinyXML2::XML_ERROR_FILE_NOT_FOUND.
Referenced by Voxel::ParameterDMLParser::ParameterDMLParser().
 {
     Clear();
     FILE* fp = callfopen( filename, "rb" );
     if ( !fp ) {
         SetError( XML_ERROR_FILE_NOT_FOUND, filename, 0 );
         return _errorID;
     }
     LoadFile( fp );
     fclose( fp );
     return _errorID;
 }
XMLError TinyXML2::XMLDocument::LoadFile (FILE * fp)
Load an XML file from disk. You are responsible for providing and closing the FILE*.
Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1773 of file TinyXML2.cpp.
References _charBuffer, _errorID, _writeBOM, Clear(), TinyXML2::XMLNode::ParseDeep(), TinyXML2::XMLUtil::ReadBOM(), SetError(), TinyXML2::XMLUtil::SkipWhiteSpace(), TinyXML2::XML_ERROR_EMPTY_DOCUMENT, and TinyXML2::XML_ERROR_FILE_READ_ERROR.
 {
     Clear();
     fseek( fp, 0, SEEK_SET );
     if ( fgetc( fp ) == EOF && ferror( fp ) != 0 ) {
         SetError( XML_ERROR_FILE_READ_ERROR, 0, 0 );
         return _errorID;
     }
     fseek( fp, 0, SEEK_END );
     const long filelength = ftell( fp );
     fseek( fp, 0, SEEK_SET );
     if ( filelength == -1L ) {
         SetError( XML_ERROR_FILE_READ_ERROR, 0, 0 );
         return _errorID;
     }
     const size_t size = filelength;
     if ( size == 0 ) {
         SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
         return _errorID;
     }
     _charBuffer = new char[size+1];
     size_t read = fread( _charBuffer, 1, size, fp );
     if ( read != size ) {
         SetError( XML_ERROR_FILE_READ_ERROR, 0, 0 );
         return _errorID;
     }
     _charBuffer[size] = 0;
     const char* p = _charBuffer;
     p = XMLUtil::SkipWhiteSpace( p );
     p = XMLUtil::ReadBOM( p, &_writeBOM );
     if ( !p || !*p ) {
         SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
         return _errorID;
     }
     ParseDeep( _charBuffer + (p-_charBuffer), 0 );
     return _errorID;
 }
XMLComment * TinyXML2::XMLDocument::NewComment (const char * comment)
Create a new Comment associated with this Document. The memory for the Comment is managed by the Document.
Definition at line 1708 of file TinyXML2.cpp.
References _commentPool, and TinyXML2::XMLNode::SetValue().
Referenced by TinyXML2::XMLComment::ShallowClone().
 {
     XMLComment* comment = new (_commentPool.Alloc()) XMLComment( this );
     comment->_memPool = &_commentPool;
     comment->SetValue( str );
     return comment;
 }
XMLDeclaration * TinyXML2::XMLDocument::NewDeclaration (const char * text = 0)
Create a new Declaration associated with this Document. The memory for the object is managed by the Document.
If the 'text' param is null, the standard declaration is used.:
  <?xml version="1.0" encoding="UTF-8"?>
Definition at line 1726 of file TinyXML2.cpp.
References _commentPool, and TinyXML2::XMLNode::SetValue().
Referenced by TinyXML2::XMLDeclaration::ShallowClone().
 {
     XMLDeclaration* dec = new (_commentPool.Alloc()) XMLDeclaration( this );
     dec->_memPool = &_commentPool;
     dec->SetValue( str ? str : "xml version=\"1.0\" encoding=\"UTF-8\"" );
     return dec;
 }
XMLElement * TinyXML2::XMLDocument::NewElement (const char * name)
Create a new Element associated with this Document. The memory for the Element is managed by the Document.
Definition at line 1699 of file TinyXML2.cpp.
References _elementPool, TinyXML2::XMLElement::SetName(), and XMLElement.
Referenced by TinyXML2::XMLElement::ShallowClone().
 {
     XMLElement* ele = new (_elementPool.Alloc()) XMLElement( this );
     ele->_memPool = &_elementPool;
     ele->SetName( name );
     return ele;
 }
XMLText * TinyXML2::XMLDocument::NewText (const char * text)
Create a new Text associated with this Document. The memory for the Text is managed by the Document.
Definition at line 1717 of file TinyXML2.cpp.
References _textPool, and TinyXML2::XMLNode::SetValue().
Referenced by TinyXML2::XMLElement::SetText(), and TinyXML2::XMLText::ShallowClone().
 {
     XMLText* text = new (_textPool.Alloc()) XMLText( this );
     text->_memPool = &_textPool;
     text->SetValue( str );
     return text;
 }
XMLUnknown * TinyXML2::XMLDocument::NewUnknown (const char * text)
Create a new Unknown associated with this Document. The memory for the object is managed by the Document.
Definition at line 1735 of file TinyXML2.cpp.
References _commentPool, and TinyXML2::XMLNode::SetValue().
Referenced by TinyXML2::XMLUnknown::ShallowClone().
 {
     XMLUnknown* unk = new (_commentPool.Alloc()) XMLUnknown( this );
     unk->_memPool = &_commentPool;
     unk->SetValue( str );
     return unk;
 }
void TinyXML2::XMLDocument::operator= (const XMLDocument &) private
XMLError TinyXML2::XMLDocument::Parse (const char * xml, size_t nBytes = (size_t)(-1))
Parse an XML file from a character string. Returns XML_NO_ERROR (0) on success, or an errorID.
You may optionally pass in the 'nBytes', which is the number of bytes which will be parsed. If not specified, TinyXML-2 will assume 'xml' points to a null terminated string.
Definition at line 1840 of file TinyXML2.cpp.
References _attributePool, _charBuffer, _commentPool, _elementPool, _errorID, _textPool, _writeBOM, Clear(), TinyXML2::XMLNode::DeleteChildren(), Error(), TinyXML2::XMLNode::ParseDeep(), TinyXML2::XMLUtil::ReadBOM(), SetError(), TinyXML2::XMLUtil::SkipWhiteSpace(), and TinyXML2::XML_ERROR_EMPTY_DOCUMENT.
 {
   const char* start = p;
     Clear();
     if ( len == 0 || !p || !*p ) {
         SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
         return _errorID;
     }
     if ( len == (size_t)(-1) ) {
         len = strlen( p );
     }
     _charBuffer = new char[ len+1 ];
     memcpy( _charBuffer, p, len );
     _charBuffer[len] = 0;
     p = XMLUtil::SkipWhiteSpace( p );
     p = XMLUtil::ReadBOM( p, &_writeBOM );
     if ( !p || !*p ) {
         SetError( XML_ERROR_EMPTY_DOCUMENT, 0, 0 );
         return _errorID;
     }
     ptrdiff_t delta = p - start;  // skip initial whitespace, BOM, etc.
     ParseDeep( _charBuffer+delta, 0 );
     if ( Error() ) {
         // clean up now essentially dangling memory.
         // and the parse fail can put objects in the
         // pools that are dead and inaccessible.
         DeleteChildren();
         _elementPool.Clear();
         _attributePool.Clear();
         _textPool.Clear();
         _commentPool.Clear();
     }
     return _errorID;
 }
void TinyXML2::XMLDocument::Print (XMLPrinter * streamer = 0) const
Print the Document. If the Printer is not provided, it will print to stdout. If you provide Printer, this can print to a file:
XMLPrinter printer(fp);
doc.Print(&printer);
Or you can use a printer to print to memory:
XMLPrinter printer;
doc.Print(&printer);
// printer.CStr() has a const char* to the XML
Definition at line 1879 of file TinyXML2.cpp.
References Accept().
Referenced by SaveFile().
 {
     XMLPrinter stdStreamer( stdout );
     if ( !streamer ) {
         streamer = &stdStreamer;
     }
     Accept( streamer );
 }
void TinyXML2::XMLDocument::PrintError () const
If there is an error, print it to stdout.
Definition at line 1903 of file TinyXML2.cpp.
References _errorID, _errorStr1, _errorStr2, Error(), ErrorName(), and TIXML_SNPRINTF.
 {
     if ( Error() ) {
         static const int LEN = 20;
         char buf1[LEN] = { 0 };
         char buf2[LEN] = { 0 };
         if ( _errorStr1 ) {
             TIXML_SNPRINTF( buf1, LEN, "%s", _errorStr1 );
         }
         if ( _errorStr2 ) {
             TIXML_SNPRINTF( buf2, LEN, "%s", _errorStr2 );
         }
         printf( "XMLDocument error id=%d '%s' str1=%s str2=%s\n",
                 _errorID, ErrorName(), buf1, buf2 );
     }
 }
bool TinyXML2::XMLDocument::ProcessEntities () const inline
Definition at line 1598 of file TinyXML2.h.
Referenced by TinyXML2::XMLElement::ParseAttributes(), TinyXML2::XMLText::ParseDeep(), and TinyXML2::XMLPrinter::VisitEnter().
{
         return _processEntities;
     }
XMLElement* TinyXML2::XMLDocument::RootElement () inline
Return the root element of DOM. Equivalent to FirstChildElement(). To get the first node, use FirstChild().
Definition at line 1620 of file TinyXML2.h.
{
         return FirstChildElement();
     }
const XMLElement* TinyXML2::XMLDocument::RootElement () const inline
Definition at line 1623 of file TinyXML2.h.
{
         return FirstChildElement();
     }
XMLError TinyXML2::XMLDocument::SaveFile (const char * filename, bool compact = false)
Save the XML file to disk. Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1819 of file TinyXML2.cpp.
References _errorID, SetError(), and TinyXML2::XML_ERROR_FILE_COULD_NOT_BE_OPENED.
 {
     FILE* fp = callfopen( filename, "w" );
     if ( !fp ) {
         SetError( XML_ERROR_FILE_COULD_NOT_BE_OPENED, filename, 0 );
         return _errorID;
     }
     SaveFile(fp, compact);
     fclose( fp );
     return _errorID;
 }
XMLError TinyXML2::XMLDocument::SaveFile (FILE * fp, bool compact = false)
Save the XML file to disk. You are responsible for providing and closing the FILE*.
Returns XML_NO_ERROR (0) on success, or an errorID.
Definition at line 1832 of file TinyXML2.cpp.
References _errorID, and Print().
 {
     XMLPrinter stream( fp, compact );
     Print( &stream );
     return _errorID;
 }
void TinyXML2::XMLDocument::SetBOM (bool useBOM) inline
Sets whether to write the BOM when writing the file.
Definition at line 1613 of file TinyXML2.h.
{
         _writeBOM = useBOM;
     }
void TinyXML2::XMLDocument::SetError (XMLError error, const char * str1, const char * str2)
Definition at line 1889 of file TinyXML2.cpp.
References _errorID, _errorStr1, _errorStr2, TIXMLASSERT, and TinyXML2::XML_ERROR_COUNT.
Referenced by LoadFile(), Parse(), TinyXML2::XMLElement::ParseAttributes(), TinyXML2::XMLNode::ParseDeep(), TinyXML2::XMLText::ParseDeep(), TinyXML2::XMLComment::ParseDeep(), TinyXML2::XMLDeclaration::ParseDeep(), TinyXML2::XMLUnknown::ParseDeep(), and SaveFile().
 {
     TIXMLASSERT( error >= 0 && error < XML_ERROR_COUNT );
     _errorID = error;
     _errorStr1 = str1;
     _errorStr2 = str2;
 }
virtual XMLNode* TinyXML2::XMLDocument::ShallowClone (XMLDocument * document) const inline virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements TinyXML2::XMLNode.
Definition at line 1720 of file TinyXML2.h.
{
         return 0;
     }
virtual bool TinyXML2::XMLDocument::ShallowEqual (const XMLNode * compare) const inline virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements TinyXML2::XMLNode.
Definition at line 1723 of file TinyXML2.h.
{
         return false;
     }
virtual XMLDocument* TinyXML2::XMLDocument::ToDocument () inline virtual
Safely cast to a Document, or null.
Reimplemented from TinyXML2::XMLNode.
Definition at line 1547 of file TinyXML2.h.
{
         return this;
     }
virtual const XMLDocument* TinyXML2::XMLDocument::ToDocument () const inline virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 1550 of file TinyXML2.h.
{
         return this;
     }
Whitespace TinyXML2::XMLDocument::WhitespaceMode () const inline
Definition at line 1601 of file TinyXML2.h.
Referenced by TinyXML2::XMLText::ParseDeep().
{
         return _whitespace;
     }
Friends And Related Function Documentation
friend class XMLElement friend
Definition at line 1541 of file TinyXML2.h.
Referenced by Identify(), and NewElement().
Member Data Documentation
MemPoolT< sizeof(XMLAttribute) > TinyXML2::XMLDocument::_attributePool private
Definition at line 1740 of file TinyXML2.h.
Referenced by Clear(), TinyXML2::XMLElement::FindOrCreateAttribute(), Parse(), and TinyXML2::XMLElement::ParseAttributes().
char* TinyXML2::XMLDocument::_charBuffer private
Definition at line 1737 of file TinyXML2.h.
Referenced by Clear(), LoadFile(), and Parse().
MemPoolT< sizeof(XMLComment) > TinyXML2::XMLDocument::_commentPool private
Definition at line 1742 of file TinyXML2.h.
Referenced by Clear(), Identify(), NewComment(), NewDeclaration(), NewUnknown(), and Parse().
MemPoolT< sizeof(XMLElement) > TinyXML2::XMLDocument::_elementPool private
Definition at line 1739 of file TinyXML2.h.
Referenced by Clear(), Identify(), NewElement(), and Parse().
XMLError TinyXML2::XMLDocument::_errorID private
Definition at line 1733 of file TinyXML2.h.
Referenced by Clear(), ErrorName(), LoadFile(), Parse(), PrintError(), SaveFile(), and SetError().
const char * TinyXML2::XMLDocument::_errorNames static private
Initial value:
= {
    "XML_SUCCESS",
    "XML_NO_ATTRIBUTE",
    "XML_WRONG_ATTRIBUTE_TYPE",
    "XML_ERROR_FILE_NOT_FOUND",
    "XML_ERROR_FILE_COULD_NOT_BE_OPENED",
    "XML_ERROR_FILE_READ_ERROR",
    "XML_ERROR_ELEMENT_MISMATCH",
    "XML_ERROR_PARSING_ELEMENT",
    "XML_ERROR_PARSING_ATTRIBUTE",
    "XML_ERROR_IDENTIFYING_TAG",
    "XML_ERROR_PARSING_TEXT",
    "XML_ERROR_PARSING_CDATA",
    "XML_ERROR_PARSING_COMMENT",
    "XML_ERROR_PARSING_DECLARATION",
    "XML_ERROR_PARSING_UNKNOWN",
    "XML_ERROR_EMPTY_DOCUMENT",
    "XML_ERROR_MISMATCHED_ELEMENT",
    "XML_ERROR_PARSING",
    "XML_CAN_NOT_CONVERT_TEXT",
    "XML_NO_TEXT_NODE"
}
Definition at line 1744 of file TinyXML2.h.
Referenced by ErrorName().
const char* TinyXML2::XMLDocument::_errorStr1 private
Definition at line 1735 of file TinyXML2.h.
Referenced by Clear(), PrintError(), and SetError().
const char* TinyXML2::XMLDocument::_errorStr2 private
Definition at line 1736 of file TinyXML2.h.
Referenced by Clear(), PrintError(), and SetError().
bool TinyXML2::XMLDocument::_processEntities private
Definition at line 1732 of file TinyXML2.h.
MemPoolT< sizeof(XMLText) > TinyXML2::XMLDocument::_textPool private
Definition at line 1741 of file TinyXML2.h.
Referenced by Clear(), Identify(), NewText(), and Parse().
Whitespace TinyXML2::XMLDocument::_whitespace private
Definition at line 1734 of file TinyXML2.h.
bool TinyXML2::XMLDocument::_writeBOM private
Definition at line 1731 of file TinyXML2.h.
Referenced by LoadFile(), and Parse().
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp