Voxel: Voxel::FrameGenerator Class Reference
Voxel::FrameGenerator Class Reference abstract
#include <FrameGenerator.h>
Public Member Functions
FrameGenerator (GeneratorIDType id, int frameType, uint8_t majorVersion, uint8_t minorVersion)
const GeneratorIDType & id () const
void setFrameStreamWriter (Ptr< FrameStreamWriter > &writer)
void removeFrameStreamWriter ()
virtual bool readConfiguration (SerializedObject &object)
virtual bool writeConfiguration ()
virtual bool generate (const FramePtr &in, FramePtr &out)=0
template<typename T >
bool get (const String &name, T &value) const
virtual ~FrameGenerator ()
template<>
bool get (const String &name, String &value) const
Protected Member Functions
virtual bool _onReadConfiguration ()=0
virtual bool _onWriteConfiguration ()=0
bool _getParam (const String &name, SerializablePtr &param) const
template<typename T >
bool _set (const String &name, const T &value)
template<>
bool _set (const String &name, const String &value)
Protected Attributes
GeneratorIDType _id
int _frameType
Ptr< FrameStreamWriter > _frameStreamWriter
StringKeySerializableMap _frameGeneratorParameters
uint8_t _majorVersion
uint8_t _minorVersion
Detailed Description
Definition at line 20 of file FrameGenerator.h.
Constructor & Destructor Documentation
Voxel::FrameGenerator::FrameGenerator (GeneratorIDType id, int frameType, uint8_t majorVersion, uint8_t minorVersion) inline
Definition at line 40 of file FrameGenerator.h.
                                                                                                : _id(id), _frameType(frameType),
   _majorVersion(majorVersion), _minorVersion(minorVersion)
   {
     _frameGeneratorParameters["version"] =
         SerializablePtr(new SerializableUnsignedInt((majorVersion << 8) + minorVersion));
   }
virtual Voxel::FrameGenerator::~FrameGenerator () inline virtual
Definition at line 60 of file FrameGenerator.h.
 {}
Member Function Documentation
bool Voxel::FrameGenerator::_getParam (const String & name, SerializablePtr & param) const inline protected
Definition at line 64 of file FrameGenerator.h.
References _frameGeneratorParameters, and LensCalibrationTest::x.
Referenced by _set(), and get().
 {
   auto x = _frameGeneratorParameters.find(name);
   if(x != _frameGeneratorParameters.end())
   {
     param = x->second;
     return true;
   }
   return false;
 }
virtual bool Voxel::FrameGenerator::_onReadConfiguration () protected pure virtual
Implemented in Voxel::TI::ToFFrameGenerator, Voxel::TI::ToFDepthFrameGenerator, and Voxel::PointCloudFrameGenerator.
Referenced by readConfiguration().
virtual bool Voxel::FrameGenerator::_onWriteConfiguration () protected pure virtual
Implemented in Voxel::TI::ToFFrameGenerator, Voxel::TI::ToFDepthFrameGenerator, and Voxel::PointCloudFrameGenerator.
Referenced by writeConfiguration().
template<typename T > bool Voxel::FrameGenerator::_set (const String & name, const T & value) inline protected
Definition at line 78 of file FrameGenerator.h.
References _getParam(), and Voxel::BasicSerializable< T >::value.
Referenced by Voxel::PointCloudFrameGenerator::setParameters(), Voxel::TI::ToFDepthFrameGenerator::setParameters(), and Voxel::TI::ToFFrameGenerator::setParameters().
 {
   SerializablePtr param;
   if(!_getParam(name, param))
     return false;
   BasicSerializable<T> *p = dynamic_cast<BasicSerializable<T> *>(param.get());
   if(p)
   {
     p->value = value;
     return true;
   }
   return false;
 }
template<> bool Voxel::FrameGenerator::_set (const String & name, const String & value) inline protected
Definition at line 96 of file FrameGenerator.h.
 {
   SerializablePtr param;
   if(!_getParam(name, param))
     return false;
   SerializableString *p = dynamic_cast<SerializableString *>(param.get());
   if(p)
   {
     *p = value;
     return true;
   }
   return false;
 }
virtual bool Voxel::FrameGenerator::generate (const FramePtr & in, FramePtr & out) pure virtual
Implemented in Voxel::TI::ToFFrameGenerator, Voxel::TI::ToFDepthFrameGenerator, and Voxel::PointCloudFrameGenerator.
template<typename T > bool Voxel::FrameGenerator::get (const String & name, T & value) const inline
Definition at line 114 of file FrameGenerator.h.
References _getParam(), and Voxel::BasicSerializable< T >::value.
 {
   SerializablePtr param;
   if(!_getParam(name, param))
     return false;
   const BasicSerializable<T> *p = dynamic_cast<BasicSerializable<T> *>(param.get());
   if(p)
   {
     value = p->value;
     return true;
   }
   return false;
 }
template<> bool Voxel::FrameGenerator::get (const String & name, String & value) const inline
Definition at line 132 of file FrameGenerator.h.
 {
   SerializablePtr param;
   if(!_getParam(name, param))
     return false;
   SerializableString *p = dynamic_cast<SerializableString *>(param.get());
   if(p)
   {
     value = *p;
     return true;
   }
   return false;
 }
const GeneratorIDType& Voxel::FrameGenerator::id () const inline
Definition at line 47 of file FrameGenerator.h.
 { return _id; }
bool Voxel::FrameGenerator::readConfiguration (SerializedObject & object) virtual
Definition at line 31 of file FrameGenerator.cpp.
References _frameGeneratorParameters, _majorVersion, _minorVersion, _onReadConfiguration(), and Voxel::SerializableMap< Key >::read().
 {
   if(!_frameGeneratorParameters.read(object))
     return false;
   uint32_t version;
   if(!get("version", version))
     return false;
   _majorVersion = (version & 0xFF00) >> 8;
   _minorVersion = (version & 0xFF);
   if(!_onReadConfiguration())
     return false;
   return true;
 }
void Voxel::FrameGenerator::removeFrameStreamWriter () inline
Definition at line 50 of file FrameGenerator.h.
 { _frameStreamWriter = nullptr; }
void Voxel::FrameGenerator::setFrameStreamWriter (Ptr< FrameStreamWriter > & writer) inline
Definition at line 49 of file FrameGenerator.h.
 { _frameStreamWriter = writer; }
bool Voxel::FrameGenerator::writeConfiguration () virtual
Definition at line 13 of file FrameGenerator.cpp.
References _frameGeneratorParameters, _frameStreamWriter, _frameType, _onWriteConfiguration(), Voxel::SerializableMap< Key >::serializedSize(), and Voxel::SerializableMap< Key >::write().
Referenced by Voxel::PointCloudFrameGenerator::setParameters(), Voxel::TI::ToFDepthFrameGenerator::setParameters(), and Voxel::TI::ToFFrameGenerator::setParameters().
 {
   if(!_frameStreamWriter)
     return true;
   auto &p = _frameStreamWriter->getConfigObject();
   p.resize(_frameGeneratorParameters.serializedSize());
   if(!_frameGeneratorParameters.write(p))
     return false;
   if(!_onWriteConfiguration())
     return false;
   return _frameStreamWriter->writeGeneratorConfiguration(_frameType);
 }
Member Data Documentation
StringKeySerializableMap Voxel::FrameGenerator::_frameGeneratorParameters protected
Definition at line 27 of file FrameGenerator.h.
Referenced by _getParam(), Voxel::PointCloudFrameGenerator::PointCloudFrameGenerator(), readConfiguration(), Voxel::TI::ToFDepthFrameGenerator::ToFDepthFrameGenerator(), Voxel::TI::ToFFrameGenerator::ToFFrameGenerator(), and writeConfiguration().
Ptr<FrameStreamWriter> Voxel::FrameGenerator::_frameStreamWriter protected
Definition at line 25 of file FrameGenerator.h.
Referenced by writeConfiguration().
int Voxel::FrameGenerator::_frameType protected
Definition at line 24 of file FrameGenerator.h.
Referenced by writeConfiguration().
GeneratorIDType Voxel::FrameGenerator::_id protected
Definition at line 23 of file FrameGenerator.h.
uint8_t Voxel::FrameGenerator::_majorVersion protected
Definition at line 29 of file FrameGenerator.h.
Referenced by Voxel::TI::ToFFrameGenerator::_onReadConfiguration(), and readConfiguration().
uint8_t Voxel::FrameGenerator::_minorVersion protected
Definition at line 29 of file FrameGenerator.h.
Referenced by Voxel::TI::ToFFrameGenerator::_onReadConfiguration(), and readConfiguration().
The documentation for this class was generated from the following files:
FrameGenerator.h
FrameGenerator.cpp