Voxel: Voxel::Device Class Reference
Voxel::Device Class Reference
Camera System Components
#include <Device.h>
Public Types
enum Interface { USB = 0, LPT = 1, SERIAL = 2, I2C = 3 }
Public Member Functions
Device (Interface interfaceid, const String &deviceid, const String &serialnumber, int channelID=-1, const String &description="", const String &serialIndex="", bool showSerialIndex=false)
virtual Vector< Ptr< Device > > getDevices (const Vector< int > &channels) const
const String & id () const
Interface interfaceID () const
const String & deviceID () const
const String & serialNumber () const
void setSerialNumber (const String &s)
const String & serialIndex () const
void showSerialIndex ()
void dontShowSerialIndex ()
const int channelID () const
const String & description () const
virtual ~Device ()
Protected Member Functions
void _makeID ()
Protected Attributes
String _id
Interface _interfaceID
String _deviceID
String _serialNumber
String _serialIndex
bool _showSerialIndex
String _description
int _channelID
Detailed Description
Definition at line 20 of file Device.h.
Member Enumeration Documentation
enum Voxel::Device::Interface
Enumerator
USB
LPT
SERIAL
I2C
Definition at line 23 of file Device.h.
                  {
     USB = 0,
     LPT = 1,
     SERIAL = 2,
     I2C = 3
   };
Constructor & Destructor Documentation
Voxel::Device::Device (Interface interfaceid, const String & deviceid, const String & serialnumber, int channelID = -1, const String & description = "", const String & serialIndex = "", bool showSerialIndex = false) inline
Definition at line 56 of file Device.h.
                                                                                                                                                                                                      : _interfaceID(interfaceid),
     _deviceID(deviceid), _serialNumber(serialnumber), _description(description), _channelID(channelID), _serialIndex(serialIndex), _showSerialIndex(showSerialIndex)
   {
     _makeID();
   }
virtual Voxel::Device::~Device () inline virtual
Definition at line 76 of file Device.h.
 {}
Member Function Documentation
void Voxel::Device::_makeID () inline protected
Definition at line 41 of file Device.h.
   {
     std::ostringstream s;
     s << _interfaceID << "::" <<  _deviceID << "::" << _serialNumber;
     if(_showSerialIndex)
       s << ":" << _serialIndex;
     if(_channelID >= 0)
       s << "::" << _channelID;
     _id = s.str();
   }
const int Voxel::Device::channelID () const inline
Definition at line 74 of file Device.h.
Referenced by Voxel::USBSystemPrivate::getDeviceNode().
 { return _channelID; }
const String& Voxel::Device::description () const inline
Definition at line 75 of file Device.h.
Referenced by Voxel::USBDevice::getDevices().
 { return _description; }
const String& Voxel::Device::deviceID () const inline
Definition at line 68 of file Device.h.
 { return _deviceID; }
void Voxel::Device::dontShowSerialIndex () inline
Definition at line 73 of file Device.h.
 { _showSerialIndex = false; _makeID(); }
virtual Vector<Ptr<Device> > Voxel::Device::getDevices (const Vector< int > & channels) const inline virtual
Reimplemented in Voxel::USBDevice.
Definition at line 63 of file Device.h.
 { return Vector<Ptr<Device>>(); }
const String& Voxel::Device::id () const inline
Definition at line 65 of file Device.h.
Referenced by Voxel::USBSystemPrivate::getDeviceHandle(), and Voxel::USBIO::USBIOPrivate::USBIOPrivate().
 { return _id; }
Interface Voxel::Device::interfaceID () const inline
Definition at line 67 of file Device.h.
 { return _interfaceID; }
const String& Voxel::Device::serialIndex () const inline
Definition at line 71 of file Device.h.
Referenced by Voxel::USBSystemPrivate::getBusDevNumbers(), Voxel::USBSystemPrivate::getDeviceNode(), and Voxel::USBDevice::getDevices().
 { return _serialIndex; }
const String& Voxel::Device::serialNumber () const inline
Definition at line 69 of file Device.h.
Referenced by Voxel::TI::Voxel14Camera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::USBSystemPrivate::getBusDevNumbers(), Voxel::USBSystemPrivate::getDeviceNode(), Voxel::USBDevice::getDevices(), and main().
 { return _serialNumber; }
void Voxel::Device::setSerialNumber (const String & s) inline
Definition at line 70 of file Device.h.
 { _serialNumber = s; }
void Voxel::Device::showSerialIndex () inline
Definition at line 72 of file Device.h.
 { _showSerialIndex = true; _makeID(); }
Member Data Documentation
int Voxel::Device::_channelID protected
Definition at line 39 of file Device.h.
String Voxel::Device::_description protected
Definition at line 38 of file Device.h.
String Voxel::Device::_deviceID protected
Definition at line 32 of file Device.h.
String Voxel::Device::_id protected
Definition at line 30 of file Device.h.
Interface Voxel::Device::_interfaceID protected
Definition at line 31 of file Device.h.
String Voxel::Device::_serialIndex protected
Definition at line 35 of file Device.h.
String Voxel::Device::_serialNumber protected
Definition at line 33 of file Device.h.
bool Voxel::Device::_showSerialIndex protected
Definition at line 36 of file Device.h.
Referenced by Voxel::USBDevice::getDevices().
The documentation for this class was generated from the following file:
Device.h