Voxel: ELFIO::dump Class Reference
ELFIO::dump Class Reference
#include <elfio_dump.hpp>
Static Public Member Functions
static void header (std::ostream &out, const elfio &reader)
static void section_headers (std::ostream &out, const elfio &reader)
static void section_header (std::ostream &out, Elf_Half no, const section *sec, unsigned char elf_class)
static void segment_headers (std::ostream &out, const elfio &reader)
static void segment_header (std::ostream &out, Elf_Half no, const segment *seg, unsigned int elf_class)
static void symbol_tables (std::ostream &out, const elfio &reader)
static void symbol_table (std::ostream &out, Elf_Half no, std::string &name, Elf64_Addr value, Elf_Xword size, unsigned char bind, unsigned char type, Elf_Half section, unsigned int elf_class)
static void notes (std::ostream &out, const elfio &reader)
static void note (std::ostream &out, int no, Elf_Word type, const std::string &name)
static void dynamic_tags (std::ostream &out, const elfio &reader)
static void dynamic_tag (std::ostream &out, int no, Elf_Xword tag, Elf_Xword value, std::string str, unsigned int)
static void section_data (std::ostream &out, const section *sec)
static void section_datas (std::ostream &out, const elfio &reader)
static void segment_data (std::ostream &out, Elf_Half no, const segment *seg)
static void segment_datas (std::ostream &out, const elfio &reader)
Static Private Member Functions
template<typename T , typename K >
static std::string find_value_in_table (const T &table, const K &key)
template<typename T , typename K >
static std::string format_assoc (const T &table, const K &key)
template<typename T >
static std::string format_assoc (const T &table, const char key)
static std::string section_flags (Elf_Xword flags)
Detailed Description
Definition at line 419 of file elfio_dump.hpp.
Member Function Documentation
static void ELFIO::dump::dynamic_tag (std::ostream & out, int no, Elf_Xword tag, Elf_Xword value, std::string str, unsigned int) inline static
Definition at line 749 of file elfio_dump.hpp.
References DUMP_DEC_FORMAT, DUMP_HEX_FORMAT, and DUMP_STR_FORMAT.
Referenced by dynamic_tags().
     {
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_STR_FORMAT( 16 ) << str_dynamic_tag( tag ) << " ";
             if ( str.empty() ) {
                 out << DUMP_HEX_FORMAT( 16 ) << value                  << " ";
             }
             else {
                 out << DUMP_STR_FORMAT( 32 ) << str                    << " ";
             }
             out << std::endl;
     }
static void ELFIO::dump::dynamic_tags (std::ostream & out, const elfio & reader) inline static
Definition at line 718 of file elfio_dump.hpp.
References DT_NULL, dynamic_tag(), ELFIO::dynamic_section_accessor::get_entries_num(), ELFIO::dynamic_section_accessor::get_entry(), ELFIO::elfio::sections, SHT_DYNAMIC, and ELFIO::elfio::Sections::size().
     {
         Elf_Half n = reader.sections.size();
         for ( Elf_Half i = 0; i < n; ++i ) {    // For all sections
             section* sec = reader.sections[i];
             if ( SHT_DYNAMIC == sec->get_type() ) {
                 dynamic_section_accessor dynamic( reader, sec );
                 Elf_Xword dyn_no = dynamic.get_entries_num();
                 if ( dyn_no > 0 ) {
                     out << "Dynamic section (" << sec->get_name() << ")" << std::endl;
                     out << "[  Nr ] Tag              Name/Value" << std::endl;
                     for ( int i = 0; i < dyn_no; ++i ) {
                         Elf_Xword   tag   = 0;
                         Elf_Xword   value = 0;
                         std::string str;
                         dynamic.get_entry( i, tag, value, str );
                         dynamic_tag( out, i, tag, value, str, reader.get_class() );
                         if ( DT_NULL == tag ) {
                             break;
                         }
                     }
                     out << std::endl;
                 }
             }
         }
     }
template<typename T , typename K > static std::string ELFIO::dump::find_value_in_table (const T & table, const K & key) inline static private
Definition at line 875 of file elfio_dump.hpp.
Referenced by format_assoc().
     {
         std::string res = "?";
         for ( unsigned int i = 0; i < sizeof( table )/sizeof( table[0] ); ++i ) {
             if ( table[i].key == key ) {
                 res = table[i].str;
                 break;
             }
         }
         return res;
     }
template<typename T , typename K > static std::string ELFIO::dump::format_assoc (const T & table, const K & key) inline static private
Definition at line 893 of file elfio_dump.hpp.
References find_value_in_table().
Referenced by format_assoc().
     {
         std::string str = find_value_in_table( table, key );
         if ( str == "?" ) {
             std::ostringstream oss;
             oss << str << " (0x" << std::hex << key << ")";
             str = oss.str();
         }
         return str;
     }
template<typename T > static std::string ELFIO::dump::format_assoc (const T & table, const char key) inline static private
Definition at line 910 of file elfio_dump.hpp.
References format_assoc().
     {
         return format_assoc( table, (const int)key );
     }
static void ELFIO::dump::header (std::ostream & out, const elfio & reader) inline static
Definition at line 431 of file elfio_dump.hpp.
     {
         out << "ELF Header"     << std::endl                               << std::endl
             << "  Class:      " << str_class( reader.get_class() )         << std::endl
             << "  Encoding:   " << str_endian( reader.get_encoding() )     << std::endl
             << "  ELFVersion: " << str_version( reader.get_elf_version() ) << std::endl
             << "  Type:       " << str_type( reader.get_type() )           << std::endl
             << "  Machine:    " << str_machine( reader.get_machine() )     << std::endl
             << "  Version:    " << str_version( reader.get_version() )     << std::endl
             << "  Entry:      " << "0x" << std::hex << reader.get_entry()  << std::endl
             << "  Flags:      " << "0x" << std::hex << reader.get_flags()  << std::endl
             << std::endl;
     }
static void ELFIO::dump::note (std::ostream & out, int no, Elf_Word type, const std::string & name) inline static
Definition at line 703 of file elfio_dump.hpp.
References DUMP_DEC_FORMAT, DUMP_HEX_FORMAT, and DUMP_STR_FORMAT.
Referenced by notes().
     {
         out << "  ["
             << DUMP_DEC_FORMAT( 2 ) << no
             << "] "
             << DUMP_HEX_FORMAT( 8 ) << type << " "
             << DUMP_STR_FORMAT( 1 ) << name
             << std::endl;
     }
static void ELFIO::dump::notes (std::ostream & out, const elfio & reader) inline static
Definition at line 671 of file elfio_dump.hpp.
References ELFIO::note_section_accessor::get_note(), ELFIO::note_section_accessor::get_notes_num(), note(), ELFIO::elfio::sections, SHT_NOTE, and ELFIO::elfio::Sections::size().
     {
         Elf_Half no = reader.sections.size();
         for ( Elf_Half i = 0; i < no; ++i ) {                 // For all sections
             section* sec = reader.sections[i];
             if ( SHT_NOTE == sec->get_type() ) {              // Look at notes
                 note_section_accessor notes( reader, sec );
                 int no_notes = notes.get_notes_num();
                 if ( no > 0 ) {
                     out << "Note section (" << sec->get_name() << ")" << std::endl
                         << "    No Type     Name"
                         << std::endl;
                     for ( int j = 0; j < no_notes; ++j ) {    // For all notes
                         Elf_Word    type;
                         std::string name;
                         void*       desc;
                         Elf_Word    descsz;
                         notes.get_note( j, type, name, desc, descsz );
                         // 'name' usually contains \0 at the end. Try to fix it
                         name = name.c_str();
                         note( out, j, type, name );
                     }
                     out << std::endl;
                 }
             }
         }
     }
static void ELFIO::dump::section_data (std::ostream & out, const section * sec) inline static
Definition at line 771 of file elfio_dump.hpp.
References DUMP_HEX_FORMAT, and ELFIO::section::get_data().
Referenced by section_datas().
     {
         std::ios_base::fmtflags original_flags = out.flags();
         out << sec->get_name() << std::endl;
         const char* pdata = sec->get_data();
         ELFIO::Elf_Xword i;
         for ( i = 0; i < std::min( sec->get_size(), MAX_DATA_ENTRIES ); ++i ) {
             if ( i % 16 == 0 ) {
                 out << "[" <<  DUMP_HEX_FORMAT( 8 ) << i << "]";
             }
             out << " " << DUMP_HEX_FORMAT( 2 ) << ( pdata[i] & 0x000000FF );
             if ( i % 16 == 15 ) {
                 out << std::endl;
             }
         }
         if ( i % 16 != 0 ) {
             out << std::endl;
         }
         out.flags(original_flags);
         return;
     }
static void ELFIO::dump::section_datas (std::ostream & out, const elfio & reader) inline static
Definition at line 800 of file elfio_dump.hpp.
References section_data(), ELFIO::elfio::sections, SHT_NOBITS, and ELFIO::elfio::Sections::size().
     {
         Elf_Half n = reader.sections.size();
         if ( n == 0 ) {
             return;
         }
         out << "Section Data:" << std::endl;
         for ( Elf_Half i = 1; i < n; ++i ) { // For all sections
             section* sec = reader.sections[i];
             if ( sec->get_type() == SHT_NOBITS ) {
                 continue;
             }
             section_data( out, sec );
         }
         out << std::endl;
     }
static std::string ELFIO::dump::section_flags (Elf_Xword flags) inline static private
Definition at line 919 of file elfio_dump.hpp.
References SHF_ALLOC, SHF_EXECINSTR, and SHF_WRITE.
Referenced by section_header().
     {
         std::string ret = "";
         if ( flags & SHF_WRITE ) {
             ret += "W";
         }
         if ( flags & SHF_ALLOC ) {
             ret += "A";
         }
         if ( flags & SHF_EXECINSTR ) {
             ret += "X";
         }
         return ret;
     }
static void ELFIO::dump::section_header (std::ostream & out, Elf_Half no, const section * sec, unsigned char elf_class) inline static
Definition at line 475 of file elfio_dump.hpp.
References DUMP_DEC_FORMAT, DUMP_HEX_FORMAT, DUMP_STR_FORMAT, ELFCLASS32, and section_flags().
Referenced by section_headers().
     {
         std::ios_base::fmtflags original_flags = out.flags();
         if ( elf_class == ELFCLASS32 ) { // Output for 32-bit
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_STR_FORMAT( 17 ) << str_section_type( sec->get_type() ) << " "
                 << DUMP_HEX_FORMAT(  8 ) << sec->get_address()                  << " "
                 << DUMP_HEX_FORMAT(  8 ) << sec->get_size()                     << " "
                 << DUMP_HEX_FORMAT(  2 ) << sec->get_entry_size()               << " "
                 << DUMP_STR_FORMAT(  3 ) << section_flags( sec->get_flags() )   << " "
                 << DUMP_HEX_FORMAT(  2 ) << sec->get_link()                     << " "
                 << DUMP_HEX_FORMAT(  3 ) << sec->get_info()                     << " "
                 << DUMP_HEX_FORMAT(  2 ) << sec->get_addr_align()               << " "
                 << DUMP_STR_FORMAT( 17 ) << sec->get_name()                     << " "
                 << std::endl;
         }
         else {                           // Output for 64-bit
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_STR_FORMAT( 17 ) << str_section_type( sec->get_type() ) << " "
                 << DUMP_HEX_FORMAT( 16 ) << sec->get_address()                  << " "
                 << DUMP_HEX_FORMAT( 16 ) << sec->get_size()                     << " "
                 << DUMP_HEX_FORMAT(  4 ) << sec->get_entry_size()               << " "
                 << DUMP_STR_FORMAT(  3 ) << section_flags( sec->get_flags() )   << " "
                 << std::endl
                 << "        "
                 << DUMP_HEX_FORMAT(  4 ) << sec->get_link()                     << " "
                 << DUMP_HEX_FORMAT(  4 ) << sec->get_info()                     << " "
                 << DUMP_HEX_FORMAT(  4 ) << sec->get_addr_align()               << "    "
                 << DUMP_STR_FORMAT( 17 ) << sec->get_name()                     << " "
                 << std::endl;
         }
         out.flags(original_flags);
         return;
     }
static void ELFIO::dump::section_headers (std::ostream & out, const elfio & reader) inline static
Definition at line 447 of file elfio_dump.hpp.
References ELFCLASS32, section_header(), ELFIO::elfio::sections, and ELFIO::elfio::Sections::size().
     {
         Elf_Half n = reader.sections.size();
         if ( n == 0 ) {
             return;
         }
         out << "Section Headers:" << std::endl;
         if ( reader.get_class() == ELFCLASS32 ) { // Output for 32-bit
             out << "[  Nr ] Type              Addr     Size     ES Flg Lk Inf Al Name" << std::endl;
         }
         else {                                    // Output for 64-bit
             out << "[  Nr ] Type              Addr             Size             ES   Flg" << std::endl
                 << "        Lk   Inf  Al      Name" << std::endl;
         }
         for ( Elf_Half i = 0; i < n; ++i ) { // For all sections
             section* sec = reader.sections[i];
             section_header( out, i, sec, reader.get_class() );
         }
         out << "Key to Flags: W (write), A (alloc), X (execute)\n\n"
             << std::endl;
     }
static void ELFIO::dump::segment_data (std::ostream & out, Elf_Half no, const segment * seg) inline static
Definition at line 823 of file elfio_dump.hpp.
References DUMP_HEX_FORMAT, and ELFIO::segment::get_data().
Referenced by segment_datas().
     {
         std::ios_base::fmtflags original_flags = out.flags();
         out << "Segment # " << no << std::endl;
         const char* pdata = seg->get_data();
         ELFIO::Elf_Xword i;
         for ( i = 0; i < std::min( seg->get_file_size(), MAX_DATA_ENTRIES ); ++i ) {
             if ( i % 16 == 0 ) {
                 out << "[" <<  DUMP_HEX_FORMAT( 8 ) << i << "]";
             }
             out << " " << DUMP_HEX_FORMAT( 2 ) << ( pdata[i] & 0x000000FF );
             if ( i % 16 == 15 ) {
                 out << std::endl;
             }
         }
         if ( i % 16 != 0 ) {
             out << std::endl;
         }
         out.flags(original_flags);
         return;
     }
static void ELFIO::dump::segment_datas (std::ostream & out, const elfio & reader) inline static
Definition at line 852 of file elfio_dump.hpp.
References segment_data(), ELFIO::elfio::segments, and ELFIO::elfio::Segments::size().
     {
         Elf_Half n = reader.segments.size();
         if ( n == 0 ) {
             return;
         }
         out << "Segment Data:" << std::endl;
         for ( Elf_Half i = 0; i < n; ++i ) { // For all sections
             segment* seg = reader.segments[i];
             segment_data( out, i, seg );
         }
         out << std::endl;
     }
static void ELFIO::dump::segment_header (std::ostream & out, Elf_Half no, const segment * seg, unsigned int elf_class) inline static
Definition at line 548 of file elfio_dump.hpp.
References DUMP_DEC_FORMAT, DUMP_HEX_FORMAT, DUMP_STR_FORMAT, and ELFCLASS32.
Referenced by segment_headers().
     {
         std::ios_base::fmtflags original_flags = out.flags();
         if ( elf_class == ELFCLASS32 ) { // Output for 32-bit
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_STR_FORMAT( 14 ) << str_segment_type( seg->get_type() )  << " "
                 << DUMP_HEX_FORMAT(  8 ) << seg->get_virtual_address()           << " "
                 << DUMP_HEX_FORMAT(  8 ) << seg->get_physical_address()          << " "
                 << DUMP_HEX_FORMAT(  8 ) << seg->get_file_size()                 << " "
                 << DUMP_HEX_FORMAT(  8 ) << seg->get_memory_size()               << " "
                 << DUMP_STR_FORMAT(  8 ) << str_segment_flag( seg->get_flags() ) << " "
                 << DUMP_HEX_FORMAT(  8 ) << seg->get_align()                     << " "
                 << std::endl;
         }
         else {                           // Output for 64-bit
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_STR_FORMAT( 14 ) << str_segment_type( seg->get_type() )  << " "
                 << DUMP_HEX_FORMAT( 16 ) << seg->get_virtual_address()           << " "
                 << DUMP_HEX_FORMAT( 16 ) << seg->get_physical_address()          << " "
                 << DUMP_STR_FORMAT( 16 ) << str_segment_flag( seg->get_flags() ) << " "
                 << std::endl
                 << "                       "
                 << DUMP_HEX_FORMAT( 16 ) << seg->get_file_size()                 << " "
                 << DUMP_HEX_FORMAT( 16 ) << seg->get_memory_size()               << " "
                 << DUMP_HEX_FORMAT( 16 ) << seg->get_align()                     << " "
                 << std::endl;
         }
         out.flags(original_flags);
     }
static void ELFIO::dump::segment_headers (std::ostream & out, const elfio & reader) inline static
Definition at line 520 of file elfio_dump.hpp.
References ELFCLASS32, segment_header(), ELFIO::elfio::segments, and ELFIO::elfio::Segments::size().
     {
         Elf_Half n = reader.segments.size();
         if ( n == 0 ) {
             return;
         }
         out << "Segment headers:" << std::endl;
         if ( reader.get_class() == ELFCLASS32 ) { // Output for 32-bit
             out << "[  Nr ] Type           VirtAddr PhysAddr FileSize Mem.Size Flags    Align"
                 << std::endl;
         }
         else {                                    // Output for 64-bit
             out << "[  Nr ] Type           VirtAddr         PhysAddr         Flags" << std::endl
                 << "                       FileSize         Mem.Size         Align"
                 << std::endl;
         }
         for ( Elf_Half i = 0; i < n; ++i ) {
             segment* seg = reader.segments[i];
             segment_header( out, i, seg, reader.get_class() );
         }
         out << std::endl;
     }
static void ELFIO::dump::symbol_table (std::ostream & out, Elf_Half no, std::string & name, Elf64_Addr value, Elf_Xword size, unsigned char bind, unsigned char type, Elf_Half section, unsigned int elf_class) inline static
Definition at line 627 of file elfio_dump.hpp.
References DUMP_DEC_FORMAT, DUMP_HEX_FORMAT, DUMP_STR_FORMAT, and ELFCLASS32.
Referenced by symbol_tables().
     {
         std::ios_base::fmtflags original_flags = out.flags();
         if ( elf_class == ELFCLASS32 ) { // Output for 32-bit
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_HEX_FORMAT(  8 ) << value                   << " "
                 << DUMP_HEX_FORMAT(  8 ) << size                    << " "
                 << DUMP_STR_FORMAT(  7 ) << str_symbol_type( type ) << " "
                 << DUMP_STR_FORMAT(  8 ) << str_symbol_bind( bind ) << " "
                 << DUMP_DEC_FORMAT(  5 ) << section                 << " "
                 << DUMP_STR_FORMAT(  1 ) << name                    << " "
                 << std::endl;
         }
         else {                           // Output for 64-bit
             out << "["
                 << DUMP_DEC_FORMAT(  5 ) << no
                 << "] "
                 << DUMP_HEX_FORMAT( 16 ) << value                   << " "
                 << DUMP_HEX_FORMAT( 16 ) << size                    << " "
                 << DUMP_STR_FORMAT(  7 ) << str_symbol_type( type ) << " "
                 << DUMP_STR_FORMAT(  8 ) << str_symbol_bind( bind ) << " "
                 << DUMP_DEC_FORMAT(  5 ) << section                 << " "
                 << std::endl
                 << "        "
                 << DUMP_STR_FORMAT(  1 ) << name                    << " "
                 << std::endl;
         }
         out.flags(original_flags);
     }
static void ELFIO::dump::symbol_tables (std::ostream & out, const elfio & reader) inline static
Definition at line 587 of file elfio_dump.hpp.
References ELFCLASS32, ELFIO::symbol_section_accessor::get_symbol(), ELFIO::symbol_section_accessor::get_symbols_num(), ELFIO::elfio::sections, SHT_DYNSYM, SHT_SYMTAB, ELFIO::elfio::Sections::size(), and symbol_table().
     {
         Elf_Half n = reader.sections.size();
         for ( Elf_Half i = 0; i < n; ++i ) {    // For all sections
             section* sec = reader.sections[i];
             if ( SHT_SYMTAB == sec->get_type() || SHT_DYNSYM == sec->get_type() ) {
                 symbol_section_accessor symbols( reader, sec );
                 Elf_Xword     sym_no = symbols.get_symbols_num();
                 if ( sym_no > 0 ) {
                     out << "Symbol table (" << sec->get_name() << ")" << std::endl;
                     if ( reader.get_class() == ELFCLASS32 ) { // Output for 32-bit
                         out << "[  Nr ] Value    Size     Type    Bind      Sect Name"
                             << std::endl;
                     }
                     else {                                    // Output for 64-bit
                         out << "[  Nr ] Value            Size             Type    Bind      Sect" << std::endl
                             << "        Name"
                             << std::endl;
                     }
                     for ( Elf_Half i = 0; i < sym_no; ++i ) {
                         std::string   name;
                         Elf64_Addr    value   = 0;
                         Elf_Xword     size    = 0;
                         unsigned char bind    = 0;
                         unsigned char type    = 0;
                         Elf_Half      section = 0;
                         unsigned char other   = 0;
                         symbols.get_symbol( i, name, value, size, bind, type, section, other );
                         symbol_table( out, i, name, value, size, bind, type, section, reader.get_class() );
                     }
                     out << std::endl;
                 }
             }
         }
     }
The documentation for this class was generated from the following file:
elfio_dump.hpp