Voxel: TinyXML2::XMLElement Class Reference
TinyXML2::XMLElement Class Reference
Common and Utility classes
#include <TinyXML2.h>
Public Types
enum { OPEN, CLOSED, CLOSING }
Public Member Functions
const char * Name () const
Get the name of an element (which is the Value() of the node.)
void SetName (const char *str, bool staticMem=false)
Set the name of the element.
virtual XMLElement * ToElement ()
Safely cast to an Element, or null.
virtual const XMLElement * ToElement () const
virtual bool Accept (XMLVisitor *visitor) const
const char * Attribute (const char *name, const char *value=0) const
int IntAttribute (const char *name) const
unsigned UnsignedAttribute (const char *name) const
See IntAttribute()
bool BoolAttribute (const char *name) const
See IntAttribute()
double DoubleAttribute (const char *name) const
See IntAttribute()
float FloatAttribute (const char *name) const
See IntAttribute()
XMLError QueryIntAttribute (const char *name, int *value) const
XMLError QueryUnsignedAttribute (const char *name, unsigned int *value) const
See QueryIntAttribute()
XMLError QueryBoolAttribute (const char *name, bool *value) const
See QueryIntAttribute()
XMLError QueryDoubleAttribute (const char *name, double *value) const
See QueryIntAttribute()
XMLError QueryFloatAttribute (const char *name, float *value) const
See QueryIntAttribute()
int QueryAttribute (const char *name, int *value) const
int QueryAttribute (const char *name, unsigned int *value) const
int QueryAttribute (const char *name, bool *value) const
int QueryAttribute (const char *name, double *value) const
int QueryAttribute (const char *name, float *value) const
void SetAttribute (const char *name, const char *value)
Sets the named attribute to value.
void SetAttribute (const char *name, int value)
Sets the named attribute to value.
void SetAttribute (const char *name, unsigned value)
Sets the named attribute to value.
void SetAttribute (const char *name, bool value)
Sets the named attribute to value.
void SetAttribute (const char *name, double value)
Sets the named attribute to value.
void SetAttribute (const char *name, float value)
Sets the named attribute to value.
void DeleteAttribute (const char *name)
const XMLAttribute * FirstAttribute () const
Return the first attribute in the list.
const XMLAttribute * FindAttribute (const char *name) const
Query a specific attribute in the list.
const char * GetText () const
void SetText (const char *inText)
void SetText (int value)
Convenience method for setting text inside and element. See SetText() for important limitations.
void SetText (unsigned value)
Convenience method for setting text inside and element. See SetText() for important limitations.
void SetText (bool value)
Convenience method for setting text inside and element. See SetText() for important limitations.
void SetText (double value)
Convenience method for setting text inside and element. See SetText() for important limitations.
void SetText (float value)
Convenience method for setting text inside and element. See SetText() for important limitations.
XMLError QueryIntText (int *ival) const
XMLError QueryUnsignedText (unsigned *uval) const
See QueryIntText()
XMLError QueryBoolText (bool *bval) const
See QueryIntText()
XMLError QueryDoubleText (double *dval) const
See QueryIntText()
XMLError QueryFloatText (float *fval) const
See QueryIntText()
int ClosingType () const
char * ParseDeep (char *p, StrPair *endTag)
virtual XMLNode * ShallowClone (XMLDocument *document) const
virtual bool ShallowEqual (const XMLNode *compare) const
Public Member Functions inherited from TinyXML2::XMLNode
const XMLDocument * GetDocument () const
Get the XMLDocument that owns this XMLNode.
XMLDocument * GetDocument ()
Get the XMLDocument that owns this XMLNode.
virtual XMLText * ToText ()
Safely cast to Text, or null.
virtual XMLComment * ToComment ()
Safely cast to a Comment, or null.
virtual XMLDocument * ToDocument ()
Safely cast to a Document, or null.
virtual XMLDeclaration * ToDeclaration ()
Safely cast to a Declaration, or null.
virtual XMLUnknown * ToUnknown ()
Safely cast to an Unknown, or null.
virtual const XMLText * ToText () const
virtual const XMLComment * ToComment () const
virtual const XMLDocument * ToDocument () const
virtual const XMLDeclaration * ToDeclaration () const
virtual const XMLUnknown * ToUnknown () const
const char * Value () const
void SetValue (const char *val, bool staticMem=false)
const XMLNode * Parent () const
Get the parent of this node on the DOM.
XMLNode * Parent ()
bool NoChildren () const
Returns true if this node has no children.
const XMLNode * FirstChild () const
Get the first child node, or null if none exists.
XMLNode * FirstChild ()
const XMLElement * FirstChildElement (const char *value=0) const
XMLElement * FirstChildElement (const char *value=0)
const XMLNode * LastChild () const
Get the last child node, or null if none exists.
XMLNode * LastChild ()
const XMLElement * LastChildElement (const char *value=0) const
XMLElement * LastChildElement (const char *value=0)
const XMLNode * PreviousSibling () const
Get the previous (left) sibling node of this node.
XMLNode * PreviousSibling ()
const XMLElement * PreviousSiblingElement (const char *value=0) const
Get the previous (left) sibling element of this node, with an optionally supplied name.
XMLElement * PreviousSiblingElement (const char *value=0)
const XMLNode * NextSibling () const
Get the next (right) sibling node of this node.
XMLNode * NextSibling ()
const XMLElement * NextSiblingElement (const char *value=0) const
Get the next (right) sibling element of this node, with an optionally supplied name.
XMLElement * NextSiblingElement (const char *value=0)
XMLNode * InsertEndChild (XMLNode *addThis)
XMLNode * LinkEndChild (XMLNode *addThis)
XMLNode * InsertFirstChild (XMLNode *addThis)
XMLNode * InsertAfterChild (XMLNode *afterThis, XMLNode *addThis)
void DeleteChildren ()
void DeleteChild (XMLNode *node)
Private Types
enum { BUF_SIZE = 200 }
Private Member Functions
XMLElement (XMLDocument *doc)
virtual ~XMLElement ()
XMLElement (const XMLElement &)
void operator= (const XMLElement &)
XMLAttribute * FindAttribute (const char *name)
XMLAttribute * FindOrCreateAttribute (const char *name)
char * ParseAttributes (char *p)
Static Private Member Functions
static void DeleteAttribute (XMLAttribute *attribute)
Private Attributes
int _closingType
XMLAttribute * _rootAttribute
Friends
class XMLBase
class XMLDocument
Additional Inherited Members
Protected Member Functions inherited from TinyXML2::XMLNode
XMLNode (XMLDocument *)
virtual ~XMLNode ()
XMLNode (const XMLNode &)
XMLNode & operator= (const XMLNode &)
Protected Attributes inherited from TinyXML2::XMLNode
XMLDocument * _document
XMLNode * _parent
StrPair _value
XMLNode * _firstChild
XMLNode * _lastChild
XMLNode * _prev
XMLNode * _next
Detailed Description
The element is a container class. It has a value, the element name, and can contain other elements, text, comments, and unknowns. Elements also contain an arbitrary number of attributes.
Definition at line 1164 of file TinyXML2.h.
Member Enumeration Documentation
anonymous enum
Enumerator
OPEN
CLOSED
CLOSING
Definition at line 1493 of file TinyXML2.h.
          {
         OPEN,   // <foo>
         CLOSED,   // <foo/>
         CLOSING   // </foo>
     };
anonymous enum private
Enumerator
BUF_SIZE
Definition at line 1519 of file TinyXML2.h.
 { BUF_SIZE = 200 };
Constructor & Destructor Documentation
TinyXML2::XMLElement::XMLElement (XMLDocument * doc) private
Definition at line 1252 of file TinyXML2.cpp.
                                          : XMLNode( doc ),
     _closingType( 0 ),
     _rootAttribute( 0 )
 {
 }
TinyXML2::XMLElement::~XMLElement () private virtual
Definition at line 1259 of file TinyXML2.cpp.
References TinyXML2::XMLAttribute::_next, _rootAttribute, and DeleteAttribute().
 {
     while( _rootAttribute ) {
         XMLAttribute* next = _rootAttribute->_next;
         DeleteAttribute( _rootAttribute );
         _rootAttribute = next;
     }
 }
TinyXML2::XMLElement::XMLElement (const XMLElement &) private
Member Function Documentation
bool TinyXML2::XMLElement::Accept (XMLVisitor * visitor) const virtual
Accept a hierarchical visit of the nodes in the TinyXML-2 DOM. Every node in the XML tree will be conditionally visited and the host will be called back via the XMLVisitor interface.
This is essentially a SAX interface for TinyXML-2. (Note however it doesn't re-parse the XML for the callbacks, so the performance of TinyXML-2 is unchanged by using this interface versus any other.)
The interface has been based on ideas from:
http://www.saxproject.org/
http://c2.com/cgi/wiki?HierarchicalVisitorPattern
Which are both good references for "visiting".
An example of using Accept():
XMLPrinter printer;
tinyxmlDoc.Accept(&printer);
const char* xmlcstr = printer.CStr();
Implements TinyXML2::XMLNode.
Definition at line 1606 of file TinyXML2.cpp.
References _rootAttribute, TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLNode::NextSibling(), TIXMLASSERT, TinyXML2::XMLVisitor::VisitEnter(), and TinyXML2::XMLVisitor::VisitExit().
 {
     TIXMLASSERT( visitor );
     if ( visitor->VisitEnter( *this, _rootAttribute ) ) {
         for ( const XMLNode* node=FirstChild(); node; node=node->NextSibling() ) {
             if ( !node->Accept( visitor ) ) {
                 break;
             }
         }
     }
     return visitor->VisitExit( *this );
 }
const char * TinyXML2::XMLElement::Attribute (const char * name, const char * value = 0) const
Given an attribute name, Attribute() returns the value for the attribute of that name, or null if none exists. For example:
const char* value = ele->Attribute("foo");
The 'value' parameter is normally null. However, if specified, the attribute will only be returned if the 'name' and 'value' match. This allow you to write code:
if (ele->Attribute("foo", "bar")) callFooIsBar();
rather than:
if (ele->Attribute("foo")) {
  if ( strcmp( ele->Attribute( "foo" ), "bar" ) == 0 ) callFooIsBar();
}
Definition at line 1280 of file TinyXML2.cpp.
References FindAttribute(), TinyXML2::XMLUtil::StringEqual(), and TinyXML2::XMLAttribute::Value().
Referenced by Voxel::ParameterDMLParser::_getParameter(), Voxel::ParameterDMLParser::_prepare(), Voxel::ParameterDMLParser::getParameters(), and ParseAttributes().
 {
     const XMLAttribute* a = FindAttribute( name );
     if ( !a ) {
         return 0;
     }
     if ( !value || XMLUtil::StringEqual( a->Value(), value )) {
         return a->Value();
     }
     return 0;
 }
bool TinyXML2::XMLElement::BoolAttribute (const char * name) const inline
See IntAttribute()
Definition at line 1228 of file TinyXML2.h.
{
         bool b=false;
         QueryBoolAttribute( name, &b );
         return b;
     }
int TinyXML2::XMLElement::ClosingType () const inline
Definition at line 1498 of file TinyXML2.h.
Referenced by TinyXML2::XMLNode::ParseDeep().
{
         return _closingType;
     }
void TinyXML2::XMLElement::DeleteAttribute (const char * name)
Delete an attribute.
Definition at line 1446 of file TinyXML2.cpp.
References TinyXML2::XMLAttribute::_next, _rootAttribute, and TinyXML2::XMLUtil::StringEqual().
Referenced by ParseAttributes(), and ~XMLElement().
 {
     XMLAttribute* prev = 0;
     for( XMLAttribute* a=_rootAttribute; a; a=a->_next ) {
         if ( XMLUtil::StringEqual( name, a->Name() ) ) {
             if ( prev ) {
                 prev->_next = a->_next;
             }
             else {
                 _rootAttribute = a->_next;
             }
             DeleteAttribute( a );
             break;
         }
         prev = a;
     }
 }
void TinyXML2::XMLElement::DeleteAttribute (XMLAttribute * attribute) static private
Definition at line 1521 of file TinyXML2.cpp.
References TinyXML2::XMLAttribute::_memPool, TinyXML2::MemPool::Free(), and TinyXML2::XMLAttribute::~XMLAttribute().
 {
     if ( attribute == 0 ) {
         return;
     }
     MemPool* pool = attribute->_memPool;
     attribute->~XMLAttribute();
     pool->Free( attribute );
 }
double TinyXML2::XMLElement::DoubleAttribute (const char * name) const inline
See IntAttribute()
Definition at line 1234 of file TinyXML2.h.
{
         double d=0;
         QueryDoubleAttribute( name, &d );
         return d;
     }
const XMLAttribute * TinyXML2::XMLElement::FindAttribute (const char * name) const
Query a specific attribute in the list.
Definition at line 1269 of file TinyXML2.cpp.
References TinyXML2::XMLAttribute::_next, _rootAttribute, and TinyXML2::XMLUtil::StringEqual().
Referenced by Attribute().
 {
     for( XMLAttribute* a = _rootAttribute; a; a = a->_next ) {
         if ( XMLUtil::StringEqual( a->Name(), name ) ) {
             return a;
         }
     }
     return 0;
 }
XMLAttribute* TinyXML2::XMLElement::FindAttribute (const char * name) inline private
Definition at line 1511 of file TinyXML2.h.
{
         return const_cast<XMLAttribute*>(const_cast<const XMLElement*>(this)->FindAttribute( name ));
     }
XMLAttribute * TinyXML2::XMLElement::FindOrCreateAttribute (const char * name) private
Definition at line 1419 of file TinyXML2.cpp.
References TinyXML2::XMLDocument::_attributePool, TinyXML2::XMLNode::_document, TinyXML2::XMLAttribute::_memPool, TinyXML2::XMLAttribute::_next, _rootAttribute, TinyXML2::XMLAttribute::SetName(), and TinyXML2::XMLUtil::StringEqual().
 {
     XMLAttribute* last = 0;
     XMLAttribute* attrib = 0;
     for( attrib = _rootAttribute;
             attrib;
             last = attrib, attrib = attrib->_next ) {
         if ( XMLUtil::StringEqual( attrib->Name(), name ) ) {
             break;
         }
     }
     if ( !attrib ) {
         attrib = new (_document->_attributePool.Alloc() ) XMLAttribute();
         attrib->_memPool = &_document->_attributePool;
         if ( last ) {
             last->_next = attrib;
         }
         else {
             _rootAttribute = attrib;
         }
         attrib->SetName( name );
         attrib->_memPool->SetTracked(); // always created and linked.
     }
     return attrib;
 }
const XMLAttribute* TinyXML2::XMLElement::FirstAttribute () const inline
Return the first attribute in the list.
Definition at line 1374 of file TinyXML2.h.
Referenced by ShallowClone(), and ShallowEqual().
{
         return _rootAttribute;
     }
float TinyXML2::XMLElement::FloatAttribute (const char * name) const inline
See IntAttribute()
Definition at line 1240 of file TinyXML2.h.
{
         float f=0;
         QueryFloatAttribute( name, &f );
         return f;
     }
const char * TinyXML2::XMLElement::GetText () const
Convenience function for easy access to the text inside an element. Although easy and concise, GetText() is limited compared to getting the XMLText child and accessing it directly.
If the first child of 'this' is a XMLText, the GetText() returns the character string of the Text node, else null is returned.
This is a convenient method for getting the text of simple contained text:
<foo>This is text</foo>
  const char* str = fooElement->GetText();
'str' will be a pointer to "This is text".
Note that this function can be misleading. If the element foo was created from this XML:
  <foo><b>This is text</b></foo>
then the value of str would be null. The first child node isn't a text node, it is another element. From this XML:
  <foo>This is <b>text</b></foo>
GetText() will return "This is ".
Definition at line 1293 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLNode::ToText(), and TinyXML2::XMLNode::Value().
 {
     if ( FirstChild() && FirstChild()->ToText() ) {
         return FirstChild()->Value();
     }
     return 0;
 }
int TinyXML2::XMLElement::IntAttribute (const char * name) const inline
Given an attribute name, IntAttribute() returns the value of the attribute interpreted as an integer. 0 will be returned if there is an error. For a method with error checking, see QueryIntAttribute()
Definition at line 1216 of file TinyXML2.h.
Referenced by Voxel::ParameterDMLParser::_getParameter(), and Voxel::ParameterDMLParser::_prepare().
{
         int i=0;
         QueryIntAttribute( name, &i );
         return i;
     }
const char* TinyXML2::XMLElement::Name () const inline
Get the name of an element (which is the Value() of the node.)
Definition at line 1170 of file TinyXML2.h.
Referenced by TinyXML2::XMLNode::FirstChildElement(), TinyXML2::XMLNode::LastChildElement(), ParseAttributes(), and TinyXML2::XMLPrinter::VisitEnter().
{
         return Value();
     }
void TinyXML2::XMLElement::operator= (const XMLElement &) private
char * TinyXML2::XMLElement::ParseAttributes (char * p) private
Definition at line 1465 of file TinyXML2.cpp.
References TinyXML2::XMLDocument::_attributePool, _closingType, TinyXML2::XMLNode::_document, TinyXML2::XMLAttribute::_memPool, TinyXML2::XMLAttribute::_next, _rootAttribute, Attribute(), CLOSED, DeleteAttribute(), TinyXML2::XMLUtil::IsNameStartChar(), TinyXML2::XMLAttribute::Name(), Name(), TinyXML2::XMLAttribute::ParseDeep(), TinyXML2::XMLDocument::ProcessEntities(), TinyXML2::XMLDocument::SetError(), TinyXML2::MemPool::SetTracked(), TinyXML2::XMLUtil::SkipWhiteSpace(), TinyXML2::XML_ERROR_PARSING_ATTRIBUTE, and TinyXML2::XML_ERROR_PARSING_ELEMENT.
Referenced by ParseDeep().
 {
     const char* start = p;
     XMLAttribute* prevAttribute = 0;
     // Read the attributes.
     while( p ) {
         p = XMLUtil::SkipWhiteSpace( p );
         if ( !p || !(*p) ) {
             _document->SetError( XML_ERROR_PARSING_ELEMENT, start, Name() );
             return 0;
         }
         // attribute.
         if (XMLUtil::IsNameStartChar( *p ) ) {
             XMLAttribute* attrib = new (_document->_attributePool.Alloc() ) XMLAttribute();
             attrib->_memPool = &_document->_attributePool;
       attrib->_memPool->SetTracked();
             p = attrib->ParseDeep( p, _document->ProcessEntities() );
             if ( !p || Attribute( attrib->Name() ) ) {
                 DeleteAttribute( attrib );
                 _document->SetError( XML_ERROR_PARSING_ATTRIBUTE, start, p );
                 return 0;
             }
             // There is a minor bug here: if the attribute in the source xml
             // document is duplicated, it will not be detected and the
             // attribute will be doubly added. However, tracking the 'prevAttribute'
             // avoids re-scanning the attribute list. Preferring performance for
             // now, may reconsider in the future.
             if ( prevAttribute ) {
                 prevAttribute->_next = attrib;
             }
             else {
                 _rootAttribute = attrib;
             }
             prevAttribute = attrib;
         }
         // end of the tag
         else if ( *p == '/' && *(p+1) == '>' ) {
             _closingType = CLOSED;
             return p+2; // done; sealed element.
         }
         // end of the tag
         else if ( *p == '>' ) {
             ++p;
             break;
         }
         else {
             _document->SetError( XML_ERROR_PARSING_ELEMENT, start, p );
             return 0;
         }
     }
     return p;
 }
char * TinyXML2::XMLElement::ParseDeep (char * p, StrPair * endTag) virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 1535 of file TinyXML2.cpp.
References _closingType, TinyXML2::XMLNode::_value, CLOSING, TinyXML2::StrPair::Empty(), ParseAttributes(), TinyXML2::XMLNode::ParseDeep(), TinyXML2::StrPair::ParseName(), and TinyXML2::XMLUtil::SkipWhiteSpace().
 {
     // Read the element name.
     p = XMLUtil::SkipWhiteSpace( p );
     if ( !p ) {
         return 0;
     }
     // The closing element is the </element> form. It is
     // parsed just like a regular element then deleted from
     // the DOM.
     if ( *p == '/' ) {
         _closingType = CLOSING;
         ++p;
     }
     p = _value.ParseName( p );
     if ( _value.Empty() ) {
         return 0;
     }
     p = ParseAttributes( p );
     if ( !p || !*p || _closingType ) {
         return p;
     }
     p = XMLNode::ParseDeep( p, strPair );
     return p;
 }
int TinyXML2::XMLElement::QueryAttribute (const char * name, int * value) const inline
Given an attribute name, QueryAttribute() returns XML_NO_ERROR, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. It is overloaded for the primitive types, and is a generally more convenient replacement of QueryIntAttribute() and related functions.
If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
  int value = 10;
  QueryAttribute( "foo", &value );    // if "foo" isn't found, value will still be 10
Definition at line 1317 of file TinyXML2.h.
{
     return QueryIntAttribute( name, value );
   }
int TinyXML2::XMLElement::QueryAttribute (const char * name, unsigned int * value) const inline
Definition at line 1321 of file TinyXML2.h.
{
     return QueryUnsignedAttribute( name, value );
   }
int TinyXML2::XMLElement::QueryAttribute (const char * name, bool * value) const inline
Definition at line 1325 of file TinyXML2.h.
{
     return QueryBoolAttribute( name, value );
   }
int TinyXML2::XMLElement::QueryAttribute (const char * name, double * value) const inline
Definition at line 1329 of file TinyXML2.h.
{
     return QueryDoubleAttribute( name, value );
   }
int TinyXML2::XMLElement::QueryAttribute (const char * name, float * value) const inline
Definition at line 1333 of file TinyXML2.h.
{
     return QueryFloatAttribute( name, value );
   }
XMLError TinyXML2::XMLElement::QueryBoolAttribute (const char * name, bool * value) const inline
See QueryIntAttribute()
Definition at line 1275 of file TinyXML2.h.
References TinyXML2::XMLAttribute::QueryBoolValue(), and TinyXML2::XML_NO_ATTRIBUTE.
{
         const XMLAttribute* a = FindAttribute( name );
         if ( !a ) {
             return XML_NO_ATTRIBUTE;
         }
         return a->QueryBoolValue( value );
     }
XMLError TinyXML2::XMLElement::QueryBoolText (bool * bval) const
See QueryIntText()
Definition at line 1379 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLUtil::ToBool(), TinyXML2::XMLNode::ToText(), TinyXML2::XMLNode::Value(), TinyXML2::XML_CAN_NOT_CONVERT_TEXT, TinyXML2::XML_NO_TEXT_NODE, and TinyXML2::XML_SUCCESS.
 {
     if ( FirstChild() && FirstChild()->ToText() ) {
         const char* t = FirstChild()->Value();
         if ( XMLUtil::ToBool( t, bval ) ) {
             return XML_SUCCESS;
         }
         return XML_CAN_NOT_CONVERT_TEXT;
     }
     return XML_NO_TEXT_NODE;
 }
XMLError TinyXML2::XMLElement::QueryDoubleAttribute (const char * name, double * value) const inline
See QueryIntAttribute()
Definition at line 1283 of file TinyXML2.h.
References TinyXML2::XMLAttribute::QueryDoubleValue(), and TinyXML2::XML_NO_ATTRIBUTE.
{
         const XMLAttribute* a = FindAttribute( name );
         if ( !a ) {
             return XML_NO_ATTRIBUTE;
         }
         return a->QueryDoubleValue( value );
     }
XMLError TinyXML2::XMLElement::QueryDoubleText (double * dval) const
See QueryIntText()
Definition at line 1392 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLUtil::ToDouble(), TinyXML2::XMLNode::ToText(), TinyXML2::XMLNode::Value(), TinyXML2::XML_CAN_NOT_CONVERT_TEXT, TinyXML2::XML_NO_TEXT_NODE, and TinyXML2::XML_SUCCESS.
 {
     if ( FirstChild() && FirstChild()->ToText() ) {
         const char* t = FirstChild()->Value();
         if ( XMLUtil::ToDouble( t, dval ) ) {
             return XML_SUCCESS;
         }
         return XML_CAN_NOT_CONVERT_TEXT;
     }
     return XML_NO_TEXT_NODE;
 }
XMLError TinyXML2::XMLElement::QueryFloatAttribute (const char * name, float * value) const inline
See QueryIntAttribute()
Definition at line 1291 of file TinyXML2.h.
References TinyXML2::XMLAttribute::QueryFloatValue(), and TinyXML2::XML_NO_ATTRIBUTE.
{
         const XMLAttribute* a = FindAttribute( name );
         if ( !a ) {
             return XML_NO_ATTRIBUTE;
         }
         return a->QueryFloatValue( value );
     }
XMLError TinyXML2::XMLElement::QueryFloatText (float * fval) const
See QueryIntText()
Definition at line 1405 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLUtil::ToFloat(), TinyXML2::XMLNode::ToText(), TinyXML2::XMLNode::Value(), TinyXML2::XML_CAN_NOT_CONVERT_TEXT, TinyXML2::XML_NO_TEXT_NODE, and TinyXML2::XML_SUCCESS.
 {
     if ( FirstChild() && FirstChild()->ToText() ) {
         const char* t = FirstChild()->Value();
         if ( XMLUtil::ToFloat( t, fval ) ) {
             return XML_SUCCESS;
         }
         return XML_CAN_NOT_CONVERT_TEXT;
     }
     return XML_NO_TEXT_NODE;
 }
XMLError TinyXML2::XMLElement::QueryIntAttribute (const char * name, int * value) const inline
Given an attribute name, QueryIntAttribute() returns XML_NO_ERROR, XML_WRONG_ATTRIBUTE_TYPE if the conversion can't be performed, or XML_NO_ATTRIBUTE if the attribute doesn't exist. If successful, the result of the conversion will be written to 'value'. If not successful, nothing will be written to 'value'. This allows you to provide default value:
int value = 10;
QueryIntAttribute("foo", &value);   // if "foo" isn't found, value will still be 10
Definition at line 1259 of file TinyXML2.h.
References TinyXML2::XMLAttribute::QueryIntValue(), and TinyXML2::XML_NO_ATTRIBUTE.
{
         const XMLAttribute* a = FindAttribute( name );
         if ( !a ) {
             return XML_NO_ATTRIBUTE;
         }
         return a->QueryIntValue( value );
     }
XMLError TinyXML2::XMLElement::QueryIntText (int * ival) const
Convenience method to query the value of a child text node. This is probably best shown by example. Given you have a document is this form:
  <point>
    <x>1</x>
    <y>1.4</y>
  </point>
The QueryIntText() and similar functions provide a safe and easier way to get to the "value" of x and y.
  int x = 0;
  float y = 0;  // types of x and y are contrived for example
  const XMLElement* xElement = pointElement->FirstChildElement( "x" );
  const XMLElement* yElement = pointElement->FirstChildElement( "y" );
  xElement->QueryIntText( &x );
  yElement->QueryFloatText( &y );
Returns
XML_SUCCESS (0) on success, XML_CAN_NOT_CONVERT_TEXT if the text cannot be converted to the requested type, and XML_NO_TEXT_NODE if there is no child text to query.
Definition at line 1353 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLUtil::ToInt(), TinyXML2::XMLNode::ToText(), TinyXML2::XMLNode::Value(), TinyXML2::XML_CAN_NOT_CONVERT_TEXT, TinyXML2::XML_NO_TEXT_NODE, and TinyXML2::XML_SUCCESS.
 {
     if ( FirstChild() && FirstChild()->ToText() ) {
         const char* t = FirstChild()->Value();
         if ( XMLUtil::ToInt( t, ival ) ) {
             return XML_SUCCESS;
         }
         return XML_CAN_NOT_CONVERT_TEXT;
     }
     return XML_NO_TEXT_NODE;
 }
XMLError TinyXML2::XMLElement::QueryUnsignedAttribute (const char * name, unsigned int * value) const inline
See QueryIntAttribute()
Definition at line 1267 of file TinyXML2.h.
References TinyXML2::XMLAttribute::QueryUnsignedValue(), and TinyXML2::XML_NO_ATTRIBUTE.
{
         const XMLAttribute* a = FindAttribute( name );
         if ( !a ) {
             return XML_NO_ATTRIBUTE;
         }
         return a->QueryUnsignedValue( value );
     }
XMLError TinyXML2::XMLElement::QueryUnsignedText (unsigned * uval) const
See QueryIntText()
Definition at line 1366 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLNode::ToText(), TinyXML2::XMLUtil::ToUnsigned(), TinyXML2::XMLNode::Value(), TinyXML2::XML_CAN_NOT_CONVERT_TEXT, TinyXML2::XML_NO_TEXT_NODE, and TinyXML2::XML_SUCCESS.
 {
     if ( FirstChild() && FirstChild()->ToText() ) {
         const char* t = FirstChild()->Value();
         if ( XMLUtil::ToUnsigned( t, uval ) ) {
             return XML_SUCCESS;
         }
         return XML_CAN_NOT_CONVERT_TEXT;
     }
     return XML_NO_TEXT_NODE;
 }
void TinyXML2::XMLElement::SetAttribute (const char * name, const char * value) inline
Sets the named attribute to value.
Definition at line 1338 of file TinyXML2.h.
References TinyXML2::XMLAttribute::SetAttribute().
Referenced by ShallowClone().
{
         XMLAttribute* a = FindOrCreateAttribute( name );
         a->SetAttribute( value );
     }
void TinyXML2::XMLElement::SetAttribute (const char * name, int value) inline
Sets the named attribute to value.
Definition at line 1343 of file TinyXML2.h.
References TinyXML2::XMLAttribute::SetAttribute().
{
         XMLAttribute* a = FindOrCreateAttribute( name );
         a->SetAttribute( value );
     }
void TinyXML2::XMLElement::SetAttribute (const char * name, unsigned value) inline
Sets the named attribute to value.
Definition at line 1348 of file TinyXML2.h.
References TinyXML2::XMLAttribute::SetAttribute().
{
         XMLAttribute* a = FindOrCreateAttribute( name );
         a->SetAttribute( value );
     }
void TinyXML2::XMLElement::SetAttribute (const char * name, bool value) inline
Sets the named attribute to value.
Definition at line 1353 of file TinyXML2.h.
References TinyXML2::XMLAttribute::SetAttribute().
{
         XMLAttribute* a = FindOrCreateAttribute( name );
         a->SetAttribute( value );
     }
void TinyXML2::XMLElement::SetAttribute (const char * name, double value) inline
Sets the named attribute to value.
Definition at line 1358 of file TinyXML2.h.
References TinyXML2::XMLAttribute::SetAttribute().
{
         XMLAttribute* a = FindOrCreateAttribute( name );
         a->SetAttribute( value );
     }
void TinyXML2::XMLElement::SetAttribute (const char * name, float value) inline
Sets the named attribute to value.
Definition at line 1363 of file TinyXML2.h.
References TinyXML2::XMLAttribute::SetAttribute().
{
         XMLAttribute* a = FindOrCreateAttribute( name );
         a->SetAttribute( value );
     }
void TinyXML2::XMLElement::SetName (const char * str, bool staticMem = false) inline
Set the name of the element.
Definition at line 1174 of file TinyXML2.h.
Referenced by TinyXML2::XMLDocument::NewElement().
{
         SetValue( str, staticMem );
     }
void TinyXML2::XMLElement::SetText (const char * inText)
Convenience function for easy access to the text inside an element. Although easy and concise, SetText() is limited compared to creating an XMLText child and mutating it directly.
If the first child of 'this' is a XMLText, SetText() sets its value to the given string, otherwise it will create a first child that is an XMLText.
This is a convenient method for setting the text of simple contained text:
  <foo>This is text</foo>
    fooElement->SetText( "Hullaballoo!" );
  <foo>Hullaballoo!</foo>
Note that this function can be misleading. If the element foo was created from this XML:
    <foo><b>This is text</b></foo>
then it will not change "This is text", but rather prefix it with a text element:
    <foo>Hullaballoo!<b>This is text</b></foo>
For this XML:
    <foo />
SetText() will generate
    <foo>Hullaballoo!</foo>
Definition at line 1302 of file TinyXML2.cpp.
References TinyXML2::XMLNode::FirstChild(), TinyXML2::XMLNode::GetDocument(), TinyXML2::XMLNode::InsertFirstChild(), TinyXML2::XMLDocument::NewText(), TinyXML2::XMLNode::SetValue(), and TinyXML2::XMLNode::ToText().
Referenced by SetText().
 {
   if ( FirstChild() && FirstChild()->ToText() )
     FirstChild()->SetValue( inText );
   else {
     XMLText*  theText = GetDocument()->NewText( inText );
     InsertFirstChild( theText );
   }
 }
void TinyXML2::XMLElement::SetText (int value)
Convenience method for setting text inside and element. See SetText() for important limitations.
Definition at line 1313 of file TinyXML2.cpp.
References BUF_SIZE, SetText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     SetText( buf );
 }
void TinyXML2::XMLElement::SetText (unsigned value)
Convenience method for setting text inside and element. See SetText() for important limitations.
Definition at line 1321 of file TinyXML2.cpp.
References BUF_SIZE, SetText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     SetText( buf );
 }
void TinyXML2::XMLElement::SetText (bool value)
Convenience method for setting text inside and element. See SetText() for important limitations.
Definition at line 1329 of file TinyXML2.cpp.
References BUF_SIZE, SetText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     SetText( buf );
 }
void TinyXML2::XMLElement::SetText (double value)
Convenience method for setting text inside and element. See SetText() for important limitations.
Definition at line 1345 of file TinyXML2.cpp.
References BUF_SIZE, SetText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     SetText( buf );
 }
void TinyXML2::XMLElement::SetText (float value)
Convenience method for setting text inside and element. See SetText() for important limitations.
Definition at line 1337 of file TinyXML2.cpp.
References BUF_SIZE, SetText(), and TinyXML2::XMLUtil::ToStr().
 {
     char buf[BUF_SIZE];
     XMLUtil::ToStr( v, buf, BUF_SIZE );
     SetText( buf );
 }
XMLNode * TinyXML2::XMLElement::ShallowClone (XMLDocument * document) const virtual
Make a copy of this node, but not its children. You may pass in a Document pointer that will be the owner of the new Node. If the 'document' is null, then the node returned will be allocated from the current Document. (this->GetDocument())
Note: if called on a XMLDocument, this will return null.
Implements TinyXML2::XMLNode.
Definition at line 1567 of file TinyXML2.cpp.
References TinyXML2::XMLNode::_document, FirstAttribute(), TinyXML2::XMLDocument::NewElement(), TinyXML2::XMLAttribute::Next(), SetAttribute(), and TinyXML2::XMLNode::Value().
 {
     if ( !doc ) {
         doc = _document;
     }
     XMLElement* element = doc->NewElement( Value() );         // fixme: this will always allocate memory. Intern?
     for( const XMLAttribute* a=FirstAttribute(); a; a=a->Next() ) {
         element->SetAttribute( a->Name(), a->Value() );         // fixme: this will always allocate memory. Intern?
     }
     return element;
 }
bool TinyXML2::XMLElement::ShallowEqual (const XMLNode * compare) const virtual
Test if 2 nodes are the same, but don't test children. The 2 nodes do not need to be in the same Document.
Note: if called on a XMLDocument, this will return false.
Implements TinyXML2::XMLNode.
Definition at line 1580 of file TinyXML2.cpp.
References FirstAttribute(), TinyXML2::XMLAttribute::Next(), TinyXML2::XMLUtil::StringEqual(), TIXMLASSERT, TinyXML2::XMLNode::ToElement(), TinyXML2::XMLNode::Value(), and TinyXML2::XMLAttribute::Value().
 {
     TIXMLASSERT( compare );
     const XMLElement* other = compare->ToElement();
     if ( other && XMLUtil::StringEqual( other->Value(), Value() )) {
         const XMLAttribute* a=FirstAttribute();
         const XMLAttribute* b=other->FirstAttribute();
         while ( a && b ) {
             if ( !XMLUtil::StringEqual( a->Value(), b->Value() ) ) {
                 return false;
             }
             a = a->Next();
             b = b->Next();
         }
         if ( a || b ) {
             // different count
             return false;
         }
         return true;
     }
     return false;
 }
virtual XMLElement* TinyXML2::XMLElement::ToElement () inline virtual
Safely cast to an Element, or null.
Reimplemented from TinyXML2::XMLNode.
Definition at line 1178 of file TinyXML2.h.
Referenced by TinyXML2::XMLNode::FirstChildElement(), TinyXML2::XMLNode::LastChildElement(), TinyXML2::XMLNode::NextSiblingElement(), and TinyXML2::XMLNode::PreviousSiblingElement().
{
         return this;
     }
virtual const XMLElement* TinyXML2::XMLElement::ToElement () const inline virtual
Reimplemented from TinyXML2::XMLNode.
Definition at line 1181 of file TinyXML2.h.
{
         return this;
     }
unsigned TinyXML2::XMLElement::UnsignedAttribute (const char * name) const inline
See IntAttribute()
Definition at line 1222 of file TinyXML2.h.
Referenced by Voxel::ParameterDMLParser::_getParameter().
{
         unsigned i=0;
         QueryUnsignedAttribute( name, &i );
         return i;
     }
Friends And Related Function Documentation
friend class XMLBase friend
Definition at line 1166 of file TinyXML2.h.
friend class XMLDocument friend
Definition at line 1167 of file TinyXML2.h.
Member Data Documentation
int TinyXML2::XMLElement::_closingType private
Definition at line 1520 of file TinyXML2.h.
Referenced by ParseAttributes(), and ParseDeep().
XMLAttribute* TinyXML2::XMLElement::_rootAttribute private
Definition at line 1524 of file TinyXML2.h.
Referenced by Accept(), DeleteAttribute(), FindAttribute(), FindOrCreateAttribute(), ParseAttributes(), and ~XMLElement().
The documentation for this class was generated from the following files:
TinyXML2.h
TinyXML2.cpp