Voxel: Voxel::MedianFilter Class Reference
Voxel::MedianFilter Class Reference
Filter related classes
#include <MedianFilter.h>
Public Member Functions
MedianFilter (float stability=0.1, float deadband=0.05, float deadbandStep=0.01, uint halfKernelSize=1)
virtual ~MedianFilter ()
virtual void reset ()
Public Member Functions inherited from Voxel::Filter
Filter (const String &name, const String &description="", const String &nameScope="")
void setDepthCamera (const DepthCameraPtr &d)
const Map< String,
FilterParameterPtr > & parameters ()
const String & name ()
const String & description ()
void setNameScope (const String &scope)
bool filter (const FramePtr &in, FramePtr &out)
FilterParameterConstPtr getParam (const String &name) const
template<typename T >
bool get (const String &name, T &value)
template<typename T >
bool set (const String &name, const T &value)
virtual ~Filter ()
Protected Member Functions
template<typename T >
bool _filter (const T *in, T *out)
virtual void _onSet (const FilterParameterPtr &f)
virtual bool _filter (const FramePtr &in, FramePtr &out)
Protected Member Functions inherited from Voxel::Filter
void _makeID ()
virtual bool _addParameters (const Vector< FilterParameterPtr > &params)
virtual bool _prepareOutput (const FramePtr &in, FramePtr &out)
template<typename T >
bool _get (const String &name, T &value)
template<typename T >
bool _set (const String &name, const T &value)
Protected Attributes
float _stability
float _deadband
float _deadbandStep
uint _halfKernelSize
Vector< ByteType > _current
Vector< ByteType > _hist
FrameSize _size
Protected Attributes inherited from Voxel::Filter
String _name
String _nameScope
String _description
String _id
Mutex _accessMutex
DepthCameraPtr _depthCamera
Map< String, FilterParameterPtr > _parameters
Detailed Description
Definition at line 21 of file MedianFilter.h.
Constructor & Destructor Documentation
Voxel::MedianFilter::MedianFilter (float stability = 0.1, float deadband = 0.05, float deadbandStep = 0.01, uint halfKernelSize = 1)
Definition at line 14 of file MedianFilter.cpp.
References Voxel::Filter::_addParameters().
                                                                                                   : Filter("MedianFilter"),
   _stability(stability), _deadband(deadband), _deadbandStep(deadbandStep), _halfKernelSize(halfKernelSize)
 {
   _addParameters({
     FilterParameterPtr(new FloatFilterParameter("stability", "Stability", "Stability factor", stability, "", 0, 1)),
     FilterParameterPtr(new FloatFilterParameter("deadband", "Dead band", "Dead band", deadband, "", 0, 1)),
     FilterParameterPtr(new FloatFilterParameter("deadbandStep", "Dead band step", "Dead band step", deadbandStep, "", 0, 1)),
     FilterParameterPtr(new UnsignedFilterParameter("halfKernelSize", "Half kernel size", "Half kernel size", halfKernelSize, "", 1, 100))
   });
 }
virtual Voxel::MedianFilter::~MedianFilter () inline virtual
Definition at line 40 of file MedianFilter.h.
 {}
Member Function Documentation
template<typename T > bool Voxel::MedianFilter::_filter (const T * in, T * out) protected
Definition at line 60 of file MedianFilter.cpp.
References _current, _deadband, _deadbandStep, _halfKernelSize, _hist, Voxel::Filter::_set(), _size, _stability, Voxel::FrameSize::height, and Voxel::FrameSize::width.
 {
   uint s = _size.width*_size.height;
   T *cur, *hist;
   if(_current.size() != s*sizeof(T))
   {
     _current.resize(s*sizeof(T));
     memset(_current.data(), 0, s*sizeof(T));
   }
   uint histSize = (2*_halfKernelSize + 1)*(2*_halfKernelSize + 1);
   if(_hist.size() != histSize*sizeof(T))
   {
     _hist.resize(histSize*sizeof(T));
     memset(_hist.data(), 0, histSize*sizeof(T));
   }
   cur = (T *)_current.data();
   hist = (T *)_hist.data();
   int stablePixel = _size.width*_size.height;
   int index;
   for (int j = 0; j < _size.height; j++)
   {
     for (int i = 0; i < _size.width; i++)
     {
       int p = j*_size.width + i;
       index = 0;
       for (int k = -(int)_halfKernelSize; k <= (int)_halfKernelSize; k++)
       {
         for (int m = -(int)_halfKernelSize; m <= (int)_halfKernelSize; m++)
         {
           int i2 = i+m; int j2 = j+k;
           if ((j2 >= 0 && j2 < _size.height) && (i2 >= 0 && i2 < _size.width))
           {
             int q = j2*_size.width+i2;
             hist[index++] = in[q];
           }
         }
       }
       std::nth_element(hist, hist + index/2, hist + index);
       T val = hist[index/2];
       // Output w/ deadband
       float ferr = cur[p]?fabs((float)(val- cur[p])/cur[p]):FLT_MAX;
       if (ferr > _deadband)
       {
         out[p] = cur[p] = val;
         stablePixel--;
       }
       else
         out[p] = cur[p];
     }  // for (i)
   } // for (j)
   // Adjust deadband until ratio is achieved
   float diff = (float)stablePixel - _stability*_size.width*_size.height;
   if (diff < 0)
     _deadband += _deadbandStep;
   else
     _deadband -= _deadbandStep;
   _set("deadband", _deadband);
   return true;
 }
bool Voxel::MedianFilter::_filter (const FramePtr & in, FramePtr & out) protected virtual
Implements Voxel::Filter.
Definition at line 135 of file MedianFilter.cpp.
References Voxel::Filter::_prepareOutput(), _size, Voxel::ToFRawFrame::ambient(), Voxel::ToFRawFrame::ambientWordWidth(), Voxel::DepthFrame::amplitude, Voxel::ToFRawFrame::amplitude(), Voxel::ToFRawFrame::amplitudeWordWidth(), Voxel::DepthFrame::depth, Voxel::ToFRawFrame::flags(), Voxel::ToFRawFrame::flagsWordWidth(), Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::ToFRawFrame::phase(), Voxel::ToFRawFrame::phaseWordWidth(), Voxel::DepthFrame::size, Voxel::ToFRawFrame::size, CameraSystemIQFrameTest::tofFrame, and Voxel::FrameSize::width.
 {
   ToFRawFrame *tofFrame = dynamic_cast<ToFRawFrame *>(in.get());
   DepthFrame *depthFrame = dynamic_cast<DepthFrame *>(in.get());
   if((!tofFrame && !depthFrame) || !_prepareOutput(in, out))
   {
     logger(LOG_ERROR) << "IIRFilter: Input frame type is not ToFRawFrame or DepthFrame or failed get the output ready" << std::endl;
     return false;
   }
   if(tofFrame)
   {
     _size = tofFrame->size;
     ToFRawFrame *o = dynamic_cast<ToFRawFrame *>(out.get());
     if(!o)
     {
       logger(LOG_ERROR) << "IIRFilter: Invalid frame type. Expecting ToFRawFrame." << std::endl;
       return false;
     }
     //logger(LOG_INFO) << "IIRFilter: Applying filter with gain = " << _gain << " to ToFRawFrame id = " << tofFrame->id << std::endl;
     uint s = _size.width*_size.height;
     memcpy(o->ambient(), tofFrame->ambient(), s*tofFrame->ambientWordWidth());
     memcpy(o->amplitude(), tofFrame->amplitude(), s*tofFrame->amplitudeWordWidth());
     memcpy(o->flags(), tofFrame->flags(), s*tofFrame->flagsWordWidth());
     if(tofFrame->phaseWordWidth() == 2)
       return _filter<uint16_t>((uint16_t *)tofFrame->phase(), (uint16_t *)o->phase());
     else if(tofFrame->phaseWordWidth() == 1)
       return _filter<uint8_t>((uint8_t *)tofFrame->phase(), (uint8_t *)o->phase());
     else if(tofFrame->phaseWordWidth() == 4)
       return _filter<uint32_t>((uint32_t *)tofFrame->phase(), (uint32_t *)o->phase());
     else
       return false;
   }
   else if(depthFrame)
   {
     _size = depthFrame->size;
     DepthFrame *o = dynamic_cast<DepthFrame *>(out.get());
     if(!o)
     {
       logger(LOG_ERROR) << "IIRFilter: Invalid frame type. Expecting DepthFrame." << std::endl;
       return false;
     }
     o->amplitude = depthFrame->amplitude;
     return _filter<float>(depthFrame->depth.data(), o->depth.data());
   }
   else
     return false;
 }
void Voxel::MedianFilter::_onSet (const FilterParameterPtr & f) protected virtual
Implements Voxel::Filter.
Definition at line 27 of file MedianFilter.cpp.
References _deadband, _deadbandStep, Voxel::Filter::_get(), _halfKernelSize, _stability, Voxel::LOG_WARNING, and Voxel::logger.
 {
   if(f->name() == "stability")
   {
     if(!_get(f->name(), _stability))
     {
       logger(LOG_WARNING) << "MedianFilter: Could not get the recently updated 'stability' parameter" << std::endl;
     }
   }
   else if(f->name() == "deadband")
   {
     if(!_get(f->name(), _deadband))
     {
       logger(LOG_WARNING) << "MedianFilter: Could not get the recently updated 'deadband' parameter" << std::endl;
     }
   }
   else if(f->name() == "deadbandStep")
   {
     if(!_get(f->name(), _deadbandStep))
     {
       logger(LOG_WARNING) << "MedianFilter: Could not get the recently updated 'deadbandStep' parameter" << std::endl;
     }
   }
   else if(f->name() == "halfKernelSize")
   {
     if(!_get(f->name(), _halfKernelSize))
     {
       logger(LOG_WARNING) << "MedianFilter: Could not get the recently updated 'halfKernelSize' parameter" << std::endl;
     }
   }
 }
void Voxel::MedianFilter::reset () virtual
Implements Voxel::Filter.
Definition at line 25 of file MedianFilter.cpp.
References _current.
 { _current.clear(); }
Member Data Documentation
Vector<ByteType> Voxel::MedianFilter::_current protected
Definition at line 27 of file MedianFilter.h.
Referenced by _filter(), and reset().
float Voxel::MedianFilter::_deadband protected
Definition at line 24 of file MedianFilter.h.
Referenced by _filter(), and _onSet().
float Voxel::MedianFilter::_deadbandStep protected
Definition at line 24 of file MedianFilter.h.
Referenced by _filter(), and _onSet().
uint Voxel::MedianFilter::_halfKernelSize protected
Definition at line 25 of file MedianFilter.h.
Referenced by _filter(), and _onSet().
Vector<ByteType> Voxel::MedianFilter::_hist protected
Definition at line 27 of file MedianFilter.h.
Referenced by _filter().
FrameSize Voxel::MedianFilter::_size protected
Definition at line 29 of file MedianFilter.h.
Referenced by _filter().
float Voxel::MedianFilter::_stability protected
Definition at line 24 of file MedianFilter.h.
Referenced by _filter(), and _onSet().
The documentation for this class was generated from the following files:
MedianFilter.h
MedianFilter.cpp