Voxel: Voxel::Filter Class Reference
Voxel::Filter Class Reference abstract
Filter related classes
#include <Filter.h>
Public Member Functions
Filter (const String &name, const String &description="", const String &nameScope="")
void setDepthCamera (const DepthCameraPtr &d)
const Map< String,
FilterParameterPtr > & parameters ()
const String & name ()
const String & description ()
void setNameScope (const String &scope)
bool filter (const FramePtr &in, FramePtr &out)
virtual void reset ()=0
FilterParameterConstPtr getParam (const String &name) const
template<typename T >
bool get (const String &name, T &value)
template<typename T >
bool set (const String &name, const T &value)
virtual ~Filter ()
Protected Member Functions
void _makeID ()
virtual bool _addParameters (const Vector< FilterParameterPtr > &params)
virtual bool _prepareOutput (const FramePtr &in, FramePtr &out)
virtual void _onSet (const FilterParameterPtr &f)=0
virtual bool _filter (const FramePtr &in, FramePtr &out)=0
template<typename T >
bool _get (const String &name, T &value)
template<typename T >
bool _set (const String &name, const T &value)
Protected Attributes
String _name
String _nameScope
String _description
String _id
Mutex _accessMutex
DepthCameraPtr _depthCamera
Map< String, FilterParameterPtr > _parameters
Detailed Description
Definition at line 32 of file Filter.h.
Constructor & Destructor Documentation
Voxel::Filter::Filter (const String & name, const String & description = "", const String & nameScope = "") inline
Definition at line 68 of file Filter.h.
                                                                                           : _name(name), _nameScope(nameScope), _description(description)
   {
     _makeID();
   }
virtual Voxel::Filter::~Filter () inline virtual
Definition at line 97 of file Filter.h.
 {}
Member Function Documentation
bool Voxel::Filter::_addParameters (const Vector< FilterParameterPtr > & params) protected virtual
Definition at line 12 of file Filter.cpp.
References _parameters, Voxel::LOG_ERROR, Voxel::logger, and LensCalibrationTest::x.
Referenced by Voxel::BilateralFilter::BilateralFilter(), Voxel::IIRFilter::IIRFilter(), Voxel::MedianFilter::MedianFilter(), Voxel::SmoothFilter::SmoothFilter(), and Voxel::TemporalMedianFilter::TemporalMedianFilter().
 {
   for(auto &p: params)
   {
     auto x = _parameters.find(p->name());
     if(x != _parameters.end())
     {
       logger(LOG_ERROR) << "Filter: A parameter with name '" << p->name() << "' already exists" << std::endl;
       return false;
     }
     _parameters[p->name()] = p;
   }
   return true;
 }
virtual bool Voxel::Filter::_filter (const FramePtr & in, FramePtr & out) protected pure virtual
Implemented in Voxel::TemporalMedianFilter, Voxel::MedianFilter, Voxel::SmoothFilter, Voxel::BilateralFilter, Voxel::IIRFilter, and Voxel::ToFCrossTalkFilter.
Referenced by filter().
void Voxel::Filter::_makeID () inline protected
Definition at line 38 of file Filter.h.
   {
     if(_nameScope.size())
       _id = _nameScope + "::" + _name;
     else
       _id = _name;
   }
virtual void Voxel::Filter::_onSet (const FilterParameterPtr & f) protected pure virtual
Implemented in Voxel::IIRFilter, Voxel::MedianFilter, Voxel::SmoothFilter, Voxel::TemporalMedianFilter, Voxel::BilateralFilter, and Voxel::ToFCrossTalkFilter.
Referenced by _set().
bool Voxel::Filter::_prepareOutput (const FramePtr & in, FramePtr & out) protected virtual
Definition at line 28 of file Filter.cpp.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::MedianFilter::_filter(), and Voxel::TemporalMedianFilter::_filter().
 {
   if(out && out->isSameSize(*in))
   {
     out->id = in->id;
     out->timestamp = in->timestamp;
     return true;
   }
   out = in->newFrame();
   out->id = in->id;
   out->timestamp = in->timestamp;
   return true;
 }
const String& Voxel::Filter::description () inline
Definition at line 81 of file Filter.h.
 { return _description; }
const String& Voxel::Filter::name () inline
Definition at line 80 of file Filter.h.
Referenced by _get(), and _set().
 { return _id; }
const Map<String, FilterParameterPtr>& Voxel::Filter::parameters () inline
Definition at line 78 of file Filter.h.
 { return _parameters; }
virtual void Voxel::Filter::reset () pure virtual
Implemented in Voxel::TemporalMedianFilter, Voxel::MedianFilter, Voxel::SmoothFilter, Voxel::BilateralFilter, Voxel::IIRFilter, and Voxel::ToFCrossTalkFilter.
void Voxel::Filter::setDepthCamera (const DepthCameraPtr & d) inline
Definition at line 73 of file Filter.h.
   {
     _depthCamera = d;
   }
void Voxel::Filter::setNameScope (const String & scope) inline
Definition at line 83 of file Filter.h.
 { _nameScope = scope; _makeID(); }
Member Data Documentation
Mutex Voxel::Filter::_accessMutex mutable protected
Definition at line 46 of file Filter.h.
Referenced by filter(), get(), getParam(), and set().
DepthCameraPtr Voxel::Filter::_depthCamera protected
Definition at line 48 of file Filter.h.
String Voxel::Filter::_description protected
Definition at line 35 of file Filter.h.
String Voxel::Filter::_id protected
Definition at line 36 of file Filter.h.
String Voxel::Filter::_name protected
Definition at line 35 of file Filter.h.
String Voxel::Filter::_nameScope protected
Definition at line 35 of file Filter.h.
Map<String, FilterParameterPtr> Voxel::Filter::_parameters protected
Definition at line 50 of file Filter.h.
Referenced by _addParameters(), _get(), _set(), and getParam().
The documentation for this class was generated from the following files:
Filter.h
Filter.cpp