Voxel: TinyXML2::MemPool Class Reference
TinyXML2::MemPool Class Reference abstract
Common and Utility classes
#include <TinyXML2.h>
Public Member Functions
MemPool ()
virtual ~MemPool ()
virtual int ItemSize () const =0
virtual void * Alloc ()=0
virtual void Free (void *)=0
virtual void SetTracked ()=0
virtual void Clear ()=0
Detailed Description
Definition at line 331 of file TinyXML2.h.
Constructor & Destructor Documentation
TinyXML2::MemPool::MemPool () inline
Definition at line 334 of file TinyXML2.h.
 {}
virtual TinyXML2::MemPool::~MemPool () inline virtual
Definition at line 335 of file TinyXML2.h.
 {}
Member Function Documentation
virtual void* TinyXML2::MemPool::Alloc () pure virtual
Implemented in TinyXML2::MemPoolT< SIZE >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLComment) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLAttribute) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLElement) >, and TinyXML2::MemPoolT< sizeof(TinyXML2::XMLText) >.
virtual void TinyXML2::MemPool::Clear () pure virtual
Implemented in TinyXML2::MemPoolT< SIZE >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLComment) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLAttribute) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLElement) >, and TinyXML2::MemPoolT< sizeof(TinyXML2::XMLText) >.
virtual void TinyXML2::MemPool::Free (void *) pure virtual
Implemented in TinyXML2::MemPoolT< SIZE >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLComment) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLAttribute) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLElement) >, and TinyXML2::MemPoolT< sizeof(TinyXML2::XMLText) >.
Referenced by TinyXML2::XMLElement::DeleteAttribute(), and TinyXML2::XMLNode::DeleteNode().
virtual int TinyXML2::MemPool::ItemSize () const pure virtual
Implemented in TinyXML2::MemPoolT< SIZE >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLComment) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLAttribute) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLElement) >, and TinyXML2::MemPoolT< sizeof(TinyXML2::XMLText) >.
virtual void TinyXML2::MemPool::SetTracked () pure virtual
Implemented in TinyXML2::MemPoolT< SIZE >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLComment) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLAttribute) >, TinyXML2::MemPoolT< sizeof(TinyXML2::XMLElement) >, and TinyXML2::MemPoolT< sizeof(TinyXML2::XMLText) >.
Referenced by TinyXML2::XMLNode::InsertAfterChild(), TinyXML2::XMLNode::InsertEndChild(), TinyXML2::XMLNode::InsertFirstChild(), TinyXML2::XMLElement::ParseAttributes(), and TinyXML2::XMLNode::ParseDeep().
The documentation for this class was generated from the following file:
TinyXML2.h