Voxel: Voxel::USBSystemPrivate Class Reference
Voxel::USBSystemPrivate Class Reference
I/O classes
#include <USBSystemPrivateLinux.h>
Public Member Functions
USBSystemPrivate ()
bool isInitialized ()
libusb_context * getContext ()
libusb_device * getDeviceHandle (const USBDevice &usbd)
This does not look at the channel to determine which channel to use.
Vector< DevicePtr > getDevices ()
String getDeviceNode (const USBDevice &usbd)
bool getBusDevNumbers (const USBDevice &usbd, uint8_t &busNumber, uint8_t &devNumber)
virtual ~USBSystemPrivate ()
USBSystemPrivate ()
bool isInitialized ()
Vector< DevicePtr > getDevices ()
String getDeviceNode (const USBDevice &usbd)
bool getDevInst (const String &devicePath, DWORD &devInst, LPGUID guid=(LPGUID)&GUID_CLASS_USB_DEVICE)
virtual ~USBSystemPrivate ()
Protected Member Functions
bool _iterateUDevUSB (Function< void(struct udev_device *dev, uint16_t vendorID, uint16_t productID, const String &serial, const String &serialIndex, const String &description)> process)
Protected Attributes
libusb_context * _context = 0
Private Member Functions
bool _getDeviceProperty (HDEVINFO devClassInfo, DeviceInfo &devInfo, DWORD prop, String &result)
template<typename T >
bool _getDeviceProperty (HANDLE devHandle, DWORD prop, Ptr< T > &result, Function< void(T &t)> init=nullptr)
bool _iterateSetupAPI (LPGUID guid, Function< void(HDEVINFO devClassInfo, DeviceInfo &devInfo, ULONG hubIndex)> process)
bool _iterateOverAllDevices (LPGUID guid, Function< void(HANDLE hubDevice, ULONG portIndex, const String &driverKeyName, DevicePtr &device)> process)
void _enumerateHub (int busIndex, const String &hubIndex, const String &hubName, Function< void(HANDLE hubDevice, ULONG portIndex, const String &driverKeyName, DevicePtr &device)> process)
bool _getStringDescriptor (HANDLE devHandle, ULONG index, UCHAR descriptorIndex, String &descriptor)
Detailed Description
Definition at line 24 of file USBSystemPrivateLinux.h.
Constructor & Destructor Documentation
Voxel::USBSystemPrivate::USBSystemPrivate () inline
Definition at line 32 of file USBSystemPrivateLinux.h.
References _context.
   {
     int ret = libusb_init(&_context);
     if(ret != LIBUSB_SUCCESS)
     {
       std::cerr << "Initialization of USB library failed" << std::endl;
       _context = 0;
       return;
     }
   }
virtual Voxel::USBSystemPrivate::~USBSystemPrivate () inline virtual
Definition at line 61 of file USBSystemPrivateLinux.h.
References _context.
   {
     if(_context)
     {
       libusb_exit(_context);
       _context = 0;
     }
   }
Voxel::USBSystemPrivate::USBSystemPrivate () inline
Definition at line 55 of file USBSystemPrivateWindows.h.
 {}
virtual Voxel::USBSystemPrivate::~USBSystemPrivate () inline virtual
Definition at line 65 of file USBSystemPrivateWindows.h.
 {}
Member Function Documentation
void Voxel::USBSystemPrivate::_enumerateHub (int busIndex, const String & hubIndex, const String & hubName, Function< void(HANDLE hubDevice, ULONG portIndex, const String &driverKeyName, DevicePtr &device)> process) private
Definition at line 164 of file USBSystemPrivateWindows.cpp.
References _getStringDescriptor(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by _iterateOverAllDevices().
 {
   String deviceName = "\\\\.\\" + hubName;
   HANDLE hHubDevice = CreateFile(deviceName.c_str(), GENERIC_WRITE, FILE_SHARE_WRITE, NULL, OPEN_EXISTING, 0, NULL);
   if (hHubDevice == INVALID_HANDLE_VALUE)
   {
     logger(LOG_ERROR) << "USBSystem: Could not open handle to device = '" << deviceName << "'" << std::endl;
     return;
   }
   USB_NODE_INFORMATION hubInfo;
   ULONG nBytes = 0;
   if (!DeviceIoControl(hHubDevice, IOCTL_USB_GET_NODE_INFORMATION, &hubInfo, sizeof(USB_NODE_INFORMATION), &hubInfo, sizeof(USB_NODE_INFORMATION), &nBytes, NULL))
   {
     logger(LOG_ERROR) << "USBSystem: Could not get information about USB hub device = '" << deviceName << "'" << std::endl;
     CloseHandle(hHubDevice);
     return;
   }
   ULONG numPorts = hubInfo.u.HubInformation.HubDescriptor.bNumberOfPorts;
   // Support for information + upto 30 end point informations
   nBytes = sizeof(USB_NODE_CONNECTION_INFORMATION) + sizeof(USB_PIPE_INFO) * 30;
   Ptr<USB_NODE_CONNECTION_INFORMATION> connectionInfo = byteAlloc<USB_NODE_CONNECTION_INFORMATION>(nBytes);
   for (ULONG index = 1; index <= numPorts; index++)
   {
     connectionInfo->ConnectionIndex = index;
     if (!DeviceIoControl(hHubDevice, IOCTL_USB_GET_NODE_CONNECTION_INFORMATION, &*connectionInfo, nBytes, &*connectionInfo, nBytes, &nBytes, NULL))
     {
       logger(LOG_ERROR) << "USBSystem: Could not get information about device = " << index << " connected to USB hub device = '" << deviceName << "'" << std::endl;
       continue;
     }
     if (connectionInfo->ConnectionStatus != DeviceConnected)
       continue;
     String portIndex = (hubIndex.size() ? (hubIndex + "." + std::to_string(index)) : std::to_string(index));
     if (connectionInfo->DeviceIsHub)
     {
       Ptr<USB_NODE_CONNECTION_NAME> usbNodeName;
       if (!_getDeviceProperty<USB_NODE_CONNECTION_NAME>(hHubDevice, IOCTL_USB_GET_NODE_CONNECTION_NAME, usbNodeName, [index](USB_NODE_CONNECTION_NAME &t) { t.ConnectionIndex = index; }))
       {
         logger(LOG_ERROR) << "USBSystem: Could not get node name of device = " << index << " connected to USB hub device = '" << deviceName << "'" << std::endl;
         continue;
       }
       _bstr_t b(usbNodeName->NodeName);
       String nodeName = b;
       _enumerateHub(busIndex, portIndex, nodeName, process);
     }
     else
     {
       Ptr<USB_NODE_CONNECTION_DRIVERKEY_NAME> usbNodeName;
       if (!_getDeviceProperty<USB_NODE_CONNECTION_DRIVERKEY_NAME>(hHubDevice, IOCTL_USB_GET_NODE_CONNECTION_DRIVERKEY_NAME, usbNodeName, [index](USB_NODE_CONNECTION_DRIVERKEY_NAME &t) { t.ConnectionIndex = index; }))
       {
         logger(LOG_ERROR) << "USBSystem: Could not get node name of device = " << index << " connected to USB hub device = '" << deviceName << "'" << std::endl;
         continue;
       }
       _bstr_t b(usbNodeName->DriverKeyName);
       String driverKeyName = b;
       String product, manufacturer, serialNumber, description;
       bool ret1 = _getStringDescriptor(hHubDevice, index, connectionInfo->DeviceDescriptor.iProduct, product);
       bool ret2 = _getStringDescriptor(hHubDevice, index, connectionInfo->DeviceDescriptor.iManufacturer, manufacturer);
       bool ret3 = _getStringDescriptor(hHubDevice, index, connectionInfo->DeviceDescriptor.iSerialNumber, serialNumber);
       if (!(ret1 && ret2 && ret3))
       {
         logger(LOG_DEBUG) << "USBSystem: Could not get request string descriptors for connection index = " << index << " connected to USB hub device = '" << deviceName << "'" << std::endl;
       }
       if (manufacturer.size() && product.size())
         description = manufacturer + " - " + product;
       else if (manufacturer.size())
         description = manufacturer;
       else if (product.size())
         description = product;
       if (process)
         process(hHubDevice, index, driverKeyName, DevicePtr(new USBDevice(connectionInfo->DeviceDescriptor.idVendor, connectionInfo->DeviceDescriptor.idProduct, serialNumber, -1, description, std::to_string(busIndex) + ":" + portIndex)));
     }
   }
   CloseHandle(hHubDevice);
 }
bool Voxel::USBSystemPrivate::_getDeviceProperty (HDEVINFO devClassInfo, DeviceInfo & devInfo, DWORD prop, String & result) private
Definition at line 62 of file USBSystemPrivateWindows.cpp.
References Voxel::DeviceInfo::devInfo.
Referenced by _iterateOverAllDevices().
 {
   BOOL bResult;
   DWORD requiredLength = 0;
   ppBuffer.clear();
   bResult = SetupDiGetDeviceRegistryProperty(devClassInfo, &devInfo.devInfo, prop, NULL, NULL, 0, &requiredLength);
   if ((requiredLength == 0) || (bResult && GetLastError() != ERROR_INSUFFICIENT_BUFFER))
     return false;
   ppBuffer.resize(requiredLength - 1); // but set size to one less to not consider null character
   ppBuffer.reserve(requiredLength);// Give space for null character
   return SetupDiGetDeviceRegistryProperty(devClassInfo, &devInfo.devInfo, prop, NULL, (PBYTE)ppBuffer.data(), requiredLength, &requiredLength);
 }
template<typename T > bool Voxel::USBSystemPrivate::_getDeviceProperty (HANDLE devHandle, DWORD prop, Ptr< T > & result, Function< void(T &t)> init = nullptr) private
Definition at line 81 of file USBSystemPrivateWindows.cpp.
 {
   ULONG nBytes = 0;
   T t;
   if (init)
     init(t);
   if (!DeviceIoControl(devHandle, prop, &t, sizeof(T), &t, sizeof(T), &nBytes, NULL))
     return false;
   nBytes = t.ActualLength;
   result = byteAlloc<T>(t.ActualLength); // Actual required size with custom deleter to reconvert to byte type and delete.
   if (!result)
     return false;
   if (init)
     init(*result);
   return DeviceIoControl(devHandle, prop, &*result, nBytes, &*result, nBytes, &nBytes, NULL);
 }
bool Voxel::USBSystemPrivate::_getStringDescriptor (HANDLE devHandle, ULONG index, UCHAR descriptorIndex, String & descriptor) private
Definition at line 263 of file USBSystemPrivateWindows.cpp.
References Voxel::LOG_DEBUG, and Voxel::logger.
Referenced by _enumerateHub().
 {
   ULONG   nBytes = sizeof(USB_DESCRIPTOR_REQUEST) + MAXIMUM_USB_STRING_LENGTH;
   ULONG   nBytesReturned = 0;
   if (descriptorIndex == 0) // No descriptor available
   {
     descriptor.clear();
     return true;
   }
   Ptr<USB_DESCRIPTOR_REQUEST> request = byteAlloc<USB_DESCRIPTOR_REQUEST>(nBytes);
   USB_STRING_DESCRIPTOR *stringDescriptor = (USB_STRING_DESCRIPTOR *)(request.get() + 1); // Appended to the end after sizeof(USB_DESCRIPTOR_REQUEST)
   // Zero fill the entire request structure
   //
   memset(request.get(), 0, nBytes);
   // Indicate the port from which the descriptor will be requested
   //
   request->ConnectionIndex = index;
   //
   // USBHUB uses URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE to process this
   // IOCTL_USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION request.
   //
   // USBD will automatically initialize these fields:
   //     bmRequest = 0x80
   //     bRequest  = 0x06
   //
   // We must inititialize these fields:
   //     wValue    = Descriptor Type (high) and Descriptor Index (low byte)
   //     wIndex    = Zero (or Language ID for String Descriptors)
   //     wLength   = Length of descriptor buffer
   //
   request->SetupPacket.wValue = (USB_STRING_DESCRIPTOR_TYPE << 8) | descriptorIndex;
   request->SetupPacket.wIndex = 0; // Using language ID zero
   request->SetupPacket.wLength = (USHORT)(nBytes - sizeof(USB_DESCRIPTOR_REQUEST));
   // Now issue the get descriptor request.
   //
   if (!DeviceIoControl(devHandle, IOCTL_USB_GET_DESCRIPTOR_FROM_NODE_CONNECTION, &*request, nBytes, &*request, nBytes, &nBytesReturned, NULL))
   {
     logger(LOG_DEBUG) << "USBSystem: Could not get string descriptor = " << (uint)descriptorIndex << " for connection index = " << index << std::endl;
     return false;
   }
   if (nBytesReturned < 2 || stringDescriptor->bDescriptorType != USB_STRING_DESCRIPTOR_TYPE ||
     (stringDescriptor->bLength != nBytesReturned - sizeof(USB_DESCRIPTOR_REQUEST)) ||
     stringDescriptor->bLength % 2 != 0)
   {
     logger(LOG_DEBUG) << "USBSystem: Got invalid string descriptor = " << (uint)descriptorIndex << " for connection index = " << index << std::endl;
     return false;
   }
   _bstr_t b(stringDescriptor->bString);
   descriptor = b;
   return true;
 }
bool Voxel::USBSystemPrivate::_iterateOverAllDevices (LPGUID guid, Function< void(HANDLE hubDevice, ULONG portIndex, const String &driverKeyName, DevicePtr &device)> process) private
Definition at line 327 of file USBSystemPrivateWindows.cpp.
References _enumerateHub(), _getDeviceProperty(), _iterateSetupAPI(), and Voxel::DeviceInfo::devInterfaceDetailData.
 {
   return _iterateSetupAPI(guid, [this, &process](HDEVINFO devClassInfo, DeviceInfo &devInfo, ULONG hubIndex) {
     HANDLE hHCDev = CreateFile(devInfo.devInterfaceDetailData->DevicePath, GENERIC_WRITE, FILE_SHARE_WRITE, NULL, OPEN_EXISTING, 0, NULL);
     if (hHCDev != INVALID_HANDLE_VALUE)
     {
       Ptr<USB_ROOT_HUB_NAME> rootHubName;
       if (!_getDeviceProperty(hHCDev, IOCTL_USB_GET_ROOT_HUB_NAME, rootHubName))
         return;
       _bstr_t b(rootHubName->RootHubName);
       String hubName = b;
       _enumerateHub(hubIndex + 1, "", hubName, process);
     }
     CloseHandle(hHCDev);
   });
 }
bool Voxel::USBSystemPrivate::_iterateSetupAPI (LPGUID guid, Function< void(HDEVINFO devClassInfo, DeviceInfo &devInfo, ULONG hubIndex)> process) private
Definition at line 106 of file USBSystemPrivateWindows.cpp.
References Voxel::DeviceInfo::devInfo, Voxel::DeviceInfo::devInterfaceData, Voxel::DeviceInfo::devInterfaceDetailData, Voxel::getDeviceError(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by _iterateOverAllDevices(), and getDevInst().
 {
   DWORD flags = DIGCF_PRESENT;
   if (guid) flags |= DIGCF_DEVICEINTERFACE;
   if (!guid) flags |= DIGCF_ALLCLASSES;
   HDEVINFO devClassInfo = SetupDiGetClassDevs(guid, NULL, NULL, flags); // | DIGCF_DEVICEINTERFACE
   if (devClassInfo == INVALID_HANDLE_VALUE)
   {
     logger(LOG_ERROR) << "USBSystem: Failed to get handle to device class. Error = " << getDeviceError() << std::endl;
     return false;
   }
   DeviceInfo deviceInfo;
   deviceInfo.devInfo.cbSize = sizeof(SP_DEVINFO_DATA);
   ULONG requiredLength;
   for (ULONG index = 0; SetupDiEnumDeviceInfo(devClassInfo, index, &deviceInfo.devInfo); index++)
   {
     deviceInfo.devInterfaceData.cbSize = sizeof(SP_DEVICE_INTERFACE_DATA);
     // FIXME: Currently this considers only the first interface of the device. Should we look for all the interfaces?
     if (!SetupDiEnumDeviceInterfaces(devClassInfo, &deviceInfo.devInfo, guid, 0, &deviceInfo.devInterfaceData))
     {
       logger(LOG_ERROR) << "USBSystem: Failed to enumerate device interfaces for index = " << index << ". Error = " << getDeviceError() << std::endl;
       SetupDiDestroyDeviceInfoList(devClassInfo);
       return false;
     }
     if (!SetupDiGetDeviceInterfaceDetail(devClassInfo, &deviceInfo.devInterfaceData, NULL, 0, &requiredLength, NULL) && GetLastError() != ERROR_INSUFFICIENT_BUFFER)
     {
       logger(LOG_ERROR) << "USBSystem: Failed to get size for interface details for index = " << index << ". Error = " << getDeviceError() << std::endl;
       SetupDiDestroyDeviceInfoList(devClassInfo);
       return false;
     }
     deviceInfo.devInterfaceDetailData = byteAlloc<SP_DEVICE_INTERFACE_DETAIL_DATA>(requiredLength);
     deviceInfo.devInterfaceDetailData->cbSize = sizeof(SP_DEVICE_INTERFACE_DETAIL_DATA);
     if (!SetupDiGetDeviceInterfaceDetail(devClassInfo, &deviceInfo.devInterfaceData, &*deviceInfo.devInterfaceDetailData, requiredLength, &requiredLength, NULL))
     {
       logger(LOG_ERROR) << "USBSystem: Failed to get interface details for index = " << index << ". Error = " << getDeviceError() << std::endl;
       SetupDiDestroyDeviceInfoList(devClassInfo);
       return false;
     }
     process(devClassInfo, deviceInfo, index);
   }
   SetupDiDestroyDeviceInfoList(devClassInfo);
   return true;
 }
bool Voxel::USBSystemPrivate::_iterateUDevUSB (Function< void(struct udev_device *dev, uint16_t vendorID, uint16_t productID, const String &serial, const String &serialIndex, const String &description)> process) protected
Definition at line 60 of file USBSystemPrivateLinux.cpp.
References CameraSystemTest::devices, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by getBusDevNumbers(), and getDevices().
 {
   udev *udevHandle = udev_new();
   String devNode;
   if(!udevHandle)
   {
     logger(LOG_ERROR) << "USBSystem: UDev Init failed" << std::endl;
     return false;
   }
   struct udev_enumerate *enumerate;
   struct udev_list_entry *devices;
   struct udev_list_entry *devListEntry;
   /* Create a list of the devices in the 'v4l2' subsystem. */
   enumerate = udev_enumerate_new(udevHandle);
   udev_enumerate_add_match_subsystem(enumerate, "usb");
   udev_enumerate_add_match_property(enumerate, "DEVTYPE", "usb_device");
   udev_enumerate_scan_devices(enumerate);
   devices = udev_enumerate_get_list_entry(enumerate);
   /*
    * For each item enumerated, print out its information.
    * udev_list_entry_foreach is a macro which expands to
    * a loop. The loop will be executed for each member in
    * devices, setting dev_list_entry to a list entry
    * which contains the device's path in /sys.
    */
   udev_list_entry_foreach(devListEntry, devices)
   {
     const char *path;
     /*
      * Get the filename of the /sys entry for the device
      * and create a udev_device object (dev) representing it
      */
     path = udev_list_entry_get_name(devListEntry);
     struct udev_device *dev = udev_device_new_from_syspath(udevHandle, path);
     uint16_t vendorID, productID;
     String serial, serialIndex, description, productDesc;
     char *endptr;
     vendorID = strtol(udev_device_get_sysattr_value(dev, "idVendor"), &endptr, 16);
     productID = strtol(udev_device_get_sysattr_value(dev, "idProduct"), &endptr, 16);
     serialIndex += udev_device_get_sysattr_value(dev, "busnum");
     serialIndex += ":";
     serialIndex += udev_device_get_sysattr_value(dev, "devpath");
     if(udev_device_get_sysattr_value(dev, "manufacturer"))
       description = udev_device_get_sysattr_value(dev, "manufacturer");
     if(udev_device_get_sysattr_value(dev, "product"))
       productDesc = udev_device_get_sysattr_value(dev, "product");
     if(productDesc.size())
     {
       if(description.size())
         description += " - ";
       description += productDesc;
     }
     const char *s = udev_device_get_sysattr_value(dev, "serial");
     if(s) serial = s;
     process(dev, vendorID, productID, serial, serialIndex, description);
     udev_device_unref(dev);
   }
   /* Free the enumerator object */
   udev_enumerate_unref(enumerate);
   udev_unref(udevHandle);
   return true;
 }
bool Voxel::USBSystemPrivate::getBusDevNumbers (const USBDevice & usbd, uint8_t & busNumber, uint8_t & devNumber)
Definition at line 139 of file USBSystemPrivateLinux.cpp.
References _iterateUDevUSB(), Voxel::USBDevice::productID(), Voxel::Device::serialIndex(), Voxel::Device::serialNumber(), and Voxel::USBDevice::vendorID().
Referenced by getDeviceHandle().
 {
   busNumber = devNumber = 0;
   bool gotDevice = false;
   _iterateUDevUSB([&gotDevice, &busNumber, &devNumber, &usbd](struct udev_device *dev, uint16_t vendorID, uint16_t productID, const String &serial, const String &serialIndex,
     const String &description)
   {
     char *endptr;
     if(!gotDevice && usbd.vendorID() == vendorID && usbd.productID() == productID &&
         (usbd.serialNumber().size() == 0 || serial == usbd.serialNumber()) &&
         (usbd.serialIndex().size() == 0 || serialIndex == usbd.serialIndex()))
       {
         busNumber = strtol(udev_device_get_sysattr_value(dev, "busnum"), &endptr, 10);
         devNumber = strtol(udev_device_get_sysattr_value(dev, "devnum"), &endptr, 10);
         gotDevice = true;
       }
   });
   return gotDevice;
 }
libusb_context* Voxel::USBSystemPrivate::getContext () inline
Definition at line 46 of file USBSystemPrivateLinux.h.
References _context.
Referenced by isInitialized().
   {
     return _context;
   }
libusb_device * Voxel::USBSystemPrivate::getDeviceHandle (const USBDevice & usbd)
This does not look at the channel to determine which channel to use.
Definition at line 28 of file USBSystemPrivateLinux.cpp.
References _context, CameraSystemIQFrameTest::count, getBusDevNumbers(), Voxel::Device::id(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::USBIO::USBIOPrivate::USBIOPrivate().
 {
   uint8_t busNumber, devNumber;
   if(!_context)
     return nullptr; // libusb is not initialized
   if(!getBusDevNumbers(usbd, busNumber, devNumber))
   {
     logger(LOG_ERROR) << "USBSystem: Failed to get bus and device numbers for device '" << usbd.id() << "'" << std::endl;
     return nullptr;
   }
   libusb_device *selected = 0;
   libusb_device** libusb_list;
   int count = libusb_get_device_list(_context, &libusb_list);
   for (auto i = 0; i < count; i++)
   {
     if ((busNumber == libusb_get_bus_number(libusb_list[i])) && (devNumber == libusb_get_device_address(libusb_list[i])))
       selected = libusb_list[i];
     else
       libusb_unref_device(libusb_list[i]);
   }
   libusb_free_device_list(libusb_list, 0);
   return selected;
 }
String Voxel::USBSystemPrivate::getDeviceNode (const USBDevice & usbd)
Definition at line 163 of file USBSystemPrivateLinux.cpp.
References Voxel::Device::channelID(), CameraSystemTest::devices, Voxel::LOG_ERROR, Voxel::LOG_WARNING, Voxel::logger, Voxel::USBDevice::productID(), Voxel::Device::serialIndex(), Voxel::Device::serialNumber(), and Voxel::USBDevice::vendorID().
 {
   udev *udevHandle = udev_new();
   String devNode;
   if(!udevHandle)
   {
     logger(LOG_ERROR) << "USBSystem: Init failed to get device node" << std::endl;
     return "";
   }
   struct udev_enumerate *enumerate;
   struct udev_list_entry *devices;
   struct udev_list_entry *devListEntry;
   /* Create a list of the devices in the 'v4l2' subsystem. */
   enumerate = udev_enumerate_new(udevHandle);
   udev_enumerate_add_match_subsystem(enumerate, "video4linux");
   udev_enumerate_scan_devices(enumerate);
   devices = udev_enumerate_get_list_entry(enumerate);
   /*
     * For each item enumerated, print out its information.
     * udev_list_entry_foreach is a macro which expands to
     * a loop. The loop will be executed for each member in
     * devices, setting dev_list_entry to a list entry
     * which contains the device's path in /sys.
     */
   udev_list_entry_foreach(devListEntry, devices)
   {
     const char *path;
     /*
       * Get the filename of the /sys entry for the device
       * and create a udev_device object (dev) representing it
       */
     path = udev_list_entry_get_name(devListEntry);
     struct udev_device *dev = udev_device_new_from_syspath(udevHandle, path), *pdev, *pdev2;
     /* usb_device_get_devnode() returns the path to the device node
       * itself in /dev.
       */
     const char *v4l2Device = udev_device_get_devnode(dev);
     /* The device pointed to by dev contains information about
       *      t he v4l2 device. In orde*r to get information about the
       *      USB device, get the parent device with the
       *      subsystem/devtype pair of "usb"/"usb_device". This will
       *      be several levels up the tree, but the function will find
       *      it.*/
     pdev = udev_device_get_parent_with_subsystem_devtype(dev, "usb", "usb_device");
     if(!pdev)
     {
       logger(LOG_WARNING) << "USBSystem: Unable to find parent usb device." << std::endl;
       udev_device_unref(dev);
       continue;
     }
     if(usbd.channelID() >= 0) // Valid channel ID?
     {
       pdev2 = udev_device_get_parent_with_subsystem_devtype(dev, "usb", "usb_interface");
       if(!pdev2)
       {
         logger(LOG_WARNING) << "USBSystem: Unable to find parent usb interface." << std::endl;
         udev_device_unref(dev);
         continue;
       }
     }
     /* From here, we can call get_sysattr_value() for each file
       *      in the device's /sys entry. The strings passed into these
       *      functions (idProduct, idVendor, serial, etc.) correspond
       *      directly to the files in the directory which represents
       *      the USB device. Note that USB strings are Unicode, UCS2
       *      encoded, but the strings returned from
       *      udev_device_get_sysattr_value() are UTF-8 encoded. */
     uint16_t vendorID, productID;
     uint8_t channelID;
     String serial, serialIndex;
     char *endptr;
     vendorID = strtol(udev_device_get_sysattr_value(pdev, "idVendor"), &endptr, 16);
     productID = strtol(udev_device_get_sysattr_value(pdev, "idProduct"), &endptr, 16);
     if(usbd.channelID() >= 0)
       channelID = strtol(udev_device_get_sysattr_value(pdev2, "bInterfaceNumber"), &endptr, 16);
     if(usbd.serialIndex().size())
     {
       serialIndex += udev_device_get_sysattr_value(pdev, "busnum");
       serialIndex += ":";
       serialIndex += udev_device_get_sysattr_value(pdev, "devpath");
     }
     const char *s = udev_device_get_sysattr_value(pdev, "serial");
     if(s) serial = s;
     if(usbd.vendorID() == vendorID && usbd.productID() == productID &&
       (usbd.serialNumber().size() == 0 || serial == usbd.serialNumber()) &&
       (usbd.channelID() < 0 || channelID == usbd.channelID()) &&
       (usbd.serialIndex().size() == 0 || serialIndex == usbd.serialIndex()))
       devNode = v4l2Device;
     udev_device_unref(dev);
   }
   /* Free the enumerator object */
   udev_enumerate_unref(enumerate);
   udev_unref(udevHandle);
   return devNode;
 }
String Voxel::USBSystemPrivate::getDeviceNode (const USBDevice & usbd)
Vector< DevicePtr > Voxel::USBSystemPrivate::getDevices ()
Definition at line 15 of file USBSystemPrivateLinux.cpp.
References _iterateUDevUSB(), and CameraSystemTest::devices.
 {
   Vector<DevicePtr> devices;
   devices.reserve(10);
   _iterateUDevUSB([&devices](struct udev_device *dev, uint16_t vendorID, uint16_t productID, const String &serial, const String &serialIndex, const String &description)
   {
     devices.push_back(DevicePtr(new USBDevice(vendorID, productID, serial, -1, description, serialIndex)));
   });
   return devices;
 }
Vector<DevicePtr> Voxel::USBSystemPrivate::getDevices ()
bool Voxel::USBSystemPrivate::getDevInst (const String & devicePath, DWORD & devInst, LPGUID guid = (LPGUID)&GUID_CLASS_USB_DEVICE)
Definition at line 418 of file USBSystemPrivateWindows.cpp.
References _iterateSetupAPI(), Voxel::DeviceInfo::devInfo, and Voxel::DeviceInfo::devInterfaceDetailData.
 {
   bool devInstSet = false;
   bool ret = _iterateSetupAPI(guid, [this, &devicePath, &devInst, &devInstSet](HDEVINFO devClassInfo, DeviceInfo &devInfo, ULONG hubIndex) {
     _bstr_t b(devInfo.devInterfaceDetailData->DevicePath);
     String devPath = b;
     if (!devInstSet && devPath == devicePath)
     {
       devInst = devInfo.devInfo.DevInst;
       devInstSet = true;
     }
   });
   return devInstSet;
 }
bool Voxel::USBSystemPrivate::isInitialized () inline
Definition at line 44 of file USBSystemPrivateLinux.h.
References getContext().
 { return getContext(); }
bool Voxel::USBSystemPrivate::isInitialized ()
Member Data Documentation
libusb_context* Voxel::USBSystemPrivate::_context = 0 protected
Definition at line 27 of file USBSystemPrivateLinux.h.
Referenced by getContext(), getDeviceHandle(), USBSystemPrivate(), and ~USBSystemPrivate().
The documentation for this class was generated from the following files:
USBSystemPrivateLinux.h
USBSystemPrivateWindows.h
USBSystemPrivateLinux.cpp
USBSystemPrivateWindows.cpp