Voxel: ELFIO::section_impl< T > Class Template Reference
ELFIO::section_impl< T > Class Template Reference
#include <elfio_section.hpp>
Public Member Functions
section_impl (const endianess_convertor *convertor_)
~section_impl ()
ELFIO_GET_SET_ACCESS (Elf_Word, type, header.sh_type)
ELFIO_GET_SET_ACCESS (Elf_Xword, flags, header.sh_flags)
ELFIO_GET_SET_ACCESS (Elf_Xword, size, header.sh_size)
ELFIO_GET_SET_ACCESS (Elf_Word, link, header.sh_link)
ELFIO_GET_SET_ACCESS (Elf_Word, info, header.sh_info)
ELFIO_GET_SET_ACCESS (Elf_Xword, addr_align, header.sh_addralign)
ELFIO_GET_SET_ACCESS (Elf_Xword, entry_size, header.sh_entsize)
ELFIO_GET_SET_ACCESS (Elf_Word, name_string_offset, header.sh_name)
ELFIO_GET_ACCESS (Elf64_Addr, address, header.sh_addr)
Elf_Half get_index () const
std::string get_name () const
void set_name (std::string name_)
void set_address (Elf64_Addr value)
bool is_address_initialized () const
const char * get_data () const
void set_data (const char *raw_data, Elf_Word size)
void set_data (const std::string &str_data)
void append_data (const char *raw_data, Elf_Word size)
void append_data (const std::string &str_data)
Public Member Functions inherited from ELFIO::section
virtual ~section ()
ELFIO_GET_ACCESS_DECL (Elf_Half, index)
ELFIO_GET_SET_ACCESS_DECL (std::string, name)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, type)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, flags)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, info)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, link)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, addr_align)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, entry_size)
ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr, address)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, size)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, name_string_offset)
Protected Member Functions
ELFIO_GET_SET_ACCESS (Elf64_Off, offset, header.sh_offset)
void set_index (Elf_Half value)
void load (std::istream &stream, std::streampos header_offset)
void save (std::ostream &f, std::streampos header_offset, std::streampos data_offset)
Protected Member Functions inherited from ELFIO::section
ELFIO_GET_SET_ACCESS_DECL (Elf64_Off, offset)
ELFIO_SET_ACCESS_DECL (Elf_Half, index)
Private Member Functions
void save_header (std::ostream &f, std::streampos header_offset) const
void save_data (std::ostream &f, std::streampos data_offset) const
Private Attributes
T header
Elf_Half index
std::string name
char * data
Elf_Word data_size
const endianess_convertor * convertor
bool is_address_set
Detailed Description
template<class T>
class ELFIO::section_impl< T >
Definition at line 69 of file elfio_section.hpp.
Constructor & Destructor Documentation
template<class T > ELFIO::section_impl< T >::section_impl (const endianess_convertor * convertor_) inline
Definition at line 73 of file elfio_section.hpp.
References ELFIO::section_impl< T >::data, ELFIO::section_impl< T >::data_size, ELFIO::section_impl< T >::header, and ELFIO::section_impl< T >::is_address_set.
                                                           : convertor( convertor_ )
     {
         std::fill_n( reinterpret_cast<char*>( &header ), sizeof( header ), '\0' );
         is_address_set = false;
         data           = 0;
         data_size      = 0;
     }
template<class T > ELFIO::section_impl< T >::~section_impl () inline
Definition at line 82 of file elfio_section.hpp.
References ELFIO::section_impl< T >::data.
     {
         delete [] data;
     }
Member Function Documentation
template<class T > void ELFIO::section_impl< T >::append_data (const char * raw_data, Elf_Word size) inline virtual
Implements ELFIO::section.
Definition at line 169 of file elfio_section.hpp.
References ELFIO::section_impl< T >::data, ELFIO::section_impl< T >::data_size, and SHT_NOBITS.
Referenced by ELFIO::section_impl< T >::append_data().
     {
         if ( get_type() != SHT_NOBITS ) {
             if ( get_size() + size < data_size ) {
                 std::copy( raw_data, raw_data + size, data + get_size() );
             }
             else {
                 data_size = 2*( data_size + size);
                 char* new_data = new char[data_size];
                 if ( 0 != new_data ) {
                     std::copy( data, data + get_size(), new_data );
                     std::copy( raw_data, raw_data + size, new_data + get_size() );
                     delete [] data;
                     data = new_data;
                 }
             }
             set_size( get_size() + size );
         }
     }
template<class T > void ELFIO::section_impl< T >::append_data (const std::string & str_data) inline virtual
Implements ELFIO::section.
Definition at line 191 of file elfio_section.hpp.
References ELFIO::section_impl< T >::append_data().
     {
         return append_data( str_data.c_str(), (Elf_Word)str_data.size() );
     }
template<class T > ELFIO::section_impl< T >::ELFIO_GET_ACCESS (Elf64_Addr , address , header. sh_addr)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Word , type , header. sh_type)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Xword , flags , header. sh_flags)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Xword , size , header. sh_size)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Word , link , header. sh_link)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Word , info , header. sh_info)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Xword , addr_align , header. sh_addralign)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Xword , entry_size , header. sh_entsize)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf_Word , name_string_offset , header. sh_name)
template<class T > ELFIO::section_impl< T >::ELFIO_GET_SET_ACCESS (Elf64_Off , offset , header. sh_offset) protected
template<class T > const char* ELFIO::section_impl< T >::get_data () const inline virtual
Implements ELFIO::section.
Definition at line 139 of file elfio_section.hpp.
References ELFIO::section_impl< T >::data.
Referenced by ELFIO::section_impl< T >::save_data().
     {
         return data;
     }
template<class T > Elf_Half ELFIO::section_impl< T >::get_index () const inline
Definition at line 101 of file elfio_section.hpp.
References ELFIO::section_impl< T >::index.
Referenced by ELFIO::section_impl< T >::save().
     {
         return index;
     }
template<class T > std::string ELFIO::section_impl< T >::get_name () const inline
Definition at line 109 of file elfio_section.hpp.
References ELFIO::section_impl< T >::name.
     {
         return name;
     }
template<class T > bool ELFIO::section_impl< T >::is_address_initialized () const inline virtual
Implements ELFIO::section.
Definition at line 132 of file elfio_section.hpp.
References ELFIO::section_impl< T >::is_address_set.
     {
         return is_address_set;
     }
template<class T > void ELFIO::section_impl< T >::load (std::istream & stream, std::streampos header_offset) inline protected virtual
Implements ELFIO::section.
Definition at line 210 of file elfio_section.hpp.
References ELFIO::section_impl< T >::convertor, ELFIO::section_impl< T >::data, ELFIO::section_impl< T >::data_size, ELFIO::section_impl< T >::header, SHT_NOBITS, and SHT_NULL.
     {
         std::fill_n( reinterpret_cast<char*>( &header ), sizeof( header ), '\0' );
         stream.seekg( header_offset );
         stream.read( reinterpret_cast<char*>( &header ), sizeof( header ) );
         Elf_Xword size = get_size();
         if ( 0 == data && SHT_NULL != get_type() && SHT_NOBITS != get_type() ) {
             data = new char[size];
             if ( 0 != size ) {
                 stream.seekg( (*convertor)( header.sh_offset ) );
                 stream.read( data, size );
                 data_size = size;
             }
         }
     }
template<class T > void ELFIO::section_impl< T >::save (std::ostream & f, std::streampos header_offset, std::streampos data_offset) inline protected virtual
Implements ELFIO::section.
Definition at line 230 of file elfio_section.hpp.
References ELFIO::section_impl< T >::data, ELFIO::section_impl< T >::get_index(), ELFIO::section_impl< T >::header, ELFIO::section_impl< T >::save_data(), ELFIO::section_impl< T >::save_header(), SHT_NOBITS, and SHT_NULL.
     {
         if ( 0 != get_index() ) {
             header.sh_offset = data_offset;
             header.sh_offset = (*convertor)( header.sh_offset );
         }
         save_header( f, header_offset );
         if ( get_type() != SHT_NOBITS && get_type() != SHT_NULL &&
              get_size() != 0 && data != 0 ) {
             save_data( f, data_offset );
         }
     }
template<class T > void ELFIO::section_impl< T >::save_data (std::ostream & f, std::streampos data_offset) const inline private
Definition at line 259 of file elfio_section.hpp.
References ELFIO::section_impl< T >::get_data().
Referenced by ELFIO::section_impl< T >::save().
     {
         f.seekp( data_offset );
         f.write( get_data(), get_size() );
     }
template<class T > void ELFIO::section_impl< T >::save_header (std::ostream & f, std::streampos header_offset) const inline private
Definition at line 250 of file elfio_section.hpp.
References ELFIO::section_impl< T >::header.
Referenced by ELFIO::section_impl< T >::save().
     {
         f.seekp( header_offset );
         f.write( reinterpret_cast<const char*>( &header ), sizeof( header ) );
     }
template<class T > void ELFIO::section_impl< T >::set_address (Elf64_Addr value) inline
Definition at line 123 of file elfio_section.hpp.
References ELFIO::section_impl< T >::header, and ELFIO::section_impl< T >::is_address_set.
     {
         header.sh_addr = value;
         header.sh_addr = (*convertor)( header.sh_addr );
         is_address_set = true;
     }
template<class T > void ELFIO::section_impl< T >::set_data (const char * raw_data, Elf_Word size) inline virtual
Implements ELFIO::section.
Definition at line 146 of file elfio_section.hpp.
References ELFIO::section_impl< T >::data, ELFIO::section_impl< T >::data_size, and SHT_NOBITS.
Referenced by ELFIO::section_impl< T >::set_data().
     {
         if ( get_type() != SHT_NOBITS ) {
             delete [] data;
             data = new char[size];
             if ( 0 != data && 0 != raw_data ) {
                 data_size = size;
                 std::copy( raw_data, raw_data + size, data );
             }
         }
         set_size( size );
     }
template<class T > void ELFIO::section_impl< T >::set_data (const std::string & str_data) inline virtual
Implements ELFIO::section.
Definition at line 162 of file elfio_section.hpp.
References ELFIO::section_impl< T >::set_data().
     {
         return set_data( str_data.c_str(), (Elf_Word)str_data.size() );
     }
template<class T > void ELFIO::section_impl< T >::set_index (Elf_Half value) inline protected
Definition at line 203 of file elfio_section.hpp.
References ELFIO::section_impl< T >::index.
     {
         index = value;
     }
template<class T > void ELFIO::section_impl< T >::set_name (std::string name_) inline
Definition at line 116 of file elfio_section.hpp.
References ELFIO::section_impl< T >::name.
     {
         name = name_;
     }
Member Data Documentation
template<class T > const endianess_convertor* ELFIO::section_impl< T >::convertor private
Definition at line 273 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::load().
template<class T > char* ELFIO::section_impl< T >::data private
Definition at line 271 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::append_data(), ELFIO::section_impl< T >::get_data(), ELFIO::section_impl< T >::load(), ELFIO::section_impl< T >::save(), ELFIO::section_impl< T >::section_impl(), ELFIO::section_impl< T >::set_data(), and ELFIO::section_impl< T >::~section_impl().
template<class T > Elf_Word ELFIO::section_impl< T >::data_size private
Definition at line 272 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::append_data(), ELFIO::section_impl< T >::load(), ELFIO::section_impl< T >::section_impl(), and ELFIO::section_impl< T >::set_data().
template<class T > T ELFIO::section_impl< T >::header private
Definition at line 268 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::load(), ELFIO::section_impl< T >::save(), ELFIO::section_impl< T >::save_header(), ELFIO::section_impl< T >::section_impl(), and ELFIO::section_impl< T >::set_address().
template<class T > Elf_Half ELFIO::section_impl< T >::index private
Definition at line 269 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::get_index(), and ELFIO::section_impl< T >::set_index().
template<class T > bool ELFIO::section_impl< T >::is_address_set private
Definition at line 274 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::is_address_initialized(), ELFIO::section_impl< T >::section_impl(), and ELFIO::section_impl< T >::set_address().
template<class T > std::string ELFIO::section_impl< T >::name private
Definition at line 270 of file elfio_section.hpp.
Referenced by ELFIO::section_impl< T >::get_name(), and ELFIO::section_impl< T >::set_name().
The documentation for this class was generated from the following file:
elfio_section.hpp