Voxel: Voxel::ConfigSet Class Reference
Voxel::ConfigSet Class Reference
#include <Configuration.h>
Public Member Functions
bool remove (const String &name)
bool isEmpty ()
bool isPresent (const String &name) const
String get (const String &name) const
int getInteger (const String &name) const
float getFloat (const String &name) const
bool getBoolean (const String &name) const
bool set (const String &name, const String &value)
bool setInteger (const String &name, int value)
bool setFloat (const String &name, float value)
bool setBoolean (const String &name, bool value)
Public Attributes
Map< String, String > params
Vector< String > paramNames
Protected Member Functions
bool _get (const String &name, String &value) const
bool _set (const String &name, const String &value)
Friends
class ConfigurationFile
Detailed Description
Definition at line 70 of file Configuration.h.
Member Function Documentation
bool Voxel::ConfigSet::_get (const String & name, String & value) const protected
Definition at line 289 of file Configuration.cpp.
References params.
Referenced by Voxel::ConfigurationFile::_get(), and get().
 {
   if(params.find(name) != params.end())
   {
     value = params.at(name);
     return true;
   }
   return false;
 }
bool Voxel::ConfigSet::_set (const String & name, const String & value) protected
Definition at line 647 of file Configuration.cpp.
References paramNames, params, and Voxel::trim().
Referenced by Voxel::ConfigurationFile::_set(), set(), setBoolean(), setFloat(), and setInteger().
 {
   String n = name, v = value;
   trim(n);
   trim(v);
   params[n] = v;
   bool present = false;
   for(auto i = 0; i < paramNames.size(); i++)
     if(paramNames[i] == n)
     {
       present = true;
       break;
     }
   if(!present)
     paramNames.push_back(name);
   return true;
 }
String Voxel::ConfigSet::get (const String & name) const
Definition at line 333 of file Configuration.cpp.
References _get().
Referenced by Voxel::DepthCamera::_applyConfigParams().
 {
   String value;
   if(!_get(name, value))
     return "";
   else
     return value;
 }
bool Voxel::ConfigSet::getBoolean (const String & name) const
Definition at line 395 of file Configuration.cpp.
Referenced by Voxel::DepthCamera::_applyConfigParams().
 {
   String s = get(name);
   if(!s.size())
     return false;
   if(s == "true" || s == "True" || s == "1")
     return true;
   else
     return false;
 }
float Voxel::ConfigSet::getFloat (const String & name) const
Definition at line 374 of file Configuration.cpp.
Referenced by Voxel::DepthCamera::_applyConfigParams().
 {
   String s = get(name);
   if(!s.size())
     return 0.0f;
   return atof(s.c_str());
 }
int Voxel::ConfigSet::getInteger (const String & name) const
Definition at line 353 of file Configuration.cpp.
Referenced by Voxel::DepthCamera::_applyConfigParams().
 {
   String s = get(name);
   if(!s.size())
     return 0;
   return atoi(s.c_str());
 }
bool Voxel::ConfigSet::isEmpty () inline
Definition at line 82 of file Configuration.h.
Referenced by Voxel::ConfigurationFile::remove().
 { return params.size() == 0; }
bool Voxel::ConfigSet::isPresent (const String & name) const
Definition at line 227 of file Configuration.cpp.
References params.
Referenced by Voxel::ConfigurationFile::isPresent().
 {
   if(params.find(name) == params.end())
     return false;
   return true;
 }
bool Voxel::ConfigSet::remove (const String & name)
Definition at line 749 of file Configuration.cpp.
References paramNames, and params.
Referenced by Voxel::ConfigurationFile::remove().
 {
   if(params.find(name) != params.end())
   {
     params.erase(params.find(name));
     for(auto i = paramNames.begin(); i != paramNames.end(); i++)
       if(name == *i)
       {
         paramNames.erase(i);
         break;
       }
     return true;
   }
   return false;
 }
bool Voxel::ConfigSet::set (const String & name, const String & value)
Definition at line 669 of file Configuration.cpp.
References _set().
 {
   return _set(name, value);
 }
bool Voxel::ConfigSet::setBoolean (const String & name, bool value)
Definition at line 674 of file Configuration.cpp.
References _set().
 {
   if(value)
     return _set(name, "true");
   else
     return _set(name, "false");
 }
bool Voxel::ConfigSet::setFloat (const String & name, float value)
Definition at line 682 of file Configuration.cpp.
References _set().
 {
   OutputStringStream o;
   o << value;
   return _set(name, o.str());
 }
bool Voxel::ConfigSet::setInteger (const String & name, int value)
Definition at line 690 of file Configuration.cpp.
References _set().
 {
   OutputStringStream o;
   o << value;
   return _set(name, o.str());
 }
Friends And Related Function Documentation
friend class ConfigurationFile friend
Definition at line 95 of file Configuration.h.
Member Data Documentation
Vector<String> Voxel::ConfigSet::paramNames
Definition at line 78 of file Configuration.h.
Referenced by Voxel::DepthCamera::_applyConfigParams(), _set(), and remove().
Map<String, String> Voxel::ConfigSet::params
Definition at line 77 of file Configuration.h.
Referenced by _get(), _set(), isPresent(), and remove().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp