Voxel: Voxel::UVCXU Class Reference
Voxel::UVCXU Class Reference
I/O classes
#include <UVCXU.h>
Classes
class UVCXUPrivate
Public Member Functions
UVCXU (DevicePtr usb, int xuID)
bool isInitialized ()
virtual ~UVCXU ()
bool setControl (int controlnumber, int size, uint8_t *value)
bool getControl (int controlnumber, int size, uint8_t *value)
Public Member Functions inherited from Voxel::UVC
UVC (DevicePtr usb)
UVCPrivate & getUVCPrivate ()
bool read (uint8_t *buffer, std::size_t size)
virtual ~UVC ()
Protected Attributes
int _xuID
class VOXEL_NO_EXPORT UVCXUPrivate
Ptr< UVCXUPrivate > _uvcXUPrivate
Protected Attributes inherited from Voxel::UVC
DevicePtr _usb
Ptr< UVCPrivate > _uvcPrivate
Detailed Description
Definition at line 20 of file UVCXU.h.
Constructor & Destructor Documentation
Voxel::UVCXU::UVCXU (DevicePtr usb, int xuID)
Definition at line 49 of file UVCXU.cpp.
References Voxel::UVC::_uvcPrivate, _uvcXUPrivate, _xuID, Voxel::UVC::isInitialized(), Voxel::LOG_ERROR, and Voxel::logger.
                                    : UVC(usb), _xuID(xuID), _uvcXUPrivate(Ptr<UVCXUPrivate>(new UVCXUPrivate()))
 {
 #ifdef WINDOWS
   if (!UVC::isInitialized())
     return;
   HRESULT hr = S_OK;
   Ptr<IKsTopologyInfo> ksTopologyInfo;
   void *p;
   if ((hr = _uvcPrivate->getCaptureFilter()->QueryInterface(__uuidof(IKsTopologyInfo), &p)) != S_OK)
   {
     logger(LOG_ERROR) << "UVCXU: Could not get IksTopologyInfo structure associated with video input device '" << usb->id() << "'" << std::endl;
     return;
   }
   ksTopologyInfo = Ptr<IKsTopologyInfo>((IKsTopologyInfo *)p, [](IKsTopologyInfo *d) { d->Release(); });
   // Retrieve the number of nodes in the filter
   DWORD numNodes = 0;
   if ((hr = ksTopologyInfo->get_NumNodes(&numNodes)) != S_OK || numNodes == 0)
   {
     logger(LOG_ERROR) << "UVCXU: Could not get number of nodes in the given IKsTopologyInfo for video input device '" << usb->id() << "'" << std::endl;
     return;
   }
   // Find the extension unit node that corresponds to the given GUID
   GUID guidNodeType;
   KSP_NODE ExtensionProp;
   ULONG bytesReturned = 0;
   for (unsigned int i = 0; i < numNodes; i++)
   {
     ksTopologyInfo->get_NodeType(i, &guidNodeType);
     if (IsEqualGUID(guidNodeType, KSNODETYPE_DEV_SPECIFIC))
     {
       if ((hr = ksTopologyInfo->CreateNodeInstance(i, IID_IKsControl, (void **)&p)) == S_OK)
       {
         ExtensionProp.Property.Set = PROPSETID_FX2_XU; // FIXME: This seems to be specific to Voxel-14. Need to handle this separately
         ExtensionProp.Property.Id = 0;
         ExtensionProp.Property.Flags = KSPROPERTY_TYPE_SETSUPPORT | KSPROPERTY_TYPE_TOPOLOGY;
         ExtensionProp.NodeId = i;
         ExtensionProp.Reserved = 0;
         if ((hr = ((IKsControl *)p)->KsProperty((PKSPROPERTY)&ExtensionProp, sizeof(ExtensionProp), NULL, 0, &bytesReturned)) != S_OK)
         {
           ((IKsControl *)p)->Release();
           continue;
         }
         _uvcXUPrivate->ksControl = Ptr<IKsControl>((IKsControl *)p, [](IKsControl *d) { d->Release(); }); // Removed d->Release(); from delete function, to avoid a crash
         _xuID = i;
         break;
       }
     }
   }
   if (!_uvcXUPrivate->ksControl)
   {
     logger(LOG_ERROR) << "UVCXU: Could not get IKsControl instance associated with video input device '" << usb->id() << "'" << std::endl;
     return;
   }
   std::this_thread::sleep_for(std::chrono::milliseconds(100)); // Wait for the device to get ready
 #endif
 }
Voxel::UVCXU::~UVCXU () virtual
Definition at line 125 of file UVCXU.cpp.
 {}
Member Function Documentation
bool Voxel::UVCXU::getControl (int controlnumber, int size, uint8_t * value)
Definition at line 127 of file UVCXU.cpp.
References Voxel::UVC::_usb, _uvcXUPrivate, _xuID, Voxel::UVC::getUVCPrivate(), isInitialized(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, and Voxel::UVCPrivate::xioctl().
 {
   if(!isInitialized())
     return false;
 #ifdef LINUX
   struct uvc_xu_control_query uvc;
   memset(&uvc, 0, sizeof(uvc));
   logger(LOG_DEBUG) << "UVCXU: get control " << controlnumber << ", size " << size << ", value[0] 0x" << std::hex << (uint)value[0] << std::endl;
   uvc.unit = _xuID;
   uvc.selector = controlnumber;
   uvc.query = UVC_GET_CUR;
   uvc.size = size;
   uvc.data = value;
   if (getUVCPrivate().xioctl(UVCIOC_CTRL_QUERY, &uvc) == -1)
   {
     logger(LOG_ERROR) << "UVCXU: " << _usb->id() << " UVCIOC_CTRL_QUERY failed.\n";
     return false;
   }
 #elif defined(WINDOWS)
   KSP_NODE ExtensionProp;
   ULONG bytesReturned = 0;
   HRESULT hr;
   ExtensionProp.Property.Set = PROPSETID_FX2_XU;
   ExtensionProp.Property.Id = controlnumber;
   ExtensionProp.Property.Flags = KSPROPERTY_TYPE_GET | KSPROPERTY_TYPE_TOPOLOGY;
   ExtensionProp.NodeId = _xuID;
   if ((hr = _uvcXUPrivate->ksControl->KsProperty((PKSPROPERTY)&ExtensionProp, sizeof(ExtensionProp), (PVOID)value, size, &bytesReturned)) != S_OK)
   {
     logger(LOG_ERROR) << "UVCXU: " << _usb->id() << " KsProperty query failed. Error: " << _com_error(hr).ErrorMessage() << std::endl;
     return false;
   }
   if (bytesReturned != size)
   {
     logger(LOG_ERROR) << "UVCXU: " << _usb->id() << " KsProperty query returned only " << bytesReturned << " bytes, but expected " << size << " bytes." << std::endl;
     return false;
   }
 #endif
   return true;
 }
bool Voxel::UVCXU::isInitialized () virtual
Reimplemented from Voxel::UVC.
Definition at line 116 of file UVCXU.cpp.
References _uvcXUPrivate, and Voxel::UVC::isInitialized().
Referenced by getControl(), and setControl().
 {
   return UVC::isInitialized()
 #ifdef WINDOWS
     && _uvcXUPrivate->ksControl
 #endif
     ;
 }
bool Voxel::UVCXU::setControl (int controlnumber, int size, uint8_t * value)
Definition at line 176 of file UVCXU.cpp.
References Voxel::UVC::_usb, _uvcXUPrivate, _xuID, Voxel::UVC::getUVCPrivate(), isInitialized(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, and Voxel::UVCPrivate::xioctl().
 {
   if(!isInitialized())
     return false;
 #ifdef LINUX
   struct uvc_xu_control_query uvc;
   memset(&uvc, 0, sizeof(uvc));
   logger(LOG_DEBUG) << "UVCXU: set control " << controlnumber << ", size " << size << ", value[0] 0x" << std::hex << (uint)value[0] << std::endl;
   uvc.unit = _xuID;
   uvc.selector = controlnumber;
   uvc.query = UVC_SET_CUR;
   uvc.size = size;
   uvc.data = value;
   if (getUVCPrivate().xioctl(UVCIOC_CTRL_QUERY, &uvc) == -1)
   {
     logger(LOG_ERROR) << "UVCXU: " << _usb->id() << " UVCIOC_CTRL_QUERY failed.\n";
     return false;
   }
 #elif defined(WINDOWS)
   KSP_NODE ExtensionProp;
   ULONG bytesReturned = 0;
   ExtensionProp.Property.Set = PROPSETID_FX2_XU;
   ExtensionProp.Property.Id = controlnumber;
   ExtensionProp.Property.Flags = KSPROPERTY_TYPE_SET | KSPROPERTY_TYPE_TOPOLOGY;
   ExtensionProp.NodeId = _xuID;
   if (_uvcXUPrivate->ksControl->KsProperty((PKSPROPERTY)&ExtensionProp, sizeof(ExtensionProp), (PVOID)value, size, &bytesReturned) != S_OK)
   {
     logger(LOG_ERROR) << "UVCXU: " << _usb->id() << " KsProperty query failed." << std::endl;
     return false;
   }
 #endif
   return true;
 }
Member Data Documentation
Ptr<UVCXUPrivate> Voxel::UVCXU::_uvcXUPrivate protected
Definition at line 26 of file UVCXU.h.
Referenced by getControl(), isInitialized(), setControl(), and UVCXU().
int Voxel::UVCXU::_xuID protected
Definition at line 23 of file UVCXU.h.
Referenced by getControl(), setControl(), and UVCXU().
class VOXEL_NO_EXPORT Voxel::UVCXU::UVCXUPrivate protected
Definition at line 25 of file UVCXU.h.
The documentation for this class was generated from the following files:
UVCXU.h
UVCXU.cpp