Voxel: Voxel::Streamer Class Reference
Voxel::Streamer Class Reference abstract
I/O classes
#include <Streamer.h>
Public Member Functions
Streamer (DevicePtr device)
virtual ~Streamer ()
virtual bool isInitialized ()=0
virtual bool isRunning ()
virtual bool start ()
virtual bool capture (RawDataFramePtr &p)
virtual bool stop ()
virtual bool getSupportedVideoModes (Vector< VideoMode > &videoModes)=0
virtual bool getCurrentVideoMode (VideoMode &videoMode)=0
virtual bool setVideoMode (const VideoMode &videoMode)=0
Protected Member Functions
virtual bool _start ()=0
virtual bool _capture (RawDataFramePtr &p)=0
virtual bool _stop ()=0
Protected Attributes
DevicePtr _device
Timer _time
int _currentID = -1
TimeStampType _currentTimeStamp = 0
bool _isRunning = false
Detailed Description
Definition at line 23 of file Streamer.h.
Constructor & Destructor Documentation
Voxel::Streamer::Streamer (DevicePtr device) inline
Definition at line 40 of file Streamer.h.
 : _device(device) {}
Voxel::Streamer::~Streamer () virtual
Definition at line 44 of file Streamer.cpp.
 {
 }
Member Function Documentation
virtual bool Voxel::Streamer::_capture (RawDataFramePtr & p) protected pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
Referenced by capture().
virtual bool Voxel::Streamer::_start () protected pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
Referenced by start().
virtual bool Voxel::Streamer::_stop () protected pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
Referenced by stop().
bool Voxel::Streamer::capture (RawDataFramePtr & p) virtual
Definition at line 22 of file Streamer.cpp.
References _capture(), isInitialized(), and isRunning().
Referenced by main().
 {
   if(!isInitialized() || !isRunning() || !_capture(p))
     return false;
   return true;
 }
virtual bool Voxel::Streamer::getCurrentVideoMode (VideoMode & videoMode) pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
virtual bool Voxel::Streamer::getSupportedVideoModes (Vector< VideoMode > & videoModes) pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
virtual bool Voxel::Streamer::isInitialized () pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
Referenced by capture(), start(), and stop().
virtual bool Voxel::Streamer::isRunning () inline virtual
Definition at line 45 of file Streamer.h.
Referenced by capture(), Voxel::UVCStreamer::setVideoMode(), stop(), and Voxel::UVCStreamer::~UVCStreamer().
 { return _isRunning; }
virtual bool Voxel::Streamer::setVideoMode (const VideoMode & videoMode) pure virtual
Implemented in Voxel::UVCStreamer, and Voxel::USBBulkStreamer.
bool Voxel::Streamer::start () virtual
Definition at line 12 of file Streamer.cpp.
References _currentID, _isRunning, _start(), and isInitialized().
Referenced by main().
 {
   if(!isInitialized() || !_start())
     return false;
   _currentID = 0;
   return _isRunning = true;
 }
bool Voxel::Streamer::stop () virtual
Definition at line 31 of file Streamer.cpp.
References _isRunning, _stop(), isInitialized(), and isRunning().
Referenced by main(), and Voxel::UVCStreamer::~UVCStreamer().
 {
   if(!isInitialized() || !isRunning())
     return false;
   _isRunning = false;
   if(!_stop())
     return false;
   return true;
 }
Member Data Documentation
int Voxel::Streamer::_currentID = -1 protected
Definition at line 30 of file Streamer.h.
Referenced by Voxel::USBBulkStreamer::_capture(), Voxel::UVCStreamer::_capture(), and start().
TimeStampType Voxel::Streamer::_currentTimeStamp = 0 protected
Definition at line 31 of file Streamer.h.
DevicePtr Voxel::Streamer::_device protected
Definition at line 26 of file Streamer.h.
Referenced by Voxel::UVCStreamer::_initForCapture(), Voxel::UVCStreamer::_start(), and Voxel::UVCStreamer::_uvcInit().
bool Voxel::Streamer::_isRunning = false protected
Definition at line 33 of file Streamer.h.
Referenced by start(), and stop().
Timer Voxel::Streamer::_time protected
Definition at line 28 of file Streamer.h.
Referenced by Voxel::UVCStreamer::_capture().
The documentation for this class was generated from the following files:
Streamer.h
Streamer.cpp