Voxel: Voxel::TI::CalculusVCOFrequency Class Reference
Voxel::TI::CalculusVCOFrequency Class Reference
Public Member Functions
CalculusVCOFrequency (ToFCalculusCamera &depthCamera, RegisterProgrammer &programmer)
virtual bool get (float &value, bool refresh=false)
virtual bool set (const float &value)
virtual ~CalculusVCOFrequency ()
Public Member Functions inherited from Voxel::FloatParameter
FloatParameter (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, float lowerLimit, float upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual ~FloatParameter ()
Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &lowerLimit, const float &upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const float lowerLimit () const
virtual const float upperLimit () const
virtual void setLowerLimit (floatlowerLimit)
virtual void setUpperLimit (floatupperLimit)
virtual bool validate (const float &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< float >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool refresh ()
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFCalculusCamera & _tofCalculusCamera
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::FloatParameter
static Ptr< FloatParameter > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
static Ptr
< RangeParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< float >
static Ptr< ParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::FloatParameter
virtual float _fromRawValue (uint32_t value) const
virtual uint32_t _toRawValue (float value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< float >
float _lowerLimit
float _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< float >
float _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Definition at line 114 of file ToFCalculusCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::CalculusVCOFrequency::CalculusVCOFrequency (ToFCalculusCamera & depthCamera, RegisterProgrammer & programmer) inline
Definition at line 118 of file ToFCalculusCamera.cpp.
References MOD_M, and MOD_N.
                                                                                       :
   FloatParameter(programmer, VCO_FREQ, "MHz", 0, 0, 0, 1, 600, 1300, 864, "VCO frequency",
                  "Frequency of the VCO used for generating modulation frequencies", IOType::IO_READ_WRITE, {MOD_M, MOD_N}), _tofCalculusCamera(depthCamera) {}
virtual Voxel::TI::CalculusVCOFrequency::~CalculusVCOFrequency () inline virtual
Definition at line 176 of file ToFCalculusCamera.cpp.
 {}
Member Function Documentation
virtual bool Voxel::TI::CalculusVCOFrequency::get (float & value, bool refresh = false) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 122 of file ToFCalculusCamera.cpp.
References Voxel::DepthCamera::_get(), _tofCalculusCamera, MOD_M, MOD_N, Voxel::ParameterTemplate< float >::refresh(), and Voxel::RangeParameterTemplate< float >::validate().
Referenced by Voxel::TI::CalculusModulationFrequencyParameter::set().
   {
     int modN;
     uint modM, systemClockFrequency;
 #if 0
     if(!_tofCalculusCamera._get(MOD_M, modM, refresh) || !_tofCalculusCamera._get(MOD_N, modN, refresh))
       return false;
     if(modN == 0)
       return false;
     float v = systemClockFrequency*modM/modN;
     if(!validate(v))
       return false;
     value = v;
 #endif
     value = 1300;
     return true;
   }
virtual bool Voxel::TI::CalculusVCOFrequency::set (const float & value) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 144 of file ToFCalculusCamera.cpp.
References Voxel::TI::ToFCalculusCamera::_getSystemClockFrequency(), Voxel::DepthCamera::_set(), _tofCalculusCamera, Voxel::ParameterTemplate< float >::_value, MOD_M, MOD_N, MOD_PLL_UPDATE, and Voxel::RangeParameterTemplate< float >::validate().
Referenced by Voxel::TI::CalculusModulationFrequencyParameter::set().
   {
     if(!validate(value))
       return false;
 #if 0
     if(!_tofCalculusCamera._set(MOD_PLL_UPDATE, true))
       return false;
     ParameterPtr pllUpdate(nullptr, [this](Parameter *) { _tofCalculusCamera._set(MOD_PLL_UPDATE, false); }); // Set PLL update to false when going out of scope of this function
     int modN;
     uint modM, systemClockFrequency;
     if(!_tofCalculusCamera._getSystemClockFrequency(systemClockFrequency))
       return false;
     modN = 18;
     if(systemClockFrequency == 0)
       return false;
     modM = value*modN/systemClockFrequency;
     if(!_tofCalculusCamera._set(MOD_M, modM) || !_tofCalculusCamera._set(MOD_N, modN))
       return false;
     _value = modM*systemClockFrequency/modN;
 #endif
     return true;
   }
Member Data Documentation
ToFCalculusCamera& Voxel::TI::CalculusVCOFrequency::_tofCalculusCamera private
Definition at line 116 of file ToFCalculusCamera.cpp.
Referenced by get(), and set().
The documentation for this class was generated from the following file:
ToFCalculusCamera.cpp