Voxel: Voxel::TI::TintinCDKCamera Class Reference
Voxel::TI::TintinCDKCamera Class Reference
#include <TintinCDKCamera.h>
Public Member Functions
TintinCDKCamera (DevicePtr device)
virtual ~TintinCDKCamera ()
Public Member Functions inherited from Voxel::TI::ToFTintinCamera
ToFTintinCamera (const String &name, DevicePtr device)
virtual bool _getMaximumFrameSize (FrameSize &s) const
virtual ~ToFTintinCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (int &id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _getFieldOfView (float &fovHalfAngle) const
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
virtual bool _setStreamerFrameSize (const FrameSize &s)
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _initStartParams ()
virtual bool _readConfigFromHardware (MainConfigurationFile::ConfigSerialNumberType &serialNumber, TimeStampType &knownTimestamp, Voxel::SerializedObject &so)
virtual bool _writeConfigFromHardware (MainConfigurationFile::ConfigSerialNumberType &serialNumber, TimeStampType &timestamp, SerializedObject &so)
virtual bool _getEEPROMSize (uint32_t &size)
Protected Member Functions inherited from Voxel::TI::ToFTintinCamera
bool _init ()
virtual bool _getIlluminationFrequency (float &frequency) const
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _getFrameSize (FrameSize &s) const
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _getDealiasedPhaseMask (int &dealiasedPhaseMask)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Protected Attributes
Ptr< Downloader > _downloader
uint8_t _boardRevision [2]
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Detailed Description
Definition at line 35 of file TintinCDKCamera.h.
Constructor & Destructor Documentation
Voxel::TI::TintinCDKCamera::TintinCDKCamera (Voxel::DevicePtr device)
Definition at line 27 of file TintinCDKCamera.cpp.
References _init().
                                                      : ToFTintinCamera("TintinCDKCamera", device)
 {
   _init();
 }
virtual Voxel::TI::TintinCDKCamera::~TintinCDKCamera () inline virtual
Definition at line 61 of file TintinCDKCamera.h.
 {}
Member Function Documentation
bool Voxel::TI::TintinCDKCamera::_getEEPROMSize (uint32_t & size) protected virtual
Definition at line 589 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_programmer, Voxel::USBIO::FROM_DEVICE, Voxel::TI::VoxelUSBProgrammer::getUSBIO(), Voxel::LOG_ERROR, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, REQUEST_EEPROM_SIZE, and Voxel::USBIO::REQUEST_VENDOR.
Referenced by _readConfigFromHardware(), and _writeConfigFromHardware().
 {
   VoxelUSBProgrammer *p = dynamic_cast<VoxelUSBProgrammer *>(&*_programmer);
   if(p)
   {
     USBIOPtr usbIO = p->getUSBIO();
     uint8_t data[4];
     uint16_t length = 4;
     if(!usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       REQUEST_EEPROM_SIZE, 0, 0, data, length))
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Failed to read available size in EEPROM." << std::endl;
       return false;
     }
     size = *(uint32_t *)&data[0];
     return true;
   }
   else
     return false;
 }
bool Voxel::TI::TintinCDKCamera::_getFieldOfView (float & fovHalfAngle) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 453 of file TintinCDKCamera.cpp.
 {
   fovHalfAngle = (87/2.0f)*(M_PI/180.0f);
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_getMaximumFrameRate (FrameRate & frameRate, const FrameSize & forFrameSize) const protected virtual
Reimplemented from Voxel::TI::ToFCamera.
Definition at line 565 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_get(), Voxel::FrameRate::denominator, Voxel::gcd(), Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameRate::numerator, OP_CLK_FREQ, PIXEL_DATA_SIZE, and Voxel::FrameSize::width.
 {
   int opClockFrequency, bytesPerPixel;
   if(!_get(OP_CLK_FREQ, opClockFrequency) || !_get(PIXEL_DATA_SIZE, bytesPerPixel))
   {
     logger(LOG_ERROR) << "TintinCDKCamera: Could not get " << OP_CLK_FREQ << " or " << PIXEL_DATA_SIZE << std::endl;
     return false;
   }
   opClockFrequency = 24/(1 << opClockFrequency);
   uint numerator = opClockFrequency*1000000,
   denominator = bytesPerPixel*forFrameSize.width*forFrameSize.height;
   uint g = gcd(numerator, denominator);
   frameRate.numerator = 0.8*numerator/g; // 90% of maximum
   frameRate.denominator = denominator/g;
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_getMaximumVideoMode (VideoMode & videoMode) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 543 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_device, Voxel::DepthCamera::_get(), Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameRate::numerator, PIXEL_DATA_SIZE, Voxel::USBDevice::productID(), TINTIN_CDK_PRODUCT_UVC, and Voxel::FrameSize::width.
 {
   int bytesPerPixel;
   USBDevice &d = (USBDevice &)*_device;
   if(!_get(PIXEL_DATA_SIZE, bytesPerPixel))
   {
     logger(LOG_ERROR) << "TintinCDKCamera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   videoMode.frameSize.width = 320;
   videoMode.frameSize.height = 240;
   videoMode.frameRate.denominator = 1;
   if (d.productID() == TINTIN_CDK_PRODUCT_UVC) {
     videoMode.frameRate.numerator = (bytesPerPixel == 4)?25:50;
   } else {
     videoMode.frameRate.numerator = 60;
   }
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_getSupportedVideoModes (Vector< SupportedVideoMode > & supportedVideoModes) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 516 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_device, Voxel::USBDevice::productID(), and TINTIN_CDK_PRODUCT_UVC.
 {
   USBDevice &d = (USBDevice &)*_device;
   if (d.productID() == TINTIN_CDK_PRODUCT_UVC)
   {
     supportedVideoModes = Vector<SupportedVideoMode> {
       SupportedVideoMode(320,240,25,1,4),
       SupportedVideoMode(160,240,50,1,4),
       SupportedVideoMode(160,120,100,1,4),
       SupportedVideoMode(80,120,200,1,4),
       SupportedVideoMode(80,60,400,1,4),
       SupportedVideoMode(320,240,50,1,2),
       SupportedVideoMode(320,120,100,1,2),
       SupportedVideoMode(160,120,200,1,2),
       SupportedVideoMode(160,60,400,1,2),
       SupportedVideoMode(80,60,400,1,2),
     };
   }
   else
   {
     supportedVideoModes.clear();
   }
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_init () protected
Definition at line 310 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_addParameters(), _boardRevision, Voxel::DepthCamera::_device, Voxel::TI::ToFTintinCamera::_init(), Voxel::DepthCamera::_parameters, Voxel::DepthCamera::_programmer, _readConfigFromHardware(), Voxel::DepthCamera::_streamer, _writeConfigFromHardware(), COMP_VREF, Voxel::DepthCamera::configFile, DELAY_FB_CORR_MODE, DELAY_FB_DC_CORR_MODE, Voxel::USBIO::FROM_DEVICE, Voxel::DepthCamera::getParam(), ILLUM_DC_CORR, ILLUM_DC_CORR_DIR, INTG_DUTY_CYCLE, INTG_TIME, Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, LUMPED_DEAD_TIME, PIX_CNT_MAX, Voxel::USBDevice::productID(), Voxel::USBIO::RECIPIENT_DEVICE, Voxel::USBIO::REQUEST_VENDOR, Voxel::DepthCamera::set(), Voxel::MainConfigurationFile::setHardwareReader(), Voxel::MainConfigurationFile::setHardwareWriter(), TINTIN_CDK_PRODUCT_UVC, and TINTIN_CDK_USBIO_BOARD_REVISION.
Referenced by TintinCDKCamera().
 {
   USBDevice &d = (USBDevice &)*_device;
   DevicePtr controlDevice = _device;
   if (d.productID() == TINTIN_CDK_PRODUCT_UVC)
   {
     _programmer = Ptr<RegisterProgrammer>(new VoxelXUProgrammer(
       { {0x2D, 1}, {0x52, 1}, {0x54, 1}, {0x4B, 2}, {0x4E, 2}, {0x58, 3}, {0x5C, 3} },
       controlDevice));
     _streamer = Ptr<Streamer>(new UVCStreamer(controlDevice));
     _boardRevision[0] = _boardRevision[1] = 0;
   }
   else
   {
     USBIOPtr usbIO(new USBIO(controlDevice));
     _programmer = Ptr<RegisterProgrammer>(new VoxelUSBProgrammer(
       { {0x2D, 1}, {0x52, 1}, {0x54, 1}, {0x4B, 2}, {0x4E, 2}, {0x58, 3}, {0x5C, 3} },
       {
         {0x58, {0x08, 0x09, 0}},
         {0x5C, {0x08, 0x09, 0}},
         {0x4B, {0x0A, 0x0B, 0}},
         {0x4E, {0x0A, 0x0B, 0}},
         {0x2D, {0x04, 0x03, 8}},
         {0x52, {0x04, 0x03, 8}},
         {0x54, {0x04, 0x03, 8}}
       }, usbIO, controlDevice));
     _streamer = Ptr<Streamer>(new USBBulkStreamer(usbIO, controlDevice, 0x82));
     uint16_t length = 2;
     if(!usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, TINTIN_CDK_USBIO_BOARD_REVISION, 0, 0, _boardRevision, length))
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Failed to get board revision" << std::endl;
       return false;
     }
     logger(LOG_INFO) << "TintinCDKCamera: Board revision = " << (int)_boardRevision[0] << "." << (int)_boardRevision[1] << std::endl;
   }
   if(!_programmer->isInitialized() || !_streamer->isInitialized())
     return false;
   /* TPL0102 - remove non-volatile access */
   if (!_programmer->writeRegister(0x5410, 0xC0))
     return false;
   if(!_addParameters({
     ParameterPtr(new TintinCDKMixVoltageParameter(*_programmer)),
     ParameterPtr(new TintinCDKIllumVrefParameter(*_programmer)),
     ParameterPtr(new TintinCDKMainCurrentParameter(*_programmer)),
     ParameterPtr(new TintinCDKIllumCurrentParameter(*_programmer)),
     ParameterPtr(new TintinCDKIlluminationPowerParameter(*_programmer)),
     ParameterPtr(new TintinCDKIlluminationPowerPercentParameter(*this, *_programmer)),
     }))
   {
     return false;
   }
   if ((int) _boardRevision[0] == 1) {
     if (!_addParameters({ParameterPtr(new TintinCDKPVDDParameterRev1(*_programmer)),}))
       return false;
   } else {
     if (!_addParameters({ParameterPtr(new TintinCDKPVDDParameterRev2(*_programmer)),}))
       return false;
   }
   /* INA226 initializations: note byteswapped for now */
   if (!_programmer->writeRegister(0x4B00, 0x274F) ||
     !_programmer->writeRegister(0x4E00, 0x274F) ||
     !_programmer->writeRegister(0x4B05, 0x4807) ||
     !_programmer->writeRegister(0x4E05, 0x4F1B)
   )
     return false;
   configFile.setHardwareReader(std::bind(&TintinCDKCamera::_readConfigFromHardware, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
   configFile.setHardwareWriter(std::bind(&TintinCDKCamera::_writeConfigFromHardware, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
   if(!ToFTintinCamera::_init())
     return false;
   Ptr<UnsignedIntegerParameter> pixCntMax = std::dynamic_pointer_cast<UnsignedIntegerParameter>(getParam(PIX_CNT_MAX));
   if(pixCntMax)
     pixCntMax->setLowerLimit(50000);
   Ptr<UnsignedIntegerParameter> intgDutyCycle = std::dynamic_pointer_cast<UnsignedIntegerParameter>(getParam(INTG_DUTY_CYCLE));
   if (intgDutyCycle)
     intgDutyCycle->setUpperLimit(30);
   Ptr<UnsignedIntegerParameter> intgTime = std::dynamic_pointer_cast<UnsignedIntegerParameter>(getParam(INTG_TIME));
   if (intgTime)
     intgTime->setUpperLimit(46);
   _parameters.erase(LUMPED_DEAD_TIME);
   _parameters.erase(ILLUM_DC_CORR);
   _parameters.erase(ILLUM_DC_CORR_DIR);
   /*
    * On the first revision of boards, these two parameters should not be set;
    * but we would like to keep a single set of calibration conf files for
    * both revisions of the board.
    * So use dummy parameters for now that mask the register writes till we find
    * a more elegant solution.
    */
   if ((int) _boardRevision[0] == 1) {
     _parameters.erase(DELAY_FB_CORR_MODE);
     _parameters.erase(DELAY_FB_DC_CORR_MODE);
     if (!_addParameters({ParameterPtr(new TintinCDKDummyDelayFBCorrModeParameter(*_programmer)),}))
       return false;
     if (!_addParameters({ParameterPtr(new TintinCDKDummyDelayFBDCCorrModeParameter(*_programmer)),}))
       return false;
   }
   if (!set(COMP_VREF, 1405U))
     return false;
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_initStartParams () protected virtual
Reimplemented from Voxel::TI::ToFTintinCamera.
Definition at line 435 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_device, Voxel::TI::ToFTintinCamera::_initStartParams(), BLK_HEADER_EN, Voxel::USBDevice::productID(), Voxel::DepthCamera::set(), TILLUM_SLAVE_ADDR, and TINTIN_CDK_PRODUCT_BULK.
 {
   USBDevice &d = (USBDevice &)*_device;
   if(!ToFTintinCamera::_initStartParams())
     return false;
   if (!set(TILLUM_SLAVE_ADDR, 0x72U))
     return false;
   if ((d.productID() == TINTIN_CDK_PRODUCT_BULK) && !set(BLK_HEADER_EN, false))
     return false;
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_readConfigFromHardware (MainConfigurationFile::ConfigSerialNumberType & serialNumber, TimeStampType & knownTimestamp, Voxel::SerializedObject & so) protected virtual
Definition at line 615 of file TintinCDKCamera.cpp.
References _getEEPROMSize(), Voxel::DepthCamera::_programmer, Voxel::USBIO::FROM_DEVICE, Voxel::SerializedObject::getBytes(), Voxel::Timer::getCurentRealTime(), Voxel::TI::VoxelUSBProgrammer::getUSBIO(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::USBIO::RECIPIENT_DEVICE, REQUEST_EEPROM_DATA, Voxel::USBIO::REQUEST_VENDOR, Voxel::SerializedObject::resize(), and Voxel::SerializedObject::size().
Referenced by _init().
 {
   VoxelUSBProgrammer *p = dynamic_cast<VoxelUSBProgrammer *>(&*_programmer);
   if(p)
   {
     Timer t;
     TimeStampType d = t.getCurentRealTime();
     USBIOPtr usbIO = p->getUSBIO();
     uint8_t data[9 + 2 + sizeof(TimeStampType)];
     uint16_t l = sizeof(data);
     if(!usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE, REQUEST_EEPROM_DATA, 0, 0, data, l))
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Failed to read config size in EEPROM." << std::endl;
       return false;
     }
     if(data[0] != 'V' || data[1] != 'O' || data[2] != 'X' || data[3] != 'E' || data[4] != 'L')
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Invalid config data in EEPROM." << std::endl;
       return false;
     }
     // Ignoring the version info for now
     //std::cout << "Timestamp in hardware = " << *(TimeStampType *)&data[7] << ", expected = " << knownTimestamp << std::endl;
     if(*(TimeStampType *)&data[7] == knownTimestamp)
     {
       so.resize(0);
       return true;
     }
     int32_t length = *(uint32_t *)&data[7 + sizeof(TimeStampType)];
     uint32_t totalSize;
     if(!_getEEPROMSize(totalSize))
       return false;
     if(length > totalSize)
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Length of config data is greater than available size in EEPROM. ("
         << length << " > " << totalSize << ")" << std::endl;
       return false;
     }
     so.resize(length);
     uint32_t offset = l, localOffset = 0;
     const uint32_t maxTransferLength = 4096;
     while(length > 0)
     {
       l = length;
       if(l > maxTransferLength) l = maxTransferLength;
       //std::cout << "l = " << l << std::endl;
       uint16_t offsetLower = (offset & 0xFFFF);
       uint16_t offsetUpper = (offset >> 16);
       if(!usbIO->controlTransfer(USBIO::FROM_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
         REQUEST_EEPROM_DATA, offsetUpper, offsetLower, (uint8_t *)so.getBytes().data() + localOffset, l) || l == 0)
       {
         logger(LOG_ERROR) << "TintinCDKCamera: Failed to read config data from EEPROM." << std::endl;
         return false;
       }
       length -= l;
       offset += l;
       localOffset += l;
     }
     logger(LOG_INFO) << "TintinCDKCamera: Received " << so.size() << " bytes from EEPROM in " << (t.getCurentRealTime() - d)*1E-6 << " s" << std::endl;
     return true;
   }
   else
     return false;
 }
bool Voxel::TI::TintinCDKCamera::_setStreamerFrameSize (const FrameSize & s) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 459 of file TintinCDKCamera.cpp.
References Voxel::DepthCamera::_device, Voxel::DepthCamera::_get(), Voxel::TI::ToFCamera::_getFrameRate(), Voxel::DepthCamera::_streamer, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, PIXEL_DATA_SIZE, Voxel::USBDevice::productID(), Voxel::USBBulkStreamer::setBufferSize(), Voxel::UVCStreamer::setVideoMode(), TINTIN_CDK_PRODUCT_BULK, TINTIN_CDK_PRODUCT_UVC, and Voxel::FrameSize::width.
 {
   UVCStreamer *uvcStreamer = dynamic_cast<UVCStreamer *>(&*_streamer);
   USBBulkStreamer *bulkStreamer = dynamic_cast<USBBulkStreamer *>(&*_streamer);
   USBDevice &d = (USBDevice &)*_device;
   VideoMode m;
   m.frameSize = s;
   int bytesPerPixel;
   if(!_get(PIXEL_DATA_SIZE, bytesPerPixel))
   {
     logger(LOG_ERROR) << "TintinCDKCamera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   if(!_getFrameRate(m.frameRate))
   {
     logger(LOG_ERROR) << "TintinCDKCamera: Could not get current frame rate" << std::endl;
     return false;
   }
   if ((d.productID() == TINTIN_CDK_PRODUCT_UVC))
   {
     if(bytesPerPixel == 4)
       m.frameSize.width *= 2;
     if (!uvcStreamer)
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Streamer is not of type UVC" << std::endl;
       return false;
     }
     if(!uvcStreamer->setVideoMode(m))
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Could not set video mode for UVC" << std::endl;
       return false;
     }
   }
   else if ((d.productID() == TINTIN_CDK_PRODUCT_BULK))
   {
     if (!bulkStreamer)
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Streamer is not of type Bulk" << std::endl;
       return false;
     }
     if (!bulkStreamer->setBufferSize(s.width * s.height * bytesPerPixel))
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Could not set buffer size for bulk transfer" << std::endl;
       return false;
     }
   }
   return true;
 }
bool Voxel::TI::TintinCDKCamera::_writeConfigFromHardware (MainConfigurationFile::ConfigSerialNumberType & serialNumber, Voxel::TimeStampType & timestamp, Voxel::SerializedObject & so) protected virtual
Definition at line 703 of file TintinCDKCamera.cpp.
References _getEEPROMSize(), Voxel::DepthCamera::_programmer, Voxel::SerializedObject::getBytes(), Voxel::Timer::getCurentRealTime(), Voxel::TI::VoxelUSBProgrammer::getUSBIO(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::MainConfigurationFile::ConfigSerialNumberType::major, Voxel::MainConfigurationFile::ConfigSerialNumberType::minor, Voxel::USBIO::RECIPIENT_DEVICE, REQUEST_EEPROM_DATA, Voxel::USBIO::REQUEST_VENDOR, Voxel::SerializedObject::size(), and Voxel::USBIO::TO_DEVICE.
Referenced by _init().
 {
   VoxelUSBProgrammer *p = dynamic_cast<VoxelUSBProgrammer *>(&*_programmer);
   if(p)
   {
     Timer t;
     TimeStampType d = t.getCurentRealTime();
     USBIOPtr usbIO = p->getUSBIO();
     int32_t length = so.size();
     uint32_t totalSize;
     if(!_getEEPROMSize(totalSize))
       return false;
     if(length + 9 > totalSize)
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Length of config data is greater than available size in EEPROM. ("
       << length + 9 << " > " << totalSize << ")" << std::endl;
       return false;
     }
     logger(LOG_INFO) << "TintinCDKCamera: Length of data to EEPROM = " << length << std::endl;
     uint8_t data[9 + 2 + sizeof(TimeStampType)];
     data[0] = 'V';
     data[1] = 'O';
     data[2] = 'X';
     data[3] = 'E';
     data[4] = 'L';
     data[5] = serialNumber.major;
     data[6] = serialNumber.minor;
     *(TimeStampType *)&data[7] = timestamp;
     *(uint32_t *)&data[7 + sizeof(TimeStampType)] = so.size();
     uint16_t l = sizeof(data);
     if(!usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
       REQUEST_EEPROM_DATA, 0, 0, data, l))
     {
       logger(LOG_ERROR) << "TintinCDKCamera: Failed to read config size in EEPROM." << std::endl;
       return false;
     }
     uint32_t offset = l, localOffset = 0;
     while(length > 0)
     {
       logger(LOG_DEBUG) << "TintinCDKCamera: Transferred till offset = " << offset << std::endl;
       l = 64 - (offset % 64);
       if(l > length) l = length;
       uint16_t offsetLower = (offset & 0xFFFF);
       uint16_t offsetUpper = (offset >> 16);
       if(!usbIO->controlTransfer(USBIO::TO_DEVICE, USBIO::REQUEST_VENDOR, USBIO::RECIPIENT_DEVICE,
         REQUEST_EEPROM_DATA, offsetUpper, offsetLower, (uint8_t *)so.getBytes().data() + localOffset, l, false, 1000))
       {
         logger(LOG_ERROR) << "TintinCDKCamera: Failed to read config data from EEPROM." << std::endl;
         return false;
       }
       length -= l;
       offset += l;
       localOffset += l;
     }
     logger(LOG_INFO) << "TintinCDKCamera: Transferred " << so.size() << " bytes to EEPROM in " << (t.getCurentRealTime() - d)*1E-6 << " s" << std::endl;
     return true;
   }
   else
     return true; // Falsely accept write
 }
Member Data Documentation
uint8_t Voxel::TI::TintinCDKCamera::_boardRevision[2] protected
Definition at line 40 of file TintinCDKCamera.h.
Referenced by _init().
Ptr<Downloader> Voxel::TI::TintinCDKCamera::_downloader protected
Definition at line 38 of file TintinCDKCamera.h.
The documentation for this class was generated from the following files:
TintinCDKCamera.h
TintinCDKCamera.cpp