Voxel: ELFIO::section Class Reference
ELFIO::section Class Reference abstract
#include <elfio_section.hpp>
Public Member Functions
virtual ~section ()
ELFIO_GET_ACCESS_DECL (Elf_Half, index)
ELFIO_GET_SET_ACCESS_DECL (std::string, name)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, type)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, flags)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, info)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, link)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, addr_align)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, entry_size)
ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr, address)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, size)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, name_string_offset)
virtual const char * get_data () const =0
virtual void set_data (const char *pData, Elf_Word size)=0
virtual void set_data (const std::string &data)=0
virtual void append_data (const char *pData, Elf_Word size)=0
virtual void append_data (const std::string &data)=0
Protected Member Functions
ELFIO_GET_SET_ACCESS_DECL (Elf64_Off, offset)
ELFIO_SET_ACCESS_DECL (Elf_Half, index)
virtual void load (std::istream &f, std::streampos header_offset)=0
virtual void save (std::ostream &f, std::streampos header_offset, std::streampos data_offset)=0
virtual bool is_address_initialized () const =0
Friends
class elfio
Detailed Description
Definition at line 31 of file elfio_section.hpp.
Constructor & Destructor Documentation
virtual ELFIO::section::~section () inline virtual
Definition at line 35 of file elfio_section.hpp.
 {};
Member Function Documentation
virtual void ELFIO::section::append_data (const char * pData, Elf_Word size) pure virtual
Implemented in ELFIO::section_impl< T >.
Referenced by ELFIO::note_section_accessor::add_note(), ELFIO::string_section_accessor::add_string(), ELFIO::dynamic_section_accessor::generic_add_entry(), ELFIO::relocation_section_accessor::generic_add_entry(), and ELFIO::symbol_section_accessor::generic_add_symbol().
virtual void ELFIO::section::append_data (const std::string & data) pure virtual
Implemented in ELFIO::section_impl< T >.
ELFIO::section::ELFIO_GET_ACCESS_DECL (Elf_Half , index)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (std::string , name)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Word , type)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , flags)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Word , info)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Word , link)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , addr_align)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , entry_size)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr , address)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , size)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf_Word , name_string_offset)
ELFIO::section::ELFIO_GET_SET_ACCESS_DECL (Elf64_Off , offset) protected
ELFIO::section::ELFIO_SET_ACCESS_DECL (Elf_Half , index) protected
virtual const char* ELFIO::section::get_data () const pure virtual
Implemented in ELFIO::section_impl< T >.
Referenced by ELFIO::dynamic_section_accessor::generic_get_entry_dyn(), ELFIO::relocation_section_accessor::generic_get_entry_rel(), ELFIO::relocation_section_accessor::generic_get_entry_rela(), ELFIO::symbol_section_accessor::generic_get_symbol(), ELFIO::note_section_accessor::get_note(), ELFIO::string_section_accessor::get_string(), ELFIO::symbol_section_accessor::get_symbol(), ELFIO::note_section_accessor::process_section(), and ELFIO::dump::section_data().
virtual bool ELFIO::section::is_address_initialized () const protected pure virtual
Implemented in ELFIO::section_impl< T >.
Referenced by ELFIO::elfio::layout_segments_and_their_sections().
virtual void ELFIO::section::load (std::istream & f, std::streampos header_offset) protected pure virtual
Implemented in ELFIO::section_impl< T >.
Referenced by ELFIO::elfio::load_sections().
virtual void ELFIO::section::save (std::ostream & f, std::streampos header_offset, std::streampos data_offset) protected pure virtual
Implemented in ELFIO::section_impl< T >.
Referenced by ELFIO::elfio::save_sections().
virtual void ELFIO::section::set_data (const char * pData, Elf_Word size) pure virtual
Implemented in ELFIO::section_impl< T >.
virtual void ELFIO::section::set_data (const std::string & data) pure virtual
Implemented in ELFIO::section_impl< T >.
Friends And Related Function Documentation
friend class elfio friend
Definition at line 33 of file elfio_section.hpp.
The documentation for this class was generated from the following file:
elfio_section.hpp