Voxel: Voxel::TI::IntegrationTimeParameter Class Reference
Voxel::TI::IntegrationTimeParameter Class Reference
Public Member Functions
IntegrationTimeParameter (ToFCamera &depthCamera, RegisterProgrammer &programmer)
_depthCamera (depthCamera)
virtual bool get (uint &value, bool refresh=false)
virtual bool set (const uint &value)
Public Member Functions inherited from Voxel::RangeParameterTemplate< T >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &lowerLimit, const T &upperLimit, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const T lowerLimit () const
virtual const T upperLimit () const
virtual void setLowerLimit (T lowerLimit)
virtual void setUpperLimit (T upperLimit)
virtual bool validate (const T &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< T >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool set (const T &value)
virtual bool refresh ()
virtual bool get (T &value, bool refresh=false)
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFCamera & _depthCamera
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< T >
static Ptr
< RangeParameterTemplate< T > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< T >
static Ptr< ParameterTemplate
< T > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::ParameterTemplate< T >
virtual uint32_t _toRawValue (T value) const
virtual T _fromRawValue (uint32_t value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< T >
T _lowerLimit
T _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< T >
T _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Definition at line 21 of file ToFCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::IntegrationTimeParameter::IntegrationTimeParameter (ToFCamera & depthCamera, RegisterProgrammer & programmer) inline
Definition at line 25 of file ToFCamera.cpp.
                                                                                   :
   UnsignedIntegerParameter(programmer, INTG_TIME, "%", 0, 0, 0, 1, 0, 100, 0, "Integration time",
                 "Integration time as percentage of total cycle time", Parameter::IO_READ_WRITE, {INTG_DUTY_CYCLE}), _depthCamera(depthCamera) {}
Member Function Documentation
Voxel::TI::IntegrationTimeParameter::_depthCamera (depthCamera) inline
Definition at line 27 of file ToFCamera.cpp.
References INTG_DUTY_CYCLE.
 {INTG_DUTY_CYCLE}), _depthCamera(depthCamera) {}
virtual bool Voxel::TI::IntegrationTimeParameter::get (uint & value, bool refresh = false) inline virtual
Definition at line 30 of file ToFCamera.cpp.
References _depthCamera, Voxel::DepthCamera::_get(), INTG_DUTY_CYCLE, INTG_DUTY_CYCLE_SET_FAILED, and Voxel::ParameterTemplate< T >::refresh().
   {
     uint integrationDutyCycle;
     bool integrationDutyCycleSetFailed;
     if(!_depthCamera._get(INTG_DUTY_CYCLE, integrationDutyCycle, refresh) ||
       !_depthCamera._get(INTG_DUTY_CYCLE_SET_FAILED, integrationDutyCycleSetFailed, refresh)
       || integrationDutyCycleSetFailed)
       return false;
     uint v = (uint)((integrationDutyCycle*100.0)/64 + 0.5); // rounded value
     if(v > 100) v = 100;
     if(v < 0) v = 0;
     value = v;
     return true;
   }
virtual bool Voxel::TI::IntegrationTimeParameter::set (const uint & value) inline virtual
Definition at line 51 of file ToFCamera.cpp.
References _depthCamera, Voxel::DepthCamera::_get(), Voxel::DepthCamera::_set(), INTG_DUTY_CYCLE, INTG_DUTY_CYCLE_SET_FAILED, and Voxel::RangeParameterTemplate< T >::validate().
   {
     if(!validate(value))
       return false;
     uint integrationDutyCycle = (uint)((value*64.0/100) + 0.5); // rounded value
     if(integrationDutyCycle > 63) integrationDutyCycle = 63;
     if(!_depthCamera._set(INTG_DUTY_CYCLE, integrationDutyCycle))
       return false;
     bool integrationDutyCycleSetFailed;
     if(!_depthCamera._get(INTG_DUTY_CYCLE_SET_FAILED, integrationDutyCycleSetFailed)
       || integrationDutyCycleSetFailed)
       return false;
     return true;
   }
Member Data Documentation
ToFCamera& Voxel::TI::IntegrationTimeParameter::_depthCamera private
Definition at line 23 of file ToFCamera.cpp.
Referenced by get(), and set().
The documentation for this class was generated from the following file:
ToFCamera.cpp