Voxel: Voxel::TI::CalculusModulationFrequencyParameter Class Reference
Voxel::TI::CalculusModulationFrequencyParameter Class Reference
Public Member Functions
CalculusModulationFrequencyParameter (ToFCalculusCamera &depthCamera, RegisterProgrammer &programmer, const String &name, const String &psName)
_psName (psName)
_tofCalculusCamera (depthCamera)
virtual bool get (float &value, bool refresh=false)
virtual bool set (const float &value)
Public Member Functions inherited from Voxel::FloatParameter
FloatParameter (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, float lowerLimit, float upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual ~FloatParameter ()
Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
RangeParameterTemplate (RegisterProgrammer &programmer, const String &name, const String &unit, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &lowerLimit, const float &upperLimit, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const String & unit () const
virtual const float lowerLimit () const
virtual const float upperLimit () const
virtual void setLowerLimit (floatlowerLimit)
virtual void setUpperLimit (floatupperLimit)
virtual bool validate (const float &value) const
virtual ~RangeParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< float >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const float &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool refresh ()
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Private Attributes
ToFCalculusCamera & _tofCalculusCamera
String _psName
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Static Public Member Functions inherited from Voxel::FloatParameter
static Ptr< FloatParameter > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::RangeParameterTemplate< float >
static Ptr
< RangeParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< float >
static Ptr< ParameterTemplate
< float > > typeCast (const ParameterPtr &other)
Protected Member Functions inherited from Voxel::FloatParameter
virtual float _fromRawValue (uint32_t value) const
virtual uint32_t _toRawValue (float value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Protected Attributes inherited from Voxel::RangeParameterTemplate< float >
float _lowerLimit
float _upperLimit
String _unit
Protected Attributes inherited from Voxel::ParameterTemplate< float >
float _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Detailed Description
Definition at line 179 of file ToFCalculusCamera.cpp.
Constructor & Destructor Documentation
Voxel::TI::CalculusModulationFrequencyParameter::CalculusModulationFrequencyParameter (ToFCalculusCamera & depthCamera, RegisterProgrammer & programmer, const String & name, const String & psName) inline
Definition at line 184 of file ToFCalculusCamera.cpp.
                                                                                                                                                 :
   FloatParameter(programmer, name, "MHz", 0, 0, 0, 1, 6.25f, 433.333f, 18, "Modulation frequency", "Frequency used for modulation of illumination",
                  Parameter::IO_READ_WRITE, {psName}), _psName(psName), _tofCalculusCamera(depthCamera) {}
Member Function Documentation
Voxel::TI::CalculusModulationFrequencyParameter::_psName (psName)
Voxel::TI::CalculusModulationFrequencyParameter::_tofCalculusCamera (depthCamera) inline
Definition at line 186 of file ToFCalculusCamera.cpp.
 {psName}), _psName(psName), _tofCalculusCamera(depthCamera) {}
virtual bool Voxel::TI::CalculusModulationFrequencyParameter::get (float & value, bool refresh = false) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 188 of file ToFCalculusCamera.cpp.
References Voxel::DepthCamera::_get(), _psName, _tofCalculusCamera, Voxel::ParameterTemplate< float >::refresh(), Voxel::RangeParameterTemplate< float >::validate(), and VCO_FREQ.
   {
     float vcoFrequency;
     uint modulationPS;
 #if 0
     if(!_tofCalculusCamera._get(VCO_FREQ, vcoFrequency, refresh) || !_tofCalculusCamera._get(_psName, modulationPS, refresh))
       return false;
     float v = vcoFrequency/3/modulationPS;
     if(!validate(v))
       return false;
     value = v;
 #endif
     value = 19.2f;
     return true;
   }
virtual bool Voxel::TI::CalculusModulationFrequencyParameter::set (const float & value) inline virtual
Reimplemented from Voxel::ParameterTemplate< float >.
Definition at line 209 of file ToFCalculusCamera.cpp.
References _psName, Voxel::DepthCamera::_set(), _tofCalculusCamera, Voxel::TI::CalculusVCOFrequency::get(), Voxel::DepthCamera::getParam(), MOD_PLL_UPDATE, Voxel::TI::CalculusVCOFrequency::set(), Voxel::RangeParameterTemplate< T >::upperLimit(), Voxel::RangeParameterTemplate< float >::validate(), and VCO_FREQ.
   {
     if(!validate(value))
       return false;
 #if 0
     ParameterPtr p = _tofCalculusCamera.getParam(VCO_FREQ);
     if(!p)
       return false;
     CalculusVCOFrequency &v = (CalculusVCOFrequency &)*p;
     uint modulationPS = v.upperLimit()/3/value;
     if(!v.set(modulationPS*3*value))
       return false;
     if(!_tofCalculusCamera._set(MOD_PLL_UPDATE, true))
       return false;
     ParameterPtr pllUpdate(nullptr, [this](Parameter *) { _tofCalculusCamera._set(MOD_PLL_UPDATE, false); }); // Set PLL update to false when going out of scope of this function
     if(!_tofCalculusCamera._set(_psName, modulationPS))
       return false;
     float val;
     if(!v.get(val))
       return false;
 #endif
     return true;
   }
Member Data Documentation
String Voxel::TI::CalculusModulationFrequencyParameter::_psName private
Definition at line 182 of file ToFCalculusCamera.cpp.
Referenced by get(), and set().
ToFCalculusCamera& Voxel::TI::CalculusModulationFrequencyParameter::_tofCalculusCamera private
Definition at line 181 of file ToFCalculusCamera.cpp.
Referenced by get(), and set().
The documentation for this class was generated from the following file:
ToFCalculusCamera.cpp