Voxel: Voxel::PCLViewer Class Reference
Voxel::PCLViewer Class Reference
#include <PCLViewer.h>
Public Member Functions
PCLViewer ()
void setDepthCamera (Voxel::DepthCameraPtr depthCamera)
void removeDepthCamera ()
Ptr< pcl::Grabber > getGrabber ()
void start ()
bool isRunning ()
void stop ()
bool viewerStopped ()
virtual ~PCLViewer ()
Protected Member Functions
void _cloudRenderCallback (const pcl::PointCloud< pcl::PointXYZI > &cloud)
void _renderLoop ()
Protected Attributes
DepthCameraPtr _depthCamera
Mutex _cloudUpdateMutex
Ptr
< pcl::visualization::PCLVisualizer > _viewer
Ptr
< pcl::visualization::PointCloudColorHandlerGenericField
< pcl::PointXYZI > > _handler
bool _stopLoop = false
Ptr< pcl::Grabber > _grabber
boost::shared_ptr< const
pcl::PointCloud
< pcl::PointXYZI > > _cloud
std::thread _renderThread
Detailed Description
Definition at line 35 of file PCLViewer.h.
Constructor & Destructor Documentation
Voxel::PCLViewer::PCLViewer ()
Definition at line 19 of file PCLViewer.cpp.
 {
 }
virtual Voxel::PCLViewer::~PCLViewer () inline virtual
Definition at line 71 of file PCLViewer.h.
References _renderThread, isRunning(), and stop().
   {
     if(isRunning()) stop();
     if(_renderThread.joinable()) _renderThread.join();
   }
Member Function Documentation
void Voxel::PCLViewer::_cloudRenderCallback (const pcl::PointCloud< pcl::PointXYZI > & cloud) protected
Definition at line 116 of file PCLViewer.cpp.
References _cloud, _cloudUpdateMutex, _handler, and _viewer.
Referenced by start().
 {
   if(_viewer && !_viewer->wasStopped())
   {
     Lock<Mutex> _(_cloudUpdateMutex);
     _cloud = boost::shared_ptr<const pcl::PointCloud<pcl::PointXYZI>>(new pcl::PointCloud<pcl::PointXYZI>(cloud));
     _handler = Ptr<pcl::visualization::PointCloudColorHandlerGenericField<pcl::PointXYZI>>(
       new pcl::visualization::PointCloudColorHandlerGenericField<pcl::PointXYZI>(_cloud, "intensity"));
   }
 }
void Voxel::PCLViewer::_renderLoop () protected
Definition at line 23 of file PCLViewer.cpp.
References _cloud, _cloudUpdateMutex, _handler, _stopLoop, _viewer, and CLOUD_NAME.
Referenced by start().
 {
   if(!_viewer)
   {
     _viewer =  Ptr<pcl::visualization::PCLVisualizer>(new pcl::visualization::PCLVisualizer("PCL Voxel Viewer"));
     _viewer->setBackgroundColor(0, 0, 0);
     //_viewer->createInteractor();
     _viewer->addCoordinateSystem(1.0);
     _viewer->initCameraParameters();
     _viewer->setShowFPS(false);
     _viewer->resetCameraViewpoint();
     _viewer->setCameraPosition(15, 15, 20, 0, 0, 5, 0, 0, 1);
   }
   if(_viewer->wasStopped())
     _viewer->resetStoppedFlag();
   bool firstTime = false;
   int updateCount = 0;
   while(!_stopLoop && !_viewer->wasStopped())
   {
     {
       Lock<Mutex> _(_cloudUpdateMutex);
       if(_cloud && _handler)
       {
         double psize = 1.0, opacity = 1.0, linesize =1.0;
         _viewer->getPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_LINE_WIDTH, linesize, CLOUD_NAME);
         _viewer->getPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_OPACITY, opacity, CLOUD_NAME);
         _viewer->getPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, psize, CLOUD_NAME);
         if(!_viewer->updatePointCloud(_cloud, *_handler, CLOUD_NAME))
         {
           _viewer->addPointCloud(_cloud, *_handler, CLOUD_NAME);
           _viewer->setPointCloudRenderingProperties(pcl::visualization::PCL_VISUALIZER_POINT_SIZE, 1, CLOUD_NAME);
           // Get the cloud mapper and set it not scale intensity to false color range dynamically
           auto cloudActorMap = _viewer->getCloudActorMap();
           auto actor = cloudActorMap->find(CLOUD_NAME);
           vtkPolyDataMapper *polyDataMapper = reinterpret_cast<vtkPolyDataMapper*>(actor->second.actor->GetMapper());
           polyDataMapper->UseLookupTableScalarRangeOn();
         }
         else
         {
           _viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_POINT_SIZE, psize, CLOUD_NAME);
           _viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_LINE_WIDTH, linesize, CLOUD_NAME);
           _viewer->setPointCloudRenderingProperties (pcl::visualization::PCL_VISUALIZER_OPACITY, opacity, CLOUD_NAME);
         }
       }
     }
     _viewer->spinOnce(10);
     std::this_thread::sleep_for(std::chrono::microseconds(10000));
     updateCount++;
     if(firstTime)
     {
       _viewer->setCameraPosition(15, 15, 20, 0, 0, 5, 0, 0, 1);
       firstTime = false;
     }
   }
   //_viewer->close();
   //_viewer = nullptr;
   _stopLoop = true;
 }
Ptr<pcl::Grabber> Voxel::PCLViewer::getGrabber () inline
Definition at line 63 of file PCLViewer.h.
References _grabber.
 { return _grabber; }
bool Voxel::PCLViewer::isRunning ()
Definition at line 154 of file PCLViewer.cpp.
References _grabber, _stopLoop, and viewerStopped().
Referenced by main(), removeDepthCamera(), setDepthCamera(), and ~PCLViewer().
 {
   return _grabber && _grabber->isRunning() && !_stopLoop && !viewerStopped();
 }
void Voxel::PCLViewer::removeDepthCamera ()
Definition at line 105 of file PCLViewer.cpp.
References _depthCamera, isRunning(), and stop().
 {
   if(isRunning())
   {
     stop();
   }
   _depthCamera = nullptr;
 }
void Voxel::PCLViewer::setDepthCamera (Voxel::DepthCameraPtr depthCamera)
Definition at line 93 of file PCLViewer.cpp.
References _depthCamera, isRunning(), start(), and stop().
Referenced by main().
 {
   if(isRunning())
   {
     stop();
     _depthCamera = depthCamera;
     start();
   }
   else
     _depthCamera = depthCamera;
 }
void Voxel::PCLViewer::start ()
Definition at line 128 of file PCLViewer.cpp.
References _cloudRenderCallback(), _depthCamera, _grabber, _renderLoop(), _renderThread, _stopLoop, and _viewer.
Referenced by main(), and setDepthCamera().
 {
   if(!_depthCamera)
     return;
   _stopLoop = true;
   if(_renderThread.joinable())
     _renderThread.join();
 #ifdef WINDOWS
   _viewer = nullptr;
 #endif
   _stopLoop = false;
   _renderThread = std::thread(&PCLViewer::_renderLoop, this);
   _grabber = Ptr<pcl::Grabber>(new Voxel::PCLGrabber(*_depthCamera));
   boost::function<void (const pcl::PointCloud<pcl::PointXYZI> &)> f = boost::bind(&PCLViewer::_cloudRenderCallback, this, _1);
   _grabber->registerCallback(f);
   _grabber->start();
 }
void Voxel::PCLViewer::stop ()
Definition at line 164 of file PCLViewer.cpp.
References _grabber, _renderThread, _stopLoop, and _viewer.
Referenced by removeDepthCamera(), setDepthCamera(), and ~PCLViewer().
 {
   _stopLoop = true;
   if(_renderThread.joinable()) _renderThread.join();
   //if (_viewer)
   //{
   //  Lock<Mutex> _(_cloudUpdateMutex);
   //  _viewer->removePointCloud(CLOUD_NAME);
   //}
 #ifdef WINDOWS
   _viewer = nullptr;
 #endif
   _grabber = nullptr;
 }
bool Voxel::PCLViewer::viewerStopped ()
Definition at line 159 of file PCLViewer.cpp.
References _viewer.
Referenced by isRunning().
 {
   return !_viewer || _viewer->wasStopped();
 }
Member Data Documentation
boost::shared_ptr<const pcl::PointCloud<pcl::PointXYZI> > Voxel::PCLViewer::_cloud protected
Definition at line 49 of file PCLViewer.h.
Referenced by _cloudRenderCallback(), and _renderLoop().
Mutex Voxel::PCLViewer::_cloudUpdateMutex protected
Definition at line 40 of file PCLViewer.h.
Referenced by _cloudRenderCallback(), and _renderLoop().
DepthCameraPtr Voxel::PCLViewer::_depthCamera protected
Definition at line 38 of file PCLViewer.h.
Referenced by removeDepthCamera(), setDepthCamera(), and start().
Ptr<pcl::Grabber> Voxel::PCLViewer::_grabber protected
Definition at line 47 of file PCLViewer.h.
Referenced by getGrabber(), isRunning(), start(), and stop().
Ptr<pcl::visualization::PointCloudColorHandlerGenericField<pcl::PointXYZI> > Voxel::PCLViewer::_handler protected
Definition at line 43 of file PCLViewer.h.
Referenced by _cloudRenderCallback(), and _renderLoop().
std::thread Voxel::PCLViewer::_renderThread protected
Definition at line 55 of file PCLViewer.h.
Referenced by start(), stop(), and ~PCLViewer().
bool Voxel::PCLViewer::_stopLoop = false protected
Definition at line 45 of file PCLViewer.h.
Referenced by _renderLoop(), isRunning(), start(), and stop().
Ptr<pcl::visualization::PCLVisualizer> Voxel::PCLViewer::_viewer protected
Definition at line 42 of file PCLViewer.h.
Referenced by _cloudRenderCallback(), _renderLoop(), start(), stop(), and viewerStopped().
The documentation for this class was generated from the following files:
PCLViewer.h
PCLViewer.cpp