Voxel: Voxel::RegisterProgrammer Class Reference
Voxel::RegisterProgrammer Class Reference abstract
I/O classes
#include <RegisterProgrammer.h>
Public Member Functions
virtual bool isInitialized () const =0
virtual bool setValue (const Parameter &param, uint32_t value, bool writeOnly=false)=0
virtual bool getValue (const Parameter &param, uint32_t &value) const =0
virtual bool readRegister (uint32_t address, uint32_t &value) const =0
virtual bool writeRegister (uint32_t address, uint32_t value)=0
virtual bool reset ()=0
virtual ~RegisterProgrammer ()
Detailed Description
Definition at line 24 of file RegisterProgrammer.h.
Constructor & Destructor Documentation
virtual Voxel::RegisterProgrammer::~RegisterProgrammer () inline virtual
Definition at line 38 of file RegisterProgrammer.h.
 {}
Member Function Documentation
virtual bool Voxel::RegisterProgrammer::getValue (const Parameter & param, uint32_t & value) const pure virtual
Implemented in Voxel::TI::VoxelProgrammerBase, and DummyRegisterProgrammer.
Referenced by Voxel::ParameterTemplate< bool >::get().
virtual bool Voxel::RegisterProgrammer::isInitialized () const pure virtual
Implemented in Voxel::TI::VoxelXUProgrammer, Voxel::TI::VoxelUSBProgrammer, and DummyRegisterProgrammer.
Referenced by Voxel::TI::VoxelProgrammerBase::readRegister(), and Voxel::TI::VoxelProgrammerBase::writeRegister().
virtual bool Voxel::RegisterProgrammer::readRegister (uint32_t address, uint32_t & value) const pure virtual
Implemented in Voxel::TI::VoxelProgrammerBase, and DummyRegisterProgrammer.
virtual bool Voxel::RegisterProgrammer::reset () pure virtual
Implemented in Voxel::TI::VoxelXUProgrammer, Voxel::TI::VoxelUSBProgrammer, and DummyRegisterProgrammer.
virtual bool Voxel::RegisterProgrammer::setValue (const Parameter & param, uint32_t value, bool writeOnly = false) pure virtual
Implemented in Voxel::TI::VoxelProgrammerBase, and DummyRegisterProgrammer.
Referenced by Voxel::ParameterTemplate< bool >::set().
virtual bool Voxel::RegisterProgrammer::writeRegister (uint32_t address, uint32_t value) pure virtual
Implemented in Voxel::TI::VoxelProgrammerBase, and DummyRegisterProgrammer.
The documentation for this class was generated from the following file:
RegisterProgrammer.h