Voxel: Voxel::FrameStreamReader Class Reference
Voxel::FrameStreamReader Class Reference
#include <FrameStream.h>
Public Member Functions
FrameStreamReader (const String &fileName, CameraSystem &sys)
FrameStreamReader (InputFileStream &stream, CameraSystem &sys)
bool isStreamGood ()
bool readNext ()
bool seekTo (size_t position)
size_t currentPosition ()
size_t size ()
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool close ()
virtual ~FrameStreamReader ()
Public Attributes
Vector< FramePtr > frames
Private Member Functions
bool _init ()
bool _getPacket (size_t packetIndex, FrameStreamPacket &packet)
bool _readConfigPacket (size_t packetIndex)
Private Attributes
InputFileStream & _stream
InputFileStream _internalStream
Vector< FileOffsetType > _allPacketOffsets
Vector< IndexType > _dataPacketLocation
Vector< IndexType > _configPacketLocation
FrameStreamHeader _header
size_t _currentPacketIndex
size_t _currentFrameIndex
CameraSystem & _sys
Ptr< FrameGenerator > _frameGenerator [3]
FrameStreamPacket _dataPacket
FrameStreamPacket _configPacket
GeneratorConfigurationSubPacket _configSubPacket
Detailed Description
Definition at line 84 of file FrameStream.h.
Constructor & Destructor Documentation
Voxel::FrameStreamReader::FrameStreamReader (const String & fileName, CameraSystem & sys)
Definition at line 152 of file FrameStream.cpp.
References _init(), _stream, Voxel::LOG_ERROR, and Voxel::logger.
                                                                              : _stream(_internalStream), _sys(sys), frames(4)
 {
   _stream.open(fileName, std::ios::binary | std::ios::in);
   if(!_stream.good())
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to open file '" << fileName << "'" << std::endl;
   }
   else
     _init();
 }
Voxel::FrameStreamReader::FrameStreamReader (InputFileStream & stream, CameraSystem & sys)
Definition at line 147 of file FrameStream.cpp.
References _init().
                                                                               :_stream(stream), _sys(sys), frames(4)
 {
   _init();
 }
virtual Voxel::FrameStreamReader::~FrameStreamReader () inline virtual
Definition at line 129 of file FrameStream.h.
 {}
Member Function Documentation
bool Voxel::FrameStreamReader::_getPacket (size_t packetIndex, FrameStreamPacket & packet) private
Definition at line 242 of file FrameStream.cpp.
References _allPacketOffsets, _stream, Voxel::LOG_ERROR, Voxel::logger, Voxel::DataPacket::read(), and Voxel::DataPacket::verifyMagic().
Referenced by _readConfigPacket(), and readNext().
 {
   if(packetIndex < 0 || packetIndex >= _allPacketOffsets.size())
     return false;
   _stream.seekg(_allPacketOffsets[packetIndex], std::ios::beg);
   if(!_stream.good())
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to move the stream get position" << std::endl;
     return false;
   }
   if(!packet.read(_stream))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to read packet with index = " << packetIndex << std::endl;
     return false;
   }
   if(!packet.verifyMagic())
   {
     logger(LOG_ERROR) << "FrameStreamReader: Found packet with invalid magic string" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::FrameStreamReader::_init () private
Definition at line 164 of file FrameStream.cpp.
References _allPacketOffsets, _configPacketLocation, _currentFrameIndex, _currentPacketIndex, _dataPacket, _dataPacketLocation, _frameGenerator, _header, _stream, _sys, Voxel::DepthCamera::FRAME_DEPTH_FRAME, Voxel::DepthCamera::FRAME_RAW_FRAME_PROCESSED, Voxel::DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME, Voxel::FrameStreamHeader::generatorIDs, Voxel::CameraSystem::getFrameGenerator(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameStreamPacket::PACKET_DATA, Voxel::FrameStreamPacket::PACKET_GENERATOR_CONFIG, Voxel::DataPacket::readHeader(), readNext(), seekTo(), Voxel::DataPacket::size, Voxel::DataPacket::type, Voxel::DataPacket::verifyMagic(), and Voxel::FrameStreamHeader::version.
Referenced by FrameStreamReader().
 {
   if(!_stream.good())
     return false;
   _currentFrameIndex = _currentPacketIndex = 0;
   _stream.read(_header.version, 2);
   _stream.read((char *)&_header.generatorIDs, sizeof(GeneratorIDType)*3);
   if(_stream.fail() | _stream.bad())
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to read frame headers." << std::endl;
     return false;
   }
   if(!_sys.getFrameGenerator(DepthCamera::FRAME_RAW_FRAME_PROCESSED, _header.generatorIDs[0], _frameGenerator[0]) ||
   !_sys.getFrameGenerator(DepthCamera::FRAME_DEPTH_FRAME, _header.generatorIDs[1], _frameGenerator[1]) ||
   !_sys.getFrameGenerator(DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME, _header.generatorIDs[2], _frameGenerator[2]))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to get necessary frame generators to read stream." << std::endl;
     return false;
   }
   DepthFrameGeneratorPtr p = std::dynamic_pointer_cast<DepthFrameGenerator>(_frameGenerator[1]);
   if(!p || !p->setProcessedFrameGenerator(_frameGenerator[0]))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Could not initialize depth frame generator" << std::endl;
     return false;
   }
   _allPacketOffsets.reserve(500);
   _dataPacketLocation.reserve(500);
   _configPacketLocation.reserve(500);
   while(!_stream.eof())
   {
     uint offset = _stream.tellg();
     if(!_dataPacket.readHeader(_stream))
       break;
     if(!_dataPacket.verifyMagic())
     {
       logger(LOG_ERROR) << "FrameStreamReader: Got invalid packet at offset = " << _stream.tellg() << std::endl;
       continue;
     }
     if(_dataPacket.type == FrameStreamPacket::PACKET_DATA)
     {
       _allPacketOffsets.push_back(offset);
       _dataPacketLocation.push_back(_allPacketOffsets.size() - 1);
       _stream.seekg(_dataPacket.size, std::ios::cur);
     }
     else if(_dataPacket.type == FrameStreamPacket::PACKET_GENERATOR_CONFIG)
     {
       _allPacketOffsets.push_back(offset);
       _configPacketLocation.push_back(_allPacketOffsets.size() - 1);
       _stream.seekg(_dataPacket.size, std::ios::cur);
     }
     else
     {
       logger(LOG_ERROR) << "FrameStreamReader: Got invalid packet type = " << _dataPacket.type << std::endl;
     }
   }
   _stream.clear();
   if(_allPacketOffsets.size())
     _stream.seekg(_allPacketOffsets[0], std::ios::beg);
   logger(LOG_DEBUG) << "stream state: fail = " << _stream.fail() << ", bad = " << _stream.bad() << ", eof = " << _stream.eof() << std::endl;
   readNext(); // Read initial frame parameters
   seekTo(0);
   return true;
 }
bool Voxel::FrameStreamReader::_readConfigPacket (size_t packetIndex) private
Definition at line 270 of file FrameStream.cpp.
References _configPacket, _configSubPacket, _frameGenerator, _getPacket(), Voxel::GeneratorConfigurationSubPacket::config, Voxel::GeneratorConfigurationSubPacket::frameType, Voxel::LOG_ERROR, Voxel::logger, Voxel::DataPacket::object, Voxel::FrameStreamPacket::PACKET_GENERATOR_CONFIG, Voxel::GeneratorConfigurationSubPacket::read(), and Voxel::DataPacket::type.
Referenced by readNext().
 {
   if(!_getPacket(packetIndex, _configPacket))
     return false;
   if(_configPacket.type != FrameStreamPacket::PACKET_GENERATOR_CONFIG)
   {
     logger(LOG_ERROR) << "FrameStreamReader: Don't know how to handle config packet of type = '" << _configPacket.type << "'. Skipping it."<< "'" << std::endl;
     return false;
   }
   if(!_configSubPacket.read(_configPacket.object))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Could not get extract the configuration for config packet of type = '" << _configPacket.type << "'. Skipping it."<< "'" << std::endl;
     return false;
   }
   if(_configSubPacket.frameType > 3)
   {
     logger(LOG_ERROR) << "FrameStreamReader: Got configuration for unknown frame type = '" << _configSubPacket.frameType << "'" << std::endl;
     return false;
   }
   if(!_frameGenerator[_configSubPacket.frameType - 1]->readConfiguration(_configSubPacket.config))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to read configuration for frame type = '" << (uint)_configSubPacket.frameType << "'. Skipping it."<< "'" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::FrameStreamReader::close ()
Definition at line 352 of file FrameStream.cpp.
References _stream.
 {
   if(_stream.is_open())
     _stream.close();
   return !_stream.fail();
 }
size_t Voxel::FrameStreamReader::currentPosition () inline
Definition at line 121 of file FrameStream.h.
 { return _currentFrameIndex; }
template<typename T > bool Voxel::FrameStreamReader::getStreamParam (const String & name, T & value) const
Definition at line 135 of file FrameStream.h.
References _frameGenerator.
 {
   if(!_frameGenerator[0]->get(name, value) && !_frameGenerator[1]->get(name, value) && !_frameGenerator[2]->get(name, value))
     return false;
   return true;
 }
bool Voxel::FrameStreamReader::isStreamGood () inline
Definition at line 114 of file FrameStream.h.
Referenced by main().
 { return _stream.good(); }
bool Voxel::FrameStreamReader::readNext ()
Definition at line 304 of file FrameStream.cpp.
References _currentFrameIndex, _currentPacketIndex, _dataPacket, _dataPacketLocation, _frameGenerator, _getPacket(), _readConfigPacket(), Voxel::RawDataFrame::deserialize(), frames, Voxel::LOG_ERROR, Voxel::logger, Voxel::DataPacket::object, CameraSystemIQFrameTest::r, and size().
Referenced by _init(), and main().
 {
   if(_currentFrameIndex >= size())
     return false;
   size_t nextIndex = _dataPacketLocation[_currentFrameIndex];
   if(nextIndex > _currentPacketIndex) // some non-data packets in between?
   {
     for(; _currentPacketIndex < nextIndex; _currentPacketIndex++)
     {
       _readConfigPacket(_currentPacketIndex);
     }
   }
   RawDataFrame *r = dynamic_cast<RawDataFrame *>(frames[0].get());
   if(!r)
   {
     r = new RawDataFrame();
     frames[0] = FramePtr(r);
   }
   if(!_getPacket(_currentPacketIndex, _dataPacket))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to get data packet at index = " << _currentFrameIndex << std::endl;
     return false;
   }
   _currentFrameIndex++;
   _currentPacketIndex++;
   if(!r->deserialize(_dataPacket.object))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to deserialize data packet at index = " << _currentFrameIndex << std::endl;
     return false;
   }
   if(!_frameGenerator[0]->generate(frames[0], frames[1]) ||
     !_frameGenerator[1]->generate(frames[1], frames[2]) ||
     !_frameGenerator[2]->generate(frames[2], frames[3]))
   {
     logger(LOG_ERROR) << "FrameStreamReader: Failed to process and generate subsequent frame types at index = " << _currentFrameIndex << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::FrameStreamReader::seekTo (size_t position)
Definition at line 361 of file FrameStream.cpp.
References _currentFrameIndex, _currentPacketIndex, and _dataPacketLocation.
Referenced by _init().
 {
   if(position >= _dataPacketLocation.size())
     return false;
   if(position == 0)
     _currentFrameIndex = _currentPacketIndex = 0;
   else
   {
     _currentFrameIndex = position;
     _currentPacketIndex = _dataPacketLocation[position];
   }
   return true;
 }
size_t Voxel::FrameStreamReader::size () inline
Definition at line 122 of file FrameStream.h.
Referenced by main(), and readNext().
 { return _dataPacketLocation.size(); }
Member Data Documentation
Vector<FileOffsetType> Voxel::FrameStreamReader::_allPacketOffsets private
Definition at line 89 of file FrameStream.h.
Referenced by _getPacket(), and _init().
FrameStreamPacket Voxel::FrameStreamReader::_configPacket private
Definition at line 102 of file FrameStream.h.
Referenced by _readConfigPacket().
Vector<IndexType> Voxel::FrameStreamReader::_configPacketLocation private
Definition at line 91 of file FrameStream.h.
Referenced by _init().
GeneratorConfigurationSubPacket Voxel::FrameStreamReader::_configSubPacket private
Definition at line 103 of file FrameStream.h.
Referenced by _readConfigPacket().
size_t Voxel::FrameStreamReader::_currentFrameIndex private
Definition at line 96 of file FrameStream.h.
Referenced by _init(), readNext(), and seekTo().
size_t Voxel::FrameStreamReader::_currentPacketIndex private
Definition at line 95 of file FrameStream.h.
Referenced by _init(), readNext(), and seekTo().
FrameStreamPacket Voxel::FrameStreamReader::_dataPacket private
Definition at line 102 of file FrameStream.h.
Referenced by _init(), and readNext().
Vector<IndexType> Voxel::FrameStreamReader::_dataPacketLocation private
Definition at line 91 of file FrameStream.h.
Referenced by _init(), readNext(), and seekTo().
Ptr<FrameGenerator> Voxel::FrameStreamReader::_frameGenerator[3] private
Definition at line 100 of file FrameStream.h.
Referenced by _init(), _readConfigPacket(), getStreamParam(), and readNext().
FrameStreamHeader Voxel::FrameStreamReader::_header private
Definition at line 93 of file FrameStream.h.
Referenced by _init().
InputFileStream Voxel::FrameStreamReader::_internalStream private
Definition at line 87 of file FrameStream.h.
InputFileStream& Voxel::FrameStreamReader::_stream private
Definition at line 86 of file FrameStream.h.
Referenced by _getPacket(), _init(), close(), and FrameStreamReader().
CameraSystem& Voxel::FrameStreamReader::_sys private
Definition at line 98 of file FrameStream.h.
Referenced by _init().
Vector<FramePtr> Voxel::FrameStreamReader::frames
Definition at line 116 of file FrameStream.h.
Referenced by main(), and readNext().
The documentation for this class was generated from the following files:
FrameStream.h
FrameStream.cpp