Voxel: Voxel::USBDevice Class Reference
Voxel::USBDevice Class Reference
Camera System Components
#include <Device.h>
Public Member Functions
USBDevice (uint16_t vendorid, uint16_t productid, const String &serialnumber, int channelID=-1, const String &description="", const String &serialIndex="", bool showSerialIndex=false)
virtual Vector< DevicePtr > getDevices (const Vector< int > &channels) const
uint16_t vendorID () const
uint16_t productID () const
virtual ~USBDevice ()
Public Member Functions inherited from Voxel::Device
Device (Interface interfaceid, const String &deviceid, const String &serialnumber, int channelID=-1, const String &description="", const String &serialIndex="", bool showSerialIndex=false)
const String & id () const
Interface interfaceID () const
const String & deviceID () const
const String & serialNumber () const
void setSerialNumber (const String &s)
const String & serialIndex () const
void showSerialIndex ()
void dontShowSerialIndex ()
const int channelID () const
const String & description () const
virtual ~Device ()
Private Attributes
uint16_t _vendorID
uint16_t _productID
Additional Inherited Members
Public Types inherited from Voxel::Device
enum Interface { USB = 0, LPT = 1, SERIAL = 2, I2C = 3 }
Protected Member Functions inherited from Voxel::Device
void _makeID ()
Protected Attributes inherited from Voxel::Device
String _id
Interface _interfaceID
String _deviceID
String _serialNumber
String _serialIndex
bool _showSerialIndex
String _description
int _channelID
Detailed Description
Definition at line 81 of file Device.h.
Constructor & Destructor Documentation
Voxel::USBDevice::USBDevice (uint16_t vendorid, uint16_t productid, const String & serialnumber, int channelID = -1, const String & description = "", const String & serialIndex = "", bool showSerialIndex = false) inline
Definition at line 85 of file Device.h.
Referenced by getDevices().
                                                                                                                                                                                                 :
     Device(Device::USB, getHex(vendorid) + ":" + getHex(productid), serialnumber, channelID, description, serialIndex, showSerialIndex), _vendorID(vendorid), _productID(productid) {}
virtual Voxel::USBDevice::~USBDevice () inline virtual
Definition at line 93 of file Device.h.
 {}
Member Function Documentation
Vector< DevicePtr > Voxel::USBDevice::getDevices (const Vector< int > & channels) const virtual
Reimplemented from Voxel::Device.
Definition at line 26 of file Device.cpp.
References Voxel::Device::_showSerialIndex, Voxel::Device::description(), CameraSystemTest::devices, productID(), Voxel::Device::serialIndex(), Voxel::Device::serialNumber(), USBDevice(), and vendorID().
 {
   Vector<DevicePtr> devices;
   for(auto i = 0; i < channels.size(); i++)
   {
     devices.push_back(DevicePtr(new USBDevice(vendorID(), productID(), serialNumber(), channels[i], description(), serialIndex(), _showSerialIndex)));
   }
   return devices;
 }
uint16_t Voxel::USBDevice::productID () const inline
Definition at line 91 of file Device.h.
Referenced by Voxel::TI::TintinEEPROMDownloader::_configureForDownload(), Voxel::TI::TintinCDKCamera::_getMaximumVideoMode(), Voxel::TI::TintinCDKCamera::_getSupportedVideoModes(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::TintinCDKCamera::_setStreamerFrameSize(), Voxel::USBSystemPrivate::getBusDevNumbers(), Voxel::TI::CalculusCDKCameraFactory::getDepthCamera(), Voxel::TI::TintinCDKCameraFactory::getDepthCamera(), Voxel::TI::Voxel14CameraFactory::getDepthCamera(), Voxel::TI::HaddockCDKCameraFactory::getDepthCamera(), Voxel::TI::RTS5825CameraFactory::getDepthCamera(), Voxel::TI::VoxelDCameraFactory::getDepthCamera(), Voxel::USBSystemPrivate::getDeviceNode(), getDevices(), Voxel::TI::TintinCDKDownloaderFactory::getDownloader(), and main().
 { return _productID; }
uint16_t Voxel::USBDevice::vendorID () const inline
Definition at line 90 of file Device.h.
Referenced by Voxel::TI::Voxel14Camera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::USBSystemPrivate::getBusDevNumbers(), Voxel::TI::Voxel14CameraFactory::getDepthCamera(), Voxel::TI::RTS5825CameraFactory::getDepthCamera(), Voxel::TI::HaddockCDKCameraFactory::getDepthCamera(), Voxel::TI::CalculusCDKCameraFactory::getDepthCamera(), Voxel::TI::VoxelDCameraFactory::getDepthCamera(), Voxel::TI::TintinCDKCameraFactory::getDepthCamera(), Voxel::USBSystemPrivate::getDeviceNode(), getDevices(), Voxel::TI::TintinCDKDownloaderFactory::getDownloader(), and main().
 { return _vendorID; }
Member Data Documentation
uint16_t Voxel::USBDevice::_productID private
Definition at line 83 of file Device.h.
uint16_t Voxel::USBDevice::_vendorID private
Definition at line 83 of file Device.h.
The documentation for this class was generated from the following files:
Device.h
Device.cpp