Voxel: ELFIO::elfio::Segments Class Reference
ELFIO::elfio::Segments Class Reference
#include <elfio.hpp>
Public Member Functions
Segments (elfio *parent_)
Elf_Half size () const
segment * operator[] (unsigned int index) const
segment * add ()
std::vector< segment * >::iterator begin ()
std::vector< segment * >::iterator end ()
Private Attributes
elfio * parent
Detailed Description
Definition at line 779 of file elfio.hpp.
Constructor & Destructor Documentation
ELFIO::elfio::Segments::Segments (elfio * parent_) inline
Definition at line 782 of file elfio.hpp.
                                    :
             parent( parent_ )
         {
         }
Member Function Documentation
segment* ELFIO::elfio::Segments::add () inline
Definition at line 801 of file elfio.hpp.
References ELFIO::elfio::create_segment(), and parent.
         {
             return parent->create_segment();
         }
std::vector<segment*>::iterator ELFIO::elfio::Segments::begin () inline
Definition at line 807 of file elfio.hpp.
References parent, and ELFIO::elfio::segments_.
{
             return parent->segments_.begin();
         }
std::vector<segment*>::iterator ELFIO::elfio::Segments::end () inline
Definition at line 812 of file elfio.hpp.
References parent, and ELFIO::elfio::segments_.
{
             return parent->segments_.end();
         }
segment* ELFIO::elfio::Segments::operator[] (unsigned int index) const inline
Definition at line 794 of file elfio.hpp.
References parent, and ELFIO::elfio::segments_.
         {
             return parent->segments_[index];
         }
Elf_Half ELFIO::elfio::Segments::size () const inline
Definition at line 788 of file elfio.hpp.
References parent, and ELFIO::elfio::segments_.
Referenced by ELFIO::elfio::get_ordered_segments(), ELFIO::elfio::is_section_without_segment(), ELFIO::elfio::save(), ELFIO::dump::segment_datas(), and ELFIO::dump::segment_headers().
         {
             return (Elf_Half)parent->segments_.size();
         }
Member Data Documentation
elfio* ELFIO::elfio::Segments::parent private
Definition at line 818 of file elfio.hpp.
Referenced by add(), begin(), end(), operator[](), and size().
The documentation for this class was generated from the following file:
elfio.hpp