Voxel: Voxel::USBIO::USBIOPrivate Class Reference
Voxel::USBIO::USBIOPrivate Class Reference
Public Member Functions
USBIOPrivate (DevicePtr device)
bool isInitialized ()
bool controlTransfer (Direction direction, RequestType requestType, RecipientType recipientType, uint8_t request, uint16_t value, uint16_t index, uint8_t *data, uint16_t &length, bool needFullLength=true, long timeout=1000)
bool bulkTransfer (uint8_t endpoint, uint8_t *data, long toTransferLength, long &transferredLength, long timeout=1000)
bool resetBulkEndPoint (uint8_t endpoint)
~USBIOPrivate ()
Public Attributes
USBHandle handle
USBDeviceHandle deviceHandle
USBSystem sys
DevicePtr device
bool _initialized
long lastTransferSize = 0
Detailed Description
Definition at line 22 of file USBIO.cpp.
Constructor & Destructor Documentation
Voxel::USBIO::USBIOPrivate::USBIOPrivate (DevicePtr device)
Definition at line 56 of file USBIO.cpp.
References _initialized, deviceHandle, Voxel::USBSystemPrivate::getDeviceHandle(), Voxel::USBSystem::getDeviceNode(), Voxel::USBSystem::getUSBSystemPrivate(), handle, Voxel::Device::id(), Voxel::USBSystem::isInitialized(), Voxel::LOG_ERROR, Voxel::logger, sys, and Voxel::Device::USB.
                                                : device(device), handle(0), _initialized(false)
 #ifdef LINUX
   , deviceHandle(0)
 #elif defined(WINDOWS)
   , deviceHandle(INVALID_HANDLE_VALUE)
 #endif
 {
   if(device->interfaceID() != Device::USB)
   {
     logger(LOG_ERROR) << "USBIO: cannot download to a non-USB device" << std::endl;
     return;
   }
   USBDevice &d = (USBDevice &)*device;
   if(!sys.isInitialized())
   {
     logger(LOG_ERROR) << "USBIO: USBSystem init failed." << std::endl;
     return;
   }
 #ifdef LINUX
   int rc;
   deviceHandle = sys.getUSBSystemPrivate().getDeviceHandle(d);
   if(deviceHandle)
   {
     if((rc = libusb_open(deviceHandle, &handle)) == LIBUSB_SUCCESS)
     {
       int channelID = device->channelID();
       if(channelID < 0) channelID = 0;
       if((rc = libusb_claim_interface(handle, channelID)) != LIBUSB_SUCCESS)
       {
         logger(LOG_ERROR) << "USBIO: " << libusb_strerror((libusb_error)rc) << std::endl;
         return;
       }
       _initialized = true;
     }
     else
     {
       logger(LOG_ERROR) << "USBIO: " << libusb_strerror((libusb_error)rc) << std::endl;
       return;
     }
   }
   else
   {
     logger(LOG_ERROR) << "USBIO: Failed to get device handle. Check that device is connected and is accessible from current user." << std::endl;
     return;
   }
 #elif defined(WINDOWS)
   String devicePath = sys.getDeviceNode(d);
   if (!devicePath.size())
   {
     logger(LOG_ERROR) << "USBIO: Could not get device path for '" << d.id() << "'" << std::endl;
     return;
   }
   deviceHandle = CreateFile(devicePath.c_str(), GENERIC_WRITE | GENERIC_READ, FILE_SHARE_WRITE | FILE_SHARE_READ, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL | FILE_FLAG_OVERLAPPED, NULL);
   if (deviceHandle == INVALID_HANDLE_VALUE)
   {
     logger(LOG_ERROR) << "USBIO: Failed to open device path '" << devicePath << "' for device '" << d.id() << "'" << std::endl;
     return;
   }
   handle = Ptr<CCyUSBDevice>(new CCyUSBDevice(deviceHandle));
   if(handle->IsOpen())
   {
     _initialized = true;
   }
 #endif
 }
Voxel::USBIO::USBIOPrivate::~USBIOPrivate ()
Definition at line 135 of file USBIO.cpp.
 {
 #ifdef LINUX
   if(_initialized)
   {
     libusb_release_interface(handle, device->channelID());
     _initialized = false;
   }
   if(handle)
     libusb_close(handle);
   if(deviceHandle)
     libusb_unref_device(deviceHandle);
 #endif
 }
Member Function Documentation
bool Voxel::USBIO::USBIOPrivate::bulkTransfer (uint8_t endpoint, uint8_t * data, long toTransferLength, long & transferredLength, long timeout = 1000)
Definition at line 192 of file USBIO.cpp.
References Voxel::LOG_ERROR, Voxel::logger, and Voxel::nearestPowerOf2().
 {
 #ifdef LINUX
   int transferred;
   int rc = libusb_bulk_transfer(handle, endpoint, data, toTransferLength, &transferred, timeout);
   if(rc != 0 && rc != LIBUSB_ERROR_TIMEOUT)
   {
     logger(LOG_ERROR) << "USBIO: Bulk transfer failed." << std::endl;
     return false;
   }
   transferredLength = transferred;
   lastTransferSize = toTransferLength;
   return true;
 #elif defined(WINDOWS)
   CCyBulkEndPoint *dataEP;
   if(endpoint & 0x80)
   {
     dataEP = handle->BulkInEndPt;
     unsigned int index;
     if (lastTransferSize != toTransferLength)
       dataEP->SetXferSize(nearestPowerOf2(toTransferLength, index));
   }
   else
     dataEP = handle->BulkOutEndPt;
   dataEP->TimeOut = timeout;
   transferredLength = toTransferLength;
   lastTransferSize = toTransferLength;
   if (!dataEP->XferData(data, transferredLength, NULL))
   {
     logger(LOG_ERROR) << "USBIO: Could not transfer '" << transferredLength << "' bytes" << std::endl;
     return false;
   }
   return true;
 #endif
 }
bool Voxel::USBIO::USBIOPrivate::controlTransfer (Direction direction, RequestType requestType, RecipientType recipientType, uint8_t request, uint16_t value, uint16_t index, uint8_t * data, uint16_t & length, bool needFullLength = true, long timeout = 1000)
Definition at line 152 of file USBIO.cpp.
References Voxel::LOG_ERROR, and Voxel::logger.
 {
 #ifdef LINUX
   int status;
   status = libusb_control_transfer(handle,
                                    (direction << 7) | (requestType << 5) | recipientType,
                                    request,
                                    value,
                                    index,
                                    data, length, timeout);
   if ((needFullLength && status != length) || (!needFullLength && status < 0))
   {
     logger(LOG_ERROR) << "USBIO: Control transfer issue: Status " << status << std::endl;
     return false;
   }
   length = (uint16_t)status;
   return true;
 #elif defined(WINDOWS)
   CCyControlEndPoint *ept = handle->ControlEndPt;
   ept->Target = (CTL_XFER_TGT_TYPE)recipientType;
   ept->ReqType = (CTL_XFER_REQ_TYPE)requestType;
   ept->Direction = (CTL_XFER_DIR_TYPE)direction;
   ept->ReqCode = request;
   ept->Value = value;
   ept->TimeOut = timeout;
   ept->Index = index;
   long l = length;
   if (!ept->XferData(data, l, NULL))
   {
     logger(LOG_ERROR) << "USBIO: Control transfer issue." << std::endl;
     return false;
   }
   length = (uint16_t)l;
   return true;
 #endif
 }
bool Voxel::USBIO::USBIOPrivate::isInitialized () inline
Definition at line 44 of file USBIO.cpp.
References _initialized, and handle.
 { return _initialized && handle != 0; }
bool Voxel::USBIO::USBIOPrivate::resetBulkEndPoint (uint8_t endpoint)
Definition at line 237 of file USBIO.cpp.
 {
 #ifdef LINUX
   return libusb_clear_halt(handle, endpoint) == 0;
 #elif defined(WINDOWS)
   CCyBulkEndPoint *dataEP;
   if(endpoint & 0x80)
     dataEP = handle->BulkInEndPt;
   else
     dataEP = handle->BulkOutEndPt;
   return dataEP->Reset();
 #endif
 }
Member Data Documentation
bool Voxel::USBIO::USBIOPrivate::_initialized
Definition at line 39 of file USBIO.cpp.
Referenced by isInitialized(), and USBIOPrivate().
DevicePtr Voxel::USBIO::USBIOPrivate::device
Definition at line 37 of file USBIO.cpp.
USBDeviceHandle Voxel::USBIO::USBIOPrivate::deviceHandle
Definition at line 33 of file USBIO.cpp.
Referenced by USBIOPrivate().
USBHandle Voxel::USBIO::USBIOPrivate::handle
Definition at line 32 of file USBIO.cpp.
Referenced by isInitialized(), and USBIOPrivate().
long Voxel::USBIO::USBIOPrivate::lastTransferSize = 0
Definition at line 41 of file USBIO.cpp.
USBSystem Voxel::USBIO::USBIOPrivate::sys
Definition at line 35 of file USBIO.cpp.
Referenced by USBIOPrivate().
The documentation for this class was generated from the following file:
USBIO.cpp