Voxel: Voxel::TI::ToFHaddockCamera Class Reference
Voxel::TI::ToFHaddockCamera Class Reference
#include <ToFHaddockCamera.h>
Public Member Functions
ToFHaddockCamera (const String &name, DevicePtr device)
virtual ~ToFHaddockCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (int &id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _initStartParams ()
bool _getMaximumFrameSize (FrameSize &s) const
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _getIlluminationFrequency (float &frequency) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _getFrameSize (FrameSize &s) const
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _setStreamerFrameSize (const FrameSize &s)=0
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _getDealiasedPhaseMask (int &dealiasedPhaseMask)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const =0
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const =0
virtual bool _getFieldOfView (float &fovHalfAngle) const =0
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Friends
class HaddockVCOFrequency
class HaddockModulationFrequencyParameter
class HaddockUnambiguousRangeParameter
class HaddockSensorTemperatureParameter
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Detailed Description
Definition at line 20 of file ToFHaddockCamera.h.
Constructor & Destructor Documentation
Voxel::TI::ToFHaddockCamera::ToFHaddockCamera (const String & name, DevicePtr device)
Definition at line 324 of file ToFHaddockCamera.cpp.
                                                                       : ToFCamera(name, device)
 {
 }
virtual Voxel::TI::ToFHaddockCamera::~ToFHaddockCamera () inline virtual
Definition at line 48 of file ToFHaddockCamera.h.
 {}
Member Function Documentation
bool Voxel::TI::ToFHaddockCamera::_allowedROI (String & message) protected virtual
Implements Voxel::DepthCamera.
Definition at line 456 of file ToFHaddockCamera.cpp.
 {
   message  = "Column start and end must be multiples of 16, both between 0 to 319. ";
   message += "Row start and end must be between 0 to 239.";
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_applyCalibrationParams () protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 394 of file ToFHaddockCamera.cpp.
References CALIB_DISABLE, CALIB_PREC, CALIB_SECT_COMMON_PHASE, CALIB_SECT_TEMPERATURE, COEFF_ILLUM_1, COEFF_ILLUM_2, COEFF_SENSOR_1, COEFF_SENSOR_2, Voxel::DepthCamera::configFile, DISABLE_OFFSET_CORR, DISABLE_TEMP_CORR, Voxel::ConfigurationFile::getBoolean(), Voxel::ConfigurationFile::getInteger(), Voxel::MainConfigurationFile::isPresent(), PHASE_CORR_1, PHASE_CORR_2, Voxel::DepthCamera::set(), TILLUM_CALIB, and TSENSOR_CALIB.
 {
   bool commonPhaseCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_COMMON_PHASE) == 0;
   bool temperatureCalibEnable = (configFile.getInteger("calib", CALIB_DISABLE) & CALIB_SECT_TEMPERATURE) == 0;
   if(commonPhaseCalibEnable)
   {
     if(!set(PHASE_CORR_1, configFile.getInteger("calib", PHASE_CORR_1)) ||
     !set(PHASE_CORR_2, configFile.getInteger("calib", PHASE_CORR_2)) ||
     !set(TILLUM_CALIB, (uint)configFile.getInteger("calib", TILLUM_CALIB)) ||
     !set(TSENSOR_CALIB, (uint)configFile.getInteger("calib", TSENSOR_CALIB)) ||
     !set(DISABLE_OFFSET_CORR, configFile.getBoolean("calib", DISABLE_OFFSET_CORR)))
       return false;
   }
   else
   {
     if(!set(DISABLE_OFFSET_CORR, true))
       return false;
   }
   if(temperatureCalibEnable)
   {
     if(!set(DISABLE_TEMP_CORR, configFile.getBoolean("calib", DISABLE_TEMP_CORR)))
       return false;
     int factor = 1;
     if(configFile.isPresent("calib", CALIB_PREC))
       factor = (configFile.getInteger("calib", CALIB_PREC) == 0)?16:256;
     return
     set(COEFF_ILLUM_1, configFile.getInteger("calib", COEFF_ILLUM_1)/factor) &&
     set(COEFF_ILLUM_2, configFile.getInteger("calib", COEFF_ILLUM_2)/factor) &&
     set(COEFF_SENSOR_1, configFile.getInteger("calib", COEFF_SENSOR_1)/factor) &&
     set(COEFF_SENSOR_2, configFile.getInteger("calib", COEFF_SENSOR_2)/factor);
   }
   else
   {
     if(!set(DISABLE_TEMP_CORR, true))
       return false;
   }
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_getCurrentProfileRegisterName (String & name) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 559 of file ToFHaddockCamera.cpp.
References CURRENT_PROFILE.
 {
   name = CURRENT_PROFILE;
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_getIlluminationFrequency (float & frequency) const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 528 of file ToFHaddockCamera.cpp.
References DEALIAS_EN, Voxel::gcd(), MOD_FREQ1, MOD_PS1, and MOD_PS2.
 {
   float modulationFrequency1;
   bool dealiasingEnabled;
   uint modulationPS1, modulationPS2;
   if(!get(DEALIAS_EN, dealiasingEnabled))
     return false;
   if(dealiasingEnabled)
   {
     if(!get(MOD_FREQ1, modulationFrequency1)) // ensure that these are valid
       return false;
     if(!get(MOD_PS1, modulationPS1) || !get(MOD_PS2, modulationPS2))
       return false;
     frequency = modulationFrequency1*gcd(modulationPS1, modulationPS2)/modulationPS2;
     return true;
   }
   else
   {
     if(!get(MOD_FREQ1, frequency))
       return false;
     return true;
   }
 }
bool Voxel::TI::ToFHaddockCamera::_getMaximumFrameSize (FrameSize & s) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 335 of file ToFHaddockCamera.cpp.
References Voxel::FrameSize::height, and Voxel::FrameSize::width.
 {
   s.width = 320;
   s.height = 240;
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_getROI (RegionOfInterest & roi) protected virtual
Implements Voxel::DepthCamera.
Definition at line 463 of file ToFHaddockCamera.cpp.
References Voxel::DepthCamera::_get(), COL_END, COL_START, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, ROW_END, ROW_START, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
   uint rowStart, rowEnd, colStart, colEnd;
   if(!_get(ROW_START, rowStart) || !_get(ROW_END, rowEnd) || !_get(COL_START, colStart) || !_get(COL_END, colEnd))
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Could not get necessary parameters for ROI." << std::endl;
     return false;
   }
   colStart = colStart*2;
   colEnd = (colEnd + 1)*2 - 1;
   roi.x = colStart;
   roi.y = rowStart;
   roi.width = colEnd - colStart + 1;
   roi.height = rowEnd - rowStart + 1;
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_getSystemClockFrequency (uint & frequency) const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 328 of file ToFHaddockCamera.cpp.
Referenced by Voxel::TI::HaddockVCOFrequency::get(), and Voxel::TI::HaddockVCOFrequency::set().
 {
   frequency = 48;
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_init () protected
Definition at line 343 of file ToFHaddockCamera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::TI::ToFCamera::_init(), Voxel::DepthCamera::_parameterInit, Voxel::DepthCamera::_programmer, Voxel::DepthCamera::configFile, Voxel::MainConfigurationFile::get(), Voxel::Configuration::getConfFile(), Voxel::ParameterDMLParser::getParameters(), HaddockModulationFrequencyParameter, HaddockSensorTemperatureParameter, HaddockUnambiguousRangeParameter, HaddockVCOFrequency, Voxel::LOG_ERROR, Voxel::logger, MOD_FREQ1, MOD_FREQ2, MOD_PS1, MOD_PS2, and Voxel::DepthCamera::name().
Referenced by Voxel::TI::Voxel14Camera::_init(), and Voxel::TI::HaddockCDKCamera::_init().
 {
   Configuration c;
   String name = configFile.get("core", "dml");
   if(!name.size() || !c.getConfFile(name)) // true => name is now a proper path
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Failed to locate/read DML file '" << name << "'" << std::endl;
     return false;
   }
   ParameterDMLParser p(*_programmer, name);
   Vector<ParameterPtr> params;
   if(!p.getParameters(params))
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Could not read parameters from DML file '" << name << "'" << std::endl;
     return _parameterInit = false;
   }
   for(auto &p: params)
   {
     if((p->address() >> 8) == 0) // bankId == 0
       p->setAddress((0x58 << 8) + p->address());
     else if((p->address() >> 8) == 3) // bankId == 3
       p->setAddress((0x5C << 8) + (p->address() & 0xFF));
   }
   if(!_addParameters(params))
     return false;
   if(!_addParameters({
     ParameterPtr(new HaddockVCOFrequency(*this, *_programmer)),
     ParameterPtr(new HaddockModulationFrequencyParameter(*this, *_programmer, MOD_FREQ1, MOD_PS1)),
     ParameterPtr(new HaddockModulationFrequencyParameter(*this, *_programmer, MOD_FREQ2, MOD_PS2)),
     ParameterPtr(new HaddockUnambiguousRangeParameter(*this, *_programmer)),
     ParameterPtr(new HaddockSensorTemperatureParameter(*this, *_programmer))
   }))
     return false;
   if(!ToFCamera::_init())
   {
     return false;
   }
   return true;
 }
bool Voxel::TI::ToFHaddockCamera::_initStartParams () protected virtual
set(DEBUG_EN, true) || // Uncomment this for sample data
Reimplemented from Voxel::TI::ToFCamera.
Reimplemented in Voxel::TI::HaddockCDKCamera, and Voxel::TI::Voxel14Camera.
Definition at line 440 of file ToFHaddockCamera.cpp.
References Voxel::TI::ToFCamera::_initStartParams(), BLK_HEADER_EN, BLK_SIZE, CONFIDENCE_THRESHOLD, FB_READY_EN, ILLUM_EN_POL, OP_CS_POL, Voxel::DepthCamera::set(), and TG_EN.
Referenced by Voxel::TI::Voxel14Camera::_initStartParams().
 {
   if(!set(TG_EN, true) ||
      !set(BLK_SIZE, 1024U) ||
      !set(BLK_HEADER_EN, true) ||
      !set(OP_CS_POL, true) ||
      !set(FB_READY_EN, true) ||
      !set(CONFIDENCE_THRESHOLD, 1U) ||
      !set(ILLUM_EN_POL, false))
     // || set(INTG_TIME, 40.0f);
     return false;
   return ToFCamera::_initStartParams();
 }
bool Voxel::TI::ToFHaddockCamera::_isHistogramEnabled () const protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 522 of file ToFHaddockCamera.cpp.
References Voxel::DepthCamera::_get(), and HISTOGRAM_EN.
 {
   bool histogramEnabled;
   return _get(HISTOGRAM_EN, histogramEnabled) && histogramEnabled;
 }
bool Voxel::TI::ToFHaddockCamera::_setROI (const RegionOfInterest & roi) protected virtual
Implements Voxel::DepthCamera.
Definition at line 483 of file ToFHaddockCamera.cpp.
References Voxel::TI::ToFCamera::_getFrameSize(), Voxel::DepthCamera::_set(), Voxel::TI::ToFCamera::_setBinning(), Voxel::TI::ToFCamera::_setFrameSize(), COL_END, COL_START, Voxel::FrameSize::height, Voxel::DepthCamera::isRunning(), Voxel::LOG_ERROR, Voxel::logger, ROW_END, ROW_START, Voxel::FrameSize::width, Voxel::RegionOfInterest::x, and Voxel::RegionOfInterest::y.
 {
   if(isRunning())
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Cannot set frame size while the camera is streaming" << std::endl;
     return false;
   }
   uint rowStart, rowEnd, colStart, colEnd;
   colStart = (roi.x/16)*8;
   colEnd = ((roi.x + roi.width)/16)*8 - 1;
   rowStart = roi.y;
   rowEnd = rowStart + roi.height - 1;
   if(!_set(ROW_START, rowStart) || !_set(ROW_END, rowEnd) || !_set(COL_START, colStart) || !_set(COL_END, colEnd))
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Could not get necessary parameters for ROI." << std::endl;
     return false;
   }
   if(!_setBinning(1, 1, roi))
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Could not reset binning while setting ROI." << std::endl;
     return false;
   }
   FrameSize s;
   if(!_getFrameSize(s) || !_setFrameSize(s, false)) // Get and set frame size to closest possible
   {
     logger(LOG_ERROR) << "ToFHaddockCamera: Could not update frame size to closest valid frame size" << std::endl;
     return false;
   }
   return true;
 }
Friends And Related Function Documentation
friend class HaddockModulationFrequencyParameter friend
Definition at line 51 of file ToFHaddockCamera.h.
Referenced by _init().
friend class HaddockSensorTemperatureParameter friend
Definition at line 53 of file ToFHaddockCamera.h.
Referenced by _init().
friend class HaddockUnambiguousRangeParameter friend
Definition at line 52 of file ToFHaddockCamera.h.
Referenced by _init().
friend class HaddockVCOFrequency friend
Definition at line 50 of file ToFHaddockCamera.h.
Referenced by _init().
The documentation for this class was generated from the following files:
ToFHaddockCamera.h
ToFHaddockCamera.cpp