Voxel: Voxel::PCLGrabber Class Reference
Voxel::PCLGrabber Class Reference
#include <PCLGrabber.h>
Public Types
typedef void(PointCloudCallBack)(const pcl::PointCloud< pcl::PointXYZI > &)
typedef void(PointCloudFrameCallBack)(const Voxel::PointCloudFrame &)
typedef void(DepthImageCallBack)(const Voxel::DepthFrame &)
typedef void(RawImageCallBack)(const Voxel::RawFrame &, const Voxel::DepthCamera::FrameType type)
Public Member Functions
PCLGrabber (DepthCamera &depthCamera)
virtual float getFramesPerSecond () const
virtual std::string getName () const
virtual bool isRunning () const
virtual void start ()
virtual void stop ()
virtual ~PCLGrabber ()
Protected Member Functions
void _callback (DepthCamera &depthCamera, const Frame &frame, DepthCamera::FrameType type)
Protected Attributes
DepthCamera & _depthCamera
FrameBufferManager
< pcl::PointCloud
< pcl::PointXYZI > > _pointCloudBuffer
boost::signals2::signal
< PointCloudFrameCallBack > * _pointCloudFrameSignal
boost::signals2::signal
< PointCloudCallBack > * _pointCloudSignal
boost::signals2::signal
< DepthImageCallBack > * _depthImageSignal
boost::signals2::signal
< RawImageCallBack > * _rawImageSignal
Detailed Description
Definition at line 20 of file PCLGrabber.h.
Member Typedef Documentation
typedef void(Voxel::PCLGrabber::DepthImageCallBack)(const Voxel::DepthFrame &)
Definition at line 25 of file PCLGrabber.h.
typedef void(Voxel::PCLGrabber::PointCloudCallBack)(const pcl::PointCloud< pcl::PointXYZI > &)
Definition at line 23 of file PCLGrabber.h.
typedef void(Voxel::PCLGrabber::PointCloudFrameCallBack)(const Voxel::PointCloudFrame &)
Definition at line 24 of file PCLGrabber.h.
typedef void(Voxel::PCLGrabber::RawImageCallBack)(const Voxel::RawFrame &, const Voxel::DepthCamera::FrameType type)
Definition at line 26 of file PCLGrabber.h.
Constructor & Destructor Documentation
Voxel::PCLGrabber::PCLGrabber (DepthCamera & depthCamera)
Definition at line 12 of file PCLGrabber.cpp.
References _callback(), _depthCamera, _depthImageSignal, _pointCloudFrameSignal, _pointCloudSignal, _rawImageSignal, Voxel::DepthCamera::FRAME_DEPTH_FRAME, Voxel::DepthCamera::FRAME_RAW_FRAME_PROCESSED, Voxel::DepthCamera::FRAME_RAW_FRAME_UNPROCESSED, Voxel::DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME, and Voxel::DepthCamera::registerCallback().
                                               : _depthCamera(depthCamera), _pointCloudBuffer(2)
 {
   _pointCloudSignal = createSignal<PointCloudCallBack>();
   _pointCloudFrameSignal = createSignal<PointCloudFrameCallBack>();
   _depthImageSignal = createSignal<DepthImageCallBack>();
   _rawImageSignal = createSignal<RawImageCallBack>();
   _depthCamera.registerCallback(DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME, std::bind(&PCLGrabber::_callback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
   _depthCamera.registerCallback(DepthCamera::FRAME_DEPTH_FRAME, std::bind(&PCLGrabber::_callback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
   _depthCamera.registerCallback(DepthCamera::FRAME_RAW_FRAME_PROCESSED, std::bind(&PCLGrabber::_callback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
   _depthCamera.registerCallback(DepthCamera::FRAME_RAW_FRAME_UNPROCESSED, std::bind(&PCLGrabber::_callback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));
 }
virtual Voxel::PCLGrabber::~PCLGrabber () inline virtual
Definition at line 61 of file PCLGrabber.h.
   {
     if(isRunning())
       stop();
   }
Member Function Documentation
void Voxel::PCLGrabber::_callback (DepthCamera & depthCamera, const Frame & frame, DepthCamera::FrameType type) protected
Definition at line 25 of file PCLGrabber.cpp.
References _depthImageSignal, _pointCloudBuffer, _pointCloudFrameSignal, _pointCloudSignal, _rawImageSignal, Voxel::DepthCamera::FRAME_DEPTH_FRAME, Voxel::DepthCamera::FRAME_RAW_FRAME_PROCESSED, Voxel::DepthCamera::FRAME_RAW_FRAME_UNPROCESSED, Voxel::DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME, Voxel::FrameBufferManager< BufferType >::get(), Voxel::LOG_ERROR, Voxel::logger, and Voxel::PointCloudFrameTemplate< PointType >::points.
Referenced by PCLGrabber().
 {
   if(type == DepthCamera::FRAME_RAW_FRAME_UNPROCESSED || type == DepthCamera::FRAME_RAW_FRAME_PROCESSED)
   {
     if(_rawImageSignal->num_slots() > 0)
     {
       const RawFrame *f = dynamic_cast<const RawFrame *>(&frame);
       if(f)
         (*_rawImageSignal)(*f, type);
       else
         logger(LOG_ERROR) << "PCLGrabber: Callback type claims a raw frame, but obtained frame not raw?" << std::endl;
     }
   }
   else if(type == DepthCamera::FRAME_DEPTH_FRAME)
   {
     if(_depthImageSignal->num_slots() > 0)
     {
       const DepthFrame *f = dynamic_cast<const DepthFrame *>(&frame);
       if(f)
         (*_depthImageSignal)(*f);
       else
         logger(LOG_ERROR) << "PCLGrabber: Callback type claims a depth frame, but obtained frame not a depth frame?" << std::endl;
     }
   }
   else if(type == DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME)
   {
     if(_pointCloudFrameSignal->num_slots() > 0)
     {
       const PointCloudFrame *f = dynamic_cast<const PointCloudFrame *>(&frame);
       if(f)
       {
         (*_pointCloudFrameSignal)(*f);
       }
     }
     if(_pointCloudSignal->num_slots() > 0)
     {
       const XYZIPointCloudFrame *f = dynamic_cast<const XYZIPointCloudFrame *>(&frame);
       if(f)
       {
         auto pointCloud = _pointCloudBuffer.get();
         if(!*pointCloud)
         {
           (*pointCloud) = Ptr<pcl::PointCloud<pcl::PointXYZI>>(new pcl::PointCloud<pcl::PointXYZI>());
           (*pointCloud)->sensor_origin_.setZero ();
           (*pointCloud)->sensor_orientation_.w () = 1.0f;
           (*pointCloud)->sensor_orientation_.x () = 0.0f;
           (*pointCloud)->sensor_orientation_.y () = 0.0f;
           (*pointCloud)->sensor_orientation_.z () = 0.0f;
         }
         (*pointCloud)->points.resize(f->points.size());
         auto index = 0;
         for(auto &p: f->points)
         {
           auto &q = (*pointCloud)->points[index];
           q.x = p.x;
           q.y = p.y;
           q.z = p.z;
           q.intensity = p.i*256;
           index++;
         }
         (*_pointCloudSignal)(**pointCloud);
       }
       else
         logger(LOG_ERROR) << "PCLGrabber: Callback type claims a point cloud frame, but obtained frame is not?" << std::endl;
     }
   }
   else
     logger(LOG_ERROR) << "PCLGrabber: Do not know how to handle callback frame type = " << type << std::endl;
 }
virtual float Voxel::PCLGrabber::getFramesPerSecond () const inline virtual
Definition at line 44 of file PCLGrabber.h.
References Voxel::FrameRate::getFrameRate(), and CameraSystemIQFrameTest::r.
   {
     FrameRate r;
     if(!_depthCamera.getFrameRate(r))
       return 0;
     else
       return r.getFrameRate();
   }
virtual std::string Voxel::PCLGrabber::getName () const inline virtual
Definition at line 53 of file PCLGrabber.h.
 { return _depthCamera.id(); }
virtual bool Voxel::PCLGrabber::isRunning () const inline virtual
Definition at line 55 of file PCLGrabber.h.
 { return _depthCamera.isRunning(); }
virtual void Voxel::PCLGrabber::start () inline virtual
Definition at line 57 of file PCLGrabber.h.
 { _depthCamera.start(); }
virtual void Voxel::PCLGrabber::stop () inline virtual
Definition at line 59 of file PCLGrabber.h.
 { _depthCamera.stop(); _depthCamera.wait(); }
Member Data Documentation
DepthCamera& Voxel::PCLGrabber::_depthCamera protected
Definition at line 30 of file PCLGrabber.h.
Referenced by PCLGrabber().
boost::signals2::signal<DepthImageCallBack>* Voxel::PCLGrabber::_depthImageSignal protected
Definition at line 36 of file PCLGrabber.h.
Referenced by _callback(), and PCLGrabber().
FrameBufferManager<pcl::PointCloud<pcl::PointXYZI> > Voxel::PCLGrabber::_pointCloudBuffer protected
Definition at line 32 of file PCLGrabber.h.
Referenced by _callback().
boost::signals2::signal<PointCloudFrameCallBack>* Voxel::PCLGrabber::_pointCloudFrameSignal protected
Definition at line 34 of file PCLGrabber.h.
Referenced by _callback(), and PCLGrabber().
boost::signals2::signal<PointCloudCallBack>* Voxel::PCLGrabber::_pointCloudSignal protected
Definition at line 35 of file PCLGrabber.h.
Referenced by _callback(), and PCLGrabber().
boost::signals2::signal<RawImageCallBack>* Voxel::PCLGrabber::_rawImageSignal protected
Definition at line 37 of file PCLGrabber.h.
Referenced by _callback(), and PCLGrabber().
The documentation for this class was generated from the following files:
PCLGrabber.h
PCLGrabber.cpp