Voxel: ELFIO::relocation_section_accessor Class Reference
ELFIO::relocation_section_accessor Class Reference
#include <elfio_relocation.hpp>
Public Member Functions
relocation_section_accessor (const elfio &elf_file_, section *section_)
Elf_Xword get_entries_num () const
bool get_entry (Elf_Xword index, Elf64_Addr &offset, Elf_Word &symbol, Elf_Word &type, Elf_Sxword &addend) const
bool get_entry (Elf_Xword index, Elf64_Addr &offset, Elf64_Addr &symbolValue, std::string &symbolName, Elf_Word &type, Elf_Sxword &addend, Elf_Sxword &calcValue) const
void add_entry (Elf64_Addr offset, Elf_Xword info)
void add_entry (Elf64_Addr offset, Elf_Word symbol, unsigned char type)
void add_entry (Elf64_Addr offset, Elf_Xword info, Elf_Sxword addend)
void add_entry (Elf64_Addr offset, Elf_Word symbol, unsigned char type, Elf_Sxword addend)
void add_entry (string_section_accessor str_writer, const char *str, symbol_section_accessor sym_writer, Elf64_Addr value, Elf_Word size, unsigned char sym_info, unsigned char other, Elf_Half shndx, Elf64_Addr offset, unsigned char type)
Private Member Functions
Elf_Half get_symbol_table_index () const
template<class T >
void generic_get_entry_rel (Elf_Xword index, Elf64_Addr &offset, Elf_Word &symbol, Elf_Word &type, Elf_Sxword &addend) const
template<class T >
void generic_get_entry_rela (Elf_Xword index, Elf64_Addr &offset, Elf_Word &symbol, Elf_Word &type, Elf_Sxword &addend) const
template<class T >
void generic_add_entry (Elf64_Addr offset, Elf_Xword info)
template<class T >
void generic_add_entry (Elf64_Addr offset, Elf_Xword info, Elf_Sxword addend)
Private Attributes
const elfio & elf_file
section * relocation_section
Detailed Description
Definition at line 76 of file elfio_relocation.hpp.
Constructor & Destructor Documentation
ELFIO::relocation_section_accessor::relocation_section_accessor (const elfio & elf_file_, section * section_) inline
Definition at line 80 of file elfio_relocation.hpp.
                                                                              :
                                  elf_file( elf_file_ ),
                                  relocation_section( section_ )
     {
     }
Member Function Documentation
void ELFIO::relocation_section_accessor::add_entry (Elf64_Addr offset, Elf_Xword info) inline
Definition at line 204 of file elfio_relocation.hpp.
References elf_file, and ELFCLASS32.
Referenced by add_entry().
     {
         if ( elf_file.get_class() == ELFCLASS32 ) {
             generic_add_entry< Elf32_Rel >( offset, info );
         }
         else {
             generic_add_entry< Elf64_Rel >( offset, info );
         }
     }
void ELFIO::relocation_section_accessor::add_entry (Elf64_Addr offset, Elf_Word symbol, unsigned char type) inline
Definition at line 216 of file elfio_relocation.hpp.
References add_entry(), ELF32_R_INFO, ELF64_R_INFO, elf_file, and ELFCLASS32.
     {
         Elf_Xword info;
         if ( elf_file.get_class() == ELFCLASS32 ) {
             info = ELF32_R_INFO( symbol, type );
         }
         else {
             info = ELF64_R_INFO( symbol, type );
         }
         add_entry( offset, info );
     }
void ELFIO::relocation_section_accessor::add_entry (Elf64_Addr offset, Elf_Xword info, Elf_Sxword addend) inline
Definition at line 231 of file elfio_relocation.hpp.
References elf_file, and ELFCLASS32.
     {
         if ( elf_file.get_class() == ELFCLASS32 ) {
             generic_add_entry< Elf32_Rela >( offset, info, addend );
         }
         else {
             generic_add_entry< Elf64_Rela >( offset, info, addend );
         }
     }
void ELFIO::relocation_section_accessor::add_entry (Elf64_Addr offset, Elf_Word symbol, unsigned char type, Elf_Sxword addend) inline
Definition at line 243 of file elfio_relocation.hpp.
References add_entry(), ELF32_R_INFO, ELF64_R_INFO, elf_file, and ELFCLASS32.
     {
         Elf_Xword info;
         if ( elf_file.get_class() == ELFCLASS32 ) {
             info = ELF32_R_INFO( symbol, type );
         }
         else {
             info = ELF64_R_INFO( symbol, type );
         }
         add_entry( offset, info, addend );
     }
void ELFIO::relocation_section_accessor::add_entry (string_section_accessor str_writer, const char * str, symbol_section_accessor sym_writer, Elf64_Addr value, Elf_Word size, unsigned char sym_info, unsigned char other, Elf_Half shndx, Elf64_Addr offset, unsigned char type) inline
Definition at line 259 of file elfio_relocation.hpp.
References add_entry(), ELFIO::string_section_accessor::add_string(), and ELFIO::symbol_section_accessor::add_symbol().
     {
         Elf_Word str_index = str_writer.add_string( str );
         Elf_Word sym_index = sym_writer.add_symbol( str_index, value, size,
                                                    sym_info, other, shndx );
         add_entry( offset, sym_index, type );
     }
template<class T > void ELFIO::relocation_section_accessor::generic_add_entry (Elf64_Addr offset, Elf_Xword info) inline private
Definition at line 330 of file elfio_relocation.hpp.
References ELFIO::section::append_data(), elf_file, ELFIO::elfio::get_convertor(), and relocation_section.
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         T entry;
         entry.r_offset = offset;
         entry.r_info   = info;
         entry.r_offset = convertor( entry.r_offset );
         entry.r_info   = convertor( entry.r_info );
         relocation_section->append_data( reinterpret_cast<char*>( &entry ), sizeof( entry ) );
     }
template<class T > void ELFIO::relocation_section_accessor::generic_add_entry (Elf64_Addr offset, Elf_Xword info, Elf_Sxword addend) inline private
Definition at line 346 of file elfio_relocation.hpp.
References ELFIO::section::append_data(), elf_file, ELFIO::elfio::get_convertor(), and relocation_section.
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         T entry;
         entry.r_offset = offset;
         entry.r_info   = info;
         entry.r_addend = addend;
         entry.r_offset = convertor( entry.r_offset );
         entry.r_info   = convertor( entry.r_info );
         entry.r_addend = convertor( entry.r_addend );
         relocation_section->append_data( reinterpret_cast<char*>( &entry ), sizeof( entry ) );
     }
template<class T > void ELFIO::relocation_section_accessor::generic_get_entry_rel (Elf_Xword index, Elf64_Addr & offset, Elf_Word & symbol, Elf_Word & type, Elf_Sxword & addend) const inline private
Definition at line 288 of file elfio_relocation.hpp.
References elf_file, ELFIO::elfio::get_convertor(), ELFIO::section::get_data(), and relocation_section.
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         const T* pEntry = reinterpret_cast<const T*>(
                 relocation_section->get_data() +
                 index * relocation_section->get_entry_size() );
         offset        = convertor( pEntry->r_offset );
         Elf_Xword tmp = convertor( pEntry->r_info );
         symbol        = get_sym_and_type<T>::get_r_sym( tmp );
         type          = get_sym_and_type<T>::get_r_type( tmp );
         addend        = 0;
     }
template<class T > void ELFIO::relocation_section_accessor::generic_get_entry_rela (Elf_Xword index, Elf64_Addr & offset, Elf_Word & symbol, Elf_Word & type, Elf_Sxword & addend) const inline private
Definition at line 309 of file elfio_relocation.hpp.
References elf_file, ELFIO::elfio::get_convertor(), ELFIO::section::get_data(), and relocation_section.
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         const T* pEntry = reinterpret_cast<const T*>(
                 relocation_section->get_data() +
                 index * relocation_section->get_entry_size() );
         offset        = convertor( pEntry->r_offset );
         Elf_Xword tmp = convertor( pEntry->r_info );
         symbol        = get_sym_and_type<T>::get_r_sym( tmp );
         type          = get_sym_and_type<T>::get_r_type( tmp );
         addend        = convertor( pEntry->r_addend );
     }
Elf_Xword ELFIO::relocation_section_accessor::get_entries_num () const inline
Definition at line 88 of file elfio_relocation.hpp.
References relocation_section.
Referenced by get_entry().
     {
         Elf_Xword nRet = 0;
         if ( 0 != relocation_section->get_entry_size() ) {
             nRet = relocation_section->get_size() / relocation_section->get_entry_size();
         }
         return nRet;
     }
bool ELFIO::relocation_section_accessor::get_entry (Elf_Xword index, Elf64_Addr & offset, Elf_Word & symbol, Elf_Word & type, Elf_Sxword & addend) const inline
Definition at line 101 of file elfio_relocation.hpp.
References elf_file, ELFCLASS32, get_entries_num(), relocation_section, SHT_REL, and SHT_RELA.
Referenced by get_entry().
     {
         if ( index >= get_entries_num() ) {    // Is index valid
             return false;
         }
         if ( elf_file.get_class() == ELFCLASS32 ) {
             if ( SHT_REL == relocation_section->get_type() ) {
                 generic_get_entry_rel< Elf32_Rel >( index, offset, symbol,
                                                     type,  addend );
             }
             else if ( SHT_RELA == relocation_section->get_type() ) {
                 generic_get_entry_rela< Elf32_Rela >( index, offset, symbol,
                                                       type,  addend );
             }
         }
         else {
             if ( SHT_REL == relocation_section->get_type() ) {
                 generic_get_entry_rel< Elf64_Rel >( index, offset, symbol,
                                                     type,  addend );
             }
             else if ( SHT_RELA == relocation_section->get_type() ) {
                 generic_get_entry_rela< Elf64_Rela >( index, offset, symbol,
                                                       type,  addend );
             }
         }
         return true;
     }
bool ELFIO::relocation_section_accessor::get_entry (Elf_Xword index, Elf64_Addr & offset, Elf64_Addr & symbolValue, std::string & symbolName, Elf_Word & type, Elf_Sxword & addend, Elf_Sxword & calcValue) const inline
Definition at line 137 of file elfio_relocation.hpp.
References elf_file, get_entry(), ELFIO::symbol_section_accessor::get_symbol(), get_symbol_table_index(), R_386_32, R_386_COPY, R_386_GLOB_DAT, R_386_GOT32, R_386_GOTOFF, R_386_GOTPC, R_386_JMP_SLOT, R_386_NONE, R_386_PC32, R_386_PLT32, R_386_RELATIVE, and ELFIO::elfio::sections.
     {
         // Do regular job
         Elf_Word symbol;
         bool ret = get_entry( index, offset, symbol, type, addend );
         // Find the symbol
         Elf_Xword     size;
         unsigned char bind;
         unsigned char symbolType;
         Elf_Half      section;
         unsigned char other;
         symbol_section_accessor symbols( elf_file, elf_file.sections[get_symbol_table_index()] );
         ret = symbols.get_symbol( symbol, symbolName, symbolValue,
                                   size, bind, symbolType, section, other );
         if ( ret ) { // Was it successful?
             switch ( type ) {
             case R_386_NONE:        // none
                 calcValue = 0;
                 break;
             case R_386_32:          // S + A
                 calcValue = symbolValue + addend;
                 break;
             case R_386_PC32:        // S + A - P
                 calcValue = symbolValue + addend - offset;
                 break;
             case R_386_GOT32:       // G + A - P
                 calcValue = 0;
                 break;
             case R_386_PLT32:       // L + A - P
                 calcValue = 0;
                 break;
             case R_386_COPY:        // none
                 calcValue = 0;
                 break;
             case R_386_GLOB_DAT:    // S
             case R_386_JMP_SLOT:    // S
                 calcValue = symbolValue;
                 break;
             case R_386_RELATIVE:    // B + A
                 calcValue = addend;
                 break;
             case R_386_GOTOFF:      // S + A - GOT
                 calcValue = 0;
                 break;
             case R_386_GOTPC:       // GOT + A - P
                 calcValue = 0;
                 break;
             default:                // Not recognized symbol!
                 calcValue = 0;
                 break;
             }
         }
         return ret;
     }
Elf_Half ELFIO::relocation_section_accessor::get_symbol_table_index () const inline private
Definition at line 280 of file elfio_relocation.hpp.
References relocation_section.
Referenced by get_entry().
     {
         return (Elf_Half)relocation_section->get_link();
     }
Member Data Documentation
const elfio& ELFIO::relocation_section_accessor::elf_file private
Definition at line 363 of file elfio_relocation.hpp.
Referenced by add_entry(), generic_add_entry(), generic_get_entry_rel(), generic_get_entry_rela(), and get_entry().
section* ELFIO::relocation_section_accessor::relocation_section private
Definition at line 364 of file elfio_relocation.hpp.
Referenced by generic_add_entry(), generic_get_entry_rel(), generic_get_entry_rela(), get_entries_num(), get_entry(), and get_symbol_table_index().
The documentation for this class was generated from the following file:
elfio_relocation.hpp