Voxel: Voxel::FilterSet< FrameType > Class Template Reference
Voxel::FilterSet< FrameType > Class Template Reference
Filter related classes
#include <FilterSet.h>
Classes
class FrameSequence
Public Member Functions
FilterSet (FrameBufferManager< FrameType > &m)
int addFilter (FilterPtr p, int beforeFilterIndex=-1)
FilterPtr getFilter (int index) const
bool removeFilter (int index)
bool removeAllFilters ()
SizeType size () const
bool applyFilter (FrameSequence &seq)
void reset ()
FilterSetIterator< FrameType > begin () const
FilterSetIterator< FrameType > end () const
Protected Attributes
Vector< int > _indices
int _filterCounter
Map< int, FilterPtr > _filters
Mutex _accessMutex
FrameBufferManager< FrameType > & _frameBufferManager
Friends
class FilterSetIterator< FrameType >
Detailed Description
template<typename FrameType>
class Voxel::FilterSet< FrameType >
Definition at line 21 of file FilterSet.h.
Constructor & Destructor Documentation
template<typename FrameType> Voxel::FilterSet< FrameType >::FilterSet (FrameBufferManager< FrameType > & m) inline
Definition at line 62 of file FilterSet.h.
 : _frameBufferManager(m), _filterCounter(0) { _indices.reserve(10); }
Member Function Documentation
template<typename FrameType> FilterSetIterator<FrameType> Voxel::FilterSet< FrameType >::begin () const inline
Definition at line 79 of file FilterSet.h.
Referenced by Voxel::CLIManager::_showFilterSet().
   {
     return FilterSetIterator<FrameType>(*this, 0);
   }
template<typename FrameType> FilterSetIterator<FrameType> Voxel::FilterSet< FrameType >::end () const inline
Definition at line 84 of file FilterSet.h.
Referenced by Voxel::CLIManager::_showFilterSet().
   {
     return FilterSetIterator<FrameType>(*this, _indices.size());
   }
template<typename FrameType> SizeType Voxel::FilterSet< FrameType >::size () const inline
Definition at line 70 of file FilterSet.h.
Referenced by Voxel::FilterSet< FrameType >::FrameSequence::~FrameSequence().
 { return _indices.size(); }
Friends And Related Function Documentation
template<typename FrameType> friend class FilterSetIterator< FrameType > friend
Definition at line 89 of file FilterSet.h.
Member Data Documentation
template<typename FrameType> Mutex Voxel::FilterSet< FrameType >::_accessMutex mutable protected
Definition at line 47 of file FilterSet.h.
template<typename FrameType> int Voxel::FilterSet< FrameType >::_filterCounter protected
Definition at line 44 of file FilterSet.h.
template<typename FrameType> Map<int, FilterPtr> Voxel::FilterSet< FrameType >::_filters protected
Definition at line 45 of file FilterSet.h.
template<typename FrameType> FrameBufferManager<FrameType>& Voxel::FilterSet< FrameType >::_frameBufferManager protected
Definition at line 49 of file FilterSet.h.
template<typename FrameType> Vector<int> Voxel::FilterSet< FrameType >::_indices protected
Definition at line 43 of file FilterSet.h.
Referenced by Voxel::FilterSet< Voxel::DepthFrame >::end(), Voxel::FilterSet< Voxel::DepthFrame >::FilterSet(), Voxel::FilterSetIterator< FrameType >::FilterSetIterator(), and Voxel::FilterSet< Voxel::DepthFrame >::size().
The documentation for this class was generated from the following file:
FilterSet.h