Voxel: Voxel::EnumParameterTemplate< T > Class Template Reference
Voxel::EnumParameterTemplate< T > Class Template Reference
Parameter related classes
#include <Parameter.h>
Public Member Functions
EnumParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const Vector< String > &valueDescription, const Vector< String > &valueMeaning, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
const Vector< String > & valueDescription () const
const Vector< String > & valueMeaning () const
virtual ~EnumParameterTemplate ()
Public Member Functions inherited from Voxel::ParameterTemplate< T >
ParameterTemplate (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const T &defaultValue, const String &displayName, const String &description, Parameter::IOType ioType=Parameter::IO_READ_WRITE, const Vector< String > &dependencies={})
virtual bool set (const T &value)
virtual bool validate (const T &value) const =0
virtual bool refresh ()
virtual bool get (T &value, bool refresh=false)
virtual ~ParameterTemplate ()
Public Member Functions inherited from Voxel::Parameter
Parameter (RegisterProgrammer &programmer, const String &name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const String &displayName, const String &description, IOType ioType=IO_READ_WRITE, const Vector< String > &dependencies={})
const String & name () const
const String & displayName () const
const String & description () const
uint32_t address () const
uint8_t msb () const
uint32_t mask () const
uint8_t lsb () const
IOType ioType () const
void setName (const String &n)
void setAddress (uint32_t a)
virtual ~Parameter ()
Static Public Member Functions
static Ptr
< EnumParameterTemplate< T > > typeCast (const ParameterPtr &other)
Static Public Member Functions inherited from Voxel::ParameterTemplate< T >
static Ptr< ParameterTemplate
< T > > typeCast (const ParameterPtr &other)
Protected Attributes
Vector< String > _valueMeaning
Vector< String > _valueDescription
Protected Attributes inherited from Voxel::ParameterTemplate< T >
T _value
Protected Attributes inherited from Voxel::Parameter
uint32_t _address
uint32_t _mask
uint8_t _msb
uint8_t _lsb
uint8_t _registerLength
IOType _ioType
String _name
String _displayName
String _description
Vector< String > _dependencies
RegisterProgrammer & _programmer
Additional Inherited Members
Public Types inherited from Voxel::Parameter
enum IOType { IO_READ_ONLY = 0, IO_READ_WRITE, IO_WRITE_ONLY }
Protected Member Functions inherited from Voxel::ParameterTemplate< T >
virtual uint32_t _toRawValue (T value) const
virtual T _fromRawValue (uint32_t value) const
Protected Member Functions inherited from Voxel::Parameter
void _computeMask ()
Detailed Description
template<typename T>
class Voxel::EnumParameterTemplate< T >
Definition at line 190 of file Parameter.h.
Constructor & Destructor Documentation
template<typename T> Voxel::EnumParameterTemplate< T >::EnumParameterTemplate (RegisterProgrammer & programmer, const String & name, uint32_t address, uint8_t registerLength, uint8_t msb, uint8_t lsb, const Vector< String > & valueDescription, const Vector< String > & valueMeaning, const T & defaultValue, const String & displayName, const String & description, Parameter::IOType ioType = Parameter::IO_READ_WRITE, const Vector< String > & dependencies = {}) inline
Definition at line 197 of file Parameter.h.
                                                                                                                                                             {}):
   ParameterTemplate<T>(programmer, name, address, registerLength, msb, lsb, defaultValue, displayName, description, ioType, dependencies), _valueDescription(valueDescription), _valueMeaning(valueMeaning)
   {
   }
template<typename T> virtual Voxel::EnumParameterTemplate< T >::~EnumParameterTemplate () inline virtual
Definition at line 212 of file Parameter.h.
 {}
Member Function Documentation
template<typename T> static Ptr<EnumParameterTemplate<T> > Voxel::EnumParameterTemplate< T >::typeCast (const ParameterPtr & other) inline static
Definition at line 204 of file Parameter.h.
   {
     return std::dynamic_pointer_cast<EnumParameterTemplate<T>>(other);
   }
template<typename T> const Vector<String>& Voxel::EnumParameterTemplate< T >::valueDescription () const inline
Definition at line 209 of file Parameter.h.
Referenced by Voxel::CLIManager::_showParameterInfo().
 { return _valueDescription; }
template<typename T> const Vector<String>& Voxel::EnumParameterTemplate< T >::valueMeaning () const inline
Definition at line 210 of file Parameter.h.
Referenced by Voxel::CLIManager::_getParameter(), and Voxel::CLIManager::_showParameterInfo().
 { return _valueMeaning; }
Member Data Documentation
template<typename T> Vector<String> Voxel::EnumParameterTemplate< T >::_valueDescription protected
Definition at line 194 of file Parameter.h.
template<typename T> Vector<String> Voxel::EnumParameterTemplate< T >::_valueMeaning protected
Definition at line 193 of file Parameter.h.
The documentation for this class was generated from the following file:
Parameter.h