Voxel: ELFIO::segment Class Reference
ELFIO::segment Class Reference abstract
#include <elfio_segment.hpp>
Public Member Functions
virtual ~segment ()
ELFIO_GET_ACCESS_DECL (Elf_Half, index)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, type)
ELFIO_GET_SET_ACCESS_DECL (Elf_Word, flags)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, align)
ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr, virtual_address)
ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr, physical_address)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, file_size)
ELFIO_GET_SET_ACCESS_DECL (Elf_Xword, memory_size)
ELFIO_GET_ACCESS_DECL (Elf64_Off, offset)
virtual const char * get_data () const =0
virtual Elf_Half add_section_index (Elf_Half index, Elf_Xword addr_align)=0
virtual Elf_Half get_sections_num () const =0
virtual Elf_Half get_section_index_at (Elf_Half num) const =0
virtual bool is_offset_initialized () const =0
Protected Member Functions
ELFIO_SET_ACCESS_DECL (Elf64_Off, offset)
ELFIO_SET_ACCESS_DECL (Elf_Half, index)
virtual const std::vector
< Elf_Half > & get_sections () const =0
virtual void load (std::istream &stream, std::streampos header_offset)=0
virtual void save (std::ostream &f, std::streampos header_offset, std::streampos data_offset)=0
Friends
class elfio
Detailed Description
Definition at line 31 of file elfio_segment.hpp.
Constructor & Destructor Documentation
virtual ELFIO::segment::~segment () inline virtual
Definition at line 35 of file elfio_segment.hpp.
 {};
Member Function Documentation
virtual Elf_Half ELFIO::segment::add_section_index (Elf_Half index, Elf_Xword addr_align) pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::elfio::load_segments().
ELFIO::segment::ELFIO_GET_ACCESS_DECL (Elf_Half , index)
ELFIO::segment::ELFIO_GET_ACCESS_DECL (Elf64_Off , offset)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf_Word , type)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf_Word , flags)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , align)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr , virtual_address)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf64_Addr , physical_address)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , file_size)
ELFIO::segment::ELFIO_GET_SET_ACCESS_DECL (Elf_Xword , memory_size)
ELFIO::segment::ELFIO_SET_ACCESS_DECL (Elf64_Off , offset) protected
ELFIO::segment::ELFIO_SET_ACCESS_DECL (Elf_Half , index) protected
virtual const char* ELFIO::segment::get_data () const pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::dump::segment_data().
virtual Elf_Half ELFIO::segment::get_section_index_at (Elf_Half num) const pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::elfio::layout_segments_and_their_sections().
virtual const std::vector<Elf_Half>& ELFIO::segment::get_sections () const protected pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::elfio::is_subsequence_of().
virtual Elf_Half ELFIO::segment::get_sections_num () const pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::elfio::layout_segments_and_their_sections().
virtual bool ELFIO::segment::is_offset_initialized () const pure virtual
Implemented in ELFIO::segment_impl< T >.
virtual void ELFIO::segment::load (std::istream & stream, std::streampos header_offset) protected pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::elfio::load_segments().
virtual void ELFIO::segment::save (std::ostream & f, std::streampos header_offset, std::streampos data_offset) protected pure virtual
Implemented in ELFIO::segment_impl< T >.
Referenced by ELFIO::elfio::save_segments().
Friends And Related Function Documentation
friend class elfio friend
Definition at line 33 of file elfio_segment.hpp.
The documentation for this class was generated from the following file:
elfio_segment.hpp