Voxel: Voxel::Downloader Class Reference
Voxel::Downloader Class Reference abstract
I/O classes
#include <Downloader.h>
Public Types
typedef Function< void(float)> ProgressFunctionType
Public Member Functions
Downloader (DevicePtr device)
virtual bool download (const String &file)=0
void setLogCallback (LoggerOutStream::LoggerOutStreamFunctionType f)
void removeLogCallback ()
void setProgressFunction (ProgressFunctionType f)
void removeProgressFunction ()
float getProgress ()
virtual ~Downloader ()
Protected Member Functions
virtual bool _locateFile (String &file)
void _setProgress (float progress)
void _setProgressIncrement (float progress)
Protected Attributes
DevicePtr _device
LoggerOutStream _outStream
ProgressFunctionType _progressFunction
float _progress = 0
Detailed Description
Definition at line 23 of file Downloader.h.
Member Typedef Documentation
typedef Function<void(float)> Voxel::Downloader::ProgressFunctionType
Definition at line 26 of file Downloader.h.
Constructor & Destructor Documentation
Voxel::Downloader::Downloader (DevicePtr device) inline
Definition at line 54 of file Downloader.h.
 : _device(device) {}
virtual Voxel::Downloader::~Downloader () inline virtual
Definition at line 65 of file Downloader.h.
 {}
Member Function Documentation
bool Voxel::Downloader::_locateFile (String & file) protected virtual
Definition at line 17 of file Downloader.cpp.
References Voxel::Configuration::getFirmwareFile().
Referenced by Voxel::USBDownloader::download().
 {
   Configuration c;
   if(c.getFirmwareFile(file))
     return true;
   // Try name as is, to see whether it is valid by itself. That is,
   // it could be an absolute path or path relative to current working directory
   std::ifstream f(file, std::ios::binary);
   if(f.good())
     return true;
   return false;
 }
void Voxel::Downloader::_setProgress (float progress) inline protected
Definition at line 37 of file Downloader.h.
Referenced by Voxel::TI::TintinEEPROMDownloader::_configureForDownload(), Voxel::USBDownloader::_configureForDownload(), Voxel::TI::TintinEEPROMDownloader::_download(), Voxel::USBDownloader::_download(), and Voxel::USBDownloader::download().
   {
     _progress = (progress > 100?100:progress);
     if(_progress < 0)
       _progress = 0;
     if(_progressFunction)
       _progressFunction(progress);
   }
void Voxel::Downloader::_setProgressIncrement (float progress) inline protected
Definition at line 48 of file Downloader.h.
   {
     _setProgress(_progress + progress);
   }
virtual bool Voxel::Downloader::download (const String & file) pure virtual
Implemented in Voxel::USBDownloader.
float Voxel::Downloader::getProgress () inline
Definition at line 63 of file Downloader.h.
Referenced by Voxel::TI::TintinEEPROMDownloader::_download(), and Voxel::USBDownloader::_download().
 { return _progress; }
void Voxel::Downloader::removeLogCallback () inline
Definition at line 59 of file Downloader.h.
 { _outStream.setOutputFunction(nullptr); }
void Voxel::Downloader::removeProgressFunction () inline
Definition at line 62 of file Downloader.h.
 { _progressFunction = nullptr; }
void Voxel::Downloader::setLogCallback (LoggerOutStream::LoggerOutStreamFunctionType f) inline
Definition at line 58 of file Downloader.h.
 { _outStream.setOutputFunction(f); }
void Voxel::Downloader::setProgressFunction (ProgressFunctionType f) inline
Definition at line 61 of file Downloader.h.
 { _progressFunction = f; }
Member Data Documentation
DevicePtr Voxel::Downloader::_device protected
Definition at line 29 of file Downloader.h.
Referenced by Voxel::TI::TintinEEPROMDownloader::_configureForDownload().
LoggerOutStream Voxel::Downloader::_outStream protected
Definition at line 30 of file Downloader.h.
Referenced by Voxel::TI::TintinEEPROMDownloader::_configureForDownload(), Voxel::USBDownloader::_configureForDownload(), Voxel::TI::TintinEEPROMDownloader::_download(), Voxel::TI::TintinEEPROMDownloader::_getEEPROMStatus(), Voxel::TI::TintinEEPROMDownloader::_printEEPROMFirst64Bytes(), and Voxel::USBDownloader::download().
float Voxel::Downloader::_progress = 0 protected
Definition at line 36 of file Downloader.h.
ProgressFunctionType Voxel::Downloader::_progressFunction protected
Definition at line 32 of file Downloader.h.
The documentation for this class was generated from the following files:
Downloader.h
Downloader.cpp