Voxel: Voxel::TI::RTS5825CameraUVCStreamer Class Reference
Voxel::TI::RTS5825CameraUVCStreamer Class Reference
Public Member Functions
bool start ()
bool stop ()
bool isRunning ()
bool setVideoMode (const VideoMode &videoMode)
RTS5825CameraUVCStreamer (DevicePtr device)
virtual ~RTS5825CameraUVCStreamer ()
Public Member Functions inherited from Voxel::UVCStreamer
UVCStreamer (DevicePtr device)
virtual bool isInitialized ()
virtual bool getSupportedVideoModes (Vector< VideoMode > &videoModes)
virtual bool getCurrentVideoMode (VideoMode &videoMode)
virtual ~UVCStreamer ()
Public Member Functions inherited from Voxel::Streamer
Streamer (DevicePtr device)
virtual ~Streamer ()
virtual bool capture (RawDataFramePtr &p)
Protected Attributes
bool _isReallyRunning = false
Protected Attributes inherited from Voxel::UVCStreamer
Ptr< UVCStreamerPrivate > _uvcStreamerPrivate
Ptr< VideoMode > _currentVideoMode
Protected Attributes inherited from Voxel::Streamer
DevicePtr _device
Timer _time
int _currentID = -1
TimeStampType _currentTimeStamp = 0
bool _isRunning = false
Additional Inherited Members
Protected Member Functions inherited from Voxel::UVCStreamer
void _storeCurrentVideoMode (const VideoMode &videoMode)
bool _uvcInit ()
bool _initForCapture ()
virtual bool _start ()
virtual bool _capture (RawDataFramePtr &p)
virtual bool _stop ()
Detailed Description
Definition at line 83 of file RTS5825Camera.cpp.
Constructor & Destructor Documentation
Voxel::TI::RTS5825CameraUVCStreamer::RTS5825CameraUVCStreamer (DevicePtr device) inline
Definition at line 109 of file RTS5825Camera.cpp.
References Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, Voxel::FrameRate::numerator, Voxel::UVCStreamer::setVideoMode(), Voxel::Streamer::start(), and Voxel::FrameSize::width.
                                              : UVCStreamer(device)
   {
     VideoMode m;
     m.frameSize.width = 320*2;
     m.frameSize.height = 240;
     m.frameRate.numerator = 25;
     m.frameRate.denominator = 1;
     UVCStreamer::setVideoMode(m);
     UVCStreamer::start();
     std::this_thread::sleep_for(std::chrono::milliseconds(2000));
   }
virtual Voxel::TI::RTS5825CameraUVCStreamer::~RTS5825CameraUVCStreamer () inline virtual
Definition at line 121 of file RTS5825Camera.cpp.
References Voxel::UVCStreamer::isInitialized(), isRunning(), Voxel::Streamer::stop(), and stop().
   {
     if (isInitialized() && isRunning())
       stop();
     UVCStreamer::stop();
   }
Member Function Documentation
bool Voxel::TI::RTS5825CameraUVCStreamer::isRunning () inline virtual
Reimplemented from Voxel::Streamer.
Definition at line 99 of file RTS5825Camera.cpp.
References _isReallyRunning.
Referenced by ~RTS5825CameraUVCStreamer().
   {
     return _isReallyRunning;
   }
bool Voxel::TI::RTS5825CameraUVCStreamer::setVideoMode (const VideoMode & videoMode) inline virtual
Reimplemented from Voxel::UVCStreamer.
Definition at line 104 of file RTS5825Camera.cpp.
   {
     return true;
   }
bool Voxel::TI::RTS5825CameraUVCStreamer::start () inline virtual
Reimplemented from Voxel::Streamer.
Definition at line 88 of file RTS5825Camera.cpp.
References _isReallyRunning.
   {
     return _isReallyRunning = true;
   }
bool Voxel::TI::RTS5825CameraUVCStreamer::stop () inline virtual
Reimplemented from Voxel::Streamer.
Definition at line 93 of file RTS5825Camera.cpp.
References _isReallyRunning.
Referenced by ~RTS5825CameraUVCStreamer().
   {
     _isReallyRunning = false;
     return true;
   }
Member Data Documentation
bool Voxel::TI::RTS5825CameraUVCStreamer::_isReallyRunning = false protected
Definition at line 86 of file RTS5825Camera.cpp.
Referenced by isRunning(), start(), and stop().
The documentation for this class was generated from the following file:
RTS5825Camera.cpp