Voxel: Voxel::ToFRawFrame Class Reference
Voxel::ToFRawFrame Class Reference abstract
Frame related classes
#include <Frame.h>
Public Member Functions
virtual const uint8_t * phase () const =0
virtual uint8_t * phase ()=0
virtual SizeType phaseWordWidth () const =0
virtual const uint8_t * amplitude () const =0
virtual uint8_t * amplitude ()=0
virtual SizeType amplitudeWordWidth () const =0
virtual const uint8_t * flags () const =0
virtual uint8_t * flags ()=0
virtual SizeType flagsWordWidth () const =0
virtual const uint8_t * ambient () const =0
virtual uint8_t * ambient ()=0
virtual SizeType ambientWordWidth () const =0
virtual const uint16_t * histogram () const =0
virtual uint16_t * histogram ()=0
virtual SizeType histogramSize () const =0
virtual ~ToFRawFrame ()
Public Member Functions inherited from Voxel::RawFrame
virtual ~RawFrame ()
Public Member Functions inherited from Voxel::Frame
operator String ()
virtual Ptr< Frame > copy () const =0
virtual Ptr< Frame > copyTo (Ptr< Frame > &other) const =0
virtual Ptr< Frame > newFrame () const =0
virtual bool isSameType (const Frame &other) const =0
virtual bool isSameSize (const Frame &other) const =0
virtual bool serialize (SerializedObject &object) const =0
virtual bool deserialize (SerializedObject &object)=0
virtual ~Frame ()
Static Public Member Functions
static Ptr< ToFRawFrame > typeCast (FramePtr ptr)
Static Public Member Functions inherited from Voxel::RawFrame
static Ptr< RawFrame > typeCast (FramePtr ptr)
Public Attributes
FrameSize size
Public Attributes inherited from Voxel::Frame
TimeStampType timestamp = 0
int id = -1
Detailed Description
Definition at line 168 of file Frame.h.
Constructor & Destructor Documentation
virtual Voxel::ToFRawFrame::~ToFRawFrame () inline virtual
Definition at line 198 of file Frame.h.
 {}
Member Function Documentation
virtual const uint8_t* Voxel::ToFRawFrame::ambient () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual uint8_t* Voxel::ToFRawFrame::ambient () pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual SizeType Voxel::ToFRawFrame::ambientWordWidth () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual const uint8_t* Voxel::ToFRawFrame::amplitude () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual uint8_t* Voxel::ToFRawFrame::amplitude () pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual SizeType Voxel::ToFRawFrame::amplitudeWordWidth () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual const uint8_t* Voxel::ToFRawFrame::flags () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual uint8_t* Voxel::ToFRawFrame::flags () pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual SizeType Voxel::ToFRawFrame::flagsWordWidth () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual const uint16_t* Voxel::ToFRawFrame::histogram () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual uint16_t* Voxel::ToFRawFrame::histogram () pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual SizeType Voxel::ToFRawFrame::histogramSize () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual const uint8_t* Voxel::ToFRawFrame::phase () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
virtual uint8_t* Voxel::ToFRawFrame::phase () pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
virtual SizeType Voxel::ToFRawFrame::phaseWordWidth () const pure virtual
Implemented in Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::CLIManager::_save(), and main().
static Ptr<ToFRawFrame> Voxel::ToFRawFrame::typeCast (FramePtr ptr) inline static
Definition at line 193 of file Frame.h.
   {
     return std::dynamic_pointer_cast<ToFRawFrame>(ptr);
   }
Member Data Documentation
FrameSize Voxel::ToFRawFrame::size
Definition at line 191 of file Frame.h.
Referenced by Voxel::ToFCrossTalkFilter::_filter(), Voxel::IIRFilter::_filter(), Voxel::BilateralFilter::_filter(), Voxel::MedianFilter::_filter(), Voxel::SmoothFilter::_filter(), Voxel::TemporalMedianFilter::_filter(), Voxel::TI::ToFFrameGenerator::_generateToFRawFrame(), Voxel::CLIManager::_save(), Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >::copyTo(), Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >::deserialize(), Voxel::TI::ToFFrameGenerator::generate(), Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >::isSameSize(), main(), Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >::newFrame(), and Voxel::ToFRawFrameTemplate< PhaseByteType, AmbientByteType >::serialize().
The documentation for this class was generated from the following file:
Frame.h