Voxel: Voxel::UVC Class Reference
Voxel::UVC Class Reference
I/O classes
#include <UVC.h>
Public Member Functions
UVC (DevicePtr usb)
virtual bool isInitialized ()
UVCPrivate & getUVCPrivate ()
bool read (uint8_t *buffer, std::size_t size)
virtual ~UVC ()
Protected Attributes
DevicePtr _usb
Ptr< UVCPrivate > _uvcPrivate
Detailed Description
Definition at line 31 of file UVC.h.
Constructor & Destructor Documentation
Voxel::UVC::UVC (DevicePtr usb)
Definition at line 24 of file UVC.cpp.
References _uvcPrivate, and Voxel::UVCPrivate.
                      : _usb(usb)
 {
   _uvcPrivate = Ptr<UVCPrivate>(new UVCPrivate(usb));
 }
Voxel::UVC::~UVC () virtual
Definition at line 41 of file UVC.cpp.
 {}
Member Function Documentation
UVCPrivate& Voxel::UVC::getUVCPrivate () inline
Definition at line 43 of file UVC.h.
Referenced by Voxel::UVCXU::getControl(), and Voxel::UVCXU::setControl().
 { return *_uvcPrivate; }
bool Voxel::UVC::isInitialized () virtual
Reimplemented in Voxel::UVCXU.
Definition at line 29 of file UVC.cpp.
References _uvcPrivate.
Referenced by Voxel::UVCXU::isInitialized(), and Voxel::UVCXU::UVCXU().
 {
   return _uvcPrivate->isInitialized();
 }
bool Voxel::UVC::read (uint8_t * buffer, std::size_t size)
TODO This is untested code as Voxel-14 does not support read as of now buffer is assumed to have capacity of atleast "size" bytes
Definition at line 36 of file UVC.cpp.
References _uvcPrivate.
 {
   return _uvcPrivate->read(buffer, size);
 }
Member Data Documentation
DevicePtr Voxel::UVC::_usb protected
Definition at line 34 of file UVC.h.
Referenced by Voxel::UVCXU::getControl(), and Voxel::UVCXU::setControl().
Ptr<UVCPrivate> Voxel::UVC::_uvcPrivate protected
Definition at line 36 of file UVC.h.
Referenced by isInitialized(), read(), UVC(), and Voxel::UVCXU::UVCXU().
The documentation for this class was generated from the following files:
UVC.h
UVC.cpp