Voxel: Voxel::DepthCameraLibrary Class Reference
Voxel::DepthCameraLibrary Class Reference
Camera System Components
#include <DepthCameraLibrary.h>
Public Member Functions
DepthCameraLibrary (const String &libName)
bool load ()
bool isLoaded ()
DepthCameraFactoryPtr getDepthCameraFactory ()
FilterFactoryPtr getFilterFactory ()
DownloaderFactoryPtr getDownloaderFactory ()
int getABIVersion ()
virtual ~DepthCameraLibrary ()
Protected Attributes
String _libName
Ptr< DepthCameraLibraryPrivate > _libraryPrivate
Detailed Description
Definition at line 25 of file DepthCameraLibrary.h.
Constructor & Destructor Documentation
Voxel::DepthCameraLibrary::DepthCameraLibrary (const String & libName)
Definition at line 65 of file DepthCameraLibrary.cpp.
                                                             : _libName(libName),
 _libraryPrivate(Ptr<DepthCameraLibraryPrivate>(new DepthCameraLibraryPrivate())) {}
Voxel::DepthCameraLibrary::~DepthCameraLibrary () virtual
Definition at line 187 of file DepthCameraLibrary.cpp.
References _libraryPrivate, and isLoaded().
 {
   if(isLoaded())
   {
 #ifdef LINUX
     dlclose(_libraryPrivate->handle);
 #elif defined(WINDOWS)
     FreeLibrary(_libraryPrivate->handle);
 #endif
     _libraryPrivate->handle = 0;
   }
 }
Member Function Documentation
int Voxel::DepthCameraLibrary::getABIVersion ()
Definition at line 164 of file DepthCameraLibrary.cpp.
References _libName, _libraryPrivate, Voxel::dynamicLoadError(), isLoaded(), Voxel::LOG_DEBUG, and Voxel::logger.
 {
   if (!isLoaded())
     return -1;
   char symbol[] = "getABIVersion";
 #ifdef LINUX
   GetABIVersion g = (GetABIVersion)dlsym(_libraryPrivate->handle, symbol);
 #elif defined(WINDOWS)
   GetABIVersion g = (GetABIVersion)GetProcAddress(_libraryPrivate->handle, symbol);
 #endif
   String error;
   if(!g && (error = dynamicLoadError()).size())
   {
     logger(LOG_DEBUG) << "DepthCameraLibrary: Failed to load symbol " << symbol << " from library " << _libName << ". Error: " << error << std::endl;
     return 0;
   }
   return (*g)();
 }
DepthCameraFactoryPtr Voxel::DepthCameraLibrary::getDepthCameraFactory ()
Definition at line 86 of file DepthCameraLibrary.cpp.
References _libName, _libraryPrivate, Voxel::dynamicLoadError(), isLoaded(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(!isLoaded())
     return 0;
   char symbol[] = "getDepthCameraFactory";
 #ifdef LINUX
   GetDepthCameraFactory g = (GetDepthCameraFactory)dlsym(_libraryPrivate->handle, symbol);
 #elif defined(WINDOWS)
   GetDepthCameraFactory g = (GetDepthCameraFactory)GetProcAddress(_libraryPrivate->handle, symbol);
 #endif
   String error;
   if (!g && (error = dynamicLoadError()).size())
   {
     logger(LOG_ERROR) << "DepthCameraLibrary: Failed to load symbol " << symbol << " from library " << _libName << ". Error: " << error << std::endl;
     return 0;
   }
   DepthCameraFactoryPtr p;
   (*g)(p);
   return p;
 }
DownloaderFactoryPtr Voxel::DepthCameraLibrary::getDownloaderFactory ()
Definition at line 138 of file DepthCameraLibrary.cpp.
References _libName, _libraryPrivate, Voxel::dynamicLoadError(), isLoaded(), Voxel::LOG_DEBUG, and Voxel::logger.
 {
   if(!isLoaded())
     return 0;
   char symbol[] = "getDownloaderFactory";
   #ifdef LINUX
   GetDownloaderFactory g = (GetDownloaderFactory)dlsym(_libraryPrivate->handle, symbol);
   #elif defined(WINDOWS)
   GetDownloaderFactory g = (GetDownloaderFactory)GetProcAddress(_libraryPrivate->handle, symbol);
   #endif
   String error;
   if(!g && (error = dynamicLoadError()).size())
   {
     logger(LOG_DEBUG) << "DepthCameraLibrary: Failed to load symbol " << symbol << " from library " << _libName << ". Error: " << error << std::endl;
     return 0;
   }
   DownloaderFactoryPtr p;
   (*g)(p);
   return p;
 }
FilterFactoryPtr Voxel::DepthCameraLibrary::getFilterFactory ()
Definition at line 112 of file DepthCameraLibrary.cpp.
References _libName, _libraryPrivate, Voxel::dynamicLoadError(), isLoaded(), Voxel::LOG_DEBUG, and Voxel::logger.
 {
   if(!isLoaded())
     return 0;
   char symbol[] = "getFilterFactory";
   #ifdef LINUX
   GetFilterFactory g = (GetFilterFactory)dlsym(_libraryPrivate->handle, symbol);
   #elif defined(WINDOWS)
   GetFilterFactory g = (GetFilterFactory)GetProcAddress(_libraryPrivate->handle, symbol);
   #endif
   String error;
   if(!g && (error = dynamicLoadError()).size())
   {
     logger(LOG_DEBUG) << "DepthCameraLibrary: Failed to load symbol " << symbol << " from library " << _libName << ". Error: " << error << std::endl;
     return 0;
   }
   FilterFactoryPtr p;
   (*g)(p);
   return p;
 }
bool Voxel::DepthCameraLibrary::isLoaded () inline
Definition at line 84 of file DepthCameraLibrary.cpp.
References _libraryPrivate.
Referenced by getABIVersion(), getDepthCameraFactory(), getDownloaderFactory(), getFilterFactory(), and ~DepthCameraLibrary().
 { return _libraryPrivate->handle; }
bool Voxel::DepthCameraLibrary::load ()
Definition at line 68 of file DepthCameraLibrary.cpp.
References _libName, _libraryPrivate, Voxel::dynamicLoadError(), Voxel::LOG_ERROR, and Voxel::logger.
 {
 #ifdef LINUX
   _libraryPrivate->handle = dlopen(_libName.c_str(), RTLD_LAZY);
 #elif defined(WINDOWS)
   _libraryPrivate->handle = LoadLibrary(_libName.c_str());
 #endif
   if(!_libraryPrivate->handle)
   {
     logger(LOG_ERROR) << "DepthCameraLibrary: Failed to load " << _libName << ". Error: " << dynamicLoadError() << std::endl;
     return false;
   }
   return true;
 }
Member Data Documentation
String Voxel::DepthCameraLibrary::_libName protected
Definition at line 28 of file DepthCameraLibrary.h.
Referenced by getABIVersion(), getDepthCameraFactory(), getDownloaderFactory(), getFilterFactory(), and load().
Ptr<DepthCameraLibraryPrivate> Voxel::DepthCameraLibrary::_libraryPrivate protected
Definition at line 30 of file DepthCameraLibrary.h.
Referenced by getABIVersion(), getDepthCameraFactory(), getDownloaderFactory(), getFilterFactory(), isLoaded(), load(), and ~DepthCameraLibrary().
The documentation for this class was generated from the following files:
DepthCameraLibrary.h
DepthCameraLibrary.cpp