Voxel: Voxel::IIRFilter Class Reference
Voxel::IIRFilter Class Reference
Filter related classes
#include <IIRFilter.h>
Public Member Functions
IIRFilter (float gain=0.5)
virtual void reset ()
virtual ~IIRFilter ()
Public Member Functions inherited from Voxel::Filter
Filter (const String &name, const String &description="", const String &nameScope="")
void setDepthCamera (const DepthCameraPtr &d)
const Map< String,
FilterParameterPtr > & parameters ()
const String & name ()
const String & description ()
void setNameScope (const String &scope)
bool filter (const FramePtr &in, FramePtr &out)
FilterParameterConstPtr getParam (const String &name) const
template<typename T >
bool get (const String &name, T &value)
template<typename T >
bool set (const String &name, const T &value)
virtual ~Filter ()
Protected Member Functions
template<typename T >
bool _filter (const T *in, T *out)
virtual bool _filter (const FramePtr &in, FramePtr &out)
virtual void _onSet (const FilterParameterPtr &f)
Protected Member Functions inherited from Voxel::Filter
void _makeID ()
virtual bool _addParameters (const Vector< FilterParameterPtr > &params)
virtual bool _prepareOutput (const FramePtr &in, FramePtr &out)
template<typename T >
bool _get (const String &name, T &value)
template<typename T >
bool _set (const String &name, const T &value)
Protected Attributes
float _gain
Vector< ByteType > _current
FrameSize _size
Protected Attributes inherited from Voxel::Filter
String _name
String _nameScope
String _description
String _id
Mutex _accessMutex
DepthCameraPtr _depthCamera
Map< String, FilterParameterPtr > _parameters
Detailed Description
Definition at line 22 of file IIRFilter.h.
Constructor & Destructor Documentation
Voxel::IIRFilter::IIRFilter (float gain = 0.5)
Definition at line 12 of file IIRFilter.cpp.
References Voxel::Filter::_addParameters().
                               : Filter("IIRFilter"), _gain(gain)
 {
   _addParameters({
     FilterParameterPtr(new FloatFilterParameter("gain", "Gain", "IIR gain coefficient", gain, "", 0.0f, 1.0f))
   });
 }
virtual Voxel::IIRFilter::~IIRFilter () inline virtual
Definition at line 42 of file IIRFilter.h.
 {}
Member Function Documentation
template<typename T > bool Voxel::IIRFilter::_filter (const T * in, T * out) protected
Definition at line 34 of file IIRFilter.cpp.
References _current, _gain, _size, Voxel::FrameSize::height, and Voxel::FrameSize::width.
 {
   uint s = _size.width*_size.height;
   T *cur;
   if(_current.size() != s*sizeof(T))
   {
     _current.resize(s*sizeof(T));
     memset(_current.data(), 0, s*sizeof(T));
   }
   cur = (T *)_current.data();
   for(auto i = 0; i < s; i++)
     out[i] = cur[i] = cur[i]*(1.0 - _gain) + in[i]*_gain;
   return true;
 }
bool Voxel::IIRFilter::_filter (const FramePtr & in, FramePtr & out) protected virtual
Implements Voxel::Filter.
Definition at line 54 of file IIRFilter.cpp.
References Voxel::Filter::_prepareOutput(), _size, Voxel::ToFRawFrame::ambient(), Voxel::ToFRawFrame::ambientWordWidth(), Voxel::DepthFrame::amplitude, Voxel::ToFRawFrame::amplitude(), Voxel::ToFRawFrame::amplitudeWordWidth(), Voxel::DepthFrame::depth, Voxel::ToFRawFrame::flags(), Voxel::ToFRawFrame::flagsWordWidth(), Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::ToFRawFrame::phase(), Voxel::ToFRawFrame::phaseWordWidth(), Voxel::DepthFrame::size, Voxel::ToFRawFrame::size, CameraSystemIQFrameTest::tofFrame, and Voxel::FrameSize::width.
 {
   ToFRawFrame *tofFrame = dynamic_cast<ToFRawFrame *>(in.get());
   DepthFrame *depthFrame = dynamic_cast<DepthFrame *>(in.get());
   if((!tofFrame && !depthFrame) || !_prepareOutput(in, out))
   {
     logger(LOG_ERROR) << "IIRFilter: Input frame type is not ToFRawFrame or DepthFrame or failed get the output ready" << std::endl;
     return false;
   }
   if(tofFrame)
   {
     _size = tofFrame->size;
     ToFRawFrame *o = dynamic_cast<ToFRawFrame *>(out.get());
     if(!o)
     {
       logger(LOG_ERROR) << "IIRFilter: Invalid frame type. Expecting ToFRawFrame." << std::endl;
       return false;
     }
     //logger(LOG_INFO) << "IIRFilter: Applying filter with gain = " << _gain << " to ToFRawFrame id = " << tofFrame->id << std::endl;
     uint s = _size.width*_size.height;
     memcpy(o->ambient(), tofFrame->ambient(), s*tofFrame->ambientWordWidth());
     memcpy(o->amplitude(), tofFrame->amplitude(), s*tofFrame->amplitudeWordWidth());
     memcpy(o->flags(), tofFrame->flags(), s*tofFrame->flagsWordWidth());
     if(tofFrame->phaseWordWidth() == 2)
       return _filter<uint16_t>((uint16_t *)tofFrame->phase(), (uint16_t *)o->phase());
     else if(tofFrame->phaseWordWidth() == 1)
       return _filter<uint8_t>((uint8_t *)tofFrame->phase(), (uint8_t *)o->phase());
     else if(tofFrame->phaseWordWidth() == 4)
       return _filter<uint32_t>((uint32_t *)tofFrame->phase(), (uint32_t *)o->phase());
     else
       return false;
   }
   else if(depthFrame)
   {
     _size = depthFrame->size;
     DepthFrame *o = dynamic_cast<DepthFrame *>(out.get());
     if(!o)
     {
       logger(LOG_ERROR) << "IIRFilter: Invalid frame type. Expecting DepthFrame." << std::endl;
       return false;
     }
     o->amplitude = depthFrame->amplitude;
     return _filter<float>(depthFrame->depth.data(), o->depth.data());
   }
   else
     return false;
 }
void Voxel::IIRFilter::_onSet (const FilterParameterPtr & f) protected virtual
Implements Voxel::Filter.
Definition at line 19 of file IIRFilter.cpp.
References _gain, Voxel::Filter::_get(), Voxel::LOG_WARNING, and Voxel::logger.
 {
   if(f->name() == "gain")
     if(!_get(f->name(), _gain))
     {
       logger(LOG_WARNING) << "IIRFilter:  Could not get the recently updated 'gain' parameter" << std::endl;
     }
 }
void Voxel::IIRFilter::reset () virtual
Implements Voxel::Filter.
Definition at line 28 of file IIRFilter.cpp.
References _current.
 {
   _current.clear();
 }
Member Data Documentation
Vector<ByteType> Voxel::IIRFilter::_current protected
Definition at line 26 of file IIRFilter.h.
Referenced by _filter(), and reset().
float Voxel::IIRFilter::_gain protected
Definition at line 25 of file IIRFilter.h.
Referenced by _filter(), and _onSet().
FrameSize Voxel::IIRFilter::_size protected
Definition at line 28 of file IIRFilter.h.
Referenced by _filter().
The documentation for this class was generated from the following files:
IIRFilter.h
IIRFilter.cpp