Voxel: Voxel::PointCloudFrame Class Reference
Voxel::PointCloudFrame Class Reference abstract
Frame related classes
#include <Frame.h>
Public Member Functions
virtual SizeType size () const =0
virtual Point * operator[] (IndexType index)=0
virtual ~PointCloudFrame ()
Public Member Functions inherited from Voxel::Frame
operator String ()
virtual Ptr< Frame > copy () const =0
virtual Ptr< Frame > copyTo (Ptr< Frame > &other) const =0
virtual Ptr< Frame > newFrame () const =0
virtual bool isSameType (const Frame &other) const =0
virtual bool isSameSize (const Frame &other) const =0
virtual bool serialize (SerializedObject &object) const =0
virtual bool deserialize (SerializedObject &object)=0
virtual ~Frame ()
Static Public Member Functions
static Ptr< PointCloudFrame > typeCast (FramePtr ptr)
Additional Inherited Members
Public Attributes inherited from Voxel::Frame
TimeStampType timestamp = 0
int id = -1
Detailed Description
Definition at line 645 of file Frame.h.
Constructor & Destructor Documentation
virtual Voxel::PointCloudFrame::~PointCloudFrame () inline virtual
Definition at line 656 of file Frame.h.
 {}
Member Function Documentation
virtual Point* Voxel::PointCloudFrame::operator[] (IndexType index) pure virtual
Implemented in Voxel::PointCloudFrameTemplate< PointType >.
virtual SizeType Voxel::PointCloudFrame::size () const pure virtual
Implemented in Voxel::PointCloudFrameTemplate< PointType >.
Referenced by Voxel::PointCloudTransform::depthToPointCloud(), and main().
static Ptr<PointCloudFrame> Voxel::PointCloudFrame::typeCast (FramePtr ptr) inline static
Definition at line 651 of file Frame.h.
Referenced by CameraSystemTest::callback().
   {
     return std::dynamic_pointer_cast<PointCloudFrame>(ptr);
   }
The documentation for this class was generated from the following file:
Frame.h