Voxel: Voxel::UVCPrivate Class Reference
Voxel::UVCPrivate Class Reference
I/O classes
#include <UVCPrivateLinux.h>
Public Member Functions
UVCPrivate (DevicePtr usb)
bool isInitialized ()
int xioctl (int request, void *arg)
bool read (uint8_t *buffer, std::size_t size)
bool mmap (uint32_t offset, UVCRawData &data)
bool clearMMap ()
bool isReadReady (TimeStampType timeout, bool &timedOut)
virtual ~UVCPrivate ()
UVCPrivate (DevicePtr usb)
bool isInitialized ()
IBaseFilter * getCaptureFilter ()
bool read (uint8_t *buffer, std::size_t size)
virtual ~UVCPrivate ()
Protected Member Functions
bool _munmap (UVCRawData &data)
Protected Attributes
int _fd = -1
String _deviceNode
DevicePtr _usb
Vector< UVCRawData > _mappedRawData
Private Attributes
Ptr< IBaseFilter > _captureFilter
Detailed Description
Definition at line 25 of file UVCPrivateLinux.h.
Constructor & Destructor Documentation
Voxel::UVCPrivate::UVCPrivate (DevicePtr usb)
Definition at line 118 of file UVCPrivateLinux.cpp.
References _deviceNode, _fd, _usb, Voxel::USBSystem::getDeviceNode(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, CameraSystemTest::sys, and Voxel::Device::USB.
                                    : _usb(usb), _fd(-1)
 {
   USBSystem sys;
   if(usb->interfaceID() != Device::USB)
     return;
   _deviceNode = sys.getDeviceNode((USBDevice &)*usb);
   if(_deviceNode.size() > 0)
   {
     logger(LOG_INFO) << "UVC: Connecting to UVC device '" << _deviceNode << "'" << std::endl;
     _fd = open(_deviceNode.c_str(), O_RDWR | O_NONBLOCK);
     if(_fd == -1)
       logger(LOG_ERROR) << "Could not open device node " << _deviceNode << ". Please check for permissions." << std::endl;
   }
   else
     logger(LOG_ERROR) << "Could not located device node for " << _usb->id() << "." << std::endl;
 }
Voxel::UVCPrivate::~UVCPrivate () virtual
Definition at line 140 of file UVCPrivateLinux.cpp.
References _fd, and clearMMap().
 {
   if(_fd >= 0)
   {
     clearMMap();
     close(_fd);
     _fd = 0;
   }
 }
Voxel::UVCPrivate::UVCPrivate (DevicePtr usb)
virtual Voxel::UVCPrivate::~UVCPrivate () virtual
Member Function Documentation
bool Voxel::UVCPrivate::_munmap (UVCRawData & data) protected
Definition at line 110 of file UVCPrivateLinux.cpp.
References Voxel::UVCRawData::data, isInitialized(), and Voxel::UVCRawData::size.
Referenced by clearMMap().
 {
   if(!isInitialized())
     return false;
   return ::munmap((void *)&*data.data, data.size) == -1;
 }
bool Voxel::UVCPrivate::clearMMap ()
Definition at line 151 of file UVCPrivateLinux.cpp.
References _mappedRawData, _munmap(), and isInitialized().
Referenced by ~UVCPrivate().
 {
   if(isInitialized() && _mappedRawData.size() > 0)
   {
     for(auto i = 0; i < _mappedRawData.size(); i++)
       _munmap(_mappedRawData[i]);
     _mappedRawData.clear();
     return true;
   }
   return false;
 }
IBaseFilter* Voxel::UVCPrivate::getCaptureFilter () inline
Definition at line 33 of file UVCPrivateWindows.h.
 { return _captureFilter.get(); }
bool Voxel::UVCPrivate::isInitialized () inline
Definition at line 30 of file UVCPrivateWindows.h.
 { return (bool)_captureFilter; }
bool Voxel::UVCPrivate::isInitialized () inline
Definition at line 39 of file UVCPrivateLinux.h.
References _fd.
Referenced by _munmap(), clearMMap(), isReadReady(), mmap(), read(), and xioctl().
 { return _fd >= 0; }
bool Voxel::UVCPrivate::isReadReady (TimeStampType timeout, bool & timedOut)
Definition at line 164 of file UVCPrivateLinux.cpp.
References _fd, isInitialized(), and CameraSystemIQFrameTest::r.
 {
   timedOut = false;
   if(!isInitialized())
     return false;
   while(1)
   {
     fd_set fds;
     struct timeval tv;
     int r;
     FD_ZERO(&fds);
     FD_SET(_fd, &fds);
     /* Timeout. */
     tv.tv_sec = timeout/1000;
     tv.tv_usec = (timeout % 1000)*1000;
     r = select(_fd + 1, &fds, NULL, NULL, &tv);
     if(r == -1)
     {
       if(EINTR == errno)
         continue;
       return false;
     }
     if(r == 0)
     {
       timedOut = true;
       return false;
     }
     return true;
   }
 }
bool Voxel::UVCPrivate::mmap (uint32_t offset, UVCRawData & data)
Definition at line 90 of file UVCPrivateLinux.cpp.
References _fd, _mappedRawData, Voxel::UVCRawData::data, isInitialized(), and Voxel::UVCRawData::size.
 {
   if(!isInitialized())
     return false;
   void *d = ::mmap(NULL /* start anywhere */,
                     data.size,
                     PROT_READ | PROT_WRITE /* required */,
                     MAP_SHARED /* recommended */,
                     _fd, offset);
   if(d == MAP_FAILED)
     return false;
   data.data = Ptr<ByteType>((ByteType *)d, [](ByteType *){}); // encasing in Ptr<> with a null deleter
   _mappedRawData.push_back(data);
   return true;
 }
bool Voxel::UVCPrivate::read (uint8_t * buffer, std::size_t size)
bool Voxel::UVCPrivate::read (uint8_t * buffer, std::size_t size)
TODO This is untested code as Voxel-14 does not support read as of now buffer is assumed to have capacity of atleast "size" bytes
Definition at line 46 of file UVCPrivateLinux.cpp.
References _fd, FD_RETRY_LIMIT, isInitialized(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(!isInitialized())
     return false;
   int64_t toRead = size;
   int64_t bytesRead;
   int retryCount = 0;
   while(toRead > 0)
   {
     bytesRead = ::read(_fd, (void *)(buffer + (size - toRead)), toRead);
     if(bytesRead > 0)
     {
       toRead -= bytesRead;
       retryCount = 0;
     }
     else if(bytesRead == -1) // error condition
     {
       if(errno == EAGAIN || errno == EWOULDBLOCK)
       {
         retryCount++;
         if(retryCount < FD_RETRY_LIMIT)
           continue;
         else
         {
           logger(LOG_ERROR) << "UVC: Hit maximum number (" << FD_RETRY_LIMIT << ") of retries to read data" << std::endl;
           return false;
         }
       }
       else
         return false;
     }
   }
   assert(toRead == 0);
   return true;
 }
int Voxel::UVCPrivate::xioctl (int request, void * arg)
Definition at line 25 of file UVCPrivateLinux.cpp.
References _fd, FD_RETRY_LIMIT, isInitialized(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::UVCXU::getControl(), and Voxel::UVCXU::setControl().
 {
   if(!isInitialized())
     return -1;
   int ret = 0;
   int tries = FD_RETRY_LIMIT;
   do
   {
     ret = ioctl(_fd, request, arg);
   }
   while(ret && tries-- && ((errno == EINTR) || (errno == EAGAIN) || (errno == ETIMEDOUT)));
   if (ret && (tries <= 0))
     logger(LOG_ERROR) << "UVC: ioctl (" << request << ") retried " << FD_RETRY_LIMIT << " times - giving up: " << strerror(errno) << ")" << std::endl;
   return ret;
 }
Member Data Documentation
Ptr<IBaseFilter> Voxel::UVCPrivate::_captureFilter private
Definition at line 26 of file UVCPrivateWindows.h.
String Voxel::UVCPrivate::_deviceNode protected
Definition at line 29 of file UVCPrivateLinux.h.
Referenced by UVCPrivate().
int Voxel::UVCPrivate::_fd = -1 protected
Definition at line 28 of file UVCPrivateLinux.h.
Referenced by isInitialized(), isReadReady(), mmap(), read(), UVCPrivate(), xioctl(), and ~UVCPrivate().
Vector<UVCRawData> Voxel::UVCPrivate::_mappedRawData protected
Definition at line 32 of file UVCPrivateLinux.h.
Referenced by clearMMap(), and mmap().
DevicePtr Voxel::UVCPrivate::_usb protected
Definition at line 30 of file UVCPrivateLinux.h.
Referenced by UVCPrivate().
The documentation for this class was generated from the following files:
UVCPrivateLinux.h
UVCPrivateWindows.h
UVCPrivateLinux.cpp
UVCPrivateWindows.cpp