Voxel: Voxel::ConfigurationFile Class Reference
Voxel::ConfigurationFile Class Reference
#include <Configuration.h>
Public Types
enum Location { IN_HOST = 0, IN_CAMERA = 1 }
typedef Map< String, ConfigSet > ConfigSetMap
Public Member Functions
Location getLocation () const
const String & getFileName () const
virtual bool isPresent (const String &section, const String &name, bool includeParent=true) const
virtual String get (const String &section, const String &name) const
void setID (const int id)
template<typename T >
bool getFile (const String &section, const String &name, String &fileName, Vector< T > &data)
int getInteger (const String &section, const String &name) const
float getFloat (const String &section, const String &name) const
bool getBoolean (const String &section, const String &name) const
virtual bool set (const String &section, const String &name, const String &value)
template<typename T >
bool setFile (const String &section, const String &name, const String &fileName, const Vector< T > &data)
bool setInteger (const String &section, const String &name, int value)
bool setFloat (const String &section, const String &name, float value)
bool setBoolean (const String &section, const String &name, bool value)
bool remove (const String &section, const String &name)
virtual bool getConfigSet (const String &section, const ConfigSet *&configSet) const
virtual bool read (const String &configFile)
virtual bool read (InputStream &in)
virtual bool write (const String &configFile="")
virtual bool write (OutputStream &out)
bool isValidCameraProfile ()
virtual bool removeFile ()
void clear ()
const String & getConfigFileName ()
ConfigurationFile ()
ConfigurationFile (MainConfigurationFile *mainConfigurationFile)
ConfigurationFile (const ConfigurationFile &other)
ConfigurationFile & operator= (const ConfigurationFile &other)
bool mergeParentConfiguration ()
ConfigurationFile & copy (const ConfigurationFile &other)
virtual ~ConfigurationFile ()
Public Attributes
ConfigSetMap configs
Protected Member Functions
bool _get (const String &section, const String &name, String &value) const
bool _set (const String &section, const String &name, const String &value)
bool _serializeAllDataFiles (OutputStream &out)
bool _saveAllDataFiles (const String &prefix)
template<typename T >
bool _getData (const String &fileName, Vector< T > &data)
template<typename T >
bool _setData (const String &fileName, const Vector< T > &data)
bool _copyFromParentIfNotPresent (ConfigurationFile *other, bool recurse=true)
Protected Attributes
String _fileName
Map< String, Vector< ByteType > > _dataFiles
MainConfigurationFile * _mainConfigurationFile
int _id
int _parentID
String _profileName
Mutex _mutex
Location _location
Friends
class MainConfigurationFile
Detailed Description
Definition at line 113 of file Configuration.h.
Member Typedef Documentation
typedef Map<String, ConfigSet> Voxel::ConfigurationFile::ConfigSetMap
Definition at line 142 of file Configuration.h.
Member Enumeration Documentation
enum Voxel::ConfigurationFile::Location
Enumerator
IN_HOST
IN_CAMERA
Definition at line 144 of file Configuration.h.
   {
     IN_HOST = 0,
     IN_CAMERA = 1
   };
Constructor & Destructor Documentation
Voxel::ConfigurationFile::ConfigurationFile () inline
Definition at line 198 of file Configuration.h.
Referenced by Voxel::MainConfigurationFile::addCameraProfile().
 : ConfigurationFile(0) {}
Voxel::ConfigurationFile::ConfigurationFile (MainConfigurationFile * mainConfigurationFile) inline
Definition at line 199 of file Configuration.h.
                                                                  :
   _mainConfigurationFile(mainConfigurationFile), _id(-1), _parentID(-1), _location(IN_HOST) {}
Voxel::ConfigurationFile::ConfigurationFile (const ConfigurationFile & other) inline
Definition at line 202 of file Configuration.h.
   {
     operator =(other);
   }
virtual Voxel::ConfigurationFile::~ConfigurationFile () inline virtual
Definition at line 230 of file Configuration.h.
 {}
Member Function Documentation
bool Voxel::ConfigurationFile::_copyFromParentIfNotPresent (ConfigurationFile * other, bool recurse = true) protected
Definition at line 827 of file Configuration.cpp.
References _copyFromParentIfNotPresent(), _mainConfigurationFile, _parentID, configs, Voxel::MainConfigurationFile::getCameraProfile(), isPresent(), and set().
Referenced by _copyFromParentIfNotPresent().
 {
   if(!_mainConfigurationFile)
     return true;
   ConfigurationFile *parent = _mainConfigurationFile->getCameraProfile(_parentID);
   if(!parent)
     return true;
   for(auto c = parent->configs.begin(); c != parent->configs.end(); c++)
   {
     for(auto i = c->second.params.begin(); i != c->second.params.end(); i++)
     {
       if(to->isPresent(c->first, i->first, false))
         continue;
       to->set(c->first, i->first, i->second);
     }
   }
   if(recurse)
     return parent->_copyFromParentIfNotPresent(to, recurse);
   else
     return true;
 }
bool Voxel::ConfigurationFile::_get (const String & section, const String & name, String & value) const protected
Definition at line 290 of file Configuration.cpp.
References Voxel::ConfigSet::_get(), _get(), _mainConfigurationFile, _mutex, _parentID, configs, Voxel::MainConfigurationFile::getCameraProfile(), and set().
Referenced by _get(), get(), and Voxel::MainConfigurationFile::get().
 {
   Lock<Mutex> _(_mutex);
   int parentID;
   bool checkParent = false;
   if(configs.find(section) != configs.end())
   {
     const ConfigSet &set = configs.at(section);
     if(!set._get(name, value))
       checkParent = true;
     else
       return true;
   }
   else
     checkParent = true;
   if(checkParent)
   {
     if(section != "global" && _mainConfigurationFile && _parentID >= 0)
     {
       ConfigurationFile *parentConfig = _mainConfigurationFile->getCameraProfile(_parentID);
       // TODO This does not handle circular references between profiles
       if(parentConfig)
         return parentConfig->_get(section, name, value);
     }
   }
   return false;
 }
template<typename T > bool Voxel::ConfigurationFile::_getData (const String & fileName, Vector< T > & data) protected
Definition at line 258 of file Configuration.h.
References _dataFiles, Voxel::Configuration::getConfFile(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by getFile().
 {
   if(_dataFiles.find(fileName) == _dataFiles.end())
   {
     Configuration c;
     String f = fileName;
     if(!c.getConfFile(f))
     {
       logger(LOG_ERROR) << "ConfigurationFile: Could not locate file '" << fileName << "'" << std::endl;
       return false;
     }
     InputFileStream fs(f, std::ios::in | std::ios::binary | std::ios::ate);
     if(!fs.good())
     {
       logger(LOG_ERROR) << "ConfigurationFile: Could not open file '" << fileName << "'" << std::endl;
       return false;
     }
     int size = fs.tellg();
     if(size == 0)
     {
       logger(LOG_ERROR) << "ConfigurationFile: Null config data '" << f << "'" << std::endl;
       return false;
     }
     Vector<ByteType> &d = _dataFiles[fileName];
     d.resize(size);
     fs.seekg(std::ios::beg);
     fs.clear();
     fs.read((char *)d.data(), size);
   }
   Vector<ByteType> &d = _dataFiles[fileName];
   data.resize((d.size() + sizeof(T)/2)/sizeof(T));
   memcpy(data.data(), d.data(), d.size());
   return true;
 }
bool Voxel::ConfigurationFile::_saveAllDataFiles (const String & prefix) protected
Definition at line 553 of file Configuration.cpp.
References configs, and FILE_PREFIX.
Referenced by write().
 {
   for(auto c = configs.begin(); c != configs.end(); c++)
   {
     for(auto i = c->second.params.begin(); i != c->second.params.end(); i++)
     {
       if(i->second.compare(0, sizeof(FILE_PREFIX) - 1, FILE_PREFIX) == 0)
       {
         String f;
         Vector<uint8_t> d;
         if(!getFile<uint8_t>(c->first, i->first, f, d))
           return false;
         if(!setFile<uint8_t>(c->first, i->first, prefix + f, d)) // save the file locally
           return false;
       }
     }
   }
   return true;
 }
bool Voxel::ConfigurationFile::_serializeAllDataFiles (OutputStream & out) protected
Definition at line 502 of file Configuration.cpp.
References _id, Voxel::Data2DCodec::compress(), configs, FILE_PREFIX, Voxel::LOG_ERROR, Voxel::logger, Voxel::DataPacket::object, Voxel::ConfigDataPacket::PACKET_2D_DATA_FILE, Voxel::SerializedObject::put(), Voxel::SerializedObject::resize(), Voxel::SerializableString::serializedSize(), Voxel::DataPacket::size, Voxel::SerializedObject::size(), Voxel::DataPacket::type, Voxel::DataPacket::write(), and Voxel::SerializableString::write().
 {
   for(auto c = configs.begin(); c != configs.end(); c++)
   {
     for(auto i = c->second.params.begin(); i != c->second.params.end(); i++)
     {
       if(i->second.compare(0, sizeof(FILE_PREFIX) - 1, FILE_PREFIX) == 0)
       {
         String f;
         Vector<uint8_t> d;
         if(!getFile<uint8_t>(c->first, i->first, f, d))
           return false;
         ConfigDataPacket cp;
         cp.type = ConfigDataPacket::PACKET_2D_DATA_FILE;
         Data2DCodec codec;
         Data2DCodec::Array2D in;
         Data2DCodec::ArrayBool2D invalidPixels; // Just empty array
         Data2DCodec::ByteArray dout;
         in.resize(d.size()/sizeof(Data2DCodec::Array2DElementType));
         memcpy(in.data(), d.data(), d.size());
         if(!codec.compress(in, invalidPixels, dout))
         {
           logger(LOG_ERROR) << "ConfigurationFile: Failed to compress data file '" << f << "'" << std::endl;
           return false;
         }
         uint8_t id = _id;
         SerializableString section = c->first;
         SerializableString field = i->first;
         cp.object.resize(1 + section.serializedSize() + field.serializedSize() + dout.size());
         cp.object.put((const char *)&id, sizeof(id));
         section.write(cp.object);
         field.write(cp.object);
         cp.object.put((const char *)dout.data(), dout.size());
         cp.size = cp.object.size();
         cp.write(out);
       }
     }
   }
   return true;
 }
bool Voxel::ConfigurationFile::_set (const String & section, const String & name, const String & value) protected
Definition at line 688 of file Configuration.cpp.
References _mutex, Voxel::ConfigSet::_set(), configs, and set().
Referenced by set(), setBoolean(), setFloat(), and setInteger().
 {
   Lock<Mutex> _(_mutex);
   if(configs.find(section) == configs.end())
     configs[section]; // Create section
   ConfigSet &set = configs.at(section);
   return set._set(name, value);
 }
template<typename T > bool Voxel::ConfigurationFile::_setData (const String & fileName, const Vector< T > & data) protected
Definition at line 305 of file Configuration.h.
References _dataFiles, Voxel::Configuration::getLocalConfFile(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by setFile().
 {
   Configuration c;
   String f = fileName;
   if(!c.getLocalConfFile(f))
   {
     logger(LOG_ERROR) << "ConfigurationFile: Failed to locate file '" << fileName << "'" << std::endl;
     return false;
   }
   OutputFileStream fs(f, std::ios::out | std::ios::binary);
   if(!fs.good())
   {
     logger(LOG_ERROR) << "ConfigurationFile: Could not open file '" << fileName << "'" << std::endl;
     return false;
   }
   fs.write((const char *)data.data(), data.size()*sizeof(T));
   fs.close();
   _dataFiles[fileName].resize(data.size()*sizeof(T));
   memcpy(_dataFiles[fileName].data(), data.data(), data.size()*sizeof(T));
   return true;
 }
void Voxel::ConfigurationFile::clear () inline
Definition at line 194 of file Configuration.h.
 { Lock<Mutex> _(_mutex); configs.clear(); }
ConfigurationFile& Voxel::ConfigurationFile::copy (const ConfigurationFile & other) inline
Definition at line 225 of file Configuration.h.
   {
     return operator =(other);
   }
String Voxel::ConfigurationFile::get (const String & section, const String & name) const virtual
Reimplemented in Voxel::MainConfigurationFile.
Definition at line 333 of file Configuration.cpp.
References _get().
Referenced by main(), Voxel::MainConfigurationFile::read(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   String value;
   if(!_get(section, name, value))
     return "";
   else
     return value;
 }
bool Voxel::ConfigurationFile::getBoolean (const String & section, const String & name) const
Definition at line 399 of file Configuration.cpp.
Referenced by Voxel::TI::ToFHaddockCamera::_applyCalibrationParams(), and Voxel::TI::ToFTintinCamera::_applyCalibrationParams().
 {
   String s = get(section, name);
   if(!s.size())
     return false;
   if(s == "true" || s == "True" || s == "1")
     return true;
   else
     return false;
 }
const String& Voxel::ConfigurationFile::getConfigFileName () inline
Definition at line 196 of file Configuration.h.
 { return _fileName; }
bool Voxel::ConfigurationFile::getConfigSet (const String & section, const ConfigSet *& configSet) const virtual
Definition at line 257 of file Configuration.cpp.
References _mainConfigurationFile, _parentID, configs, Voxel::MainConfigurationFile::getCameraProfile(), and getConfigSet().
Referenced by getConfigSet(), and Voxel::DepthCamera::setCameraProfile().
 {
   if(configs.find(section) != configs.end())
   {
     configSet = &configs.at(section);
     return true;
   }
   else
   {
     if(section != "global" && _mainConfigurationFile && _parentID >= 0)
     {
       ConfigurationFile *parentConfig = _mainConfigurationFile->getCameraProfile(_parentID);
       // TODO This does not handle circular references between profiles
       if(parentConfig)
         return parentConfig->getConfigSet(section, configSet);
     }
   }
   return false;
 }
template<typename T > bool Voxel::ConfigurationFile::getFile (const String & section, const String & name, String & fileName, Vector< T > & data)
Definition at line 236 of file Configuration.h.
References _getData(), FILE_PREFIX, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::MainConfigurationFile::getFile().
 {
   String v = get(section, name);
   if(v.compare(0, sizeof(FILE_PREFIX) - 1, FILE_PREFIX) != 0 || v.size() <= sizeof(FILE_PREFIX) - 1)
   {
     logger(LOG_ERROR) << "ConfigurationFile: section = " << section << ", name = " << name << ", is not a file type." << std::endl;
     return false;
   }
   fileName = v.substr(sizeof(FILE_PREFIX) - 1);
   return _getData(fileName, data);
 }
const String& Voxel::ConfigurationFile::getFileName () const inline
Definition at line 157 of file Configuration.h.
Referenced by main().
 { return _fileName; }
float Voxel::ConfigurationFile::getFloat (const String & section, const String & name) const
Definition at line 375 of file Configuration.cpp.
Referenced by Voxel::TI::ToFCamera::_getDepthScalingFactor(), and Voxel::TI::ToFCamera::_initStartParams().
 {
   String s = get(section, name);
   if(!s.size())
     return 0.0f;
   return atof(s.c_str());
 }
int Voxel::ConfigurationFile::getInteger (const String & section, const String & name) const
Definition at line 354 of file Configuration.cpp.
Referenced by Voxel::TI::ToFHaddockCamera::_applyCalibrationParams(), Voxel::TI::ToFTintinCamera::_applyCalibrationParams(), Voxel::TI::ToFCamera::_getDepthScalingFactor(), Voxel::TI::ToFCamera::_initStartParams(), isValidCameraProfile(), read(), Voxel::MainConfigurationFile::read(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   String s = get(section, name);
   if(!s.size())
     return 0;
   return atoi(s.c_str());
 }
Location Voxel::ConfigurationFile::getLocation () const inline
Definition at line 156 of file Configuration.h.
Referenced by main(), Voxel::MainConfigurationFile::removeCameraProfile(), Voxel::MainConfigurationFile::saveCameraProfileToHardware(), Voxel::MainConfigurationFile::setDefaultCameraProfile(), and write().
 { return _location; }
bool Voxel::ConfigurationFile::isPresent (const String & section, const String & name, bool includeParent = true) const virtual
Reimplemented in Voxel::MainConfigurationFile.
Definition at line 225 of file Configuration.cpp.
References _mainConfigurationFile, _parentID, configs, Voxel::MainConfigurationFile::getCameraProfile(), Voxel::ConfigSet::isPresent(), isPresent(), and set().
Referenced by _copyFromParentIfNotPresent(), isPresent(), Voxel::MainConfigurationFile::isPresent(), isValidCameraProfile(), main(), read(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   bool checkParent = false;
   if(configs.find(section) == configs.end())
     checkParent = true;
   else
   {
     const ConfigSet &set = configs.at(section);
     if(!set.isPresent(name))
       checkParent = true;
     else
       return true;
   }
   if(checkParent && includeParent)
   {
     if(section != "global" && _mainConfigurationFile && _parentID >= 0)
     {
       ConfigurationFile *parentConfig = _mainConfigurationFile->getCameraProfile(_parentID);
       // TODO This does not handle circular references between profiles
       if(parentConfig)
       {
         return parentConfig->isPresent(section, name);
       }
     }
   }
   return false;
 }
bool Voxel::ConfigurationFile::isValidCameraProfile ()
Definition at line 802 of file Configuration.cpp.
References _fileName, _mainConfigurationFile, Voxel::MainConfigurationFile::getCameraProfile(), getInteger(), isPresent(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::MainConfigurationFile::read(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   if(!isPresent("global", "id"))
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Could not get ID of profile " << _fileName << std::endl;
     return false;
   }
   int id = getInteger("global", "id");
   if(_mainConfigurationFile->getCameraProfile(id) != 0)
   {
     logger(LOG_ERROR) << "MainConfigurationFile: A profile with ID = " << id << " already exists." << std::endl;
     return false;
   }
   if(!isPresent("global", "name"))
   {
     logger(LOG_ERROR) << "MainConfigurationFile: Could not get name of profile in " << _fileName << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::ConfigurationFile::mergeParentConfiguration () inline
Definition at line 220 of file Configuration.h.
Referenced by Voxel::MainConfigurationFile::saveCameraProfileToHardware().
   {
     return _copyFromParentIfNotPresent(this);
   }
ConfigurationFile& Voxel::ConfigurationFile::operator= (const ConfigurationFile & other) inline
Definition at line 207 of file Configuration.h.
References _dataFiles, _fileName, _id, _location, _mainConfigurationFile, _parentID, _profileName, and configs.
   {
     configs = other.configs;
     _fileName = other._fileName;
     _mainConfigurationFile = other._mainConfigurationFile;
     _id = other._id;
     _profileName = other._profileName;
     _parentID = other._parentID;
     _location = other._location;
     _dataFiles = other._dataFiles;
     return *this;
   }
bool Voxel::ConfigurationFile::read (const String & configFile) virtual
Reimplemented in Voxel::MainConfigurationFile.
Definition at line 413 of file Configuration.cpp.
References _fileName, configs, Voxel::Configuration::getConfFile(), Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::MainConfigurationFile::read(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   Configuration c;
   String f = filename;
   configs.clear();
   if(!c.getConfFile(f))
   {
     logger(LOG_ERROR) << "ConfigurationFile: Failed to get configuration file '" << f << "'" << std::endl;
     return false;
   }
   _fileName = f;
   InputFileStream fin(f, std::ios::binary | std::ios::in);
   if (!fin.good())
   {
     logger(LOG_ERROR) << "ConfigurationFile: Could not read file '" << filename << "'" << std::endl;
     return false;
   }
   return read(fin);
 }
bool Voxel::ConfigurationFile::read (InputStream & in) virtual
Definition at line 439 of file Configuration.cpp.
References _id, _mutex, _parentID, _profileName, configs, getInteger(), isPresent(), and Voxel::trim().
 {
   {
     Lock<Mutex> _(_mutex);
     char buffer[2048];
     char name[1000];
     char value[1000];
     ConfigSet *currentSet = 0;
     while(in.good())
     {
       in.getline(buffer, 2048);
       if(strlen(buffer) < 2)
       {
         // ignore this line - nothing to do
       }
       else if(buffer[0] == '[') // new section
       {
         int nret = sscanf(buffer, "[%[^]]]", name);
         if(nret == 1)
           currentSet = &configs[name];
         else
           return false;
       }
       else if(buffer[0] != '#') // allow comments
       {
         int nret = sscanf(buffer, "%[^=] = %[^\t\r\n]", name, value);
         if(nret >= 1 && currentSet != 0)
         {
           String n = name;
           trim(n);
           String v;
           if(nret == 2)
           {
             v = value;
             trim(v);
           }
           (*currentSet).paramNames.push_back(n);
           (*currentSet).params[n] = v;
         }
         else
           return false;
       }
     }
   }
   if(isPresent("global", "id"))
     _id = getInteger("global", "id");
   if(isPresent("global", "parent"))
     _parentID = getInteger("global", "parent");
   if(isPresent("global", "name"))
     _profileName = get("global", "name");
   return true;
 }
bool Voxel::ConfigurationFile::remove (const String & section, const String & name)
Definition at line 756 of file Configuration.cpp.
References configs, Voxel::ConfigSet::isEmpty(), Voxel::ConfigSet::remove(), and set().
 {
   if(configs.find(section) != configs.end())
   {
     ConfigSet &set = configs.at(section);
     if(set.remove(name))
     {
       if(set.isEmpty())
       {
         configs.erase(configs.find(section)); // Remove section
       }
       return true;
     }
   }
   return false;
 }
bool Voxel::ConfigurationFile::removeFile () virtual
Definition at line 775 of file Configuration.cpp.
References _fileName, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::MainConfigurationFile::removeCameraProfile().
 {
   if(_fileName.size() == 0)
   {
     logger(LOG_ERROR) << "ConfigurationFile: No file present for current configuration" << std::endl;
     return false;
   }
   InputFileStream f(_fileName);
   if(!f.good())
   {
     logger(LOG_ERROR) << "ConfigurationFile: Could not find file '" << _fileName << "'" << std::endl;
     return false;
   }
   f.close();
   if(::remove(_fileName.c_str()) != 0)
   {
     logger(LOG_ERROR) << "ConfigurationFile: Failed to remove file '" << _fileName << "'" << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::ConfigurationFile::set (const String & section, const String & name, const String & value) virtual
Definition at line 699 of file Configuration.cpp.
References _profileName, and _set().
Referenced by _copyFromParentIfNotPresent(), _get(), _set(), Voxel::MainConfigurationFile::_updateCameraProfileList(), isPresent(), main(), remove(), and setFile().
 {
   if(section == "global" && name == "name")
     _profileName = value;
   return _set(section, name, value);
 }
bool Voxel::ConfigurationFile::setBoolean (const String & section, const String & name, bool value)
Definition at line 707 of file Configuration.cpp.
References _set().
 {
   if(value)
     return _set(section, name, "true");
   else
     return _set(section, name, "false");
 }
template<typename T > bool Voxel::ConfigurationFile::setFile (const String & section, const String & name, const String & fileName, const Vector< T > & data)
Definition at line 252 of file Configuration.h.
References _setData(), and set().
 {
   return _setData(fileName, data) && set(section, name, "file:" + fileName);
 }
bool Voxel::ConfigurationFile::setFloat (const String & section, const String & name, float value)
Definition at line 715 of file Configuration.cpp.
References _set().
 {
   OutputStringStream s;
   s << value;
   return _set(section, name, s.str());
 }
void Voxel::ConfigurationFile::setID (const int id) inline
Definition at line 162 of file Configuration.h.
Referenced by Voxel::MainConfigurationFile::saveCameraProfileToHardware().
 { _id = id; setInteger("global", "id", id); }
bool Voxel::ConfigurationFile::setInteger (const String & section, const String & name, int value)
Definition at line 723 of file Configuration.cpp.
References _id, _parentID, and _set().
Referenced by Voxel::MainConfigurationFile::setDefaultCameraProfile().
 {
   OutputStringStream s;
   s << value;
   if(section == "global")
   {
     if(name == "id")
       _id = value;
     else if(name == "parent")
       _parentID = value;
   }
   return _set(section, name, s.str());
 }
bool Voxel::ConfigurationFile::write (const String & configFile = "") virtual
Definition at line 594 of file Configuration.cpp.
References _fileName, Voxel::MainConfigurationFile::_hardwareID, _mainConfigurationFile, _saveAllDataFiles(), Voxel::basename(), Voxel::Configuration::getLocalConfFile(), getLocation(), IN_CAMERA, Voxel::LOG_ERROR, Voxel::LOG_INFO, and Voxel::logger.
Referenced by Voxel::MainConfigurationFile::_updateCameraProfileList(), Voxel::MainConfigurationFile::addCameraProfile(), main(), and Voxel::MainConfigurationFile::setDefaultCameraProfile().
 {
   Configuration c;
   if(configFile != "") // Use new file name or old one itself?
   {
     String f = basename(configFile);
     if(!c.getLocalConfFile(f))
     {
       logger(LOG_ERROR) << "ConfigurationFile: Failed to get configuration local path." << std::endl;
       return false;
     }
     _fileName = f;
   }
   else
   {
     String f = basename(_fileName);
     if(!c.getLocalConfFile(f))
     {
       logger(LOG_ERROR) << "ConfigurationFile: Failed to get configuration local path." << std::endl;
       return false;
     }
     _fileName = f;
   }
   OutputFileStream fout(_fileName, std::ios::binary | std::ios::out);
   if (!fout.good())
   {
     logger(LOG_ERROR) << "ConfigurationFile: Could not write file '" << configFile << "'" << std::endl;
     return false;
   }
   logger(LOG_INFO) << "ConfigurationFile: Saving profile to '" << _fileName << "'..." << std::endl;
   if(getLocation() == ConfigurationFile::IN_CAMERA && !_saveAllDataFiles(_mainConfigurationFile->_hardwareID + "-"))
     return false;
   return write(fout);
 }
bool Voxel::ConfigurationFile::write (OutputStream & out) virtual
Definition at line 577 of file Configuration.cpp.
References _mutex, and configs.
 {
   Lock<Mutex> _(_mutex);
   for(auto c = configs.begin(); c != configs.end(); c++)
   {
     out << "[" << c->first << "]\n";
     for(auto i = 0; i < c->second.paramNames.size(); i++)
     {
       out << c->second.paramNames[i] << " = " << c->second.params[c->second.paramNames[i]] << std::endl;
     }
     out << std::endl;
   }
   return true;
 }
Friends And Related Function Documentation
friend class MainConfigurationFile friend
Definition at line 232 of file Configuration.h.
Member Data Documentation
Map<String, Vector<ByteType> > Voxel::ConfigurationFile::_dataFiles protected
Definition at line 121 of file Configuration.h.
Referenced by _getData(), _setData(), operator=(), and Voxel::MainConfigurationFile::readFromHardware().
String Voxel::ConfigurationFile::_fileName protected
Definition at line 119 of file Configuration.h.
Referenced by Voxel::MainConfigurationFile::addCameraProfile(), isValidCameraProfile(), operator=(), read(), Voxel::MainConfigurationFile::readFromHardware(), Voxel::MainConfigurationFile::removeCameraProfile(), removeFile(), and write().
int Voxel::ConfigurationFile::_id protected
Definition at line 125 of file Configuration.h.
Referenced by _serializeAllDataFiles(), operator=(), read(), and setInteger().
Location Voxel::ConfigurationFile::_location protected
Definition at line 151 of file Configuration.h.
Referenced by operator=(), Voxel::MainConfigurationFile::readFromHardware(), and Voxel::MainConfigurationFile::saveCameraProfileToHardware().
MainConfigurationFile* Voxel::ConfigurationFile::_mainConfigurationFile protected
Definition at line 123 of file Configuration.h.
Referenced by _copyFromParentIfNotPresent(), _get(), getConfigSet(), isPresent(), isValidCameraProfile(), operator=(), and write().
Mutex Voxel::ConfigurationFile::_mutex mutable protected
Definition at line 128 of file Configuration.h.
Referenced by _get(), _set(), read(), and write().
int Voxel::ConfigurationFile::_parentID protected
Definition at line 125 of file Configuration.h.
Referenced by _copyFromParentIfNotPresent(), _get(), getConfigSet(), isPresent(), operator=(), read(), Voxel::MainConfigurationFile::removeCameraProfile(), Voxel::MainConfigurationFile::saveCameraProfileToHardware(), and setInteger().
String Voxel::ConfigurationFile::_profileName protected
Definition at line 126 of file Configuration.h.
Referenced by operator=(), read(), Voxel::MainConfigurationFile::readFromHardware(), Voxel::MainConfigurationFile::saveCameraProfileToHardware(), and set().
ConfigSetMap Voxel::ConfigurationFile::configs
Definition at line 154 of file Configuration.h.
Referenced by _copyFromParentIfNotPresent(), _get(), _saveAllDataFiles(), _serializeAllDataFiles(), _set(), getConfigSet(), isPresent(), operator=(), read(), remove(), and write().
The documentation for this class was generated from the following files:
Configuration.h
Configuration.cpp