Voxel: Voxel::FilterParameterTemplate< T > Class Template Reference
Voxel::FilterParameterTemplate< T > Class Template Reference abstract
Filter related classes
#include <FilterParameter.h>
Public Member Functions
FilterParameterTemplate (const String &name, const String &displayName, const String &description, const T &defaultValue)
virtual bool get (T &v) const
virtual bool set (const T &v)
virtual bool validate (const T &v) const =0
virtual ~FilterParameterTemplate ()
Public Member Functions inherited from Voxel::FilterParameter
FilterParameter (const String &name, const String &displayName, const String &description)
const String & name () const
const String & displayName () const
const String & description () const
virtual ~FilterParameter ()
Static Public Member Functions
static Ptr
< FilterParameterTemplate< T > > typeCast (const FilterParameterPtr &other)
Protected Attributes
T _value
Protected Attributes inherited from Voxel::FilterParameter
String _name
String _displayName
String _description
Detailed Description
template<typename T>
class Voxel::FilterParameterTemplate< T >
Definition at line 40 of file FilterParameter.h.
Constructor & Destructor Documentation
template<typename T> Voxel::FilterParameterTemplate< T >::FilterParameterTemplate (const String & name, const String & displayName, const String & description, const T & defaultValue) inline
Definition at line 46 of file FilterParameter.h.
                                                                                                                           :
     FilterParameter(name, displayName, description), _value(defaultValue) {}
template<typename T> virtual Voxel::FilterParameterTemplate< T >::~FilterParameterTemplate () inline virtual
Definition at line 68 of file FilterParameter.h.
 {}
Member Function Documentation
template<typename T> virtual bool Voxel::FilterParameterTemplate< T >::get (T & v) const inline virtual
Definition at line 54 of file FilterParameter.h.
Referenced by Voxel::Filter::_get(), and Voxel::CLIManager::_showFilterSet().
 { v = _value; return true; }
template<typename T> virtual bool Voxel::FilterParameterTemplate< T >::set (const T & v) inline virtual
Definition at line 55 of file FilterParameter.h.
Referenced by Voxel::Filter::_set().
   {
     if(validate(v))
     {
       _value = v;
       return true;
     }
     else
       return false;
   }
template<typename T> static Ptr<FilterParameterTemplate<T> > Voxel::FilterParameterTemplate< T >::typeCast (const FilterParameterPtr & other) inline static
Definition at line 49 of file FilterParameter.h.
   {
     return std::dynamic_pointer_cast<FilterParameterTemplate<T>>(other);
   }
template<typename T> virtual bool Voxel::FilterParameterTemplate< T >::validate (const T & v) const pure virtual
Implemented in Voxel::FilterParameterEnumTemplate< T >, Voxel::FilterParameterEnumTemplate< bool >, and Voxel::FilterParameterRangeTemplate< T >.
Referenced by Voxel::FilterParameterTemplate< bool >::set().
Member Data Documentation
template<typename T> T Voxel::FilterParameterTemplate< T >::_value protected
Definition at line 43 of file FilterParameter.h.
Referenced by Voxel::FilterParameterTemplate< bool >::get(), and Voxel::FilterParameterTemplate< bool >::set().
The documentation for this class was generated from the following file:
FilterParameter.h