Voxel: ELFIO::note_section_accessor Class Reference
ELFIO::note_section_accessor Class Reference
#include <elfio_note.hpp>
Public Member Functions
note_section_accessor (const elfio &elf_file_, section *section_)
Elf_Word get_notes_num () const
bool get_note (Elf_Word index, Elf_Word &type, std::string &name, void *&desc, Elf_Word &descSize) const
void add_note (Elf_Word type, const std::string &name, const void *desc, Elf_Word descSize)
Private Member Functions
void process_section ()
Private Attributes
const elfio & elf_file
section * note_section
std::vector< Elf_Xword > note_start_positions
Detailed Description
Definition at line 29 of file elfio_note.hpp.
Constructor & Destructor Documentation
ELFIO::note_section_accessor::note_section_accessor (const elfio & elf_file_, section * section_) inline
Definition at line 33 of file elfio_note.hpp.
References process_section().
                                                                        :
                            elf_file( elf_file_ ), note_section( section_ )
     {
         process_section();
     }
Member Function Documentation
void ELFIO::note_section_accessor::add_note (Elf_Word type, const std::string & name, const void * desc, Elf_Word descSize) inline
Definition at line 81 of file elfio_note.hpp.
References ELFIO::section::append_data(), elf_file, ELFIO::elfio::get_convertor(), note_section, and note_start_positions.
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         Elf_Word nameLen     = (Elf_Word)name.size() + 1;
         Elf_Word nameLenConv = convertor( nameLen );
         std::string buffer( reinterpret_cast<char*>( &nameLenConv ), sizeof( nameLenConv ) );
         Elf_Word descSizeConv = convertor( descSize );
         buffer.append( reinterpret_cast<char*>( &descSizeConv ), sizeof( descSizeConv ) );
         type = convertor( type );
         buffer.append( reinterpret_cast<char*>( &type ), sizeof( type ) );
         buffer.append( name );
         buffer.append( 1, '\x00' );
         const char pad[] = { '\0', '\0', '\0', '\0' };
         if ( nameLen % sizeof( Elf_Word ) != 0 ) {
             buffer.append( pad, sizeof( Elf_Word ) -
                                 nameLen % sizeof( Elf_Word ) );
         }
         if ( desc != 0 && descSize != 0 ) {
             buffer.append( reinterpret_cast<const char*>( desc ), descSize );
             if ( descSize % sizeof( Elf_Word ) != 0 ) {
                 buffer.append( pad, sizeof( Elf_Word ) -
                                     descSize % sizeof( Elf_Word ) );
             }
         }
         note_start_positions.push_back( note_section->get_size() );
         note_section->append_data( buffer );
     }
bool ELFIO::note_section_accessor::get_note (Elf_Word index, Elf_Word & type, std::string & name, void *& desc, Elf_Word & descSize) const inline
Definition at line 48 of file elfio_note.hpp.
References elf_file, ELFCLASS32, ELFIO::elfio::get_convertor(), ELFIO::section::get_data(), note_section, and note_start_positions.
Referenced by ELFIO::dump::notes().
     {
         if ( index >= note_section->get_size() ) {
             return false;
         }
         const char* pData = note_section->get_data() + note_start_positions[index];
         const endianess_convertor& convertor = elf_file.get_convertor();
         type = convertor( *(Elf_Word*)( pData + 2*sizeof( Elf_Word ) ) );
         Elf_Word namesz = convertor( *(Elf_Word*)( pData ) );
         name.assign( pData + 3*sizeof( Elf_Word ), namesz );
         descSize = convertor( *(Elf_Word*)( pData + sizeof( namesz ) ) );
         if ( 0 == descSize ) {
             desc = 0;
         }
         else {
             int align = sizeof( Elf_Xword );
             if ( elf_file.get_class() == ELFCLASS32 ) {
                 align = sizeof( Elf_Word );
             }
             desc = const_cast<char*> ( pData + 3*sizeof( Elf_Word ) +
                                        ( ( namesz + align - 1 ) / align ) * align );
         }
         return true;
     }
Elf_Word ELFIO::note_section_accessor::get_notes_num () const inline
Definition at line 41 of file elfio_note.hpp.
References note_start_positions.
Referenced by ELFIO::dump::notes().
     {
         return (Elf_Word)note_start_positions.size();
     }
void ELFIO::note_section_accessor::process_section () inline private
Definition at line 116 of file elfio_note.hpp.
References elf_file, ELFCLASS32, ELFIO::elfio::get_convertor(), ELFIO::section::get_data(), note_section, and note_start_positions.
Referenced by note_section_accessor().
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         const char* data                     = note_section->get_data();
         Elf_Xword   size                     = note_section->get_size();
         Elf_Xword   current                  = 0;
         note_start_positions.clear();
         // Is it empty?
         if ( 0 == data || 0 == size ) {
             return;
         }
         while ( current + 3*sizeof( Elf_Word ) <= size ) {
             note_start_positions.push_back( current );
             Elf_Word namesz = convertor(
                             *(Elf_Word*)( data + current ) );
             Elf_Word descsz = convertor(
                             *(Elf_Word*)( data + current + sizeof( namesz ) ) );
             int align = sizeof( Elf_Xword );
             if ( elf_file.get_class() == ELFCLASS32 ) {
                 align = sizeof( Elf_Word );
             }
             current += 3*sizeof( Elf_Word ) +
                        ( ( namesz + align - 1 ) / align ) * align +
                        ( ( descsz + align - 1 ) / align ) * align;
         }
     }
Member Data Documentation
const elfio& ELFIO::note_section_accessor::elf_file private
Definition at line 150 of file elfio_note.hpp.
Referenced by add_note(), get_note(), and process_section().
section* ELFIO::note_section_accessor::note_section private
Definition at line 151 of file elfio_note.hpp.
Referenced by add_note(), get_note(), and process_section().
std::vector<Elf_Xword> ELFIO::note_section_accessor::note_start_positions private
Definition at line 152 of file elfio_note.hpp.
Referenced by add_note(), get_note(), get_notes_num(), and process_section().
The documentation for this class was generated from the following file:
elfio_note.hpp