Voxel: ELFIO::symbol_section_accessor Class Reference
ELFIO::symbol_section_accessor Class Reference
#include <elfio_symbols.hpp>
Public Member Functions
symbol_section_accessor (const elfio &elf_file_, section *symbol_section_)
Elf_Xword get_symbols_num () const
bool get_symbol (Elf_Xword index, std::string &name, Elf64_Addr &value, Elf_Xword &size, unsigned char &bind, unsigned char &type, Elf_Half &section_index, unsigned char &other) const
bool get_symbol (const std::string &name, Elf64_Addr &value, Elf_Xword &size, unsigned char &bind, unsigned char &type, Elf_Half &section_index, unsigned char &other) const
Elf_Word add_symbol (Elf_Word name, Elf64_Addr value, Elf_Xword size, unsigned char info, unsigned char other, Elf_Half shndx)
Elf_Word add_symbol (Elf_Word name, Elf64_Addr value, Elf_Xword size, unsigned char bind, unsigned char type, unsigned char other, Elf_Half shndx)
Elf_Word add_symbol (string_section_accessor &pStrWriter, const char *str, Elf64_Addr value, Elf_Xword size, unsigned char info, unsigned char other, Elf_Half shndx)
Elf_Word add_symbol (string_section_accessor &pStrWriter, const char *str, Elf64_Addr value, Elf_Xword size, unsigned char bind, unsigned char type, unsigned char other, Elf_Half shndx)
Private Member Functions
void find_hash_section ()
Elf_Half get_string_table_index () const
Elf_Half get_hash_table_index () const
template<class T >
bool generic_get_symbol (Elf_Xword index, std::string &name, Elf64_Addr &value, Elf_Xword &size, unsigned char &bind, unsigned char &type, Elf_Half &section_index, unsigned char &other) const
template<class T >
Elf_Word generic_add_symbol (Elf_Word name, Elf64_Addr value, Elf_Xword size, unsigned char info, unsigned char other, Elf_Half shndx)
Private Attributes
const elfio & elf_file
section * symbol_section
Elf_Half hash_section_index
const section * hash_section
Detailed Description
Definition at line 29 of file elfio_symbols.hpp.
Constructor & Destructor Documentation
ELFIO::symbol_section_accessor::symbol_section_accessor (const elfio & elf_file_, section * symbol_section_) inline
Definition at line 33 of file elfio_symbols.hpp.
References find_hash_section().
                                                                                 :
                              elf_file( elf_file_ ),
                              symbol_section( symbol_section_ )
     {
         find_hash_section();
     }
Member Function Documentation
Elf_Word ELFIO::symbol_section_accessor::add_symbol (Elf_Word name, Elf64_Addr value, Elf_Xword size, unsigned char info, unsigned char other, Elf_Half shndx) inline
Definition at line 114 of file elfio_symbols.hpp.
References elf_file, ELFCLASS32, and symbol_section.
Referenced by ELFIO::relocation_section_accessor::add_entry(), and add_symbol().
     {
         Elf_Word nRet;
         if ( symbol_section->get_size() == 0 ) {
             if ( elf_file.get_class() == ELFCLASS32 ) {
                 nRet = generic_add_symbol<Elf32_Sym>( 0, 0, 0, 0, 0, 0 );
             }
             else {
                 nRet = generic_add_symbol<Elf64_Sym>( 0, 0, 0, 0, 0, 0 );
             }
         }
         if ( elf_file.get_class() == ELFCLASS32 ) {
             nRet = generic_add_symbol<Elf32_Sym>( name, value, size, info, other,
                                                   shndx );
         }
         else {
             nRet = generic_add_symbol<Elf64_Sym>( name, value, size, info, other,
                                                   shndx );
         }
         return nRet;
     }
Elf_Word ELFIO::symbol_section_accessor::add_symbol (Elf_Word name, Elf64_Addr value, Elf_Xword size, unsigned char bind, unsigned char type, unsigned char other, Elf_Half shndx) inline
Definition at line 143 of file elfio_symbols.hpp.
References add_symbol(), and ELF_ST_INFO.
     {
         return add_symbol( name, value, size, ELF_ST_INFO( bind, type ), other, shndx );
     }
Elf_Word ELFIO::symbol_section_accessor::add_symbol (string_section_accessor & pStrWriter, const char * str, Elf64_Addr value, Elf_Xword size, unsigned char info, unsigned char other, Elf_Half shndx) inline
Definition at line 152 of file elfio_symbols.hpp.
References ELFIO::string_section_accessor::add_string(), and add_symbol().
     {
         Elf_Word index = pStrWriter.add_string( str );
         return add_symbol( index, value, size, info, other, shndx );
     }
Elf_Word ELFIO::symbol_section_accessor::add_symbol (string_section_accessor & pStrWriter, const char * str, Elf64_Addr value, Elf_Xword size, unsigned char bind, unsigned char type, unsigned char other, Elf_Half shndx) inline
Definition at line 163 of file elfio_symbols.hpp.
References add_symbol(), and ELF_ST_INFO.
     {
         return add_symbol( pStrWriter, str, value, size, ELF_ST_INFO( bind, type ), other, shndx );
     }
void ELFIO::symbol_section_accessor::find_hash_section () inline private
Definition at line 175 of file elfio_symbols.hpp.
References elf_file, hash_section, hash_section_index, ELFIO::elfio::sections, ELFIO::elfio::Sections::size(), and symbol_section.
Referenced by symbol_section_accessor().
     {
         hash_section       = 0;
         hash_section_index = 0;
         Elf_Half nSecNo = elf_file.sections.size();
         for ( Elf_Half i = 0; i < nSecNo && 0 == hash_section_index; ++i ) {
             const section* sec = elf_file.sections[i];
             if ( sec->get_link() == symbol_section->get_index() ) {
                 hash_section       = sec;
                 hash_section_index = i;
             }
         }
     }
template<class T > Elf_Word ELFIO::symbol_section_accessor::generic_add_symbol (Elf_Word name, Elf64_Addr value, Elf_Xword size, unsigned char info, unsigned char other, Elf_Half shndx) inline private
Definition at line 244 of file elfio_symbols.hpp.
References ELFIO::section::append_data(), elf_file, ELFIO::elfio::get_convertor(), and symbol_section.
     {
         const endianess_convertor& convertor = elf_file.get_convertor();
         T entry;
         entry.st_name  = convertor( name );
         entry.st_value = value;
         entry.st_value = convertor( entry.st_value );
         entry.st_size  = size;
         entry.st_size  = convertor( entry.st_size );
         entry.st_info  = convertor( info );
         entry.st_other = convertor( other );
         entry.st_shndx = convertor( shndx );
         symbol_section->append_data( reinterpret_cast<char*>( &entry ),
                                      sizeof( entry ) );
         Elf_Word nRet = symbol_section->get_size() / sizeof( entry ) - 1;
         return nRet;
     }
template<class T > bool ELFIO::symbol_section_accessor::generic_get_symbol (Elf_Xword index, std::string & name, Elf64_Addr & value, Elf_Xword & size, unsigned char & bind, unsigned char & type, Elf_Half & section_index, unsigned char & other) const inline private
Definition at line 206 of file elfio_symbols.hpp.
References elf_file, ELF_ST_BIND, ELF_ST_TYPE, ELFIO::elfio::get_convertor(), ELFIO::section::get_data(), ELFIO::string_section_accessor::get_string(), get_string_table_index(), get_symbols_num(), ELFIO::elfio::sections, and symbol_section.
     {
         bool ret = false;
         if ( index < get_symbols_num() ) {
             const T* pSym = reinterpret_cast<const T*>(
                 symbol_section->get_data() +
                     index * symbol_section->get_entry_size() );
             const endianess_convertor& convertor = elf_file.get_convertor();
             section* string_section = elf_file.sections[get_string_table_index()];
             string_section_accessor str_reader( string_section );
             const char* pStr = str_reader.get_string( convertor( pSym->st_name ) );
             if ( 0 != pStr ) {
                 name = pStr;
             }
             value   = convertor( pSym->st_value );
             size    = convertor( pSym->st_size );
             bind    = ELF_ST_BIND( pSym->st_info );
             type    = ELF_ST_TYPE( pSym->st_info );
             section_index = convertor( pSym->st_shndx );
             other   = pSym->st_other;
             ret = true;
         }
         return ret;
     }
Elf_Half ELFIO::symbol_section_accessor::get_hash_table_index () const inline private
Definition at line 198 of file elfio_symbols.hpp.
References hash_section_index.
Referenced by get_symbol().
     {
         return hash_section_index;
     }
Elf_Half ELFIO::symbol_section_accessor::get_string_table_index () const inline private
Definition at line 191 of file elfio_symbols.hpp.
References symbol_section.
Referenced by generic_get_symbol().
     {
         return (Elf_Half)symbol_section->get_link();
     }
bool ELFIO::symbol_section_accessor::get_symbol (Elf_Xword index, std::string & name, Elf64_Addr & value, Elf_Xword & size, unsigned char & bind, unsigned char & type, Elf_Half & section_index, unsigned char & other) const inline
Definition at line 54 of file elfio_symbols.hpp.
References elf_file, and ELFCLASS32.
Referenced by ELFIO::relocation_section_accessor::get_entry(), get_symbol(), and ELFIO::dump::symbol_tables().
     {
         bool ret = false;
         if ( elf_file.get_class() == ELFCLASS32 ) {
             ret = generic_get_symbol<Elf32_Sym>( index, name, value, size, bind,
                                                  type, section_index, other );
         }
         else {
             ret = generic_get_symbol<Elf64_Sym>( index, name, value, size, bind,
                                                  type, section_index, other );
         }
         return ret;
     }
bool ELFIO::symbol_section_accessor::get_symbol (const std::string & name, Elf64_Addr & value, Elf_Xword & size, unsigned char & bind, unsigned char & type, Elf_Half & section_index, unsigned char & other) const inline
Definition at line 79 of file elfio_symbols.hpp.
References ELFIO::elf_hash(), ELFIO::section::get_data(), get_hash_table_index(), get_symbol(), hash_section, STN_UNDEF, and LensCalibrationTest::y.
     {
         bool ret = false;
         if ( 0 != get_hash_table_index() ) {
             Elf_Word nbucket = *(Elf_Word*)hash_section->get_data();
             Elf_Word nchain  = *(Elf_Word*)( hash_section->get_data() +
                                    sizeof( Elf_Word ) );
             Elf_Word val     = elf_hash( (const unsigned char*)name.c_str() );
             Elf_Word y   = *(Elf_Word*)( hash_section->get_data() +
                                ( 2 + val % nbucket ) * sizeof( Elf_Word ) );
             std::string   str;
             get_symbol( y, str, value, size, bind, type, section_index, other );
             while ( str != name && STN_UNDEF != y && y < nchain ) {
                 y = *(Elf_Word*)( hash_section->get_data() +
                         ( 2 + nbucket + y ) * sizeof( Elf_Word ) );
                 get_symbol( y, str, value, size, bind, type, section_index, other );
             }
             if (  str == name ) {
                 ret = true;
             }
         }
         return ret;
     }
Elf_Xword ELFIO::symbol_section_accessor::get_symbols_num () const inline
Definition at line 42 of file elfio_symbols.hpp.
References symbol_section.
Referenced by generic_get_symbol(), and ELFIO::dump::symbol_tables().
     {
         Elf_Xword nRet = 0;
         if ( 0 != symbol_section->get_entry_size() ) {
             nRet = symbol_section->get_size() / symbol_section->get_entry_size();
         }
         return nRet;
     }
Member Data Documentation
const elfio& ELFIO::symbol_section_accessor::elf_file private
Definition at line 270 of file elfio_symbols.hpp.
Referenced by add_symbol(), find_hash_section(), generic_add_symbol(), generic_get_symbol(), and get_symbol().
const section* ELFIO::symbol_section_accessor::hash_section private
Definition at line 273 of file elfio_symbols.hpp.
Referenced by find_hash_section(), and get_symbol().
Elf_Half ELFIO::symbol_section_accessor::hash_section_index private
Definition at line 272 of file elfio_symbols.hpp.
Referenced by find_hash_section(), and get_hash_table_index().
section* ELFIO::symbol_section_accessor::symbol_section private
Definition at line 271 of file elfio_symbols.hpp.
Referenced by add_symbol(), find_hash_section(), generic_add_symbol(), generic_get_symbol(), get_string_table_index(), and get_symbols_num().
The documentation for this class was generated from the following file:
elfio_symbols.hpp