Voxel: Voxel::CameraSystem Class Reference
Voxel::CameraSystem Class Reference
Camera System Components
This class provides ways to instantiate individual cameras and components like filters.
#include <CameraSystem.h>
Public Member Functions
CameraSystem ()
bool addDepthCameraFactory (DepthCameraFactoryPtr factory)
Vector< DevicePtr > scan ()
DepthCameraPtr connect (const DevicePtr &device)
bool disconnect (const DepthCameraPtr &depthCamera, bool reset=false)
bool addFilterFactory (FilterFactoryPtr filterFactory)
Vector< String > getSupportedFilters ()
bool getFilterDescription (const String &filterName, FilterDescription &description)
FilterPtr createFilter (const String &name, DepthCamera::FrameType type)
Vector< DevicePtr > getProgrammableDevices ()
bool addDownloaderFactory (DownloaderFactoryPtr downloaderFactory)
DownloaderPtr getDownloader (const DevicePtr &device)
bool getFrameGenerator (uint8_t frameType, GeneratorIDType generatorID, FrameGeneratorPtr &frameGenerator)
virtual ~CameraSystem ()
Protected Member Functions
void _init ()
void _loadLibraries (const Vector< String > &paths)
Protected Attributes
Vector< DepthCameraLibraryPtr > _libraries
Map< String,
DepthCameraFactoryPtr > _factories
Map< String, DepthCameraPtr > _depthCameras
Map< String, FilterFactoryPtr > _filterFactories
Map< String, DownloaderFactoryPtr > _downloaderFactories
Map< GeneratorIDType,
DepthCameraFactoryPtr > _factoryForGeneratorID
Detailed Description
This class provides ways to instantiate individual cameras and components like filters.
Definition at line 28 of file CameraSystem.h.
Constructor & Destructor Documentation
Voxel::CameraSystem::CameraSystem ()
Definition at line 24 of file CameraSystem.cpp.
References _init().
 {
   _init();
 }
Voxel::CameraSystem::~CameraSystem () virtual
Definition at line 416 of file CameraSystem.cpp.
References _depthCameras, _downloaderFactories, _factories, _factoryForGeneratorID, and _libraries.
 {
   _depthCameras.clear();
   _factories.clear();
   _downloaderFactories.clear();
   _factoryForGeneratorID.clear();
   _libraries.clear();
 }
Member Function Documentation
void Voxel::CameraSystem::_init () protected
Definition at line 30 of file CameraSystem.cpp.
References _loadLibraries(), addFilterFactory(), and Voxel::Configuration::getLibPaths().
Referenced by CameraSystem().
 {
   addFilterFactory(FilterFactoryPtr(new VoxelFilterFactory()));
   Configuration c;
   Vector<String> paths;
   c.getLibPaths(paths);
   _loadLibraries(paths);
 }
void Voxel::CameraSystem::_loadLibraries (const Vector< String > & paths) protected
Definition at line 43 of file CameraSystem.cpp.
References _libraries, addDepthCameraFactory(), addDownloaderFactory(), addFilterFactory(), Voxel::getFiles(), Voxel::LOG_DEBUG, Voxel::LOG_INFO, Voxel::LOG_WARNING, and Voxel::logger.
Referenced by _init().
 {
   Vector<String> files;
   int numberOfLoadLibraries = 0;
   for(auto &path: paths)
   {
     getFiles(path, LIB_MATCH_STRING, files);
     for(auto &file: files)
     {
       std::ifstream ff(file, std::ios::binary);
       if(ff.good()) // File readable
       {
         ff.close();
         DepthCameraLibraryPtr p(new DepthCameraLibrary(file));
         if (p->getABIVersion() != VOXEL_ABI_VERSION)
         {
           logger(LOG_WARNING) << "CameraSystem: Ignoring Voxel library " << file << " with ABI version = " << p->getABIVersion() << ". Expected ABI version = " << VOXEL_ABI_VERSION << std::endl;
           continue;
         }
         if(!p->load())
         {
           logger(LOG_WARNING) << "CameraSystem: Failed to load library " << file << ". Ignoring it." << std::endl;
           continue;
         }
         bool success = false;
         DepthCameraFactoryPtr factory = p->getDepthCameraFactory();
         if(!factory || !addDepthCameraFactory(factory))
           logger(LOG_WARNING) << "CameraSystem: Failed to load or register a depth camera factory from library " << file  <<". Ignoring this library." << std::endl;
         else
           success = true;
         FilterFactoryPtr filterFactory = p->getFilterFactory();
         if(!filterFactory || !addFilterFactory(filterFactory))
           logger(LOG_DEBUG) << "CameraSystem: Could not find filter factory" << std::endl;
         else
           success = true;
         DownloaderFactoryPtr downloaderFactory = p->getDownloaderFactory();
         if(!downloaderFactory || !addDownloaderFactory(downloaderFactory))
           logger(LOG_DEBUG) << "CameraSystem: Could not find downloader factory" << std::endl;
         else
           success = true;
         if(success)
         {
           // Preserving this library
           _libraries.push_back(p);
           numberOfLoadLibraries++;
           logger(LOG_INFO) << "CameraSystem: Successfully loaded factory from library " << file << std::endl;
         }
       }
       else
         logger(LOG_WARNING) << "CameraSystem: Library file " << file << " is not readable. Ignoring it." << std::endl;
     }
   }
   if(!numberOfLoadLibraries)
     logger(LOG_WARNING) << "CameraSystem: No depth camera library found or loaded." << std::endl;
 }
bool Voxel::CameraSystem::addDepthCameraFactory (DepthCameraFactoryPtr factory)
Definition at line 116 of file CameraSystem.cpp.
References _factories, _factoryForGeneratorID, CameraSystemTest::devices, Voxel::LOG_DEBUG, Voxel::LOG_WARNING, and Voxel::logger.
Referenced by _loadLibraries().
 {
   // Adding factory to the "_factories" map for later query
   const Vector<DevicePtr> &devices = factory->getSupportedDevices();
   if(!devices.size()) // No devices?
     return false;
   int numberOfDevicesAdded = 0;
   for(auto &device: devices)
   {
     if(device->serialNumber().size())
     {
       logger(LOG_WARNING) << "CameraSystem: Device type " << device->id() << " being registered from factory has serial number. Ignoring it." << std::endl;
       continue;
     }
     auto f = _factories.find(device->id());
     if(f != _factories.end())
     {
       logger(LOG_WARNING) << "CameraSystem: Device type " << device->id() << " already has a factory '" << f->second->name() << "'. Not overwriting it." << std::endl;
       continue;
     }
     numberOfDevicesAdded++;
     _factories[device->id()] = factory;
   }
   if(!numberOfDevicesAdded)
   {
     logger(LOG_WARNING) << "CameraSystem: No devices added from factory '" << factory->name() << "'. Ignoring this factory." << std::endl;
     return false;
   }
   Vector<GeneratorIDType> supportedGeneratorIDs = factory->getSupportedGeneratorTypes();
   for(auto &d: supportedGeneratorIDs)
   {
     auto f = _factoryForGeneratorID.find(d);
     if(f != _factoryForGeneratorID.end())
     {
       logger(LOG_DEBUG) << "CameraSystem: A factory is already registered for generator ID '" << d << "'. Not replacing it." << std::endl;
       continue;
     }
     _factoryForGeneratorID[d] = factory;
   }
   return true;
 }
bool Voxel::CameraSystem::addDownloaderFactory (DownloaderFactoryPtr downloaderFactory)
Definition at line 361 of file CameraSystem.cpp.
References _downloaderFactories, CameraSystemTest::devices, Voxel::LOG_WARNING, and Voxel::logger.
Referenced by _loadLibraries().
 {
   // Adding factory to the "_downloaderFactories" map for later query
   const Vector<DevicePtr> &devices = factory->getSupportedDevices();
   if(!devices.size()) // No devices?
     return false;
   int numberOfDevicesAdded = 0;
   for(auto &device: devices)
   {
     if(device->serialNumber().size())
     {
       logger(LOG_WARNING) << "CameraSystem: Device type " << device->id() << " being registered from downloader factory has serial number. Ignoring it." << std::endl;
       continue;
     }
     auto f = _downloaderFactories.find(device->id());
     if(f != _downloaderFactories.end())
     {
       logger(LOG_WARNING) << "CameraSystem: Device type " << device->id() << " already has a downloader factory '" << f->second->name() << "'. Not overwriting it." << std::endl;
       continue;
     }
     numberOfDevicesAdded++;
     _downloaderFactories[device->id()] = factory;
   }
   if(!numberOfDevicesAdded)
   {
     logger(LOG_WARNING) << "CameraSystem: No devices added from downloader factory '" << factory->name() << ". Ignoring this factory." << std::endl;
     return false;
   }
   return true;
 }
bool Voxel::CameraSystem::addFilterFactory (FilterFactoryPtr filterFactory)
Definition at line 190 of file CameraSystem.cpp.
References _filterFactories, Voxel::LOG_WARNING, Voxel::logger, and LensCalibrationTest::x.
Referenced by _init(), and _loadLibraries().
 {
   auto &desc = filterFactory->getSupportedFilters();
   for(auto &d: desc)
   {
     auto x = _filterFactories.find(d.first);
     if(x != _filterFactories.end())
     {
       logger(LOG_WARNING) << "CameraSystem: A filter with name '" << d.first << "' is already registered. Ignoring the new one." << std::endl;
       continue;
     }
     _filterFactories[d.first] = filterFactory;
   }
   return true;
 }
DepthCameraPtr Voxel::CameraSystem::connect (const DevicePtr & device)
Definition at line 274 of file CameraSystem.cpp.
References _depthCameras, _factories, Voxel::LOG_ERROR, Voxel::LOG_INFO, and Voxel::logger.
Referenced by Voxel::CLIManager::_connect(), Voxel::CLIManager::CLIManager(), and main().
 {
   auto c = _depthCameras.find(device->id());
   if(c != _depthCameras.end())
   {
     logger(LOG_INFO) << "CameraSystem: DepthCamera for " << device->id() << " was already created. Returning it." << std::endl;
     if(!c->second->refreshParams())
       logger(LOG_ERROR) << "CameraSystem: Could not refresh parameters for " << c->second->id() << "." << std::endl;
     else
       logger(LOG_INFO) << "CameraSystem: Successfully refreshed parameters for " << c->second->id() << "." << std::endl;
     return c->second;
   }
   Device d(device->interfaceID(), device->deviceID(), ""); // get device ID without serial number
   auto f = _factories.find(d.id());
   if(f != _factories.end())
   {
     DepthCameraPtr p = f->second->getDepthCamera(device);
     if(!p->refreshParams())
       logger(LOG_ERROR) << "CameraSystem: Could not refresh parameters for " << p->id() << "." << std::endl;
     else
       logger(LOG_INFO) << "CameraSystem: Successfully refreshed parameters for " << p->id() << "." << std::endl;
     _depthCameras[p->getDevice()->id()] = p;
     return p;
   }
   else
     return nullptr;
 }
FilterPtr Voxel::CameraSystem::createFilter (const String & name, DepthCamera::FrameType type)
Definition at line 307 of file CameraSystem.cpp.
References _filterFactories, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::CLIManager::_addFilter2(), and main().
 {
   auto f = _filterFactories.find(name);
   if(f != _filterFactories.end())
   {
     return f->second->createFilter(name, type);
   }
   else
   {
     logger(LOG_ERROR) << "CameraSystem: Unknown filter '" << name << "'" << std::endl;
     return nullptr;
   }
 }
bool Voxel::CameraSystem::disconnect (const DepthCameraPtr & depthCamera, bool reset = false)
Definition at line 323 of file CameraSystem.cpp.
References _depthCameras.
Referenced by Voxel::CLIManager::_disconnect(), and Voxel::CLIManager::_reset().
 {
   auto f = _depthCameras.find(depthCamera->getDevice()->id());
   if(f != _depthCameras.end())
   {
     _depthCameras.erase(f);
     bool ret;
     if(reset)
       ret = depthCamera->reset();
     return depthCamera->close() && ret;
   }
   return false;
 }
DownloaderPtr Voxel::CameraSystem::getDownloader (const DevicePtr & device)
Definition at line 400 of file CameraSystem.cpp.
References _downloaderFactories.
 {
   Device d(device->interfaceID(), device->deviceID(), ""); // get device ID without serial number
   auto f = _downloaderFactories.find(d.id());
   if(f != _downloaderFactories.end())
   {
     DownloaderPtr p = f->second->getDownloader(device);
     return p;
   }
   else
     return nullptr;
 }
bool Voxel::CameraSystem::getFilterDescription (const String & filterName, FilterDescription & description)
Definition at line 220 of file CameraSystem.cpp.
References _filterFactories, LensCalibrationTest::x, and LensCalibrationTest::y.
 {
   auto x = _filterFactories.find(filterName);
   if(x != _filterFactories.end())
   {
     auto &desc = x->second->getSupportedFilters();
     auto y = desc.find(filterName);
     if(y != desc.end())
     {
       description = y->second;
       return true;
     }
   }
   return false;
 }
bool Voxel::CameraSystem::getFrameGenerator (uint8_t frameType, GeneratorIDType generatorID, FrameGeneratorPtr & frameGenerator)
Definition at line 170 of file CameraSystem.cpp.
References _factoryForGeneratorID, Voxel::DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::FrameStreamReader::_init().
 {
   if(frameType == DepthCamera::FRAME_XYZI_POINT_CLOUD_FRAME)
   {
     frameGenerator = FrameGeneratorPtr(new PointCloudFrameGenerator());
     return true;
   }
   else
   {
     auto f = _factoryForGeneratorID.find(generatorID);
     if(f == _factoryForGeneratorID.end())
     {
       logger(LOG_ERROR) << "CameraSystem: Could not find factory for generator ID '" << generatorID << "'" << std::endl;
       return false;
     }
     return f->second->getFrameGenerator(frameType, generatorID, frameGenerator);
   }
 }
Vector< DevicePtr > Voxel::CameraSystem::getProgrammableDevices ()
Definition at line 341 of file CameraSystem.cpp.
References _downloaderFactories, CameraSystemTest::devices, and Voxel::DeviceScanner::scan().
 {
   Vector<DevicePtr> devices = DeviceScanner::scan();
   Vector<DevicePtr> toReturn;
   for(auto &device: devices)
   {
     Device d(device->interfaceID(), device->deviceID(), ""); // get device ID without serial number
     auto f = _downloaderFactories.find(d.id());
     if(f != _downloaderFactories.end())
     {
       toReturn.push_back(device);
     }
   }
   return toReturn;
 }
Vector< String > Voxel::CameraSystem::getSupportedFilters ()
Definition at line 209 of file CameraSystem.cpp.
References _filterFactories, and LensCalibrationTest::x.
Referenced by Voxel::CLIManager::_addFilterCompletion(), and Voxel::CLIManager::_filters().
 {
   Vector<String> f;
   f.reserve(_filterFactories.size());
   for(auto &x: _filterFactories)
     f.push_back(x.first);
   return f;
 }
Vector< DevicePtr > Voxel::CameraSystem::scan ()
Definition at line 240 of file CameraSystem.cpp.
References _factories, CameraSystemTest::devices, Voxel::LOG_WARNING, Voxel::logger, and Voxel::DeviceScanner::scan().
Referenced by Voxel::CLIManager::_connect(), Voxel::CLIManager::_connectCompletion(), Voxel::CLIManager::_list(), Voxel::CLIManager::CLIManager(), and main().
 {
   Vector<DevicePtr> devices = DeviceScanner::scan();
   Vector<DevicePtr> toReturn;
   Vector<int> channels;
   for(auto &device: devices)
   {
     Device d(device->interfaceID(), device->deviceID(), ""); // get device ID without serial number
     auto f = _factories.find(d.id());
     if(f != _factories.end())
     {
       if(!f->second->getChannels(d, channels) || channels.size() == 0)
       {
         logger(LOG_WARNING) << "CameraSystem: Could not get channels for device '" << device->id() << "'" << std::endl;
         continue;
       }
       if(channels.size() == 1)
         toReturn.push_back(device);
       else
       {
         const Vector<DevicePtr> &ds = device->getDevices(channels);
         toReturn.insert(toReturn.end(), ds.begin(), ds.end());
       }
     }
   }
   return toReturn;
 }
Member Data Documentation
Map<String, DepthCameraPtr> Voxel::CameraSystem::_depthCameras protected
Definition at line 33 of file CameraSystem.h.
Referenced by connect(), disconnect(), and ~CameraSystem().
Map<String, DownloaderFactoryPtr> Voxel::CameraSystem::_downloaderFactories protected
Definition at line 37 of file CameraSystem.h.
Referenced by addDownloaderFactory(), getDownloader(), getProgrammableDevices(), and ~CameraSystem().
Map<String, DepthCameraFactoryPtr> Voxel::CameraSystem::_factories protected
Definition at line 32 of file CameraSystem.h.
Referenced by addDepthCameraFactory(), connect(), scan(), and ~CameraSystem().
Map<GeneratorIDType, DepthCameraFactoryPtr> Voxel::CameraSystem::_factoryForGeneratorID protected
Definition at line 39 of file CameraSystem.h.
Referenced by addDepthCameraFactory(), getFrameGenerator(), and ~CameraSystem().
Map<String, FilterFactoryPtr> Voxel::CameraSystem::_filterFactories protected
Definition at line 35 of file CameraSystem.h.
Referenced by addFilterFactory(), createFilter(), getFilterDescription(), and getSupportedFilters().
Vector<DepthCameraLibraryPtr> Voxel::CameraSystem::_libraries protected
Definition at line 31 of file CameraSystem.h.
Referenced by _loadLibraries(), and ~CameraSystem().
The documentation for this class was generated from the following files:
CameraSystem.h
CameraSystem.cpp