Voxel: Voxel::DepthCamera Class Reference
Voxel::DepthCamera Class Reference abstract
Camera System Components
This is primary class which provides API for a depth camera.
#include <DepthCamera.h>
Public Types
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Member Functions
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
virtual bool setSerialNumber (const String &serialNumber)
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (int &id)
bool close ()
virtual ~DepthCamera ()
Public Attributes
MainConfigurationFile configFile
Protected Member Functions
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _start ()=0
virtual bool _stop ()=0
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)=0
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)=0
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)=0
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
virtual bool _setFrameRate (const FrameRate &r)=0
virtual bool _getFrameRate (FrameRate &r) const =0
virtual bool _setFrameSize (const FrameSize &s)=0
virtual bool _getFrameSize (FrameSize &s) const =0
virtual bool _getMaximumFrameSize (FrameSize &s) const =0
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const =0
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const =0
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const =0
virtual bool _getBytesPerPixel (uint &bpp) const =0
virtual bool _setBytesPerPixel (const uint &bpp)=0
virtual bool _getROI (RegionOfInterest &roi)=0
virtual bool _setROI (const RegionOfInterest &roi)=0
virtual bool _allowedROI (String &message)=0
virtual bool _getFieldOfView (float &fovHalfAngle) const =0
void _makeID ()
virtual bool _reset ()=0
virtual bool _onReset ()=0
virtual bool _applyConfigParams (const ConfigSet *params)
virtual bool _saveCurrentProfileID (const int id)=0
virtual bool _getCurrentProfileID (int &id)=0
bool _init ()
Protected Attributes
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Private Attributes
Mutex _accessMutex
Mutex _frameStreamWriterMutex
Detailed Description
This is primary class which provides API for a depth camera.
DepthCamera is an abstract class which needs to be derived and implemented for individual depth camera types.
Definition at line 39 of file DepthCamera.h.
Member Typedef Documentation
typedef Function<void (DepthCamera &camera, const Frame &frame, FrameType callBackType)> Voxel::DepthCamera::CallbackType
Definition at line 51 of file DepthCamera.h.
Member Enumeration Documentation
enum Voxel::DepthCamera::FrameType
Enumerator
FRAME_RAW_FRAME_UNPROCESSED
FRAME_RAW_FRAME_PROCESSED
FRAME_DEPTH_FRAME
FRAME_XYZI_POINT_CLOUD_FRAME
FRAME_TYPE_COUNT
Definition at line 42 of file DepthCamera.h.
   {
     FRAME_RAW_FRAME_UNPROCESSED = 0,
     FRAME_RAW_FRAME_PROCESSED = 1,
     FRAME_DEPTH_FRAME = 2,
     FRAME_XYZI_POINT_CLOUD_FRAME = 3,
     FRAME_TYPE_COUNT = 4 // This is just used for number of callback types
   };
Constructor & Destructor Documentation
Voxel::DepthCamera::DepthCamera (const String & name, DevicePtr device)
Definition at line 20 of file DepthCamera.cpp.
References _frameGenerators, _makeID(), _pointCloudFrameGenerator, configFile, and Voxel::MainConfigurationFile::read().
                                                             : _device(device), _name(name),
 _rawFrameBuffers(MAX_FRAME_BUFFERS), _depthFrameBuffers(MAX_FRAME_BUFFERS), _pointCloudBuffers(MAX_FRAME_BUFFERS),
 _parameterInit(true), _running(false),
 _unprocessedFilters(_rawFrameBuffers), _processedFilters(_rawFrameBuffers), _depthFilters(_depthFrameBuffers),
 _pointCloudFrameGenerator(new PointCloudFrameGenerator()),
 configFile(name, "")
 {
   _frameGenerators[2] = std::dynamic_pointer_cast<FrameGenerator>(_pointCloudFrameGenerator);
   _makeID();
   configFile.read(name + ".conf"); // Read and keep the configuration ready for use. The file must be in VOXEL_CONF_PATH
 }
Voxel::DepthCamera::~DepthCamera () virtual
Definition at line 363 of file DepthCamera.cpp.
References close().
 {
   close();
 }
Member Function Documentation
bool Voxel::DepthCamera::_addParameters (const Vector< ParameterPtr > & params) protected
Definition at line 55 of file DepthCamera.cpp.
References _parameters, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::CalculusCDKCamera::_init(), Voxel::TI::HaddockCDKCamera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), Voxel::TI::ToFTintinCamera::_init(), and Voxel::TI::ToFCamera::_init().
 {
   _parameters.reserve(_parameters.size() + params.size());
   for(const ParameterPtr &p: params)
   {
     if(_parameters.find(p->name()) == _parameters.end())
     {
       _parameters[p->name()] = p;
     }
     else
     {
       logger(LOG_ERROR) << "DepthCamera: Found an existing parameter in the list of parameters, with name " << p->name() << ". Not overwriting it." << std::endl;
       //return _parameterInit = false;
     }
   }
   return true;
 }
virtual bool Voxel::DepthCamera::_allowedROI (String & message) protected pure virtual
Implemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by allowedROI().
bool Voxel::DepthCamera::_applyConfigParams (const ConfigSet * params) protected virtual
Definition at line 614 of file DepthCamera.cpp.
References _programmer, Voxel::FrameRate::denominator, Voxel::gcd(), Voxel::ConfigSet::get(), Voxel::ConfigSet::getBoolean(), Voxel::ConfigSet::getFloat(), Voxel::ConfigSet::getInteger(), getParam(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, Voxel::FrameRate::numerator, Voxel::ConfigSet::paramNames, CameraSystemIQFrameTest::r, set(), and setFrameRate().
Referenced by setCameraProfile().
 {
   for(auto i = 0; i < params->paramNames.size(); i++)
   {
     if(params->paramNames[i].compare(0, 2, "0x") == 0)
     {
       logger(LOG_INFO) << "DepthCamera: Setting register '" << params->paramNames[i] << "'" << std::endl;
       char *endptr;
       uint32_t reg = (uint32_t)strtol(params->paramNames[i].c_str(), &endptr, 16);
       uint32_t value = (uint32_t)strtol(params->get(params->paramNames[i]).c_str(), &endptr, 0);
       if(!_programmer->writeRegister(reg, value))
       {
         logger(LOG_ERROR) << "Failed to write to register @0x" << std::hex << reg << " = 0x" << value << std::dec << std::endl;
       }
       continue;
     }
     else if(params->paramNames[i] == "frame_rate")
     {
       float rate = params->getFloat(params->paramNames[i]);
       FrameRate r;
       r.numerator = rate*10000;
       r.denominator = 10000;
       uint g = gcd(r.numerator, r.denominator);
       r.numerator /= g;
       r.denominator /= g;
       if(!setFrameRate(r))
       {
         logger(LOG_ERROR) << "DepthCamera: Failed to set frame rate to " << rate << "fps" << std::endl;
         return false;
       }
       continue;
     }
     logger(LOG_INFO) << "DepthCamera: Setting parameter '" << params->paramNames[i] << "'" << std::endl;
     const Parameter *p = getParam(params->paramNames[i]).get();
     if(!p)
     {
       logger(LOG_ERROR) << "DepthCamera: Ignoring unknown parameter " << params->paramNames[i] << std::endl;
       return false;
     }
     const BoolParameter *bp = dynamic_cast<const BoolParameter *>(p);
     const EnumParameter *ep = dynamic_cast<const EnumParameter *>(p);
     const IntegerParameter *ip = dynamic_cast<const IntegerParameter *>(p);
     const UnsignedIntegerParameter *up = dynamic_cast<const UnsignedIntegerParameter *>(p);
     const FloatParameter *fp = dynamic_cast<const FloatParameter *>(p);
     if(bp)
     {
       if(!set(params->paramNames[i], params->getBoolean(params->paramNames[i])))
         return false;
     }
     else if(ip || ep)
     {
       if(!set(params->paramNames[i], params->getInteger(params->paramNames[i])))
         return false;
     }
     else if(up)
     {
       if(!set(params->paramNames[i], (uint)params->getInteger(params->paramNames[i])))
         return false;
     }
     else if(fp)
     {
       if(!set(params->paramNames[i], params->getFloat(params->paramNames[i])))
         return false;
     }
     else
     {
       logger(LOG_ERROR) << "DepthCamera: Parameter type unknown for " << params->paramNames[i] << std::endl;
       return false;
     }
   }
   return true;
 }
bool Voxel::DepthCamera::_callbackAndContinue (uint32_t & callBackTypesToBeCalled, DepthCamera::FrameType type, const Frame & frame) protected virtual
Definition at line 106 of file DepthCamera.cpp.
References _callback.
Referenced by _captureLoop().
 {
   if((callBackTypesToBeCalled | (1 << type)) && _callback[type])
   {
     _callback[type](*this, frame, type);
   }
   callBackTypesToBeCalled &= ~(1 << type);
   return callBackTypesToBeCalled != 0;
 }
void Voxel::DepthCamera::_captureLoop () protected virtual
Definition at line 119 of file DepthCamera.cpp.
References _callback, _callbackAndContinue(), _callBackTypesRegistered, _captureRawUnprocessedFrame(), _convertToDepthFrame(), _convertToPointCloudFrame(), _depthFilters, _depthFrameBuffers, _pointCloudBuffers, _processedFilters, _processRawFrame(), _rawFrameBuffers, _running, _stop(), _unprocessedFilters, _writeToFrameStream(), closeFrameStream(), FRAME_DEPTH_FRAME, FRAME_RAW_FRAME_PROCESSED, FRAME_RAW_FRAME_UNPROCESSED, FRAME_XYZI_POINT_CLOUD_FRAME, id(), isSavingFrameStream(), Voxel::LOG_ERROR, Voxel::LOG_INFO, and Voxel::logger.
Referenced by _captureThreadWrapper().
 {
   uint consecutiveCaptureFails = 0;
   while(_running)
   {
     uint32_t callBackTypesToBeCalled = _callBackTypesRegistered;
     if(consecutiveCaptureFails > 100)
     {
       logger(LOG_ERROR) << "DepthCamera: 100 consecutive failures in capture of frame. Stopping stream for " << id() << std::endl;
       _running = false;
       continue;
     }
     if((_callBackTypesRegistered == 0 || _callBackTypesRegistered == FRAME_RAW_FRAME_UNPROCESSED) && !isSavingFrameStream()) // Only unprocessed frame types requested or none requested?
     {
       auto f = _rawFrameBuffers.get();
       if(!_captureRawUnprocessedFrame(*f))
       {
         consecutiveCaptureFails++;
         continue;
       }
       if(_callback[FRAME_RAW_FRAME_UNPROCESSED])
       {
         FilterSet<RawFrame>::FrameSequence _frameBuffers;
         _frameBuffers.push_front(f);
         if(!_unprocessedFilters.applyFilter(_frameBuffers))
         {
           logger(LOG_ERROR) << "DepthCamera: Failed to apply filters on raw unprocessed frame" << std::endl;
           consecutiveCaptureFails++;
           continue;
         }
         _callback[FRAME_RAW_FRAME_UNPROCESSED](*this, (Frame &)(**_frameBuffers.begin()), FRAME_RAW_FRAME_UNPROCESSED);
         _writeToFrameStream(**_frameBuffers.begin());
       }
       else
       {
         _writeToFrameStream(*f);
       }
       consecutiveCaptureFails = 0;
     }
     else
     {
       auto f1 = _rawFrameBuffers.get();
       if(!_captureRawUnprocessedFrame(*f1))
       {
         consecutiveCaptureFails++;
         continue;
       }
       FilterSet<RawFrame>::FrameSequence _unprocessedFrameBuffers;
       _unprocessedFrameBuffers.push_front(f1);
       if(!_unprocessedFilters.applyFilter(_unprocessedFrameBuffers))
       {
         logger(LOG_ERROR) << "DepthCamera: Failed to apply filters on raw unprocessed frame" << std::endl;
         consecutiveCaptureFails++;
         continue;
       }
       if(!_callbackAndContinue(callBackTypesToBeCalled, FRAME_RAW_FRAME_UNPROCESSED, ***_unprocessedFrameBuffers.begin()) && !isSavingFrameStream())
       {
         consecutiveCaptureFails = 0;
         continue;
       }
       auto f = _rawFrameBuffers.get();
       if(!_processRawFrame(**_unprocessedFrameBuffers.begin(), *f))
       {
         consecutiveCaptureFails++;
         continue;
       }
       FilterSet<RawFrame>::FrameSequence _processedFrameBuffers;
       _processedFrameBuffers.push_front(f);
       if(!_processedFilters.applyFilter(_processedFrameBuffers))
       {
         logger(LOG_ERROR) << "DepthCamera: Failed to apply filters on raw processed frame" << std::endl;
         consecutiveCaptureFails++;
         continue;
       }
       if(!_callbackAndContinue(callBackTypesToBeCalled, FRAME_RAW_FRAME_PROCESSED, ***_processedFrameBuffers.begin())  && !isSavingFrameStream())
       {
         consecutiveCaptureFails = 0;
         continue;
       }
       auto d = _depthFrameBuffers.get();
       if(!_convertToDepthFrame(**_processedFrameBuffers.begin(), *d))
       {
         consecutiveCaptureFails++;
         continue;
       }
       FilterSet<DepthFrame>::FrameSequence _depthFrameBuffers;
       _depthFrameBuffers.push_front(d);
       if(!_depthFilters.applyFilter(_depthFrameBuffers))
       {
         logger(LOG_ERROR) << "DepthCamera: Failed to apply filters on depth frame" << std::endl;
         consecutiveCaptureFails++;
         continue;
       }
       if(!_callbackAndContinue(callBackTypesToBeCalled, FRAME_DEPTH_FRAME, ***_depthFrameBuffers.begin()) && !isSavingFrameStream())
       {
         consecutiveCaptureFails = 0;
         continue;
       }
       auto p = _pointCloudBuffers.get();
       if(!_convertToPointCloudFrame(**_depthFrameBuffers.begin(), *p))
       {
         consecutiveCaptureFails++;
         continue;
       }
       _callbackAndContinue(callBackTypesToBeCalled, FRAME_XYZI_POINT_CLOUD_FRAME, **p);
       consecutiveCaptureFails = 0;
       _writeToFrameStream(**_unprocessedFrameBuffers.begin());
     }
   }
   if(!_running)
   {
     closeFrameStream();
     _stop();
   }
   logger(LOG_INFO) << "DepthCamera: Streaming stopped." << std::endl;
 }
virtual bool Voxel::DepthCamera::_captureRawUnprocessedFrame (RawFramePtr & rawFrame) protected pure virtual
Implemented in Voxel::TI::ToFCameraBase.
Referenced by _captureLoop().
void Voxel::DepthCamera::_captureThreadWrapper () protected
Definition at line 287 of file DepthCamera.cpp.
References _captureLoop().
Referenced by start().
 {
   _captureLoop();
 }
virtual bool Voxel::DepthCamera::_convertToDepthFrame (const RawFramePtr & rawFrame, DepthFramePtr & depthFrame) protected pure virtual
Implemented in Voxel::TI::ToFCameraBase.
Referenced by _captureLoop().
bool Voxel::DepthCamera::_convertToPointCloudFrame (const DepthFramePtr & depthFrame, PointCloudFramePtr & pointCloudFrame) protected virtual
Definition at line 264 of file DepthCamera.cpp.
References _pointCloudFrameGenerator, Voxel::LOG_ERROR, Voxel::logger, LensCalibrationTest::p1, and LensCalibrationTest::p2.
Referenced by _captureLoop().
 {
   if(!depthFrame)
   {
     logger(LOG_ERROR) << "DepthCamera: Blank depth frame." << std::endl;
     return false;
   }
   FramePtr p1 = std::dynamic_pointer_cast<Frame>(depthFrame);
   FramePtr p2 = std::dynamic_pointer_cast<Frame>(pointCloudFrame);
   bool ret = _pointCloudFrameGenerator->generate(p1, p2);
   if(ret)
   {
     pointCloudFrame = std::dynamic_pointer_cast<PointCloudFrame>(p2);
     return true;
   }
   else
     return false;
 }
template<typename T > bool Voxel::DepthCamera::_get (const String & name, T & value, bool refresh = false) const protected
Definition at line 353 of file DepthCamera.h.
References _id, _parameters, Voxel::ParameterTemplate< T >::get(), Voxel::LOG_ERROR, Voxel::logger, and name().
Referenced by Voxel::TI::ToFCamera::_getBytesPerPixel(), Voxel::TI::ToFCamera::_getCurrentProfileID(), Voxel::TI::ToFCamera::_getFrameRate(), Voxel::TI::ToFCamera::_getFrameSize(), Voxel::TI::HaddockCDKCamera::_getMaximumFrameRate(), Voxel::TI::TintinCDKCamera::_getMaximumFrameRate(), Voxel::TI::Voxel14Camera::_getMaximumVideoMode(), Voxel::TI::VoxelDCamera::_getMaximumVideoMode(), Voxel::TI::TintinCDKCamera::_getMaximumVideoMode(), Voxel::TI::ToFHaddockCamera::_getROI(), Voxel::TI::ToFCalculusCamera::_getROI(), Voxel::TI::ToFTintinCamera::_getROI(), Voxel::TI::ToFCamera::_getToFFrameType(), Voxel::TI::ToFHaddockCamera::_isHistogramEnabled(), Voxel::TI::ToFCamera::_setFrameRate(), Voxel::TI::Voxel14Camera::_setStreamerFrameSize(), Voxel::TI::HaddockCDKCamera::_setStreamerFrameSize(), Voxel::TI::VoxelDCamera::_setStreamerFrameSize(), Voxel::TI::TintinCDKCamera::_setStreamerFrameSize(), Voxel::TI::ToFCalculusCamera::_updateEasyConf(), Voxel::TI::HaddockVCOFrequency::get(), Voxel::TI::IntegrationTimeParameter::get(), Voxel::TI::TintinVCOFrequency::get(), Voxel::TI::HaddockCDKIlluminationPowerPercentageParameter::get(), Voxel::TI::HaddockModulationFrequencyParameter::get(), Voxel::TI::CalculusVCOFrequency::get(), Voxel::TI::TintinModulationFrequencyParameter::get(), get(), Voxel::TI::CalculusModulationFrequencyParameter::get(), Voxel::TI::TintinUnambiguousRangeParameter::get(), Voxel::TI::HaddockSensorTemperatureParameter::get(), Voxel::TI::TintinModulationFrequencyParameter::lowerLimit(), Voxel::TI::IntegrationTimeParameter::set(), Voxel::TI::TintinModulationFrequencyParameter::set(), and Voxel::TI::TintinModulationFrequencyParameter::upperLimit().
 {
   auto p = _parameters.find(name);
   if(p != _parameters.end())
   {
     ParameterTemplate<T> *param = dynamic_cast<ParameterTemplate<T> *>(p->second.get());
     if(param == 0)
     {
       logger(LOG_ERROR) << "DepthCamera: Invalid value type '" << typeid(value).name() << "' used to get parameter " << _id << "." << name << std::endl;
       return false;
     }
     if(!param->get(value, refresh))
     {
       logger(LOG_ERROR) << "DepthCamera:Could not get value for parameter " << _id << "." << name << std::endl;
       return false;
     }
     return true;
   }
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Unknown parameter " << _id << "." << name << std::endl;
     return false;
   }
 }
virtual bool Voxel::DepthCamera::_getBytesPerPixel (uint & bpp) const protected pure virtual
Implemented in Voxel::TI::ToFCamera, and Voxel::TI::ToFCalculusCamera.
Referenced by getBytesPerPixel().
virtual bool Voxel::DepthCamera::_getCurrentProfileID (int & id) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by _init().
virtual bool Voxel::DepthCamera::_getFieldOfView (float & fovHalfAngle) const protected pure virtual
Implemented in Voxel::TI::TintinCDKCamera, Voxel::TI::VoxelDCamera, Voxel::TI::HaddockCDKCamera, Voxel::TI::CalculusCDKCamera, and Voxel::TI::Voxel14Camera.
Referenced by getFieldOfView().
virtual bool Voxel::DepthCamera::_getFrameRate (FrameRate & r) const protected pure virtual
Implemented in Voxel::TI::ToFCamera, and Voxel::TI::ToFCalculusCamera.
Referenced by getFrameRate().
virtual bool Voxel::DepthCamera::_getFrameSize (FrameSize & s) const protected pure virtual
Implemented in Voxel::TI::ToFCamera, and Voxel::TI::ToFCalculusCamera.
Referenced by getFrameSize().
virtual bool Voxel::DepthCamera::_getMaximumFrameRate (FrameRate & frameRate, const FrameSize & forFrameSize) const protected pure virtual
Implemented in Voxel::TI::ToFCamera, Voxel::TI::TintinCDKCamera, Voxel::TI::HaddockCDKCamera, and Voxel::TI::CalculusCDKCamera.
Referenced by getMaximumFrameRate().
virtual bool Voxel::DepthCamera::_getMaximumFrameSize (FrameSize & s) const protected pure virtual
Implemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by Voxel::TI::ToFCamera::_setFrameSize(), and getMaximumFrameSize().
virtual bool Voxel::DepthCamera::_getMaximumVideoMode (VideoMode & videoMode) const protected pure virtual
Implemented in Voxel::TI::TintinCDKCamera, Voxel::TI::VoxelDCamera, Voxel::TI::HaddockCDKCamera, Voxel::TI::CalculusCDKCamera, and Voxel::TI::Voxel14Camera.
Referenced by getMaximumVideoMode().
virtual bool Voxel::DepthCamera::_getROI (RegionOfInterest & roi) protected pure virtual
Implemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by Voxel::TI::ToFCamera::_setFrameSize(), and getROI().
virtual bool Voxel::DepthCamera::_getSupportedVideoModes (Vector< SupportedVideoMode > & supportedVideoModes) const protected pure virtual
Implemented in Voxel::TI::TintinCDKCamera, Voxel::TI::VoxelDCamera, Voxel::TI::HaddockCDKCamera, Voxel::TI::CalculusCDKCamera, and Voxel::TI::Voxel14Camera.
Referenced by Voxel::TI::ToFCamera::_getMaximumFrameRate(), Voxel::TI::ToFCamera::_setFrameSize(), and getSupportedVideoModes().
bool Voxel::DepthCamera::_init () protected
Definition at line 33 of file DepthCamera.cpp.
References _getCurrentProfileID(), configFile, Voxel::MainConfigurationFile::getDefaultCameraProfileID(), getSerialNumber(), Voxel::MainConfigurationFile::readFromHardware(), setCameraProfile(), and Voxel::MainConfigurationFile::setHardwareID().
Referenced by Voxel::TI::ToFCameraBase::_init().
 {
   String serialNumber;
   if(getSerialNumber(serialNumber))
   {
     configFile.setHardwareID(serialNumber);
     configFile.readFromHardware();
   }
   int currentID = -1;
   if(_getCurrentProfileID(currentID) && currentID >= 0)
   {
     if(!setCameraProfile(currentID, true))
       return setCameraProfile(configFile.getDefaultCameraProfileID());
     else
       return true;
   }
   else
     return setCameraProfile(configFile.getDefaultCameraProfileID());
 }
void Voxel::DepthCamera::_makeID () inline protected
Definition at line 139 of file DepthCamera.h.
Referenced by Voxel::TI::Voxel14Camera::_init(), Voxel::TI::VoxelDCamera::_init(), and DepthCamera().
 { _id = _name + "(" + _device->id() + ")"; }
virtual bool Voxel::DepthCamera::_onReset () protected pure virtual
Implemented in Voxel::TI::ToFCameraBase.
Referenced by setCameraProfile().
virtual bool Voxel::DepthCamera::_processRawFrame (const RawFramePtr & rawFrameInput, RawFramePtr & rawFrameOutput) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by _captureLoop().
virtual bool Voxel::DepthCamera::_reset () protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by reset().
virtual bool Voxel::DepthCamera::_saveCurrentProfileID (const int id) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by setCameraProfile().
template<typename T > bool Voxel::DepthCamera::_set (const String & name, const T & value) protected
Definition at line 383 of file DepthCamera.h.
References _device, _id, _parameters, Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, name(), and Voxel::ParameterTemplate< T >::set().
Referenced by Voxel::TI::ToFCamera::_saveCurrentProfileID(), Voxel::TI::ToFCamera::_setBinning(), Voxel::TI::ToFCamera::_setBytesPerPixel(), Voxel::TI::ToFCamera::_setFrameRate(), Voxel::TI::ToFHaddockCamera::_setROI(), Voxel::TI::ToFCalculusCamera::_setROI(), Voxel::TI::ToFTintinCamera::_setROI(), Voxel::TI::ToFCalculusCamera::_updateEasyConf(), Voxel::TI::HaddockVCOFrequency::set(), Voxel::TI::IntegrationTimeParameter::set(), Voxel::TI::TintinVCOFrequency::set(), Voxel::TI::HaddockCDKIlluminationPowerPercentageParameter::set(), Voxel::TI::HaddockModulationFrequencyParameter::set(), Voxel::TI::CalculusVCOFrequency::set(), Voxel::TI::TintinModulationFrequencyParameter::set(), set(), Voxel::TI::HaddockUnambiguousRangeParameter::set(), Voxel::TI::CalculusModulationFrequencyParameter::set(), Voxel::TI::TintinUnambiguousRangeParameter::set(), and Voxel::TI::HaddockSensorTemperatureParameter::set().
 {
   auto p = _parameters.find(name);
   if(p != _parameters.end())
   {
     logger(LOG_DEBUG) << "DepthCamera: Setting parameter '" << name << "' = " << value << std::endl;
     ParameterTemplate<T> *param = dynamic_cast<ParameterTemplate<T> *>(p->second.get());
     if(param == 0)
     {
       logger(LOG_ERROR) << "DepthCamera: Invalid value type '" << typeid(value).name() << "' used to set parameter " << this->name() << "(" << _device->id() << ")." << name << std::endl;
       return false;
     }
     if(!param->set(value))
     {
       logger(LOG_ERROR) << "DepthCamera: Could not set value " << value << " for parameter " << this->name() << "(" << _device->id() << ")." << name << std::endl;
       return false;
     }
     return true;
   }
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Unknown parameter " << _id << "." << name << std::endl;
     return false;
   }
 }
virtual bool Voxel::DepthCamera::_setBytesPerPixel (const uint & bpp) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by setBytesPerPixel().
virtual bool Voxel::DepthCamera::_setFrameRate (const FrameRate & r) protected pure virtual
Implemented in Voxel::TI::ToFCamera, and Voxel::TI::ToFCalculusCamera.
Referenced by setFrameRate().
virtual bool Voxel::DepthCamera::_setFrameSize (const FrameSize & s) protected pure virtual
Implemented in Voxel::TI::ToFCamera.
Referenced by setFrameSize().
virtual bool Voxel::DepthCamera::_setROI (const RegionOfInterest & roi) protected pure virtual
Implemented in Voxel::TI::ToFTintinCamera, Voxel::TI::ToFCalculusCamera, and Voxel::TI::ToFHaddockCamera.
Referenced by Voxel::TI::ToFCamera::_setFrameSize(), and setROI().
virtual bool Voxel::DepthCamera::_start () protected pure virtual
Implemented in Voxel::TI::ToFCameraBase.
Referenced by start().
virtual bool Voxel::DepthCamera::_stop () protected pure virtual
Implemented in Voxel::TI::ToFCameraBase.
Referenced by _captureLoop().
bool Voxel::DepthCamera::_writeToFrameStream (RawFramePtr & rawUnprocessed) protected
Definition at line 470 of file DepthCamera.cpp.
References _frameStreamWriter, _frameStreamWriterMutex, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by _captureLoop().
 {
   Lock<Mutex> _(_frameStreamWriterMutex);
   if(_frameStreamWriter && !_frameStreamWriter->write(std::dynamic_pointer_cast<Frame>(rawUnprocessed)))
   {
     logger(LOG_ERROR) << "DepthCamera: Failed to save frames to frame stream" << std::endl;
     return false;
   }
   return true;
 }
int Voxel::DepthCamera::addCameraProfile (const String & profileName, const int parentID)
Definition at line 602 of file DepthCamera.cpp.
References Voxel::MainConfigurationFile::addCameraProfile(), and configFile.
 {
   return configFile.addCameraProfile(profileName, parentID);
 }
int Voxel::DepthCamera::addFilter (FilterPtr p, DepthCamera::FrameType frameType, int beforeFilterID = -1) virtual
Definition at line 386 of file DepthCamera.cpp.
References _depthFilters, _processedFilters, _unprocessedFilters, FRAME_DEPTH_FRAME, FRAME_RAW_FRAME_PROCESSED, FRAME_RAW_FRAME_UNPROCESSED, id(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(frameType == FRAME_RAW_FRAME_UNPROCESSED)
     return _unprocessedFilters.addFilter(p, beforeFilterID);
   else if(frameType == FRAME_RAW_FRAME_PROCESSED)
     return _processedFilters.addFilter(p, beforeFilterID);
   else if(frameType == FRAME_DEPTH_FRAME)
     return _depthFilters.addFilter(p, beforeFilterID);
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Filter not supported for frame type = '" << frameType << "' for camera = " << id() << std::endl;
     return -1;
   }
 }
bool Voxel::DepthCamera::allowedROI (String & message) inline
Definition at line 334 of file DepthCamera.h.
References _accessMutex, and _allowedROI().
 {
   Lock<Mutex> _(_accessMutex);
   return _allowedROI(message);
 }
bool Voxel::DepthCamera::clearAllCallbacks () virtual
Definition at line 74 of file DepthCamera.cpp.
References _callback, and FRAME_TYPE_COUNT.
 {
   for(auto i = 0; i < FRAME_TYPE_COUNT; i++)
     _callback[i] = nullptr;
   return true;
 }
bool Voxel::DepthCamera::clearCallback (FrameType type) virtual
Definition at line 81 of file DepthCamera.cpp.
References _callback, and FRAME_TYPE_COUNT.
 {
   if(type < FRAME_TYPE_COUNT)
   {
     _callback[type] = nullptr;
     return true;
   }
   return false;
 }
bool Voxel::DepthCamera::close ()
Definition at line 345 of file DepthCamera.cpp.
References _depthFrameBuffers, _parameters, _pointCloudBuffers, _programmer, _rawFrameBuffers, _streamer, isRunning(), and stop().
Referenced by ~DepthCamera().
 {
   if(isRunning())
     stop();
   _programmer.reset();
   _streamer.reset();
   _rawFrameBuffers.clear();
   _depthFrameBuffers.clear();
   _pointCloudBuffers.clear();
   _parameters.clear();
   return true;
 }
bool Voxel::DepthCamera::closeFrameStream () virtual
Definition at line 520 of file DepthCamera.cpp.
References _frameGenerators, _frameStreamWriter, _frameStreamWriterMutex, Voxel::LOG_DEBUG, and Voxel::logger.
Referenced by _captureLoop().
 {
   Lock<Mutex> _(_frameStreamWriterMutex);
   if(_frameStreamWriter)
   {
     _frameGenerators[0]->removeFrameStreamWriter();
     _frameGenerators[1]->removeFrameStreamWriter();
     _frameGenerators[2]->removeFrameStreamWriter();
     _frameStreamWriter->close();
     _frameStreamWriter.reset();
     return true;
   }
   else
   {
     logger(LOG_DEBUG) << "DepthCamera: Frame stream writer not present." << std::endl;
     return false;
   }
 }
template<typename T > bool Voxel::DepthCamera::get (const String & name, T & value, bool refresh = false) const
Definition at line 253 of file DepthCamera.h.
References _accessMutex, and _get().
 {
   Lock<Mutex> _(_accessMutex);
   return _get(name, value, refresh);
 }
bool Voxel::DepthCamera::getBytesPerPixel (uint & bpp) const inline
Definition at line 321 of file DepthCamera.h.
References _accessMutex, and _getBytesPerPixel().
 {
   Lock<Mutex> _(_accessMutex);
   return _getBytesPerPixel(bpp);
 }
const Map<int, String>& Voxel::DepthCamera::getCameraProfileNames () inline
Definition at line 240 of file DepthCamera.h.
 { return configFile.getCameraProfileNames(); }
int Voxel::DepthCamera::getCurrentCameraProfileID () inline
Definition at line 241 of file DepthCamera.h.
 { return configFile.getCurrentProfileID(); }
const FilterSet<DepthFrame>& Voxel::DepthCamera::getDepthFilterSet () inline
Definition at line 227 of file DepthCamera.h.
 { return _depthFilters; }
const DevicePtr& Voxel::DepthCamera::getDevice () const inline
Definition at line 169 of file DepthCamera.h.
 { return _device; }
bool Voxel::DepthCamera::getFieldOfView (float & fovHalfAngle) const inline
Definition at line 266 of file DepthCamera.h.
References _accessMutex, and _getFieldOfView().
 {
   Lock<Mutex> _(_accessMutex);
   return _getFieldOfView(fovHalfAngle);
 }
FilterPtr Voxel::DepthCamera::getFilter (int filterID, DepthCamera::FrameType frameType) const virtual
Definition at line 416 of file DepthCamera.cpp.
References _depthFilters, _processedFilters, _unprocessedFilters, FRAME_DEPTH_FRAME, FRAME_RAW_FRAME_PROCESSED, FRAME_RAW_FRAME_UNPROCESSED, id(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(frameType == FRAME_RAW_FRAME_UNPROCESSED)
     return _unprocessedFilters.getFilter(filterID);
   else if(frameType == FRAME_RAW_FRAME_PROCESSED)
     return _processedFilters.getFilter(filterID);
   else if(frameType == FRAME_DEPTH_FRAME)
     return _depthFilters.getFilter(filterID);
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Filter not supported for frame type = '" << frameType << "' for camera = " << id() << std::endl;
     return nullptr;
   }
 }
bool Voxel::DepthCamera::getFrameRate (FrameRate & r) const inline
Definition at line 272 of file DepthCamera.h.
References _accessMutex, and _getFrameRate().
Referenced by Voxel::TI::ToFCameraBase::_onReset(), and Voxel::TI::ToFCameraBase::_start().
 {
   Lock<Mutex> _(_accessMutex);
   return _getFrameRate(r);
 }
bool Voxel::DepthCamera::getFrameSize (FrameSize & s) const inline
Definition at line 284 of file DepthCamera.h.
References _accessMutex, and _getFrameSize().
Referenced by Voxel::TI::CalculusCDKCamera::_init(), Voxel::TI::HaddockCDKCamera::_init(), Voxel::TI::ToFCalculusCamera::_initStartParams(), Voxel::TI::ToFCamera::_initStartParams(), Voxel::TI::ToFCameraBase::_onReset(), and Voxel::TI::ToFCameraBase::_start().
 {
   Lock<Mutex> _(_accessMutex);
   return _getFrameSize(s);
 }
bool Voxel::DepthCamera::getMaximumFrameRate (FrameRate & frameRate, const FrameSize & forFrameSize) const inline
Definition at line 302 of file DepthCamera.h.
References _accessMutex, and _getMaximumFrameRate().
 {
   Lock<Mutex> _(_accessMutex);
   return _getMaximumFrameRate(frameRate, forFrameSize);
 }
bool Voxel::DepthCamera::getMaximumFrameSize (FrameSize & s) const inline
Definition at line 296 of file DepthCamera.h.
References _accessMutex, and _getMaximumFrameSize().
Referenced by Voxel::TI::ToFCamera::_initStartParams().
 {
   Lock<Mutex> _(_accessMutex);
   return _getMaximumFrameSize(s);
 }
bool Voxel::DepthCamera::getMaximumVideoMode (VideoMode & videoMode) const inline
Definition at line 315 of file DepthCamera.h.
References _accessMutex, and _getMaximumVideoMode().
Referenced by Voxel::TI::ToFCameraBase::_onReset().
 {
   Lock<Mutex> _(_accessMutex);
   return _getMaximumVideoMode(videoMode);
 }
const ParameterPtr Voxel::DepthCamera::getParam (const String & name) const inline
Definition at line 413 of file DepthCamera.h.
References _id, _parameters, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by _applyConfigParams(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::TintinCDKIlluminationPowerPercentParameter::get(), Voxel::TI::HaddockModulationFrequencyParameter::set(), Voxel::TI::TintinModulationFrequencyParameter::set(), Voxel::TI::TintinCDKIlluminationPowerPercentParameter::set(), Voxel::TI::HaddockUnambiguousRangeParameter::set(), Voxel::TI::CalculusModulationFrequencyParameter::set(), and Voxel::TI::TintinUnambiguousRangeParameter::set().
 {
   auto p = _parameters.find(name);
   if(p != _parameters.end())
     return p->second;
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Unknown parameter " << _id << "." << name << std::endl;
     return 0;
   }
 }
const Map<String, ParameterPtr>& Voxel::DepthCamera::getParameters () const inline
Definition at line 186 of file DepthCamera.h.
 { return _parameters; }
const FilterSet<RawFrame>& Voxel::DepthCamera::getProcessedRawFilterSet () inline
Definition at line 226 of file DepthCamera.h.
 { return _processedFilters; }
Ptr<RegisterProgrammer> Voxel::DepthCamera::getProgrammer () inline
Definition at line 236 of file DepthCamera.h.
 { return _programmer; } // RegisterProgrammer is usually thread-safe to use outside directly
bool Voxel::DepthCamera::getROI (RegionOfInterest & roi) inline
Definition at line 340 of file DepthCamera.h.
References _accessMutex, and _getROI().
Referenced by Voxel::TI::ToFCalculusCamera::_initStartParams(), and Voxel::TI::ToFCamera::_initStartParams().
 {
   Lock<Mutex> _(_accessMutex);
   return _getROI(roi);
 }
bool Voxel::DepthCamera::getSerialNumber (String & serialNumber) const virtual
Definition at line 697 of file DepthCamera.cpp.
References _device.
Referenced by _init().
 {
   serialNumber = _device->serialNumber();
   return true;
 }
Ptr<Streamer> Voxel::DepthCamera::getStreamer () inline
Definition at line 237 of file DepthCamera.h.
 { return _streamer; } // Streamer may not be thread-safe
template<typename T > bool Voxel::DepthCamera::getStreamParam (const String & name, T & value) const
Definition at line 427 of file DepthCamera.h.
 {
   if(!_frameGenerators[0]->get(name, value) && !_frameGenerators[1]->get(name, value) && !_frameGenerators[2]->get(name, value))
     return false;
   return true;
 }
bool Voxel::DepthCamera::getSupportedVideoModes (Vector< SupportedVideoMode > & supportedVideoModes) const inline
Definition at line 309 of file DepthCamera.h.
References _accessMutex, and _getSupportedVideoModes().
 {
   Lock<Mutex> _(_accessMutex);
   return _getSupportedVideoModes(supportedVideoModes);
 }
const FilterSet<RawFrame>& Voxel::DepthCamera::getUnprocessedRawFilterSet () inline
Definition at line 225 of file DepthCamera.h.
 { return _unprocessedFilters; }
const String& Voxel::DepthCamera::id () const inline
Definition at line 164 of file DepthCamera.h.
Referenced by _captureLoop(), Voxel::TI::ToFCamera::_saveCurrentProfileID(), addFilter(), getFilter(), registerCallback(), removeAllFilters(), removeFilter(), and reset().
 { return _id; }
virtual bool Voxel::DepthCamera::isInitialized () const inline virtual
Definition at line 156 of file DepthCamera.h.
Referenced by Voxel::TI::ToFCameraBase::_captureRawUnprocessedFrame(), Voxel::TI::ToFCameraBase::_start(), and Voxel::TI::ToFCameraBase::_stop().
   {
     return _programmer && _programmer->isInitialized() &&
            _streamer && _streamer->isInitialized() && _parameterInit;
   }
bool Voxel::DepthCamera::isRunning () const inline
Definition at line 171 of file DepthCamera.h.
Referenced by Voxel::TI::ToFCamera::_setFrameSize(), Voxel::TI::ToFHaddockCamera::_setROI(), Voxel::TI::ToFCalculusCamera::_setROI(), Voxel::TI::ToFTintinCamera::_setROI(), close(), reset(), start(), and stop().
 { return _running; }
bool Voxel::DepthCamera::isSavingFrameStream () virtual
Definition at line 513 of file DepthCamera.cpp.
References _frameStreamWriter, and _frameStreamWriterMutex.
Referenced by _captureLoop().
 {
   Lock<Mutex> _(_frameStreamWriterMutex);
   return _frameStreamWriter?true:false;
 }
const String& Voxel::DepthCamera::name () const inline
Definition at line 162 of file DepthCamera.h.
Referenced by _get(), Voxel::TI::ToFCamera::_getCurrentProfileID(), Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), Voxel::TI::ToFTintinCamera::_init(), Voxel::TI::ToFCamera::_saveCurrentProfileID(), and _set().
 { return _name; }
bool Voxel::DepthCamera::refreshParams ()
Definition at line 447 of file DepthCamera.cpp.
References _accessMutex, _parameters, Voxel::LOG_ERROR, and Voxel::logger.
Referenced by setCameraProfile().
 {
   Lock<Mutex> _(_accessMutex);
   bool ret = true;
   for(auto &i: _parameters)
   {
     if(!i.second->refresh())
     {
       logger(LOG_ERROR) << "DepthCamera: Failed to update value for parameter '" << i.first << "'" << std::endl;
       ret = false;
     }
   }
   return ret;
 }
bool Voxel::DepthCamera::registerCallback (FrameType type, CallbackType f) virtual
Definition at line 91 of file DepthCamera.cpp.
References _callback, _callBackTypesRegistered, FRAME_TYPE_COUNT, id(), Voxel::LOG_ERROR, Voxel::LOG_WARNING, and Voxel::logger.
Referenced by Voxel::PCLGrabber::PCLGrabber().
 {
   if(type < FRAME_TYPE_COUNT)
   {
     if(_callback[type])
       logger(LOG_WARNING) << "DepthCamera: " << id() << " already has a callback for this type = " << type << ". Overwriting it now." << std::endl;
     _callBackTypesRegistered |= (1 << type);
     _callback[type] = f;
     return true;
   }
   logger(LOG_ERROR) << "DepthCamera: Invalid callback type = " << type << " attempted for depth camera " << id() << std::endl;
   return false;
 }
bool Voxel::DepthCamera::reloadConfiguration () inline
Definition at line 239 of file DepthCamera.h.
 { return configFile.read(_name + ".conf"); }
bool Voxel::DepthCamera::removeAllFilters (FrameType frameType) virtual
Definition at line 401 of file DepthCamera.cpp.
References _depthFilters, _processedFilters, _unprocessedFilters, FRAME_DEPTH_FRAME, FRAME_RAW_FRAME_PROCESSED, FRAME_RAW_FRAME_UNPROCESSED, id(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(frameType == FRAME_RAW_FRAME_UNPROCESSED)
     return _unprocessedFilters.removeAllFilters();
   else if(frameType == FRAME_RAW_FRAME_PROCESSED)
     return _processedFilters.removeAllFilters();
   else if(frameType == FRAME_DEPTH_FRAME)
     return _depthFilters.removeAllFilters();
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Filter not supported for frame type = '" << frameType << "' for camera = " << id() << std::endl;
     return false;
   }
 }
bool Voxel::DepthCamera::removeCameraProfile (const int id)
Definition at line 608 of file DepthCamera.cpp.
References configFile, and Voxel::MainConfigurationFile::removeCameraProfile().
 {
   return configFile.removeCameraProfile(id);
 }
bool Voxel::DepthCamera::removeFilter (int filterID, FrameType frameType) virtual
Definition at line 432 of file DepthCamera.cpp.
References _depthFilters, _processedFilters, _unprocessedFilters, FRAME_DEPTH_FRAME, FRAME_RAW_FRAME_PROCESSED, FRAME_RAW_FRAME_UNPROCESSED, id(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(frameType == FRAME_RAW_FRAME_UNPROCESSED)
     return _unprocessedFilters.removeFilter(filterID);
   else if(frameType == FRAME_RAW_FRAME_PROCESSED)
     return _processedFilters.removeFilter(filterID);
   else if(frameType == FRAME_DEPTH_FRAME)
     return _depthFilters.removeFilter(filterID);
   else
   {
     logger(LOG_ERROR) << "DepthCamera: Filter not supported for frame type = '" << frameType << "' for camera = " << id() << std::endl;
     return false;
   }
 }
bool Voxel::DepthCamera::reset ()
Definition at line 368 of file DepthCamera.cpp.
References _reset(), id(), isRunning(), Voxel::LOG_ERROR, Voxel::logger, and resetFilters().
 {
   if(isRunning())
   {
     logger(LOG_ERROR) << "DepthCamera: Please stop the depth camera before calling reset" << std::endl;
     return false;
   }
   if(!_reset())
   {
     logger(LOG_ERROR) << "DepthCamera: Failed to reset device " << id() << std::endl;
     return false;
   }
   resetFilters();
   return true;
 }
void Voxel::DepthCamera::resetFilters () virtual
Definition at line 463 of file DepthCamera.cpp.
References _depthFilters, _processedFilters, and _unprocessedFilters.
Referenced by reset(), and start().
 {
   _unprocessedFilters.reset();
   _processedFilters.reset();
   _depthFilters.reset();
 }
bool Voxel::DepthCamera::saveCameraProfileToHardware (int & id) inline
Definition at line 246 of file DepthCamera.h.
 { return configFile.saveCameraProfileToHardware(id); }
bool Voxel::DepthCamera::saveFrameStream (const String & fileName) virtual
Definition at line 481 of file DepthCamera.cpp.
References _frameGenerators, _frameStreamWriter, _frameStreamWriterMutex, Voxel::LOG_ERROR, and Voxel::logger.
 {
   Lock<Mutex> _(_frameStreamWriterMutex);
   if(_frameStreamWriter)
   {
     logger(LOG_ERROR) << "DepthCamera: Frame stream is already being saved." << std::endl;
     return false;
   }
   if(!_frameGenerators[0] || !_frameGenerators[1] || !_frameGenerators[2])
   {
     logger(LOG_ERROR) << "DepthCamera: Necessary generators are not yet created? Can't save stream." << std::endl;
     return false;
   }
   FrameStreamWriterPtr w = FrameStreamWriterPtr(
     new FrameStreamWriter(fileName, _frameGenerators[0]->id(), _frameGenerators[1]->id(), _frameGenerators[2]->id())
   );
   _frameGenerators[0]->setFrameStreamWriter(w);
   _frameGenerators[1]->setFrameStreamWriter(w);
   _frameGenerators[2]->setFrameStreamWriter(w);
   _frameGenerators[0]->writeConfiguration();
   _frameGenerators[1]->writeConfiguration();
   _frameGenerators[2]->writeConfiguration();
   _frameStreamWriter = w;
   return _frameStreamWriter->isStreamGood();
 }
template<typename T > bool Voxel::DepthCamera::set (const String & name, const T & value)
Definition at line 260 of file DepthCamera.h.
References _accessMutex, and _set().
Referenced by Voxel::TI::ToFHaddockCamera::_applyCalibrationParams(), Voxel::TI::ToFTintinCamera::_applyCalibrationParams(), _applyConfigParams(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::ToFHaddockCamera::_initStartParams(), Voxel::TI::HaddockCDKCamera::_initStartParams(), Voxel::TI::VoxelDCamera::_initStartParams(), Voxel::TI::TintinCDKCamera::_initStartParams(), Voxel::TI::ToFCalculusCamera::_initStartParams(), Voxel::TI::ToFTintinCamera::_initStartParams(), and Voxel::TI::ToFCamera::_reset().
 {
   Lock<Mutex> _(_accessMutex);
   return _set(name, value);
 }
bool Voxel::DepthCamera::setBytesPerPixel (const uint & bpp) inline
Definition at line 327 of file DepthCamera.h.
References _accessMutex, and _setBytesPerPixel().
 {
   Lock<Mutex> _(_accessMutex);
   return _setBytesPerPixel(bpp);
 }
bool Voxel::DepthCamera::setCameraProfile (const int id, bool softApply = false)
Definition at line 540 of file DepthCamera.cpp.
References _applyConfigParams(), _onReset(), _saveCurrentProfileID(), configFile, Voxel::MainConfigurationFile::getCameraProfile(), Voxel::MainConfigurationFile::getCameraProfileName(), Voxel::ConfigurationFile::getConfigSet(), Voxel::LOG_ERROR, Voxel::LOG_WARNING, Voxel::logger, refreshParams(), and Voxel::MainConfigurationFile::setCurrentCameraProfile().
Referenced by _init().
 {
   if(!configFile.setCurrentCameraProfile(id))
   {
     logger(LOG_ERROR) << "DepthCamera: Could not set the camera profile to '" << id << "'" << std::endl;
     return false;
   }
   if(!_saveCurrentProfileID(id))
     logger(LOG_WARNING) << "DepthCamera: Could not save the camera profile ID '" << id << "'" << std::endl;
   /*
   // Uncomment this perform soft-reset every time a profile is selected.
   if(!reset())
   {
     logger(LOG_ERROR) << "DepthCamera: Failed to reset camera, to set new camera profile" << std::endl;
     return false;
   }
   */
   if(!refreshParams())
     return false;
   if(!softApply)
   {
     ConfigurationFile *config;
     String cameraProfileName;
     if(!configFile.getCameraProfileName(id, cameraProfileName))
     {
       logger(LOG_ERROR) << "DepthCamera: Failed to get new camera profile name" << std::endl;
       return false;
     }
     if(!(config = configFile.getCameraProfile(id)))
     {
       logger(LOG_ERROR) << "DepthCamera: Failed to get new camera profile information" << std::endl;
       return false;
     }
     const ConfigSet *params;
     if(config->getConfigSet("params", params) && !_applyConfigParams(params))
     {
       logger(LOG_ERROR) << "DepthCamera: Could not set parameters to initialize profile '" << cameraProfileName << "'" << std::endl;
       return false;
     }
     if(config->getConfigSet("defining_params", params) && !_applyConfigParams(params))
     {
       logger(LOG_ERROR) << "DepthCamera: Could not set parameters to initialize profile '" << cameraProfileName << "'" << std::endl;
       return false;
     }
   }
   if(!_onReset())
     return false;
   return true;
 }
bool Voxel::DepthCamera::setFrameRate (const FrameRate & r) inline
Definition at line 278 of file DepthCamera.h.
References _accessMutex, and _setFrameRate().
Referenced by _applyConfigParams(), and Voxel::TI::ToFCameraBase::_onReset().
 {
   Lock<Mutex> _(_accessMutex);
   return _setFrameRate(r);
 }
bool Voxel::DepthCamera::setFrameSize (const FrameSize & s) inline
Definition at line 290 of file DepthCamera.h.
References _accessMutex, and _setFrameSize().
Referenced by Voxel::TI::ToFCameraBase::_onReset().
 {
   Lock<Mutex> _(_accessMutex);
   return _setFrameSize(s);
 }
bool Voxel::DepthCamera::setROI (const RegionOfInterest & roi) inline
Definition at line 346 of file DepthCamera.h.
References _accessMutex, and _setROI().
 {
   Lock<Mutex> _(_accessMutex);
   return _setROI(roi);
 }
bool Voxel::DepthCamera::setSerialNumber (const String & serialNumber) virtual
Reimplemented in Voxel::TI::ToFCamera.
Definition at line 703 of file DepthCamera.cpp.
Referenced by Voxel::TI::ToFCamera::setSerialNumber().
 {
   return false;
 }
bool Voxel::DepthCamera::start ()
Definition at line 292 of file DepthCamera.cpp.
References _callBackTypesRegistered, _captureThread, _captureThreadWrapper(), _id, _running, _start(), isRunning(), Voxel::LOG_ERROR, Voxel::logger, resetFilters(), and wait().
 {
   if (isRunning())
   {
     logger(LOG_ERROR) << "DepthCamera: Camera is already running. Please stop it before calling start() again." << std::endl;
     return false;
   }
   wait();
   if (_captureThread &&  _captureThread->joinable())
   {
     logger(LOG_ERROR) << "DepthCamera: Camera is still running. Please wait for the current capture loop to complete before calling start() again." << std::endl;
     return false;
   }
   if(!_callBackTypesRegistered)
   {
     logger(LOG_ERROR) << "DepthCamera: Please register a callback to " << _id << " before starting capture" << std::endl;
     return false;
   }
   resetFilters();
   if(!_start())
     return false;
   _running = true;
   //_captureThreadWrapper();
   _captureThread = ThreadPtr(new Thread(&DepthCamera::_captureThreadWrapper, this));
   return true;
 }
bool Voxel::DepthCamera::stop ()
Definition at line 326 of file DepthCamera.cpp.
References _running, isRunning(), Voxel::LOG_WARNING, Voxel::logger, and wait().
Referenced by close(), and main().
 {
   if (!isRunning())
   {
     logger(LOG_WARNING) << "DepthCamera: Camera is not running." << std::endl;
     return true;
   }
   _running = false;
   wait();
   return true;
 }
void Voxel::DepthCamera::wait ()
Definition at line 339 of file DepthCamera.cpp.
References _captureThread.
Referenced by start(), and stop().
 {
   if(_captureThread &&  _captureThread->get_id() != std::this_thread::get_id() && _captureThread->joinable())
     _captureThread->join();
 }
Member Data Documentation
Mutex Voxel::DepthCamera::_accessMutex mutable private
Definition at line 54 of file DepthCamera.h.
Referenced by allowedROI(), get(), getBytesPerPixel(), getFieldOfView(), getFrameRate(), getFrameSize(), getMaximumFrameRate(), getMaximumFrameSize(), getMaximumVideoMode(), getROI(), getSupportedVideoModes(), refreshParams(), set(), setBytesPerPixel(), setFrameRate(), setFrameSize(), and setROI().
CallbackType Voxel::DepthCamera::_callback[FRAME_TYPE_COUNT] protected
Definition at line 86 of file DepthCamera.h.
Referenced by _callbackAndContinue(), _captureLoop(), clearAllCallbacks(), clearCallback(), and registerCallback().
uint32_t Voxel::DepthCamera::_callBackTypesRegistered = 0 protected
Definition at line 88 of file DepthCamera.h.
Referenced by _captureLoop(), registerCallback(), and start().
ThreadPtr Voxel::DepthCamera::_captureThread protected
Definition at line 90 of file DepthCamera.h.
Referenced by start(), and wait().
FilterSet<DepthFrame> Voxel::DepthCamera::_depthFilters protected
Definition at line 80 of file DepthCamera.h.
Referenced by _captureLoop(), addFilter(), getFilter(), removeAllFilters(), removeFilter(), and resetFilters().
FrameBufferManager<DepthFrame> Voxel::DepthCamera::_depthFrameBuffers protected
Definition at line 75 of file DepthCamera.h.
Referenced by _captureLoop(), and close().
DevicePtr Voxel::DepthCamera::_device protected
Definition at line 58 of file DepthCamera.h.
Referenced by Voxel::TI::TintinCDKCamera::_getMaximumVideoMode(), Voxel::TI::TintinCDKCamera::_getSupportedVideoModes(), Voxel::TI::CalculusCDKCamera::_init(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::HaddockCDKCamera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::TintinCDKCamera::_initStartParams(), _set(), Voxel::TI::TintinCDKCamera::_setStreamerFrameSize(), getSerialNumber(), and Voxel::TI::ToFCamera::setSerialNumber().
FrameGeneratorPtr Voxel::DepthCamera::_frameGenerators[3] protected
Definition at line 68 of file DepthCamera.h.
Referenced by closeFrameStream(), DepthCamera(), saveFrameStream(), and Voxel::TI::ToFCamera::ToFCamera().
FrameStreamWriterPtr Voxel::DepthCamera::_frameStreamWriter protected
Definition at line 82 of file DepthCamera.h.
Referenced by _writeToFrameStream(), closeFrameStream(), isSavingFrameStream(), and saveFrameStream().
Mutex Voxel::DepthCamera::_frameStreamWriterMutex mutable private
Definition at line 55 of file DepthCamera.h.
Referenced by _writeToFrameStream(), closeFrameStream(), isSavingFrameStream(), and saveFrameStream().
String Voxel::DepthCamera::_id protected
Definition at line 60 of file DepthCamera.h.
Referenced by _get(), _set(), getParam(), and start().
String Voxel::DepthCamera::_name protected
Definition at line 60 of file DepthCamera.h.
bool Voxel::DepthCamera::_parameterInit protected
Definition at line 72 of file DepthCamera.h.
Referenced by Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), and Voxel::TI::ToFTintinCamera::_init().
Map<String, ParameterPtr> Voxel::DepthCamera::_parameters protected
Definition at line 62 of file DepthCamera.h.
Referenced by _addParameters(), _get(), Voxel::TI::TintinCDKCamera::_init(), _set(), close(), getParam(), and refreshParams().
FrameBufferManager<PointCloudFrame> Voxel::DepthCamera::_pointCloudBuffers protected
Definition at line 76 of file DepthCamera.h.
Referenced by _captureLoop(), and close().
Ptr<PointCloudFrameGenerator> Voxel::DepthCamera::_pointCloudFrameGenerator protected
Definition at line 70 of file DepthCamera.h.
Referenced by _convertToPointCloudFrame(), Voxel::TI::ToFCamera::_initStartParams(), and DepthCamera().
FilterSet<RawFrame> Voxel::DepthCamera::_processedFilters protected
Definition at line 78 of file DepthCamera.h.
Referenced by _captureLoop(), addFilter(), getFilter(), removeAllFilters(), removeFilter(), and resetFilters().
Ptr<RegisterProgrammer> Voxel::DepthCamera::_programmer protected
Definition at line 64 of file DepthCamera.h.
Referenced by _applyConfigParams(), Voxel::TI::TintinCDKCamera::_getEEPROMSize(), Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::CalculusCDKCamera::_init(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::HaddockCDKCamera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), Voxel::TI::ToFTintinCamera::_init(), Voxel::TI::ToFCamera::_init(), Voxel::TI::CalculusCDKCamera::_initStartParams(), Voxel::TI::ToFCalculusCamera::_initStartParams(), Voxel::TI::TintinCDKCamera::_readConfigFromHardware(), Voxel::TI::VoxelDCamera::_setIllumPolarity(), Voxel::TI::ToFCalculusCamera::_updateEasyConf(), Voxel::TI::TintinCDKCamera::_writeConfigFromHardware(), close(), and Voxel::TI::ToFCamera::setSerialNumber().
FrameBufferManager<RawFrame> Voxel::DepthCamera::_rawFrameBuffers protected
Definition at line 74 of file DepthCamera.h.
Referenced by _captureLoop(), and close().
bool Voxel::DepthCamera::_running protected
Definition at line 107 of file DepthCamera.h.
Referenced by _captureLoop(), start(), and stop().
Ptr<Streamer> Voxel::DepthCamera::_streamer protected
Definition at line 65 of file DepthCamera.h.
Referenced by Voxel::TI::ToFCameraBase::_captureRawUnprocessedFrame(), Voxel::TI::CalculusCDKCamera::_init(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::HaddockCDKCamera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::Voxel14Camera::_setStreamerFrameSize(), Voxel::TI::CalculusCDKCamera::_setStreamerFrameSize(), Voxel::TI::HaddockCDKCamera::_setStreamerFrameSize(), Voxel::TI::VoxelDCamera::_setStreamerFrameSize(), Voxel::TI::TintinCDKCamera::_setStreamerFrameSize(), Voxel::TI::ToFCameraBase::_start(), Voxel::TI::ToFCameraBase::_stop(), and close().
FilterSet<RawFrame> Voxel::DepthCamera::_unprocessedFilters protected
Definition at line 78 of file DepthCamera.h.
Referenced by _captureLoop(), addFilter(), getFilter(), removeAllFilters(), removeFilter(), and resetFilters().
MainConfigurationFile Voxel::DepthCamera::configFile
Definition at line 152 of file DepthCamera.h.
Referenced by Voxel::TI::ToFHaddockCamera::_applyCalibrationParams(), Voxel::TI::ToFTintinCamera::_applyCalibrationParams(), Voxel::TI::ToFCamera::_getDepthScalingFactor(), Voxel::TI::ToFHaddockCamera::_init(), Voxel::TI::Voxel14Camera::_init(), Voxel::TI::VoxelDCamera::_init(), Voxel::TI::TintinCDKCamera::_init(), Voxel::TI::ToFCalculusCamera::_init(), Voxel::TI::ToFTintinCamera::_init(), _init(), Voxel::TI::ToFCamera::_initStartParams(), addCameraProfile(), DepthCamera(), removeCameraProfile(), and setCameraProfile().
The documentation for this class was generated from the following files:
DepthCamera.h
DepthCamera.cpp