Voxel: Voxel::UVCStreamer Class Reference
Voxel::UVCStreamer Class Reference
I/O classes
#include <UVCStreamer.h>
Classes
class UVCStreamerPrivate
Public Member Functions
UVCStreamer (DevicePtr device)
virtual bool isInitialized ()
virtual bool getSupportedVideoModes (Vector< VideoMode > &videoModes)
virtual bool getCurrentVideoMode (VideoMode &videoMode)
virtual bool setVideoMode (const VideoMode &videoMode)
virtual ~UVCStreamer ()
Public Member Functions inherited from Voxel::Streamer
Streamer (DevicePtr device)
virtual ~Streamer ()
virtual bool isRunning ()
virtual bool start ()
virtual bool capture (RawDataFramePtr &p)
virtual bool stop ()
Protected Member Functions
void _storeCurrentVideoMode (const VideoMode &videoMode)
bool _uvcInit ()
bool _initForCapture ()
virtual bool _start ()
virtual bool _capture (RawDataFramePtr &p)
virtual bool _stop ()
Protected Attributes
Ptr< UVCStreamerPrivate > _uvcStreamerPrivate
Ptr< VideoMode > _currentVideoMode
Protected Attributes inherited from Voxel::Streamer
DevicePtr _device
Timer _time
int _currentID = -1
TimeStampType _currentTimeStamp = 0
bool _isRunning = false
Detailed Description
Definition at line 24 of file UVCStreamer.h.
Constructor & Destructor Documentation
Voxel::UVCStreamer::UVCStreamer (Voxel::DevicePtr device)
Definition at line 335 of file UVCStreamer.cpp.
References _uvcInit(), and _uvcStreamerPrivate.
                                               : Streamer(device)
 {
   if (!_uvcInit() && _uvcStreamerPrivate)
   {
     _uvcStreamerPrivate->initialized = false;
     return;
   }
 }
Voxel::UVCStreamer::~UVCStreamer () virtual
Definition at line 1078 of file UVCStreamer.cpp.
References isInitialized(), Voxel::Streamer::isRunning(), and Voxel::Streamer::stop().
 {
   if(isInitialized() && isRunning())
     stop(); // NOTE This cannot be called in the base class desctructor as UVCStreamer would already be destroyed by then
 }
Member Function Documentation
bool Voxel::UVCStreamer::_capture (RawDataFramePtr & p) protected virtual
Implements Voxel::Streamer.
Definition at line 887 of file UVCStreamer.cpp.
References Voxel::Streamer::_currentID, Voxel::Streamer::_time, _uvcStreamerPrivate, Voxel::Timer::convertToRealTime(), Voxel::Timer::getCurentRealTime(), isInitialized(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, and Voxel::logger.
 {
   TimeStampType waitTime = 2000;//ms
 #ifdef LINUX
   bool timedOut;
   if(!isInitialized() || !_uvcStreamerPrivate->uvc->getUVCPrivate().isReadReady(waitTime, timedOut))
   {
     if(timedOut)
       logger(LOG_ERROR) << "No data available. Waited for " << waitTime << " ms" << std::endl;
     return false;
   }
   if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_READ_WRITE)
   {
     if(!p || p->data.size() != _uvcStreamerPrivate->frameByteSize)
     {
       p = RawDataFramePtr(new RawDataFrame());
       p->data.resize(_uvcStreamerPrivate->frameByteSize);
       logger(LOG_DEBUG) << "UVCStreamer: Frame provided is not of appropriate size. Recreating a new frame." << std::endl;
     }
     bool ret = _uvcStreamerPrivate->uvc->read(p->data.data(), _uvcStreamerPrivate->frameByteSize);
     if(ret)
     {
       p->id = _currentID++;
       p->timestamp = _time.getCurentRealTime();
       return true;
     }
     return false;
   }
   else if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_MMAP || _uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_USER_POINTER)
   {
     struct v4l2_buffer buf;
     memset(&buf, 0, sizeof(buf));
     buf.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     buf.memory = (_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_MMAP)?V4L2_MEMORY_MMAP:V4L2_MEMORY_USERPTR;
     if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_DQBUF, &buf) == -1)
     {
       switch(errno)
       {
         case EIO:
           /* Could ignore EIO, see spec. */
           /* fall through */
         default:
           logger(LOG_ERROR) << "UVCStreamer: Failed to dequeue a raw frame buffer" << std::endl;
           return false;
       }
     }
     if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_USER_POINTER)
     {
       buf.index = _uvcStreamerPrivate->rawDataBuffers.size();
       for(auto i = 0; i < _uvcStreamerPrivate->rawDataBuffers.size(); i++)
         if(&*_uvcStreamerPrivate->rawDataBuffers[i].data == (ByteType *)buf.m.userptr && _uvcStreamerPrivate->rawDataBuffers[i].size == buf.bytesused)
         {
           buf.index = i;
           break;
         }
     }
     assert(buf.index < _uvcStreamerPrivate->rawDataBuffers.size());
     if(buf.bytesused < _uvcStreamerPrivate->frameByteSize)
     {
       logger(LOG_ERROR) << "Incomplete frame data. Skipping it. Expected bytes = "
       << _uvcStreamerPrivate->frameByteSize << ", got bytes = " << buf.bytesused << std::endl;
       if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_QBUF, &buf) == -1)
       {
         logger(LOG_ERROR) << "UVCStreamer: Failed to enqueue back the raw frame buffer" << std::endl;
         return false;
       }
       return false;
     }
     if(!p || p->data.size() != buf.bytesused)
     {
       p = RawDataFramePtr(new RawDataFrame());
       p->data.resize(buf.bytesused);
       logger(LOG_DEBUG) << "UVCStreamer: Frame provided is not of appropriate size. Recreating a new frame." << std::endl;
     }
     p->timestamp = _time.convertToRealTime(buf.timestamp.tv_sec*1000000L + buf.timestamp.tv_usec);
     memcpy(p->data.data(), &*_uvcStreamerPrivate->rawDataBuffers[buf.index].data, buf.bytesused);
     if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_QBUF, &buf) == -1)
     {
       logger(LOG_ERROR) << "UVCStreamer: Failed to enqueue back the raw frame buffer" << std::endl;
       return false;
     }
     p->id = _currentID++;
     return true;
   }
 #elif defined(WINDOWS)
   if (_uvcStreamerPrivate->getBuffer(waitTime, p))
   {
     p->id = _currentID++;
     return true;
   }
   return false;
 #endif
 }
bool Voxel::UVCStreamer::_initForCapture () protected
Definition at line 618 of file UVCStreamer.cpp.
References _currentVideoMode, Voxel::Streamer::_device, _uvcInit(), _uvcStreamerPrivate, getCurrentVideoMode(), Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::logger, and setVideoMode().
Referenced by _start().
 {
   if(!_uvcInit())
     return false;
 #ifdef LINUX
   struct v4l2_capability cap;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_QUERYCAP, &cap) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " is not a V4L2 device" << std::endl;
     return _uvcStreamerPrivate->initialized = false;
   }
   if(!(cap.capabilities & V4L2_CAP_VIDEO_CAPTURE))
   {
     logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " is no video capture device" << std::endl;
     return _uvcStreamerPrivate->initialized = false;
   }
   if(cap.capabilities & V4L2_CAP_READWRITE)
   {
     logger(LOG_INFO) << "UVCStreamer: " << _device->id() << " does not support read()/write() calls" << std::endl;
     _uvcStreamerPrivate->captureMode = UVCStreamerPrivate::CAPTURE_READ_WRITE;
   }
   else if(cap.capabilities & V4L2_CAP_STREAMING)
   {
     logger(LOG_INFO) << "UVCStreamer: " << _device->id() << " supports streaming modes" << std::endl;
     _uvcStreamerPrivate->captureMode = UVCStreamerPrivate::CAPTURE_STREAMING;
   }
 #endif
   if (_currentVideoMode && !setVideoMode(*_currentVideoMode))
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not set the current video mode" << std::endl;
     return _uvcStreamerPrivate->initialized = false;
   }
   VideoMode currentVideoMode;
   if(!getCurrentVideoMode(currentVideoMode))
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get the current video mode" << std::endl;
     return _uvcStreamerPrivate->initialized = false;
   }
   return _uvcStreamerPrivate->initialized = true;
 }
bool Voxel::UVCStreamer::_start () protected virtual
Implements Voxel::Streamer.
Definition at line 669 of file UVCStreamer.cpp.
References Voxel::Streamer::_device, _initForCapture(), _uvcStreamerPrivate, Voxel::LOG_ERROR, Voxel::LOG_INFO, Voxel::LOG_WARNING, Voxel::logger, and MAX_BUFFER_COUNT.
 {
   if(!_initForCapture())
     return false;
 #ifdef LINUX
   if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_STREAMING)
   {
     struct v4l2_requestbuffers req;
     memset(&req, 0, sizeof(req));
     req.count = MAX_BUFFER_COUNT;
     req.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     req.memory = V4L2_MEMORY_MMAP;
     if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_REQBUFS, &req) == -1)
     {
       if(EINVAL == errno)
       {
         logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " does not support mmap" << std::endl;
         memset(&req, 0, sizeof(req));
         req.count = MAX_BUFFER_COUNT;
         req.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
         req.memory = V4L2_MEMORY_USERPTR;
         if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_REQBUFS, &req) == -1)
         {
           if(EINVAL == errno)
           {
             logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " does not support user pointer" << std::endl;
             return _uvcStreamerPrivate->initialized = false; // No usable capture mode available
           }
         }
         else
         {
           logger(LOG_INFO) << "UVCStreamer: " << _device->id() << " supports user pointer" << std::endl;
           _uvcStreamerPrivate->captureMode = UVCStreamerPrivate::CAPTURE_USER_POINTER;
           if(req.count < 2)
           {
             logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " insufficient buffers to capture" << std::endl;
             return _uvcStreamerPrivate->initialized = false;
           }
           _uvcStreamerPrivate->rawDataBuffers.resize(req.count);
         }
       }
       else
       {
         logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " VIDIC_REQBUFS failed" << std::endl;
         return _uvcStreamerPrivate->initialized = false;
       }
     }
     else
     {
       logger(LOG_INFO) << "UVCStreamer: " << _device->id() << " supports mmap" << std::endl;
       _uvcStreamerPrivate->captureMode = UVCStreamerPrivate::CAPTURE_MMAP;
       if(req.count < 2)
       {
         logger(LOG_ERROR) << "UVCStreamer: " << _device->id() << " insufficient buffers to capture" << std::endl;
         return _uvcStreamerPrivate->initialized = false;
       }
       _uvcStreamerPrivate->rawDataBuffers.resize(req.count);
     }
   }
   if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_MMAP)
   {
     for(auto i = 0; i < _uvcStreamerPrivate->rawDataBuffers.size(); i++)
     {
       struct v4l2_buffer buf;
       memset(&buf, 0, sizeof(buf));
       buf.type   = V4L2_BUF_TYPE_VIDEO_CAPTURE;
       buf.memory = V4L2_MEMORY_MMAP;
       buf.index  = i;
       if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_QUERYBUF, &buf) == -1)
       {
         logger(LOG_ERROR) << "UVCStreamer: Could not prepare raw data buffer '" << i << "'" << std::endl;
         return _uvcStreamerPrivate->initialized = false;
       }
       _uvcStreamerPrivate->rawDataBuffers[i].size = buf.length;
       if(!_uvcStreamerPrivate->uvc->getUVCPrivate().mmap(buf.m.offset, _uvcStreamerPrivate->rawDataBuffers[i]))
       {
         logger(LOG_ERROR) << "UVCStreamer: Failed to get raw memory mapped buffer '" << i << "'" << std::endl;
         return _uvcStreamerPrivate->initialized = false;
       }
     }
   }
   else if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_USER_POINTER)
   {
     for(auto i = 0; i < _uvcStreamerPrivate->rawDataBuffers.size(); i++)
     {
       _uvcStreamerPrivate->rawDataBuffers[i].size = _uvcStreamerPrivate->frameByteSize;
       _uvcStreamerPrivate->rawDataBuffers[i].data = Ptr<ByteType>(new ByteType[_uvcStreamerPrivate->frameByteSize],
                                               [](ByteType *d){ delete []d; });
     }
   }
   if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_MMAP || _uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_USER_POINTER)
   {
     for(auto i = 0; i < _uvcStreamerPrivate->rawDataBuffers.size(); i++)
     {
       struct v4l2_buffer buf;
       memset(&buf, 0, sizeof(buf));
       buf.type   = V4L2_BUF_TYPE_VIDEO_CAPTURE;
       buf.memory = (_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_MMAP)?V4L2_MEMORY_MMAP:V4L2_MEMORY_USERPTR;
       buf.index  = i;
       if(_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_USER_POINTER)
       {
         buf.m.userptr = (unsigned long)&*_uvcStreamerPrivate->rawDataBuffers[i].data;
         buf.length = _uvcStreamerPrivate->rawDataBuffers[i].size;
       }
       if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_QBUF, &buf) == -1)
       {
         logger(LOG_ERROR) << "UVCStreamer: Could not queue raw data buffer '" << i << "'" << std::endl;
         return _uvcStreamerPrivate->initialized = false;
       }
     }
     enum v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
     if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_STREAMON, &type) == -1)
     {
       logger(LOG_ERROR) << "UVCStreamer: Failed to start capture stream" << std::endl;
       return _uvcStreamerPrivate->initialized = false;
     }
   }
 #elif defined(WINDOWS)
   HRESULT hr;
   if ((hr = _uvcStreamerPrivate->mediaControl->Run()) < 0)
   {
     logger(LOG_ERROR) << "Failed to start the capture filter. Error: " << _com_error(hr).ErrorMessage();
     return false;
   }
   OAFilterState state;
   if ((hr == _uvcStreamerPrivate->mediaControl->GetState(INFINITE, &state)) != S_OK)
   {
     logger(LOG_ERROR) << "Failed to start the capture filter. Error: " << _com_error(hr).ErrorMessage();
     return false;
   }
   if (state != State_Running)
   {
     logger(LOG_ERROR) << "Filter is not running. Current state: " << state << std::endl;
     return false;
   }
   if ((hr = _uvcStreamerPrivate->AddGraphToRot()) != S_OK) // Allow for graph debugging via graphedit
   {
     logger(LOG_WARNING) << "Could not add filter graph to ROT" << std::endl;
   }
 #endif
   return true;
 }
bool Voxel::UVCStreamer::_stop () protected virtual
Implements Voxel::Streamer.
Definition at line 842 of file UVCStreamer.cpp.
References _uvcStreamerPrivate, isInitialized(), Voxel::LOG_ERROR, and Voxel::logger.
 {
   if(!isInitialized())
     return false;
 #ifdef LINUX
   enum v4l2_buf_type type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_STREAMOFF, &type) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Failed to stop capture stream" << std::endl;
     return _uvcStreamerPrivate->initialized = false;
   }
   _uvcStreamerPrivate->uvc->getUVCPrivate().clearMMap();
   struct v4l2_requestbuffers req;
   memset(&req, 0, sizeof(req));
   req.count = 0;
   req.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
   req.memory = (_uvcStreamerPrivate->captureMode == UVCStreamerPrivate::CAPTURE_MMAP)?V4L2_MEMORY_MMAP:V4L2_MEMORY_USERPTR;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_REQBUFS, &req) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Failed to remove buffers" << std::endl;
     return _uvcStreamerPrivate->initialized = false;
   }
   _uvcStreamerPrivate->rawDataBuffers.clear();
 #elif defined(WINDOWS)
   _uvcStreamerPrivate->mediaControl->Stop();
   long evCode;
   _uvcStreamerPrivate->mediaEventEx->WaitForCompletion(500, &evCode);
   _uvcStreamerPrivate->RemoveGraphFromRot(); // Remove graph for debugging via graphedit
 #endif
   return true;
 }
void Voxel::UVCStreamer::_storeCurrentVideoMode (const VideoMode & videoMode) protected
Definition at line 514 of file UVCStreamer.cpp.
References _currentVideoMode.
Referenced by setVideoMode().
 {
   if (!_currentVideoMode)
     _currentVideoMode = Ptr<VideoMode>(new VideoMode());
   *_currentVideoMode = videoMode;
 }
bool Voxel::UVCStreamer::_uvcInit () protected
Definition at line 344 of file UVCStreamer.cpp.
References Voxel::Streamer::_device, _uvcStreamerPrivate, Voxel::LOG_ERROR, Voxel::logger, and Voxel::Device::USB.
Referenced by _initForCapture(), and UVCStreamer().
 {
   if(_device->interfaceID() != Device::USB)
     return false;
   _uvcStreamerPrivate = Ptr<UVCStreamerPrivate>(new UVCStreamerPrivate());
   _uvcStreamerPrivate->uvc = Ptr<UVC>(new UVC(_device));
 #ifdef WINDOWS
   if (_uvcStreamerPrivate->uvc->isInitialized())
   {
     HRESULT hr;
     if ((hr = CoCreateInstance(CLSID_FilterGraph, NULL, CLSCTX_INPROC, IID_IGraphBuilder, (void **)&_uvcStreamerPrivate->filterGraph)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to create filter graph. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->filterGraph->QueryInterface(IID_IMediaControl, (LPVOID *)&_uvcStreamerPrivate->mediaControl)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to get interface for media control. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->filterGraph->QueryInterface(IID_IMediaEventEx, (LPVOID *)&_uvcStreamerPrivate->mediaEventEx)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to get interface for media filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->filterGraph->QueryInterface(IID_IMediaFilter, (LPVOID *)&_uvcStreamerPrivate->mediaFilter)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to get interface for media filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->filterGraph->AddFilter(_uvcStreamerPrivate->uvc->getUVCPrivate().getCaptureFilter(), L"UVC Capture")) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to add UVC capture filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     // Create the Sample Grabber filter.
     if ((hr = CoCreateInstance(CLSID_SampleGrabber, NULL, CLSCTX_INPROC_SERVER, IID_IBaseFilter, (LPVOID *)&_uvcStreamerPrivate->sampleGrabberFilter)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to create sample grabber filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->filterGraph->AddFilter(_uvcStreamerPrivate->sampleGrabberFilter, L"Sample Grabber")) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to add sample grabber filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->sampleGrabberFilter->QueryInterface(IID_ISampleGrabber, (LPVOID *)&_uvcStreamerPrivate->sampleGrabber)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to get sample grabber interface. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     AM_MEDIA_TYPE mt;
     ZeroMemory(&mt, sizeof(AM_MEDIA_TYPE));
     mt.majortype = MEDIATYPE_Video;
     mt.subtype = MEDIASUBTYPE_YUY2;
     mt.formattype = FORMAT_VideoInfo;
     if ((hr = _uvcStreamerPrivate->sampleGrabber->SetMediaType(&mt)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to set YUY2 as media subtype. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->sampleGrabber->SetBufferSamples(FALSE)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to configure sample grabber. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->sampleGrabber->SetOneShot(FALSE)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to configure sample grabber. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->sampleGrabber->SetCallback(&*_uvcStreamerPrivate, 1)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to configure sample grabber. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = CoCreateInstance(CLSID_NullRenderer, NULL, CLSCTX_INPROC_SERVER, IID_IBaseFilter, (LPVOID *)&_uvcStreamerPrivate->nullRendererFilter)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to create null renderer filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->filterGraph->AddFilter(_uvcStreamerPrivate->nullRendererFilter, L"Null Renderer")) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to add null renderer filter. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = CoCreateInstance(CLSID_CaptureGraphBuilder2, NULL, CLSCTX_INPROC, IID_ICaptureGraphBuilder2, (void **)&_uvcStreamerPrivate->captureGraphBuilder2)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to create capture graph builder. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->captureGraphBuilder2->SetFiltergraph(_uvcStreamerPrivate->filterGraph)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to set filter graph to capture graph builder. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
     if ((hr = _uvcStreamerPrivate->captureGraphBuilder2->RenderStream(&PIN_CATEGORY_CAPTURE, &MEDIATYPE_Video,
       _uvcStreamerPrivate->uvc->getUVCPrivate().getCaptureFilter(), _uvcStreamerPrivate->sampleGrabberFilter, _uvcStreamerPrivate->nullRendererFilter)) != S_OK)
     {
       logger(LOG_ERROR) << "Failed to connect filters in the capture graph builder. Error: " << _com_error(hr).ErrorMessage();
       return _uvcStreamerPrivate->initialized = false;
     }
   }
 #endif
   return _uvcStreamerPrivate->uvc->isInitialized();
 }
bool Voxel::UVCStreamer::getCurrentVideoMode (VideoMode & videoMode) virtual
Implements Voxel::Streamer.
Definition at line 473 of file UVCStreamer.cpp.
References _uvcStreamerPrivate, Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, isInitialized(), Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameRate::numerator, and Voxel::FrameSize::width.
Referenced by _initForCapture(), and main().
 {
   if(!isInitialized())
     return false;
 #ifdef LINUX
   struct v4l2_format fmt;
   memset(&fmt, 0, sizeof(fmt));
   fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_G_FMT, &fmt) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get current frame format" << std::endl;
     return false;
   }
   videoMode.frameSize.width = fmt.fmt.pix.width;
   videoMode.frameSize.height = fmt.fmt.pix.height;
   _uvcStreamerPrivate->updateFrameByteSize(fmt.fmt.pix.width, fmt.fmt.pix.height, fmt.fmt.pix.bytesperline, fmt.fmt.pix.sizeimage);
   struct v4l2_streamparm parm;
   memset(&parm, 0, sizeof(parm));
   parm.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_G_PARM, &parm) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get current capture parameters" << std::endl;
     return false;
   }
   videoMode.frameRate.numerator = parm.parm.capture.timeperframe.denominator;
   videoMode.frameRate.denominator = parm.parm.capture.timeperframe.numerator;
 #elif defined(WINDOWS)
 #endif
   return true;
 }
bool Voxel::UVCStreamer::getSupportedVideoModes (Vector< VideoMode > & videoModes) virtual
Implements Voxel::Streamer.
Definition at line 999 of file UVCStreamer.cpp.
References _uvcStreamerPrivate, Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, isInitialized(), Voxel::LOG_WARNING, Voxel::logger, Voxel::FrameRate::numerator, and Voxel::FrameSize::width.
Referenced by main().
 {
   if(!isInitialized())
     return false;
   videoModes.clear();
 #ifdef LINUX
   int frameSizeIndex = 0;
   int frameRateIndex = 0;
   uint32_t frameWidth, frameHeight;
   struct v4l2_frmsizeenum frameSizeEnum;
   struct v4l2_frmivalenum frameIntervalEnum;
   while(1)
   {
     memset(&frameSizeEnum, 0, sizeof(frameSizeEnum));
     frameSizeEnum.index = frameSizeIndex++;
     frameSizeEnum.pixel_format = V4L2_PIX_FMT_YUYV;//V4L2_PIX_FMT_UYVY;//V4L2_PIX_FMT_YUYV;
     if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_ENUM_FRAMESIZES, &frameSizeEnum) == -1)
     {
       if(errno == EINVAL)
         break;
       else
         return false;
     }
     if(frameSizeEnum.type != V4L2_FRMSIZE_TYPE_DISCRETE)
     {
       logger(LOG_WARNING) << "Frame types other than discrete, are not supported currently." << std::endl;
       continue;
     }
     frameWidth = frameSizeEnum.discrete.width;
     frameHeight = frameSizeEnum.discrete.height;
     frameRateIndex = 0;
     while(1)
     {
       memset(&frameIntervalEnum, 0, sizeof(frameIntervalEnum));
       frameIntervalEnum.index = frameRateIndex++;
       frameIntervalEnum.pixel_format = V4L2_PIX_FMT_YUYV;
       frameIntervalEnum.width = frameWidth;
       frameIntervalEnum.height = frameHeight;
       if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_ENUM_FRAMEINTERVALS, &frameIntervalEnum) == -1)
       {
         if(errno == EINVAL)
           break;
         else
           return false;
       }
       if(frameIntervalEnum.type != V4L2_FRMIVAL_TYPE_DISCRETE)
       {
         logger(LOG_WARNING) << "Frame interval types other than discrete, are not supported currently." << std::endl;
         continue;
       }
       VideoMode vm;
       vm.frameSize.width = frameWidth;
       vm.frameSize.height = frameHeight;
       vm.frameRate.numerator = frameIntervalEnum.discrete.denominator;
       vm.frameRate.denominator = frameIntervalEnum.discrete.numerator;
       videoModes.push_back(vm);
     }
   }
 #elif defined(WINDOWS)
 #endif
   return true;
 }
bool Voxel::UVCStreamer::isInitialized () virtual
Implements Voxel::Streamer.
Definition at line 330 of file UVCStreamer.cpp.
Referenced by _capture(), _stop(), getCurrentVideoMode(), getSupportedVideoModes(), main(), setVideoMode(), and ~UVCStreamer().
 {
   return _uvcStreamerPrivate->uvc && _uvcStreamerPrivate->initialized;
 }
bool Voxel::UVCStreamer::setVideoMode (const VideoMode & videoMode) virtual
Implements Voxel::Streamer.
Definition at line 522 of file UVCStreamer.cpp.
References _storeCurrentVideoMode(), _uvcStreamerPrivate, Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::VideoMode::getFrameRate(), Voxel::FrameSize::height, isInitialized(), Voxel::Streamer::isRunning(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameRate::numerator, and Voxel::FrameSize::width.
Referenced by _initForCapture(), Voxel::TI::Voxel14Camera::_setStreamerFrameSize(), Voxel::TI::VoxelDCamera::_setStreamerFrameSize(), Voxel::TI::TintinCDKCamera::_setStreamerFrameSize(), and main().
 {
   if(!isInitialized() || isRunning())
     return false;
   logger(LOG_DEBUG) << "UVCStreamer: Setting video mode = "
     << videoMode.frameSize.width << "x" << videoMode.frameSize.height
     << "@" << videoMode.getFrameRate() << "fps" << std::endl;
 #ifdef LINUX
   struct v4l2_format fmt;
   memset(&fmt, 0, sizeof(fmt));
   fmt.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_G_FMT, &fmt) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get current frame format" << std::endl;
     return false;
   }
   fmt.fmt.pix.width = videoMode.frameSize.width;
   fmt.fmt.pix.height = videoMode.frameSize.height;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_S_FMT, &fmt) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not set current frame format" << std::endl;
     return false;
   }
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_G_FMT, &fmt) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not set current frame format" << std::endl;
     return false;
   }
   _uvcStreamerPrivate->updateFrameByteSize(fmt.fmt.pix.width, fmt.fmt.pix.height, fmt.fmt.pix.bytesperline, fmt.fmt.pix.sizeimage);
   struct v4l2_streamparm parm;
   memset(&parm, 0, sizeof(parm));
   parm.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_G_PARM, &parm) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get current capture parameters" << std::endl;
     return false;
   }
   parm.parm.capture.timeperframe.denominator = videoMode.frameRate.numerator;
   parm.parm.capture.timeperframe.numerator = videoMode.frameRate.denominator;
   if(_uvcStreamerPrivate->uvc->getUVCPrivate().xioctl(VIDIOC_S_PARM, &parm) == -1)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not set current capture parameters" << std::endl;
     return false;
   }
 #elif defined(WINDOWS)
   HRESULT hr;
   IAMStreamConfig *config;
   if((hr = _uvcStreamerPrivate->captureGraphBuilder2->FindInterface(&PIN_CATEGORY_CAPTURE, &MEDIATYPE_Video,
     _uvcStreamerPrivate->uvc->getUVCPrivate().getCaptureFilter(), IID_IAMStreamConfig, (void**)&config)) != S_OK)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get stream configurator. Error: " << _com_error(hr).ErrorMessage();
     return false;
   }
   AM_MEDIA_TYPE *mtConfig = NULL;
   if ((hr = config->GetFormat(&mtConfig)) != S_OK)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get current format. Error: " << _com_error(hr).ErrorMessage();
     config->Release();
     return false;
   }
   VIDEOINFOHEADER *videoHeader = (VIDEOINFOHEADER*)mtConfig->pbFormat;
   videoHeader->AvgTimePerFrame = videoMode.frameRate.denominator / videoMode.frameRate.numerator;
   videoHeader->bmiHeader.biWidth = videoMode.frameSize.width;
   videoHeader->bmiHeader.biHeight = videoMode.frameSize.height;
   if ((hr = config->SetFormat(mtConfig)) != S_OK)
   {
     logger(LOG_ERROR) << "UVCStreamer: Could not get current format. Error: " << _com_error(hr).ErrorMessage();
     config->Release();
     _uvcStreamerPrivate->DeleteMediaType(mtConfig);
     return false;
   }
   config->Release();
   _uvcStreamerPrivate->DeleteMediaType(mtConfig);
 #endif
   _storeCurrentVideoMode(videoMode);
   return true;
 }
Member Data Documentation
Ptr<VideoMode> Voxel::UVCStreamer::_currentVideoMode protected
Definition at line 30 of file UVCStreamer.h.
Referenced by _initForCapture(), and _storeCurrentVideoMode().
Ptr<UVCStreamerPrivate> Voxel::UVCStreamer::_uvcStreamerPrivate protected
Definition at line 27 of file UVCStreamer.h.
Referenced by _capture(), _initForCapture(), _start(), _stop(), _uvcInit(), getCurrentVideoMode(), getSupportedVideoModes(), setVideoMode(), and UVCStreamer().
The documentation for this class was generated from the following files:
UVCStreamer.h
UVCStreamer.cpp