Voxel: Voxel::TI::Voxel14Camera Class Reference
Voxel::TI::Voxel14Camera Class Reference
#include <Voxel14Camera.h>
Public Member Functions
Voxel14Camera (DevicePtr device)
virtual ~Voxel14Camera ()
Public Member Functions inherited from Voxel::TI::ToFHaddockCamera
ToFHaddockCamera (const String &name, DevicePtr device)
virtual ~ToFHaddockCamera ()
Public Member Functions inherited from Voxel::TI::ToFCamera
ToFCamera (const String &name, DevicePtr device)
virtual bool setSerialNumber (const String &serialNumber)
virtual ~ToFCamera ()
Public Member Functions inherited from Voxel::TI::ToFCameraBase
ToFCameraBase (const String &name, DevicePtr device)
virtual ~ToFCameraBase ()
Public Member Functions inherited from Voxel::DepthCamera
DepthCamera (const String &name, DevicePtr device)
virtual bool isInitialized () const
const String & name () const
const String & id () const
virtual bool getSerialNumber (String &serialNumber) const
const DevicePtr & getDevice () const
bool isRunning () const
template<typename T >
bool getStreamParam (const String &name, T &value) const
bool refreshParams ()
template<typename T >
bool get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool set (const String &name, const T &value)
const ParameterPtr getParam (const String &name) const
const Map< String, ParameterPtr > & getParameters () const
bool setFrameRate (const FrameRate &r)
bool getFrameRate (FrameRate &r) const
bool setFrameSize (const FrameSize &s)
bool getFrameSize (FrameSize &s) const
bool getMaximumFrameSize (FrameSize &s) const
bool getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
bool getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
bool getMaximumVideoMode (VideoMode &videoMode) const
bool getBytesPerPixel (uint &bpp) const
bool setBytesPerPixel (const uint &bpp)
bool getROI (RegionOfInterest &roi)
bool setROI (const RegionOfInterest &roi)
bool allowedROI (String &message)
bool getFieldOfView (float &fovHalfAngle) const
virtual bool saveFrameStream (const String &fileName)
virtual bool isSavingFrameStream ()
virtual bool closeFrameStream ()
virtual bool registerCallback (FrameType type, CallbackType f)
virtual bool clearAllCallbacks ()
virtual bool clearCallback (FrameType type)
virtual int addFilter (FilterPtr p, FrameType frameType, int beforeFilterID=-1)
virtual FilterPtr getFilter (int filterID, FrameType frameType) const
virtual bool removeFilter (int filterID, FrameType frameType)
virtual bool removeAllFilters (FrameType frameType)
virtual void resetFilters ()
const FilterSet< RawFrame > & getUnprocessedRawFilterSet ()
const FilterSet< RawFrame > & getProcessedRawFilterSet ()
const FilterSet< DepthFrame > & getDepthFilterSet ()
bool start ()
bool stop ()
void wait ()
bool reset ()
Ptr< RegisterProgrammer > getProgrammer ()
Ptr< Streamer > getStreamer ()
bool reloadConfiguration ()
const Map< int, String > & getCameraProfileNames ()
int getCurrentCameraProfileID ()
int addCameraProfile (const String &profileName, const int parentID)
bool setCameraProfile (const int id, bool softApply=false)
bool removeCameraProfile (const int id)
bool saveCameraProfileToHardware (int &id)
bool close ()
virtual ~DepthCamera ()
Protected Member Functions
bool _init ()
virtual bool _getFieldOfView (float &fovHalfAngle) const
virtual bool _getSupportedVideoModes (Vector< SupportedVideoMode > &supportedVideoModes) const
virtual bool _setStreamerFrameSize (const FrameSize &s)
virtual bool _getMaximumVideoMode (VideoMode &videoMode) const
virtual bool _initStartParams ()
Protected Member Functions inherited from Voxel::TI::ToFHaddockCamera
bool _init ()
bool _getMaximumFrameSize (FrameSize &s) const
virtual bool _getSystemClockFrequency (uint &frequency) const
virtual bool _getIlluminationFrequency (float &frequency) const
virtual bool _allowedROI (String &message)
virtual bool _getROI (RegionOfInterest &roi)
virtual bool _setROI (const RegionOfInterest &roi)
virtual bool _isHistogramEnabled () const
virtual bool _applyCalibrationParams ()
virtual bool _getCurrentProfileRegisterName (String &name)
Protected Member Functions inherited from Voxel::TI::ToFCamera
bool _init ()
virtual bool _processRawFrame (const RawFramePtr &rawFrameInput, RawFramePtr &rawFrameOutput)
virtual bool _getAmplitudeNormalizingFactor (float &factor)
virtual bool _getDepthScalingFactor (float &factor)
virtual bool _setFrameRate (const FrameRate &r)
virtual bool _getFrameRate (FrameRate &r) const
virtual bool _getFrameSize (FrameSize &s) const
virtual bool _setFrameSize (const FrameSize &s)
virtual bool _setFrameSize (const FrameSize &s, bool resetROI)
virtual bool _getMaximumFrameRate (FrameRate &frameRate, const FrameSize &forFrameSize) const
virtual bool _getBytesPerPixel (uint &bpp) const
virtual bool _setBytesPerPixel (const uint &bpp)
virtual bool _getOpDataArrangeMode (int &dataArrangeMode) const
virtual bool _getBinning (uint &rowsToMerge, uint &columnsToMerge) const
virtual bool _setBinning (uint rowsToMerge, uint columnsToMerge, const FrameSize &frameSize)
virtual bool _getToFFrameType (ToFFrameType &frameType) const
virtual bool _is16BitModeEnabled (bool &mode16Bit)
virtual bool _getDealiasedPhaseMask (int &dealiasedPhaseMask)
virtual bool _getCurrentProfileID (int &id)
virtual bool _saveCurrentProfileID (const int id)
virtual bool _reset ()
Protected Member Functions inherited from Voxel::TI::ToFCameraBase
virtual bool _captureRawUnprocessedFrame (RawFramePtr &rawFrame)
virtual bool _convertToDepthFrame (const RawFramePtr &rawFrame, DepthFramePtr &depthFrame)
virtual bool _start ()
virtual bool _stop ()
bool _init ()
virtual bool _onReset ()
Protected Member Functions inherited from Voxel::DepthCamera
bool _addParameters (const Vector< ParameterPtr > &params)
virtual bool _callbackAndContinue (uint32_t &callBackTypesToBeCalled, FrameType type, const Frame &frame)
virtual bool _convertToPointCloudFrame (const DepthFramePtr &depthFrame, PointCloudFramePtr &pointCloudFrame)
virtual void _captureLoop ()
void _captureThreadWrapper ()
bool _writeToFrameStream (RawFramePtr &rawUnprocessed)
template<typename T >
bool _get (const String &name, T &value, bool refresh=false) const
template<typename T >
bool _set (const String &name, const T &value)
void _makeID ()
virtual bool _applyConfigParams (const ConfigSet *params)
bool _init ()
Protected Attributes
Ptr< Downloader > _downloader
Protected Attributes inherited from Voxel::TI::ToFCamera
Ptr< ToFFrameGenerator > _tofFrameGenerator
Protected Attributes inherited from Voxel::TI::ToFCameraBase
RawDataFramePtr _rawDataFrame
Ptr< ToFDepthFrameGenerator > _tofDepthFrameGenerator
Protected Attributes inherited from Voxel::DepthCamera
DevicePtr _device
String _name
String _id
Map< String, ParameterPtr > _parameters
Ptr< RegisterProgrammer > _programmer
Ptr< Streamer > _streamer
FrameGeneratorPtr _frameGenerators [3]
Ptr< PointCloudFrameGenerator > _pointCloudFrameGenerator
bool _parameterInit
FrameBufferManager< RawFrame > _rawFrameBuffers
FrameBufferManager< DepthFrame > _depthFrameBuffers
FrameBufferManager
< PointCloudFrame > _pointCloudBuffers
FilterSet< RawFrame > _unprocessedFilters
FilterSet< RawFrame > _processedFilters
FilterSet< DepthFrame > _depthFilters
FrameStreamWriterPtr _frameStreamWriter
CallbackType _callback [FRAME_TYPE_COUNT]
uint32_t _callBackTypesRegistered = 0
ThreadPtr _captureThread
bool _running
Additional Inherited Members
Public Types inherited from Voxel::DepthCamera
enum FrameType {
FRAME_RAW_FRAME_UNPROCESSED = 0, FRAME_RAW_FRAME_PROCESSED = 1, FRAME_DEPTH_FRAME = 2, FRAME_XYZI_POINT_CLOUD_FRAME = 3,
FRAME_TYPE_COUNT = 4
}
typedef Function< void(DepthCamera
&camera, const Frame &frame,
FrameType callBackType)> CallbackType
Public Attributes inherited from Voxel::DepthCamera
MainConfigurationFile configFile
Detailed Description
Definition at line 26 of file Voxel14Camera.h.
Constructor & Destructor Documentation
Voxel::TI::Voxel14Camera::Voxel14Camera (Voxel::DevicePtr device)
Definition at line 21 of file Voxel14Camera.cpp.
References _init().
                                                  : ToFHaddockCamera("Voxel14Camera", device)
 {
   _init();
 }
virtual Voxel::TI::Voxel14Camera::~Voxel14Camera () inline virtual
Definition at line 44 of file Voxel14Camera.h.
 {}
Member Function Documentation
bool Voxel::TI::Voxel14Camera::_getFieldOfView (float & fovHalfAngle) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 158 of file Voxel14Camera.cpp.
 {
   fovHalfAngle = (87/2.0f)*(M_PI/180.0f);
   return true;
 }
bool Voxel::TI::Voxel14Camera::_getMaximumVideoMode (VideoMode & videoMode) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 220 of file Voxel14Camera.cpp.
References Voxel::DepthCamera::_get(), Voxel::FrameRate::denominator, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::FrameSize::height, Voxel::LOG_ERROR, Voxel::logger, Voxel::FrameRate::numerator, PIXEL_DATA_SIZE, and Voxel::FrameSize::width.
 {
   int bytesPerPixel;
   if(!_get(PIXEL_DATA_SIZE, bytesPerPixel))
   {
     logger(LOG_ERROR) << "Voxel14Camera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   videoMode.frameSize.width = 320;
   videoMode.frameSize.height = 240;
   videoMode.frameRate.denominator = 1;
   videoMode.frameRate.numerator = (bytesPerPixel == 4)?25:50;
   return true;
 }
bool Voxel::TI::Voxel14Camera::_getSupportedVideoModes (Vector< SupportedVideoMode > & supportedVideoModes) const protected virtual
Implements Voxel::DepthCamera.
Definition at line 203 of file Voxel14Camera.cpp.
 {
   supportedVideoModes = Vector<SupportedVideoMode> {
     SupportedVideoMode(320,240,25,1,4),
     SupportedVideoMode(160,240,50,1,4),
     SupportedVideoMode(160,120,100,1,4),
     SupportedVideoMode(80,120,200,1,4),
     SupportedVideoMode(80,60,400,1,4),
     SupportedVideoMode(320,240,50,1,2),
     SupportedVideoMode(320,120,100,1,2),
     SupportedVideoMode(160,120,200,1,2),
     SupportedVideoMode(160,60,400,1,2),
     SupportedVideoMode(80,60,400,1,2),
   };
   return true;
 }
bool Voxel::TI::Voxel14Camera::_init () protected
Definition at line 84 of file Voxel14Camera.cpp.
References Voxel::DepthCamera::_addParameters(), Voxel::DepthCamera::_device, _downloader, Voxel::TI::ToFHaddockCamera::_init(), Voxel::DepthCamera::_makeID(), Voxel::DepthCamera::_programmer, Voxel::DepthCamera::_streamer, Voxel::DepthCamera::configFile, CameraSystemTest::devices, Voxel::MainConfigurationFile::get(), Voxel::LOG_ERROR, Voxel::logger, Voxel::USBDevice::productID(), Voxel::DeviceScanner::scan(), Voxel::Device::serialNumber(), Voxel::Device::USB, Voxel::USBDevice::vendorID(), VOXEL_14_PRODUCT_ID1, VOXEL_14_PRODUCT_ID2, and VOXEL_14_VENDOR_ID.
Referenced by Voxel14Camera().
 {
   USBDevice &d = (USBDevice &)*_device;
   DevicePtr controlDevice;
   if(d.productID() == VOXEL_14_PRODUCT_ID1)
   {
     Vector<DevicePtr> devices = DeviceScanner::scan();
     uint repeatCount = 0;
     for(auto &d1: devices)
     {
       if(d1->interfaceID() != Device::USB)
         continue;
       USBDevice &usbd = (USBDevice &)*d1;
       if(usbd.vendorID() == VOXEL_14_VENDOR_ID && usbd.productID() == VOXEL_14_PRODUCT_ID2 &&
         (d.serialNumber().size() == 0 || d.serialNumber() == usbd.serialNumber()))
         repeatCount++;
     }
     _downloader = Ptr<Downloader>(new USBDownloader(_device));
     if(!_downloader->download(configFile.get("core", "fw")))
     {
       logger(LOG_ERROR) << "Voxel14Camera: Firmware download failed" << std::endl;
       return false;
     }
     else
       std::this_thread::sleep_for(std::chrono::milliseconds(2000)); // wait for device to get ready after loading firmware
     controlDevice = DevicePtr(new USBDevice(VOXEL_14_VENDOR_ID, VOXEL_14_PRODUCT_ID2, _device->serialNumber(),
                                             _device->channelID(), _device->description(), _device->serialIndex(), repeatCount > 0));
     _device = controlDevice;
     _makeID();
   }
   else
     controlDevice = _device;
   _programmer = Ptr<RegisterProgrammer>(new VoxelXUProgrammer(
     { {0x2D, 1}, {0x58, 3}, {0x5C, 3} },
     controlDevice));
   _streamer = Ptr<Streamer>(new UVCStreamer(controlDevice));
   if(!_programmer->isInitialized() || !_streamer->isInitialized())
     return false;
   if(!_addParameters({
     ParameterPtr(new Voxel14MixVoltageParameter(*_programmer)),
     ParameterPtr(new Voxel14IlluminationVoltageParameter(*_programmer)),
     }))
   {
     return false;
   }
   if(!ToFHaddockCamera::_init())
     return false;
   return true;
 }
bool Voxel::TI::Voxel14Camera::_initStartParams () protected virtual
Reimplemented from Voxel::TI::ToFHaddockCamera.
Definition at line 148 of file Voxel14Camera.cpp.
References Voxel::TI::ToFHaddockCamera::_initStartParams().
 {
   return
   //set(ILLUM_VOLTAGE, 1500U) &&
   //set(MIX_VOLTAGE, 1500U) &&
   Voxel::TI::ToFHaddockCamera::_initStartParams();
 }
bool Voxel::TI::Voxel14Camera::_setStreamerFrameSize (const FrameSize & s) protected virtual
Implements Voxel::TI::ToFCamera.
Definition at line 164 of file Voxel14Camera.cpp.
References Voxel::DepthCamera::_get(), Voxel::TI::ToFCamera::_getFrameRate(), Voxel::DepthCamera::_streamer, Voxel::VideoMode::frameRate, Voxel::VideoMode::frameSize, Voxel::LOG_ERROR, Voxel::logger, PIXEL_DATA_SIZE, Voxel::UVCStreamer::setVideoMode(), and Voxel::FrameSize::width.
 {
   UVCStreamer *streamer = dynamic_cast<UVCStreamer *>(&*_streamer);
   if(!streamer)
   {
     logger(LOG_ERROR) << "Voxel14Camera: Streamer is not of type UVC" << std::endl;
     return false;
   }
   VideoMode m;
   m.frameSize = s;
   int bytesPerPixel;
   if(!_get(PIXEL_DATA_SIZE, bytesPerPixel))
   {
     logger(LOG_ERROR) << "Voxel14Camera: Could not get current bytes per pixel" << std::endl;
     return false;
   }
   if(bytesPerPixel == 4)
     m.frameSize.width *= 2;
   if(!_getFrameRate(m.frameRate))
   {
     logger(LOG_ERROR) << "Voxel14Camera: Could not get current frame rate" << std::endl;
     return false;
   }
   if(!streamer->setVideoMode(m))
   {
     logger(LOG_ERROR) << "Voxel14Camera: Could not set video mode for UVC" << std::endl;
     return false;
   }
   return true;
 }
Member Data Documentation
Ptr<Downloader> Voxel::TI::Voxel14Camera::_downloader protected
Definition at line 29 of file Voxel14Camera.h.
Referenced by _init().
The documentation for this class was generated from the following files:
Voxel14Camera.h
Voxel14Camera.cpp