Voxel: Data2DCodecTest.cpp File Reference
Data2DCodecTest.cpp File Reference
#include "Data2DCodec.h"
#include "SimpleOpt.h"
#include "Common.h"
#include "Logger.h"
#include <iomanip>
#include <fstream>
Enumerations
enum Options {
VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2, CREATE_PROFILE = 3,
PARENT_PROFILE_ID = 4, PROFILE_ID = 5, SECTION = 6, PARAM_NAME = 7,
PARAM_VALUE = 8, LIST_PROFILES = 9, REMOVE_PROFILE = 10, WRITE_TO_EEPROM = 11,
SAVE_FILE_TO_HOST = 12, DUMP_FILE = 3, VENDOR_ID = 0, PRODUCT_ID = 1,
SERIAL_NUMBER = 2, DUMP_FILE = 3, NUM_OF_FRAMES = 4, VENDOR_ID = 0,
PRODUCT_ID = 1, SERIAL_NUMBER = 2, DUMP_FILE = 3, NUM_OF_FRAMES = 4,
PHASE_OFFSET_FILE_NAME = 0, OUTPUT_FILE_NAME = 3, INPUT_FILE_NAME = 0, OUTPUT_FILE_NAME = 1,
XML_FILE = 0, VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2,
FIRMWARE_FILE = 3, VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2,
DUMP_FILE = 3, NUM_OF_FRAMES = 4, VENDOR_ID = 0, PRODUCT_ID = 1,
SERIAL_NUMBER = 2, REGISTER = 3, READ = 4, WRITE = 5,
DATA = 6, LENGTH = 7, LSB = 8, MSB = 9,
VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2
}
Functions
void help ()
int main (int argc, char *argv[])
Variables
Vector< CSimpleOpt::SOption > argumentSpecifications
Enumeration Type Documentation
enum Options
Enumerator
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
CREATE_PROFILE
PARENT_PROFILE_ID
PROFILE_ID
SECTION
PARAM_NAME
PARAM_VALUE
LIST_PROFILES
REMOVE_PROFILE
WRITE_TO_EEPROM
SAVE_FILE_TO_HOST
DUMP_FILE
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
DUMP_FILE
NUM_OF_FRAMES
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
DUMP_FILE
NUM_OF_FRAMES
PHASE_OFFSET_FILE_NAME
OUTPUT_FILE_NAME
INPUT_FILE_NAME
OUTPUT_FILE_NAME
XML_FILE
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
FIRMWARE_FILE
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
DUMP_FILE
NUM_OF_FRAMES
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
REGISTER
READ
WRITE
DATA
LENGTH
LSB
MSB
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
Definition at line 18 of file Data2DCodecTest.cpp.
 {
   PHASE_OFFSET_FILE_NAME = 0,
   OUTPUT_FILE_NAME = 3
 };
Function Documentation
void help ()
Definition at line 31 of file Data2DCodecTest.cpp.
References argumentSpecifications.
Referenced by main().
 {
   std::cout << "Data2DCodecTest v1.0" << std::endl;
   CSimpleOpt::SOption *option = argumentSpecifications.data();
   while(option->nId >= 0)
   {
     std::cout << option->pszArg << " " << option->helpInfo << std::endl;
     option++;
   }
 }
int main (int argc, char * argv[])
Definition at line 45 of file Data2DCodecTest.cpp.
References argumentSpecifications, Voxel::Data2DCodec::compress(), Voxel::Data2DCodec::decompress(), help(), Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, OUTPUT_FILE_NAME, PHASE_OFFSET_FILE_NAME, and Voxel::Logger::setDefaultLogLevel().
 {
   CSimpleOpt s(argc, argv, argumentSpecifications);
   logger.setDefaultLogLevel(LOG_DEBUG);
   String phaseOffsetFileName, outputFileName;
   uint16_t rows = 0, columns = 0;
   char *endptr;
   while (s.Next())
   {
     if (s.LastError() != SO_SUCCESS)
     {
       std::cout << s.GetLastErrorText(s.LastError()) << ": '" << s.OptionText() << "' (use -h to get command line help)" << std::endl;
       help();
       return -1;
     }
     //std::cout << s.OptionId() << ": " << s.OptionArg() << std::endl;
     Vector<String> splits;
     switch (s.OptionId())
     {
       case PHASE_OFFSET_FILE_NAME:
         phaseOffsetFileName = s.OptionArg();
         break;
       case OUTPUT_FILE_NAME:
         outputFileName = s.OptionArg();
         break;
       default:
         help();
         break;
     };
   }
   if(phaseOffsetFileName.size() == 0 || outputFileName.size() == 0)
   {
     logger(LOG_ERROR) << "Required argument missing." << std::endl;
     help();
     return -1;
   }
   InputFileStream p(phaseOffsetFileName, std::ios::binary | std::ios::ate);
   if(!p.good())
   {
     logger(LOG_ERROR) << "Failed to open '" << phaseOffsetFileName << "'" << std::endl;
     return -1;
   }
   Data2DCodec::Array2D phaseOffsets;
   Data2DCodec::ArrayBool2D invalidPixels;
   size_t size = p.tellg();
   size -= 4; // for uint16_t row, column
   p.seekg(0, std::ios::beg);
   p.clear();
   if(!p.good())
     return -1;
   p.read((char *)&rows, sizeof(uint16_t));
   p.read((char *)&columns, sizeof(uint16_t));
   p.seekg(0, std::ios::beg);
   p.clear();
   if(size == rows*columns*2)
   {
     phaseOffsets.resize(size/2 + 2); // int16_t data
     p.read((char *)phaseOffsets.data(), size + 4);
   }
   else if(size = rows*columns*3) // including invalid pixel boolean 2D array?
   {
     phaseOffsets.resize(size/3 + 2); // int16_t data
     invalidPixels.resize(size/3);
     p.read((char *)phaseOffsets.data(), (size*2)/3 + 4);
     p.read((char *)invalidPixels.data(), size/3);
   }
   p.close();
   Data2DCodec dc;
   Data2DCodec::ByteArray output;
   if(!dc.compress(phaseOffsets, invalidPixels, output))
   {
     logger(LOG_ERROR) << "Failed to compress phase offset data" << std::endl;
     return -1;
   }
   std::cout << "Total number of bytes in compressed format = " << output.size() << std::endl;
   OutputFileStream out(outputFileName, std::ios::out | std::ios::binary);
   if(!out.good())
   {
     logger(LOG_ERROR) << "Could not open output file '" << outputFileName << "'" << std::endl;
     return -1;
   }
   out.write((const char *)output.data(), output.size());
   out.close();
   if(!dc.decompress(output, phaseOffsets))
   {
     logger(LOG_ERROR) << "Failed to decompress phase offset data" << std::endl;
     return -1;
   }
   return 0;
 }
Variable Documentation
Vector<CSimpleOpt::SOption> argumentSpecifications
Initial value:
=
{
  { PHASE_OFFSET_FILE_NAME,  "-p", SO_REQ_SEP, "Phase offset input file name"},
  { OUTPUT_FILE_NAME,        "-o", SO_REQ_SEP, "Output file name"},
  SO_END_OF_OPTIONS
}
Definition at line 24 of file Data2DCodecTest.cpp.
Referenced by help(), and main().