Voxel: DFTTest.cpp File Reference
DFTTest.cpp File Reference
#include "DFT.h"
#include "SimpleOpt.h"
#include "Common.h"
#include "Logger.h"
#include <iomanip>
#include <fstream>
Classes
class BMP
Enumerations
enum Options {
VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2, CREATE_PROFILE = 3,
PARENT_PROFILE_ID = 4, PROFILE_ID = 5, SECTION = 6, PARAM_NAME = 7,
PARAM_VALUE = 8, LIST_PROFILES = 9, REMOVE_PROFILE = 10, WRITE_TO_EEPROM = 11,
SAVE_FILE_TO_HOST = 12, DUMP_FILE = 3, VENDOR_ID = 0, PRODUCT_ID = 1,
SERIAL_NUMBER = 2, DUMP_FILE = 3, NUM_OF_FRAMES = 4, VENDOR_ID = 0,
PRODUCT_ID = 1, SERIAL_NUMBER = 2, DUMP_FILE = 3, NUM_OF_FRAMES = 4,
PHASE_OFFSET_FILE_NAME = 0, OUTPUT_FILE_NAME = 3, INPUT_FILE_NAME = 0, OUTPUT_FILE_NAME = 1,
XML_FILE = 0, VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2,
FIRMWARE_FILE = 3, VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2,
DUMP_FILE = 3, NUM_OF_FRAMES = 4, VENDOR_ID = 0, PRODUCT_ID = 1,
SERIAL_NUMBER = 2, REGISTER = 3, READ = 4, WRITE = 5,
DATA = 6, LENGTH = 7, LSB = 8, MSB = 9,
VENDOR_ID = 0, PRODUCT_ID = 1, SERIAL_NUMBER = 2
}
Functions
void help ()
int main (int argc, char *argv[])
Variables
Vector< CSimpleOpt::SOption > argumentSpecifications
Enumeration Type Documentation
enum Options
Enumerator
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
CREATE_PROFILE
PARENT_PROFILE_ID
PROFILE_ID
SECTION
PARAM_NAME
PARAM_VALUE
LIST_PROFILES
REMOVE_PROFILE
WRITE_TO_EEPROM
SAVE_FILE_TO_HOST
DUMP_FILE
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
DUMP_FILE
NUM_OF_FRAMES
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
DUMP_FILE
NUM_OF_FRAMES
PHASE_OFFSET_FILE_NAME
OUTPUT_FILE_NAME
INPUT_FILE_NAME
OUTPUT_FILE_NAME
XML_FILE
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
FIRMWARE_FILE
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
DUMP_FILE
NUM_OF_FRAMES
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
REGISTER
READ
WRITE
DATA
LENGTH
LSB
MSB
VENDOR_ID
PRODUCT_ID
SERIAL_NUMBER
Definition at line 18 of file DFTTest.cpp.
 {
   INPUT_FILE_NAME = 0,
   OUTPUT_FILE_NAME = 1
 };
Function Documentation
void help ()
Definition at line 212 of file DFTTest.cpp.
References argumentSpecifications.
Referenced by main().
 {
   std::cout << "DFTTest v1.0" << std::endl;
   CSimpleOpt::SOption *option = argumentSpecifications.data();
   while(option->nId >= 0)
   {
     std::cout << option->pszArg << " " << option->helpInfo << std::endl;
     option++;
   }
 }
int main (int argc, char * argv[])
Definition at line 226 of file DFTTest.cpp.
References argumentSpecifications, Voxel::DFT::DFT2D(), Voxel::DFT::FORWARD, help(), INPUT_FILE_NAME, Voxel::LOG_DEBUG, Voxel::LOG_ERROR, Voxel::logger, OUTPUT_FILE_NAME, Voxel::DFT::REVERSE, and Voxel::Logger::setDefaultLogLevel().
 {
   CSimpleOpt s(argc, argv, argumentSpecifications);
   logger.setDefaultLogLevel(LOG_DEBUG);
   String inputFileName, outputFileName;
   char *endptr;
   while (s.Next())
   {
     if (s.LastError() != SO_SUCCESS)
     {
       std::cout << s.GetLastErrorText(s.LastError()) << ": '" << s.OptionText() << "' (use -h to get command line help)" << std::endl;
       help();
       return -1;
     }
     //std::cout << s.OptionId() << ": " << s.OptionArg() << std::endl;
     Vector<String> splits;
     switch (s.OptionId())
     {
       case INPUT_FILE_NAME:
         inputFileName = s.OptionArg();
         break;
       case OUTPUT_FILE_NAME:
         outputFileName = s.OptionArg();
         break;
       default:
         help();
         break;
     };
   }
   if(inputFileName.size() == 0 || outputFileName.size() == 0)
   {
     logger(LOG_ERROR) << "Required argument missing." << std::endl;
     help();
     return -1;
   }
   BMP bmp;
   Vector<int16_t> data;
   if(!bmp.read(inputFileName, data))
   {
     logger(LOG_ERROR) << "Failed to read '" << inputFileName << "'" << std::endl;
     return -1;
   }
   Complex2D c;
   c.resize(bmp.height);
   for(auto i = 0; i < bmp.height; i++)
   {
     c[i].resize(bmp.width);
     for(auto j = 0; j < bmp.width; j++)
     {
       c[i][j] = data[i*bmp.width + j];
     }
   }
   std::cout << "Width = " << bmp.width << ", height = " << bmp.height << std::endl;
   DFT dft;
   if(!dft.DFT2D(c, DFT::FORWARD))
   {
     logger(LOG_ERROR) << "Failed to compute DFT of '" << inputFileName << "'" << std::endl;
     return -1;
   }
   if(!dft.DFT2D(c, DFT::REVERSE))
   {
     logger(LOG_ERROR) << "Failed to compute IDFT of '" << inputFileName << "'" << std::endl;
     return -1;
   }
   for(auto i = 0; i < bmp.height; i++)
   {
     for(auto j = 0; j < bmp.width; j++)
     {
       int v = abs(c[i][j]);
       if(v > 255)
         data[i*bmp.width + j] = 255;
       else
         data[i*bmp.width + j] = v;
     }
   }
   if(!bmp.write(outputFileName, data))
   {
     logger(LOG_ERROR) << "Failed to write '" << outputFileName << "'" << std::endl;
     return -1;
   }
   return 0;
 }
Variable Documentation
Vector<CSimpleOpt::SOption> argumentSpecifications
Initial value:
=
{
  { INPUT_FILE_NAME,         "-i", SO_REQ_SEP, "Input image file name [Only BMP supported]"},
  { OUTPUT_FILE_NAME,        "-o", SO_REQ_SEP, "Output image file name [Only BMP supported]"},
  SO_END_OF_OPTIONS
}
Definition at line 205 of file DFTTest.cpp.
Referenced by help(), and main().