Voxel: Filter related classes
Filter related classes
Classes
class Voxel::Data2DCodec
This class is used for compressing and decompressing 16-bit signed data.
class Voxel::DFT
class Voxel::BilateralFilter
class Voxel::Filter
class Voxel::FilterDescription
class Voxel::FilterFactory
class Voxel::FilterParameter
class Voxel::FilterParameterTemplate< T >
class Voxel::FilterParameterRangeTemplate< T >
class Voxel::FilterParameterEnumTemplate< T >
class Voxel::BoolFilterParameter
class Voxel::FilterSet< FrameType >
class Voxel::FilterSetIterator< FrameType >
class Voxel::IIRFilter
class Voxel::MedianFilter
class Voxel::SmoothFilter
class Voxel::TemporalMedianFilter
class Voxel::VoxelFilterFactory
Typedefs
typedef Vector< ComplexDouble > Voxel::Complex1D
typedef Vector< Vector
< ComplexDouble > > Voxel::Complex2D
typedef Ptr< Filter > Voxel::FilterPtr
typedef Ptr< FilterFactory > Voxel::FilterFactoryPtr
typedef void(* Voxel::GetFilterFactory)(FilterFactoryPtr &filterFactory)
typedef Ptr< FilterParameter > Voxel::FilterParameterPtr
typedef Ptr< const
FilterParameter > Voxel::FilterParameterConstPtr
typedef
FilterParameterTemplate< bool > Voxel::BoolFilterParameterTemplate
typedef
FilterParameterTemplate< int > Voxel::IntegerFilterParameterTemplate
typedef
FilterParameterTemplate< uint > Voxel::UnsignedIntegerFilterParameterTemplate
typedef
FilterParameterTemplate< float > Voxel::FloatFilterParameterTemplate
typedef
FilterParameterRangeTemplate
< uint > Voxel::UnsignedFilterParameter
typedef
FilterParameterRangeTemplate
< int > Voxel::SignedFilterParameter
typedef
FilterParameterRangeTemplate
< float > Voxel::FloatFilterParameter
typedef
FilterParameterEnumTemplate
< int > Voxel::EnumFilterParameter
typedef
FilterParameterEnumTemplate
< bool > Voxel::BoolEnumFilterParameterTemplate
typedef BoolFilterParameter Voxel::StrobeBoolFilterParameter
Functions
void Voxel::getFilterFactory (FilterFactoryPtr &filterFactory)
bool Voxel::Filter::filter (const FramePtr &in, FramePtr &out)
FilterParameterConstPtr Voxel::Filter::getParam (const String &name) const
template<typename T >
bool Voxel::Filter::get (const String &name, T &value)
template<typename T >
bool Voxel::Filter::_get (const String &name, T &value)
template<typename T >
bool Voxel::Filter::set (const String &name, const T &value)
template<typename T >
bool Voxel::Filter::_set (const String &name, const T &value)
int Voxel::FilterSet< FrameType >::addFilter (FilterPtr p, int beforeFilterIndex=-1)
FilterPtr Voxel::FilterSet< FrameType >::getFilter (int index) const
bool Voxel::FilterSet< FrameType >::removeFilter (int index)
bool Voxel::FilterSet< FrameType >::removeAllFilters ()
bool Voxel::FilterSet< FrameType >::applyFilter (FrameSequence &seq)
void Voxel::FilterSet< FrameType >::reset ()
Voxel::FilterSetIterator< FrameType >::FilterSetIterator (const FilterSet< FrameType > &s, int i=0)
FilterSetIterator & Voxel::FilterSetIterator< FrameType >::operator++ (int)
FilterSetIterator & Voxel::FilterSetIterator< FrameType >::operator++ ()
const FilterPtr Voxel::FilterSetIterator< FrameType >::operator* ()
bool Voxel::FilterSetIterator< FrameType >::operator!= (const FilterSetIterator &other) const
bool Voxel::FilterSetIterator< FrameType >::operator== (const FilterSetIterator &other) const
Detailed Description
Typedef Documentation
typedef FilterParameterEnumTemplate<bool> Voxel::BoolEnumFilterParameterTemplate
Definition at line 165 of file FilterParameter.h.
typedef FilterParameterTemplate<bool> Voxel::BoolFilterParameterTemplate
Definition at line 71 of file FilterParameter.h.
typedef Vector<ComplexDouble> Voxel::Complex1D
Definition at line 26 of file DFT.h.
typedef Vector<Vector<ComplexDouble> > Voxel::Complex2D
Definition at line 27 of file DFT.h.
typedef FilterParameterEnumTemplate<int> Voxel::EnumFilterParameter
Definition at line 163 of file FilterParameter.h.
typedef Ptr<FilterFactory> Voxel::FilterFactoryPtr
Definition at line 63 of file FilterFactory.h.
typedef Ptr<const FilterParameter> Voxel::FilterParameterConstPtr
Definition at line 37 of file FilterParameter.h.
typedef Ptr<FilterParameter> Voxel::FilterParameterPtr
Definition at line 36 of file FilterParameter.h.
typedef Ptr<Filter> Voxel::FilterPtr
Definition at line 188 of file Filter.h.
typedef FilterParameterRangeTemplate<float> Voxel::FloatFilterParameter
Definition at line 118 of file FilterParameter.h.
typedef FilterParameterTemplate<float> Voxel::FloatFilterParameterTemplate
Definition at line 74 of file FilterParameter.h.
typedef void(* Voxel::GetFilterFactory)(FilterFactoryPtr &filterFactory)
Definition at line 70 of file FilterFactory.h.
typedef FilterParameterTemplate<int> Voxel::IntegerFilterParameterTemplate
Definition at line 72 of file FilterParameter.h.
typedef FilterParameterRangeTemplate<int> Voxel::SignedFilterParameter
Definition at line 117 of file FilterParameter.h.
typedef BoolFilterParameter Voxel::StrobeBoolFilterParameter
Definition at line 191 of file FilterParameter.h.
typedef FilterParameterRangeTemplate<uint> Voxel::UnsignedFilterParameter
Definition at line 116 of file FilterParameter.h.
typedef FilterParameterTemplate<uint> Voxel::UnsignedIntegerFilterParameterTemplate
Definition at line 73 of file FilterParameter.h.
Function Documentation
template<typename T > bool Voxel::Filter::_get (const String & name, T & value) protected
Definition at line 128 of file Filter.h.
References Voxel::Filter::_parameters, Voxel::FilterParameterTemplate< T >::get(), Voxel::LOG_ERROR, Voxel::logger, and Voxel::Filter::name().
Referenced by Voxel::BilateralFilter::_onSet(), Voxel::TemporalMedianFilter::_onSet(), Voxel::SmoothFilter::_onSet(), Voxel::MedianFilter::_onSet(), Voxel::IIRFilter::_onSet(), and Voxel::Filter::get().
 {
   auto p = _parameters.find(name);
   if(p != _parameters.end())
   {
     FilterParameterTemplate<T> *f = dynamic_cast<FilterParameterTemplate<T> *>(p->second.get());
     if(!f)
     {
       logger(LOG_ERROR) << "Filter: Invalid type '" << typeid(value).name() << "' to get parameter '" << name << "'" << std::endl;
       return false;
     }
     return f->get(value);
   }
   else
   {
     logger(LOG_ERROR) << "Filter: Unknown parameter name '" << name << "'" << std::endl;
     return false;
   }
 }
template<typename T > bool Voxel::Filter::_set (const String & name, const T & value) protected
Definition at line 159 of file Filter.h.
References Voxel::Filter::_onSet(), Voxel::Filter::_parameters, Voxel::LOG_ERROR, Voxel::logger, Voxel::Filter::name(), and Voxel::FilterParameterTemplate< T >::set().
Referenced by Voxel::MedianFilter::_filter(), and Voxel::Filter::set().
 {
   auto p = _parameters.find(name);
   if(p != _parameters.end())
   {
     FilterParameterTemplate<T> *f = dynamic_cast<FilterParameterTemplate<T> *>(p->second.get());
     if(!f)
     {
       logger(LOG_ERROR) << "Filter: Invalid type '" << typeid(value).name() << "' to get parameter '" << name << "'" << std::endl;
       return false;
     }
     if(f->set(value))
     {
       _onSet(p->second);
       return true;
     }
     else
       return false;
   }
   else
   {
     logger(LOG_ERROR) << "Filter: Unknown parameter name '" << name << "'" << std::endl;
     return false;
   }
 }
template<typename FrameType > int Voxel::FilterSet< FrameType >::addFilter (FilterPtr p, int beforeFilterIndex = -1)
Definition at line 93 of file FilterSet.h.
 {
   Lock<Mutex> _(_accessMutex);
   if( beforeFilterIndex == -1)
     _indices.push_back(_filterCounter);
   else
   {
     auto found = -1;
     for(auto i = 0; i < _indices.size(); i++)
       if(_indices[i] == beforeFilterIndex)
         found = i;
     if(found < 0)
       return -1; // -1 => invalid filter index
     _indices.insert(_indices.begin() + found, _filterCounter);
   }
   _filters[_filterCounter] = p;
   _frameBufferManager.setMinimumBufferCount(_frameBufferManager.getMinimumBufferCount() + 1);
   int i = _filterCounter;
   _filterCounter++;
   return i;
 }
template<typename FrameType > bool Voxel::FilterSet< FrameType >::applyFilter (FrameSequence & seq)
Definition at line 176 of file FilterSet.h.
References Voxel::LOG_ERROR, and Voxel::logger.
 {
   Lock<Mutex> _(_accessMutex);
   if(seq.size() < 1)
   {
     logger(LOG_ERROR) << "Require atleast one frame in the sequence, to apply filters" << std::endl;
     return false;
   }
   for(auto f: *this)
   {
     auto g = _frameBufferManager.get();
     FramePtr p = std::dynamic_pointer_cast<Frame>(*g);
     if(!f->filter(std::dynamic_pointer_cast<Frame>(**seq.begin()), p))
     {
       logger(LOG_ERROR) << "FilterSet: Could not apply filter '" << f->name() << "'" << std::endl;
       return false;
     }
     *g = std::dynamic_pointer_cast<FrameType>(p);
     if(!*g)
     {
       logger(LOG_ERROR) << "FilterSet: Got an invalid frame from filter '" << f->name() << "'" << std::endl;
       return false;
     }
     seq.push_front(g);
   }
   return true;
 }
bool Voxel::Filter::filter (const FramePtr & in, FramePtr & out) inline
Definition at line 100 of file Filter.h.
References Voxel::Filter::_accessMutex, and Voxel::Filter::_filter().
 {
   Lock<Mutex> _(_accessMutex);
   return _filter(in, out);
 }
template<typename FrameType > Voxel::FilterSetIterator< FrameType >::FilterSetIterator (const FilterSet< FrameType > & s, int i = 0)
Definition at line 219 of file FilterSet.h.
References Voxel::FilterSet< FrameType >::_indices, and Voxel::FilterSetIterator< FrameType >::index.
                                                                                    : s(s), i(i)
 {
   if(i < s._indices.size())
     index = s._indices[i];
 }
template<typename T > bool Voxel::Filter::get (const String & name, T & value)
Definition at line 121 of file Filter.h.
References Voxel::Filter::_accessMutex, and Voxel::Filter::_get().
 {
   Lock<Mutex> _(_accessMutex);
   return _get(name, value);
 }
template<typename FrameType > FilterPtr Voxel::FilterSet< FrameType >::getFilter (int index) const
Definition at line 124 of file FilterSet.h.
References LensCalibrationTest::x.
 {
   Lock<Mutex> _(_accessMutex);
   auto x = _filters.find(index);
   if(x != _filters.end())
     return x->second;
   else
     return nullptr;
 }
void Voxel::getFilterFactory (FilterFactoryPtr & filterFactory)
FilterParameterConstPtr Voxel::Filter::getParam (const String & name) const inline
Definition at line 107 of file Filter.h.
References Voxel::Filter::_accessMutex, and Voxel::Filter::_parameters.
 {
   Lock<Mutex> _(_accessMutex);
   auto p = _parameters.find(name);
   if(p != _parameters.end())
     return std::const_pointer_cast<const FilterParameter>(p->second);
   else
     return nullptr;
 }
template<typename FrameType > bool Voxel::FilterSetIterator< FrameType >::operator!= (const FilterSetIterator< FrameType > & other) const inline
Definition at line 259 of file FilterSet.h.
 {
   return !operator==(other);
 }
template<typename FrameType > const FilterPtr Voxel::FilterSetIterator< FrameType >::operator* () inline
Definition at line 248 of file FilterSet.h.
 {
   if(i < s._indices.size())
   {
     return s._filters.at(index);
   }
   else
     return nullptr;
 }
template<typename FrameType > FilterSetIterator< FrameType > & Voxel::FilterSetIterator< FrameType >::operator++ (int) inline
Definition at line 226 of file FilterSet.h.
 {
   i++;
   if(i < s._indices.size())
     index = s._indices[i];
   return *this;
 }
template<typename FrameType > FilterSetIterator< FrameType > & Voxel::FilterSetIterator< FrameType >::operator++ () inline
Definition at line 237 of file FilterSet.h.
 {
   i++;
   if(i < s._indices.size())
     index = s._indices[i];
   return *this;
 }
template<typename FrameType > bool Voxel::FilterSetIterator< FrameType >::operator== (const FilterSetIterator< FrameType > & other) const inline
Definition at line 265 of file FilterSet.h.
References Voxel::FilterSetIterator< FrameType >::i, and Voxel::FilterSetIterator< FrameType >::s.
 {
   return (&s == &other.s) && (i == other.i);
 }
template<typename FrameType > bool Voxel::FilterSet< FrameType >::removeAllFilters ()
Definition at line 164 of file FilterSet.h.
 {
   Lock<Mutex> _(_accessMutex);
   _frameBufferManager.setMinimumBufferCount(_frameBufferManager.getMinimumBufferCount() - _filters.size());
   _filters.clear();
   _indices.clear();
   return true;
 }
template<typename FrameType > bool Voxel::FilterSet< FrameType >::removeFilter (int index)
Definition at line 138 of file FilterSet.h.
References LensCalibrationTest::x.
 {
   Lock<Mutex> _(_accessMutex);
   auto x = _filters.find(index);
   if(x != _filters.end())
   {
     for(auto i = 0; i < _indices.size(); i++)
     {
       if(_indices[i] == index)
       {
         _indices.erase(_indices.begin() + i);
         break;
       }
     }
     _filters.erase(x);
     _frameBufferManager.setMinimumBufferCount(_frameBufferManager.getMinimumBufferCount() - 1);
     return true;
   }
   return false;
 }
template<typename FrameType > void Voxel::FilterSet< FrameType >::reset ()
Definition at line 212 of file FilterSet.h.
 {
   for(auto f: *this)
     f->reset();
 }
template<typename T > bool Voxel::Filter::set (const String & name, const T & value)
Definition at line 152 of file Filter.h.
References Voxel::Filter::_accessMutex, and Voxel::Filter::_set().
 {
   Lock<Mutex> _(_accessMutex);
   return _set(name, value);
 }