Voxel: CameraSystemTest Namespace Reference
CameraSystemTest Namespace Reference
Functions
def callback
Variables
tuple sys = Voxel.CameraSystem()
tuple devices = sys.scan()
int count = 0
gdepthCamera = None
pcframe = None
gframe = None
tuple frameSize = Voxel.FrameSize()
Function Documentation
def CameraSystemTest.callback (depthCamera, frame, type)
Definition at line 27 of file CameraSystemTest.py.
References Voxel::PointCloudFrame.typeCast().
 def callback(depthCamera, frame, type):
   print 'Hello'
   print depthCamera
   print frame
   #print frame.id, '@', frame.timestamp
   global count
   print count
   count = count + 1
   global gdepthCamera, pcframe, gframe
   #gdepthCamera.start()
   #gdepthCamera.stop()
   #gdepthCamera.start()
   if count > 100:
     gdepthCamera.stop()
     #del gdepthCamera
     pcframe = Voxel.PointCloudFrame.typeCast(frame)
     gframe = frame
     return
Variable Documentation
int CameraSystemTest.count = 0
Definition at line 17 of file CameraSystemTest.py.
tuple CameraSystemTest.devices = sys.scan()
Definition at line 12 of file CameraSystemTest.py.
Referenced by Voxel::CLIManager._connect(), Voxel::CLIManager._connectCompletion(), Voxel::TI::Voxel14Camera._init(), Voxel::TI::VoxelDCamera._init(), Voxel::USBSystemPrivate._iterateUDevUSB(), Voxel::CLIManager._list(), Voxel::CameraSystem.addDepthCameraFactory(), Voxel::CameraSystem.addDownloaderFactory(), Voxel::CLIManager.CLIManager(), Voxel::USBSystemPrivate.getDeviceNode(), Voxel::USBSystem.getDevices(), Voxel::USBSystemPrivate.getDevices(), Voxel::USBDevice.getDevices(), Voxel::CameraSystem.getProgrammableDevices(), main(), and Voxel::CameraSystem.scan().
tuple CameraSystemTest.frameSize = Voxel.FrameSize()
Definition at line 52 of file CameraSystemTest.py.
Referenced by Voxel::TI::ToFCamera._initStartParams(), and Voxel::TI::ToFFrameGenerator.setParameters().
tuple CameraSystemTest.gdepthCamera = None
Definition at line 21 of file CameraSystemTest.py.
CameraSystemTest.gframe = None
Definition at line 25 of file CameraSystemTest.py.
CameraSystemTest.pcframe = None
Definition at line 23 of file CameraSystemTest.py.
tuple CameraSystemTest.sys = Voxel.CameraSystem()
Definition at line 10 of file CameraSystemTest.py.
Referenced by Voxel::USBDeviceScanner._scan(), main(), and Voxel::UVCPrivate.UVCPrivate().