Voxel: Voxel::DataPacket Struct Reference
Voxel::DataPacket Struct Reference
#include <DataPacket.h>
Public Member Functions
DataPacket ()
bool readHeader (SerializedObject &in)
bool readHeader (InputStream &in)
bool read (SerializedObject &in)
bool read (InputStream &in)
bool write (SerializedObject &out)
bool write (OutputStream &out)
bool verifyMagic ()
Public Attributes
char magic [6]
uint8_t type
uint32_t size
SerializedObject object
Detailed Description
Definition at line 18 of file DataPacket.h.
Constructor & Destructor Documentation
Voxel::DataPacket::DataPacket () inline
Definition at line 28 of file DataPacket.h.
 { strcpy(magic, "VOXEL"); }
Member Function Documentation
bool Voxel::DataPacket::read (SerializedObject & in)
Definition at line 56 of file DataPacket.cpp.
References Voxel::SerializedObject::currentGetOffset(), Voxel::SerializedObject::get(), readHeader(), size, and Voxel::SerializedObject::size().
Referenced by Voxel::FrameStreamReader::_getPacket(), and Voxel::MainConfigurationFile::readFromHardware().
 {
   if(!readHeader(in))
     return false;
   if((in.size() - in.currentGetOffset()) < size)
     return false;
   object.resize(size);
   in.get((char *)object.getBytes().data(), size);
   return true;
 }
bool Voxel::DataPacket::read (InputStream & in)
Definition at line 42 of file DataPacket.cpp.
References readHeader(), and size.
 {
   if(!readHeader(in))
     return false;
   object.resize(size);
   in.read((char *)object.getBytes().data(), size);
   if(in.fail() | in.bad())
     return false;
   return true;
 }
bool Voxel::DataPacket::readHeader (SerializedObject & in)
Definition at line 86 of file DataPacket.cpp.
References Voxel::SerializedObject::currentGetOffset(), Voxel::SerializedObject::get(), magic, size, Voxel::SerializedObject::size(), and type.
Referenced by Voxel::FrameStreamReader::_init(), and read().
 {
   if((in.size() - in.currentGetOffset()) < 5 + sizeof(type) + sizeof(size))
     return false;
   in.get(magic, 5);
   in.get((char *)&type, sizeof(type));
   in.get((char *)&size, sizeof(size));
   return true;
 }
bool Voxel::DataPacket::readHeader (InputStream & in)
Definition at line 71 of file DataPacket.cpp.
References magic, size, and type.
 {
   if(!in.good())
     return false;
   in.read(magic, 5);
   in.read((char *)&type, sizeof(type));
   in.read((char *)&size, sizeof(size));
   if(in.fail() | in.bad())
     return false;
   return true;
 }
bool Voxel::DataPacket::verifyMagic () inline
Definition at line 39 of file DataPacket.h.
Referenced by Voxel::FrameStreamReader::_getPacket(), and Voxel::FrameStreamReader::_init().
 { return magic[0] == 'V' && magic[1] == 'O' && magic[2] == 'X' && magic[3] == 'E' && magic[4] == 'L'; }
bool Voxel::DataPacket::write (SerializedObject & out)
Definition at line 28 of file DataPacket.cpp.
References Voxel::SerializedObject::currentPutOffset(), magic, Voxel::SerializedObject::put(), size, Voxel::SerializedObject::size(), and type.
Referenced by Voxel::ConfigurationFile::_serializeAllDataFiles(), Voxel::FrameStreamWriter::write(), Voxel::FrameStreamWriter::writeGeneratorConfiguration(), and Voxel::MainConfigurationFile::writeToHardware().
 {
   if(out.size() - out.currentPutOffset() < 5 + sizeof(type) + sizeof(size) + size)
     return false;
   out.put(magic, 5);
   out.put((const char *)&type, sizeof(type));
   out.put((const char *)&size, sizeof(size));
   out.put((const char *)object.getBytes().data(), size);
   return true;
 }
bool Voxel::DataPacket::write (OutputStream & out)
Definition at line 12 of file DataPacket.cpp.
References magic, size, and type.
 {
   if(!out.good())
     return false;
   out.write(magic, 5);
   out.write((const char *)&type, sizeof(type));
   out.write((const char *)&size, sizeof(size));
   out.write((const char *)object.getBytes().data(), size);
   if(out.fail() | out.bad())
     return false;
   return true;
 }
Member Data Documentation
char Voxel::DataPacket::magic[6]
Definition at line 20 of file DataPacket.h.
Referenced by readHeader(), and write().
SerializedObject Voxel::DataPacket::object
Definition at line 26 of file DataPacket.h.
Referenced by Voxel::FrameStreamReader::_readConfigPacket(), Voxel::ConfigurationFile::_serializeAllDataFiles(), Voxel::MainConfigurationFile::readFromHardware(), Voxel::FrameStreamReader::readNext(), Voxel::FrameStreamWriter::write(), Voxel::FrameStreamWriter::writeGeneratorConfiguration(), and Voxel::MainConfigurationFile::writeToHardware().
uint32_t Voxel::DataPacket::size
Definition at line 24 of file DataPacket.h.
Referenced by Voxel::FrameStreamReader::_init(), Voxel::ConfigurationFile::_serializeAllDataFiles(), read(), readHeader(), write(), Voxel::FrameStreamWriter::write(), Voxel::FrameStreamWriter::writeGeneratorConfiguration(), and Voxel::MainConfigurationFile::writeToHardware().
uint8_t Voxel::DataPacket::type
Definition at line 22 of file DataPacket.h.
Referenced by Voxel::FrameStreamReader::_init(), Voxel::FrameStreamReader::_readConfigPacket(), Voxel::ConfigurationFile::_serializeAllDataFiles(), Voxel::MainConfigurationFile::readFromHardware(), readHeader(), write(), Voxel::FrameStreamWriter::write(), Voxel::FrameStreamWriter::writeGeneratorConfiguration(), and Voxel::MainConfigurationFile::writeToHardware().
The documentation for this struct was generated from the following files:
DataPacket.h
DataPacket.cpp